import QuantumZipper.Proofs.Section5.TVLocal
import Mathlib.MeasureTheory.Measure.MeasuredSets
import Mathlib.MeasureTheory.SetAlgebra
import Mathlib.Probability.Kernel.Composition.MapComap

/-!
# D3⁺(i): measurability of the total variation distance of a kernel

Task D3P-I (decision D23). For the conditioning layer of D3⁺(i) we need `ω ↦ d_TV(κ (F ω), ν)`
to be measurable. On a countably generated space the supremum defining `TV.tvDist` may be taken
over the countable algebra of sets generated by a countable generating family (every measurable
set is approximated in `κ x + ν`-measure by sets of the algebra: mathlib's
`exists_measure_symmDiff_lt_of_generateFrom_isSetRing`). Standard measure theory; own Lean proof
(the approximation step is Halmos, *Measure Theory*, §13 Thm. D).

* `tvDist_eq_iSup_algebra`: `tvDist μ ν` is the supremum over the countable generated algebra.
* `measurable_tvDist_kernel`: `x ↦ tvDist (κ x) ν` is measurable for a finite kernel `κ`.
* `measurable_map_section`: `f ↦ μ.map (T (·, f))` is measurable (a kernel) for jointly
  measurable `T`.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Set MeasurableSpace
open scoped Topology ENNReal symmDiff

namespace QuantumZipper
namespace D3Plus

variable {E : Type*} [MeasurableSpace E] [CountablyGenerated E]

/-- The countable algebra generated by the countable generating family of `E`. -/
def tvAlg (E : Type*) [MeasurableSpace E] [CountablyGenerated E] : Set (Set E) :=
  generateSetAlgebra (countableGeneratingSet E)

theorem countable_tvAlg : (tvAlg E).Countable :=
  countable_generateSetAlgebra countable_countableGeneratingSet

theorem generateFrom_tvAlg : generateFrom (tvAlg E) = ‹MeasurableSpace E› := by
  rw [tvAlg, generateFrom_generateSetAlgebra_eq, generateFrom_countableGeneratingSet]

theorem measurableSet_of_mem_tvAlg {t : Set E} (ht : t ∈ tvAlg E) : MeasurableSet t := by
  rw [← generateFrom_tvAlg (E := E)]; exact measurableSet_generateFrom ht

/-- One half of the approximation: `μ s − ν s ≤ sup_{t ∈ 𝒜} (μ t − ν t) ⊔ (ν t − μ t)`. -/
theorem sub_le_iSup_tvAlg (μ ν : Measure E) [IsFiniteMeasure μ] [IsFiniteMeasure ν]
    {s : Set E} (hs : MeasurableSet s) :
    μ s - ν s ≤ ⨆ t ∈ tvAlg E, (μ t - ν t) ⊔ (ν t - μ t) := by
  set D := ⨆ t ∈ tvAlg E, (μ t - ν t) ⊔ (ν t - μ t)
  refine ENNReal.le_of_forall_pos_le_add fun ε hε _ => ?_
  have hε' : (0 : ℝ≥0∞) < ε / 2 := ENNReal.half_pos (by exact_mod_cast hε.ne')
  have hA := isSetAlgebra_generateSetAlgebra (𝒜 := countableGeneratingSet E)
  obtain ⟨t, ht, hts⟩ := exists_measure_symmDiff_lt_of_generateFrom_isSetRing (μ := μ + ν)
    hA.isSetRing ⟨{univ}, countable_singleton _, singleton_subset_iff.2 hA.univ_mem, by simp⟩
    (generateFrom_tvAlg (E := E)).symm hs hε'
  have hμ : μ (t ∆ s) ≤ ε / 2 := (le_add_right le_rfl).trans (Measure.add_apply μ ν _ ▸ hts.le)
  have hν : ν (t ∆ s) ≤ ε / 2 := (le_add_left le_rfl).trans (Measure.add_apply μ ν _ ▸ hts.le)
  have h1 : μ s ≤ μ t + ε / 2 := by
    calc μ s ≤ μ (t ∪ t ∆ s) := measure_mono fun x hx => by
            by_cases hxt : x ∈ t
            · exact Or.inl hxt
            · exact Or.inr (Or.inr ⟨hx, hxt⟩)
      _ ≤ μ t + μ (t ∆ s) := measure_union_le _ _
      _ ≤ μ t + ε / 2 := by gcongr
  have h2 : ν t ≤ ν s + ε / 2 := by
    calc ν t ≤ ν (s ∪ t ∆ s) := measure_mono fun x hx => by
            by_cases hxs : x ∈ s
            · exact Or.inl hxs
            · exact Or.inr (Or.inl ⟨hx, hxs⟩)
      _ ≤ ν s + ν (t ∆ s) := measure_union_le _ _
      _ ≤ ν s + ε / 2 := by gcongr
  have hD : μ t - ν t ≤ D := le_iSup₂_of_le t ht le_sup_left
  rw [tsub_le_iff_left]
  calc μ s ≤ μ t + ε / 2 := h1
    _ ≤ (ν t + (μ t - ν t)) + ε / 2 := by gcongr; exact le_add_tsub
    _ ≤ (ν s + ε / 2 + D) + ε / 2 := by gcongr
    _ = ν s + (D + (ε / 2 + ε / 2)) := by ring
    _ = ν s + (D + ε) := by rw [ENNReal.add_halves]

/-- **The TV distance is a supremum over the countable generated algebra.** -/
theorem tvDist_eq_iSup_tvAlg (μ ν : Measure E) [IsFiniteMeasure μ] [IsFiniteMeasure ν] :
    TV.tvDist μ ν = ⨆ t ∈ tvAlg E, (μ t - ν t) ⊔ (ν t - μ t) := by
  refine le_antisymm (iSup₂_le fun s hs => sup_le (sub_le_iSup_tvAlg μ ν hs) ?_)
    (iSup₂_le fun t ht => le_iSup₂_of_le t (measurableSet_of_mem_tvAlg ht) le_rfl)
  have := sub_le_iSup_tvAlg ν μ hs
  refine this.trans (iSup₂_le fun t ht => le_iSup₂_of_le t ht ?_)
  rw [sup_comm]

/-- **Measurability of the TV distance to a fixed law, along a finite kernel.** -/
theorem measurable_tvDist_kernel {T : Type*} [MeasurableSpace T] (κ : Kernel T E)
    [IsFiniteKernel κ] (ν : Measure E) [IsFiniteMeasure ν] :
    Measurable fun x => TV.tvDist (κ x) ν := by
  simp_rw [tvDist_eq_iSup_tvAlg]
  refine Measurable.biSup _ countable_tvAlg fun t ht => ?_
  have hκ := κ.measurable_coe (measurableSet_of_mem_tvAlg ht)
  exact (hκ.sub measurable_const).sup (measurable_const.sub hκ)

omit [CountablyGenerated E] in
/-- For jointly measurable `T`, `f ↦ μ.map (T (·, f))` is measurable. -/
theorem measurable_map_section {S T' : Type*} [MeasurableSpace S] [MeasurableSpace T']
    (μ : Measure S) [SFinite μ] {Tm : S × T' → E} (hT : Measurable Tm) :
    Measurable fun f : T' => μ.map fun s => Tm (s, f) := by
  refine Measure.measurable_of_measurable_coe _ fun A hA => ?_
  have hsl : ∀ f : T', Measurable fun s => Tm (s, f) := fun f =>
    hT.comp (measurable_id.prodMk measurable_const)
  simp_rw [Measure.map_apply (hsl _) hA]
  have hset : MeasurableSet {q : T' × S | Tm (q.2, q.1) ∈ A} :=
    (hT.comp measurable_swap) hA
  exact measurable_measure_prodMk_left hset

example : CountablyGenerated (ℕ → ℝ) := inferInstance

end D3Plus
end QuantumZipper
