import QuantumZipper.Proofs.Zipper.E5Final2
import QuantumZipper.Proofs.Zipper.Cor15MarkovField

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# E5-REPR-FINAL, part c: the Q-law facts of the level-space zoom model

Task E5-REPR-FINAL (Theorem 1.3, node E5, decision D39); Sheffield, arXiv:1012.4797, §5.4
(pp. 66–72, proof of Lemma 5.6: the auxiliary field is an independent free field).

On the level space `(Ω₁, Q) = ((ℝ≥0 × NS(P)) × Ω', (𝐑.withDensity w) ⊗ P')` of
`E5ESM6.lhsF_eq_levelModel` (equivalently `(𝐑 ⊗ P').withDensity (w ∘ fst)`, the form
`Rr₁.withDensity w₁` of `E5Repair7.e5_level_repr'`), the field `X' = Y ∘ snd` (`Y` a free field
under `P'`, e.g. `Y = regField ϖ ρ₀ ∘ X₁`) is a free field under `Q`, and the level point
`Ξ = fst` is independent of its balanced increments. These are the hypotheses `hXf`, `hindBase`
of `E5Final2.zoomModel_lvl` (`lvlField_isFreeGFF`, `lvlXi_indep_lvlField`).

Proofs: the law of `Y ∘ snd` under a product with a probability first factor is the law of `Y`
(`Cor15Group.isFreeGFFModConstH_of_map_eq`), and the two coordinates of a product measure are
independent (mathlib's `indepFun_prod`). Own elementary bookkeeping.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Set
open scoped NNReal ENNReal

namespace QuantumZipper
namespace E5

section General

variable {A Ω' : Type} [MeasurableSpace A] [MeasurableSpace Ω'] {P' : Measure Ω'}
  [IsProbabilityMeasure P'] {Y : Ω' → FieldSample}

/-- A density with total mass `1` gives a probability measure. -/
theorem isProbMeas_withDensity_e5f5 {μ : Measure A} {w : A → ℝ≥0∞}
    (hw1 : ∫⁻ a, w a ∂μ = 1) : IsProbabilityMeasure (μ.withDensity w) :=
  ⟨by rw [withDensity_apply _ MeasurableSet.univ, Measure.restrict_univ]; exact hw1⟩

/-- **A free field on the second factor is a free field on the product.** -/
theorem isFreeGFFModConstH_snd_prod {ν : Measure A} [IsProbabilityMeasure ν]
    (hY : IsFreeGFFModConstH Y P') :
    IsFreeGFFModConstH (fun z : A × Ω' => Y z.2) (ν.prod P') := by
  have hYm : Measurable Y := measurable_pi_iff.2 hY.measurable_coord
  refine Cor15Group.isFreeGFFModConstH_of_map_eq
    (fun m => (hY.measurable_coord m).comp measurable_snd) ?_ hY
  rw [show (fun z : A × Ω' => Y z.2) = Y ∘ Prod.snd from rfl,
    ← Measure.map_map hYm measurable_snd, Measure.map_snd_prod, measure_univ, one_smul]

omit [MeasurableSpace A] [IsProbabilityMeasure P'] in
/-- The balanced-increment σ-algebra of `Y ∘ snd` is generated by the second coordinate. -/
theorem freeIncrSigma_snd_le (hY : IsFreeGFFModConstH Y P') :
    K3.freeIncrSigma (fun z : A × Ω' => Y z.2) ≤
      MeasurableSpace.comap (Prod.snd : A × Ω' → Ω') inferInstance := by
  set F : Ω' → ({p : Measure ℂ × Measure ℂ //
      IsAdmissibleH p.1 ∧ IsAdmissibleH p.2 ∧ p.1 Set.univ = p.2 Set.univ} → ℝ) :=
    fun ω' p => Y ω' p.1.1 - Y ω' p.1.2 with hF
  have hFm : Measurable F :=
    measurable_pi_iff.2 fun p => (hY.measurable_coord _).sub (hY.measurable_coord _)
  have e : K3.freeIncrSigma (fun z : A × Ω' => Y z.2) =
      MeasurableSpace.comap (F ∘ Prod.snd) MeasurableSpace.pi := rfl
  rw [e, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono hFm.comap_le

/-- **The first coordinate is independent of the balanced increments of `Y ∘ snd`** under a
product measure. -/
theorem indep_fst_freeIncrSigma_snd {ν : Measure A} [IsProbabilityMeasure ν]
    (hY : IsFreeGFFModConstH Y P') :
    Indep (MeasurableSpace.comap (Prod.fst : A × Ω' → A) inferInstance)
      (K3.freeIncrSigma (fun z : A × Ω' => Y z.2)) (ν.prod P') := by
  have h := (IndepFun_iff_Indep _ _ _).1
    (indepFun_prod (μ := ν) (ν := P') (X := (id : A → A)) (Y := (id : Ω' → Ω')) measurable_id
      measurable_id)
  exact indep_of_indep_of_le_right h (freeIncrSigma_snd_le hY)

end General

/-! ## The level space -/

section Level

variable {Ω : Type} [MeasurableSpace Ω] {P : Measure Ω}
  {Ω' : Type} [MeasurableSpace Ω'] {P' : Measure Ω'} [IsProbabilityMeasure P']

/-- The two forms of the level measure. -/
theorem lvl_measure_eq {μ : Measure (ℝ≥0 × NullMeasurableSpace Ω P)} [SFinite μ]
    {w : ℝ≥0 × NullMeasurableSpace Ω P → ℝ≥0∞} (hw : Measurable w) :
    (μ.prod P').withDensity (fun z => w z.1) = (μ.withDensity w).prod P' :=
  (prod_withDensity_left hw).symm

/-- **`hXf` of `zoomModel_lvl`**: the D28 level field is a free field under the level measure. -/
theorem lvlField_isFreeGFF {ϖ ρ₀ : Measure ℂ} {X₁ : Ω' → FieldSample}
    (hY : IsFreeGFFModConstH (fun ω' => regField ϖ ρ₀ (X₁ ω')) P')
    {μ : Measure (ℝ≥0 × NullMeasurableSpace Ω P)} [IsProbabilityMeasure μ]
    {w : ℝ≥0 × NullMeasurableSpace Ω P → ℝ≥0∞} (hw : Measurable w) (hw1 : ∫⁻ a, w a ∂μ = 1) :
    IsFreeGFFModConstH (lvlField (Ω := Ω) (P := P) (Ω' := Ω') ϖ ρ₀ X₁)
      ((μ.prod P').withDensity (fun z => w z.1)) := by
  have := isProbMeas_withDensity_e5f5 hw1
  rw [lvl_measure_eq hw]
  exact isFreeGFFModConstH_snd_prod hY

/-- **`hindBase` of `zoomModel_lvl`**: the level point is independent of the balanced
increments of the D28 level field under the level measure. -/
theorem lvlXi_indep_lvlField {ϖ ρ₀ : Measure ℂ} {X₁ : Ω' → FieldSample}
    (hY : IsFreeGFFModConstH (fun ω' => regField ϖ ρ₀ (X₁ ω')) P')
    {μ : Measure (ℝ≥0 × NullMeasurableSpace Ω P)} [IsProbabilityMeasure μ]
    {w : ℝ≥0 × NullMeasurableSpace Ω P → ℝ≥0∞} (hw : Measurable w) (hw1 : ∫⁻ a, w a ∂μ = 1) :
    Indep (MeasurableSpace.comap
        (lvlXi : lvl Ω P Ω' → ℝ≥0 × NullMeasurableSpace Ω P) inferInstance)
      (K3.freeIncrSigma (lvlField (Ω := Ω) (P := P) (Ω' := Ω') ϖ ρ₀ X₁))
      ((μ.prod P').withDensity (fun z => w z.1)) := by
  have := isProbMeas_withDensity_e5f5 hw1
  rw [lvl_measure_eq hw]
  exact indep_fst_freeIncrSigma_snd hY

end Level

end E5
end QuantumZipper
