import QuantumZipper.Proofs.Zipper.LocRichE6

/-!
# E6-LOCABS, reductions: B5 locality for `locRich` and the measurability of the unzipped data

Theorem 1.3, node E6 under decision D25 (`DECISIONS.md`). The inputs of
`E6.e6_concrete_gen D3Plus.locRich` and of `E6.theorem1_3_of_nodes_rich` include B5 locality
`LocalAbs … locRich Reg` and `UnzipMeasStmt`. This file proves the measure-theoretic reductions
around them (own elementary arguments; the paper, Sheffield arXiv:1012.4797 §5.4, pp. 70–72,
only asserts the locality):

* `exists_measurable_factor_fullData`: Doob–Dynkin for `FullData`-valued maps (coordinatewise,
  from mathlib's `StronglyMeasurable.exists_eq_measurable_comp`; `FullData` carries the product
  σ-algebra, so measurability is coordinatewise).
* `localAbs_of_comap`: `LocalAbs … locRich Reg` follows from `LocRichComapStmt`, the same
  statement with the explicit measurable `F` replaced by *any* map `g` that is measurable for the
  σ-algebra generated by `locRich R'` (no explicit reconstruction of the output from the local
  data is needed).
* `aemeasurable_locRich_pstar`: for a `P_*` sample, each `locRich R` of the configuration is
  a.e.-measurable (from WEDGE-MEAS (1), `E6.aemeasurable_dataFull_pstar`).
* `aemeasurable_dataFull_unzip_of_localAbs_ae`: `E6.aemeasurable_dataFull_unzip_of_localAbs`
  with the hypothesis `hc'm` weakened to a.e.-measurability. (For a `P_*` sample `Y` is only
  specified in law, so `Measurable (locRich R ∘ c')` is not available in general.)
* `unzipMeasStmt_of_localAbsRich : LocalAbsRichStmt → UnzipMeasStmt`: step (4) of E6-LOCABS.
-/

noncomputable section

open MeasureTheory Set
open scoped NNReal ENNReal

namespace QuantumZipper.E6

open D3Plus

/-! ## Doob–Dynkin for `FullData` -/

/-- **Doob–Dynkin for `FullData`-valued maps**: a map measurable for the σ-algebra pulled back
along `f` factors through `f` by a measurable map. Coordinatewise application of
`StronglyMeasurable.exists_eq_measurable_comp` (mathlib, `MeasureTheory/Function/FactorsThrough`). -/
theorem exists_measurable_factor_fullData {X Y : Type*} [mY : MeasurableSpace Y] {f : X → Y}
    {g : X → FullData} (hg : Measurable[mY.comap f] g) :
    ∃ F : Y → FullData, Measurable F ∧ ∀ x, g x = F (f x) := by
  let _ : MeasurableSpace X := mY.comap f
  have h1 : ∀ i : ℕ, ∃ F : Y → ℝ, StronglyMeasurable F ∧ (fun x => (g x).1.1 i) = F ∘ f :=
    fun i => StronglyMeasurable.exists_eq_measurable_comp
      (((measurable_pi_apply i).comp (measurable_fst.comp measurable_fst)).comp hg).stronglyMeasurable
  have h2 : ∀ ρ : TestFun H, ∃ F : Y → ℝ, StronglyMeasurable F ∧
      (fun x => (g x).1.2 ρ) = F ∘ f :=
    fun ρ => StronglyMeasurable.exists_eq_measurable_comp
      (((measurable_pi_apply ρ).comp (measurable_snd.comp measurable_fst)).comp hg).stronglyMeasurable
  have h3 : ∀ s : ℝ≥0, ∃ F : Y → ℝ, StronglyMeasurable F ∧ (fun x => (g x).2 s) = F ∘ f :=
    fun s => StronglyMeasurable.exists_eq_measurable_comp
      (((measurable_pi_apply s).comp measurable_snd).comp hg).stronglyMeasurable
  choose F1 hF1 hg1 using h1
  choose F2 hF2 hg2 using h2
  choose F3 hF3 hg3 using h3
  refine ⟨fun y => ((fun i => F1 i y, fun ρ => F2 ρ y), fun s => F3 s y), ?_, fun x => ?_⟩
  · exact Measurable.prodMk (Measurable.prodMk (measurable_pi_iff.2 fun i => (hF1 i).measurable)
      (measurable_pi_iff.2 fun ρ => (hF2 ρ).measurable))
      (measurable_pi_iff.2 fun s => (hF3 s).measurable)
  · refine Prod.ext (Prod.ext (funext fun i => ?_) (funext fun ρ => ?_)) (funext fun s => ?_)
    · exact congrFun (hg1 i) x
    · exact congrFun (hg2 ρ) x
    · exact congrFun (hg3 s) x

/-! ## `LocalAbs` for `locRich` from a σ(`locRich R'`)-measurable version -/

variable {Ω' : Type*} [MeasurableSpace Ω']

/-! ## a.e.-measurability of the unzipped data from `LocalAbs` (a.e. form) -/

/-! ## The `P_*` side and `UnzipMeasStmt` -/

/-- For a `P_*` sample, every `locRich R` of the configuration is a.e.-measurable. -/
theorem aemeasurable_locRich_pstar {κ : ℝ} {Ω' : Type} [MeasurableSpace Ω'] {P' : Measure Ω'}
    {Y : Ω' → FieldSample} {B' : ℝ≥0 → Ω' → ℝ} (hP : Thm13Asm.IsPStarSample κ P' Y B')
    (R : ℕ) : AEMeasurable (fun ω' => locRich R (Y ω', drive κ B' ω')) P' := by
  have h := (measurable_truncFull R).comp_aemeasurable (aemeasurable_dataFull_pstar hP)
  exact h.congr (Filter.Eventually.of_forall fun ω' => truncFull_cfgFull R _)

end QuantumZipper.E6
