import QuantumZipper.Proofs.Zipper.E6UpBasic
import QuantumZipper.Proofs.Zipper.Thm13AssemblyStmt

/-!
# E6-UP: from equality of all local laws to equality of `configLawFull`

Task E6-UP (`handoff/THM13-ASM.md`, mismatch 1). The top-level assembly
`Thm13Asm.theorem1_3_of_nodes` needs `Thm13Asm.E6UpStmt loc : E6LocStmt loc → E6Stmt`.
Here `loc = D3Plus.locData` (decision D23: dyadic folded circles of radius `2^{-k}` inside
`closedBall 0 R`, driver on the capacity window `[0, R]`).

## What is proved

* `map_eq_of_truncLoc` (general reduction): two a.e.-measurable data maps `D₁, D₂ : Ω → T` whose
  small data `J ∘ Dᵢ` have the same law under every truncation `truncLoc R`, and which are
  recovered in law from their small data by one measurable map `G`, have the same law. Proof:
  π-λ uniqueness (`E6.ext_of_monotone_generating`; Billingsley Thm 3.3, Kallenberg Lemma 1.17)
  gives equal laws of the small data; then `law Dᵢ = law (G ∘ J ∘ Dᵢ)`.
* `map_eq_of_coord_ae`: laws on `FullData` agree if the maps agree a.s. coordinatewise, one test
  function at a time (π-λ over the directed family of finite restrictions `projS S`).
* `e6Up_of_read : E6ReadStmt → Thm13Asm.E6UpStmt D3Plus.locData`.

## Why a hypothesis `E6ReadStmt` remains (not a pure measure-theory fact)

`configLawFull` reads `lawData` = (`coordsFull`: raw values at dyadic folded circles of *all*
positive dyadic radii `(m+1)/2^j`, including radii `> 1` such as `3/4`; and raw pairings with all
test functions), while `locData` reads only `Factorization.coords` (radii `2^{-k} ≤ 1`). Since
`FieldSample = Measure ℂ → ℝ` is an arbitrary function, `lawData x` is **not** a function of
`Factorization.coords x` pointwise: the σ-algebra generated by the `locData R` (`R ∈ ℕ`) is
strictly smaller than the one `configLawFull` lives on. The upgrade therefore needs an almost-sure
reconstruction ("readability", `ReadableBy`): a measurable `G` with `coordsFull = (G ∘
Factorization.coords).1` a.s. and, for each fixed test function `ρ`, `pairRaw · ρ = (G ∘
Factorization.coords).2 ρ` a.s. (only countably many coordinates per event, so this is a property
of the joint law; `map_eq_of_coord_ae` shows it suffices), for the `P_*` field `Y` **and** for
the unzipped field `(zipLenDown γ ℓ₁ c).1` (same `G`), plus
a.e.-measurability of both data maps (without it `configLawFull` is a junk `Measure.map`).
This is `E6ReadStmt`. For GFF-type fields such a reconstruction is the classical fact that the
field is determined by its small circle averages (circle average at radius `r` = limit of Riemann
sums of `h_ε` over the circle; pairing = limit of `∫ h_ε ρ`), cf. TREG/PairLim/PairAff; for the
unzipped field it must be proved from the construction (`rescale ∘ coordChange`, which only
evaluates via `evalReg`).
-/

noncomputable section

open MeasureTheory Set
open scoped NNReal ENNReal

namespace QuantumZipper
namespace E6

/-! ## Laws on `FullData` are determined by countably many coordinates at a time -/

/-- Restriction of `configLawFull` data to finitely many test functions `S`. -/
def projS (S : Finset (TestFun H)) (e : FullData) : ((ℕ → ℝ) × (S → ℝ)) × (ℝ≥0 → ℝ) :=
  ((e.1.1, fun ρ => e.1.2 ρ.1), e.2)

theorem measurable_projS (S : Finset (TestFun H)) : Measurable (projS S) :=
  ((measurable_fst.comp measurable_fst).prodMk (measurable_pi_iff.2 fun ρ =>
    (measurable_pi_apply ρ.1).comp (measurable_snd.comp measurable_fst))).prodMk measurable_snd

theorem measurable_pi_of_dom {α ι : Type*} {m : MeasurableSpace α} {X : ι → Type*}
    [∀ i, MeasurableSpace (X i)] {g : α → ∀ i, X i} (h : ∀ i, Measurable[m] fun x => g x i) :
    Measurable[m] g := by
  refine Measurable.of_comap_le ?_
  rw [MeasurableSpace.pi, MeasurableSpace.comap_iSup]
  refine iSup_le fun i => ?_
  rw [MeasurableSpace.comap_comp]
  exact (h i).comap_le

theorem projS_directed :
    Directed (· ≤ ·) fun S : Finset (TestFun H) =>
      MeasurableSpace.comap (projS S) inferInstance := by
  classical
  intro S T
  refine ⟨S ∪ T, ?_, ?_⟩ <;>
  · refine Measurable.comap_le ?_
    set U := S ∪ T
    first
    | have hST : S ⊆ U := Finset.subset_union_left
      have hf : projS S = (fun q : ((ℕ → ℝ) × (U → ℝ)) × (ℝ≥0 → ℝ) =>
          ((q.1.1, fun ρ : S => q.1.2 ⟨ρ.1, hST ρ.2⟩), q.2)) ∘ projS U := rfl
      rw [hf]
      refine Measurable.comp ?_ (Measurable.of_comap_le le_rfl)
      exact ((measurable_fst.comp measurable_fst).prodMk (measurable_pi_iff.2 fun ρ =>
        (measurable_pi_apply _).comp (measurable_snd.comp measurable_fst))).prodMk
          measurable_snd
    | have hST : T ⊆ U := Finset.subset_union_right
      have hf : projS T = (fun q : ((ℕ → ℝ) × (U → ℝ)) × (ℝ≥0 → ℝ) =>
          ((q.1.1, fun ρ : T => q.1.2 ⟨ρ.1, hST ρ.2⟩), q.2)) ∘ projS U := rfl
      rw [hf]
      refine Measurable.comp ?_ (Measurable.of_comap_le le_rfl)
      exact ((measurable_fst.comp measurable_fst).prodMk (measurable_pi_iff.2 fun ρ =>
        (measurable_pi_apply _).comp (measurable_snd.comp measurable_fst))).prodMk
          measurable_snd

/-- The finite restrictions `projS S` generate the σ-algebra of `FullData` (own elementary
argument: each coordinate is read by some `projS S`). -/
theorem projS_generate :
    (inferInstance : MeasurableSpace FullData) ≤
      ⨆ S : Finset (TestFun H), MeasurableSpace.comap (projS S) inferInstance := by
  have hc : ∀ S, Measurable[⨆ S : Finset (TestFun H),
      MeasurableSpace.comap (projS S) inferInstance] (projS S) := fun S =>
    Measurable.of_comap_le (le_iSup (fun S : Finset (TestFun H) =>
      MeasurableSpace.comap (projS S)
        (inferInstance : MeasurableSpace (((ℕ → ℝ) × (S → ℝ)) × (ℝ≥0 → ℝ)))) S)
  have h1 := (measurable_fst.comp measurable_fst).comp (hc ∅)
  have h3 := measurable_snd.comp (hc ∅)
  have h2 : ∀ ρ : TestFun H, Measurable[⨆ S : Finset (TestFun H),
      MeasurableSpace.comap (projS S) inferInstance] fun e : FullData => e.1.2 ρ := fun ρ =>
    ((measurable_pi_apply (⟨ρ, Finset.mem_singleton_self ρ⟩ : ({ρ} : Finset (TestFun H)))).comp
      (measurable_snd.comp measurable_fst)).comp (hc {ρ})
  have hid : Measurable[⨆ S : Finset (TestFun H),
      MeasurableSpace.comap (projS S) inferInstance] fun e : FullData => ((e.1.1, e.1.2), e.2) :=
    (h1.prodMk (measurable_pi_of_dom h2)).prodMk h3
  have hid' : Measurable[⨆ S : Finset (TestFun H),
      MeasurableSpace.comap (projS S) inferInstance] (id : FullData → FullData) := hid
  have := hid'.comap_le
  rwa [MeasurableSpace.comap_id] at this

/-- Two a.e.-measurable `FullData`-valued maps whose circle coordinates and drivers agree a.s.,
and whose pairings agree a.s. **for each fixed test function**, have the same law. -/
theorem map_eq_of_coord_ae {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    [IsProbabilityMeasure P] (D D' : Ω → FullData) (hD : AEMeasurable D P)
    (hD' : AEMeasurable D' P) (h1 : ∀ᵐ ω ∂P, (D ω).1.1 = (D' ω).1.1)
    (h2 : ∀ ρ : TestFun H, ∀ᵐ ω ∂P, (D ω).1.2 ρ = (D' ω).1.2 ρ)
    (h3 : ∀ᵐ ω ∂P, (D ω).2 = (D' ω).2) : P.map D = P.map D' := by
  refine ext_of_directed_generating projS measurable_projS projS_directed projS_generate _ _
    (by simp) fun S => ?_
  rw [AEMeasurable.map_map_of_aemeasurable (measurable_projS S).aemeasurable hD,
    AEMeasurable.map_map_of_aemeasurable (measurable_projS S).aemeasurable hD']
  refine Measure.map_congr ?_
  have h2S : ∀ᵐ ω ∂P, ∀ ρ : S, (D ω).1.2 ρ.1 = (D' ω).1.2 ρ.1 :=
    ae_all_iff.2 fun ρ => h2 ρ.1
  filter_upwards [h1, h2S, h3] with ω hω1 hω2 hω3
  simp only [Function.comp_apply, projS, hω1, hω3]
  congr 2
  exact funext hω2

/-- A random field `Y` is **readable by `G`** if its circle coordinates `coordsFull` are a.s. the
first component of the measurable reconstruction `G` of its small-circle coordinates
`Factorization.coords`, and, for each fixed test function `ρ`, its raw pairing with `ρ` is a.s.
the `ρ`-component of that reconstruction (a statement about the law of countably many
coordinates at a time; no uncountable "for all `ρ`" inside the event). -/
def ReadableBy {Ω : Type*} [MeasurableSpace Ω]
    (G : (ℕ → ℝ) → (ℕ → ℝ) × (TestFun H → ℝ)) (Y : Ω → FieldSample) (P : Measure Ω) : Prop :=
  (∀ᵐ ω ∂P, CoordsFull.coordsFull (Y ω) = (G (Factorization.coords (Y ω))).1) ∧
    ∀ ρ : TestFun H, ∀ᵐ ω ∂P, pairRaw (Y ω) ρ.1 = (G (Factorization.coords (Y ω))).2 ρ

end E6
end QuantumZipper
