import QuantumZipper.Proofs.Probability.StrongMarkov
import QuantumZipper.GFF.Defs
import Mathlib.MeasureTheory.MeasurableSpace.EventuallyMeasurable
import Mathlib.MeasureTheory.PiSystem

/-!
# ESM-FILT: the augmented filtration `σ(X) ⊔ σ(B|[0,s]) ⊔ (null sets)`

Task ESM-FILT (node E-SM of `blueprint/E_BRANCH_BLUEPRINT.md`, decision `DECISIONS.md` D21):
the filtration `𝓕 s := σ(X) ⊔ σ(B u, u ≤ s)` **augmented by the `P`-null sets**
(`eventuallyMeasurableSpace`, the "usual conditions") is a `Filtration ℝ≥0 mΩ` satisfying the
three filtration hypotheses of `ESM.lintegral_levelTime_strongMarkov_lenA`:

* `esmFiltration_spec` : `B` is `𝓕`-adapted (`hBad`), the future increments
  `smPath B (fun _ => t)` are independent of `𝓕 t` (`hindF`), and every `P`-null set is in `𝓕 0`
  (`hnull`);
* `exists_filtration_ESM` : the existential form under `IsBrownianReal B P`,
  `IsFreeGFFModConstH X P`, `IndepFun (pathOf B) X P` and `P`-completeness of `mΩ`.

The ambient σ-algebra `mΩ` is assumed **`P`-complete** (`∀ N, P N = 0 → MeasurableSet N`), as the
consumer works on the completed probability space; this is an explicit hypothesis and is used for
two things: `B t` is measurable (a Brownian motion gives only a.e. measurability, mathlib
`IsPreBrownianReal.aemeasurable`), and the augmented σ-algebras are contained in `mΩ`.

Mathematics (Sheffield, *Conformal weldings of random surfaces*, arXiv:1012.4797, proof of
Lemma 5.6 / Thm 1.8; see also `handoff/E-PLAN-2.md`):
* the future increments of `B` are independent of the past `σ(B u, u ≤ s)` — the weak Markov
  property, mathlib `IsPreBrownianReal.indepFun_shift`;
* they are independent of `σ(X)`, because `X ⟂ pathOf B` (hypothesis `hind`) and the increments
  are a function of the path of `B`;
* the two combine to independence from `σ(X) ⊔ σ(B|≤s)` by the π-system criterion
  (`indep_sup_of_indep_sup`, **own elementary proof**: the intersections `A ∩ B` with `A ∈ m₁`,
  `B ∈ m₂` form a π-system generating `m₁ ⊔ m₂`);
* independence survives the `P`-null augmentation (`indep_augment`, own), because a set in the
  augmentation is a.e. equal to a measurable one and a.e. equal sets have equal measure; the
  completion bookkeeping (`augSigma_le_of_le`, `null_measurableSet_augSigma`) is own.

`pathOf B` is written unfolded as the path map `fun ω t ↦ B t ω` (definitionally equal) to keep
this module light.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Set Filter
open scoped NNReal ENNReal

namespace QuantumZipper
namespace ESM

open StrongMarkov

variable {Ω : Type*} [mΩ : MeasurableSpace Ω]

/-! ### The four σ-algebras -/

/-- `σ(B u, u ≤ s)`: the past of `B` up to time `s`. -/
def pastSigma (B : ℝ≥0 → Ω → ℝ) (s : ℝ≥0) : MeasurableSpace Ω :=
  MeasurableSpace.comap (fun ω (r : Set.Iic s) => B r.1 ω) MeasurableSpace.pi

/-- `σ(X)`: the σ-algebra generated by the field sample. -/
def xSigma (X : Ω → Measure ℂ → ℝ) : MeasurableSpace Ω :=
  MeasurableSpace.comap X (inferInstance : MeasurableSpace (Measure ℂ → ℝ))

/-- `σ(B (s + ·) − B s)`: the σ-algebra generated by the future increments at time `s`
(definitionally `MeasurableSpace.comap (smPath B (fun _ => s)) MeasurableSpace.pi`). -/
def futSigma (B : ℝ≥0 → Ω → ℝ) (s : ℝ≥0) : MeasurableSpace Ω :=
  MeasurableSpace.comap (fun ω (u : ℝ≥0) => B (s + u) ω - B s ω) MeasurableSpace.pi

/-- The raw (unaugmented) ESM σ-algebra `σ(X) ⊔ σ(B u, u ≤ s)`. -/
def rawSigma (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (s : ℝ≥0) : MeasurableSpace Ω :=
  xSigma X ⊔ pastSigma B s

/-- The `P`-null augmentation of a σ-algebra: the sets a.e. equal to an `m`-measurable set
(the same construction as `eventuallyMeasurableSpace m (ae P)`, written out to keep the
σ-algebra argument explicit). -/
def augSigma (P : Measure Ω) (m : MeasurableSpace Ω) : MeasurableSpace Ω where
  MeasurableSet' s := ∃ t, @MeasurableSet Ω m t ∧ s =ᶠ[ae P] t
  measurableSet_empty := ⟨∅, @MeasurableSet.empty Ω m, EventuallyEqSet.refl (ae P) ∅⟩
  measurableSet_compl := fun _ ⟨t, ht, hst⟩ =>
    ⟨tᶜ, @MeasurableSet.compl Ω t m ht, EventuallyEqSet.compl hst⟩
  measurableSet_iUnion := fun _ hs => by
    choose t ht hst using hs
    exact ⟨⋃ i, t i, @MeasurableSet.iUnion Ω _ m _ _ fun i => ht i,
      EventuallyEqSet.countable_iUnion hst⟩

/-- The ESM filtration σ-algebra at time `s`: `σ(X) ⊔ σ(B u, u ≤ s)`, augmented by the `P`-null
sets. -/
def esmSigma (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (P : Measure Ω) (s : ℝ≥0) :
    MeasurableSpace Ω :=
  augSigma P (rawSigma B X s)

/-! ### Elementary σ-algebra bookkeeping -/

lemma augSigma_mono (P : @Measure Ω mΩ) {m₁ m₂ : MeasurableSpace Ω} (h : m₁ ≤ m₂) :
    @augSigma Ω mΩ P m₁ ≤ @augSigma Ω mΩ P m₂ :=
  fun _ ⟨t, ht, hat⟩ => ⟨t, h t ht, hat⟩

lemma le_augSigma (P : @Measure Ω mΩ) (m : MeasurableSpace Ω) : m ≤ @augSigma Ω mΩ P m :=
  fun s hs => ⟨s, hs, EventuallyEqSet.refl (ae P) s⟩

/-- A preimage of a measurable set is measurable for the comap. -/
lemma measurableSet_comap_preimage {β : Type*} [MeasurableSpace β] {f : Ω → β} {s : Set β}
    (hs : MeasurableSet s) :
    MeasurableSet[MeasurableSpace.comap f (inferInstance : MeasurableSpace β)] (f ⁻¹' s) :=
  ⟨s, hs, rfl⟩

/-- Composition of a measurable function with the comap map is measurable for the comap. -/
lemma measurable_comp_comap {β γ : Type*} [MeasurableSpace β] [MeasurableSpace γ]
    {f : Ω → β} {g : β → γ} (hg : Measurable g) :
    Measurable[MeasurableSpace.comap f (inferInstance : MeasurableSpace β)] (g ∘ f) :=
  fun _ hU => measurableSet_comap_preimage (hg hU)

lemma pastSigma_mono (B : ℝ≥0 → Ω → ℝ) {s t : ℝ≥0} (hst : s ≤ t) :
    pastSigma B s ≤ pastSigma B t := by
  have hfun : (fun ω (r : Set.Iic s) => B r.1 ω) =
      (fun p : Set.Iic t → ℝ => fun r : Set.Iic s => p ⟨r.1, le_trans r.2 hst⟩) ∘
        (fun ω (r : Set.Iic t) => B r.1 ω) := by
    funext ω r
    rfl
  unfold pastSigma
  rw [hfun, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono (Measurable.comap_le
    (measurable_pi_iff.mpr fun r => measurable_pi_apply (⟨r.1, le_trans r.2 hst⟩ : Set.Iic t)))

lemma rawSigma_mono (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) {s t : ℝ≥0} (hst : s ≤ t) :
    rawSigma B X s ≤ rawSigma B X t :=
  sup_le_sup le_rfl (pastSigma_mono B hst)

/-- `σ(B u, u ≤ s) ≤ σ(B ·)`: the past is a function of the path of `B`. -/
lemma pastSigma_le_path (B : ℝ≥0 → Ω → ℝ) (s : ℝ≥0) :
    pastSigma B s ≤ MeasurableSpace.comap (fun ω (t : ℝ≥0) => B t ω) MeasurableSpace.pi := by
  have hfun : (fun ω (r : Set.Iic s) => B r.1 ω) =
      (fun p : ℝ≥0 → ℝ => fun r : Set.Iic s => p r.1) ∘
        (fun ω (t : ℝ≥0) => B t ω) := by
    funext ω r
    rfl
  unfold pastSigma
  rw [hfun, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono (Measurable.comap_le
    (measurable_pi_iff.mpr fun r => measurable_pi_apply r.1))

/-- `σ(B (s + ·) − B s) ≤ σ(B ·)`: the future increments are a function of the path of `B`. -/
lemma futSigma_le_path (B : ℝ≥0 → Ω → ℝ) (s : ℝ≥0) :
    futSigma B s ≤ MeasurableSpace.comap (fun ω (t : ℝ≥0) => B t ω) MeasurableSpace.pi := by
  have hfun : (fun ω (u : ℝ≥0) => B (s + u) ω - B s ω) =
      (fun p : ℝ≥0 → ℝ => fun u : ℝ≥0 => p (s + u) - p s) ∘
        (fun ω (t : ℝ≥0) => B t ω) := by
    funext ω u
    rfl
  unfold futSigma
  rw [hfun, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono (Measurable.comap_le (measurable_pi_iff.mpr fun u =>
    (measurable_pi_apply (s + u)).sub (measurable_pi_apply s)))

/-- `B t` is measurable for the past σ-algebra `σ(B u, u ≤ s)` at any time `t`; no measurability
of `B` is needed: `B t` is an evaluation of the past map. -/
lemma measurable_B_pastSigma (B : ℝ≥0 → Ω → ℝ) (t : ℝ≥0) : Measurable[pastSigma B t] (B t) :=
  show Measurable[MeasurableSpace.comap (fun ω (r : Set.Iic t) => B r.1 ω) MeasurableSpace.pi]
      (fun ω => B t ω) from
    measurable_comp_comap (f := fun ω (r : Set.Iic t) => B r.1 ω)
      (g := fun p : Set.Iic t → ℝ => p ⟨t, le_refl t⟩)
      (measurable_pi_apply (⟨t, le_refl t⟩ : Set.Iic t))

/-- `B` is adapted to the raw σ-algebra. -/
lemma measurable_B_rawSigma (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (t : ℝ≥0) :
    Measurable[rawSigma B X t] (B t) :=
  (measurable_B_pastSigma B t).mono le_sup_right le_rfl

/-- `B` is adapted to the augmented σ-algebra (`hBad` of E-SM-abs). -/
lemma measurable_B_esmSigma (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (P : Measure Ω)
    (t : ℝ≥0) : Measurable[esmSigma B X P t] (B t) :=
  (measurable_B_rawSigma B X t).mono (le_augSigma P _) le_rfl

/-- The augmented σ-algebra is contained in `mΩ` when `m ≤ mΩ` and `mΩ` contains the `P`-null
sets. -/
lemma augSigma_le_of_le (P : @Measure Ω mΩ) {m : MeasurableSpace Ω} (h : m ≤ mΩ)
    (hnull : ∀ N : Set Ω, P N = 0 → MeasurableSet[mΩ] N) : @augSigma Ω mΩ P m ≤ mΩ := by
  intro A ⟨A', hA', hA⟩
  haveI : P.IsComplete := ⟨hnull⟩
  exact NullMeasurableSet.measurable_of_complete
    (NullMeasurableSet.congr (h A' hA').nullMeasurableSet hA.symm)

/-- Every `P`-null set is measurable for the augmentation of any σ-algebra (`hnull` of
E-SM-abs). -/
lemma null_measurableSet_augSigma (P : @Measure Ω mΩ) (m : MeasurableSpace Ω) {N : Set Ω}
    (hN : P N = 0) : MeasurableSet[@augSigma Ω mΩ P m] N :=
  ⟨∅, @MeasurableSet.empty Ω m, by
    rw [eventuallyEqSet_empty]
    exact ae_iff.mpr (by simpa using hN)⟩

/-- `σ(B u, u ≤ s) ≤ mΩ` for a process all of whose coordinates are measurable. -/
lemma pastSigma_le (B : ℝ≥0 → Ω → ℝ) (hBm : ∀ t, Measurable (B t)) (s : ℝ≥0) :
    pastSigma B s ≤ mΩ :=
  (measurable_pi_iff.mpr fun (r : Set.Iic s) => hBm r.1).comap_le

/-- `σ(B (s + ·) − B s) ≤ mΩ` for a process all of whose coordinates are measurable. -/
lemma futSigma_le (B : ℝ≥0 → Ω → ℝ) (hBm : ∀ t, Measurable (B t)) (s : ℝ≥0) :
    futSigma B s ≤ mΩ :=
  (measurable_pi_iff.mpr fun u => (hBm (s + u)).sub (hBm s)).comap_le

/-! ### Independence of the future increments -/

/-- **The π-system lemma.** If `m₁` is independent of `m₂ ⊔ m₃` and `m₂` of `m₃`, then `m₁ ⊔ m₂`
is independent of `m₃` (own elementary proof: the intersections `A ∩ B`, `A ∈ m₁`, `B ∈ m₂`, form
a π-system generating `m₁ ⊔ m₂`). -/
lemma indep_sup_of_indep_sup (m₁ m₂ m₃ : MeasurableSpace Ω) {P : @Measure Ω mΩ}
    [IsProbabilityMeasure P] (h₁ : @Indep Ω m₁ (m₂ ⊔ m₃) mΩ P) (h₂ : @Indep Ω m₂ m₃ mΩ P)
    (h₁m : m₁ ≤ mΩ) (h₂m : m₂ ≤ mΩ) (h₃m : m₃ ≤ mΩ) : @Indep Ω (m₁ ⊔ m₂) m₃ mΩ P := by
  set p₁ : Set (Set Ω) :=
    {C | ∃ A : Set Ω, MeasurableSet[m₁] A ∧ ∃ B : Set Ω, MeasurableSet[m₂] B ∧ C = A ∩ B}
    with hp₁
  have mem_p₁ : ∀ C : Set Ω, C ∈ p₁ ↔
      ∃ A : Set Ω, MeasurableSet[m₁] A ∧ ∃ B : Set Ω, MeasurableSet[m₂] B ∧ C = A ∩ B :=
    fun C => by simp only [hp₁, Set.mem_ofPred_eq]
  have hgen₁ : MeasurableSpace.generateFrom p₁ = m₁ ⊔ m₂ := by
    refine le_antisymm ?_ ?_
    · refine MeasurableSpace.generateFrom_le fun C hC => ?_
      rw [mem_p₁ C] at hC
      obtain ⟨A, hA, B, hB, rfl⟩ := hC
      exact ((show m₁ ≤ m₁ ⊔ m₂ from le_sup_left) A hA).inter
        ((show m₂ ≤ m₁ ⊔ m₂ from le_sup_right) B hB)
    · refine sup_le ?_ ?_
      · intro A hA
        refine MeasurableSpace.measurableSet_generateFrom ?_
        rw [mem_p₁ A]
        exact ⟨A, hA, univ, MeasurableSet.univ, (inter_univ A).symm⟩
      · intro B hB
        refine MeasurableSpace.measurableSet_generateFrom ?_
        rw [mem_p₁ B]
        exact ⟨univ, MeasurableSet.univ, B, hB, (univ_inter B).symm⟩
  have hgen₂ : MeasurableSpace.generateFrom {C : Set Ω | MeasurableSet[m₃] C} = m₃ :=
    le_antisymm (MeasurableSpace.generateFrom_le fun _ hC => hC)
      fun _ hC => MeasurableSpace.measurableSet_generateFrom hC
  have hpi₁ : IsPiSystem p₁ := by
    intro C hC C' hC' _
    obtain ⟨A, hA, B, hB, rfl⟩ := (mem_p₁ C).1 hC
    obtain ⟨A', hA', B', hB', rfl⟩ := (mem_p₁ C').1 hC'
    rw [mem_p₁]
    exact ⟨A ∩ A', hA.inter hA', B ∩ B', hB.inter hB',
      by ext x; simp only [Set.mem_inter_iff]; tauto⟩
  have hpi₂ : IsPiSystem {C : Set Ω | MeasurableSet[m₃] C} := fun C hC C' hC' _ => hC.inter hC'
  have hmeas₁ : ∀ C : Set Ω, C ∈ p₁ → MeasurableSet[mΩ] C := by
    intro C hC
    rw [mem_p₁ C] at hC
    obtain ⟨A, hA, B, hB, rfl⟩ := hC
    exact (h₁m A hA).inter (h₂m B hB)
  have hmeas₂ : ∀ C : Set Ω, C ∈ {C : Set Ω | MeasurableSet[m₃] C} → MeasurableSet[mΩ] C :=
    fun C hC => h₃m C hC
  have hyp : @IndepSets Ω mΩ p₁ {C : Set Ω | MeasurableSet[m₃] C} P := by
    intro C D hC hD
    rw [mem_p₁ C] at hC
    obtain ⟨A, hA, B, hB, rfl⟩ := hC
    have h₁' := (@Indep_iff Ω m₁ (m₂ ⊔ m₃) mΩ P).1 h₁
    have h₂' := (@Indep_iff Ω m₂ m₃ mΩ P).1 h₂
    have hBD : MeasurableSet[m₂ ⊔ m₃] (B ∩ D) :=
      ((show m₂ ≤ m₂ ⊔ m₃ from le_sup_left) B hB).inter
        ((show m₃ ≤ m₂ ⊔ m₃ from le_sup_right) D hD)
    have hAB : P (A ∩ B) = P A * P B :=
      h₁' A B hA ((show m₂ ≤ m₂ ⊔ m₃ from le_sup_left) B hB)
    have hADD : P (A ∩ (B ∩ D)) = P A * P (B ∩ D) := h₁' A (B ∩ D) hA hBD
    have hBD' : P (B ∩ D) = P B * P D := h₂' B D hB hD
    filter_upwards with a
    calc P ((A ∩ B) ∩ D) = P (A ∩ (B ∩ D)) := by rw [Set.inter_assoc]
      _ = P A * P (B ∩ D) := hADD
      _ = P A * (P B * P D) := by rw [hBD']
      _ = P A * P B * P D := by rw [mul_assoc]
      _ = P (A ∩ B) * P D := by rw [hAB]
  have hmain := @IndepSets.indep' Ω mΩ P inferInstance p₁ {C : Set Ω | MeasurableSet[m₃] C}
    hmeas₁ hmeas₂ hpi₁ hpi₂ hyp
  rwa [hgen₁, hgen₂] at hmain

/-- Independence survives augmentation of the first σ-algebra by the `P`-null sets (own
elementary proof: use `Indep_iff`; a.e. equal sets have equal measure). -/
lemma indep_augment (P : @Measure Ω mΩ) {m₁ m₂ : MeasurableSpace Ω}
    (h : @Indep Ω m₁ m₂ mΩ P) : @Indep Ω (@augSigma Ω mΩ P m₁) m₂ mΩ P := by
  rw [@Indep_iff Ω m₁ m₂ mΩ P] at h
  rw [@Indep_iff Ω (@augSigma Ω mΩ P m₁) m₂ mΩ P]
  rintro t1 t2 ⟨t1', ht1', h1⟩ ht2
  have h2 : t1 ∩ t2 =ᶠ[ae P] t1' ∩ t2 := h1.inter (EventuallyEq.refl (ae P) t2)
  rw [measure_congr h2, measure_congr h1, h t1' t2 ht1' ht2]

/-- **Independence of the raw σ-algebra from the future increments.** If `B` is pre-Brownian and
`X` is independent of the whole path of `B`, then `σ(X) ⊔ σ(B u, u ≤ s)` is independent of the
future increments `σ(B (s + ·) − B s)`. -/
lemma indep_rawSigma (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (P : Measure Ω)
    [IsProbabilityMeasure P] (hB : IsPreBrownianReal B P)
    (hind : IndepFun (fun ω (t : ℝ≥0) => B t ω) X P) (hXm : Measurable X)
    (hBm : ∀ t, Measurable (B t)) (s : ℝ≥0) :
    @Indep Ω (rawSigma B X s) (futSigma B s) mΩ P := by
  have hle : pastSigma B s ⊔ futSigma B s ≤
      MeasurableSpace.comap (fun ω (t : ℝ≥0) => B t ω) MeasurableSpace.pi :=
    sup_le (pastSigma_le_path B s) (futSigma_le_path B s)
  have hpast : @Indep Ω (xSigma X) (pastSigma B s ⊔ futSigma B s) mΩ P := by
    have h := hind
    rw [IndepFun_iff_Indep] at h
    exact indep_of_indep_of_le_right h.symm hle
  have hmark : @Indep Ω (pastSigma B s) (futSigma B s) mΩ P := by
    have h := hB.indepFun_shift s
    rw [IndepFun_iff_Indep] at h
    exact h.symm
  have hraw : rawSigma B X s = xSigma X ⊔ pastSigma B s := rfl
  rw [hraw]
  exact indep_sup_of_indep_sup (xSigma X) (pastSigma B s) (futSigma B s) hpast hmark
    hXm.comap_le (pastSigma_le B hBm s) (futSigma_le B hBm s)

/-- **ESM-FILT.** The future increments at time `t` are independent of the augmented σ-algebra
`σ(X) ⊔ σ(B u, u ≤ t) ⊔ (null sets)`. -/
theorem indep_esmSigma (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (P : Measure Ω)
    [IsProbabilityMeasure P] (hB : IsPreBrownianReal B P)
    (hind : IndepFun (fun ω (t : ℝ≥0) => B t ω) X P) (hXm : Measurable X)
    (hBm : ∀ t, Measurable (B t)) (t : ℝ≥0) :
    @Indep Ω (esmSigma B X P t) (futSigma B t) mΩ P :=
  indep_augment P (indep_rawSigma B X P hB hind hXm hBm t)

/-! ### The filtration and its three properties -/

/-- **ESM-FILT: the augmented filtration.** `𝓕 s = σ(X) ⊔ σ(B u, u ≤ s)`, augmented by the
`P`-null sets. -/
noncomputable def esmFiltration (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (P : Measure Ω)
    (hBm : ∀ t, Measurable (B t)) (hXm : Measurable X)
    (hnull : ∀ N : Set Ω, P N = 0 → MeasurableSet[mΩ] N) : Filtration ℝ≥0 mΩ where
  seq s := esmSigma B X P s
  mono' _ _ hst := augSigma_mono P (rawSigma_mono B X hst)
  le' s := augSigma_le_of_le P (sup_le hXm.comap_le (pastSigma_le B hBm s)) hnull

/-- **ESM-FILT, assembly.** The augmented filtration satisfies the adaptedness, independence
(`hindF`) and null-set (`hnull`) hypotheses of `ESM.lintegral_levelTime_strongMarkov_lenA`. -/
theorem esmFiltration_spec (B : ℝ≥0 → Ω → ℝ) (X : Ω → Measure ℂ → ℝ) (P : Measure Ω)
    [IsProbabilityMeasure P] (hBm : ∀ t, Measurable (B t)) (hXm : Measurable X)
    (hnull : ∀ N : Set Ω, P N = 0 → MeasurableSet[mΩ] N) (hB : IsPreBrownianReal B P)
    (hind : IndepFun (fun ω (t : ℝ≥0) => B t ω) X P) :
    (∀ t, Measurable[esmFiltration B X P hBm hXm hnull t] (B t)) ∧
      (∀ t, @Indep Ω (esmFiltration B X P hBm hXm hnull t)
        (MeasurableSpace.comap (smPath B (fun _ => t)) MeasurableSpace.pi) mΩ P) ∧
      (∀ N : Set Ω, P N = 0 → MeasurableSet[esmFiltration B X P hBm hXm hnull 0] N) :=
  ⟨fun t => measurable_B_esmSigma B X P t,
    fun t => indep_esmSigma B X P hB hind hXm hBm t,
    fun _ hN => null_measurableSet_augSigma P (rawSigma B X 0) hN⟩

end ESM
end QuantumZipper
