import LQGMetric.Field.GFFInvariance
import QuantumZipper.Proofs.LQG.WedgeRestriction
import Mathlib.MeasureTheory.Constructions.Projective

/-!
# Uniqueness of the law of the whole-plane GFF (task P2-FINV)

* `GFFLaw.map_pairProc_eq`: two `IsWholePlaneGFF` fields (on possibly different probability
  spaces) have the same law of mean-zero pairings `(⟨h, φ⟩)_{φ ∈ TestC0}` on the product
  σ-algebra (= the law of `h` modulo additive constant).
  Proof: finite-dimensional laws are centered Gaussian vectors with the same covariance
  (`QuantumZipper.WedgeRes.map_eq_of_gaussian_vec`), and a measure on a product is determined by
  its finite-dimensional marginals (mathlib `IsProjectiveLimit.unique`, Kolmogorov extension
  uniqueness).
* `GFFLaw.map_eq_of_normalized`: if moreover both fields satisfy `N h = 0` a.s. for a measurable
  normalization functional `N : DistC → ℝ` with `N (h + c) = N h + c`, their laws on `DistC`
  (cylinder σ-algebra) agree. Instance: `N h = ⟨h, ρ⟩` with `∫ ρ = 1`
  (`map_eq_of_normalized_test`). GM's normalization `h_1(0) = 0` (circle average,
  `uniqueness-final.tex` l. 223–224) is the case `N = circleAvg · 1 0` (task P2-FCIRC).
* `GFFLaw.map_affine_normalized`: for such `N`, `h(r·+z) − N(h(r·+z))` has the law of `h`
  (GM l. 516: "`h(·/b) − h_{1/b}(0) =ᵈ h`", and l. 458 "scale invariance of the law of the
  whole-plane GFF, modulo additive constant").

Sources: the law of a centered Gaussian process is determined by its covariance (e.g. Janson,
*Gaussian Hilbert spaces*, Thm 1.9 / standard); the reduction "normalized field = measurable
function of the field modulo constants" is an own elementary argument.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory ProbabilityTheory Filter Topology Set
open scoped Distributions ENNReal

namespace LQGMetric
namespace GFFLaw
open GFFInv

variable {Ω Ω' : Type*} [MeasurableSpace Ω] [MeasurableSpace Ω'] {P : Measure Ω}
  {P' : Measure Ω'}

/-- the process of mean-zero pairings of a field -/
def pairProc (h : Ω → DistC) (ω : Ω) : TestC0 → ℝ := fun φ => h ω φ.1

lemma measurable_pairProc {h : Ω → DistC} (hh : Measurable h) : Measurable (pairProc h) :=
  measurable_pi_iff.2 fun φ => (measurable_pair φ.1).comp hh

/-- Uniqueness of the law of the whole-plane GFF modulo additive constant. -/
theorem map_pairProc_eq {h : Ω → DistC} {h' : Ω' → DistC} (hh : IsWholePlaneGFF h P)
    (hh' : IsWholePlaneGFF h' P') : P.map (pairProc h) = P'.map (pairProc h') := by
  have := hh.gaussian.isProbabilityMeasure
  have := hh'.gaussian.isProbabilityMeasure
  have hfin : ∀ I : Finset TestC0, (P.map (pairProc h)).map I.restrict =
      (P'.map (pairProc h')).map I.restrict := by
    intro I
    rw [Measure.map_map (Finset.measurable_restrict I) (measurable_pairProc hh.measurable),
      Measure.map_map (Finset.measurable_restrict I) (measurable_pairProc hh'.measurable)]
    exact QuantumZipper.WedgeRes.map_eq_of_gaussian_vec
      (U := fun (i : I) ω => h ω i.1.1) (V := fun (i : I) ω => h' ω i.1.1)
      (hh.gaussian.hasGaussianLaw I) (hh'.gaussian.hasGaussianLaw I)
      (fun i => (measurable_pair _).comp hh.measurable)
      (fun i => (measurable_pair _).comp hh'.measurable)
      (fun i => (hh.gaussian.hasGaussianLaw_eval i.1).memLp_two)
      (fun i => (hh'.gaussian.hasGaussianLaw_eval i.1).memLp_two)
      (fun i => hh.centered i.1) (fun i => hh'.centered i.1)
      (fun i j => by rw [hh.covariance_eq, hh'.covariance_eq])
  exact IsProjectiveLimit.unique (P := fun I => (P'.map (pairProc h')).map I.restrict)
    hfin (fun _ => rfl)

/-! ## The σ-algebra of mean-zero pairings on `DistC` -/

/-- mean-zero pairings of a distribution -/
def ev0 (g : DistC) : TestC0 → ℝ := fun φ => g φ.1

/-- the σ-algebra on `DistC` generated by the mean-zero pairings -/
def sigma0 : MeasurableSpace DistC := MeasurableSpace.comap ev0 MeasurableSpace.pi

/-- Any map out of `(DistC, sigma0)` has the same image law for two whole-plane GFFs. -/
theorem map_comp_eq_of_sigma0 {β : Type*} [MeasurableSpace β] {F : DistC → β}
    (hF : Measurable[sigma0] F) {h : Ω → DistC} {h' : Ω' → DistC} (hh : IsWholePlaneGFF h P)
    (hh' : IsWholePlaneGFF h' P') : P.map (F ∘ h) = P'.map (F ∘ h') := by
  have hle : sigma0 ≤ (inferInstance : MeasurableSpace DistC) := by
    rw [sigma0, ← measurable_iff_comap_le]
    exact measurable_pi_iff.2 fun φ => measurable_pair φ.1
  have hFm : Measurable F := hF.mono hle le_rfl
  ext S hS
  rw [Measure.map_apply (hFm.comp hh.measurable) hS,
    Measure.map_apply (hFm.comp hh'.measurable) hS]
  obtain ⟨T, hT, hTS⟩ := hF hS
  have e1 : F ∘ h ⁻¹' S = pairProc h ⁻¹' T := by
    rw [preimage_comp, ← hTS]; rfl
  have e2 : F ∘ h' ⁻¹' S = pairProc h' ⁻¹' T := by
    rw [preimage_comp, ← hTS]; rfl
  rw [e1, e2, ← Measure.map_apply (measurable_pairProc hh.measurable) hT,
    ← Measure.map_apply (measurable_pairProc hh'.measurable) hT, map_pairProc_eq hh hh']

/-! ## Recentering by a mean-one test function -/

lemma addConst_addConst (g : DistC) (a b : ℝ) :
    addConst (addConst g a) b = addConst g (a + b) :=
  DFunLike.ext _ _ fun φ => by simp only [addConst_apply]; ring

lemma addConst_zero' (g : DistC) : addConst g 0 = g :=
  DFunLike.ext _ _ fun φ => by simp only [addConst_apply, mul_zero, add_zero]

/-- `g − ⟨g, ρ⟩` -/
def recenter (ρ : TestC) (g : DistC) : DistC := addConst g (-(g ρ))

lemma integral_sub_smul {ρ : TestC} (hρ : ∫ x, ρ x = 1) (φ : TestC) :
    ∫ x, (φ - (∫ x, φ x) • ρ) x = 0 := by
  show ∫ x, (φ x - (∫ x, φ x) * ρ x) = 0
  rw [integral_sub (integrable_test φ) ((integrable_test ρ).const_mul _), integral_const_mul, hρ,
    mul_one, sub_self]

lemma recenter_apply (ρ : TestC) (g : DistC) (φ : TestC) :
    recenter ρ g φ = g (φ - (∫ x, φ x) • ρ) := by
  rw [recenter, addConst_apply, map_sub, map_smul, smul_eq_mul]; ring

lemma measurable_recenter_sigma0 {ρ : TestC} (hρ : ∫ x, ρ x = 1) :
    Measurable[sigma0] (recenter ρ) := by
  refine (@measurable_distC_iff DistC sigma0 _).2 fun φ => ?_
  simp only [recenter_apply]
  have hev : Measurable[sigma0] ev0 := fun s hs => ⟨s, hs, rfl⟩
  exact (measurable_pi_apply (⟨_, integral_sub_smul hρ φ⟩ : TestC0)).comp hev

lemma map_congr_fix {N : DistC → ℝ} {F : DistC → DistC} (hF : ∀ g, N g = 0 → F g = g)
    {h : Ω → DistC} (hn : ∀ᵐ ω ∂P, N (h ω) = 0) : P.map h = P.map (F ∘ h) :=
  Measure.map_congr (by filter_upwards [hn] with ω hω using (hF _ hω).symm)

/-- Uniqueness of the law of a normalized whole-plane GFF, for any measurable normalization
functional `N` with `N (g + c) = N g + c` (e.g. `N g = ⟨g, ρ⟩`, `∫ ρ = 1`, or the circle average
`g_1(0)` of GM l. 223). -/
theorem map_eq_of_normalized {ρ : TestC} (hρ : ∫ x, ρ x = 1) {N : DistC → ℝ}
    (hNm : Measurable N) (hN : ∀ g c, N (addConst g c) = N g + c) {h : Ω → DistC}
    {h' : Ω' → DistC} (hh : IsWholePlaneGFF h P) (hh' : IsWholePlaneGFF h' P')
    (hn : ∀ᵐ ω ∂P, N (h ω) = 0) (hn' : ∀ᵐ ω ∂P', N (h' ω) = 0) : P.map h = P'.map h' := by
  let K : DistC → DistC := fun g => addConst g (-(N g))
  have hK : Measurable K := measurable_distC_iff.2 fun φ => by
    simp only [K, addConst_apply]
    exact (measurable_pair φ).add (hNm.neg.const_mul _)
  have key : ∀ g, K (recenter ρ g) = addConst g (-(N g)) := by
    intro g
    simp only [K, recenter, hN, addConst_addConst]
    congr 1; ring
  have hF : Measurable[sigma0] (K ∘ recenter ρ) := hK.comp (measurable_recenter_sigma0 hρ)
  have hfix : ∀ g, N g = 0 → (K ∘ recenter ρ) g = g := fun g hg => by
    simp only [Function.comp_apply, key, hg, neg_zero, addConst_zero']
  rw [map_congr_fix hfix hn, map_congr_fix hfix hn', map_comp_eq_of_sigma0 hF hh hh']

/-- `h(r · + z) − N(h(r · + z))` has the law of `h`, for a normalized whole-plane GFF `h`
(GM l. 516 with `N = h_1(0)`, where `N(h(r·+z)) = h_r(z)`). -/
theorem map_affine_normalized {ρ : TestC} (hρ : ∫ x, ρ x = 1) {N : DistC → ℝ}
    (hNm : Measurable N) (hN : ∀ g c, N (addConst g c) = N g + c) {h : Ω → DistC}
    (hh : IsWholePlaneGFF h P) (hn : ∀ᵐ ω ∂P, N (h ω) = 0) {r : ℝ} (hr : 0 < r) (z : ℂ) :
    P.map (fun ω => addConst (affineComp r z (h ω)) (-(N (affineComp r z (h ω))))) =
      P.map h := by
  have h1 := hh.affineComp hr z
  have h2 := h1.addConst (hNm.comp h1.measurable).neg
  refine map_eq_of_normalized hρ hNm hN h2 hh (ae_of_all _ fun ω => ?_) hn
  simp only [hN, add_neg_cancel]

/-! ## Normalizations that are equivariant only almost surely (e.g. circle averages) -/

lemma recenter_addConst {ρ : TestC} (hρ : ∫ x, ρ x = 1) (g : DistC) (c : ℝ) :
    recenter ρ (addConst g c) = recenter ρ g :=
  DFunLike.ext _ _ fun φ => by
    rw [recenter_apply, recenter_apply, addConst_apply, integral_sub_smul hρ, zero_mul, add_zero]

/-- the equivariant modification `N̂ g = ⟨g, ρ⟩ + N(g − ⟨g, ρ⟩)` of a normalization `N` -/
def equivNorm (ρ : TestC) (N : DistC → ℝ) (g : DistC) : ℝ := g ρ + N (recenter ρ g)

lemma equivNorm_addConst {ρ : TestC} (hρ : ∫ x, ρ x = 1) (N : DistC → ℝ) (g : DistC) (c : ℝ) :
    equivNorm ρ N (addConst g c) = equivNorm ρ N g + c := by
  rw [equivNorm, equivNorm, recenter_addConst hρ, addConst_apply, hρ, one_mul]; ring

lemma equivNorm_eq {ρ : TestC} {N : DistC → ℝ} {g : DistC}
    (hg : ∀ c, N (addConst g c) = N g + c) : equivNorm ρ N g = N g := by
  rw [equivNorm, recenter, hg]; ring

/-- `map_eq_of_normalized` when `N (g + c) = N g + c` is only known at the fields, a.s. (this is
the situation of the circle average `N g = g_1(0)`, defined as a limit with junk value). -/
theorem map_eq_of_normalized_ae {ρ : TestC} (hρ : ∫ x, ρ x = 1) {N : DistC → ℝ}
    (hNm : Measurable N) {h : Ω → DistC} {h' : Ω' → DistC} (hh : IsWholePlaneGFF h P)
    (hh' : IsWholePlaneGFF h' P')
    (hN : ∀ᵐ ω ∂P, ∀ c, N (addConst (h ω) c) = N (h ω) + c)
    (hN' : ∀ᵐ ω ∂P', ∀ c, N (addConst (h' ω) c) = N (h' ω) + c)
    (hn : ∀ᵐ ω ∂P, N (h ω) = 0) (hn' : ∀ᵐ ω ∂P', N (h' ω) = 0) : P.map h = P'.map h' := by
  have hm : Measurable (equivNorm ρ N) :=
    (measurable_pair ρ).add (hNm.comp ((measurable_recenter_sigma0 hρ).mono
      (by rw [sigma0, ← measurable_iff_comap_le]
          exact measurable_pi_iff.2 fun φ => measurable_pair φ.1) le_rfl))
  refine map_eq_of_normalized hρ hm (equivNorm_addConst hρ N) hh hh' ?_ ?_
  · filter_upwards [hN, hn] with ω h1 h2 using (equivNorm_eq h1).trans h2
  · filter_upwards [hN', hn'] with ω h1 h2 using (equivNorm_eq h1).trans h2

/-- `map_affine_normalized` with `N` equivariant only at the fields, a.s. -/
theorem map_affine_normalized_ae {ρ : TestC} (hρ : ∫ x, ρ x = 1) {N : DistC → ℝ}
    (hNm : Measurable N) {h : Ω → DistC} (hh : IsWholePlaneGFF h P)
    (hN : ∀ᵐ ω ∂P, ∀ c, N (addConst (h ω) c) = N (h ω) + c) (hn : ∀ᵐ ω ∂P, N (h ω) = 0)
    {r : ℝ} (hr : 0 < r) (z : ℂ)
    (hNr : ∀ᵐ ω ∂P, ∀ c, N (addConst (affineComp r z (h ω)) c) = N (affineComp r z (h ω)) + c) :
    P.map (fun ω => addConst (affineComp r z (h ω)) (-(N (affineComp r z (h ω))))) =
      P.map h := by
  have h1 := hh.affineComp hr z
  have h2 := h1.addConst (hNm.comp h1.measurable).neg
  refine map_eq_of_normalized_ae hρ hNm h2 hh ?_ hN ?_ hn
  · filter_upwards [hNr] with ω hω c
    simp only [addConst_addConst, hω]; ring
  · filter_upwards [hNr] with ω hω
    simp only [hω, add_neg_cancel]

/-- a mean-one test function: the standard mollifier `bumpTest n x` has integral `1` -/
lemma integral_bumpTest (n : ℕ) (x : ℂ) : ∫ y, bumpTest n x y = 1 :=
  ContDiffBump.integral_normed _

end GFFLaw
end LQGMetric
