import LQGMetric.Field.HeatKernelSquareImg
import Mathlib.Algebra.Order.ToIntervalMod

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# Folding the line onto an interval (task P2-DDDFP29, WP-110)

The method of images (Feller II §X.5) rests on the fact that the line is tiled by the images
`I + 2nL` and `2a − I + 2nL` (`n ∈ ℤ`) of `I = (a, a + L]` under the reflection group generated by
`w ↦ 2a − w` and `w ↦ w + 2L`:

  `∑ₙ ∫⁻_I h(w + 2nL) dw + ∑ₙ ∫⁻_I h(2a − w + 2nL) dw = ∫⁻_ℝ h`   (`HeatSq.lintegral_fold`).

Own elementary proof (tiling by mathlib's `iUnion_Ioc_add_zsmul`, translation and reflection
invariance of Lebesgue measure).
-/

noncomputable section

open MeasureTheory Set
open scoped ENNReal

namespace LQGMetric
namespace HeatSq

/-- Translation of a set lintegral over an interval. -/
lemma setLIntegral_Ioc_comp_add (h : ℝ → ℝ≥0∞) (x y c : ℝ) :
    ∫⁻ w in Ioc x y, h (w + c) = ∫⁻ w in Ioc (x + c) (y + c), h w := by
  rw [← lintegral_indicator measurableSet_Ioc, ← lintegral_indicator measurableSet_Ioc,
    ← lintegral_add_right_eq_self (μ := volume) ((Ioc (x + c) (y + c)).indicator h) c]
  congr 1; funext w
  simp only [Set.indicator, Set.mem_Ioc, add_lt_add_iff_right, add_le_add_iff_right]

/-- Reflection of a set lintegral over an interval. -/
lemma setLIntegral_Ioc_comp_sub (h : ℝ → ℝ≥0∞) (x y c : ℝ) :
    ∫⁻ w in Ioc x y, h (c - w) = ∫⁻ w in Ico (c - y) (c - x), h w := by
  rw [← lintegral_indicator measurableSet_Ioc, ← lintegral_indicator measurableSet_Ico,
    ← lintegral_sub_left_eq_self (μ := volume) ((Ico (c - y) (c - x)).indicator h) c]
  congr 1; funext w
  simp only [Set.indicator, Set.mem_Ioc, Set.mem_Ico, sub_le_sub_iff_left, sub_lt_sub_iff_left]
  by_cases h1 : x < w <;> by_cases h2 : w ≤ y <;> simp [h1, h2]

/-- **Folding**: the images of `(a, a+L]` tile the line. -/
theorem lintegral_fold {a L : ℝ} (hL : 0 < L) (h : ℝ → ℝ≥0∞) :
    (∑' n : ℤ, ∫⁻ w in Ioc a (a + L), h (w + 2 * n * L)) +
      ∑' n : ℤ, ∫⁻ w in Ioc a (a + L), h (2 * a - w + 2 * n * L) = ∫⁻ w, h w := by
  have h2L : (0 : ℝ) < 2 * L := by positivity
  have hcell : ∀ n : ℤ, ∫⁻ w in Ioc (a + n • (2 * L)) (a + (n + 1) • (2 * L)), h w =
      (∫⁻ w in Ioc a (a + L), h (w + 2 * n * L)) +
        ∫⁻ w in Ioc a (a + L), h (2 * a - w + 2 * ((n + 1 : ℤ) : ℝ) * L) := by
    intro n
    have e1 : a + n • (2 * L) = a + 2 * n * L := by rw [zsmul_eq_mul]; ring
    have e2 : a + (n + 1) • (2 * L) = a + 2 * n * L + L + L := by
      rw [zsmul_eq_mul]; push_cast; ring
    rw [e1, e2, ← Ioc_union_Ioc_eq_Ioc (b := a + 2 * n * L + L) (by linarith) (by linarith),
      lintegral_union measurableSet_Ioc (Ioc_disjoint_Ioc_of_le le_rfl)]
    congr 1
    · rw [setLIntegral_Ioc_comp_add]; congr 2 <;> ring
    · have := setLIntegral_Ioc_comp_sub (fun w => h w) a (a + L) (2 * a + 2 * ((n + 1 : ℤ) : ℝ) * L)
      rw [show (fun w => h (2 * a - w + 2 * ((n + 1 : ℤ) : ℝ) * L)) =
        fun w => h (2 * a + 2 * ((n + 1 : ℤ) : ℝ) * L - w) by funext w; ring_nf, this,
        setLIntegral_congr Ico_ae_eq_Ioc]
      congr 2 <;> push_cast <;> ring
  rw [← setLIntegral_univ, ← iUnion_Ioc_add_zsmul h2L a,
    lintegral_iUnion (fun _ => measurableSet_Ioc) (pairwise_disjoint_Ioc_add_zsmul a (2 * L))]
  simp_rw [hcell]
  rw [ENNReal.tsum_add]
  congr 1
  exact ((Equiv.addRight (1 : ℤ)).tsum_eq
    (fun n : ℤ => ∫⁻ w in Ioc a (a + L), h (2 * a - w + 2 * (n : ℝ) * L))).symm

end HeatSq
end LQGMetric
