import LQGMetric.Field.MarkovAsmA
import LQGMetric.Field.MarkovAdmCov
import LQGMetric.Field.RandomDistVersion

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# Assembly of LM Lemma 2.1, part B: from pairing-level statements to distributions (P2-LMASM)

The Markov decomposition was proved at the level of pairings (`MarkovExt`, `MarkovAdmCov`,
`MarkovGermVer2E`): statements about the processes `φ ↦ h(φ) − zbExt φ` and `φ ↦ zbExt φ`. Here
they are transferred to a distribution-valued version `hz` (`MarkovVer2.exists_dist_version_zbExt`)
and `h − hz`, using that the cylinder σ-algebra of `𝒟'(ℂ)` is generated by the countably many
pairings `pairJ` (`distOn_measurableSpace_eq_comap_pairJ`, `measurableEmbedding_pairJ`), so that
"`hz ω φ = zbExt φ ω` a.s. for each `φ`" upgrades to a.s. equality of the `pairJ`-coordinates.

* `isZeroBoundaryGFF_restrict` : `hz|_V` is a zero-boundary GFF on `V`;
* `indepFun_sub_dist` : `h − hz` and `hz` are independent;
* `indep_dist_fieldSigmaClosed` : `hz` is independent of the germ `σ(h|_{ℂ∖V})`;
* `exists_germ_dist_version` : `h − hz` is a.s. equal to a germ-measurable random distribution.

Standard measure-theoretic bookkeeping; own elementary proofs.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Topology Set Metric TopologicalSpace

namespace LQGMetric
namespace MarkovAsm

open MarkovZB MarkovExt MarkovAdm MarkovGerm Blueprint

variable {Ω : Type} [mΩ : MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
  {h : Ω → DistC}

/-- the restriction of a family of pairings to the countable coordinates `comb ⊤ c` -/
def coordR (x : TestC → ℝ) : CoordJ → ℝ := fun c => x (comb ⊤ c)

lemma measurable_coordR : Measurable coordR :=
  measurable_pi_iff.2 fun c => measurable_pi_apply _

lemma comap_distC_eq (X : Ω → DistC) :
    MeasurableSpace.comap X inferInstance =
      MeasurableSpace.comap (fun ω => pairJ ⊤ (X ω)) MeasurableSpace.pi := by
  rw [show (inferInstance : MeasurableSpace DistC) = DistOn.measurableSpace ⊤ from rfl,
    distOn_measurableSpace_eq_comap_pairJ, MeasurableSpace.comap_comp]
  rfl

lemma ae_pairJ_eq {X : Ω → DistC} {Y : TestC → Ω → ℝ} (he : ∀ φ, (fun ω => X ω φ) =ᵐ[P] Y φ) :
    (fun ω => pairJ ⊤ (X ω)) =ᵐ[P] fun ω => coordR (fun φ => Y φ ω) := by
  filter_upwards [ae_all_iff.2 fun c : CoordJ => he (comb ⊤ c)] with ω hω
  funext c
  exact hω c

/-- a.s. modification preserves independence from a fixed σ-algebra -/
lemma indep_comap_congr {β : Type} [MeasurableSpace β] {f g : Ω → β} {m : MeasurableSpace Ω}
    (hm : m ≤ mΩ)
    (hf : Indep (MeasurableSpace.comap f inferInstance) m P) (hfg : f =ᵐ[P] g) :
    Indep (MeasurableSpace.comap g inferInstance) m P := by
  have h1 : @IndepFun Ω β Ω _ _ m f id P := by
    rw [IndepFun_iff_Indep, MeasurableSpace.comap_id]; exact hf
  have h2 := h1.congr hfg (EventuallyEq.refl _ _)
  rw [IndepFun_iff_Indep, MeasurableSpace.comap_id] at h2
  exact h2

variable (hh : IsNormalizedWPGFF h P) {V : Opens ℂ} (hV : Disjoint (V : Set ℂ) (sphere 0 1))
  {hz : Ω → DistC} (hzm : Measurable hz)
  (hzae : ∀ φ : TestC, (fun ω => hz ω φ) =ᵐ[P] zbExt hh.1 V φ)
include hh hzae

lemma pair_sub_ae (φ : TestC) :
    (fun ω => (h ω - hz ω) φ) =ᵐ[P] fun ω => h ω φ - zbExt hh.1 V φ ω := by
  filter_upwards [hzae φ] with ω hω
  rw [sub_apply, hω]

include hV in
/-- `h − hz ⫫ hz` -/
theorem indepFun_sub_dist : IndepFun (fun ω => h ω - hz ω) hz P := by
  have h0 := (indepFun_harm_zbExt_of_disjoint hh hV).comp measurable_coordR measurable_coordR
  have h1 := h0.congr (ae_pairJ_eq (pair_sub_ae hh hzae)).symm (ae_pairJ_eq hzae).symm
  rw [IndepFun_iff_Indep] at h1 ⊢
  rw [comap_distC_eq, comap_distC_eq]
  exact h1

include hV in
/-- `hz` is independent of the germ `σ(h|_{ℂ∖V})` -/
theorem indep_dist_fieldSigmaClosed :
    Indep (MeasurableSpace.comap hz inferInstance) (fieldSigmaClosed h (V : Set ℂ)ᶜ) P := by
  have h0 := indep_zbExt_fieldSigmaClosed hh hV
  have hle : MeasurableSpace.comap (fun ω => coordR (fun φ : TestC => zbExt hh.1 V φ ω))
      MeasurableSpace.pi ≤
      MeasurableSpace.comap (fun ω (φ : TestC) => zbExt hh.1 V φ ω) MeasurableSpace.pi := by
    rw [show (fun ω => coordR (fun φ : TestC => zbExt hh.1 V φ ω)) =
      coordR ∘ (fun ω (φ : TestC) => zbExt hh.1 V φ ω) from rfl, ← MeasurableSpace.comap_comp]
    exact MeasurableSpace.comap_mono measurable_coordR.comap_le
  have hm : fieldSigmaClosed h (V : Set ℂ)ᶜ ≤ mΩ := by
    refine (iInf₂_le 1 one_pos).trans ?_
    exact ((measurable_restrictTo _).comp hh.1.measurable).comap_le
  have h1 := indep_comap_congr hm (indep_of_indep_of_le_left h0 hle) (ae_pairJ_eq hzae).symm
  rw [comap_distC_eq]
  exact h1

omit hh hzae in
/-- a.s. modification of a zero-boundary GFF process -/
lemma isZBGFFProcess_congr {U : Opens ℂ} {X Y : TestOn U → Ω → ℝ} (hX : IsZBGFFProcess U X P)
    (hY : ∀ φ, Measurable (Y φ)) (he : ∀ φ, X φ =ᵐ[P] Y φ) : IsZBGFFProcess U Y P := by
  refine ⟨hY, hX.gaussian.congr he, fun φ => ?_, fun φ ψ => ?_⟩
  · rw [← integral_congr_ae (he φ)]; exact hX.centered φ
  · rw [← hX.covariance_eq φ ψ]
    unfold covariance
    rw [integral_congr_ae (he φ), integral_congr_ae (he ψ)]
    refine integral_congr_ae ?_
    filter_upwards [he φ, he ψ] with ω h1 h2
    simp only [h1, h2]

include hV hzm in
/-- `hz|_V` is a zero-boundary GFF on `V` -/
theorem isZeroBoundaryGFF_restrict :
    IsZeroBoundaryGFF V (fun ω => restrictTo V (hz ω)) P := by
  refine ⟨(measurable_restrictTo V).comp hzm,
    isZBGFFProcess_congr (isZBGFFProcess_zbProc hh.1 (zbAdmissible_of_disjoint_sphere hV))
      (fun φ => (measurable_distOn_apply φ).comp ((measurable_restrictTo V).comp hzm))
      fun φ => ?_⟩
  filter_upwards [hzae (extC V φ), zbExt_ae_eq_zbProc hh.1 φ] with ω h1 h2
  rw [← h2, ← h1]
  rfl

/-- **`h − hz` is determined by the germ `σ(h|_{ℂ∖V})`**, given germ versions of its pairings -/
theorem exists_germ_dist_version
    (hG : ∀ φ : TestC, ∃ G : Ω → ℝ, Measurable[fieldSigmaClosed h (V : Set ℂ)ᶜ] G ∧
      (fun ω => h ω φ - zbExt hh.1 V φ ω) =ᵐ[P] G) :
    ∃ G : Ω → DistC, @Measurable Ω DistC (fieldSigmaClosed h (V : Set ℂ)ᶜ) _ G ∧
      (fun ω => h ω - hz ω) =ᵐ[P] G := by
  choose Gφ hGm hGae using hG
  let Φ : Ω → CoordJ → ℝ := fun ω c => Gφ (comb ⊤ c) ω
  have hΦ : @Measurable Ω (CoordJ → ℝ) (fieldSigmaClosed h (V : Set ℂ)ᶜ) _ Φ :=
    @measurable_pi_iff Ω CoordJ (fun _ => ℝ) (fieldSigmaClosed h (V : Set ℂ)ᶜ) _ _ |>.2
      fun c => hGm (comb ⊤ c)
  refine ⟨fun ω => pairJInv ⊤ (Φ ω), (measurable_pairJInv ⊤).comp hΦ, ?_⟩
  have h1 := ae_pairJ_eq (pair_sub_ae hh hzae)
  filter_upwards [h1, ae_all_iff.2 fun c : CoordJ => hGae (comb ⊤ c)] with ω hω hω'
  have : Φ ω = pairJ ⊤ (h ω - hz ω) := by
    rw [hω]; funext c; exact (hω' c).symm
  rw [this, pairJInv_pairJ]

end MarkovAsm
end LQGMetric
