import LQGMetric.Field.StandardBorelRange
import Mathlib.MeasureTheory.Constructions.Projective

/-!
# Random distributions: weak-* Borel σ-algebra = cylinder σ-algebra (task P2-RANDDIST)

Berestycki–Powell, *Gaussian free field and Liouville quantum gravity*, arXiv:2404.16642
(`literature/src/2404.16642/definitionGFF.tex` l. 891–912): `𝒟'_0(D)` carries the weak-*
topology, and "a random variable `X` in the space of distributions is a function
`X : Ω → 𝒟'_0(D)` which is measurable with respect to the Borel σ-field induced by the weak-*
topology" (l. 907). Our `DistOn.measurableSpace` (FOUNDATIONS D2/F1) is the cylinder σ-algebra of
the pairings. Here:

* `weakStarTop U`: the weak-* topology on `𝒟'(U)` (induced by all evaluations `h ↦ h φ`);
* `borel_weakStar_eq`: its Borel σ-algebra is `DistOn.measurableSpace U`;
* `measurable_weakStar_iff`: `X : Ω → 𝒟'(U)` is a random distribution in BP's sense iff every
  pairing `ω ↦ ⟨X ω, φ⟩` is a real random variable;
* `measure_ext_of_finiteDim`: the law of a random distribution is determined by the
  finite-dimensional laws of its pairings.

Proof of `borel_weakStar_eq` (own argument in the spirit of BP's appendix, `SLE.tex` l. 470–540:
polar sets on which the weak-* topology is generated by a countable dense family). A basic
weak-* neighbourhood of `h₀` involves finitely many test functions, all supported in some `K_n`;
`h₀` lies in a "polar" `P n C N = {h | |h ψ| ≤ C ‖ψ‖_{C^N} on 𝓓_{K_n}}` (measurable: it is cut
out by the countable family `comb c`), and on `P n C N` the neighbourhood is approximated by a
rational cylinder in the countable family. So every weak-* open set is a countable union of
measurable sets.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Filter Topology Set TopologicalSpace
open scoped Distributions

namespace LQGMetric

section
variable (U : Opens ℂ)

/-- the weak-* topology on `𝒟'(U)`: pointwise convergence on test functions (BP l. 902–905) -/
@[instance_reducible] def weakStarTop : TopologicalSpace (DistOn U) :=
  TopologicalSpace.induced (fun (h : DistOn U) (φ : TestOn U) => h φ) Pi.topologicalSpace

end

end LQGMetric
