import Mathlib.Analysis.Distribution.TestFunction
import Mathlib.Topology.ContinuousMap.SecondCountableSpace
import Mathlib.Topology.ContinuousMap.Compact
import Mathlib.LinearAlgebra.Multilinear.FiniteDimensional
import Mathlib.Analysis.Normed.Module.FiniteDimension

/-!
# `𝓓_K(ℂ)` is second countable (first step towards `StandardBorelSpace (DistOn U)`)

FOUNDATIONS §9 item 4: the cylinder σ-algebra of `𝒟'(U)` is generated by countably many pairings
because `𝓓(U)` is separable. Here we prove the base case: for a compact `K ⊆ ℂ`, the Fréchet
space `𝓓_K = 𝓓^{⊤}_{K}(ℂ, ℝ)` is second countable (hence separable).

Proof: the topology of `𝓓_K` is `⨅ᵢ` of the topologies induced by `f ↦ Dⁱf ∈ ℂ →ᵇ M_i`
(mathlib's definition). For functions vanishing off `K` the sup-distance over `ℂ` equals the
sup-distance over `K`, so each of these induced topologies equals the one induced by
`f ↦ Dⁱf|_K ∈ C(K, M_i)`, and `C(K, M_i)` is second countable (`M_i` finite dimensional;
mathlib `ContinuousMap.instSecondCountableTopology`). A countable infimum of second countable
topologies is second countable (`secondCountableTopology_iInf`).

Standard fact (e.g. Trèves, *Topological Vector Spaces, Distributions and Kernels*, Ch. 14);
the argument above is an own elementary proof adapted to mathlib's definitions.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open Topology Set TopologicalSpace Filter
open scoped Distributions

namespace LQGMetric

/-- continuous multilinear maps between finite-dimensional real spaces form a finite-dimensional
space (they inject into all multilinear maps, mathlib `Module.Finite.multilinearMap`) -/
instance finiteDimensional_cmm (i : ℕ) : FiniteDimensional ℝ (ℂ [×i]→L[ℝ] ℝ) :=
  FiniteDimensional.of_injective
    (ContinuousMultilinearMap.toMultilinearMapLinear (R' := ℝ) (A := ℝ))
    ContinuousMultilinearMap.toMultilinearMap_injective

instance secondCountable_cmm (i : ℕ) : SecondCountableTopology (ℂ [×i]→L[ℝ] ℝ) := by
  have : ProperSpace (ℂ [×i]→L[ℝ] ℝ) := FiniteDimensional.proper_real _
  infer_instance

/-- two maps into pseudometric spaces with the same distances induce the same topology -/
theorem induced_eq_of_dist_eq {X A B : Type*} [PseudoMetricSpace A] [PseudoMetricSpace B]
    (f : X → A) (g : X → B) (h : ∀ x y, dist (f x) (f y) = dist (g x) (g y)) :
    TopologicalSpace.induced f inferInstance = TopologicalSpace.induced g inferInstance := by
  refine TopologicalSpace.ext_nhds fun x => ?_
  rw [nhds_induced, nhds_induced]
  refine ((Metric.nhds_basis_ball.comap f).ext (Metric.nhds_basis_ball.comap g) ?_ ?_)
  · intro ε hε
    refine ⟨ε, hε, fun y hy => ?_⟩
    simp only [mem_preimage, Metric.mem_ball] at hy ⊢
    rwa [h]
  · intro ε hε
    refine ⟨ε, hε, fun y hy => ?_⟩
    simp only [mem_preimage, Metric.mem_ball] at hy ⊢
    rwa [← h]

section
variable (K : Compacts ℂ)

/-- `f ↦ Dⁱf|_K ∈ C(K, M_i)` -/
def derivOnK (i : ℕ) (f : 𝓓^{⊤}_{K}(ℂ, ℝ)) : C((K : Set ℂ), ℂ [×i]→L[ℝ] ℝ) :=
  ⟨fun y => iteratedFDeriv ℝ i f y,
    (f.contDiff.continuous_iteratedFDeriv (by exact_mod_cast le_top)).comp continuous_subtype_val⟩

theorem dist_derivOnK (i : ℕ) (f g : 𝓓^{⊤}_{K}(ℂ, ℝ)) :
    dist (ContDiffMapSupportedIn.structureMapLM ℝ ⊤ i f)
      (ContDiffMapSupportedIn.structureMapLM ℝ ⊤ i g) =
    dist (derivOnK K i f) (derivOnK K i g) := by
  apply le_antisymm
  · refine (BoundedContinuousFunction.dist_le dist_nonneg).2 fun y => ?_
    simp only [ContDiffMapSupportedIn.structureMapLM_top_apply]
    by_cases hy : y ∈ (K : Set ℂ)
    · exact ContinuousMap.dist_apply_le_dist (f := derivOnK K i f) (g := derivOnK K i g) ⟨y, hy⟩
    · rw [f.iteratedFDeriv_zero_on_compl hy, g.iteratedFDeriv_zero_on_compl hy, dist_self]
      exact dist_nonneg
  · refine (ContinuousMap.dist_le dist_nonneg).2 fun y => ?_
    have := BoundedContinuousFunction.dist_coe_le_dist (f := ContDiffMapSupportedIn.structureMapLM
      ℝ ⊤ i f) (g := ContDiffMapSupportedIn.structureMapLM ℝ ⊤ i g) (y : ℂ)
    simpa [ContDiffMapSupportedIn.structureMapLM_top_apply, derivOnK] using this

/-- `𝓓_K(ℂ)` is second countable -/
instance secondCountableTopology_testK : SecondCountableTopology 𝓓^{⊤}_{K}(ℂ, ℝ) := by
  show @SecondCountableTopology _ (⨅ (i : ℕ), TopologicalSpace.induced
    (ContDiffMapSupportedIn.structureMapLM ℝ ⊤ i) inferInstance)
  refine secondCountableTopology_iInf fun i => ?_
  rw [induced_eq_of_dist_eq _ (derivOnK K i) (dist_derivOnK K i)]
  exact secondCountableTopology_induced _ _ _

end

end LQGMetric
