import LQGMetric.Field.Measurable
import LQGMetric.Field.StandardBorelTest
import Mathlib.Topology.Compactness.SigmaCompact

/-!
# The cylinder σ-algebra of `𝒟'(U)` is generated by countably many pairings

FOUNDATIONS §9 item 4, first half (towards `StandardBorelSpace (DistOn U)`): there is a countable
family `φ_{n,k} ∈ 𝓓(U)` such that the cylinder σ-algebra of `𝒟'(U)` is the one generated by
`h ↦ ⟨h, φ_{n,k}⟩` (`distOn_measurableSpace_eq_comap`). Hence `𝒟'(U)` is countably generated,
and `h ↦ (⟨h, φ_{n,k}⟩)_{n,k}` is injective (`injective_distOn_pairings`).

Proof: take a compact exhaustion `K_n` of `U` and dense sequences `u_n` in the separable spaces
`𝓓_{K_n}` (`secondCountableTopology_testK`); every `φ ∈ 𝓓(U)` lies in some `𝓓_{K_n}` and is a
limit there of a sequence from `u_n`, so `⟨h, φ⟩` is a pointwise limit of generators
(mathlib `measurable_of_tendsto_metrizable`). Standard; own elementary proof.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Filter Topology Set TopologicalSpace
open scoped Distributions

namespace LQGMetric

instance locallyCompactSpace_opens (U : Opens ℂ) : LocallyCompactSpace U :=
  U.isOpen.locallyCompactSpace

section
variable (U : Opens ℂ)

/-- compact exhaustion of `U`, as compacts of `ℂ` -/
def exhaustK (n : ℕ) : Compacts ℂ :=
  ⟨(↑) '' CompactExhaustion.choice U n,
    ((CompactExhaustion.choice U).isCompact n).image continuous_subtype_val⟩

lemma exhaustK_subset (n : ℕ) : (exhaustK U n : Set ℂ) ⊆ U := by
  rintro _ ⟨x, _, rfl⟩; exact x.2

lemma exists_exhaustK_superset {C : Set ℂ} (hC : IsCompact C) (hCU : C ⊆ U) :
    ∃ n, C ⊆ exhaustK U n := by
  have hc : IsCompact ((↑) ⁻¹' C : Set U) := by
    rw [Subtype.isCompact_iff, image_preimage_eq_of_subset fun x hx => ⟨⟨x, hCU hx⟩, rfl⟩]
    exact hC
  obtain ⟨n, hn⟩ := (CompactExhaustion.choice U).exists_superset_of_isCompact hc
  refine ⟨n, fun x hx => ⟨⟨x, hCU hx⟩, hn hx, rfl⟩⟩

/-- dense sequences in `𝓓_{K_n}` -/
def denseSeqK (n : ℕ) : ℕ → 𝓓^{⊤}_{exhaustK U n}(ℂ, ℝ) :=
  Classical.choose (exists_dense_seq 𝓓^{⊤}_{exhaustK U n}(ℂ, ℝ))

lemma denseRange_denseSeqK (n : ℕ) : DenseRange (denseSeqK U n) :=
  Classical.choose_spec (exists_dense_seq 𝓓^{⊤}_{exhaustK U n}(ℂ, ℝ))

/-- the countable generating family `φ_{n,k}` -/
def distGen (j : ℕ × ℕ) : TestOn U :=
  TestFunction.ofSupportedIn (exhaustK_subset U j.1) (denseSeqK U j.1 j.2)

/-- the σ-algebra generated by the countable family of pairings -/
@[instance_reducible] def distGenMS : MeasurableSpace (DistOn U) :=
  MeasurableSpace.comap (fun (h : DistOn U) (j : ℕ × ℕ) => h (distGen U j)) MeasurableSpace.pi

theorem distOn_measurableSpace_eq_comap :
    DistOn.measurableSpace U =
      MeasurableSpace.comap (fun (h : DistOn U) (j : ℕ × ℕ) => h (distGen U j))
        MeasurableSpace.pi := by
  show _ = distGenMS U
  have hgen : ∀ j, Measurable[(distGenMS U)] fun h : DistOn U => h (distGen U j) := fun j =>
    (measurable_pi_apply j).comp (comap_measurable (m := MeasurableSpace.pi)
      (fun (h : DistOn U) (j : ℕ × ℕ) => h (distGen U j)))
  refine le_antisymm ?_ (measurable_pi_iff.2 fun j => measurable_distOn_apply _).comap_le
  show MeasurableSpace.comap _ _ ≤ (distGenMS U)
  refine Measurable.comap_le ?_
  let : MeasurableSpace (DistOn U) := distGenMS U
  refine Measurable.of_eval fun φ => ?_
  obtain ⟨n, hn⟩ := exists_exhaustK_superset U φ.hasCompactSupport.isCompact φ.tsupport_subset
  let ψ : 𝓓^{⊤}_{exhaustK U n}(ℂ, ℝ) :=
    ⟨φ, φ.contDiff, fun x hx => image_eq_zero_of_notMem_tsupport fun h => hx (hn h)⟩
  have hψ : TestFunction.ofSupportedIn (exhaustK_subset U n) ψ = φ := by ext; rfl
  obtain ⟨s, hs, hlim⟩ := mem_closure_iff_seq_limit.1 ((denseRange_denseSeqK U n) ψ)
  choose k hk using hs
  have hT : Tendsto (fun i (h : DistOn U) => h (distGen U (n, k i))) atTop
      (𝓝 fun h : DistOn U => h φ) := by
    refine tendsto_pi_nhds.2 fun h => ?_
    have hc : Continuous fun χ : 𝓓^{⊤}_{exhaustK U n}(ℂ, ℝ) =>
        h (TestFunction.ofSupportedIn (exhaustK_subset U n) χ) :=
      (map_continuous h).comp
        (TestFunction.ofSupportedInCLM ℝ (exhaustK_subset U n)).continuous
    have := (hc.tendsto ψ).comp hlim
    rw [hψ] at this
    refine this.congr fun i => ?_
    simp only [Function.comp_apply, distGen, ← hk i]
  exact @measurable_of_tendsto_metrizable _ _ (distGenMS U) _ _ _ _ _ _ (fun i => hgen (n, k i)) hT

theorem injective_distOn_pairings :
    Function.Injective fun (h : DistOn U) (j : ℕ × ℕ) => h (distGen U j) := by
  intro h₁ h₂ heq
  have hmeas := distOn_measurableSpace_eq_comap U
  -- both pairings agree on the generators, hence on every test function (density)
  ext φ
  obtain ⟨n, hn⟩ := exists_exhaustK_superset U φ.hasCompactSupport.isCompact φ.tsupport_subset
  let ψ : 𝓓^{⊤}_{exhaustK U n}(ℂ, ℝ) :=
    ⟨φ, φ.contDiff, fun x hx => image_eq_zero_of_notMem_tsupport fun h => hx (hn h)⟩
  have hψ : TestFunction.ofSupportedIn (exhaustK_subset U n) ψ = φ := by ext; rfl
  have hc : ∀ h : DistOn U, Continuous fun χ : 𝓓^{⊤}_{exhaustK U n}(ℂ, ℝ) =>
      h (TestFunction.ofSupportedIn (exhaustK_subset U n) χ) := fun h =>
    (map_continuous h).comp (TestFunction.ofSupportedInCLM ℝ (exhaustK_subset U n)).continuous
  have := ((denseRange_denseSeqK U n).equalizer (hc h₁) (hc h₂)
    (funext fun k => congrFun heq (n, k)))
  have := congrFun this ψ
  simpa [hψ] using this

instance countablyGenerated_distOn : MeasurableSpace.CountablyGenerated (DistOn U) := by
  rw [distOn_measurableSpace_eq_comap U]
  exact MeasurableSpace.CountablyGenerated.comap _

end

end LQGMetric
