import QuantumZipper.Proofs.Thm18.G2ClipNodes
import QuantumZipper.Proofs.Thm18.G2ClipReduce

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# G2-CONST: the arbitrary additive constant of `gffBase.X` is invisible to the G2/G3 scheme

`IsFreeGFFModConstH X P` constrains only balanced differences `X μ − X ν` (`μ(ℂ) = ν(ℂ)`); the
"constant" `c = X · refS` of the chosen base field `gffBase.X` (fixed by `Classical.choice`) is
an arbitrary random variable, possibly correlated with everything else. This file shows that
no quantity of the G2/G3 scheme sees it, so no definition or node has to change (DECISIONS.md,
G2-CONST decision).

* `normX X ω μ := X ω μ − μ(ℂ) · X ω refS` is again a free-boundary GFF modulo constants
  (`isFreeGFFModConstH_normX`), with `normX X ω refS = 0` (`normX_refS`): it is the base field
  with the constant pinned (`c ≡ 0`). `gffBaseN` is the corresponding `GFFBase`.
* `normField γ X ω` and `normField γ (normX X) ω` agree at every probability measure
  (`normField_normX_of_prob`), hence at every folded circle, hence have the same regularized
  circle averages (`avgReg_normField_normX`). Every scheme quantity is read through `avgReg`:
  the boundary measure (`qBoundaryMeasure_normField_normX`, `g3Hν_eq_normX`), the zoom law
  including all its test pairings `pairRaw` (`zoomLaw_normField_normX`), and the rooted events
  (`g3RootEvX_eq_normX`).
* The conditioning σ-algebras are generated by balanced differences, so they coincide
  (`outsideSigma2_normX`, `outsideSigmaPalm_normX`).

In particular `lawCyl` pairing against non-mass-zero test functions is harmless: `zoomLaw` pairs
`ρ` with the *canonical* zoomed field built from `avgReg (normField γ X ω)`, i.e. from the field
normalized by `X(refS) = 0`, which is the paper's normalization `h = 𝔥₀ + X − X(S)` of
Theorem 1.2 (Sheffield, arXiv:1012.4797, §1.4 and the proof of Theorem 1.8, p. 70).

Own elementary arguments (AGENT_GUIDE cost rule).
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Set
open scoped ENNReal NNReal

namespace QuantumZipper
namespace Thm18Asm

/-! ## The normalized base field -/

section General

variable {Ω : Type*}

/-- The base field with its additive constant pinned at the unit folded semicircle:
`X' μ = X μ − μ(ℂ) · X(refS)`. -/
def normX (X : Ω → FieldSample) : Ω → FieldSample :=
  fun ω μ => X ω μ - (μ univ).toReal * X ω refS

theorem normX_apply (X : Ω → FieldSample) (ω : Ω) (μ : Measure ℂ) :
    normX X ω μ = X ω μ - (μ univ).toReal * X ω refS := rfl

theorem normX_refS (X : Ω → FieldSample) (ω : Ω) : normX X ω refS = 0 := by
  simp [normX_apply, measure_univ]

/-- Balanced differences are unchanged. -/
theorem normX_sub_of_mass_eq (X : Ω → FieldSample) (ω : Ω) {μ ν : Measure ℂ}
    (h : μ univ = ν univ) : normX X ω μ - normX X ω ν = X ω μ - X ω ν := by
  simp only [normX_apply, h]; ring

/-- At a probability measure, `normX X ω μ = X ω μ − X ω refS`. -/
theorem normX_of_prob (X : Ω → FieldSample) (ω : Ω) (μ : Measure ℂ) [IsProbabilityMeasure μ] :
    normX X ω μ = X ω μ - X ω refS := by
  simp [normX_apply, measure_univ]

/-- **`normX` of a free-boundary GFF modulo constants is one again.** -/
theorem isFreeGFFModConstH_normX [MeasurableSpace Ω] {X : Ω → FieldSample} {P : Measure Ω}
    (hX : IsFreeGFFModConstH X P) : IsFreeGFFModConstH (normX X) P := by
  have hbal : ∀ μ ν : Measure ℂ, μ univ = ν univ →
      (fun ω => normX X ω μ - normX X ω ν) = fun ω => X ω μ - X ω ν :=
    fun μ ν h => funext fun ω => normX_sub_of_mass_eq X ω h
  refine ⟨fun μ => (hX.measurable_coord μ).sub (measurable_const.mul (hX.measurable_coord refS)),
    ?_, ?_, ?_, ?_⟩
  · have e : (fun (p : {p : Measure ℂ × Measure ℂ //
          IsAdmissibleH p.1 ∧ IsAdmissibleH p.2 ∧ p.1 Set.univ = p.2 Set.univ})
        (ω : Ω) => normX X ω p.1.1 - normX X ω p.1.2) =
        fun p ω => X ω p.1.1 - X ω p.1.2 :=
      funext fun p => hbal _ _ p.2.2.2
    rw [e]; exact hX.gaussian
  · intro μ ν hμ hν hm
    rw [hbal μ ν hm]; exact hX.centered μ ν hμ hν hm
  · intro p q hp1 hp2 hpm hq1 hq2 hqm
    rw [hbal _ _ hpm, hbal _ _ hqm]
    exact hX.covariance_eq p q hp1 hp2 hpm hq1 hq2 hqm
  · intro μ ν hμ hν a b
    filter_upwards [hX.linear μ ν hμ hν a b] with ω hω
    have := hμ.1; have := hν.1
    have hm : ((a • μ + b • ν) univ).toReal = (a : ℝ) * (μ univ).toReal +
        (b : ℝ) * (ν univ).toReal := by
      rw [Measure.add_apply, Measure.smul_apply, Measure.smul_apply,
        ENNReal.toReal_add (by simp [ENNReal.mul_eq_top, measure_ne_top])
          (by simp [ENNReal.mul_eq_top, measure_ne_top]),
        ENNReal.smul_def, ENNReal.smul_def, smul_eq_mul, smul_eq_mul, ENNReal.toReal_mul,
        ENNReal.toReal_mul]
      simp
    simp only [normX_apply, hω, hm]
    ring

/-- `normField` does not see the constant: at probability measures it is unchanged. -/
theorem normField_normX_of_prob (γ : ℝ) (X : Ω → FieldSample) (ω : Ω) (μ : Measure ℂ)
    [IsProbabilityMeasure μ] : normField γ (normX X) ω μ = normField γ X ω μ := by
  show ofFun (h0rev (γ ^ 2)) μ + (normX X ω μ - normX X ω refS) = _
  rw [normX_of_prob, normX_refS, sub_zero]
  rfl

end General

/-! ## The chosen base sample -/

end Thm18Asm
end QuantumZipper
