import QuantumZipper.Proofs.Thm18.G3SchemeCI
import QuantumZipper.Proofs.GFF.K3.HalfDiscMarkov

/-!
# G3 scheme: the two-region domain Markov property of the free field

Sheffield, arXiv:1012.4797, proof of Theorem 1.8 (§5.4, p. 71): "if we condition on the GFF
values [outside the two regions] … the conditional law of the restrictions of `h` to the two
[regions] are independent by the standard GFF Markov property" (Sheffield, *Gaussian free fields
for mathematicians*, §2.6). Here the two regions are disjoint half-discs `B(t₁, r₁) ∩ ℍ` and
`B(t₂, r₂) ∩ ℍ` centred on `ℝ` (`r₁ + r₂ ≤ |t₁ − t₂|`), for a free-boundary GFF modulo
constants `X` on `ℍ`.

* `outsideSigma2 X t₁ r₁ t₂ r₂`: generated by balanced differences `X μ − X ν` of admissible
  measures giving no mass to either open disc (the field outside both regions);
* `localSigma X t r`: generated by the local part `markovZ X t r` on local measures;
* `indep_localSigma_sup_outsideSigma2`: `localSigma₁ ⊥ localSigma₂ ⊔ outsideSigma2`, from the
  one-region Markov property `K3.indep_markovZ_outside` (the second region's local part and the
  field outside both regions are functions of the field outside the first region);
* `measurable_harmH_outsideSigma2`: the harmonic part of either region is
  `outsideSigma2`-measurable;
* `condIndepCE_twoHalfDisc`: anything measurable w.r.t. region 1's local part and the outside is
  conditionally independent, given `outsideSigma2`, of anything measurable w.r.t. region 2's local
  part and the outside (with `condIndepCE_of_indep_sup`).

The reduction of the two-region property to the one-region property is an own elementary
argument (it is the usual one: Sheffield 2007, §2.6, orthogonal decomposition).
-/

noncomputable section

open MeasureTheory ProbabilityTheory Metric Set MeasurableSpace
open scoped ENNReal

namespace QuantumZipper
namespace Thm18Asm

open K3

variable {Ω : Type*} [mΩ : MeasurableSpace Ω] {P : Measure Ω} {X : Ω → FieldSample}

/-- Balanced admissible pairs giving no mass to either of two open discs. -/
abbrev OutIdx2 (t₁ r₁ t₂ r₂ : ℝ) :=
  {p : Measure ℂ × Measure ℂ // IsAdmissibleH p.1 ∧ IsAdmissibleH p.2 ∧
    p.1 Set.univ = p.2 Set.univ ∧ p.1 (ball (t₁ : ℂ) r₁ ∪ ball (t₂ : ℂ) r₂) = 0 ∧
    p.2 (ball (t₁ : ℂ) r₁ ∪ ball (t₂ : ℂ) r₂) = 0}

/-- The σ-algebra of the free field outside two half-discs. -/
def outsideSigma2 (X : Ω → FieldSample) (t₁ r₁ t₂ r₂ : ℝ) : MeasurableSpace Ω :=
  ⨆ (p : OutIdx2 t₁ r₁ t₂ r₂), MeasurableSpace.comap (fun ω => X ω p.1.1 - X ω p.1.2) inferInstance

/-- The σ-algebra of the local part of the free field in the half-disc `B(t, r) ∩ ℍ`. -/
def localSigma (X : Ω → FieldSample) (t r : ℝ) : MeasurableSpace Ω :=
  ⨆ μ : {μ // IsLocalH t r μ}, MeasurableSpace.comap (fun ω => markovZ X t r ω μ.1) inferInstance

theorem measurable_outsideSigma2 {t₁ r₁ t₂ r₂ : ℝ} {μ ν : Measure ℂ} (hμ : IsAdmissibleH μ)
    (hν : IsAdmissibleH ν) (hm : μ Set.univ = ν Set.univ)
    (hμB : μ (ball (t₁ : ℂ) r₁ ∪ ball (t₂ : ℂ) r₂) = 0)
    (hνB : ν (ball (t₁ : ℂ) r₁ ∪ ball (t₂ : ℂ) r₂) = 0) :
    Measurable[outsideSigma2 X t₁ r₁ t₂ r₂] fun ω => X ω μ - X ω ν :=
  measurable_iff_comap_le.2 (le_iSup (fun p : OutIdx2 t₁ r₁ t₂ r₂ =>
    MeasurableSpace.comap (fun ω => X ω p.1.1 - X ω p.1.2) inferInstance)
    ⟨(μ, ν), hμ, hν, hm, hμB, hνB⟩)

theorem outsideSigma2_le (hX : IsFreeGFFModConstH X P) (t₁ r₁ t₂ r₂ : ℝ) :
    outsideSigma2 X t₁ r₁ t₂ r₂ ≤ mΩ :=
  iSup_le fun _ => measurable_iff_comap_le.1
    ((hX.measurable_coord _).sub (hX.measurable_coord _))

theorem localSigma_le (hX : IsFreeGFFModConstH X P) (t r : ℝ) : localSigma X t r ≤ mΩ :=
  iSup_le fun _ => measurable_iff_comap_le.1
    ((hX.measurable_coord _).sub (hX.measurable_coord _))

/-- The field outside both regions is a function of the field outside the first. -/
theorem outsideSigma2_le_outsideSigma (t₁ r₁ t₂ r₂ : ℝ) :
    outsideSigma2 X t₁ r₁ t₂ r₂ ≤ outsideSigma X t₁ r₁ :=
  iSup_le fun p => measurable_iff_comap_le.1 (measurable_outsideSigma p.2.1 p.2.2.1 p.2.2.2.1
    (measure_mono_null subset_union_left p.2.2.2.2.1)
    (measure_mono_null subset_union_left p.2.2.2.2.2))

/-- A half-disc Poisson measure of the second region gives no mass to the first open disc. -/
theorem halfDiscPoisson_ball_other {t₁ r₁ t₂ r₂ : ℝ} (hr₂ : 0 < r₂)
    (hd : r₁ + r₂ ≤ dist (t₁ : ℂ) t₂) (z : ℂ) :
    halfDiscPoisson t₂ r₂ z (ball (t₁ : ℂ) r₁) = 0 := by
  refine measure_mono_null ?_ (halfDiscPoisson_compl_eq_zero hr₂ z)
  intro w hw hw'
  have hdis : Disjoint (closedBall (t₂ : ℂ) r₂) (ball (t₁ : ℂ) r₁) :=
    closedBall_disjoint_ball (by rw [dist_comm, add_comm]; exact hd)
  exact hdis.ne_of_mem (sphere_subset_closedBall hw'.1) hw rfl

/-- The second region's local part is a function of the field outside the first region. -/
theorem localSigma_le_outsideSigma {t₁ r₁ t₂ r₂ : ℝ} (hr₂ : 0 < r₂)
    (hd : r₁ + r₂ ≤ dist (t₁ : ℂ) t₂) : localSigma X t₂ r₂ ≤ outsideSigma X t₁ r₁ := by
  refine iSup_le fun μ => measurable_iff_comap_le.1 ?_
  obtain ⟨hμa, hμb⟩ := μ.2.bal_spec hr₂
  obtain ⟨-, r', hr', hμr⟩ := μ.2
  have hμ1 : μ.1 (ball (t₁ : ℂ) r₁) = 0 := by
    refine measure_mono_null ?_ hμr
    intro w hw hw'
    have hdis : Disjoint (closedBall (t₂ : ℂ) r₂) (ball (t₁ : ℂ) r₁) :=
      closedBall_disjoint_ball (by rw [dist_comm, add_comm]; exact hd)
    exact hdis.ne_of_mem (closedBall_subset_closedBall hr'.le hw') hw rfl
  exact measurable_outsideSigma μ.2.1 hμa hμb hμ1
    (bal_null_of_forall measurableSet_ball fun z => halfDiscPoisson_ball_other hr₂ hd z)

/-- **Two-region Markov independence.** For disjoint half-discs, the local part of the first
region is independent of the local part of the second region together with the field outside
both. -/
theorem indep_localSigma_sup_outsideSigma2 [IsProbabilityMeasure P] (hX : IsFreeGFFModConstH X P)
    {t₁ r₁ t₂ r₂ : ℝ} (hr₁ : 0 < r₁) (hr₂ : 0 < r₂) (hd : r₁ + r₂ ≤ dist (t₁ : ℂ) t₂) :
    Indep (localSigma X t₁ r₁) (localSigma X t₂ r₂ ⊔ outsideSigma2 X t₁ r₁ t₂ r₂) P :=
  indep_of_indep_of_le_right (indep_markovZ_outside hX hr₁)
    (sup_le (localSigma_le_outsideSigma hr₂ hd) (outsideSigma2_le_outsideSigma t₁ r₁ t₂ r₂))

/-- The conditioning σ-algebra of the G3 scheme on `Ω × E`: the field outside both regions and
the adjoined coordinate (the Palm length `ℓ`). -/
def outsideSigmaPalm (E : Type*) [mE : MeasurableSpace E] (X : Ω → FieldSample)
    (t₁ r₁ t₂ r₂ : ℝ) : MeasurableSpace (Ω × E) :=
  (outsideSigma2 X t₁ r₁ t₂ r₂).comap Prod.fst ⊔ mE.comap Prod.snd

/-- **Two-region conditional independence for the Palm scheme.** On `Ω × E` with law
`w · (P ⊗ λ)`, where `w` is measurable w.r.t. region 1's local part, the outside field and the
extra coordinate, anything measurable w.r.t. region 1's local part and the conditioning
σ-algebra is conditionally independent, given `outsideSigmaPalm`, of anything measurable w.r.t.
region 2's local part and the conditioning σ-algebra. -/
theorem condIndepCE_twoHalfDisc_palm [IsProbabilityMeasure P] (hX : IsFreeGFFModConstH X P)
    {t₁ r₁ t₂ r₂ : ℝ} (hr₁ : 0 < r₁) (hr₂ : 0 < r₂) (hd : r₁ + r₂ ≤ dist (t₁ : ℂ) t₂)
    {E : Type*} [mE : MeasurableSpace E] {L₀ : Measure E} [IsProbabilityMeasure L₀]
    {w : Ω × E → NNReal}
    (hw : Measurable[(localSigma X t₁ r₁).comap Prod.fst ⊔ outsideSigmaPalm E X t₁ r₁ t₂ r₂] w)
    (hwi : Integrable (fun x => (w x : ℝ)) (P.prod L₀))
    [IsProbabilityMeasure ((P.prod L₀).withDensity fun x => (w x : ℝ≥0∞))]
    {α β : Type*} [MeasurableSpace α] [MeasurableSpace β] {U : Ω × E → α} {V : Ω × E → β}
    (hU : Measurable[(localSigma X t₁ r₁).comap Prod.fst ⊔ outsideSigmaPalm E X t₁ r₁ t₂ r₂] U)
    (hV : Measurable[(localSigma X t₂ r₂).comap Prod.fst ⊔ outsideSigmaPalm E X t₁ r₁ t₂ r₂] V) :
    CondIndepCE (outsideSigmaPalm E X t₁ r₁ t₂ r₂) U V
      ((P.prod L₀).withDensity fun x => (w x : ℝ≥0∞)) := by
  have hle : ∀ {𝒞 : MeasurableSpace Ω}, 𝒞 ≤ mΩ →
      𝒞.comap Prod.fst ≤ @Prod.instMeasurableSpace Ω E mΩ mE :=
    fun h => (comap_mono h).trans measurable_fst.comap_le
  have hO : outsideSigmaPalm E X t₁ r₁ t₂ r₂ ≤ (inferInstance : MeasurableSpace (Ω × E)) :=
    sup_le (hle (outsideSigma2_le hX _ _ _ _)) measurable_snd.comap_le
  have hind := indep_comap_fst_sup_snd (L₀ := L₀) (localSigma_le hX t₁ r₁)
    (sup_le (localSigma_le hX t₂ r₂) (outsideSigma2_le hX t₁ r₁ t₂ r₂))
    (indep_localSigma_sup_outsideSigma2 hX hr₁ hr₂ hd)
  rw [MeasurableSpace.comap_sup, sup_assoc] at hind
  exact condIndepCE_of_condExp_sup_eq (hle (localSigma_le hX _ _)) (hle (localSigma_le hX _ _)) hO
    (fun _ hF => condExp_sup_eq_withDensity (hle (localSigma_le hX _ _))
      (hle (localSigma_le hX _ _)) hO
      (fun _ hF' => condExp_indicator_sup_eq (hle (localSigma_le hX _ _))
        (hle (localSigma_le hX _ _)) hO hind hF') hw hwi hF) hU hV

end Thm18Asm
end QuantumZipper
