import QuantumZipper.Proofs.Thm18.G2AgreeCond
import QuantumZipper.Proofs.Thm18.G2AgreeMass
import QuantumZipper.Proofs.Thm18.G2PalmMain
import QuantumZipper.Proofs.Thm18.G3Zc2CondU

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# G3PATH-FIX (1): the G2 conditioning variables as events of far Gaussian pairs

The conditioning variables of the fixed-point G2 leaves (outside coordinates, cut lengths, the
truncation mass) are a.s. equal to maps measurable for the D3⁺ conditioning σ-algebra
`condSigma () (palmCField X x) ρ` (`G2RootXCondStmt`, `G2RootRCondStmt`, proved). That σ-algebra
is generated by the balanced pair increments of the free field carried outside `B(x, ρ)`, i.e. by
the Gaussian family `gaussFam X (g3fPairs x ρ)` indexed by `OutIdx 0 ρ`. Hence every conditioning
event is a preimage `{gaussFam ∈ B}`, the form required by ZOOM-C's conditional decorrelation
(`G3Cv.cond_zoom_palm_free'`), and the pairs, translated back by `−x`, are far from `0`.

Sheffield, arXiv:1012.4797, proof of Prop. 5.5 (p. 65: conditioning on the field outside a
neighbourhood of the root). Own bookkeeping (AGENT_GUIDE cost rule).
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Set Metric
open scoped Topology ENNReal NNReal

namespace QuantumZipper
namespace Thm18Asm
namespace G3ZqF

open S5.FieldLaw.Raw

local notation "Ω₀" => gffBase.Ω

/-- The pairs of `OutIdx 0 ρ`, translated to the point `x`. -/
def g3fPairs (x ρ : ℝ) : K3.OutIdx 0 ρ → WedgeTK.BPair := fun p =>
  ⟨(p.1.1.map (· + (x : ℂ)), p.1.2.map (· + (x : ℂ))),
    isAdmissibleH_map_add_real p.2.1 x, isAdmissibleH_map_add_real p.2.2.1 x, by
      simp only
      rw [Measure.map_apply (measurable_add_const _) MeasurableSet.univ,
        Measure.map_apply (measurable_add_const _) MeasurableSet.univ, preimage_univ]
      exact p.2.2.2.1⟩

theorem map_add_neg_add (μ : Measure ℂ) (x : ℝ) :
    (μ.map (· + (x : ℂ))).map (· + ((-x : ℝ) : ℂ)) = μ := by
  rw [Measure.map_map (measurable_add_const _) (measurable_add_const _)]
  have e : ((· + ((-x : ℝ) : ℂ)) ∘ (· + (x : ℂ))) = id := by
    funext z; simp
  rw [e, Measure.map_id]

/-- **The translated-back pairs are admissible and far from `0`.** -/
theorem g3fPairs_far (x : ℝ) {ρ R₀ : ℝ} (hR₀ : R₀ < ρ) (k : K3.OutIdx 0 ρ) :
    IsAdmissibleH ((g3fPairs x ρ k).1.1.map (· + ((-x : ℝ) : ℂ))) ∧
      IsAdmissibleH ((g3fPairs x ρ k).1.2.map (· + ((-x : ℝ) : ℂ))) ∧
      (∀ᵐ y ∂((g3fPairs x ρ k).1.1.map (· + ((-x : ℝ) : ℂ))), R₀ < ‖y‖) ∧
      (∀ᵐ y ∂((g3fPairs x ρ k).1.2.map (· + ((-x : ℝ) : ℂ))), R₀ < ‖y‖) := by
  have e1 : (g3fPairs x ρ k).1.1.map (· + ((-x : ℝ) : ℂ)) = k.1.1 := map_add_neg_add _ x
  have e2 : (g3fPairs x ρ k).1.2.map (· + ((-x : ℝ) : ℂ)) = k.1.2 := map_add_neg_add _ x
  have hfar : ∀ μ : Measure ℂ, μ (ball ((0 : ℝ) : ℂ) ρ) = 0 → ∀ᵐ y ∂μ, R₀ < ‖y‖ := by
    intro μ hμ
    refine (measure_eq_zero_iff_ae_notMem.1 hμ).mono fun y hy => ?_
    simp only [Complex.ofReal_zero, mem_ball, dist_zero_right, not_lt] at hy
    linarith
  rw [e1, e2]
  exact ⟨k.2.1, k.2.2.1, hfar _ k.2.2.2.2.1, hfar _ k.2.2.2.2.2⟩

/-- **The D3⁺ conditioning σ-algebra at `x` is generated by the far Gaussian pairs.** -/
theorem condSigma_le_comap_gauss (x ρ : ℝ) :
    D3Plus.condSigma (fun _ : Ω₀ => ()) (palmCField gffBase.X x) ρ ≤
      MeasurableSpace.comap (fun ω k => WedgeTK.gaussFam gffBase.X (g3fPairs x ρ) k ω)
        MeasurableSpace.pi := by
  refine sup_le ?_ ?_
  · rw [MeasurableSpace.comap_const]; exact bot_le
  · refine iSup_le fun p => ?_
    have e : (fun ω => palmCField gffBase.X x ω p.1.1 - palmCField gffBase.X x ω p.1.2) =
        (fun f : K3.OutIdx 0 ρ → ℝ => f p) ∘
          (fun ω k => WedgeTK.gaussFam gffBase.X (g3fPairs x ρ) k ω) := rfl
    rw [e, ← MeasurableSpace.comap_comp]
    exact MeasurableSpace.comap_mono (measurable_pi_apply p).comap_le

/-- **Conditioning events are events of the far Gaussian pairs.** -/
theorem exists_gauss_preimage {E'' : Type} [MeasurableSpace E''] {x ρ : ℝ} {V : Ω₀ → E''}
    (hV : Measurable[D3Plus.condSigma (fun _ : Ω₀ => ()) (palmCField gffBase.X x) ρ] V)
    {G' : Set E''} (hG' : MeasurableSet G') :
    ∃ B : Set (K3.OutIdx 0 ρ → ℝ), MeasurableSet B ∧
      V ⁻¹' G' = (fun ω k => WedgeTK.gaussFam gffBase.X (g3fPairs x ρ) k ω) ⁻¹' B :=
  by
    obtain ⟨B, hB, e⟩ := condSigma_le_comap_gauss x ρ _ (hV hG')
    exact ⟨B, hB, e.symm⟩

end G3ZqF
end Thm18Asm
end QuantumZipper
