import LQGMetric.Papers.DFGPS.L2_17CoreA

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# DFGPS Lemma 2.17, core case: independence in the limit (packet P-D of D80, abstract form)

Source: DFGPS = arXiv:1905.00380, `lqg-metric-estimates-final.tex` ("T"), proof of Lemma 2.17,
Step 3, T:1257–1264 ("Since independence is preserved under convergence in law, we obtain from
(eqn-internal-metric-ind) and (eqn-internal-joint-law-conv) that `(h|_V, D_{h,W})` and
`(h̊, D_{h−φ𝔥,W'})` are independent"), in the form fixed by decision D80: the field enters
through a sub-σ-algebra `𝒢` (resp. `ℋ`) of its Borel σ-algebra (`σ(h|_{cl V})`, resp. `σ(h̊)`),
which is not generated by continuous functions, and its law is held fixed along the sequence.

* `tendsto_integral_mul_of_fixed_marginal₂` — `L217.tendsto_integral_mul_of_fixed_marginal`
  with the limit on a second probability space carrying a copy `X'` of `X` (same law).
* `indep_sup_of_tendsto` — if `σ(𝒢(X)) ∨ σ(Aₙ) ⫫ σ(ℋ(X)) ∨ σ(Bₙ)` for every `n` and
  `(X, Aₙ, Bₙ) → (X', A, B)` in law with `X' =ᵈ X`, then
  `σ(𝒢(X')) ∨ σ(A) ⫫ σ(ℋ(X')) ∨ σ(B)`.

Proof: for `g ∈ 𝒢`, `h ∈ ℋ` the pairs `(1_g(X), Aₙ)`, `(1_h(X), Bₙ)` (in `Bool × Tᵢ`) are
independent and converge jointly in law (a bounded continuous function of them is a finite sum of
`F(X) Θ(Aₙ, Bₙ)` with `F` bounded measurable, so the fixed-marginal lemma applies), so the limit
pairs are independent (`indepFun_of_tendsto_law`, T:1260); then π–λ (mathlib
`IndepSets.indep`). Own standard argument (DV-D80).
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Topology Set TopologicalSpace
open scoped BoundedContinuousFunction

namespace LQGMetric.DFGPS.L217

section FM2

variable {Ω Ω' : Type*} [MeasurableSpace Ω] [MeasurableSpace Ω'] {P : Measure Ω}
  {P' : Measure Ω'} [IsProbabilityMeasure P] [IsProbabilityMeasure P']
  {S T : Type*} [TopologicalSpace S] [MeasurableSpace S] [BorelSpace S] [PseudoMetrizableSpace S]
  [TopologicalSpace T] [MeasurableSpace T] [OpensMeasurableSpace T]

/-- the fixed-marginal convergence with the limit on another space carrying a copy of `X` -/
theorem tendsto_integral_mul_of_fixed_marginal₂ {X : Ω → S} (hX : Measurable X) {X' : Ω' → S}
    (hX' : Measurable X') (hlaw : P.map X = P'.map X') {Yn : ℕ → Ω → T} {Y : Ω' → T}
    (hYn : ∀ n, Measurable (Yn n)) (hY : Measurable Y)
    (hconv : ∀ φ : S × T → ℝ, Continuous φ → (∃ C, ∀ x, |φ x| ≤ C) →
      Tendsto (fun n => ∫ ω, φ (X ω, Yn n ω) ∂P) atTop (𝓝 (∫ ω, φ (X' ω, Y ω) ∂P')))
    {F : S → ℝ} (hF : Measurable F) {CF : ℝ} (hFb : ∀ x, |F x| ≤ CF)
    {Θ : T → ℝ} (hΘ : Continuous Θ) {CΘ : ℝ} (hΘb : ∀ y, |Θ y| ≤ CΘ) :
    Tendsto (fun n => ∫ ω, F (X ω) * Θ (Yn n ω) ∂P) atTop
      (𝓝 (∫ ω, F (X' ω) * Θ (Y ω) ∂P')) := by
  rw [Metric.tendsto_atTop]
  intro ε hε
  set K : ℝ := |CΘ| + 1 with hK
  have hKpos : 0 < K := by positivity
  set δ : ℝ := ε / (3 * K) with hδ
  have hδpos : 0 < δ := by positivity
  obtain ⟨g, hg⟩ := exists_boundedContinuous_integral_abs_sub_le (P.map X) hF hFb hδpos
  have hI0 : 0 ≤ ∫ x, |F x - g x| ∂(P.map X) := integral_nonneg fun x => abs_nonneg _
  have hKδ : |CΘ| * ∫ x, |F x - g x| ∂(P.map X) ≤ ε / 3 :=
    calc |CΘ| * ∫ x, |F x - g x| ∂(P.map X) ≤ K * δ :=
          mul_le_mul (by rw [hK]; linarith) hg hI0 hKpos.le
      _ = ε / 3 := by rw [hδ]; field_simp
  have hφ : Tendsto (fun n => ∫ ω, g (X ω) * Θ (Yn n ω) ∂P) atTop
      (𝓝 (∫ ω, g (X' ω) * Θ (Y ω) ∂P')) := by
    refine hconv (fun p => g p.1 * Θ p.2)
      ((g.continuous.comp continuous_fst).mul (hΘ.comp continuous_snd)) ⟨‖g‖ * |CΘ|, fun p => ?_⟩
    rw [abs_mul]
    refine mul_le_mul ?_ ((hΘb _).trans (le_abs_self _)) (abs_nonneg _) (norm_nonneg _)
    simpa [Real.norm_eq_abs] using g.norm_coe_le_norm p.1
  obtain ⟨N, hN⟩ := Metric.tendsto_atTop.1 hφ (ε / 3) (by positivity)
  refine ⟨N, fun n hn => ?_⟩
  have e1 := (abs_integral_mul_sub_le hX hF hFb hΘ hΘb g (hYn n)).trans hKδ
  have e2 := abs_integral_mul_sub_le (P := P') hX' hF hFb hΘ hΘb g hY
  rw [← hlaw] at e2
  have e2' := e2.trans hKδ
  have e3 := hN n hn
  rw [Real.dist_eq] at e3 ⊢
  calc |∫ ω, F (X ω) * Θ (Yn n ω) ∂P - ∫ ω, F (X' ω) * Θ (Y ω) ∂P'|
      = |(∫ ω, F (X ω) * Θ (Yn n ω) ∂P - ∫ ω, g (X ω) * Θ (Yn n ω) ∂P) +
          (∫ ω, g (X ω) * Θ (Yn n ω) ∂P - ∫ ω, g (X' ω) * Θ (Y ω) ∂P') +
          (∫ ω, g (X' ω) * Θ (Y ω) ∂P' - ∫ ω, F (X' ω) * Θ (Y ω) ∂P')| := by ring_nf
    _ ≤ |∫ ω, F (X ω) * Θ (Yn n ω) ∂P - ∫ ω, g (X ω) * Θ (Yn n ω) ∂P| +
          |∫ ω, g (X ω) * Θ (Yn n ω) ∂P - ∫ ω, g (X' ω) * Θ (Y ω) ∂P'| +
          |∫ ω, g (X' ω) * Θ (Y ω) ∂P' - ∫ ω, F (X' ω) * Θ (Y ω) ∂P'| := abs_add_three _ _ _
    _ < ε := by rw [abs_sub_comm] at e2'; linarith

end FM2

section Aux

variable {Ω' S : Type*}

open Classical in
/-- the indicator bit `x ∈ g` -/
def bitOf (g : Set S) (x : S) : Bool := decide (x ∈ g)

theorem measurable_bitOf {m : MeasurableSpace S} {g : Set S} (hg : MeasurableSet[m] g) :
    Measurable[m] (bitOf g) := by
  refine measurable_to_countable' fun b => ?_
  cases b
  · convert hg.compl using 1; ext x; simp [bitOf]
  · convert hg using 1; ext x; simp [bitOf]

theorem preimage_bitPair {T : Type*} (X' : Ω' → S) (k : Set S) (Y : Ω' → T) (D : Set T) :
    (fun ω => (bitOf k (X' ω), Y ω)) ⁻¹' ({true} ×ˢ D) = X' ⁻¹' k ∩ Y ⁻¹' D := by
  ext ω; simp [bitOf]

/-- the four-term decomposition of a function of the bit pairs -/
theorem bitPair_decomp {T₁ T₂ : Type*} (f : (Bool × T₁) × (Bool × T₂) → ℝ) (b₁ b₂ : Bool)
    (a : T₁) (b : T₂) :
    f ((b₁, a), (b₂, b)) = ∑ i : Bool, ∑ j : Bool,
      (if b₁ = i ∧ b₂ = j then (1 : ℝ) else 0) * f ((i, a), (j, b)) := by
  cases b₁ <;> cases b₂ <;> simp

/-- the rectangles `{X' ∈ g, Y ∈ C}` (`g ∈ 𝒦`) -/
def rectSets {T : Type*} [MeasurableSpace T] (𝒦 : MeasurableSpace S) (X' : Ω' → S)
    (Y : Ω' → T) : Set (Set Ω') :=
  {s | ∃ g C, MeasurableSet[𝒦] g ∧ MeasurableSet C ∧ s = X' ⁻¹' g ∩ Y ⁻¹' C}

theorem isPiSystem_rectSets {T : Type*} [MeasurableSpace T] (𝒦 : MeasurableSpace S)
    (X' : Ω' → S) (Y : Ω' → T) : IsPiSystem (rectSets 𝒦 X' Y) := by
  rintro _ ⟨g, C, hg, hC, rfl⟩ _ ⟨g', C', hg', hC', rfl⟩ -
  exact ⟨g ∩ g', C ∩ C', hg.inter hg', hC.inter hC', by ext; simp; tauto⟩

theorem comap_sup_eq_generateFrom_rectSets {T : Type*} [mT : MeasurableSpace T]
    (𝒦 : MeasurableSpace S) (X' : Ω' → S) (Y : Ω' → T) :
    𝒦.comap X' ⊔ mT.comap Y = MeasurableSpace.generateFrom (rectSets 𝒦 X' Y) := by
  refine le_antisymm (sup_le ?_ ?_) (MeasurableSpace.generateFrom_le ?_)
  · rintro _ ⟨g, hg, rfl⟩
    exact MeasurableSpace.measurableSet_generateFrom ⟨g, univ, hg, MeasurableSet.univ, by simp⟩
  · rintro _ ⟨C, hC, rfl⟩
    exact MeasurableSpace.measurableSet_generateFrom
      ⟨univ, C, MeasurableSet.univ, hC, by simp⟩
  · rintro _ ⟨g, C, hg, hC, rfl⟩
    exact MeasurableSet.inter (le_sup_left (a := 𝒦.comap X') _ ⟨g, hg, rfl⟩)
      (le_sup_right (b := mT.comap Y) _ ⟨C, hC, rfl⟩)

theorem integrable_mul_of_abs_le {Ω₀ : Type*} [MeasurableSpace Ω₀] {Q : Measure Ω₀}
    [IsFiniteMeasure Q] {u v : Ω₀ → ℝ} (hu : Measurable u) (hv : Measurable v)
    (hub : ∀ ω, |u ω| ≤ 1) {M : ℝ} (hvb : ∀ ω, |v ω| ≤ M) :
    Integrable (fun ω => u ω * v ω) Q :=
  integrable_of_abs_le (hu.mul hv) (C := 1 * M) fun ω => by
    rw [abs_mul]; exact mul_le_mul (hub ω) (hvb ω) (abs_nonneg _) zero_le_one

end Aux

section Limit

variable {Ω Ω' : Type*} [mΩ : MeasurableSpace Ω] [mΩ' : MeasurableSpace Ω'] {P : Measure Ω}
  {P' : Measure Ω'} [IsProbabilityMeasure P] [IsProbabilityMeasure P']
  {S : Type*} [TopologicalSpace S] [mS : MeasurableSpace S] [BorelSpace S]
  [PseudoMetrizableSpace S]
  {T₁ T₂ : Type*} [TopologicalSpace T₁] [mT₁ : MeasurableSpace T₁] [BorelSpace T₁]
  [SecondCountableTopology T₁] [PseudoMetrizableSpace T₁]
  [TopologicalSpace T₂] [mT₂ : MeasurableSpace T₂] [BorelSpace T₂]
  [SecondCountableTopology T₂] [PseudoMetrizableSpace T₂]

/-- the bit pairs `(1_g(X'), A)`, `(1_h(X'), B)` are independent in the limit -/
theorem indepFun_bitPair_of_tendsto {X : Ω → S} (hX : Measurable X) {X' : Ω' → S}
    (hX' : Measurable X') (hlaw : P.map X = P'.map X') {An : ℕ → Ω → T₁} {Bn : ℕ → Ω → T₂}
    {A : Ω' → T₁} {B : Ω' → T₂} (hAn : ∀ n, Measurable (An n)) (hBn : ∀ n, Measurable (Bn n))
    (hA : Measurable A) (hB : Measurable B)
    (hconv : ∀ φ : S × (T₁ × T₂) → ℝ, Continuous φ → (∃ C, ∀ x, |φ x| ≤ C) →
      Tendsto (fun n => ∫ ω, φ (X ω, (An n ω, Bn n ω)) ∂P) atTop
        (𝓝 (∫ ω, φ (X' ω, (A ω, B ω)) ∂P')))
    {g h : Set S} (hg : MeasurableSet g) (hh : MeasurableSet h)
    (hindn : ∀ n, IndepFun (fun ω => (bitOf g (X ω), An n ω)) (fun ω => (bitOf h (X ω), Bn n ω)) P) :
    IndepFun (fun ω => (bitOf g (X' ω), A ω)) (fun ω => (bitOf h (X' ω), B ω)) P' := by
  have hbg : Measurable (bitOf g) := measurable_bitOf hg
  have hbh : Measurable (bitOf h) := measurable_bitOf hh
  set Un : ℕ → Ω → Bool × T₁ := fun n ω => (bitOf g (X ω), An n ω)
  set Vn : ℕ → Ω → Bool × T₂ := fun n ω => (bitOf h (X ω), Bn n ω)
  have hUn : ∀ n, Measurable (Un n) := fun n => (hbg.comp hX).prodMk (hAn n)
  have hVn : ∀ n, Measurable (Vn n) := fun n => (hbh.comp hX).prodMk (hBn n)
  have hU : Measurable fun ω => (bitOf g (X' ω), A ω) := (hbg.comp hX').prodMk hA
  have hV : Measurable fun ω => (bitOf h (X' ω), B ω) := (hbh.comp hX').prodMk hB
  let ρ : ℕ → ProbabilityMeasure ((Bool × T₁) × (Bool × T₂)) := fun n =>
    ⟨P.map fun ω => (Un n ω, Vn n ω), (Measure.isProbabilityMeasure_map_iff
      ((hUn n).prodMk (hVn n)).aemeasurable).2 inferInstance⟩
  let ρ₀ : ProbabilityMeasure ((Bool × T₁) × (Bool × T₂)) :=
    ⟨P'.map fun ω => ((bitOf g (X' ω), A ω), (bitOf h (X' ω), B ω)),
      (Measure.isProbabilityMeasure_map_iff (hU.prodMk hV).aemeasurable).2 inferInstance⟩
  refine indepFun_of_tendsto_law (fun n => (hUn n).aemeasurable)
    (fun n => (hVn n).aemeasurable) hU.aemeasurable hV.aemeasurable hindn (ρ := ρ) (ρ₀ := ρ₀)
    (fun n => rfl) rfl ?_
  rw [ProbabilityMeasure.tendsto_iff_forall_integral_tendsto]
  intro f
  have hfm : Measurable fun p : (Bool × T₁) × (Bool × T₂) => f p := f.continuous.measurable
  show Tendsto (fun n => ∫ p, f p ∂(P.map fun ω => (Un n ω, Vn n ω))) atTop
    (𝓝 (∫ p, f p ∂(P'.map fun ω => ((bitOf g (X' ω), A ω), (bitOf h (X' ω), B ω)))))
  simp_rw [integral_map ((hUn _).prodMk (hVn _)).aemeasurable hfm.aestronglyMeasurable,
    integral_map (hU.prodMk hV).aemeasurable hfm.aestronglyMeasurable]
  set F : Bool → Bool → S → ℝ := fun i j x =>
    if bitOf g x = i ∧ bitOf h x = j then (1 : ℝ) else 0 with hF
  set Θ : Bool → Bool → T₁ × T₂ → ℝ := fun i j y => f ((i, y.1), (j, y.2)) with hΘ
  have hFm : ∀ i j, Measurable (F i j) := fun i j =>
    Measurable.ite (((measurableSet_singleton i).preimage hbg).inter
      ((measurableSet_singleton j).preimage hbh)) measurable_const measurable_const
  have hFb : ∀ i j x, |F i j x| ≤ 1 := fun i j x => by
    simp only [hF]; split_ifs <;> simp
  have hΘc : ∀ i j, Continuous (Θ i j) := fun i j =>
    f.continuous.comp ((continuous_const.prodMk continuous_fst).prodMk
      (continuous_const.prodMk continuous_snd))
  have hΘb : ∀ i j y, |Θ i j y| ≤ ‖f‖ := fun i j y => by
    simpa [Real.norm_eq_abs] using f.norm_coe_le_norm _
  have hdec : ∀ (x : S) (a : T₁) (b : T₂), f ((bitOf g x, a), (bitOf h x, b)) =
      ∑ i : Bool, ∑ j : Bool, F i j x * Θ i j (a, b) := fun x a b =>
    bitPair_decomp (fun p => f p) _ _ a b
  have e1 : ∀ n, ∫ ω, f (Un n ω, Vn n ω) ∂P =
      ∑ i : Bool, ∑ j : Bool, ∫ ω, F i j (X ω) * Θ i j (An n ω, Bn n ω) ∂P := by
    intro n
    have hi : ∀ i j, Integrable (fun ω => F i j (X ω) * Θ i j (An n ω, Bn n ω)) P :=
      fun i j => integrable_mul_of_abs_le ((hFm i j).comp hX)
        ((hΘc i j).measurable.comp ((hAn n).prodMk (hBn n))) (fun _ => hFb i j _)
        (fun _ => hΘb i j _)
    simp_rw [Un, Vn, hdec]
    rw [integral_finsetSum _ fun i _ => integrable_finsetSum _ fun j _ => hi i j]
    exact Finset.sum_congr rfl fun i _ => integral_finsetSum _ fun j _ => hi i j
  have e2 : ∫ ω, f ((bitOf g (X' ω), A ω), (bitOf h (X' ω), B ω)) ∂P' =
      ∑ i : Bool, ∑ j : Bool, ∫ ω, F i j (X' ω) * Θ i j (A ω, B ω) ∂P' := by
    have hi : ∀ i j, Integrable (fun ω => F i j (X' ω) * Θ i j (A ω, B ω)) P' :=
      fun i j => integrable_mul_of_abs_le ((hFm i j).comp hX')
        ((hΘc i j).measurable.comp (hA.prodMk hB)) (fun _ => hFb i j _)
        (fun _ => hΘb i j _)
    simp_rw [hdec]
    rw [integral_finsetSum _ fun i _ => integrable_finsetSum _ fun j _ => hi i j]
    exact Finset.sum_congr rfl fun i _ => integral_finsetSum _ fun j _ => hi i j
  simp_rw [e1, e2]
  refine tendsto_finsetSum _ fun i _ => tendsto_finsetSum _ fun j _ => ?_
  exact tendsto_integral_mul_of_fixed_marginal₂ hX hX' hlaw
    (Yn := fun n ω => (An n ω, Bn n ω)) (fun n => (hAn n).prodMk (hBn n)) (hA.prodMk hB)
    hconv (hFm i j) (hFb i j) (hΘc i j) (hΘb i j)

/-- **Independence in the limit** (DFGPS Lemma 2.17 Step 3, T:1257–1264, in the form of D80):
if `σ(𝒢(X)) ∨ σ(Aₙ) ⫫ σ(ℋ(X)) ∨ σ(Bₙ)` for all `n` and `(X, Aₙ, Bₙ) → (X', A, B)` in law with
`X' =ᵈ X`, then `σ(𝒢(X')) ∨ σ(A) ⫫ σ(ℋ(X')) ∨ σ(B)`. -/
theorem indep_sup_of_tendsto {X : Ω → S} (hX : Measurable X) {X' : Ω' → S} (hX' : Measurable X')
    (hlaw : P.map X = P'.map X') {An : ℕ → Ω → T₁} {Bn : ℕ → Ω → T₂} {A : Ω' → T₁}
    {B : Ω' → T₂} (hAn : ∀ n, Measurable (An n)) (hBn : ∀ n, Measurable (Bn n))
    (hA : Measurable A) (hB : Measurable B)
    (hconv : ∀ φ : S × (T₁ × T₂) → ℝ, Continuous φ → (∃ C, ∀ x, |φ x| ≤ C) →
      Tendsto (fun n => ∫ ω, φ (X ω, (An n ω, Bn n ω)) ∂P) atTop
        (𝓝 (∫ ω, φ (X' ω, (A ω, B ω)) ∂P')))
    (𝒢 ℋ : MeasurableSpace S) (h𝒢 : 𝒢 ≤ mS) (hℋ : ℋ ≤ mS)
    (hind : ∀ n, Indep (𝒢.comap X ⊔ mT₁.comap (An n)) (ℋ.comap X ⊔ mT₂.comap (Bn n)) P) :
    Indep (𝒢.comap X' ⊔ mT₁.comap A) (ℋ.comap X' ⊔ mT₂.comap B) P' := by
  refine IndepSets.indep (sup_le ((MeasurableSpace.comap_mono h𝒢).trans hX'.comap_le)
    hA.comap_le) (sup_le ((MeasurableSpace.comap_mono hℋ).trans hX'.comap_le) hB.comap_le)
    (isPiSystem_rectSets 𝒢 X' A) (isPiSystem_rectSets ℋ X' B)
    (comap_sup_eq_generateFrom_rectSets 𝒢 X' A) (comap_sup_eq_generateFrom_rectSets ℋ X' B) ?_
  rw [IndepSets_iff]
  rintro _ _ ⟨g, C, hg, hC, rfl⟩ ⟨h, C', hh, hC', rfl⟩
  have hg' : MeasurableSet[mS] g := h𝒢 g hg
  have hh' : MeasurableSet[mS] h := hℋ h hh
  have hpair := indepFun_bitPair_of_tendsto (mS := mS) hX hX' hlaw hAn hBn hA hB hconv hg' hh'
    fun n => by
      refine indep_of_indep_of_le_right (indep_of_indep_of_le_left (hind n) ?_) ?_
      · have m1 : Measurable[𝒢.comap X ⊔ mT₁.comap (An n)] fun ω => bitOf g (X ω) :=
          ((measurable_bitOf hg).comp (comap_measurable X)).mono le_sup_left le_rfl
        have m2 : Measurable[𝒢.comap X ⊔ mT₁.comap (An n)] (An n) :=
          (comap_measurable (An n)).mono le_sup_right le_rfl
        exact (m1.prodMk m2).comap_le
      · have m1 : Measurable[ℋ.comap X ⊔ mT₂.comap (Bn n)] fun ω => bitOf h (X ω) :=
          ((measurable_bitOf hh).comp (comap_measurable X)).mono le_sup_left le_rfl
        have m2 : Measurable[ℋ.comap X ⊔ mT₂.comap (Bn n)] (Bn n) :=
          (comap_measurable (Bn n)).mono le_sup_right le_rfl
        exact (m1.prodMk m2).comap_le
  have := (indepFun_iff_measure_inter_preimage_eq_mul.1 hpair)
    ({true} ×ˢ C) ({true} ×ˢ C') ((measurableSet_singleton _).prod hC)
    ((measurableSet_singleton _).prod hC')
  simp only [preimage_bitPair] at this
  exact this

end Limit

end LQGMetric.DFGPS.L217
