import LQGMetric.Papers.DFGPS.L2_17Core2E
import LQGMetric.Papers.DFGPS.L2_17Exh

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# DFGPS Lemma 2.17, core case: the internal metrics of `e^{−ξh_r(z)} D_h` on `V` (step E1, part)

Source: DFGPS = arXiv:1905.00380, `lqg-metric-estimates-final.tex` ("T"), proof of Lemma 2.17,
Step 4 (T:1278: "Letting `W` increase to `V` …"). The family `normFam ξ h Dh z r` of internal
metrics of `e^{−ξh_r(z)} D_h` is the family of internal metrics of the scaled metric
`D̃ = e^{−ξh_r(z)} D_h` (`ContMetric.internal_smulPos`), and on `V` it is generated, up to null
sets, by the internal metrics on the dyadic domains `W` with `W̄ ⊆ V`
(`famSigma_le_iSup_dyadicC`), each a Borel function `intFn W` of `D̃` (`internal_eq_intFn`).

* `scaledDh` — `D̃ ω = e^{−ξ h_r(z)} D_h ω` as a `ContMetric`; `normFam_eq_internalFam_scaledDh`.
* `famSigma_normFam_le` — `σ(D̃(·,·;V)) ⊆ ⋁_{W̄ ⊆ V} σ(intFn W D̃)` up to null sets.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Topology Set TopologicalSpace
open scoped ENNReal

namespace LQGMetric.DFGPS.L217

open Blueprint LFPP MetricGeometry GM.Bilip

variable {Ω : Type}

/-- `e^{−ξ h_r(z)} D_h` as a continuous metric -/
def scaledDh (ξ : ℝ) (h : Ω → DistC) (Dh : Ω → ContMetric) (z : ℂ) (r : ℝ) (ω : Ω) :
    ContMetric :=
  (Dh ω).smulPos (Real.exp (-ξ * circleAvg (h ω) r z)) (Real.exp_pos _)

theorem normFam_eq_internalFam_scaledDh (ξ : ℝ) (h : Ω → DistC) (Dh : Ω → ContMetric) (z : ℂ)
    (r : ℝ) : normFam ξ h Dh z r = internalFam (scaledDh ξ h Dh z r) := by
  funext ω V u v
  exact (ContMetric.internal_smulPos _ _ _ _ _).symm

/-- **`σ(D̃(·,·;V))` is generated by the `intFn W D̃`, `W̄ ⊆ V`, up to null sets** -/
theorem famSigma_normFam_le [MeasurableSpace Ω] {P : Measure Ω} (ξ : ℝ) (h : Ω → DistC) (Dh : Ω → ContMetric)
    (z : ℂ) (r : ℝ) (hlen : ∀ᵐ ω ∂P, (Dh ω).IsLength) {V : Set ℂ} (hV : IsOpen V) :
    famSigma (normFam ξ h Dh z r) V ≤ aeClosure P (⨆ (W : dyadicDomainsC)
      (_ : closure (W : Set ℂ) ⊆ V), MeasurableSpace.comap
        (fun ω => intFn W (scaledDh ξ h Dh z r ω).1) inferInstance) := by
  rw [normFam_eq_internalFam_scaledDh]
  refine (famSigma_le_iSup_dyadicC _ hV).trans (iSup₂_le fun W hW => ?_)
  refine (famSigma_le_aeClosure_of_measurable (comap_measurable _) ?_).trans
    (aeClosure_mono (le_iSup₂_of_le W hW le_rfl))
  filter_upwards [hlen] with ω hω
  exact internal_eq_intFn _ (ContMetric.isLength_smulPos _ hω) (isOpen_of_dyadicDomainsC W)

end L217

end LQGMetric.DFGPS
