import LQGMetric.Papers.DFGPS.L2_17Core2B
import LQGMetric.Papers.DFGPS.L2_17CoreSt

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# DFGPS Lemma 2.17, core case: independence in the limit coupling, one stage (step C4)

Source: DFGPS = arXiv:1905.00380, `lqg-metric-estimates-final.tex` ("T"), proof of Lemma 2.17,
Step 3 (T:1236–1264): "Since independence is preserved under convergence in law, we obtain from
(eqn-internal-metric-ind) and (eqn-internal-joint-law-conv) that …" (eqn-limit-metric-ind), in the
D80 form (`h|_{cl V}` on the left; decision D80, packet P-D).

For finite families `𝒲, 𝒲'` of dyadic domains whose `√εₖ`-neighbourhoods stay in `V`, resp. in
the set `U₁` where `h − φ𝔥 = h̊`:

* `FamT 𝒲` — the state space `Π_{W ∈ 𝒲} C(W̄ × W̄, ℝ)` (finite product, normed);
  `famProj 𝒲 : DyFam → FamT 𝒲` the projection.
* `indep_stage_limit` — the coupling `ρ` of `exists_lfpp_coupling` (applied to `h̃` and
  `h̃ − fn`) satisfies
  `σ(𝒢(x)) ∨ σ(d_W, W ∈ 𝒲) ⫫ σ(ℋ(x)) ∨ σ(d'_{W'}, W' ∈ 𝒲')` under `ρ`, where `d, d'` are the
  `DyFam` parts of the two `DyProd` coordinates and `𝒢, ℋ` are sub-σ-algebras of the coordinate
  space with `X⁻¹𝒢 ⊆ σ(h̃|_{cl V})`, `X⁻¹ℋ ⊆ σ(h̊)`. Proof: (eqn-internal-metric-ind) for the
  localized `D̂^ε` (`indep_lfpp_stage`), the `D̂/D` swap in law (`tendsto_integral_swap`,
  `tendsto_measure_locSqC_sub`), `indep_of_tendsto_coupling`, transport along the projection.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Topology Set TopologicalSpace Metric
open scoped ENNReal BoundedContinuousFunction

namespace LQGMetric.DFGPS.L217

open Blueprint LFPP

/-- the state space `Π_{W ∈ 𝒲} C(W̄ × W̄, ℝ)` of a finite family of dyadic metrics -/
abbrev FamT (𝒲 : Finset dyadicDomainsC) : Type :=
  (W : 𝒲) → C(closure ((W : dyadicDomainsC) : Set ℂ) × closure ((W : dyadicDomainsC) : Set ℂ), ℝ)

/-- the projection `DyFam → FamT 𝒲` -/
def famProj (𝒲 : Finset dyadicDomainsC) (d : DyFam) : FamT 𝒲 := fun W => d W

theorem continuous_famProj (𝒲 : Finset dyadicDomainsC) : Continuous (famProj 𝒲) :=
  continuous_pi fun W => continuous_apply (W : dyadicDomainsC)

/-- the σ-algebra of a finite family of maps into `FamT 𝒲` is generated by its coordinates -/
theorem comap_famT_le {Ω : Type*} {m : MeasurableSpace Ω} {𝒲 : Finset dyadicDomainsC}
    (F : Ω → FamT 𝒲) (hF : ∀ W : 𝒲, Measurable[m] fun ω => F ω W) :
    MeasurableSpace.comap F inferInstance ≤ m :=
  measurable_iff_comap_le.1 (@measurable_pi_lambda Ω 𝒲 _ m _ F hF)

/-- **(eqn-limit-metric-ind) at one stage** (T:1257–1264, D80 P-D) -/
theorem indep_stage_limit (h28 : Lem2_8) (HG : Lem2_1GffApprox.{0}) {γ : ℝ} (hγ : 0 < γ)
    (hγ2 : γ < 2) {Ω : Type} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    {ht hz : Ω → DistC} {fn : Ω → C(ℂ, ℝ)} (hht : IsGFFPlusBddCont ht P)
    (hh₂ : IsGFFPlusBddCont (fun ω => ht ω - ofCont (fn ω)) P) {V : Opens ℂ} {U₁ : Set ℂ}
    (hU₁ : IsOpen U₁)
    (hind : Indep (MeasurableSpace.comap hz inferInstance) (fieldSigmaClosed ht (closure V)) P)
    (hagree : ∀ᵐ ω ∂P, ∀ ψ : TestC, tsupport (ψ : ℂ → ℝ) ⊆ U₁ →
      (ht ω - ofCont (fn ω)) ψ = hz ω ψ)
    {εk : ℕ → ℝ} (hεk : ∀ k, 0 < εk k) (hεk0 : Tendsto εk atTop (𝓝 0))
    (𝒲 𝒲' : Finset dyadicDomainsC)
    (hWV : ∀ k, ∀ W ∈ 𝒲, ∀ z ∈ closure (W : Set ℂ), closedBall z (Real.sqrt (εk k)) ⊆ V)
    (hWU : ∀ k, ∀ W ∈ 𝒲', ∀ z ∈ closure (W : Set ℂ), closedBall z (Real.sqrt (εk k)) ⊆ U₁)
    {S : Type*} [TopologicalSpace S] [mS : MeasurableSpace S] [BorelSpace S] [PolishSpace S]
    {X : Ω → S} (hX : Measurable X) (𝒢 ℋ : {m : MeasurableSpace S // m ≤ mS})
    (h𝒢 : 𝒢.1.comap X ≤ fieldSigmaClosed ht (closure V))
    (hℋ : ℋ.1.comap X ≤ MeasurableSpace.comap hz inferInstance) :
    ∃ ψ : ℕ → ℕ, StrictMono ψ ∧ ∃ ρ : ProbabilityMeasure (S × (DyProd × DyProd)),
      (∀ f : S × (DyProd × DyProd) →ᵇ ℝ, Tendsto (fun n => ∫ ω, f (X ω,
          (lfppJoint (xiGamma γ) (εk (ψ n)) (ht ω),
            lfppJoint (xiGamma γ) (εk (ψ n)) (ht ω - ofCont (fn ω)))) ∂P)
        atTop (𝓝 (∫ p, f p ∂(ρ : Measure (S × (DyProd × DyProd)))))) ∧
      (ρ : Measure (S × (DyProd × DyProd))).map Prod.fst = P.map X ∧
      (∀ᵐ p ∂(ρ : Measure (S × (DyProd × DyProd))), IsDyadicLimit p.2.1 ∧ IsDyadicLimit p.2.2) ∧
      Indep (𝒢.1.comap Prod.fst ⊔ MeasurableSpace.comap
          (fun p : S × (DyProd × DyProd) => famProj 𝒲 p.2.1.2) inferInstance)
        (ℋ.1.comap Prod.fst ⊔ MeasurableSpace.comap
          (fun p : S × (DyProd × DyProd) => famProj 𝒲' p.2.2.2) inferInstance)
        (ρ : Measure (S × (DyProd × DyProd))) := by
  set ξ := xiGamma γ
  set h₂ : Ω → DistC := fun ω => ht ω - ofCont (fn ω) with hh₂def
  obtain ⟨ψ, hψ, ρ, hconv, hmarg, hdy⟩ := exists_lfpp_coupling h28 hγ hγ2 hX hht hh₂ hεk hεk0
  refine ⟨ψ, hψ, ρ, hconv, hmarg, hdy, ?_⟩
  set E := S × (FamT 𝒲 × FamT 𝒲')
  set π : S × (DyProd × DyProd) → E := fun p => (p.1, (famProj 𝒲 p.2.1.2, famProj 𝒲' p.2.2.2))
    with hπdef
  have hπc : Continuous π := continuous_fst.prodMk
    (((continuous_famProj 𝒲).comp (continuous_snd.comp (continuous_fst.comp continuous_snd))).prodMk
      ((continuous_famProj 𝒲').comp (continuous_snd.comp (continuous_snd.comp continuous_snd))))
  set ρ' : ProbabilityMeasure E := ρ.map π
  set εs : ℕ → ℝ := fun n => εk (ψ n)
  have hεs : ∀ n, 0 < εs n := fun n => hεk _
  have hεs0 : Tendsto εs atTop (𝓝 0) := hεk0.comp hψ.tendsto_atTop
  -- the localized families `Aₙ, Bₙ` and the (versions of the) LFPP families `Ãₙ, B̃ₙ`
  set A : ℕ → Ω → FamT 𝒲 := fun n ω W => locSqC ξ (εs n) (hεs n) (ht ω) (closure W)
  set B : ℕ → Ω → FamT 𝒲' := fun n ω W => locSqC ξ (εs n) (hεs n) (h₂ ω) (closure W)
  have hAm : ∀ n, Measurable (A n) := fun n => Measurable.of_eval fun W =>
    (measurable_locSqC ξ _ (hεs n) (W : dyadicDomainsC).2.1 (W : dyadicDomainsC).2.2).comp hht.1
  have hBm : ∀ n, Measurable (B n) := fun n => Measurable.of_eval fun W =>
    (measurable_locSqC ξ _ (hεs n) (W : dyadicDomainsC).2.1 (W : dyadicDomainsC).2.2).comp hh₂.1
  have hcS : ∀ g : Ω → DistC, IsGFFPlusBddCont g P → ∀ n, ∀ᵐ ω ∂P,
      Continuous (heatMollify (εs n) (g ω)) := fun g hg n =>
    (hg.ae_tendstoLocallyUniformly_heatMollify _ (hεs n).ne').mono fun ω hω => hω.2
  have hAt : ∀ n, AEMeasurable (fun ω => famProj 𝒲 (lfppJoint ξ (εs n) (ht ω)).2) P := fun n =>
    AEMeasurable.of_eval fun W =>
      aemeasurable_lfppSqC_closure (W : dyadicDomainsC).2.1 (W : dyadicDomainsC).2.2 hht.1
        (hcS ht hht n)
  have hBt : ∀ n, AEMeasurable (fun ω => famProj 𝒲' (lfppJoint ξ (εs n) (h₂ ω)).2) P :=
    fun n => AEMeasurable.of_eval fun W =>
      aemeasurable_lfppSqC_closure (W : dyadicDomainsC).2.1 (W : dyadicDomainsC).2.2 hh₂.1
        (hcS h₂ hh₂ n)
  -- convergence of `(X, Ãₙ, B̃ₙ)` to `ρ'`
  have hconvt : ∀ f : E →ᵇ ℝ, Tendsto (fun n => ∫ ω, f (X ω, ((hAt n).mk _ ω, (hBt n).mk _ ω)) ∂P)
      atTop (𝓝 (∫ p, f p ∂(ρ' : Measure E))) := by
    intro f
    have k := hconv (f.compContinuous ⟨π, hπc⟩)
    rw [show (ρ' : Measure E) = (ρ : Measure _).map π from rfl,
      integral_map hπc.aemeasurable f.continuous.aestronglyMeasurable]
    refine k.congr fun n => integral_congr_ae ?_
    filter_upwards [(hAt n).ae_eq_mk, (hBt n).ae_eq_mk] with ω e1 e2
    simp only [BoundedContinuousFunction.compContinuous_apply, ContinuousMap.coe_mk, hπdef]
    rw [← e1, ← e2]
  -- closeness in probability, coordinatewise (Lemma 2.1)
  have hcoord : ∀ (g : Ω → DistC) (hg : IsGFFPlusBddCont g P) (W : dyadicDomainsC)
      (i : DyProd × DyProd → DyProd), Continuous i →
      (∀ n, (fun ω => i (lfppJoint ξ (εs n) (ht ω), lfppJoint ξ (εs n) (h₂ ω))) =
        fun ω => lfppJoint ξ (εs n) (g ω)) →
      ∀ δ : ℝ, 0 < δ → Tendsto (fun n => P {ω | δ ≤ ‖locSqC ξ (εs n) (hεs n) (g ω) (closure W) -
        lfppSqC ξ (εs n) (g ω) (closure W)‖}) atTop (𝓝 0) := by
    intro g hg W i hi hiY δ hδ
    have hc : Continuous fun p : S × (DyProd × DyProd) => (i p.2).2 W :=
      (continuous_dyProd_snd W).comp (hi.comp continuous_snd)
    refine tendsto_measure_locSqC_sub HG hg ξ W hεs hεs0 (P' := (ρ : Measure _))
      hc.measurable (fun f => ?_) hδ
    have k := hconv (f.compContinuous ⟨_, hc⟩)
    refine k.congr fun n => integral_congr_ae (Eventually.of_forall fun ω => ?_)
    simp only [BoundedContinuousFunction.compContinuous_apply, ContinuousMap.coe_mk]
    rw [show i (lfppJoint ξ (εs n) (ht ω), lfppJoint ξ (εs n) (h₂ ω)) =
      lfppJoint ξ (εs n) (g ω) from congrFun (hiY n) ω]
    rfl
  have hcA : ∀ δ : ℝ, 0 < δ →
      Tendsto (fun n => P {ω | δ ≤ ‖A n ω - (hAt n).mk _ ω‖}) atTop (𝓝 0) := by
    intro δ hδ
    refine tendsto_measure_pi_norm_sub (fun W δ hδ => ?_) hδ
    refine (hcoord ht hht W Prod.fst continuous_fst (fun n => rfl) δ hδ).congr fun n =>
      measure_congr ?_
    filter_upwards [(hAt n).ae_eq_mk] with ω hω
    rw [← hω]
    rfl
  have hcB : ∀ δ : ℝ, 0 < δ →
      Tendsto (fun n => P {ω | δ ≤ ‖B n ω - (hBt n).mk _ ω‖}) atTop (𝓝 0) := by
    intro δ hδ
    refine tendsto_measure_pi_norm_sub (fun W δ hδ => ?_) hδ
    refine (hcoord h₂ hh₂ W Prod.snd continuous_snd (fun n => rfl) δ hδ).congr fun n =>
      measure_congr ?_
    filter_upwards [(hBt n).ae_eq_mk] with ω hω
    rw [← hω]
    rfl
  have hconvA := tendsto_integral_swap hX hAm (fun n => (hAt n).measurable_mk) hBm
    (fun n => (hBt n).measurable_mk) hconvt hcA hcB
  -- the laws of `(X, Aₙ, Bₙ)` converge to `ρ'`
  have hlim : Tendsto (β := ProbabilityMeasure E)
      (fun n => (⟨P.map fun ω => (X ω, (A n ω, B n ω)),
        (Measure.isProbabilityMeasure_map_iff
          (hX.prodMk ((hAm n).prodMk (hBm n))).aemeasurable).2 inferInstance⟩ :
          ProbabilityMeasure E)) atTop (𝓝 ρ') := by
    refine ProbabilityMeasure.tendsto_iff_forall_integral_tendsto.2 fun f => ?_
    refine (hconvA f).congr fun n => ?_
    show _ = ∫ p, f p ∂(P.map fun ω => (X ω, (A n ω, B n ω)))
    rw [integral_map (hX.prodMk ((hAm n).prodMk (hBm n))).aemeasurable
      f.continuous.aestronglyMeasurable]
  have hmarg' : (ρ' : Measure E).map Prod.fst = P.map X := by
    rw [show (ρ' : Measure E) = (ρ : Measure _).map π from rfl,
      Measure.map_map measurable_fst hπc.measurable]
    exact hmarg
  -- independence at the LFPP stage (eqn-internal-metric-ind)
  have hind' : ∀ n, Indep (𝒢.1.comap X ⊔ MeasurableSpace.comap (A n) inferInstance)
      (ℋ.1.comap X ⊔ MeasurableSpace.comap (B n) inferInstance) P := by
    intro n
    have k := indep_lfpp_stage ξ hU₁ hind hagree (hεs n) 𝒲 𝒲' (fun W hW => hWV _ W hW)
      (fun W hW => hWU _ W hW)
    refine indep_of_indep_of_le_right (indep_of_indep_of_le_left k
      (sup_le_sup h𝒢 (comap_famT_le _ fun W => ?_))) (sup_le_sup hℋ (comap_famT_le _ fun W => ?_))
    · exact (comap_measurable _).mono (le_iSup₂_of_le (W : dyadicDomainsC) W.2 le_rfl) le_rfl
    · exact (comap_measurable _).mono (le_iSup₂_of_le (W : dyadicDomainsC) W.2 le_rfl) le_rfl
  have hlimInd := indep_of_tendsto_coupling hX hAm hBm hlim hmarg' 𝒢 ℋ hind'
  -- transport along the projection `π`
  have ht := indep_comap_of_map_eq (P := (ρ : Measure _)) (P' := (ρ' : Measure E)) (X := π)
    (X' := id) hπc.measurable measurable_id (by rw [Measure.map_id]; rfl)
    (A := 𝒢.1.comap Prod.fst ⊔ MeasurableSpace.comap (fun p : E => p.2.1) inferInstance)
    (B := ℋ.1.comap Prod.fst ⊔ MeasurableSpace.comap (fun p : E => p.2.2) inferInstance)
    (sup_le ((MeasurableSpace.comap_mono 𝒢.2).trans (measurable_iff_comap_le.1 measurable_fst))
      (measurable_iff_comap_le.1 (measurable_fst.comp measurable_snd)))
    (sup_le ((MeasurableSpace.comap_mono ℋ.2).trans (measurable_iff_comap_le.1 measurable_fst))
      (measurable_iff_comap_le.1 (measurable_snd.comp measurable_snd)))
    (by simpa only [MeasurableSpace.comap_id] using hlimInd)
  rw [MeasurableSpace.comap_sup, MeasurableSpace.comap_sup, MeasurableSpace.comap_comp,
    MeasurableSpace.comap_comp, MeasurableSpace.comap_comp, MeasurableSpace.comap_comp] at ht
  exact ht

end L217

end LQGMetric.DFGPS
