import Mathlib.Analysis.Distribution.Distribution
import Mathlib.Analysis.Calculus.BumpFunction.Normed
import Mathlib.Analysis.Calculus.BumpFunction.InnerProduct
import Mathlib.MeasureTheory.Integral.CircleAverage

/-!
# Statement layer, part 1: test functions, distributions and operations on fields

`FOUNDATIONS.md` §1 and §3 (blocks copied verbatim; see `STATEMENT_SPEC.md` for the entry of
each definition). Source: Gwynne–Miller, arXiv:1905.00383v3 (GM),
`literature/src/1905.00383/uniqueness-final.tex`:

* `𝒟'(ℂ)` "the space of distributions (generalized functions) on ℂ, equipped with the usual weak
  topology" (GM l. 293); we use mathlib's `Distribution` with the cylinder σ-algebra (D1, D2, F1).
* `h|_U` (GM l. 298): `restrictTo U h ∈ 𝒟'(U)`.
* `h + f` (GM l. 300–302, Axiom III), `h(r · + z) + Q log r` (GM l. 304–307, Axiom IV):
  `addFun`, `addConst`, `affineComp` (D10).
* the circle average `h_r(z)` (GM l. 223 footnote, DS §3.1): `circleAvg` (D6, F4).
* the heat-kernel mollification `h*_ε(z) := (h * p_{ε²/2})(z)` (GM (1.2), l. 173–177):
  `heatMollify` (D6, F5).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory ProbabilityTheory Filter Topology Set
open scoped Distributions ENNReal

namespace LQGMetric

/-! ## §1. Test functions, distributions, field operations -/

/-- `𝓓(U)`: real smooth test functions with compact support in the open set `U` (mathlib). -/
abbrev TestOn (U : TopologicalSpace.Opens ℂ) : Type := 𝓓(U, ℝ)
/-- `𝒟'(U)`: mathlib `Distribution` (continuous linear functionals on `𝓓(U)`). -/
abbrev DistOn (U : TopologicalSpace.Opens ℂ) : Type := 𝓓'(U, ℝ)
/-- the cylinder σ-algebra on `𝒟'(U)`: generated by the pairings `h ↦ ⟨h, φ⟩`. (D2, F1) -/
instance DistOn.measurableSpace (U : TopologicalSpace.Opens ℂ) : MeasurableSpace (DistOn U) :=
  MeasurableSpace.comap (fun (h : DistOn U) (φ : TestOn U) => h φ) MeasurableSpace.pi

/-- `𝓓(ℂ)` -/
abbrev TestC : Type := TestOn ⊤
/-- `𝒟'(ℂ)` -/
abbrev DistC : Type := DistOn ⊤

/-- `h|_U ∈ 𝒟'(U)`: `h` composed with the inclusion `𝓓(U) ⊆ 𝓓(ℂ)` (mathlib `monoCLM`). -/
def restrictTo (U : TopologicalSpace.Opens ℂ) (h : DistC) : DistOn U :=
  h.comp (TestFunction.monoCLM ℝ (n₁ := ⊤) (n₂ := ⊤) (Ω₁ := U) (Ω₂ := ⊤))

/-- The distribution `φ ↦ ∫ f φ` of a continuous function. -/
def ofCont (f : C(ℂ, ℝ)) : DistC := Distribution.ofFun ⊤ (⇑f) volume ⊤
/-- `h + f` for a continuous function `f` -/
def addFun (h : DistC) (f : C(ℂ, ℝ)) : DistC := h + ofCont f
/-- `h + c` for a constant `c` -/
def addConst (h : DistC) (c : ℝ) : DistC := addFun h (ContinuousMap.const ℂ c)

/-! ### Affine pullback `h ↦ h(r · + z)` (FOUNDATIONS §1, fully proved, copied verbatim) -/

section affinePull
open TopologicalSpace

/-- `x ↦ (x - z)/r`, written `r⁻¹ • (x + -z)` -/
def affMap (r : ℝ) (z : ℂ) (x : ℂ) : ℂ := r⁻¹ • (x + -z)
/-- its linear part -/
def affLin (r : ℝ) : ℂ →L[ℝ] ℂ := r⁻¹ • ContinuousLinearMap.id ℝ ℂ

lemma comp_affMap_eq (r : ℝ) (z : ℂ) (φ : ℂ → ℝ) :
    φ ∘ affMap r z = fun y => (φ ∘ affLin r) (y + -z) := by
  ext y; simp [affMap, affLin]

lemma contDiff_comp_affMap (r : ℝ) (z : ℂ) {φ : ℂ → ℝ} {n : ℕ∞}
    (hφ : ContDiff ℝ n φ) : ContDiff ℝ n (φ ∘ affMap r z) := by
  rw [comp_affMap_eq]
  exact (hφ.comp (affLin r).contDiff).comp (contDiff_id.add contDiff_const)

lemma iteratedFDeriv_comp_affMap (r : ℝ) (z : ℂ) {φ : ℂ → ℝ}
    (hφ : ContDiff ℝ ((⊤ : ℕ∞) : WithTop ℕ∞) φ) (i : ℕ) (x : ℂ) :
    iteratedFDeriv ℝ i (φ ∘ affMap r z) x =
      (iteratedFDeriv ℝ i φ (affMap r z x)).compContinuousLinearMap fun _ => affLin r := by
  rw [comp_affMap_eq, iteratedFDeriv_comp_add_right,
    (affLin r).iteratedFDeriv_comp_right hφ _ (by exact_mod_cast le_top)]
  rfl

/-- the compact `r K + z` -/
def affK (r : ℝ) (z : ℂ) (K : Compacts ℂ) : Compacts ℂ :=
  K.map (fun y => r • y + z) (by fun_prop)

lemma affMap_mem_of (r : ℝ) (z : ℂ) (hr : r ≠ 0) (K : Compacts ℂ) {x : ℂ}
    (hx : affMap r z x ∈ (K : Set ℂ)) : x ∈ (affK r z K : Set ℂ) := by
  refine ⟨affMap r z x, hx, ?_⟩
  simp [affMap, hr]

/-- `φ ↦ φ((·-z)/r)` from `𝓓_K` to `𝓓_{rK+z}` -/
def pullK (r : ℝ) (z : ℂ) (hr : r ≠ 0) (K : Compacts ℂ) :
    𝓓^{⊤}_{K}(ℂ, ℝ) →ₗ[ℝ] 𝓓^{⊤}_{affK r z K}(ℂ, ℝ) where
  toFun φ :=
    { toFun := φ ∘ affMap r z
      contDiff' := contDiff_comp_affMap r z φ.contDiff
      zero_on_compl' := fun _ hx => φ.zero_on_compl (fun hK => hx (affMap_mem_of r z hr K hK)) }
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

lemma continuous_pullK (r : ℝ) (z : ℂ) (hr : r ≠ 0) (K : Compacts ℂ) :
    Continuous (pullK r z hr K) := by
  rw [ContDiffMapSupportedIn.continuous_iff_comp]
  intro i
  let Ψ := (ContinuousMultilinearMap.compContinuousLinearMapL (𝕜 := ℝ)
      (E := fun _ : Fin i => ℂ) (E₁ := fun _ : Fin i => ℂ) (F := ℝ)
      (fun _ => affLin r)).compLeftContinuousBounded ℂ
  have hA : Continuous (affMap r z) := by unfold affMap; fun_prop
  have key : (ContDiffMapSupportedIn.structureMapCLM ℝ ⊤ i ∘ pullK r z hr K) =
      (fun g => (Ψ g).compContinuous ⟨affMap r z, hA⟩) ∘
        ContDiffMapSupportedIn.structureMapCLM ℝ ⊤ i := by
    funext φ
    ext x : 1
    simp only [Function.comp_apply, ContDiffMapSupportedIn.structureMapCLM_top_apply]
    rw [BoundedContinuousFunction.compContinuous_apply,
      ContinuousLinearMap.compLeftContinuousBounded_apply,
      ContDiffMapSupportedIn.structureMapCLM_top_apply]
    exact iteratedFDeriv_comp_affMap r z φ.contDiff i x
  rw [key]
  exact ((BoundedContinuousFunction.continuous_compContinuous _).comp Ψ.continuous).comp
    (ContDiffMapSupportedIn.structureMapCLM ℝ ⊤ i).continuous

lemma hasCompactSupport_comp_affMap (r : ℝ) (z : ℂ) (hr : r ≠ 0) {φ : ℂ → ℝ}
    (hφ : HasCompactSupport φ) : HasCompactSupport (φ ∘ affMap r z) := by
  refine HasCompactSupport.intro (K := (fun y => r • y + z) '' tsupport φ)
    (hφ.isCompact.image (by fun_prop)) fun x hx => ?_
  have : affMap r z x ∉ tsupport φ := fun h => hx ⟨affMap r z x, h, by simp [affMap, hr]⟩
  exact image_eq_zero_of_notMem_tsupport (f := φ) this

/-- `φ ↦ φ((· - z)/r)` on `𝓓(ℂ)` (junk `0` for `r = 0`) -/
def testAffinePull (r : ℝ) (z : ℂ) : TestC →L[ℝ] TestC :=
  if hr : r = 0 then 0 else
  TestFunction.mkCLM ℝ
    (fun φ => ⟨φ ∘ affMap r z, contDiff_comp_affMap r z φ.contDiff,
      hasCompactSupport_comp_affMap r z hr φ.hasCompactSupport, subset_univ _⟩)
    (fun _ _ => rfl) (fun _ _ => rfl) (fun K _ => by
      have : (fun φ : TestC => (⟨φ ∘ affMap r z, contDiff_comp_affMap r z φ.contDiff,
          hasCompactSupport_comp_affMap r z hr φ.hasCompactSupport, subset_univ _⟩ : TestC)) ∘
          TestFunction.ofSupportedIn (subset_univ (K : Set ℂ)) =
          TestFunction.ofSupportedInCLM ℝ (subset_univ (affK r z K : Set ℂ)) ∘ pullK r z hr K := by
        funext φ; ext x; rfl
      rw [this]
      exact (TestFunction.ofSupportedInCLM ℝ _).continuous.comp (continuous_pullK r z hr K))

lemma testAffinePull_apply (r : ℝ) (z : ℂ) (hr : r ≠ 0) (φ : TestC) (x : ℂ) :
    testAffinePull r z φ x = φ ((x - z) / r) := by
  simp only [testAffinePull, hr, dite_false]
  show φ (affMap r z x) = _
  congr 1
  simp [affMap, div_eq_inv_mul, sub_eq_add_neg, Complex.real_smul]
  ring

/-- `h(r · + z)`: `⟨h(r · + z), φ⟩ = r⁻² ⟨h, φ((· - z)/r)⟩` (change of variables in `ℝ²`) -/
def affineComp (r : ℝ) (z : ℂ) (h : DistC) : DistC := (r ^ 2)⁻¹ • h.comp (testAffinePull r z)

end affinePull

/-! ## §3. Circle averages and heat-kernel mollification -/

/-- standard mollifier at scale `2^{-n}` centred at `x`, as a test function -/
def bumpTest (n : ℕ) (x : ℂ) : TestC where
  toFun := ((⟨(2 : ℝ)⁻¹ ^ (n + 1), (2 : ℝ)⁻¹ ^ n, by positivity,
      pow_lt_pow_right_of_lt_one₀ (by norm_num) (by norm_num) (Nat.lt_succ_self n)⟩ :
      ContDiffBump x).normed volume)
  contDiff' := ContDiffBump.contDiff_normed _
  hasCompactSupport' := ContDiffBump.hasCompactSupport_normed _
  tsupport_subset' := subset_univ _

/-- `h_r(z)`: limit of the circle averages of the mollified field `x ↦ ⟨h, ψ_{n,x}⟩`; junk 0. -/
def circleAvg (h : DistC) (r : ℝ) (z : ℂ) : ℝ :=
  limUnder atTop fun n : ℕ => Real.circleAverage (fun x => h (bumpTest n x)) z r

/-- heat kernel `p_s(z,w) = (2πs)⁻¹ exp(−|z−w|²/(2s))` (GM l. 173) -/
def heatKernel (s : ℝ) (z w : ℂ) : ℝ := (2 * Real.pi * s)⁻¹ * Real.exp (-‖z - w‖ ^ 2 / (2 * s))
/-- smooth cutoff: `1` on `B_{n+1}(0)`, supported in `B_{n+2}(0)` -/
def cutoff (n : ℕ) : ContDiffBump (0 : ℂ) := ⟨n + 1, n + 2, by positivity, by linarith⟩
/-- `w ↦ p_s(z,w) χ_n(w)` as a test function -/
def heatTrunc (s : ℝ) (z : ℂ) (n : ℕ) : TestC where
  toFun := fun w => heatKernel s z w * cutoff n w
  contDiff' := by
    apply ContDiff.mul _ (cutoff n).contDiff
    unfold heatKernel
    apply contDiff_const.mul
    apply Real.contDiff_exp.comp
    apply ContDiff.div_const
    apply ContDiff.neg
    exact (contDiff_norm_sq ℝ).comp (contDiff_const.sub contDiff_id)
  hasCompactSupport' := (cutoff n).hasCompactSupport.mul_left
  tsupport_subset' := subset_univ _

/-- `h*_ε(z) = (h * p_{ε²/2})(z) := lim_n ⟨h, p_{ε²/2}(z,·) χ_n⟩` (GM (1.2)); junk 0. -/
def heatMollify (ε : ℝ) (h : DistC) (z : ℂ) : ℝ :=
  limUnder atTop fun n : ℕ => h (heatTrunc (ε ^ 2 / 2) z n)

end LQGMetric
