import Mathlib.MeasureTheory.Integral.Layercake
import Mathlib.MeasureTheory.Measure.GiryMonad
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.MeasureTheory.Measure.Prod
import Mathlib.Probability.Kernel.Basic
import QuantumZipper.Proofs.Field.Factorization

/-!
# Total variation distance and TV-local convergence (TASKS.md R12 / S5-TV)

Sheffield, *Conformal weldings of random surfaces: SLE and the quantum gravity zipper*,
arXiv:1012.4797.  Blueprint `SECTION5_BLUEPRINT.md` §0: the local σ-algebra `𝓛_R` is generated by
the field at admissible measures supported in `closure (B_R(0)) ∩ Hbar` together with the driver
stopped at the exit time of `trace W` from `B_R(0)`; TV-local convergence means that for every `R`
the total variation distance of the laws restricted to `𝓛_R` tends to `0` (blueprint R4: all zoom
limits are TV limits, since GMC lengths and `θᴸ` are measurable but not continuous).

This file provides the infrastructure: the total variation distance of two measures as the
supremum over measurable sets of `|μ s - ν s|` (the `ℝ≥0∞`-valued, non-normalized version, which
avoids division and works verbatim for finite measures), its basic metric properties, the
bounded-duality estimate `|∫ g dμ - ∫ g dν| ≤ 2 * d_TV(μ,ν)` for `|g| ≤ 1`, monotonicity under
kernels and under `·.prod ρ`, the notion `TVLocalTendsto` of blueprint `E_BRANCH_BLUEPRINT.md` §2,
and the local coordinate map `locField R` recording a field sample at the dyadic folded circles
inside `closedBall 0 R` (using `QuantumZipper.Factorization.coords`, blueprint A4).

Sources (standard facts, all with own elementary proofs; cf. `DEVIATIONS.md`):
* D. A. Levin, Y. Peres, E. L. Wilmer, *Markov Chains and Mixing Times*, 2nd ed., §4.1 (the
  coupling definition of `‖μ - ν‖_TV`, its metric properties and `‖μP - νP‖_TV ≤ ‖μ - ν‖_TV`);
  we use the equivalent sup-over-measurable-sets formulation, as in the blueprint.
* A. Klenke, *Probability Theory*, Ch. 13 (the duality estimate `|∫ g dμ - ∫ g dν| ≤ ‖g‖_∞ · d_TV`
  for bounded `g`, here stated with the weaker constant `2` as required by `TASKS.md` R12).
* AUDIT5 N2: the finiteness/probability hypotheses in `abs_integral_sub_le` and
  `tvDist_prod_right_le` are needed; without them the statements are false (`toReal ⊤ = 0`).
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter
open scoped ENNReal Topology

namespace QuantumZipper

namespace TV

/-! ## The total variation distance -/

/-- The total variation distance of two measures on a measurable space, as the supremum of
`|μ s - ν s|` over measurable sets, valued in `ℝ≥0∞`. -/
def tvDist {α : Type*} [MeasurableSpace α] (μ ν : Measure α) : ℝ≥0∞ :=
  ⨆ (s : Set α) (_ : MeasurableSet s), (μ s - ν s) ⊔ (ν s - μ s)

section Basic

variable {α : Type*} [MeasurableSpace α] {μ ν ρ : Measure α}

/-- The two halves of the defining supremum. -/
theorem le_tvDist {s : Set α} (hs : MeasurableSet s) : μ s - ν s ≤ tvDist μ ν :=
  le_iSup₂_of_le s hs le_sup_left

theorem le_tvDist' {s : Set α} (hs : MeasurableSet s) : ν s - μ s ≤ tvDist μ ν :=
  le_iSup₂_of_le s hs le_sup_right

theorem tvDist_comm : tvDist μ ν = tvDist ν μ :=
  iSup_congr fun _ => iSup_congr fun _ => sup_comm _ _

theorem tvDist_self : tvDist μ μ = 0 := by
  simp [tvDist]

theorem tvDist_triangle [IsFiniteMeasure μ] [IsFiniteMeasure ν] [IsFiniteMeasure ρ] :
    tvDist μ ρ ≤ tvDist μ ν + tvDist ν ρ := by
  refine iSup_le fun s => iSup_le fun hs => sup_le ?_ ?_
  · exact (tsub_le_tsub_add_tsub (a := μ s) (b := ν s) (c := ρ s)).trans
      (add_le_add (le_tvDist hs) (le_tvDist hs))
  · refine (tsub_le_tsub_add_tsub (a := ρ s) (b := ν s) (c := μ s)).trans ?_
    rw [add_comm (tvDist μ ν) (tvDist ν ρ)]
    exact add_le_add (le_tvDist' (μ := ν) (ν := ρ) hs) (le_tvDist' (μ := μ) (ν := ν) hs)

theorem tvDist_le_one [IsProbabilityMeasure μ] [IsProbabilityMeasure ν] : tvDist μ ν ≤ 1 := by
  refine iSup_le fun s => iSup_le fun _ => sup_le ?_ ?_
  · have hμ : μ s ≤ 1 := by
      rw [← IsProbabilityMeasure.measure_univ (μ := μ)]
      exact measure_mono (Set.subset_univ s)
    exact (tsub_le_self).trans hμ
  · have hν : ν s ≤ 1 := by
      rw [← IsProbabilityMeasure.measure_univ (μ := ν)]
      exact measure_mono (Set.subset_univ s)
    exact (tsub_le_self).trans hν

theorem tvDist_map_le {β : Type*} [MeasurableSpace β] {f : α → β} (hf : Measurable f) :
    tvDist (μ.map f) (ν.map f) ≤ tvDist μ ν := by
  refine iSup_le fun s => iSup_le fun hs => sup_le ?_ ?_
  · rw [Measure.map_apply hf hs, Measure.map_apply hf hs]
    exact le_tvDist (hf hs)
  · rw [Measure.map_apply hf hs, Measure.map_apply hf hs]
    exact le_tvDist' (hf hs)

/-- For finite measures the total variation distance is finite (`toReal` is applied to it in
`abs_integral_sub_le`). -/
theorem tvDist_lt_top [IsFiniteMeasure μ] [IsFiniteMeasure ν] : tvDist μ ν < ⊤ := by
  have h : tvDist μ ν ≤ μ Set.univ + ν Set.univ :=
    iSup_le fun s => iSup_le fun _ => sup_le
      (((tsub_le_self).trans (measure_mono (μ := μ) (Set.subset_univ s))).trans le_self_add)
      (((tsub_le_self).trans (measure_mono (μ := ν) (Set.subset_univ s))).trans le_add_self)
  exact lt_of_le_of_lt h (ENNReal.add_lt_top.mpr
    ⟨IsFiniteMeasure.measure_univ_lt_top, IsFiniteMeasure.measure_univ_lt_top⟩)

theorem tvDist_ne_top [IsFiniteMeasure μ] [IsFiniteMeasure ν] : tvDist μ ν ≠ ⊤ :=
  (tvDist_lt_top (μ := μ) (ν := ν)).ne

end Basic

/-! ## Bounded duality

The key estimate: for a measurable `g : α → ℝ≥0∞` with `g ≤ 1` the difference of the integrals
against `μ` and `ν` is bounded by `tvDist μ ν`.  Proof: layer cake (`lintegral_eq_lintegral_meas_lt`)
turns `∫⁻ g` into the integral over `t ∈ (0,1]` of `μ {g > t}` (valid because `g ≤ 1` bounds the
level sets above `1` to be empty), and each level set is compared by the defining property of
`tvDist`.  No finiteness of `μ`, `ν` is needed. -/

section Duality

variable {α : Type*} [MeasurableSpace α] {μ ν : Measure α}

/-- Bounded duality in `ℝ≥0∞` form, for `ℝ`-valued `f`. -/
theorem ofReal_lintegral_le_add_tvDist {f : α → ℝ} (hf : Measurable f) (h0 : ∀ x, 0 ≤ f x)
    (h1 : ∀ x, f x ≤ 1) :
    ∫⁻ x, ENNReal.ofReal (f x) ∂μ ≤ ∫⁻ x, ENNReal.ofReal (f x) ∂ν + tvDist μ ν := by
  have hfnn : 0 ≤ᵐ[μ] f := Eventually.of_forall h0
  have hfnnν : 0 ≤ᵐ[ν] f := Eventually.of_forall h0
  have hlayerμ : ∫⁻ x, ENNReal.ofReal (f x) ∂μ = ∫⁻ t in Set.Ioi (0 : ℝ), μ {a | t < f a} :=
    lintegral_eq_lintegral_meas_lt μ hfnn hf.aemeasurable
  have hlayerν : ∫⁻ x, ENNReal.ofReal (f x) ∂ν = ∫⁻ t in Set.Ioi (0 : ℝ), ν {a | t < f a} :=
    lintegral_eq_lintegral_meas_lt ν hfnnν hf.aemeasurable
  have hIoi : ∫⁻ t in Set.Ioi (0 : ℝ), μ {a | t < f a} =
      ∫⁻ t in Set.Ioc (0 : ℝ) 1, μ {a | t < f a} := by
    have hU : Set.Ioi (0 : ℝ) = Set.Ioc 0 1 ∪ Set.Ioi 1 := by
      ext t
      simp only [Set.mem_Ioi, Set.mem_union, Set.mem_Ioc]
      constructor
      · intro h
        by_cases h' : t ≤ 1
        · exact Or.inl ⟨h, h'⟩
        · exact Or.inr (not_le.mp h')
      · rintro (⟨h, -⟩ | h)
        · exact h
        · exact lt_trans one_pos h
    rw [hU, lintegral_union measurableSet_Ioi (by
      rw [Set.disjoint_left]
      exact fun t ht ht' => absurd ht' (not_lt.mpr ht.2))]
    have hz : ∫⁻ t in Set.Ioi (1 : ℝ), μ {a | t < f a} = 0 := by
      have h0 : ∀ t ∈ Set.Ioi (1 : ℝ), μ {a | t < f a} = 0 := fun t ht =>
        measure_mono_null
          (fun a ha => absurd ha (not_lt.mpr ((lt_of_le_of_lt (h1 a) ht).le))) measure_empty
      rw [setLIntegral_congr_fun measurableSet_Ioi h0]
      simp
    rw [hz, add_zero]
  have hIoiν : ∫⁻ t in Set.Ioi (0 : ℝ), ν {a | t < f a} =
      ∫⁻ t in Set.Ioc (0 : ℝ) 1, ν {a | t < f a} := by
    have hU : Set.Ioi (0 : ℝ) = Set.Ioc 0 1 ∪ Set.Ioi 1 := by
      ext t
      simp only [Set.mem_Ioi, Set.mem_union, Set.mem_Ioc]
      constructor
      · intro h
        by_cases h' : t ≤ 1
        · exact Or.inl ⟨h, h'⟩
        · exact Or.inr (not_le.mp h')
      · rintro (⟨h, -⟩ | h)
        · exact h
        · exact lt_trans one_pos h
    rw [hU, lintegral_union measurableSet_Ioi (by
      rw [Set.disjoint_left]
      exact fun t ht ht' => absurd ht' (not_lt.mpr ht.2))]
    have hz : ∫⁻ t in Set.Ioi (1 : ℝ), ν {a | t < f a} = 0 := by
      have h0 : ∀ t ∈ Set.Ioi (1 : ℝ), ν {a | t < f a} = 0 := fun t ht =>
        measure_mono_null
          (fun a ha => absurd ha (not_lt.mpr ((lt_of_le_of_lt (h1 a) ht).le))) measure_empty
      rw [setLIntegral_congr_fun measurableSet_Ioi h0]
      simp
    rw [hz, add_zero]
  have hbdd : ∀ t : ℝ, μ {a | t < f a} ≤ ν {a | t < f a} + tvDist μ ν := fun t =>
    tsub_le_iff_left.mp (le_tvDist (measurableSet_lt measurable_const hf))
  calc ∫⁻ x, ENNReal.ofReal (f x) ∂μ = ∫⁻ t in Set.Ioc (0 : ℝ) 1, μ {a | t < f a} := by
        rw [hlayerμ, hIoi]
    _ ≤ ∫⁻ t in Set.Ioc (0 : ℝ) 1, (ν {a | t < f a} + tvDist μ ν) := lintegral_mono hbdd
    _ = ∫⁻ t in Set.Ioc (0 : ℝ) 1, (tvDist μ ν + ν {a | t < f a}) :=
        lintegral_congr fun t => add_comm _ _
    _ = tvDist μ ν + ∫⁻ t in Set.Ioc (0 : ℝ) 1, ν {a | t < f a} := by
        rw [lintegral_add_left (f := fun _ : ℝ => tvDist μ ν) measurable_const]
        rw [lintegral_const, Measure.restrict_apply MeasurableSet.univ, Set.univ_inter,
          Real.volume_Ioc]
        norm_num
    _ = ∫⁻ x, ENNReal.ofReal (f x) ∂ν + tvDist μ ν := by
        rw [add_comm, hlayerν, ← hIoiν]

/-- Bounded duality: `∫⁻ g dμ ≤ ∫⁻ g dν + tvDist μ ν` for measurable `g ≤ 1`. -/
theorem lintegral_le_lintegral_add_tvDist {g : α → ℝ≥0∞} (hg : Measurable g)
    (h1 : ∀ x, g x ≤ 1) :
    ∫⁻ x, g x ∂μ ≤ ∫⁻ x, g x ∂ν + tvDist μ ν := by
  have hgne : ∀ x, g x ≠ ⊤ := fun x => ne_top_of_le_ne_top ENNReal.one_ne_top (h1 x)
  have key := ofReal_lintegral_le_add_tvDist (μ := μ) (ν := ν) (f := fun x => (g x).toReal)
    (ENNReal.measurable_toReal.comp hg) (fun x => ENNReal.toReal_nonneg) (fun x =>
      ENNReal.toReal_mono ENNReal.one_ne_top (h1 x))
  have hμ : ∫⁻ x, ENNReal.ofReal ((g x).toReal) ∂μ = ∫⁻ x, g x ∂μ :=
    lintegral_congr fun x => ENNReal.ofReal_toReal (hgne x)
  have hν : ∫⁻ x, ENNReal.ofReal ((g x).toReal) ∂ν = ∫⁻ x, g x ∂ν :=
    lintegral_congr fun x => ENNReal.ofReal_toReal (hgne x)
  rw [hμ, hν] at key
  exact key

end Duality

/-! ## The bounded-integral estimate -/

section Integral

variable {α : Type*} [MeasurableSpace α] {μ ν : Measure α}

/-- `|∫ g dμ - ∫ g dν| ≤ 2 * (tvDist μ ν).toReal` for measurable `g` with `|g| ≤ 1` and finite
`μ`, `ν` (the factor `2` is the one required by `TASKS.md` R12; with the unnormalized definition
of `tvDist` used here this is the natural constant, cf. `tvDist_le_one`, and the proof below
gives exactly `2`).  Finiteness of `μ`, `ν` is needed for integrability of `g` and for
`(tvDist μ ν).toReal ≠ 0`; without it the statement is false (AUDIT5 N2). -/
theorem abs_integral_sub_le [IsFiniteMeasure μ] [IsFiniteMeasure ν] {g : α → ℝ}
    (hg : Measurable g) (hb : ∀ x, |g x| ≤ 1) :
    |∫ x, g x ∂μ - ∫ x, g x ∂ν| ≤ 2 * (tvDist μ ν).toReal := by
  have hCtop : tvDist μ ν ≠ ⊤ := tvDist_ne_top (μ := μ) (ν := ν)
  have key : ∀ (h : α → ℝ), Measurable h → (∀ x, |h x| ≤ 1) →
      ∫ x, h x ∂μ - ∫ x, h x ∂ν ≤ 2 * (tvDist μ ν).toReal := by
    intro h hh hhb
    have hbnd : ∀ᵐ x ∂μ, ‖h x‖ ≤ 1 := Eventually.of_forall fun x => by
      simpa [Real.norm_eq_abs] using hhb x
    have hbndν : ∀ᵐ x ∂ν, ‖h x‖ ≤ 1 := Eventually.of_forall fun x => by
      simpa [Real.norm_eq_abs] using hhb x
    have hihμ : Integrable h μ := Integrable.of_bound hh.aestronglyMeasurable 1 hbnd
    have hihν : Integrable h ν := Integrable.of_bound hh.aestronglyMeasurable 1 hbndν
    have hm1 : Measurable fun x => ENNReal.ofReal (h x) := ENNReal.measurable_ofReal.comp hh
    have hm2 : Measurable fun x => ENNReal.ofReal (-h x) := ENNReal.measurable_ofReal.comp hh.neg
    have hb1 : ∀ x, ENNReal.ofReal (h x) ≤ 1 := fun x =>
      ENNReal.ofReal_le_one.mpr ((le_abs_self (h x)).trans (hhb x))
    have hb2 : ∀ x, ENNReal.ofReal (-h x) ≤ 1 := fun x =>
      ENNReal.ofReal_le_one.mpr ((neg_le_abs (h x)).trans (hhb x))
    have e1 := lintegral_le_lintegral_add_tvDist (μ := μ) (ν := ν) hm1 hb1
    have e2 := lintegral_le_lintegral_add_tvDist (μ := ν) (ν := μ) hm2 hb2
    have htopB : ∫⁻ x, ENNReal.ofReal (h x) ∂ν < ⊤ := by
      refine lt_of_le_of_lt ?_ (IsFiniteMeasure.measure_univ_lt_top (μ := ν))
      calc ∫⁻ x, ENNReal.ofReal (h x) ∂ν ≤ ∫⁻ _, (1 : ℝ≥0∞) ∂ν := lintegral_mono hb1
        _ = ν Set.univ := by simp
    have htopE : ∫⁻ x, ENNReal.ofReal (-h x) ∂ν < ⊤ := by
      refine lt_of_le_of_lt ?_ (IsFiniteMeasure.measure_univ_lt_top (μ := ν))
      calc ∫⁻ x, ENNReal.ofReal (-h x) ∂ν ≤ ∫⁻ _, (1 : ℝ≥0∞) ∂ν := lintegral_mono hb2
        _ = ν Set.univ := by simp
    have htopD : ∫⁻ x, ENNReal.ofReal (-h x) ∂μ < ⊤ := by
      refine lt_of_le_of_lt ?_ (IsFiniteMeasure.measure_univ_lt_top (μ := μ))
      calc ∫⁻ x, ENNReal.ofReal (-h x) ∂μ ≤ ∫⁻ _, (1 : ℝ≥0∞) ∂μ := lintegral_mono hb2
        _ = μ Set.univ := by simp
    set A : ℝ := ENNReal.toReal (∫⁻ x, ENNReal.ofReal (h x) ∂μ) with hAdef
    set B : ℝ := ENNReal.toReal (∫⁻ x, ENNReal.ofReal (h x) ∂ν) with hBdef
    set D : ℝ := ENNReal.toReal (∫⁻ x, ENNReal.ofReal (-h x) ∂μ) with hDdef
    set E : ℝ := ENNReal.toReal (∫⁻ x, ENNReal.ofReal (-h x) ∂ν) with hEdef
    set C : ℝ := ENNReal.toReal (tvDist μ ν) with hCdef
    have hA : A ≤ B + C := by
      rw [hAdef, hBdef, hCdef]
      exact (ENNReal.toReal_mono
        (ENNReal.add_lt_top.mpr ⟨htopB, lt_top_iff_ne_top.mpr hCtop⟩).ne e1).trans
        ENNReal.toReal_add_le
    have hE : E ≤ D + C := by
      rw [hEdef, hDdef, hCdef]
      have hfin : (∫⁻ x, ENNReal.ofReal (-h x) ∂μ) + tvDist ν μ ≠ ⊤ :=
        (ENNReal.add_lt_top.mpr ⟨htopD, lt_top_iff_ne_top.mpr
          (by rw [tvDist_comm]; exact hCtop)⟩).ne
      have hb := (ENNReal.toReal_mono hfin e2).trans ENNReal.toReal_add_le
      rwa [tvDist_comm] at hb
    have hAB : A - B ≤ C := sub_le_iff_le_add.mpr (hA.trans_eq (add_comm B C))
    have hED : E - D ≤ C := sub_le_iff_le_add.mpr (hE.trans_eq (add_comm D C))
    rw [integral_eq_lintegral_pos_part_sub_lintegral_neg_part hihμ,
      integral_eq_lintegral_pos_part_sub_lintegral_neg_part hihν]
    show A - D - (B - E) ≤ 2 * C
    linarith [hAB, hED]
  have h1 := key g hg hb
  have h2 : -(∫ x, g x ∂μ - ∫ x, g x ∂ν) ≤ 2 * (tvDist μ ν).toReal := by
    have hneg := key (fun x => -g x) hg.neg (fun x => by simpa using hb x)
    simpa [integral_neg, sub_eq_add_neg, add_comm] using hneg
  exact abs_le.mpr ⟨by linarith, h1⟩

end Integral

/-! ## Kernels and products -/

section Kernel

variable {α β : Type*} [MeasurableSpace α] [MeasurableSpace β] {μ : Measure α}

/-- Composing one measure with two Markov kernels is `1`-Lipschitz for `tvDist` against the
average of the pointwise distances (Levin–Peres–Wilmer, *Markov Chains and Mixing Times* §4.1,
the "TV is non-increasing under applications of a transition matrix" bound in the general
kernel form). -/
theorem tvDist_bind_le (κ₁ κ₂ : Kernel α β) [IsMarkovKernel κ₁] [IsMarkovKernel κ₂] :
    tvDist (μ.bind κ₁) (μ.bind κ₂) ≤ ∫⁻ x, tvDist (κ₁ x) (κ₂ x) ∂μ := by
  refine iSup_le fun s => iSup_le fun hs => sup_le ?_ ?_
  · have hb : (μ.bind κ₁) s ≤ (μ.bind κ₂) s + ∫⁻ x, tvDist (κ₁ x) (κ₂ x) ∂μ := by
      rw [Measure.bind_apply hs κ₁.measurable.aemeasurable,
        Measure.bind_apply hs κ₂.measurable.aemeasurable]
      calc ∫⁻ x, κ₁ x s ∂μ ≤ ∫⁻ x, (κ₂ x s + tvDist (κ₁ x) (κ₂ x)) ∂μ :=
            lintegral_mono fun x =>
              (le_add_tsub (a := κ₁ x s) (b := κ₂ x s)).trans
                (add_le_add le_rfl (le_tvDist (μ := κ₁ x) (ν := κ₂ x) hs))
        _ = ∫⁻ x, κ₂ x s ∂μ + ∫⁻ x, tvDist (κ₁ x) (κ₂ x) ∂μ :=
            lintegral_add_left (κ₂.measurable_coe hs) _
    exact tsub_le_iff_left.mpr hb
  · have hb : (μ.bind κ₂) s ≤ (μ.bind κ₁) s + ∫⁻ x, tvDist (κ₁ x) (κ₂ x) ∂μ := by
      rw [Measure.bind_apply hs κ₂.measurable.aemeasurable,
        Measure.bind_apply hs κ₁.measurable.aemeasurable]
      calc ∫⁻ x, κ₂ x s ∂μ ≤ ∫⁻ x, (κ₁ x s + tvDist (κ₁ x) (κ₂ x)) ∂μ :=
            lintegral_mono fun x =>
              (le_add_tsub (a := κ₂ x s) (b := κ₁ x s)).trans
                (add_le_add le_rfl (le_tvDist' (μ := κ₁ x) (ν := κ₂ x) hs))
        _ = ∫⁻ x, κ₁ x s ∂μ + ∫⁻ x, tvDist (κ₁ x) (κ₂ x) ∂μ :=
            lintegral_add_left (κ₁.measurable_coe hs) _
    exact tsub_le_iff_left.mpr hb

end Kernel

section Prod

variable {α β : Type*} [MeasurableSpace α] [MeasurableSpace β] {μ ν : Measure α}
  {ρ : Measure β}

/-- Multiplying on the right by a fixed probability measure is `1`-Lipschitz for `tvDist`. -/
theorem tvDist_prod_right_le [SFinite μ] [SFinite ν] [IsProbabilityMeasure ρ] :
    tvDist (μ.prod ρ) (ν.prod ρ) ≤ tvDist μ ν := by
  refine iSup_le fun t => iSup_le fun ht => sup_le ?_ ?_
  · have hg : Measurable fun x => ρ (Prod.mk x ⁻¹' t) := measurable_measure_prodMk_left ht
    have hg1 : ∀ x, ρ (Prod.mk x ⁻¹' t) ≤ 1 := fun x => by
      have h := measure_mono (μ := ρ) (Set.subset_univ (Prod.mk x ⁻¹' t))
      simpa using h
    rw [Measure.prod_apply ht, Measure.prod_apply ht]
    exact tsub_le_iff_left.mpr (lintegral_le_lintegral_add_tvDist (μ := μ) (ν := ν) hg hg1)
  · have hg : Measurable fun x => ρ (Prod.mk x ⁻¹' t) := measurable_measure_prodMk_left ht
    have hg1 : ∀ x, ρ (Prod.mk x ⁻¹' t) ≤ 1 := fun x => by
      have h := measure_mono (μ := ρ) (Set.subset_univ (Prod.mk x ⁻¹' t))
      simpa using h
    rw [Measure.prod_apply ht, Measure.prod_apply ht]
    exact (tsub_le_iff_left.mpr
      (lintegral_le_lintegral_add_tvDist (μ := ν) (ν := μ) hg hg1)).trans_eq
      (tvDist_comm (μ := ν) (ν := μ))

end Prod

/-! ## TV-local convergence and the local coordinate map -/

/-- TV-local convergence of a family of measures towards `μ`, as in blueprint
`E_BRANCH_BLUEPRINT.md` §2: for every radius `R`, the pushforwards under the local data map
`loc R` converge in total variation to the pushforward of `μ`. -/
def TVLocalTendsto {ι E : Type*} [MeasurableSpace E] (l : Filter ι) (μs : ι → Measure E)
    (μ : Measure E) {F : ℕ → Type*} [∀ R, MeasurableSpace (F R)] (loc : ∀ R, E → F R) : Prop :=
  ∀ R, Tendsto (fun i => tvDist ((μs i).map (loc R)) (μ.map (loc R))) l (𝓝 0)

/-- The `n`-th dyadic folded circle lies in `closedBall 0 R`: its centre is
`(dyadicIndex n).1` and its radius is `radius (dyadicIndex n).2`, so the folded circle (a circle
of radius `radius (dyadicIndex n).2` about the centre, reflected into `Hbar`) is contained in
`closedBall 0 R` exactly when `‖centre‖ + radius ≤ R`. -/
def inBall (R n : ℕ) : Prop :=
  ‖(Factorization.dyadicIndex n).1‖ + radius (Factorization.dyadicIndex n).2 ≤ (R : ℝ)

open Classical in
/-- The local coordinates of a field sample at the dyadic folded circles lying in
`closedBall 0 R`: the `n`-th coordinate is the raw value `coords x n` when the `n`-th dyadic
folded circle is inside `closedBall 0 R`, and `0` otherwise (junk value, as in
`Factorization.reconstruct`). -/
def locField (R : ℕ) (x : FieldSample) : ℕ → ℝ := fun n =>
  if inBall R n then Factorization.coords x n else 0

theorem measurable_locField (R : ℕ) : Measurable (locField R) := by
  classical
  refine measurable_pi_iff.2 fun n => ?_
  unfold locField
  by_cases h : inBall R n
  · simp only [h, ite_true]
    exact (measurable_pi_apply n).comp Factorization.measurable_coords
  · simp only [h, ite_false]
    exact measurable_const

end TV

end QuantumZipper
