import ReflectedGMS.Process.AreaClockRealTimeShift
import ReflectedGMS.Temporal.TrajectoryCoding
import ReflectedGMS.Temporal.AnnealedTemporalTransport
import Mathlib.Probability.Kernel.MeasurableLIntegral
import ReflectedGMS.Temporal.TemporalMassTransport
import ReflectedGMS.Environment.CellArea

/-! # Real-time shift invariance of the area mixture on the càdlàg coding

`Process/AreaClockRealTimeShift` proves that the area-weighted two-sided law
`𝕢 = ∑_v a_v ℙ^v` of the area clock has shift-invariant finite-dimensional distributions at
arbitrary real times.  `Temporal/FixedEnvironmentTemporalTransport` consumes shift invariance
of the corresponding mixture on the càdlàg coding `CadlagPath S`
(`IsShiftInvariantMixture`).  This file is the bridge: **any** family of coded laws with the
finite-dimensional distributions of the two-sided process (`CodedTwoSidedLaw`) has a
shift-invariant area mixture — the manuscript's

> The sigma-finite path measure `𝕢_H = ∑_v a_v ℙ_H^v` is invariant under every
> deterministic time shift.  This follows directly from the Markov cylinder distributions
> and `a_v p_t(v,u) = a_u p_t(u,v)`.

The route is `CadlagPath.measurePreserving_timeShift_of_ratEval_law` (the coding σ-algebra
is generated by rational times), with the two σ-finite laws on `ℚ → S` identified by
`Measure.ext_of_generateFrom_of_iUnion` on the π-system of point cylinders
(`S` countable; the cover is by `{ξ 0 = c}`, of mass at most one cell area).

## Hypotheses

* `IsReflectedWalk` and detailed balance at every time (discharged for the area clock by
  `AreaReversibility.processTransitionReversible_cellArea`);
* an injective coding `code : Option V → S` (the manuscript's `ℕ ∪ {∞}` with every
  nonvertex state collapsed to `∞`), `S` countable;
* `CodedTwoSidedLaw PF code P`: `P v` has the finite-dimensional distributions of the coded
  two-sided process from `v`.  **Satisfiable**: it holds whenever `P v` is the image of
  `twoSidedStartLaw PF v` under an a.s. defined coding map into `CadlagPath S`
  (`codedTwoSidedLaw_of_map`); no such map is constructed for the actual process in the tree.

## What is *not* proved

The existence of the coding map for the actual two-sided area-clock path (càdlàg in the
one-point compactification: right-regularity (ii)+(R) forward, left limits for the reversed
half from `Forms/VertexIndicatorLeftLimits`), hence of a `MarkedPathProcess` for the actual
process.  Nothing here certifies `ScaledRootChainSystem.transport` or either main theorem.
-/

-- Merged from `ReflectedGMS/Temporal/FixedEnvironmentTemporalTransport.lean` (Packet C, 2026-09-18); names unchanged.
section Merged_FixedEnvironmentTemporalTransport

/-! # The fixed-environment half of `p:lem:timeMTP`, welded to the annealed half

`Temporal/ActualAnnealedTemporalTransport.actualTemporalMassTransport` proves the annealed step
of the manuscript proof of `p:lem:timeMTP` (tex:1379-1397) for a `MarkedPathProcess`:

```
  E ∑_{H'} E_H^{H_0} ∫ 1_{X_t = H'} V(Ω,0,t) dt  =  E ∑_v (a_v/a_o) E_H^v ∫ 1_{X_t = o} V(Ω,0,t) dt,
```

and names the remaining producer: "for each deterministic `t`, shift the sigma-finite measure
`𝕢_H = ∑_v a_v ℙ_H^v` by `t`" — the **fixed-environment half**.  This file supplies it and
assembles the two halves into the manuscript's identity `p:eq:timeMTP` itself,

```
  E ∫_ℝ V(Ω,0,t) dt  =  E ∫_ℝ V(Ω,t,0) dt ,
```

for the marked process, with the fixed-environment shift invariance as the one named input.

## What is proved

* `sum_mul_lintegral_pathNumerator_eq` — **the fixed-environment half**, on the càdlàg
  coding, for any countable family of laws `P v` mixed with any weights `a v`:
  if `𝕢 = ∑_v a_v P v` is invariant under every real time shift and `P v` starts at
  `label v`, then for every measurable time-shift covariant `W`,
  `∑_v a_v E^v ∫ 1_{X_t = label o} W(0,t) dt = a_o E^o ∫ W(s,0) ds`.
  Route: `TemporalMassTransport.lintegral_lintegral_timeTransport` applied to the
  root-marked kernel `W'(ω,s,t) = 1_{ω_t = label o} W(ω,s,t)`, which is again covariant.
* `rootedIncoming_eq_of_fixedEnvironment`, `rootedOutgoing_eq_of_target` — the two
  expressions of `actualTemporalMassTransport`, identified with `E^{H_0} ∫ V(s,0) ds` and
  `E^{H_0} ∫ V(0,t) dt`.  The cell-area factor cancels by `cellVolume_pos_lt_top`.
* `lintegral_timeMTP_of_fixedEnvironment` — **`p:eq:timeMTP` for the marked process**,
  from `MassTransport ν` and, for `ν`-a.e. environment, `FixedEnvironmentShiftInvariant`
  (the σ-finite area mixture is real-time shift invariant, and `ℙ_H^v` starts at `v`),
  time-shift covariance of `V`, and "values at nonvertex target times are set to zero".
* `isShiftInvariantMixture_const` — **satisfiability** of the shift hypothesis in the
  abstract form (constant-path laws).

## Why the root is the Palm root (the handoff's trap)

The shift invariance is of the **area-weighted σ-finite mixture** `∑_v a_v ℙ_H^v`, never of
a single `ℙ_H^v`; the passage to one root happens only after spatial mass transport, at the
root cell `H_0` of the environment law.  The identity is false for a fixed environment and a
single start (`outputs/fable-regenerative-invariance-handoff.md`, TRAP), and nothing here
asserts it there.

## What is *not* proved

The hypothesis `FixedEnvironmentShiftInvariant` for the **actual** marked process.  Its
finite-dimensional content — real-time shift invariance of `∑_v a_v ℙ_H^v` on every finite
set of real times — is `Process/AreaClockRealTimeShift.twoSidedSpeedLaw_cellArea_realCyl_shift`
(unconditional); the transfer to the coding is `Temporal/AreaClockCodingShift`.  No
`MarkedPathProcess` for the actual process is constructed anywhere.  Nothing here certifies
`ScaledRootChainSystem.transport` (`ParabolicTemporalTransport` on the rooted flow), the
marked `p:lem:timeMTP`, or either main theorem.
-/

set_option autoImplicit false

open MeasureTheory Set
open scoped ENNReal

namespace ReflectedGMS.FixedEnvironmentTemporalTransport

open Code EnvironmentLaws TrajectoryCoding TrajectoryCoding.CadlagPath
open TemporalMassTransport

variable {S : Type*} [TopologicalSpace S] [MeasurableSpace S] [BorelSpace S]
  [TopologicalSpace.PseudoMetrizableSpace S] [MeasurableSingletonClass S]

/-! ## The weighted fixed-environment mixture on the coding -/

/-- The σ-finite fixed-environment path measure `𝕢 = ∑_v a_v ℙ^v` of `p:eq:sigmapath`, on the
càdlàg coding.  No finiteness of the total weight. -/
noncomputable def weightedPathMixture {ι : Type*} (a : ι → ℝ≥0∞)
    (P : ι → Measure (CadlagPath S)) : Measure (CadlagPath S) :=
  Measure.sum fun v => a v • P v

/-- **The fixed-environment hypothesis of `p:lem:timeMTP`**, abstractly: the weighted
mixture is invariant under every real time shift, and each `P v` starts at its label. -/
def IsShiftInvariantMixture {ι : Type*} (a : ι → ℝ≥0∞) (P : ι → Measure (CadlagPath S))
    (label : ι → S) : Prop :=
  (∀ r : ℝ, MeasurePreserving (timeShift r) (weightedPathMixture a P) (weightedPathMixture a P))
    ∧ ∀ v, ∀ᵐ ω ∂P v, ω.toFun 0 = label v

/-! ## The fixed-environment half -/

/-! ## Satisfiability of the fixed-environment hypothesis -/

/-! ## The marked process -/

end ReflectedGMS.FixedEnvironmentTemporalTransport

end Merged_FixedEnvironmentTemporalTransport

set_option autoImplicit false

open MeasureTheory Set
open scoped ENNReal NNReal

namespace ReflectedGMS.AreaClockCodingShift

open ReflectedWalk ReflectedWalk.Theorem16 ReflectedGMS.TwoSided
open ReflectedGMS.AreaClockRealTimeShift
open TrajectoryCoding TrajectoryCoding.CadlagPath FixedEnvironmentTemporalTransport

universe u

variable {V : Type u} [MeasurableSpace V] [MeasurableSingletonClass V]
  [Countable V] [Nontrivial V] [DecidableEq V]
variable {S : Type*} [TopologicalSpace S] [MeasurableSpace S] [BorelSpace S]
  [TopologicalSpace.PseudoMetrizableSpace S] [MeasurableSingletonClass S]

/-! ## Coded cylinders of the two-sided process -/

/-- The coded two-sided cylinder `{code (X_{τ q}) = s q for all q ∈ J}`. -/
def codedCyl (PF : ProcessFamily V) (code : Option V → S) (J : Finset ℚ) (τ : ℚ → ℝ)
    (s : ℚ → S) : Set (PF.Ω × PF.Ω) :=
  {ω | ∀ q ∈ J, code (twoSidedReal PF ω (τ q)) = s q}

theorem measurableSet_codedCyl (PF : ProcessFamily V) (code : Option V → S) (J : Finset ℚ)
    (τ : ℚ → ℝ) (s : ℚ → S) : MeasurableSet (codedCyl PF code J τ s) := by
  have hset : codedCyl PF code J τ s = ⋂ q ∈ (J : Set ℚ),
      (fun ω => twoSidedReal PF ω (τ q)) ⁻¹' (code ⁻¹' {s q}) := by
    ext ω
    simp [codedCyl]
  rw [hset]
  exact MeasurableSet.biInter J.countable_toSet fun q _ =>
    measurable_twoSidedReal PF (τ q) (measurableSet_option _)

section Process

variable {G : ConductanceGraph V} {rate : V → ℝ} {hmin : G.EnergyMinimizer}
  {PF : ProcessFamily V}

/-- The two-sided path is a.s. at a vertex at every fixed real time, also for the σ-finite
weighted mixture. -/
theorem twoSidedSpeedLaw_twoSidedReal_none (h : IsReflectedWalk G rate hmin PF) (w : V → ℝ)
    (t : ℝ) : twoSidedSpeedLaw PF w {ω | twoSidedReal PF ω t = none} = 0 := by
  have hmeas : MeasurableSet {ω : PF.Ω × PF.Ω | twoSidedReal PF ω t = none} :=
    measurable_twoSidedReal PF t (measurableSet_option {none})
  rw [twoSidedSpeedLaw_apply PF w hmeas]
  refine ENNReal.tsum_eq_zero.2 fun z => ?_
  rw [twoSidedStartLaw]
  by_cases ht : 0 ≤ t
  · have hset : {ω : PF.Ω × PF.Ω | twoSidedReal PF ω t = none} =
        {ω₁ | PF.X t.toNNReal ω₁ = none} ×ˢ (univ : Set PF.Ω) := by
      ext ω
      simp [twoSidedReal, ht]
    rw [hset, Measure.prod_prod, measure_none_eq_zero (h z).2.1, zero_mul, mul_zero]
  · have hset : {ω : PF.Ω × PF.Ω | twoSidedReal PF ω t = none} =
        (univ : Set PF.Ω) ×ˢ {ω₂ | PF.X (-t).toNNReal ω₂ = none} := by
      ext ω
      simp [twoSidedReal, ht]
    rw [hset, Measure.prod_prod, measure_none_eq_zero (h z).2.1, mul_zero, mul_zero]

/-- **Real-time shift invariance of coded two-sided cylinders.**  Prescribed codes outside the
vertex codes give null cylinders; otherwise the cylinder is a real-time vertex cylinder and
`twoSidedSpeedLaw_realCyl_shift` applies. -/
theorem twoSidedSpeedLaw_codedCyl_shift (h : IsReflectedWalk G rate hmin PF) (w : V → ℝ)
    (hrev : ∀ (t : ℝ≥0) (x y : V),
      ENNReal.ofReal (w x) * PF.transition x t y = ENNReal.ofReal (w y) * PF.transition y t x)
    (code : Option V → S) (hcode : Function.Injective code) (J : Finset ℚ) (s : ℚ → S)
    (r : ℝ) :
    twoSidedSpeedLaw PF w (codedCyl PF code J (fun q => (q : ℝ) + r) s) =
      twoSidedSpeedLaw PF w (codedCyl PF code J (fun q => (q : ℝ)) s) := by
  classical
  by_cases hall : ∀ q ∈ J, ∃ x : V, s q = code (some x)
  · choose! g hg using hall
    let g' : ℝ → V := Function.extend (fun q : ℚ => (q : ℝ)) g fun _ => g 0
    have hg' : ∀ q : ℚ, g' (q : ℝ) = g q := fun q =>
      (Rat.cast_injective (α := ℝ)).extend_apply g _ q
    have hset : ∀ r' : ℝ, codedCyl PF code J (fun q => (q : ℝ) + r') s =
        {ω | ∀ i ∈ J.image (fun q : ℚ => (q : ℝ)), twoSidedReal PF ω (i + r') = some (g' i)} := by
      intro r'
      ext ω
      simp only [codedCyl, mem_setOf_eq, Finset.forall_mem_image, hg']
      refine forall₂_congr fun q hq => ?_
      rw [hg q hq]
      exact hcode.eq_iff
    have h0 := hset 0
    simp only [add_zero] at h0
    rw [hset r, h0]
    exact twoSidedSpeedLaw_realCyl_shift h w hrev _ g' r
  · push_neg at hall
    obtain ⟨q, hq, hne⟩ := hall
    have hsub : ∀ r' : ℝ, codedCyl PF code J (fun q => (q : ℝ) + r') s ⊆
        {ω | twoSidedReal PF ω ((q : ℝ) + r') = none} := by
      intro r' ω hω
      have hcq := hω q hq
      simp only [mem_setOf_eq]
      cases hX : twoSidedReal PF ω ((q : ℝ) + r') with
      | none => rfl
      | some x =>
          rw [hX] at hcq
          exact absurd hcq.symm (hne x)
    have h0 := hsub 0
    simp only [add_zero] at h0
    have e1 : twoSidedSpeedLaw PF w (codedCyl PF code J (fun q => (q : ℝ) + r) s) = 0 :=
      measure_mono_null (hsub r) (twoSidedSpeedLaw_twoSidedReal_none h w _)
    have e2 : twoSidedSpeedLaw PF w (codedCyl PF code J (fun q => (q : ℝ)) s) = 0 :=
      measure_mono_null h0 (twoSidedSpeedLaw_twoSidedReal_none h w _)
    rw [e1, e2]

/-- A one-time coded cylinder has finite weighted mass (at most one weight). -/
theorem twoSidedSpeedLaw_codedCyl_singleton_ne_top (h : IsReflectedWalk G rate hmin PF)
    (w : V → ℝ)
    (hrev : ∀ (t : ℝ≥0) (x y : V),
      ENNReal.ofReal (w x) * PF.transition x t y = ENNReal.ofReal (w y) * PF.transition y t x)
    (code : Option V → S) (hcode : Function.Injective code) (q : ℚ) (τ : ℚ → ℝ) (c : S) :
    twoSidedSpeedLaw PF w (codedCyl PF code {q} τ fun _ => c) ≠ ∞ := by
  classical
  by_cases hc : ∃ x : V, c = code (some x)
  · obtain ⟨x, rfl⟩ := hc
    have hset : codedCyl PF code {q} τ (fun _ => code (some x)) =
        realCyl PF {τ q} fun _ => x := by
      ext ω
      simp only [codedCyl, realCyl, mem_setOf_eq, Finset.mem_singleton, forall_eq]
      exact hcode.eq_iff
    rw [hset, twoSidedSpeedLaw_realCyl_singleton h w hrev]
    exact ENNReal.ofReal_ne_top
  · push_neg at hc
    have hsub : codedCyl PF code {q} τ (fun _ => c) ⊆ {ω | twoSidedReal PF ω (τ q) = none} := by
      intro ω hω
      have hcq := hω q (Finset.mem_singleton_self q)
      simp only [mem_setOf_eq]
      cases hX : twoSidedReal PF ω (τ q) with
      | none => rfl
      | some x =>
          rw [hX] at hcq
          exact absurd hcq.symm (hc x)
    have e1 : twoSidedSpeedLaw PF w (codedCyl PF code {q} τ fun _ => c) = 0 :=
      measure_mono_null hsub (twoSidedSpeedLaw_twoSidedReal_none h w _)
    rw [e1]
    exact ENNReal.zero_ne_top

end Process

/-! ## Coded laws and their weighted mixture -/

/-- **Finite-dimensional agreement of a family of coded laws with the two-sided process**: at
any finitely many real times, `P v` has the law of the coded two-sided process from `v`. -/
def CodedTwoSidedLaw (PF : ProcessFamily V) (code : Option V → S)
    (P : V → Measure (CadlagPath S)) : Prop :=
  ∀ (v : V) (J : Finset ℚ) (τ : ℚ → ℝ) (s : ℚ → S),
    P v {ω | ∀ q ∈ J, ω.toFun (τ q) = s q} = twoSidedStartLaw PF v (codedCyl PF code J τ s)

theorem measurableSet_pathCyl (J : Finset ℚ) (τ : ℚ → ℝ) (s : ℚ → S) :
    MeasurableSet {ω : CadlagPath S | ∀ q ∈ J, ω.toFun (τ q) = s q} := by
  have hset : {ω : CadlagPath S | ∀ q ∈ J, ω.toFun (τ q) = s q} =
      ⋂ q ∈ (J : Set ℚ), (fun ω : CadlagPath S => ω.toFun (τ q)) ⁻¹' {s q} := by
    ext ω
    simp
  rw [hset]
  exact MeasurableSet.biInter J.countable_toSet fun q _ =>
    measurable_eval (τ q) (measurableSet_singleton _)

/-- The weighted coded mixture of a cylinder is the weighted two-sided law of the coded
cylinder. -/
theorem weightedPathMixture_pathCyl (PF : ProcessFamily V) (code : Option V → S)
    (P : V → Measure (CadlagPath S)) (hP : CodedTwoSidedLaw PF code P) (w : V → ℝ)
    (J : Finset ℚ) (τ : ℚ → ℝ) (s : ℚ → S) :
    weightedPathMixture (fun v => ENNReal.ofReal (w v)) P
        {ω | ∀ q ∈ J, ω.toFun (τ q) = s q} =
      twoSidedSpeedLaw PF w (codedCyl PF code J τ s) := by
  rw [weightedPathMixture, Measure.sum_apply _ (measurableSet_pathCyl J τ s),
    twoSidedSpeedLaw_apply PF w (measurableSet_codedCyl PF code J τ s)]
  refine tsum_congr fun v => ?_
  rw [Measure.smul_apply, smul_eq_mul, hP v J τ s]

/-! ## Point cylinders on `ℚ → S` -/

/-- The point cylinder `{ξ | ξ q = s q for all q ∈ J}` on rational-time paths. -/
def ptCyl (J : Finset ℚ) (s : ℚ → S) : Set (ℚ → S) := {ξ | ∀ q ∈ J, ξ q = s q}

/-- The π-system of point cylinders. -/
def ptCyls : Set (Set (ℚ → S)) := {A | ∃ (J : Finset ℚ) (s : ℚ → S), A = ptCyl J s}

theorem measurableSet_ptCyl (J : Finset ℚ) (s : ℚ → S) : MeasurableSet (ptCyl J s) := by
  have hset : ptCyl J s = ⋂ q ∈ (J : Set ℚ), (fun ξ : ℚ → S => ξ q) ⁻¹' {s q} := by
    ext ξ
    simp [ptCyl]
  rw [hset]
  exact MeasurableSet.biInter J.countable_toSet fun q _ =>
    measurable_pi_apply q (measurableSet_singleton _)

theorem isPiSystem_ptCyls : IsPiSystem (ptCyls (S := S)) := by
  classical
  rintro _ ⟨J₁, s₁, rfl⟩ _ ⟨J₂, s₂, rfl⟩ ⟨ξ₀, hξ₁, hξ₂⟩
  refine ⟨J₁ ∪ J₂, fun q => if q ∈ J₁ then s₁ q else s₂ q, ?_⟩
  ext ξ
  simp only [ptCyl, mem_inter_iff, mem_setOf_eq, Finset.mem_union]
  constructor
  · rintro ⟨h₁, h₂⟩ q hq
    by_cases hq₁ : q ∈ J₁
    · rw [if_pos hq₁]
      exact h₁ q hq₁
    · rw [if_neg hq₁]
      exact h₂ q (hq.resolve_left hq₁)
  · intro hξ
    refine ⟨fun q hq => ?_, fun q hq => ?_⟩
    · have := hξ q (Or.inl hq)
      rwa [if_pos hq] at this
    · have := hξ q (Or.inr hq)
      by_cases hq₁ : q ∈ J₁
      · rw [if_pos hq₁] at this
        rw [this, ← hξ₁ q hq₁, hξ₂ q hq]
      · rwa [if_neg hq₁] at this

theorem generateFrom_ptCyls [Countable S] :
    MeasurableSpace.generateFrom (ptCyls (S := S)) = MeasurableSpace.pi := by
  refine le_antisymm (MeasurableSpace.generateFrom_le ?_) ?_
  · rintro _ ⟨J, s, rfl⟩
    exact measurableSet_ptCyl J s
  · refine iSup_le fun q => ?_
    refine MeasurableSpace.comap_le_iff_le_map.2 fun A _ => ?_
    change MeasurableSet[MeasurableSpace.generateFrom ptCyls] ((fun ξ : ℚ → S => ξ q) ⁻¹' A)
    have hset : (fun ξ : ℚ → S => ξ q) ⁻¹' A = ⋃ a ∈ A, ptCyl {q} fun _ => a := by
      ext ξ
      simp [ptCyl]
    rw [hset]
    exact MeasurableSet.biUnion A.to_countable fun a _ =>
      MeasurableSpace.measurableSet_generateFrom ⟨{q}, fun _ => a, rfl⟩

/-! ## The bridge -/

section Bridge

variable {G : ConductanceGraph V} {rate : V → ℝ} {hmin : G.EnergyMinimizer}
  {PF : ProcessFamily V}

/-- **The coded area mixture is invariant under every real time shift, and each coded law
starts at its vertex.**  From finite-dimensional agreement with the two-sided process and
detailed balance at every time. -/
theorem isShiftInvariantMixture_of_codedTwoSidedLaw [Countable S]
    (h : IsReflectedWalk G rate hmin PF) (w : V → ℝ)
    (hrev : ∀ (t : ℝ≥0) (x y : V),
      ENNReal.ofReal (w x) * PF.transition x t y = ENNReal.ofReal (w y) * PF.transition y t x)
    (code : Option V → S) (hcode : Function.Injective code)
    (P : V → Measure (CadlagPath S)) (hP : CodedTwoSidedLaw PF code P) :
    IsShiftInvariantMixture (fun v => ENNReal.ofReal (w v)) P fun v => code (some v) := by
  classical
  set Q := weightedPathMixture (fun v => ENNReal.ofReal (w v)) P with hQ
  -- the start
  have hstart : ∀ v, ∀ᵐ ω ∂P v, ω.toFun 0 = code (some v) := by
    intro v
    have huniv : P v univ = 1 := by
      have := hP v ∅ (fun _ => 0) (fun _ => code none)
      have hl : {ω : CadlagPath S | ∀ q ∈ (∅ : Finset ℚ), ω.toFun ((fun _ => (0 : ℝ)) q) =
          (fun _ => code none) q} = univ := by
        ext ω
        simp
      have hr : codedCyl PF code ∅ (fun _ => 0) (fun _ => code none) = univ := by
        ext ω
        simp [codedCyl]
      rw [hl, hr, measure_univ (μ := twoSidedStartLaw PF v)] at this
      exact this
    haveI : IsProbabilityMeasure (P v) := ⟨huniv⟩
    have hmeas : MeasurableSet {ω : CadlagPath S | ω.toFun 0 = code (some v)} :=
      (measurable_eval 0) (measurableSet_singleton _)
    have hone : P v {ω : CadlagPath S | ω.toFun 0 = code (some v)} = 1 := by
      have := hP v {0} (fun _ => 0) (fun _ => code (some v))
      have hl : {ω : CadlagPath S | ∀ q ∈ ({0} : Finset ℚ), ω.toFun ((fun _ => (0 : ℝ)) q) =
          (fun _ => code (some v)) q} = {ω : CadlagPath S | ω.toFun 0 = code (some v)} := by
        ext ω
        simp
      have hr : codedCyl PF code {0} (fun _ => 0) (fun _ => code (some v)) =
          {ω₁ : PF.Ω | PF.X 0 ω₁ = some v} ×ˢ (univ : Set PF.Ω) := by
        ext ω
        simp [codedCyl, twoSidedReal, hcode.eq_iff]
      rw [hl, hr, twoSidedStartLaw, Measure.prod_prod, measure_univ, mul_one] at this
      rw [this]
      have hm0 : MeasurableSet {ω : PF.Ω | PF.X 0 ω = some v} :=
        PF.measurable_X 0 (measurableSet_singleton _)
      have hc : PF.P v {ω : PF.Ω | PF.X 0 ω = some v}ᶜ = 0 := by
        rw [compl_setOf]
        exact ae_iff.1 (h v).1
      exact (prob_compl_eq_zero_iff hm0).1 hc
    rw [ae_iff]
    have hc : {ω : CadlagPath S | ¬ ω.toFun 0 = code (some v)} =
        {ω : CadlagPath S | ω.toFun 0 = code (some v)}ᶜ := rfl
    rw [hc]
    exact (prob_compl_eq_zero_iff hmeas).2 hone
  refine ⟨fun r => ?_, hstart⟩
  refine measurePreserving_timeShift_of_ratEval_law Q r ?_
  -- identify the two σ-finite laws on `ℚ → S`
  have hF : Measurable fun ω : CadlagPath S => fun q : ℚ => ω.toFun ((q : ℝ) + r) :=
    measurable_pi_iff.2 fun q => measurable_eval ((q : ℝ) + r)
  have hcyl : ∀ (J : Finset ℚ) (s : ℚ → S),
      Q.map (fun ω : CadlagPath S => fun q : ℚ => ω.toFun ((q : ℝ) + r)) (ptCyl J s) =
        Q.map ratEval (ptCyl J s) := by
    intro J s
    rw [Measure.map_apply hF (measurableSet_ptCyl J s),
      Measure.map_apply measurable_ratEval (measurableSet_ptCyl J s)]
    have h1 : (fun ω : CadlagPath S => fun q : ℚ => ω.toFun ((q : ℝ) + r)) ⁻¹' ptCyl J s =
        {ω : CadlagPath S | ∀ q ∈ J, ω.toFun ((fun q : ℚ => (q : ℝ) + r) q) = s q} := rfl
    have h2 : ratEval ⁻¹' ptCyl J s =
        {ω : CadlagPath S | ∀ q ∈ J, ω.toFun ((fun q : ℚ => (q : ℝ)) q) = s q} := rfl
    rw [h1, h2, hQ, weightedPathMixture_pathCyl PF code P hP w,
      weightedPathMixture_pathCyl PF code P hP w,
      twoSidedSpeedLaw_codedCyl_shift h w hrev code hcode J s r]
  haveI : Nonempty S := ⟨code none⟩
  obtain ⟨enum, henum⟩ := exists_surjective_nat S
  refine Measure.ext_of_generateFrom_of_iUnion ptCyls (fun n => ptCyl {0} fun _ => enum n)
    generateFrom_ptCyls.symm isPiSystem_ptCyls ?_ (fun n => ⟨{0}, fun _ => enum n, rfl⟩) ?_ ?_
  · refine eq_univ_of_forall fun ξ => ?_
    obtain ⟨n, hn⟩ := henum (ξ 0)
    exact mem_iUnion.2 ⟨n, fun q hq => by rw [Finset.mem_singleton.1 hq, hn]⟩
  · intro n
    rw [hcyl, Measure.map_apply measurable_ratEval (measurableSet_ptCyl _ _)]
    have h2 : ratEval ⁻¹' ptCyl {0} (fun _ => enum n) =
        {ω : CadlagPath S | ∀ q ∈ ({0} : Finset ℚ), ω.toFun ((fun q : ℚ => (q : ℝ)) q) =
          (fun _ => enum n) q} := rfl
    rw [h2, hQ, weightedPathMixture_pathCyl PF code P hP w]
    exact twoSidedSpeedLaw_codedCyl_singleton_ne_top h w hrev code hcode 0 _ (enum n)
  · rintro _ ⟨J, s, rfl⟩
    exact hcyl J s

end Bridge

/-! ## The area clock -/

/-- **The area instance.**  For the area-speed reflected process, any family of coded laws
with its two-sided finite-dimensional distributions has a real-time shift-invariant
area mixture `∑_v a_v P v`, each `P v` starting at `v` — the fixed-environment input
`IsShiftInvariantMixture` of `sum_mul_lintegral_pathNumerator_eq`, unconditional except for
the coded law itself. -/
theorem isShiftInvariantMixture_cellArea [Countable S] {G : ConductanceGraph V}
    {hmin : G.EnergyMinimizer} {PF : ProcessFamily V} (F : IndexedCells V) (hF : Geometry F)
    (h : IsReflectedWalk G (fun v => G.pi v / StatementIngredients.cellArea F v) hmin PF)
    (hG : G.toSimpleGraph.Connected) (code : Option V → S) (hcode : Function.Injective code)
    (P : V → Measure (CadlagPath S)) (hP : CodedTwoSidedLaw PF code P) :
    IsShiftInvariantMixture (fun v => ENNReal.ofReal (StatementIngredients.cellArea F v)) P
      fun v => code (some v) :=
  isShiftInvariantMixture_of_codedTwoSidedLaw h _
    (fun t x y => ofReal_mul_transition_comm PF _ (cellArea_nonneg F)
      (AreaReversibility.processTransitionReversible_cellArea F hF h hG t) x y)
    code hcode P hP

/-! ## Satisfiability of `CodedTwoSidedLaw` -/

end ReflectedGMS.AreaClockCodingShift
