import Mathlib.Probability.Independence.InfinitePi
import Mathlib.Probability.Independence.ZeroOne
import Mathlib.MeasureTheory.Measure.MeasuredSets
import Mathlib.Dynamics.Ergodic.Function

/-!
# Ergodicity of the two-sided iid cycle shift

The regeneration argument needs the following purely probabilistic input: a
functional of the two-sided sequence of regeneration cycles that is invariant
under the cycle shift is deterministic.  This module proves exactly that, for an
abstract cycle type.

The cycle type `Cyc` carries only a measurable structure and the cycle law `ν`
is only assumed to be a probability measure: no finite alphabet, no moment or
mean assumption, and no countable generation of `Cyc` is used.  The sequence
space is `ℤ → Cyc` with the product σ-algebra and the iid law
`iidCycleLaw ν = Measure.infinitePi (fun _ : ℤ => ν)`, and `cycleShift` is the
two-sided left shift.

The proof is the classical mixing argument, built from existing mathlib pieces:

* coordinates are independent under the product measure
  (`ProbabilityTheory.iIndepFun_infinitePi`), hence two *disjoint* windows of
  coordinates generate independent σ-algebras
  (`ProbabilityTheory.indep_iSup_of_disjoint`);
* shifting a set measurable in the window `[-n, n]` by `m` makes it measurable
  in the window `[m - n, m + n]`, so for `m = 2n + 1` the two windows are
  disjoint and the shifted set is independent of the original one;
* a general measurable set is approximated in measure by a finite-window set,
  using the existing density theorem
  `MeasureTheory.exists_measure_symmDiff_lt_of_generateFrom_isSetRing` for the
  ring of finite-window sets; hence an invariant set `A` satisfies
  `μ A = μ A * μ A` and so has measure `0` or `1`;
* `Ergodic.ae_eq_const_of_ae_eq_comp₀` upgrades this to a.e. constancy of any
  invariant real measurable functional (boundedness is *not* needed, so the
  bounded case of the consumer is a special case).

Nothing here constructs the cycle decomposition of a path: the transfer to the
actual reflected walk still needs a measurable cycle-valued encoding of the
path whose two-sided cycle sequence is iid, and the excursion-reversal step.
-/

set_option autoImplicit false

open MeasureTheory ProbabilityTheory Set

open scoped ENNReal symmDiff

namespace ReflectedGMS.Temporal

variable {Cyc : Type*} [mCyc : MeasurableSpace Cyc]

/-! ### The iid cycle sequence and its shift -/

/-- The law of a two-sided iid sequence of cycles with common cycle law `ν`. -/
noncomputable def iidCycleLaw (ν : Measure Cyc) : Measure (ℤ → Cyc) :=
  Measure.infinitePi fun _ : ℤ => ν

instance isProbabilityMeasure_iidCycleLaw (ν : Measure Cyc) [IsProbabilityMeasure ν] :
    IsProbabilityMeasure (iidCycleLaw ν) := by
  unfold iidCycleLaw
  infer_instance

/-- The two-sided cycle shift: `cycleShift ω` reads the cycle sequence one cycle later. -/
def cycleShift (ω : ℤ → Cyc) : ℤ → Cyc := fun k => ω (k + 1)

theorem measurable_cycleShift : Measurable (cycleShift : (ℤ → Cyc) → ℤ → Cyc) :=
  measurable_pi_iff.2 fun k => measurable_pi_apply (k + 1)

theorem cycleShift_iterate (m : ℕ) (ω : ℤ → Cyc) (k : ℤ) :
    cycleShift^[m] ω k = ω (k + m) := by
  induction m generalizing ω k with
  | zero => simp
  | succ m ih =>
    rw [Function.iterate_succ_apply, ih]
    simp only [cycleShift]
    congr 1
    push_cast
    ring

theorem measurePreserving_cycleShift (ν : Measure Cyc) [IsProbabilityMeasure ν] :
    MeasurePreserving (cycleShift : (ℤ → Cyc) → ℤ → Cyc) (iidCycleLaw ν) (iidCycleLaw ν) := by
  refine ⟨measurable_cycleShift, ?_⟩
  have hcoe : ⇑(MeasurableEquiv.piCongrLeft (fun _ : ℤ => Cyc) (Equiv.subRight (1 : ℤ)))
      = (cycleShift : (ℤ → Cyc) → ℤ → Cyc) := by
    funext ω k
    have h := MeasurableEquiv.piCongrLeft_apply_apply (β := fun _ : ℤ => Cyc)
      (Equiv.subRight (1 : ℤ)) ω (k + 1)
    simpa [cycleShift] using h
  show (Measure.infinitePi fun _ : ℤ => ν).map cycleShift = Measure.infinitePi fun _ : ℤ => ν
  rw [← hcoe]
  exact Measure.infinitePi_map_piCongrLeft (μ := fun _ : ℤ => ν) (Equiv.subRight (1 : ℤ))

theorem preimage_cycleShift_iterate_of_invariant {A : Set (ℤ → Cyc)}
    (hA : cycleShift ⁻¹' A = A) (m : ℕ) : cycleShift^[m] ⁻¹' A = A := by
  induction m with
  | zero => simp
  | succ m ih => rw [Function.iterate_succ, Set.preimage_comp, ih, hA]

/-! ### Coordinate σ-algebras and the ring of finite-window sets -/

/-- The σ-algebra generated by the cycles indexed by `S`. -/
def cycleCoordSigma (S : Set ℤ) : MeasurableSpace (ℤ → Cyc) :=
  ⨆ i ∈ S, mCyc.comap fun ω : ℤ → Cyc => ω i

/-- The σ-algebra generated by the cycles with index in the window `[-n, n]`. -/
def cycleWindowSigma (n : ℕ) : MeasurableSpace (ℤ → Cyc) :=
  cycleCoordSigma (Set.Icc (-(n : ℤ)) (n : ℤ))

theorem cycleCoordSigma_le (S : Set ℤ) :
    cycleCoordSigma (Cyc := Cyc) S ≤ (inferInstance : MeasurableSpace (ℤ → Cyc)) :=
  iSup₂_le fun i _ => measurable_iff_comap_le.1 (measurable_pi_apply i)

theorem cycleCoordSigma_mono {S T : Set ℤ} (h : S ⊆ T) :
    cycleCoordSigma (Cyc := Cyc) S ≤ cycleCoordSigma T :=
  iSup₂_le fun i hi => le_iSup₂_of_le i (h hi) le_rfl

theorem cycleWindowSigma_le (n : ℕ) :
    cycleWindowSigma (Cyc := Cyc) n ≤ (inferInstance : MeasurableSpace (ℤ → Cyc)) :=
  cycleCoordSigma_le _

theorem cycleWindowSigma_mono {n k : ℕ} (h : n ≤ k) :
    cycleWindowSigma (Cyc := Cyc) n ≤ cycleWindowSigma k :=
  cycleCoordSigma_mono (Set.Icc_subset_Icc (by omega) (by omega))

/-- The ring of sets depending on finitely many cycles. -/
def cycleWindowAlgebra : Set (Set (ℤ → Cyc)) :=
  {s | ∃ n : ℕ, MeasurableSet[cycleWindowSigma n] s}

theorem isSetRing_cycleWindowAlgebra : IsSetRing (cycleWindowAlgebra (Cyc := Cyc)) where
  empty_mem := ⟨0, @MeasurableSet.empty _ (cycleWindowSigma 0)⟩
  union_mem := by
    rintro s t ⟨n, hn⟩ ⟨k, hk⟩
    exact ⟨max n k, MeasurableSet.union (cycleWindowSigma_mono (le_max_left n k) _ hn)
      (cycleWindowSigma_mono (le_max_right n k) _ hk)⟩
  sdiff_mem := by
    rintro s t ⟨n, hn⟩ ⟨k, hk⟩
    exact ⟨max n k, MeasurableSet.diff (cycleWindowSigma_mono (le_max_left n k) _ hn)
      (cycleWindowSigma_mono (le_max_right n k) _ hk)⟩

theorem generateFrom_cycleWindowAlgebra :
    MeasurableSpace.generateFrom (cycleWindowAlgebra (Cyc := Cyc)) =
      (inferInstance : MeasurableSpace (ℤ → Cyc)) := by
  have hset : cycleWindowAlgebra (Cyc := Cyc)
      = ⋃ n : ℕ, {s : Set (ℤ → Cyc) | MeasurableSet[cycleWindowSigma n] s} := by
    ext s
    simp only [cycleWindowAlgebra, Set.mem_setOf_eq, Set.mem_iUnion]
  rw [hset, MeasurableSpace.generateFrom_iUnion_measurableSet
    (fun n : ℕ => cycleWindowSigma (Cyc := Cyc) n)]
  refine le_antisymm (iSup_le fun n => cycleWindowSigma_le n) ?_
  have hcoord : ∀ i : ℤ, (mCyc.comap fun ω : ℤ → Cyc => ω i)
      ≤ ⨆ n : ℕ, cycleWindowSigma (Cyc := Cyc) n := by
    intro i
    refine le_iSup_of_le i.natAbs ?_
    refine le_iSup₂_of_le i ?_ le_rfl
    simp only [Set.mem_Icc]
    omega
  exact iSup_le hcoord

/-! ### Independence of disjoint windows, and shifting a window -/

theorem iIndep_cycleCoord (ν : Measure Cyc) [IsProbabilityMeasure ν] :
    iIndep (fun i : ℤ => mCyc.comap fun ω : ℤ → Cyc => ω i) (iidCycleLaw ν) := by
  exact iIndepFun_infinitePi (Ω := fun _ : ℤ => Cyc) (P := fun _ : ℤ => ν)
    (X := fun _ : ℤ => (id : Cyc → Cyc)) fun _ => measurable_id

theorem indep_cycleCoordSigma_of_disjoint (ν : Measure Cyc) [IsProbabilityMeasure ν]
    {S T : Set ℤ} (hST : Disjoint S T) :
    Indep (cycleCoordSigma (Cyc := Cyc) S) (cycleCoordSigma (Cyc := Cyc) T) (iidCycleLaw ν) := by
  exact indep_iSup_of_disjoint
    (fun i => measurable_iff_comap_le.1 (measurable_pi_apply i)) (iIndep_cycleCoord ν) hST

/-- Shifting by `m` moves the window `[-n, n]` to the window `[m - n, m + n]`. -/
theorem comap_cycleShift_iterate_le (n m : ℕ) :
    MeasurableSpace.comap (fun ω : ℤ → Cyc => cycleShift^[m] ω) (cycleWindowSigma (Cyc := Cyc) n)
      ≤ cycleCoordSigma (Set.Icc ((m : ℤ) - n) ((m : ℤ) + n)) := by
  rw [MeasurableSpace.comap_le_iff_le_map]
  refine iSup₂_le fun i hi => ?_
  rw [← MeasurableSpace.comap_le_iff_le_map, MeasurableSpace.comap_comp]
  have hfun : ((fun ω : ℤ → Cyc => ω i) ∘ fun ω : ℤ → Cyc => cycleShift^[m] ω)
      = fun ω : ℤ → Cyc => ω (i + m) := by
    funext ω
    exact cycleShift_iterate m ω i
  rw [hfun]
  refine le_iSup₂_of_le (i + m) ?_ le_rfl
  simp only [Set.mem_Icc] at hi ⊢
  omega

/-! ### Elementary symmetric-difference estimates -/

theorem measureReal_le_add_measureReal_symmDiff {α : Type*} [MeasurableSpace α]
    {μ : Measure α} [IsFiniteMeasure μ] (s t : Set α) :
    μ.real s ≤ μ.real t + μ.real (s ∆ t) := by
  have hsub : s ⊆ t ∪ s ∆ t := by
    intro x hx
    simp only [Set.mem_union, Set.mem_symmDiff]
    tauto
  calc μ.real s ≤ μ.real (t ∪ s ∆ t) := measureReal_mono hsub
    _ ≤ μ.real t + μ.real (s ∆ t) := measureReal_union_le _ _

theorem measureReal_inter_le_add_measureReal_symmDiff {α : Type*} [MeasurableSpace α]
    {μ : Measure α} [IsFiniteMeasure μ] (s₁ s₂ t₁ t₂ : Set α) :
    μ.real (s₁ ∩ s₂) ≤ μ.real (t₁ ∩ t₂) + (μ.real (s₁ ∆ t₁) + μ.real (s₂ ∆ t₂)) := by
  have hsub : s₁ ∩ s₂ ⊆ (t₁ ∩ t₂) ∪ (s₁ ∆ t₁ ∪ s₂ ∆ t₂) := by
    intro x hx
    simp only [Set.mem_union, Set.mem_inter_iff, Set.mem_symmDiff] at hx ⊢
    tauto
  calc μ.real (s₁ ∩ s₂) ≤ μ.real ((t₁ ∩ t₂) ∪ (s₁ ∆ t₁ ∪ s₂ ∆ t₂)) := measureReal_mono hsub
    _ ≤ μ.real (t₁ ∩ t₂) + μ.real (s₁ ∆ t₁ ∪ s₂ ∆ t₂) := measureReal_union_le _ _
    _ ≤ μ.real (t₁ ∩ t₂) + (μ.real (s₁ ∆ t₁) + μ.real (s₂ ∆ t₂)) := by
        gcongr
        exact measureReal_union_le _ _

/-! ### Ergodicity of the cycle shift -/

/-- A shift-invariant measurable set of cycle sequences has probability `0` or `1`. -/
theorem measure_eq_zero_or_one_of_cycleShift_invariant (ν : Measure Cyc) [IsProbabilityMeasure ν]
    {A : Set (ℤ → Cyc)} (hA : MeasurableSet A) (hinvA : cycleShift ⁻¹' A = A) :
    iidCycleLaw ν A = 0 ∨ iidCycleLaw ν A = 1 := by
  set μ : Measure (ℤ → Cyc) := iidCycleLaw ν with hμdef
  have hiter : ∀ m : ℕ, cycleShift^[m] ⁻¹' A = A :=
    preimage_cycleShift_iterate_of_invariant hinvA
  have h0a : (0 : ℝ) ≤ μ.real A := measureReal_nonneg
  have h1a : μ.real A ≤ 1 := by
    have h := ENNReal.toReal_mono (a := μ A) (b := 1) (by simp) prob_le_one
    simpa [measureReal_def] using h
  have key : ∀ δ : ℝ, 0 < δ → |μ.real A - μ.real A * μ.real A| ≤ 4 * δ := by
    intro δ hδ
    obtain ⟨B, hBmem, hBlt⟩ :=
      exists_measure_symmDiff_lt_of_generateFrom_isSetRing (μ := μ)
        isSetRing_cycleWindowAlgebra
        ⟨{Set.univ}, Set.countable_singleton _, by
          rintro s rfl
          exact ⟨0, MeasurableSet.univ⟩, by simp⟩
        generateFrom_cycleWindowAlgebra.symm hA (ENNReal.ofReal_pos.2 hδ)
    obtain ⟨n, hBn⟩ := hBmem
    have hBmeas : MeasurableSet B := cycleWindowSigma_le n _ hBn
    have hABmeas : MeasurableSet (A ∆ B) := (hA.diff hBmeas).union (hBmeas.diff hA)
    set m : ℕ := 2 * n + 1 with hm
    -- the shifted window is disjoint from the original one
    have hdisj : Disjoint (Set.Icc (-(n : ℤ)) (n : ℤ))
        (Set.Icc ((m : ℤ) - n) ((m : ℤ) + n)) := by
      rw [Set.disjoint_left]
      intro x hx hx'
      simp only [Set.mem_Icc] at hx hx'
      omega
    have hshiftB : MeasurableSet[cycleCoordSigma (Set.Icc ((m : ℤ) - n) ((m : ℤ) + n))]
        (cycleShift^[m] ⁻¹' B) := comap_cycleShift_iterate_le n m _ ⟨B, hBn, rfl⟩
    have hindep := indep_cycleCoordSigma_of_disjoint ν hdisj
    have hmul : μ (B ∩ cycleShift^[m] ⁻¹' B) = μ B * μ (cycleShift^[m] ⁻¹' B) :=
      (hindep.indepSet_of_measurableSet hBn hshiftB).measure_inter_eq_mul
    have hmp : MeasurePreserving (cycleShift^[m] : (ℤ → Cyc) → ℤ → Cyc) μ μ :=
      (measurePreserving_cycleShift ν).iterate m
    have hpreB : μ (cycleShift^[m] ⁻¹' B) = μ B :=
      hmp.measure_preimage hBmeas.nullMeasurableSet
    have hrealB : μ.real (B ∩ cycleShift^[m] ⁻¹' B) = μ.real B * μ.real B := by
      simp only [measureReal_def, hmul, hpreB, ENNReal.toReal_mul]
    have hpre_eq : μ (cycleShift^[m] ⁻¹' (A ∆ B)) = μ (A ∆ B) :=
      hmp.measure_preimage hABmeas.nullMeasurableSet
    have hpreSymm : μ.real ((cycleShift^[m] ⁻¹' A) ∆ (cycleShift^[m] ⁻¹' B))
        = μ.real (A ∆ B) := by
      rw [← Set.preimage_symmDiff]
      simp only [measureReal_def, hpre_eq]
    -- the approximation error
    have he : μ.real (A ∆ B) < δ := by
      have h1 : μ (A ∆ B) < ENNReal.ofReal δ := by rwa [symmDiff_comm] at hBlt
      have h2 := (ENNReal.toReal_lt_toReal (measure_ne_top μ _) ENNReal.ofReal_ne_top).2 h1
      rwa [ENNReal.toReal_ofReal hδ.le] at h2
    have h0e : (0 : ℝ) ≤ μ.real (A ∆ B) := measureReal_nonneg
    have h0b : (0 : ℝ) ≤ μ.real B := measureReal_nonneg
    have h1b : μ.real B ≤ 1 := by
      have h := ENNReal.toReal_mono (a := μ B) (b := 1) (by simp) prob_le_one
      simpa [measureReal_def] using h
    have hab1 : μ.real A ≤ μ.real B + μ.real (A ∆ B) :=
      measureReal_le_add_measureReal_symmDiff (μ := μ) A B
    have hab2 : μ.real B ≤ μ.real A + μ.real (A ∆ B) := by
      have h := measureReal_le_add_measureReal_symmDiff (μ := μ) B A
      rwa [symmDiff_comm B A] at h
    have hAA : A ∩ cycleShift^[m] ⁻¹' A = A := by rw [hiter m, Set.inter_self]
    have hmain1 : μ.real A ≤ μ.real B * μ.real B + (μ.real (A ∆ B) + μ.real (A ∆ B)) := by
      have h := measureReal_inter_le_add_measureReal_symmDiff (μ := μ) A (cycleShift^[m] ⁻¹' A) B
        (cycleShift^[m] ⁻¹' B)
      rwa [hAA, hrealB, hpreSymm] at h
    have hmain2 : μ.real B * μ.real B ≤ μ.real A + (μ.real (A ∆ B) + μ.real (A ∆ B)) := by
      have h := measureReal_inter_le_add_measureReal_symmDiff (μ := μ) B (cycleShift^[m] ⁻¹' B) A
        (cycleShift^[m] ⁻¹' A)
      rwa [hAA, hrealB, symmDiff_comm B A,
        symmDiff_comm (cycleShift^[m] ⁻¹' B) (cycleShift^[m] ⁻¹' A), hpreSymm] at h
    have hae : μ.real A * μ.real (A ∆ B) ≤ μ.real (A ∆ B) := by nlinarith
    have hbe : μ.real B * μ.real (A ∆ B) ≤ μ.real (A ∆ B) := by nlinarith
    have hsq1 : μ.real B * μ.real B ≤ μ.real A * μ.real A + 2 * μ.real (A ∆ B) := by
      nlinarith [mul_le_mul_of_nonneg_right hab2 h0b, mul_le_mul_of_nonneg_left hab2 h0a]
    have hsq2 : μ.real A * μ.real A ≤ μ.real B * μ.real B + 2 * μ.real (A ∆ B) := by
      nlinarith [mul_le_mul_of_nonneg_right hab1 h0a, mul_le_mul_of_nonneg_left hab1 h0b]
    rw [abs_le]
    constructor <;> linarith
  have hfix : μ.real A = μ.real A * μ.real A := by
    by_contra hne
    have hpos : 0 < |μ.real A - μ.real A * μ.real A| := abs_pos.2 (sub_ne_zero.2 hne)
    have h := key (|μ.real A - μ.real A * μ.real A| / 8) (by positivity)
    linarith
  have hprod : μ.real A * (1 - μ.real A) = 0 := by nlinarith
  rcases mul_eq_zero.1 hprod with h | h
  · left
    exact (measureReal_eq_zero_iff (measure_ne_top μ A)).1 h
  · right
    have h1 : μ.real A = 1 := by linarith
    rwa [measureReal_def, ENNReal.toReal_eq_one_iff] at h1

theorem preErgodic_cycleShift (ν : Measure Cyc) [IsProbabilityMeasure ν] :
    PreErgodic (cycleShift : (ℤ → Cyc) → ℤ → Cyc) (iidCycleLaw ν) := by
  refine ⟨fun A hA hinvA => ?_⟩
  rw [Filter.eventuallyEmptyOrUniv_iff']
  rcases measure_eq_zero_or_one_of_cycleShift_invariant ν hA hinvA with h | h
  · exact Or.inl (ae_eq_empty.2 h)
  · refine Or.inr (ae_eq_univ.2 ?_)
    rw [measure_compl hA (measure_ne_top _ A), measure_univ, h, tsub_self]

/-- **Ergodicity of the two-sided iid cycle shift.**  No mean, moment, finite-alphabet or
countable-generation assumption is used: the cycle type only carries a measurable structure
and the cycle law is only assumed to be a probability measure. -/
theorem ergodic_cycleShift (ν : Measure Cyc) [IsProbabilityMeasure ν] :
    Ergodic (cycleShift : (ℤ → Cyc) → ℤ → Cyc) (iidCycleLaw ν) :=
  ⟨measurePreserving_cycleShift ν, preErgodic_cycleShift ν⟩

/-- **The regeneration-invariance input.**  A measurable functional of the two-sided iid cycle
sequence that is invariant under the cycle shift is almost surely constant.  Bounded invariant
functionals are the special case used by the regeneration lemma. -/
theorem ae_eq_const_of_cycleShift_invariant (ν : Measure Cyc) [IsProbabilityMeasure ν]
    {f : (ℤ → Cyc) → ℝ} (hf : Measurable f) (hinv : ∀ ω, f (cycleShift ω) = f ω) :
    ∃ c : ℝ, f =ᵐ[iidCycleLaw ν] fun _ => c := by
  obtain ⟨c, hc⟩ := (ergodic_cycleShift ν).ae_eq_const_of_ae_eq_comp₀ hf.nullMeasurable
    (by filter_upwards with ω; exact hinv ω)
  exact ⟨c, hc⟩

end ReflectedGMS.Temporal
