import ReflectedGMS.Temporal.FlowCodingLine
import ReflectedGMS.Temporal.TwoSidedCycleSpliceKernel
import ReflectedGMS.Temporal.RegenerationKernelMeasurability

/-!
# The bridge kernel `κF : Kernel Env FlowCoding` of the regeneration lane

The regeneration kernel lives on the raw two-sided label coding
(`RegenerationKernelMeasurability.regenerationKernel`, fibre `TwoSidedRegenerationCoding.rootedLaw`)
and on its regularity subtype (`TwoSidedCycleSpliceKernel.rootedRegKernel`); the exact re-rooting
flow lives on the càdlàg carrier `FlowCoding = CadlagPath ℕ∞ × CadlagPath Plane`
(`TwoSidedRegenerationFlow`).  This module builds the kernel on the carrier.

## Construction (lift through the sample space, NOT `liftSubtype`)

At a live environment (`e ∈ G`, root slot present) the fibre is the image of the product of two
independent area walks from the root cell (`(areaFamily e).P r`, the forward half and the backward
half of tex:1345) under a measurable map `build`:
* on a `toMeasurable` conull set `goodSet` of sample pairs (both halves right-regular with left
  limits, both representative paths extend càdlàg, every rational time is a vertex time at which
  the walk is locally constant, both start at the root) the label path is
  `glue (forward labels) (backward labels)` and the position path is
  `glue (forward extension) (backward extension)` (`FlowCodingLine.glue`: the backward half is read
  through LEFT limits, so both are càdlàg on `ℝ`);
* off it, the cemetery configuration `cemFlow`.
The kernel's measurability in the environment is inherited from the raw regeneration kernel
through the rational-time code (`liftKernelRat`): a law on the carrier is determined by its
rational-time values (`FlowCoding`'s σ-algebra is `comap ratRead`), and the rational-time image of
the fibre is the image of `regenerationKernel` under the jointly measurable `ratCode`
(`map_ratRead_flowKernel`).  No outer-measure hypothesis of `liftSubtype` type is used.

## Requirements B1–B7 of `outputs/regeneration-flow-handoff.2026-09-18.md` §4

* (B1) `map_ratRead_flowKernel`, `map_ratRead_flowKernel_eq_rootedRegKernel`: the rational-time
  image of `κF e` IS the image of the regeneration kernel, resp. of `rootedRegKernel`, under
  `ratCode` (values at rational times, positions read from the representative field).
* (B2)/(B7) `build_label_of_nonneg`: on `goodSet` the forward half is untouched on `[0,∞)`.
* (B3) `build_mem_coupled`: on `goodSet` the configuration is in `Coupled z` — its position path
  reads the representative field at every rational vertex time; the probabilistic input is the
  hypothesis `hext` (produced from MTP + FE by
  `FlowCodingPositionExtension.ae_exists_cadlag_extension_areaFamily`).
* (B4) `build_label_zero`, `build_pos_zero`: rooted at the root cell, `P 0 = z e (root)`.
* (B6) built in: the carrier is càdlàg by construction.
* (B5) (pointwise equivariance of a coding map) is NOT provided: `build` is defined per
  environment on the sample space.  The density clauses that B5 was meant for are discharged
  pointwise by `Limit/FlowCodingDensity` instead; the transport needs the law-level covariance,
  which stays inside `hsys`.
* Gate independence (`compProd_flowKernel_congr`): the annealed law `ν ⊗ₘ κF` does not depend on
  which conull admissible gate is used, so the similarity-closed gate can be substituted without
  changing any binder stated at `ν ⊗ₘ κF`.

Nothing here certifies `p:prop:pathsextend`, `hsys`, `hregen` or either main theorem.
-/

set_option autoImplicit false

open MeasureTheory ProbabilityTheory Filter Set Topology
open scoped NNReal ENNReal

namespace ReflectedGMS.FlowCodingKernel

open Code EnvironmentFields EnvironmentLaws AreaClocks RootDensities
open ReflectedWalk ReflectedWalk.Theorem16
open ReflectedGMS.TrajectoryCoding ReflectedGMS.TwoSidedRegenerationFlow
open ReflectedGMS.TwoSidedRegenerationCoding ReflectedGMS.RegenerationKernel
open ReflectedGMS.EnvironmentWalkDataProducer ReflectedGMS.FlowCodingLine
open ReflectedGMS.TwoSidedCycleSplice

/-! ### 1. Rational-time code and the comap lift -/

/-- The rational-time values of a configuration of the carrier. -/
abbrev RatCode : Type := (ℚ → ℕ∞) × (ℚ → Plane)

/-- Reading a configuration at rational times. -/
def ratRead : FlowCoding → RatCode := Prod.map CadlagPath.ratEval CadlagPath.ratEval

theorem measurable_ratRead : Measurable ratRead :=
  (CadlagPath.measurable_ratEval.comp measurable_fst).prodMk
    (CadlagPath.measurable_ratEval.comp measurable_snd)

/-- **The σ-algebra of the carrier is generated by the rational-time values.** -/
theorem measurableSpace_flowCoding_eq :
    (inferInstance : MeasurableSpace FlowCoding) =
      MeasurableSpace.comap ratRead (inferInstance : MeasurableSpace RatCode) :=
  (MeasurableSpace.comap_prodMap CadlagPath.ratEval CadlagPath.ratEval).symm

theorem exists_ratRead_preimage {s : Set FlowCoding} (hs : MeasurableSet s) :
    ∃ B : Set RatCode, MeasurableSet B ∧ ratRead ⁻¹' B = s := by
  have hs' : MeasurableSet[MeasurableSpace.comap ratRead
      (inferInstance : MeasurableSpace RatCode)] s := by
    rw [← measurableSpace_flowCoding_eq]
    exact hs
  exact MeasurableSpace.measurableSet_comap.1 hs'

/-- **Lift of a rational-code kernel to the carrier**: a family of laws on the carrier whose
rational-time images form a kernel is a kernel. -/
noncomputable def liftKernelRat {α : Type*} [MeasurableSpace α] (κR : Kernel α RatCode)
    (μ : α → Measure FlowCoding) (h : ∀ a, (μ a).map ratRead = κR a) :
    Kernel α FlowCoding where
  toFun := μ
  measurable' := by
    refine Measure.measurable_of_measurable_coe _ fun s hs => ?_
    obtain ⟨B, hB, rfl⟩ := exists_ratRead_preimage hs
    have heq : (fun a => μ a (ratRead ⁻¹' B)) = fun a => κR a B := by
      funext a
      rw [← Measure.map_apply measurable_ratRead hB, h a]
    rw [heq]
    exact κR.measurable_coe hB

/-! ### 2. The rational code of the raw two-sided coding -/

/-- The label of the raw two-sided coding at a rational time: the forward half at `q ≥ 0`, the
backward half at `-q` for `q < 0` (VALUES; at fixed times they agree with the left limits a.s.). -/
noncomputable def rawLabel (x : TwoSidedCoding) (q : ℚ) : ℕ∞ :=
  if 0 ≤ q then toENatLabel (x.1 (q : ℝ).toNNReal) else toENatLabel (x.2 (-(q : ℝ)).toNNReal)

/-- The representative field read at a label of `ℕ∞` (`0` at the cemetery; `CellField` is already
`0` at absent labels). -/
noncomputable def repAt (z : CellField) (e : Env) (y : ℕ∞) : Plane :=
  ENat.recTopCoe 0 (fun n => z.value e n) y

@[simp] theorem repAt_top (z : CellField) (e : Env) : repAt z e ⊤ = 0 := ENat.recTopCoe_top _ _

@[simp] theorem repAt_natCast (z : CellField) (e : Env) (n : ℕ) :
    repAt z e (n : ℕ∞) = z.value e n := ENat.recTopCoe_natCast _ _ n

/-- **The rational code** of an environment and a raw two-sided coding. -/
noncomputable def ratCode (z : CellField) (p : Env × TwoSidedCoding) : RatCode :=
  (fun q => rawLabel p.2 q, fun q => repAt z p.1 (rawLabel p.2 q))

theorem measurable_toENatLabel : Measurable toENatLabel := measurable_of_countable _

theorem measurable_rawLabel (q : ℚ) : Measurable fun x : TwoSidedCoding => rawLabel x q := by
  by_cases hq : 0 ≤ q
  · have h : (fun x : TwoSidedCoding => rawLabel x q) =
        fun x => toENatLabel (x.1 (q : ℝ).toNNReal) := funext fun x => if_pos hq
    rw [h]
    exact measurable_toENatLabel.comp ((measurable_pi_apply _).comp measurable_fst)
  · have h : (fun x : TwoSidedCoding => rawLabel x q) =
        fun x => toENatLabel (x.2 (-(q : ℝ)).toNNReal) := funext fun x => if_neg hq
    rw [h]
    exact measurable_toENatLabel.comp ((measurable_pi_apply _).comp measurable_snd)

theorem measurable_repAt (z : CellField) :
    Measurable fun p : Env × ℕ∞ => repAt z p.1 p.2 := by
  refine measurable_from_prod_countable_left fun y => ?_
  induction y using ENat.recTopCoe with
  | top =>
    show Measurable fun e : Env => repAt z e ⊤
    simp only [repAt_top]
    exact measurable_const
  | coe n =>
    show Measurable fun e : Env => repAt z e (n : ℕ∞)
    simp only [repAt_natCast]
    exact z.measurable_label n

theorem measurable_ratCode (z : CellField) : Measurable (ratCode z) := by
  show Measurable fun p : Env × TwoSidedCoding =>
    ((fun q => rawLabel p.2 q), (fun q => repAt z p.1 (rawLabel p.2 q)))
  refine Measurable.prodMk (measurable_pi_iff.2 fun q => ?_) (measurable_pi_iff.2 fun q => ?_)
  · exact (measurable_rawLabel q).comp measurable_snd
  · have h : Measurable ((fun p : Env × ℕ∞ => repAt z p.1 p.2) ∘
        fun p : Env × TwoSidedCoding => (p.1, rawLabel p.2 q)) :=
      (measurable_repAt z).comp (measurable_fst.prodMk ((measurable_rawLabel q).comp measurable_snd))
    exact h

/-- **The rational-code kernel**: the regeneration kernel read at rational times. -/
noncomputable def ratKernel (z : CellField) (G : Set Env) (hG : MeasurableSet G)
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) : Kernel Env RatCode :=
  Kernel.map (Kernel.id ×ₖ RegenerationKernelMeasurability.regenerationKernel G hG hwalk)
    (ratCode z)

theorem ratKernel_apply (z : CellField) (G : Set Env) (hG : MeasurableSet G)
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) (e : Env) :
    ratKernel z G hG hwalk e = (rootedLaw G e).map fun x => ratCode z (e, x) := by
  rw [ratKernel, Kernel.map_apply _ (measurable_ratCode z), Kernel.prod_apply, Kernel.id_apply,
    RegenerationKernelMeasurability.regenerationKernel_apply, Measure.dirac_prod,
    Measure.map_map (measurable_ratCode z) measurable_prodMk_left]
  rfl

/-! ### 3. The sample-level construction at one environment -/

section Sample

variable (z : CellField) (e : Env) (r : Vertex e.val)

/-- The `ℕ∞`-label path of a sample of the area walk. -/
noncomputable def labelPath (ω : (areaFamily e).Ω) (t : ℝ≥0) : ℕ∞ :=
  toENatLabel (labelTraj ((areaFamily e).trajectory ω) t)

/-- The epsilon-choice of a càdlàg path through the representative field at vertex times. -/
noncomputable def extPath (ω : (areaFamily e).Ω) : ℝ≥0 → Plane :=
  Classical.epsilon fun Z : ℝ≥0 → Plane =>
    IsCadlag Z ∧ ∀ t v, (areaFamily e).X t ω = some v → Z t = z.at e v

/-- **One good half**: regular with left limits, representative path extends càdlàg, locally
constant at a vertex at every rational time, started at the root. -/
structure HalfGood (ω : (areaFamily e).Ω) : Prop where
  reg : IsRegLL (labelTraj ((areaFamily e).trajectory ω))
  ext : ∃ Z : ℝ≥0 → Plane, IsCadlag Z ∧ ∀ t v, (areaFamily e).X t ω = some v → Z t = z.at e v
  fixed : ∀ q : ℚ, (∃ v, (areaFamily e).X (q : ℝ).toNNReal ω = some v) ∧
    ∃ ε : ℝ, 0 < ε ∧ ∀ s ∈ Metric.ball ((q : ℝ).toNNReal) ε,
      (areaFamily e).X s ω = (areaFamily e).X (q : ℝ).toNNReal ω
  start : (areaFamily e).X 0 ω = some r

/-- The good set of sample pairs (conull under the product law, `ae_mem_goodSet`). -/
noncomputable def goodSet : Set ((areaFamily e).Ω × (areaFamily e).Ω) :=
  (toMeasurable (((areaFamily e).P r).prod ((areaFamily e).P r))
    {ω | ¬ (HalfGood z e r ω.1 ∧ HalfGood z e r ω.2)})ᶜ

theorem measurableSet_goodSet : MeasurableSet (goodSet z e r) :=
  (measurableSet_toMeasurable _ _).compl

theorem halfGood_of_mem_goodSet {ω : (areaFamily e).Ω × (areaFamily e).Ω}
    (h : ω ∈ goodSet z e r) : HalfGood z e r ω.1 ∧ HalfGood z e r ω.2 := by
  by_contra hn
  exact h (subset_toMeasurable _ _ hn)

variable {z e r}

theorem extPath_spec {ω : (areaFamily e).Ω} (h : HalfGood z e r ω) :
    IsCadlag (extPath z e ω) ∧ ∀ t v, (areaFamily e).X t ω = some v → extPath z e ω t = z.at e v :=
  Classical.epsilon_spec h.ext

theorem isCadlag_labelPath {ω : (areaFamily e).Ω} (h : HalfGood z e r ω) :
    IsCadlag (labelPath e ω) :=
  isCadlag_label h.reg

variable (z e r)

/-- The cemetery configuration of the carrier. -/
def cemFlow : FlowCoding :=
  (⟨fun _ => ⊤, IsCadlag.const⟩, ⟨fun _ => 0, IsCadlag.const⟩)

/-- The configuration built from a good pair of samples. -/
noncomputable def goodPath (ω : (areaFamily e).Ω × (areaFamily e).Ω)
    (h : HalfGood z e r ω.1 ∧ HalfGood z e r ω.2) : FlowCoding :=
  (⟨glue (fun s : ℝ => labelPath e ω.1 s.toNNReal) (fun s : ℝ => labelPath e ω.2 s.toNNReal),
      isCadlag_glue (isCadlag_comp_toNNReal (isCadlag_labelPath h.1))
        (isCadlag_comp_toNNReal (isCadlag_labelPath h.2))⟩,
    ⟨glue (fun s : ℝ => extPath z e ω.1 s.toNNReal) (fun s : ℝ => extPath z e ω.2 s.toNNReal),
      isCadlag_glue (isCadlag_comp_toNNReal (extPath_spec h.1).1)
        (isCadlag_comp_toNNReal (extPath_spec h.2).1)⟩)

open Classical in
/-- **The sample-to-carrier map**: the glued configuration on the good set, the cemetery
configuration off it. -/
noncomputable def build (ω : (areaFamily e).Ω × (areaFamily e).Ω) : FlowCoding :=
  if h : ω ∈ goodSet z e r then goodPath z e r ω (halfGood_of_mem_goodSet z e r h) else cemFlow

theorem build_of_mem {ω : (areaFamily e).Ω × (areaFamily e).Ω} (h : ω ∈ goodSet z e r) :
    build z e r ω = goodPath z e r ω (halfGood_of_mem_goodSet z e r h) := by
  classical
  unfold build
  rw [dif_pos h]

theorem build_of_not_mem {ω : (areaFamily e).Ω × (areaFamily e).Ω} (h : ω ∉ goodSet z e r) :
    build z e r ω = cemFlow := by
  classical
  unfold build
  rw [dif_neg h]

variable {z e r}

/-- A good half is locally constant at every positive rational time, so its label path is. -/
theorem labelPath_eventually_const {ω : (areaFamily e).Ω} (h : HalfGood z e r ω) (q : ℚ) :
    ∀ᶠ x in 𝓝[<] ((q : ℝ)), labelPath e ω x.toNNReal = labelPath e ω (q : ℝ).toNNReal ∧
      extPath z e ω x.toNNReal = extPath z e ω (q : ℝ).toNNReal := by
  obtain ⟨⟨v, hv⟩, ε, hε, hball⟩ := h.fixed q
  have hcont : ContinuousAt Real.toNNReal (q : ℝ) := continuous_real_toNNReal.continuousAt
  have hmem : Real.toNNReal ⁻¹' Metric.ball ((q : ℝ).toNNReal) ε ∈ 𝓝 (q : ℝ) :=
    hcont (Metric.ball_mem_nhds _ hε)
  filter_upwards [nhdsWithin_le_nhds hmem] with x hx
  have hX : (areaFamily e).X x.toNNReal ω = (areaFamily e).X (q : ℝ).toNNReal ω := hball _ hx
  refine ⟨?_, ?_⟩
  · show toENatLabel (((areaFamily e).X x.toNNReal ω).map Subtype.val) =
      toENatLabel (((areaFamily e).X (q : ℝ).toNNReal ω).map Subtype.val)
    rw [hX]
  · rw [(extPath_spec h).2 _ v (hX.trans hv), (extPath_spec h).2 _ v hv]

/-- **The rational-time reading of a built configuration is the rational code of the raw
label trajectories** (labels: `rawLabel`; positions: the representative field). -/
theorem ratRead_build_of_mem {ω : (areaFamily e).Ω × (areaFamily e).Ω}
    (h : ω ∈ goodSet z e r) :
    ratRead (build z e r ω) = ratCode z (e, (labelTraj ((areaFamily e).trajectory ω.1),
      labelTraj ((areaFamily e).trajectory ω.2))) := by
  have hg := halfGood_of_mem_goodSet z e r h
  rw [build_of_mem z e r h]
  refine Prod.ext (funext fun q => ?_) (funext fun q => ?_)
  · show glue (fun s : ℝ => labelPath e ω.1 s.toNNReal) (fun s : ℝ => labelPath e ω.2 s.toNNReal)
      (q : ℝ) = rawLabel _ q
    by_cases hq : 0 ≤ q
    · rw [glue_of_nonneg _ _ (by exact_mod_cast hq)]
      unfold rawLabel
      rw [if_pos hq]
      rfl
    · have hq' : (q : ℝ) < 0 := by exact_mod_cast not_le.1 hq
      rw [glue_of_neg _ _ hq']
      unfold rawLabel
      rw [if_neg hq]
      have h1 := labelPath_eventually_const hg.2 (-q)
      rw [Rat.cast_neg] at h1
      exact leftLim_eq_of_eventuallyEq_const (h1.mono fun x hx => hx.1)
  · show glue (fun s : ℝ => extPath z e ω.1 s.toNNReal) (fun s : ℝ => extPath z e ω.2 s.toNNReal)
      (q : ℝ) = repAt z e (rawLabel _ q)
    by_cases hq : 0 ≤ q
    · rw [glue_of_nonneg _ _ (by exact_mod_cast hq)]
      obtain ⟨⟨v, hv⟩, -⟩ := hg.1.fixed q
      rw [(extPath_spec hg.1).2 _ v hv]
      unfold rawLabel
      rw [if_pos hq]
      show z.at e v = repAt z e (toENatLabel (((areaFamily e).X (q : ℝ).toNNReal ω.1).map
        Subtype.val))
      rw [hv]
      simp [CellField.at]
    · have hq' : (q : ℝ) < 0 := by exact_mod_cast not_le.1 hq
      rw [glue_of_neg _ _ hq']
      unfold rawLabel
      rw [if_neg hq]
      have h1 := labelPath_eventually_const hg.2 (-q)
      rw [Rat.cast_neg] at h1
      rw [leftLim_eq_of_eventuallyEq_const (h1.mono fun x hx => hx.2)]
      obtain ⟨⟨v, hv⟩, -⟩ := hg.2.fixed (-q)
      rw [Rat.cast_neg] at hv
      rw [(extPath_spec hg.2).2 _ v hv]
      show z.at e v = repAt z e (toENatLabel (((areaFamily e).X (-(q : ℝ)).toNNReal ω.2).map
        Subtype.val))
      rw [hv]
      simp [CellField.at]

theorem measurable_labelTraj_trajectory :
    Measurable fun ω : (areaFamily e).Ω => labelTraj ((areaFamily e).trajectory ω) :=
  measurable_labelTraj.comp (areaFamily e).measurable_trajectory

variable (z e r)

/-- **`build` is measurable**: its rational-time values are, by `ratRead_build_of_mem`. -/
theorem measurable_build : Measurable (build z e r) := by
  have hpair : Measurable fun ω : (areaFamily e).Ω × (areaFamily e).Ω =>
      ((labelTraj ((areaFamily e).trajectory ω.1),
        labelTraj ((areaFamily e).trajectory ω.2)) : TwoSidedCoding) :=
    (measurable_labelTraj_trajectory.comp measurable_fst).prodMk
      (measurable_labelTraj_trajectory.comp measurable_snd)
  have hcode : Measurable fun ω : (areaFamily e).Ω × (areaFamily e).Ω =>
      ratCode z (e, (labelTraj ((areaFamily e).trajectory ω.1),
        labelTraj ((areaFamily e).trajectory ω.2))) :=
    (measurable_ratCode z).comp (measurable_const.prodMk hpair)
  have hR : Measurable fun ω => ratRead (build z e r ω) := by
    classical
    have heq : (fun ω => ratRead (build z e r ω)) = fun ω => if ω ∈ goodSet z e r then
        ratCode z (e, (labelTraj ((areaFamily e).trajectory ω.1),
          labelTraj ((areaFamily e).trajectory ω.2))) else ratRead cemFlow := by
      funext ω
      by_cases h : ω ∈ goodSet z e r
      · rw [if_pos h, ratRead_build_of_mem h]
      · rw [if_neg h, build_of_not_mem z e r h]
    rw [heq]
    exact Measurable.ite (measurableSet_goodSet z e r) hcode measurable_const
  -- a map into the carrier is measurable iff its rational-time reading is
  intro s hs
  obtain ⟨B, hB, rfl⟩ := exists_ratRead_preimage hs
  exact hR hB

end Sample

/-! ### 4. The kernel -/

/-- The live environments: on the gate, with the root slot present. -/
def Live (G : Set Env) (e : Env) : Prop := e ∈ G ∧ (e.val.1 (rootLabel e)).isSome

/-- The root vertex at a live environment. -/
noncomputable def rootVertex {G : Set Env} {e : Env} (h : Live G e) : Vertex e.val := ⟨rootLabel e, h.2⟩

open Classical in
/-- **The fibre of the bridge kernel.** -/
noncomputable def flowFibre (z : CellField) (G : Set Env) (e : Env) : Measure FlowCoding :=
  if h : Live G e then
    (((areaFamily e).P (rootVertex h)).prod ((areaFamily e).P (rootVertex h))).map
      (build z e (rootVertex h))
  else Measure.dirac cemFlow

theorem flowFibre_of_live {z : CellField} {G : Set Env} {e : Env} (h : Live G e) :
    flowFibre z G e = (((areaFamily e).P (rootVertex h)).prod
      ((areaFamily e).P (rootVertex h))).map (build z e (rootVertex h)) := by
  classical
  unfold flowFibre
  rw [dif_pos h]

theorem flowFibre_of_not_live {z : CellField} {G : Set Env} {e : Env} (h : ¬ Live G e) :
    flowFibre z G e = Measure.dirac cemFlow := by
  classical
  unfold flowFibre
  rw [dif_neg h]

/-- **The extension input (B3)**: at every live environment, the representative path of the area
walk from the root cell extends càdlàg almost surely. -/
def ExtensionGate (z : CellField) (G : Set Env) : Prop :=
  ∀ e (h : Live G e), ∀ᵐ ω ∂(areaFamily e).P (rootVertex h), ∃ Z : ℝ≥0 → Plane, IsCadlag Z ∧
    ∀ t v, (areaFamily e).X t ω = some v → Z t = z.at e v

/-- **The good set is conull** at a live admissible environment. -/
theorem ae_mem_goodSet {z : CellField} {G : Set Env}
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) (hext : ExtensionGate z G) {e : Env}
    (h : Live G e) :
    ∀ᵐ ω ∂(((areaFamily e).P (rootVertex h)).prod ((areaFamily e).P (rootVertex h))),
      ω ∈ goodSet z e (rootVertex h) := by
  set P := (areaFamily e).P (rootVertex h) with hPdef
  have hw := isReflectedWalk_areaFamily e (hwalk e h.1)
  have hhalf : ∀ᵐ ω ∂P, HalfGood z e (rootVertex h) ω := by
    have hfix : ∀ᵐ ω ∂P, ∀ q : ℚ, (∃ v, (areaFamily e).X (q : ℝ).toNNReal ω = some v) ∧
        ∃ ε : ℝ, 0 < ε ∧ ∀ s ∈ Metric.ball ((q : ℝ).toNNReal) ε,
          (areaFamily e).X s ω = (areaFamily e).X (q : ℝ).toNNReal ω :=
      ae_all_iff.2 fun q => (hw (rootVertex h)).2.1 ((q : ℝ).toNNReal)
    filter_upwards [TwoSidedCycleSplice.ae_isRegLL_label e (hwalk e h.1) (rootVertex h),
      hext e h, hfix, (hw (rootVertex h)).1] with ω h1 h2 h3 h4
    exact ⟨h1, h2, h3, h4⟩
  have hpair : ∀ᵐ ω ∂(P.prod P), HalfGood z e (rootVertex h) ω.1 ∧
      HalfGood z e (rootVertex h) ω.2 := by
    filter_upwards [Measure.quasiMeasurePreserving_fst.ae hhalf,
      Measure.quasiMeasurePreserving_snd.ae hhalf] with ω h1 h2
    exact ⟨h1, h2⟩
  have hnull : (P.prod P) (toMeasurable (P.prod P)
      {ω | ¬ (HalfGood z e (rootVertex h) ω.1 ∧ HalfGood z e (rootVertex h) ω.2)}) = 0 := by
    rw [measure_toMeasurable]
    exact ae_iff.1 hpair
  rw [ae_iff]
  have hc : {ω | ¬ ω ∈ goodSet z e (rootVertex h)} = toMeasurable (P.prod P)
      {ω | ¬ (HalfGood z e (rootVertex h) ω.1 ∧ HalfGood z e (rootVertex h) ω.2)} := by
    ext ω
    simp [goodSet, hPdef]
  rw [hc]
  exact hnull

/-- **(B1) The fibre's rational-time image is the regeneration kernel's rational code.** -/
theorem map_ratRead_flowFibre {z : CellField} {G : Set Env} (hG : MeasurableSet G)
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) (hext : ExtensionGate z G) (e : Env) :
    (flowFibre z G e).map ratRead = ratKernel z G hG hwalk e := by
  rw [ratKernel_apply]
  by_cases h : Live G e
  · rw [flowFibre_of_live h, Measure.map_map measurable_ratRead (measurable_build z e _)]
    set P := (areaFamily e).P (rootVertex h) with hPdef
    have hlaw : rootedLaw G e = (P.prod P).map fun ω =>
        ((labelTraj ((areaFamily e).trajectory ω.1),
          labelTraj ((areaFamily e).trajectory ω.2)) : TwoSidedCoding) := by
      have hsl : slotLaw G (rootLabel e) e = P.map fun ω =>
          labelTraj ((areaFamily e).trajectory ω) := by
        rw [slotLaw_of_mem h.1 h.2, ProcessFamily.law,
          Measure.map_map measurable_labelTraj (areaFamily e).measurable_trajectory]
        rfl
      show (slotLaw G (rootLabel e) e).prod (slotLaw G (rootLabel e) e) = _
      rw [hsl, Measure.map_prod_map _ _ measurable_labelTraj_trajectory
        measurable_labelTraj_trajectory]
      rfl
    have hpm : Measurable fun ω : (areaFamily e).Ω × (areaFamily e).Ω =>
        ((labelTraj ((areaFamily e).trajectory ω.1),
          labelTraj ((areaFamily e).trajectory ω.2)) : TwoSidedCoding) :=
      (measurable_labelTraj_trajectory.comp measurable_fst).prodMk
        (measurable_labelTraj_trajectory.comp measurable_snd)
    have hm : Measurable fun x : TwoSidedCoding => ratCode z (e, x) :=
      (measurable_ratCode z).comp measurable_prodMk_left
    rw [hlaw, Measure.map_map hm hpm]
    refine Measure.map_congr ?_
    filter_upwards [ae_mem_goodSet hwalk hext h] with ω hω
    exact ratRead_build_of_mem hω
  · rw [flowFibre_of_not_live h, Measure.map_dirac' measurable_ratRead]
    have hlaw : rootedLaw G e = Measure.dirac ((cemetery, cemetery) : TwoSidedCoding) := by
      show (slotLaw G (rootLabel e) e).prod (slotLaw G (rootLabel e) e) = _
      rw [slotLaw_of_not h, Measure.dirac_prod_dirac]
    have hm : Measurable fun x : TwoSidedCoding => ratCode z (e, x) :=
      (measurable_ratCode z).comp measurable_prodMk_left
    rw [hlaw, Measure.map_dirac' hm]
    congr 1
    refine Prod.ext (funext fun q => ?_) (funext fun q => ?_)
    · show (⊤ : ℕ∞) = rawLabel (cemetery, cemetery) q
      unfold rawLabel
      split_ifs <;> rfl
    · show (0 : Plane) = repAt z e (rawLabel (cemetery, cemetery) q)
      have hq : rawLabel (cemetery, cemetery) q = ⊤ := by
        unfold rawLabel
        split_ifs <;> rfl
      rw [hq, repAt_top]

/-- **The bridge kernel `κF`** from the regeneration kernel to the càdlàg carrier. -/
noncomputable def flowKernel (z : CellField) (G : Set Env) (hG : MeasurableSet G)
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) (hext : ExtensionGate z G) :
    Kernel Env FlowCoding :=
  liftKernelRat (ratKernel z G hG hwalk) (flowFibre z G) (map_ratRead_flowFibre hG hwalk hext)

theorem flowKernel_apply (z : CellField) (G : Set Env) (hG : MeasurableSet G)
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) (hext : ExtensionGate z G) (e : Env) :
    flowKernel z G hG hwalk hext e = flowFibre z G e := rfl

instance flowKernel_isMarkovKernel (z : CellField) (G : Set Env) (hG : MeasurableSet G)
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) (hext : ExtensionGate z G) :
    IsMarkovKernel (flowKernel z G hG hwalk hext) := by
  refine ⟨fun e => ?_⟩
  rw [flowKernel_apply]
  by_cases h : Live G e
  · rw [flowFibre_of_live h]
    infer_instance
  · rw [flowFibre_of_not_live h]
    infer_instance

/-- **(B1) at the kernel**: `κF`'s rational-time image is the raw regeneration kernel's. -/
theorem map_ratRead_flowKernel (z : CellField) (G : Set Env) (hG : MeasurableSet G)
    (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e) (hext : ExtensionGate z G) (e : Env) :
    (flowKernel z G hG hwalk hext e).map ratRead =
      (RegenerationKernelMeasurability.regenerationKernel G hG hwalk e).map
        fun x => ratCode z (e, x) := by
  rw [flowKernel_apply, map_ratRead_flowFibre hG hwalk hext, ratKernel_apply]
  rfl

/-- **(B1) on the regular carrier**: `κF`'s rational-time image is the image of the regularity
kernel `rootedRegKernel` (the carrier of the cycle splice) under the rational code. -/
theorem map_ratRead_flowKernel_eq_rootedRegKernel (z : CellField) (G : Set Env)
    (hG : MeasurableSet G) (hwalk : ∀ e ∈ G, EnvironmentAreaClockAdmissible e)
    (hext : ExtensionGate z G) (e : Env) :
    (flowKernel z G hG hwalk hext e).map ratRead =
      (TwoSidedCycleSplice.rootedRegKernel G hG hwalk
        (RegenerationKernelMeasurability.measurable_slotTransition G hG hwalk) e).map
        fun x => ratCode z (e, x.val) := by
  rw [map_ratRead_flowKernel]
  have hm : Measurable fun x : TwoSidedCoding => ratCode z (e, x) :=
    (measurable_ratCode z).comp measurable_prodMk_left
  have hcomp : (fun x : TwoSidedReg => ratCode z (e, x.val)) =
      (fun x : TwoSidedCoding => ratCode z (e, x)) ∘ Subtype.val := rfl
  rw [hcomp, ← Measure.map_map hm measurable_subtype_coe,
    TwoSidedCycleSplice.rootedRegKernel_map_val]
  rfl

/-! ### 5. The support: labels, rooting and coupling of the built configurations -/

variable {z : CellField} {e : Env} {r : Vertex e.val}

/-- **(B2)/(B7) The forward half is untouched on `[0,∞)`.** -/
theorem build_label_of_nonneg {ω : (areaFamily e).Ω × (areaFamily e).Ω}
    (h : ω ∈ goodSet z e r) {s : ℝ} (hs : 0 ≤ s) :
    (build z e r ω).1.toFun s = toENatLabel (((areaFamily e).X s.toNNReal ω.1).map Subtype.val) := by
  rw [build_of_mem z e r h]
  exact glue_of_nonneg (fun s : ℝ => labelPath e ω.1 s.toNNReal)
    (fun s : ℝ => labelPath e ω.2 s.toNNReal) hs

/-- **(B4) Rooted**: the label path starts at the root label. -/
theorem build_label_zero {ω : (areaFamily e).Ω × (areaFamily e).Ω} (h : ω ∈ goodSet z e r) :
    (build z e r ω).1.toFun 0 = ((r.val : ℕ) : ℕ∞) := by
  rw [build_label_of_nonneg h le_rfl, Real.toNNReal_zero,
    (halfGood_of_mem_goodSet z e r h).1.start]
  rfl

/-- **(B3) Coupling**: a built configuration reads the representative field at every rational
vertex time (`TwoSidedRegenerationFlow.Coupled`). -/
theorem build_mem_coupled {ω : (areaFamily e).Ω × (areaFamily e).Ω} (h : ω ∈ goodSet z e r) :
    ((e, build z e r ω) : FlowSpace) ∈ Coupled fun e' n => z.value e' n := by
  intro q n hq _
  have hR := ratRead_build_of_mem h
  have h1 : (build z e r ω).1.toFun (q : ℝ) = rawLabel (labelTraj ((areaFamily e).trajectory ω.1),
      labelTraj ((areaFamily e).trajectory ω.2)) q := congrFun (congrArg Prod.fst hR) q
  have h2 : (build z e r ω).2.toFun (q : ℝ) = repAt z e (rawLabel
      (labelTraj ((areaFamily e).trajectory ω.1),
        labelTraj ((areaFamily e).trajectory ω.2)) q) := congrFun (congrArg Prod.snd hR) q
  have hq' : (build z e r ω).1.toFun (q : ℝ) = (n : ℕ∞) := hq
  show (build z e r ω).2.toFun (q : ℝ) = z.value e n
  rw [h2, ← h1, hq', repAt_natCast]

end ReflectedGMS.FlowCodingKernel
