import QuantumZipper.Statements.Thm13
import QuantumZipper.Loewner.Curves
import QuantumZipper.Field.Law

/-!
# Theorem 1.4 (the welding determines the curve)

Sheffield, *Conformal weldings of random surfaces*, Theorem 1.4. Specification only.

Setting as in Theorem 1.3 (`κ ∈ (0,4)`, `T > 0`, `h = 𝔥_T + h̃∘f_T`, `ν = ν_h` with `γ = √κ`).
`R = R_h : (−∞,0] → [0,∞)` is defined by `ν[x,0] = ν[0,R(x)]` (`weldR`). By Theorem 1.3, `R`
on `[0₋,0]` is the welding homeomorphism of `η_T` onto `[0,0₊]`.

* (a) `R` on `[0₋,0]` determines `η_T`: any simple curve generated by a reverse Loewner flow
  (continuous driving function `W'` from `0`, some time `T' > 0`) with the same `0₋` and whose
  welding homeomorphism equals `R` on `[0₋,0]` has the same hull.
* (b) `h` determines `η_T` (STATEMENT_SPEC A11): the driving function on `[0,T]`, which is in
  bijection with `η_T` for simple curves, is a.s. equal to a measurable function of `h`, seen
  as a distribution modulo additive constants (its raw pairings with mass-zero test functions).
  The function may not read raw values of `h` at other measures. For example, the value at a
  point mass `δ_z` is `𝔥_T(z)` plus a junk constant, which would make (b) provable without
  welding (audit AUDIT-1 §2).
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

namespace QuantumZipper

/-- The conformal welding map `R_h` of the boundary measure `ν = qBoundaryMeasure γ x`:
`R(s) = inf {r ≥ 0 : ν[s,0] ≤ ν[0,r]}`, i.e. the point with `ν[s,0] = ν[0,R(s)]` when `ν` is
atom-free and charges every interval (for `s ≤ 0`). -/
noncomputable def weldR (γ : ℝ) (x : FieldSample) (s : ℝ) : ℝ :=
  sInf {r : ℝ | 0 ≤ r ∧ qBoundaryMeasure γ x (Set.Icc s 0) ≤ qBoundaryMeasure γ x (Set.Icc 0 r)}

/-- **Theorem 1.4 (a).** Almost surely, the welding `R_h` on `[0₋,0]` determines `η_T`: if
`W'` is a continuous driving function with `W' 0 = 0` whose reverse hull at some time `T' > 0`
is a simple curve, with the same negative base preimage `0₋` as `η_T`, and whose welding
homeomorphism agrees with `R_h` on `[0₋,0]`, then its hull equals `η_T = revHull W T`.

The first conjunct (DECISIONS D13) records what the paper presupposes: `0₋ < 0` and `R_h` on
`[0₋,0]` is the welding homeomorphism of `η_T` itself. It excludes the junk value
`qBoundaryMeasure = 0` (for which `R_h ≡ 0` and the second conjunct would be vacuous). -/
def theorem1_4a : Prop :=
  ∀ κ : ℝ, 0 < κ → κ < 4 → ∀ T : ℝ, 0 < T →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P]
    (B : ℝ≥0 → Ω → ℝ) (X : Ω → FieldSample),
    IsBrownianReal B P → IsFreeGFFModConstH X P → IndepFun (pathOf B) X P →
    ∀ᵐ ω ∂P,
      (zeroMinus (drive κ B ω) T < 0 ∧
        ∀ s ∈ Set.Icc (zeroMinus (drive κ B ω) T) 0,
          weldingHom (drive κ B ω) T s =
            weldR (Real.sqrt κ) (couplingFieldRev κ (drive κ B ω) T (X ω)) s) ∧
      ∀ T' : ℝ, 0 < T' → ∀ W' : ℝ → ℝ, Continuous W' → W' 0 = 0 →
      IsSimpleCurveHull (revHull W' T') →
      zeroMinus W' T' = zeroMinus (drive κ B ω) T →
      (∀ s ∈ Set.Icc (zeroMinus (drive κ B ω) T) 0,
        weldingHom W' T' s = weldR (Real.sqrt κ) (couplingFieldRev κ (drive κ B ω) T (X ω)) s) →
      revHull W' T' = revHull (drive κ B ω) T

/-- **Theorem 1.4 (b): `h` determines `η_T`.** There is a measurable map `F` from the
distribution `h` modulo additive constants, i.e. from its raw pairings `ρ ↦ ⟨h, ρ⟩` with all
mass-zero test functions `ρ` supported in `ℍ` (`TestFun0 H`, product σ-algebra), to functions
of time, such that almost surely `F` of the pairings of `h` agrees with the driving function
`W = √κ B` on `[0,T]`. On `[0,T]`, `W` is in bijection with `η_T` for simple curves. `F` may
depend on `κ`, `T` and the probability setup, but not on `ω`. Only the pairings are exposed:
`R_h` is a.s. a measurable function of them (`ν_h` is determined up to a constant factor, and
`R_h` does not see that factor). Raw values of `h` at point masses or at other measures would
leak `𝔥_T` pointwise (AUDIT-1 §2). -/
def theorem1_4b : Prop :=
  ∀ κ : ℝ, 0 < κ → κ < 4 → ∀ T : ℝ, 0 < T →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P]
    (B : ℝ≥0 → Ω → ℝ) (X : Ω → FieldSample),
    IsBrownianReal B P → IsFreeGFFModConstH X P → IndepFun (pathOf B) X P →
    ∃ F : (TestFun0 H → ℝ) → (ℝ → ℝ), Measurable F ∧
      ∀ᵐ ω ∂P, ∀ t ∈ Set.Icc (0 : ℝ) T,
        F (fun ρ => pairRaw (couplingFieldRev κ (drive κ B ω) T (X ω)) ρ.1.1) t = drive κ B ω t

/-- **Theorem 1.4**: parts (a) and (b). -/
def theorem1_4 : Prop := theorem1_4a ∧ theorem1_4b

end QuantumZipper
