import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real
import Mathlib.MeasureTheory.Measure.MeasureSpace
import Mathlib.Topology.MetricSpace.HausdorffDistance
import Mathlib.Topology.Order.Compact
import Mathlib.Topology.Instances.EReal.Lemmas
import Mathlib.Analysis.Complex.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousMap

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# Countable reductions CR1, CR2, CR5, CR6 (decision D30 = D-C1 item 6, node F.MEAS-CR)

`decisions/DEC-C.md`, OD-1, item 6. CR3 (paths and geodesics) is in `LQGMetric.Meas.Geod`,
CR4 (internal metrics, LM S-int (a)) in `LQGMetric.Meas.Internal`.

* **CR1** `measurable_biSup_of_continuous`, `measurable_biInf_of_continuous`: for
  `f : Ω → X → β` continuous in `x` (second countable `X`) and measurable in `ω`, the sup/inf over
  any deterministic set `S ⊆ X` is measurable (reduce to a countable dense subset of `S`);
  `…_continuousMap` for a measurable `C(X, β)`-valued map; `measurableSet_exists_lt`.
* **CR2** `measurableSet_exists_le_of_isClosed`: `{ω | ∃ x ∈ F, f ω x ≤ c}` is measurable for
  `F` closed in a σ-compact space (minima over compact pieces are attained).
* **CR5** random countable sets: a random subset `Z ω` of a fixed countable `I`; sums
  `∑' i, (Z ω).indicator (f ω) i` are measurable, and the union bound.
* **CR6** random sets `A : Ω → Set ℂ`: `randSetSigma A` is generated by the events `{A ⊆ U}`
  (`U` open); hitting events `{A ∩ U ≠ ∅}` (`U` open) and `{A ∩ F = ∅}` (`F` closed) lie in it.

These are standard facts (own elementary proofs, no source needed: each is a few lines of
countable-dense-subset or σ-compactness reasoning, cf. Kechris, *Classical Descriptive Set
Theory*, §12.C for the Effros Borel structure used in CR6).
-/

open MeasureTheory Set Filter Topology
open scoped ENNReal

namespace LQGMetric

section CR1

variable {Ω X β : Type*} [MeasurableSpace Ω] [TopologicalSpace X] [SecondCountableTopology X]
  [CompleteLinearOrder β] [TopologicalSpace β] [OrderTopology β] [SecondCountableTopology β]
  [MeasurableSpace β] [BorelSpace β]

/-- the sup of a continuous function over `S` equals its sup over a dense subset of `S` -/
theorem biSup_eq_of_dense {g : X → β} (hg : Continuous g) {S : Set X} {T : Set S}
    (hT : Dense T) : ⨆ x ∈ S, g x = ⨆ t ∈ T, g t.1 := by
  refine le_antisymm (iSup₂_le fun x hx => ?_) (iSup₂_le fun t _ => le_iSup₂_of_le t.1 t.2 le_rfl)
  have hcl : IsClosed {y : S | g y.1 ≤ ⨆ t ∈ T, g t.1} :=
    isClosed_le (hg.comp continuous_subtype_val) continuous_const
  have hsub : T ⊆ {y : S | g y.1 ≤ ⨆ t ∈ T, g t.1} := fun t ht => le_iSup₂_of_le t ht le_rfl
  exact (hcl.closure_subset_iff.2 hsub) (hT ⟨x, hx⟩)

theorem biInf_eq_of_dense {g : X → β} (hg : Continuous g) {S : Set X} {T : Set S}
    (hT : Dense T) : ⨅ x ∈ S, g x = ⨅ t ∈ T, g t.1 :=
  biSup_eq_of_dense (β := βᵒᵈ) hg hT

/-- **CR1** (sup over any deterministic set). -/
theorem measurable_biSup_of_continuous {f : Ω → X → β} (hc : ∀ ω, Continuous (f ω))
    (hm : ∀ x, Measurable fun ω => f ω x) (S : Set X) :
    Measurable fun ω => ⨆ x ∈ S, f ω x := by
  obtain ⟨T, hTc, hTd⟩ := TopologicalSpace.exists_countable_dense S
  have : Countable T := hTc.to_subtype
  have heq : (fun ω => ⨆ x ∈ S, f ω x) = fun ω => ⨆ t : T, f ω t.1.1 := by
    funext ω
    rw [biSup_eq_of_dense (hc ω) hTd, iSup_subtype']
  rw [heq]
  exact Measurable.iSup fun t => hm t.1.1

/-- **CR1** (inf over any deterministic set). -/
theorem measurable_biInf_of_continuous {f : Ω → X → β} (hc : ∀ ω, Continuous (f ω))
    (hm : ∀ x, Measurable fun ω => f ω x) (S : Set X) :
    Measurable fun ω => ⨅ x ∈ S, f ω x := by
  obtain ⟨T, hTc, hTd⟩ := TopologicalSpace.exists_countable_dense S
  have : Countable T := hTc.to_subtype
  have heq : (fun ω => ⨅ x ∈ S, f ω x) = fun ω => ⨅ t : T, f ω t.1.1 := by
    funext ω
    rw [biInf_eq_of_dense (hc ω) hTd, iInf_subtype']
  rw [heq]
  exact Measurable.iInf fun t => hm t.1.1

end CR1

section CR2

variable {Ω X : Type*} [MeasurableSpace Ω] [TopologicalSpace X] [SecondCountableTopology X]

/-- on a nonempty compact set, "some point has value `≤ c`" iff the infimum is `≤ c` -/
theorem exists_le_iff_biInf_le {g : X → ℝ} (hg : Continuous g) {K : Set X} (hK : IsCompact K)
    (hne : K.Nonempty) (c : ℝ) : (∃ x ∈ K, g x ≤ c) ↔ ⨅ x ∈ K, (g x : EReal) ≤ c := by
  constructor
  · rintro ⟨x, hx, hxc⟩
    exact (biInf_le _ hx).trans (EReal.coe_le_coe_iff.2 hxc)
  · intro h
    obtain ⟨x, hx, hmin⟩ := hK.exists_isMinOn hne hg.continuousOn
    refine ⟨x, hx, EReal.coe_le_coe_iff.1 ((le_iInf₂ fun y hy => ?_).trans h)⟩
    exact EReal.coe_le_coe_iff.2 (hmin hy)

/-- **CR2** (∃ a point in a closed set). -/
theorem measurableSet_exists_le_of_isClosed [SigmaCompactSpace X] {f : Ω → X → ℝ}
    (hc : ∀ ω, Continuous (f ω)) (hm : ∀ x, Measurable fun ω => f ω x) {F : Set X}
    (hF : IsClosed F) (c : ℝ) : MeasurableSet {ω | ∃ x ∈ F, f ω x ≤ c} := by
  classical
  set K : ℕ → Set X := fun n => F ∩ compactCovering X n
  have hK : ∀ n, IsCompact (K n) := fun n => (isCompact_compactCovering X n).inter_left hF
  have hunion : {ω | ∃ x ∈ F, f ω x ≤ c} = ⋃ n, {ω | ∃ x ∈ K n, f ω x ≤ c} := by
    ext ω
    simp only [mem_ofPred_eq, mem_iUnion, K, mem_inter_iff]
    constructor
    · rintro ⟨x, hx, hxc⟩
      obtain ⟨n, hn⟩ := iUnion_eq_univ_iff.1 (iUnion_compactCovering X) x
      exact ⟨n, x, ⟨hx, hn⟩, hxc⟩
    · rintro ⟨n, x, ⟨hx, -⟩, hxc⟩
      exact ⟨x, hx, hxc⟩
  rw [hunion]
  refine MeasurableSet.iUnion fun n => ?_
  rcases (K n).eq_empty_or_nonempty with he | hne
  · simp [he]
  · have : {ω | ∃ x ∈ K n, f ω x ≤ c} = {ω | ⨅ x ∈ K n, (f ω x : EReal) ≤ c} := by
      ext ω; exact exists_le_iff_biInf_le (hc ω) (hK n) hne c
    rw [this]
    refine measurableSet_le ?_ measurable_const
    exact measurable_biInf_of_continuous (f := fun ω x => (f ω x : EReal))
      (fun ω => continuous_coe_real_ereal.comp (hc ω))
      (fun x => measurable_coe_real_ereal.comp (hm x)) (K n)

end CR2

section CR5

variable {Ω I : Type*} [MeasurableSpace Ω] [Countable I]

end CR5

section CR6

variable {Ω : Type*}

end CR6

end LQGMetric
