import LQGMetric.Papers.DG.S3L19
import LQGMetric.Papers.DG.S3L11Lev

/-!
# DG Lemma 3.19 with a random level independent of the fine field (P2-DG105g)

Ding–Gwynne, arXiv:1807.01072, `metric-comparison-final.tex`, Lemma 3.19 (DG:1614–1660) as it is
used in the proof of Lemma 3.21 (DG:1699–1706): after scaling, the threshold involves the coarse
field, independent of the rescaled fine field, and DG condition on it. As in `dg_lemma311_level`
(S3L11Lev) the conditioning is on a discrete level `κ` independent of the σ-algebra generated by
the fine events; the enclosure event is a finite Boolean combination of the events of the
annulus sites (`measurableSet_not_percEnclosure`).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Set
open scoped ENNReal

namespace LQGMetric
namespace DG

/-- an enclosure only uses the sites of the annulus -/
lemma percEnclosure_of_agree {n N : ℤ} {G G' : Set (ℤ × ℤ)} (h : PercEnclosure n N G)
    (hG : ∀ z, (∃ d, z ∈ annRect n N d) → z ∈ G → z ∈ G') : PercEnclosure n N G' := by
  obtain ⟨U, hU, h1, h2, h3⟩ := h
  exact ⟨U, fun z hz => ⟨hG z (hU z hz).2 (hU z hz).1, (hU z hz).2⟩, h1, h2, h3⟩

/-- the sites of the annulus `n ≤ ‖z‖_∞ ≤ N` -/
def annFin (n N : ℤ) : Finset (ℤ × ℤ) :=
  open Classical in
  Finset.filter (fun z => ∃ d, z ∈ annRect n N d) (Finset.Icc (-N) N ×ˢ Finset.Icc (-N) N)

lemma mem_annFin {n N : ℤ} {z : ℤ × ℤ} (hz : ∃ d, z ∈ annRect n N d) : z ∈ annFin n N := by
  obtain ⟨d, hd⟩ := hz
  obtain ⟨⟨h1, h2, h3, h4⟩, h5⟩ := hd
  simp only [annFin, Finset.mem_filter, Finset.mem_product, Finset.mem_Icc]
  exact ⟨⟨⟨h1, h2⟩, h3, h4⟩, d, ⟨h1, h2, h3, h4⟩, h5⟩

lemma measurableSet_not_percEnclosure {Ω : Type*} {m : MeasurableSpace Ω} (n N : ℤ)
    (F : ℤ × ℤ → Set Ω) (hF : ∀ x, MeasurableSet[m] (F x)) :
    MeasurableSet[m] {ω | ¬ PercEnclosure n N {z | ω ∈ F z}} :=
  measurableSet_of_local (annFin n N) (fun G => ¬ PercEnclosure n N G)
    (fun _ _ hGG' hG hG' => hG (percEnclosure_of_agree hG' fun z hz h =>
      (hGG' z (mem_annFin hz)).2 h)) F (fun z _ => hF z)

variable {Ω : Type*} [MeasurableSpace Ω]

/-- **DG Lemma 3.19 at a random level** (DG:1638–1656 with DG:1699–1706): for each level `k`
let `E k z` be fine events which, on `{κ = k}`, imply `D^ε(S_z, ∂S_z(1/2)) ≥ Mf k`; if each has
probability `≥ 1 − 32^{−100}`, far failures satisfy the product bound and the level `κ` is
independent of the fine events, then `P[D^ε(∂_in, ∂_out) < Mf(κ)] ≤ 768 e^{−n log 2}`. -/
theorem dg_lemma319_level (P : Measure Ω) [IsProbabilityMeasure P] (μ : Ω → Measure ℂ)
    {ε s : ℝ} (hs : 0 < s) (b : ℂ) (n : ℕ) (κ : Ω → ℤ) (hκ : Measurable κ) (Mf : ℤ → ℝ)
    (Fg : Set (Set Ω)) (E : ℤ → ℤ × ℤ → Set Ω) (hEm : ∀ k x, E k x ∈ Fg)
    (hindκ : ∀ (k : ℤ) (A : Set Ω), MeasurableSet[MeasurableSpace.generateFrom Fg] A →
      P ({ω | κ ω = k} ∩ A) = P {ω | κ ω = k} * P A)
    (Z : Set Ω)
    (hpath : ∀ᵐ ω ∂P, ω ∉ Z → ∀ k z, κ ω = k → ω ∈ E k z →
      goodAnn (μ ω) ε s b (n / 2 : ℕ) (Mf k) z)
    (hgood : ∀ k z, (∃ d, z ∈ annRect ((n / 2 + 2 : ℕ) : ℤ) ((n - 2 + n / 2 : ℕ) : ℤ) d) →
      P (E k z)ᶜ ≤ (32⁻¹ : ℝ≥0∞) ^ 100)
    (hind : ∀ k (F : Finset (ℤ × ℤ)),
      (∀ z ∈ F, ∃ d, z ∈ annRect ((n / 2 + 2 : ℕ) : ℤ) ((n - 2 + n / 2 : ℕ) : ℤ) d) →
      (∀ x ∈ F, ∀ y ∈ F, x ≠ y → PercFar 9 x y) →
      P (⋂ x ∈ F, (E k x)ᶜ) ≤ ∏ x ∈ F, P (E k x)ᶜ) :
    P {ω | (dgLGDSet (μ ω) ε univ (annIn s b n) (frontier (annOut s b n)) : ℝ≥0∞) <
        ENNReal.ofReal (Mf (κ ω))} ≤
      ENNReal.ofReal (768 * Real.exp (-(Real.log 2 * n))) + P Z := by
  have e2 : Real.exp (-(Real.log 2 * n)) = (2 : ℝ)⁻¹ ^ n := by
    rw [Real.exp_neg, mul_comm, Real.exp_nat_mul, Real.exp_log (by norm_num), inv_pow]
  rw [e2]
  set Bad : ℤ → Set Ω := fun k =>
    {ω | ¬ PercEnclosure ((n / 2 + 2 : ℕ) : ℤ) ((n - 2 + n / 2 : ℕ) : ℤ) {z | ω ∈ E k z}}
  have hsub : {ω | (dgLGDSet (μ ω) ε univ (annIn s b n) (frontier (annOut s b n)) : ℝ≥0∞) <
      ENNReal.ofReal (Mf (κ ω))} ≤ᵐ[P] {ω | ω ∈ Bad (κ ω)} ∪ Z := by
    filter_upwards [hpath] with ω hp
    exact fun hω => by_cases (p := ω ∈ Z) (fun hZ => Or.inr hZ) fun hZ => Or.inl fun henc => (not_le.2 hω)
      (l319_le_of_enc hs b n (G := {z | ω ∈ E (κ ω) z}) (fun z hz => hp hZ (κ ω) z rfl hz) henc)
  refine (measure_mono_ae hsub).trans ((measure_union_le _ _).trans (add_le_add_left ?_ _))
  refine (prob_level_le P κ hκ Fg Bad
    (fun k => measurableSet_not_percEnclosure _ _ _
      (fun x => MeasurableSpace.measurableSet_generateFrom (hEm k x))) hindκ
    (fun k => l319_bad_le P n (E k) (hgood k) (hind k)))

end DG
end LQGMetric
