import QuantumZipper.Proofs.LQG.WedgeRestriction
import QuantumZipper.Proofs.LQG.WedgeMeasurable
import QuantumZipper.Proofs.Probability.StrongMarkov
import QuantumZipper.Proofs.Zipper.UnzipInvariance
import QuantumZipper.Proofs.ItoLite.OptionalStopping

/-!
# Wedge translation invariance (blueprint `E_BRANCH_BLUEPRINT.md` §5, node "B4(c) from L14")

For an `α`-wedge radial process `A` (`IsWedgeProcess α Q A P`, `α < Q`) and `c > 0`, with
`T_c = inf {t ≥ 0 | A t ≤ −c}`, the re-centred path `t ↦ A (T_c + t) + c` has the law of `A`
(on `ℝ → ℝ` with the product σ-algebra, as in `IsQuantumWedge`).

* `t ≥ 0`: `A (T_c + t) + c = √2 (b (T_c + t) − b T_c) − μ t` with `μ = Q − α`; by the strong
  Markov property (`StrongMarkov`, L9) the restarted Brownian motion is a Brownian motion,
  independent of `𝓕_{T_c}`, which contains `b|[0,T_c]` and `b'`.
* `t < 0`: the negative half is the Williams path `Zp` of `WilliamsDriftDecomposition` (L14),
  a named literature hypothesis (not yet a Blueprint item), taken as an explicit hypothesis.
-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Set
open scoped ENNReal NNReal Topology

namespace QuantumZipper

/-- Williams (1974); Rogers–Pitman (1981) Thm 1 and §3; Revuz–Yor VII.4 and XI. -/
def WilliamsDriftDecomposition : Prop :=
  ∀ μ σ c : ℝ, 0 < μ → 0 < σ → 0 < c →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P]
    (b b' : ℝ≥0 → Ω → ℝ), IsBrownianReal b P → IsBrownianReal b' P →
    IndepFun (pathOf b) (pathOf b') P →
    let X : ℝ → Ω → ℝ := fun t ω => σ * b t.toNNReal ω - μ * t
    let Yt : Ω → ℝ → ℝ := fun ω s => σ * b' s.toNNReal ω + μ * s
    let Yh : ℝ → Ω → ℝ := fun u ω => Yt ω (u + lastZero (Yt ω))
    let Tc : Ω → ℝ := fun ω => sInf {t | 0 ≤ t ∧ X t ω ≤ -c}
    let Zp : ℝ → Ω → ℝ := fun u ω =>
      if u ≤ Tc ω then X (Tc ω - u) ω + c else c + Yh (u - Tc ω) ω
    P.map (fun ω (u : ℝ≥0) => Zp u ω) = P.map (fun ω (u : ℝ≥0) => Yh u ω)

namespace WedgeTrans

/-! ## 1. Deterministic facts on hitting times of continuous paths -/

/-- The first time `t ≥ 0` at which `x t ≤ −c`. -/
def hitTime (x : ℝ → ℝ) (c : ℝ) : ℝ := sInf {t | 0 ≤ t ∧ x t ≤ -c}

theorem hitTime_spec {x : ℝ → ℝ} (hx : Continuous x) (h0 : x 0 = 0) {c : ℝ} (hc : 0 < c)
    (hne : ∃ s, 0 ≤ s ∧ x s ≤ -c) :
    0 ≤ hitTime x c ∧ x (hitTime x c) = -c ∧
      ∀ s, 0 ≤ s → x s ≤ -c → hitTime x c ≤ s := by
  set S : Set ℝ := {t | 0 ≤ t ∧ x t ≤ -c} with hS
  have hSc : IsClosed S :=
    (isClosed_le continuous_const continuous_id).inter (isClosed_le hx continuous_const)
  have hbdd : BddBelow S := ⟨0, fun t ht => ht.1⟩
  have hmem : hitTime x c ∈ S := hSc.csInf_mem hne hbdd
  have hle : ∀ s, 0 ≤ s → x s ≤ -c → hitTime x c ≤ s := fun s hs hxs => csInf_le hbdd ⟨hs, hxs⟩
  refine ⟨hmem.1, ?_, hle⟩
  obtain ⟨t, ht, hxt⟩ := intermediate_value_Icc' hmem.1 hx.continuousOn
    (show -c ∈ Icc (x (hitTime x c)) (x 0) from ⟨hmem.2, by rw [h0]; linarith⟩)
  have := hle t ht.1 hxt.le
  have e : t = hitTime x c := le_antisymm ht.2 this
  rw [← e, hxt]

/-! ## 2. The wedge path and its halves -/

variable {Ω : Type*}

/-- The wedge radial process built from two paths. -/
def wA (α Q : ℝ) (b b' : ℝ≥0 → Ω → ℝ) (t : ℝ) (ω : Ω) : ℝ :=
  wedgePath α Q (fun s => b s ω) (fun s => b' s ω) t

/-- Gluing a forward and a backward half into a path on `ℝ`. -/
def glue (p : (ℝ≥0 → ℝ) × (ℝ≥0 → ℝ)) (t : ℝ) : ℝ :=
  if 0 ≤ t then p.1 t.toNNReal else p.2 (-t).toNNReal

theorem measurable_glue : Measurable glue := by
  refine measurable_pi_iff.2 fun t => ?_
  by_cases ht : 0 ≤ t
  · simp only [glue, if_pos ht]; exact (measurable_pi_apply _).comp measurable_fst
  · simp only [glue, if_neg ht]; exact (measurable_pi_apply _).comp measurable_snd

/-! ## 3. The natural filtration of `(b|[0,t], b')` -/

theorem meas_comap_eval {ι β : Type*} [MeasurableSpace β] {Ω : Type*} (F : Ω → ι → β) (i : ι) :
    Measurable[MeasurableSpace.comap F MeasurableSpace.pi] (fun ω => F ω i) := by
  letI := MeasurableSpace.comap F MeasurableSpace.pi
  exact (measurable_pi_apply i).comp (comap_measurable F)

theorem meas_pi_of {Ω ι β : Type*} [MeasurableSpace β] (m : MeasurableSpace Ω)
    (F : Ω → ι → β) (h : ∀ i, Measurable[m] fun ω => F ω i) : Measurable[m] F := by
  letI := m
  exact measurable_pi_iff.2 h

section Good

variable {Ω : Type} [mΩ : MeasurableSpace Ω] {P : Measure Ω}

/-- The filtration generated by `b` up to time `t` together with the whole path `b'`. -/
def natFilt (b b' : ℝ≥0 → Ω → ℝ) (hbm : ∀ t, Measurable (b t))
    (hb'm : ∀ t, Measurable (b' t)) : Filtration ℝ≥0 mΩ where
  seq t := MeasurableSpace.comap (fun ω (r : Set.Iic t) => b r ω) MeasurableSpace.pi ⊔
    MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi
  mono' s t hst := by
    refine sup_le_sup_right (Measurable.comap_le ?_) _
    exact meas_pi_of _ _ fun r =>
      meas_comap_eval (fun ω (r : Set.Iic t) => b r ω) ⟨r, r.2.trans hst⟩
  le' t := sup_le (Measurable.comap_le (measurable_pi_iff.2 fun r => hbm r))
    (Measurable.comap_le (measurable_pi_iff.2 hb'm))

theorem natFilt_b {b b' : ℝ≥0 → Ω → ℝ} (hbm : ∀ t, Measurable (b t))
    (hb'm : ∀ t, Measurable (b' t)) (t : ℝ≥0) : Measurable[natFilt b b' hbm hb'm t] (b t) :=
  (meas_comap_eval (fun ω (r : Set.Iic t) => b r ω) ⟨t, Set.mem_Iic.2 le_rfl⟩).mono
    le_sup_left le_rfl

theorem comap_b'_le_natFilt {b b' : ℝ≥0 → Ω → ℝ} (hbm : ∀ t, Measurable (b t))
    (hb'm : ∀ t, Measurable (b' t)) (t : ℝ≥0) :
    MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi ≤ natFilt b b' hbm hb'm t :=
  le_sup_right

/-! ## 4. The translation identity for good paths -/

variable [IsProbabilityMeasure P]

theorem translation_good (hW : WilliamsDriftDecomposition) {α Q c : ℝ} (hαQ : α < Q)
    (hc : 0 < c) {b b' : ℝ≥0 → Ω → ℝ} (hbm : ∀ t, Measurable (b t))
    (hb'm : ∀ t, Measurable (b' t)) (hbc : ∀ ω, Continuous (b · ω))
    (hb'c : ∀ ω, Continuous (b' · ω)) (hb0 : ∀ ω, b 0 ω = 0)
    (hb : IsPreBrownianReal b P) (hb' : IsPreBrownianReal b' P)
    (hind : IndepFun (pathOf b) (pathOf b') P)
    (hhit : ∀ ω, ∃ s, 0 ≤ s ∧ wA α Q b b' s ω ≤ -c) :
    P.map (fun ω t => wA α Q b b' (hitTime (fun t => wA α Q b b' t ω) c + t) ω + c) =
      P.map (fun ω t => wA α Q b b' t ω) := by
  have hμ : 0 < Q - α := sub_pos.2 hαQ
  have hσ : (0 : ℝ) < √2 := by positivity
  set X : ℝ → Ω → ℝ := fun t ω => √2 * b t.toNNReal ω - (Q - α) * t with hX
  set Yt : Ω → ℝ → ℝ := fun ω s => √2 * b' s.toNNReal ω + (Q - α) * s with hYt
  set L : Ω → ℝ := fun ω => lastZero (Yt ω) with hL
  set Yh : ℝ → Ω → ℝ := fun u ω => Yt ω (u + lastZero (Yt ω)) with hYh
  set Tc : Ω → ℝ := fun ω => sInf {t | 0 ≤ t ∧ X t ω ≤ -c} with hTc
  set Zp : ℝ → Ω → ℝ := fun u ω =>
    if u ≤ Tc ω then X (Tc ω - u) ω + c else c + Yh (u - Tc ω) ω with hZp
  -- the two halves of the wedge path
  have hApos : ∀ ω t, 0 ≤ t → wA α Q b b' t ω = X t ω := by
    intro ω t ht
    simp only [wA, wedgePath, if_pos ht, hX]
    ring
  have hYeq : ∀ ω, (fun s : ℝ => √2 * b' s.toNNReal ω - (α - Q) * s) = Yt ω := fun ω =>
    funext fun s => by simp only [hYt]; ring
  have hAneg : ∀ ω t, t < 0 → wA α Q b b' t ω = Yh (-t) ω := by
    intro ω t ht
    have e : wA α Q b b' t ω = (fun s : ℝ => √2 * b' s.toNNReal ω - (α - Q) * s)
        (-t + lastZero (fun s : ℝ => √2 * b' s.toNNReal ω - (α - Q) * s)) := by
      simp only [wA, wedgePath, if_neg (not_le.2 ht)]
    rw [e, hYeq ω]
  have hT : ∀ ω, hitTime (fun t => wA α Q b b' t ω) c = Tc ω := by
    intro ω
    simp only [hitTime, hTc]
    congr 1
    ext t
    simp only [mem_setOf_eq]
    constructor
    · rintro ⟨h0, h⟩; exact ⟨h0, by rwa [hApos ω t h0] at h⟩
    · rintro ⟨h0, h⟩; exact ⟨h0, by rwa [hApos ω t h0]⟩
  have hXc : ∀ ω, Continuous fun t => X t ω := fun ω =>
    (continuous_const.mul ((hbc ω).comp continuous_real_toNNReal)).sub
      (continuous_const.mul continuous_id)
  have hX0 : ∀ ω, X 0 ω = 0 := fun ω => by simp [hX, hb0]
  have hspec : ∀ ω, 0 ≤ Tc ω ∧ X (Tc ω) ω = -c ∧ ∀ s, 0 ≤ s → X s ω ≤ -c → Tc ω ≤ s :=
    fun ω => hitTime_spec (hXc ω) (hX0 ω) hc (by
      obtain ⟨s, hs, h⟩ := hhit ω
      exact ⟨s, hs, by rwa [hApos ω s hs] at h⟩)
  set Tn : Ω → ℝ≥0 := fun ω => (Tc ω).toNNReal with hTn_def
  have hTn : ∀ ω, (Tn ω : ℝ) = Tc ω := fun ω => Real.coe_toNNReal _ (hspec ω).1
  -- the filtration and the stopping time
  set 𝓕 := natFilt b b' hbm hb'm with h𝓕
  have hbad : ∀ t, Measurable[𝓕 t] (b t) := natFilt_b hbm hb'm
  have hXad : Adapted 𝓕 (fun (s : ℝ≥0) ω => X s ω) := fun s => by
    have h := ((hbad s).const_mul (√2)).sub_const ((Q - α) * s)
    convert h using 1
    funext ω; simp only [hX, Real.toNNReal_coe]
  have hXcn : ∀ ω, Continuous fun s : ℝ≥0 => X s ω := fun ω =>
    (hXc ω).comp NNReal.continuous_coe
  have hstop : IsStoppingTime 𝓕 (fun ω => (Tn ω : WithTop ℝ≥0)) := by
    intro u
    have hh := ItoLite.isStoppingTime_hittingBtwn_of_isClosed hXad hXcn
      (isClosed_Iic (a := -c)) (u + 1) u
    convert hh using 1
    ext ω
    simp only [mem_setOf_eq, WithTop.coe_le_coe]
    constructor
    · intro h
      refine (hittingBtwn_le_of_mem zero_le (h.trans (le_add_of_nonneg_right zero_le)) ?_).trans h
      show X (Tn ω) ω ∈ Iic (-c)
      rw [hTn]; exact (hspec ω).2.1.le
    · intro h
      by_cases hex : ∃ j ∈ Icc (0 : ℝ≥0) (u + 1), (fun (s : ℝ≥0) ω => X s ω) j ω ∈ Iic (-c)
      · set S : Set ℝ≥0 := Icc 0 (u + 1) ∩ {i | X i ω ∈ Iic (-c)} with hS
        have hSc : IsClosed S := isClosed_Icc.inter (isClosed_Iic.preimage (hXcn ω))
        have hSne : S.Nonempty := by obtain ⟨j, hj, hjK⟩ := hex; exact ⟨j, hj, hjK⟩
        have hmem := hSc.csInf_mem hSne (OrderBot.bddBelow S)
        have heq : hittingBtwn (fun (s : ℝ≥0) ω => X s ω) (Iic (-c)) 0 (u + 1) ω = sInf S := by
          simp only [hittingBtwn, hex, ↓reduceIte, hS]
        rw [heq] at h
        have h1 := (hspec ω).2.2 ((sInf S : ℝ≥0) : ℝ) (NNReal.coe_nonneg _) hmem.2
        rw [← NNReal.coe_le_coe]
        rw [hTn]
        exact h1.trans (NNReal.coe_le_coe.2 h)
      · have heq : hittingBtwn (fun (s : ℝ≥0) ω => X s ω) (Iic (-c)) 0 (u + 1) ω = u + 1 := by
          simp only [hittingBtwn, hex, ↓reduceIte]
        rw [heq] at h
        exact absurd h (not_le.2 (lt_add_one u))
  -- measurability of the `b'`-data
  have hmB'le : (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi) ≤ mΩ := Measurable.comap_le (measurable_pi_iff.2 hb'm)
  have hYtc : ∀ ω, Continuous (Yt ω) := fun ω =>
    (continuous_const.mul ((hb'c ω).comp continuous_real_toNNReal)).add
      (continuous_const.mul continuous_id)
  have hYtm' : ∀ s, Measurable[(MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)] fun ω => Yt ω s := fun s =>
    ((meas_comap_eval (fun ω s => b' s ω) s.toNNReal).const_mul _).add_const _
  have hLm' : Measurable[(MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)] L := @WedgeMeas.measurable_lastZero Ω (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi) Yt hYtc hYtm'
  have hYtJ' : Measurable[@Prod.instMeasurableSpace ℝ Ω _ (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)]
      (fun p : ℝ × Ω => Yt p.2 p.1) :=
    measurable_uncurry_of_continuous_of_measurable (m := (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)) (u := fun r ω => Yt ω r)
      hYtc hYtm'
  have hYhm' : ∀ u, Measurable[(MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)] (Yh u) := fun u =>
    hYtJ'.comp (Measurable.prodMk (m := (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)) ((@measurable_const ℝ Ω _ (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi) u).add hLm')
      (@measurable_id Ω (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)))
  -- the `𝓕_T`-measurability of the Williams path
  have hmB'T : (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi) ≤ hstop.measurableSpace := by
    have h := (isStoppingTime_const 𝓕 (0 : ℝ≥0)).measurableSpace_mono hstop
      (fun ω => WithTop.coe_le_coe.2 zero_le)
    rw [IsStoppingTime.measurableSpace_const] at h
    exact (comap_b'_le_natFilt hbm hb'm 0).trans h
  have hTnT : Measurable[hstop.measurableSpace] Tn := by
    refine measurable_of_Iic fun s => ?_
    have h := hstop.measurableSet_le' s
    convert h using 1
    ext ω
    simp only [mem_preimage, mem_Iic, mem_setOf_eq, WithTop.coe_le_coe]
  have hTcT : Measurable[hstop.measurableSpace] Tc := by
    have : Tc = fun ω => ((Tn ω : ℝ≥0) : ℝ) := funext fun ω => (hTn ω).symm
    rw [this]; exact measurable_coe_nnreal_real.comp hTnT
  have hprog : IsStronglyProgressive 𝓕 b :=
    StronglyAdapted.isStronglyProgressive_of_continuous (fun t => (hbad t).stronglyMeasurable) hbc
  have hbstop : ∀ s : ℝ≥0, Measurable[hstop.measurableSpace] fun ω => b (min s (Tn ω)) ω := by
    intro s
    have hmin := hstop.min_const s
    have h1 := measurable_stoppedValue hprog hmin
    have h2 : hmin.measurableSpace ≤ hstop.measurableSpace :=
      hmin.measurableSpace_mono hstop fun ω => min_le_left _ _
    convert h1.mono h2 le_rfl using 1
    funext ω
    simp only [stoppedValue, WithTop.untopA]
    rw [← WithTop.coe_min, WithTop.untopD_coe, min_comm]
  have hbJ : Measurable[@Prod.instMeasurableSpace ℝ≥0 Ω _ hstop.measurableSpace]
      (fun p : ℝ≥0 × Ω => b (min p.1 (Tn p.2)) p.2) :=
    measurable_uncurry_of_continuous_of_measurable (m := hstop.measurableSpace)
      (u := fun s ω => b (min s (Tn ω)) ω)
      (fun ω => (hbc ω).comp (continuous_id.min continuous_const)) hbstop
  have hZpm : ∀ u : ℝ≥0, Measurable[hstop.measurableSpace] (Zp u) := by
    intro u
    have hr : Measurable[hstop.measurableSpace] fun ω => (Tc ω - u).toNNReal :=
      (hTcT.sub_const _).real_toNNReal
    have hb1 : Measurable[hstop.measurableSpace] fun ω => b (Tc ω - u).toNNReal ω := by
      have e : (fun ω => b (Tc ω - u).toNNReal ω) =
          fun ω => b (min (Tc ω - u).toNNReal (Tn ω)) ω := by
        funext ω
        congr 2
        refine (min_eq_left ?_).symm
        rw [← NNReal.coe_le_coe, hTn, Real.coe_toNNReal']
        exact max_le (by linarith [NNReal.coe_nonneg u]) (hspec ω).1
      rw [e]
      exact hbJ.comp (Measurable.prodMk (m := hstop.measurableSpace) hr (@measurable_id Ω hstop.measurableSpace))
    have hb2 : Measurable[hstop.measurableSpace] fun ω => Yt ω (u - Tc ω + L ω) :=
      hYtJ'.comp (Measurable.prodMk (m := hstop.measurableSpace)
        (((@measurable_const ℝ Ω _ hstop.measurableSpace (u : ℝ)).sub hTcT).add (hLm'.mono hmB'T le_rfl))
        ((@measurable_id Ω (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi)).mono hmB'T le_rfl))
    refine Measurable.ite (measurableSet_le measurable_const hTcT) ?_ ?_
    · exact (((hb1.const_mul _).sub ((hTcT.sub_const _).const_mul _))).add_const _
    · refine (@measurable_const ℝ Ω _ hstop.measurableSpace c).add ?_
      convert hb2 using 1
  -- the strong Markov property at `Tn`
  have hbB : IsBrownianReal b P := ⟨hb, ae_of_all _ hbc⟩
  have hb'B : IsBrownianReal b' P := ⟨hb', ae_of_all _ hb'c⟩
  have hTnm : Measurable Tn := StrongMarkov.measurable_of_isStoppingTime hstop
  have hmBple : (MeasurableSpace.comap (pathOf b) MeasurableSpace.pi) ≤ mΩ := Measurable.comap_le (measurable_pi_iff.2 hbm)
  have hindS : ∀ t, Indep (𝓕 t) (MeasurableSpace.comap
      (StrongMarkov.smPath b (fun _ => t)) MeasurableSpace.pi) P := by
    intro t
    have h12 : Indep (MeasurableSpace.comap (fun ω (r : Set.Iic t) => b r ω)
        MeasurableSpace.pi) (MeasurableSpace.comap (StrongMarkov.smPath b (fun _ => t))
        MeasurableSpace.pi) P := by
      have h := hb.indepFun_shift t
      rw [IndepFun_iff_Indep] at h
      exact h.symm
    have hXB : Indep (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi) (MeasurableSpace.comap (pathOf b) MeasurableSpace.pi) P := ((IndepFun_iff_Indep _ _ _).1 hind).symm
    have h₁ : MeasurableSpace.comap (fun ω (r : Set.Iic t) => b r ω) MeasurableSpace.pi ≤ (MeasurableSpace.comap (pathOf b) MeasurableSpace.pi) :=
      Measurable.comap_le (meas_pi_of _ _ fun r => meas_comap_eval (pathOf b) (r : ℝ≥0))
    have h₂ : MeasurableSpace.comap (StrongMarkov.smPath b fun _ => t) MeasurableSpace.pi ≤
        (MeasurableSpace.comap (pathOf b) MeasurableSpace.pi) :=
      Measurable.comap_le (meas_pi_of _ _ fun s =>
        (meas_comap_eval (pathOf b) (t + s)).sub (meas_comap_eval (pathOf b) t))
    exact UnzipInvariance.indep_sup_of_indep h₁ h₂ hmBple hmB'le h12 hXB
  have hSB : IsBrownianReal (StrongMarkov.smShift b Tn) P :=
    StrongMarkov.isBrownianReal_smShift hb hbc hbm hindS hstop
  have hSind : IndepFun (fun ω (u : ℝ≥0) => Zp u ω) (StrongMarkov.smPath b Tn) P :=
    StrongMarkov.indepFun_smPath hb hbc hbm hindS hstop (meas_pi_of hstop.measurableSpace _ fun u => hZpm u)
  -- the two paths as glued halves
  have hAP : ∀ ω, (fun t => wA α Q b b' t ω) =
      glue ((fun s : ℝ≥0 => X s ω), fun u : ℝ≥0 => Yh u ω) := by
    intro ω; funext t
    by_cases ht : 0 ≤ t
    · simp only [glue, if_pos ht, Real.coe_toNNReal _ ht]
      exact hApos ω t ht
    · have ht' : 0 ≤ -t := by linarith
      simp only [glue, if_neg ht, Real.coe_toNNReal _ ht']
      exact hAneg ω t (not_le.1 ht)
  have hA'P : ∀ ω, (fun t => wA α Q b b' (hitTime (fun t => wA α Q b b' t ω) c + t) ω + c) =
      glue ((fun s : ℝ≥0 => √2 * StrongMarkov.smShift b Tn s ω - (Q - α) * s),
        fun u : ℝ≥0 => Zp u ω) := by
    intro ω; funext t
    rw [hT ω]
    obtain ⟨h0, hXT, -⟩ := hspec ω
    by_cases ht : 0 ≤ t
    · simp only [glue, if_pos ht]
      rw [hApos ω _ (by linarith)]
      have e1 : (Tc ω + t).toNNReal = Tn ω + t.toNNReal := Real.toNNReal_add h0 ht
      have hXT' : √2 * b (Tn ω) ω - (Q - α) * Tc ω = -c := hXT
      simp only [hX, StrongMarkov.smShift, e1, Real.coe_toNNReal _ ht]
      linarith
    · have hu0 : 0 < -t := by linarith
      simp only [glue, if_neg ht, Real.coe_toNNReal _ hu0.le, hZp]
      by_cases hut : -t ≤ Tc ω
      · rw [if_pos hut, hApos ω _ (by linarith)]
        congr 2
        ring
      · rw [if_neg hut, hAneg ω _ (by linarith)]
        rw [add_comm]
        congr 2
        ring
  -- the four halves and their laws
  set ψ : (ℝ≥0 → ℝ) → (ℝ≥0 → ℝ) := fun p s => √2 * p s - (Q - α) * s with hψdef
  have hψ : Measurable ψ := measurable_pi_iff.2 fun s =>
    ((measurable_pi_apply s).const_mul _).sub_const _
  set F1 : Ω → ℝ≥0 → ℝ := fun ω s => X s ω with hF1
  set F2 : Ω → ℝ≥0 → ℝ := fun ω u => Yh u ω with hF2
  set G1 : Ω → ℝ≥0 → ℝ := fun ω s => √2 * StrongMarkov.smShift b Tn s ω - (Q - α) * s with hG1
  set G2 : Ω → ℝ≥0 → ℝ := fun ω u => Zp u ω with hG2
  have hF1ψ : F1 = ψ ∘ pathOf b := by
    funext ω s; simp only [hF1, hX, hψdef, Function.comp_apply, pathOf, Real.toNNReal_coe]
  have hG1ψ : G1 = ψ ∘ StrongMarkov.smPath b Tn := rfl
  have hpathm : Measurable (pathOf b) := measurable_pi_iff.2 hbm
  have hSpm : Measurable (StrongMarkov.smPath b Tn) := StrongMarkov.measurable_smPath hbc hbm hTnm
  have hF1m : Measurable F1 := by rw [hF1ψ]; exact hψ.comp hpathm
  have hF2m : Measurable F2 := (meas_pi_of (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi) F2 fun u => hYhm' u).mono hmB'le le_rfl
  have hG1m : Measurable G1 := by rw [hG1ψ]; exact hψ.comp hSpm
  have hG2m : Measurable G2 := (meas_pi_of hstop.measurableSpace G2 hZpm).mono hstop.measurableSpace_le le_rfl
  have hindF : IndepFun F1 F2 P := by
    rw [IndepFun_iff_Indep]
    have h := (IndepFun_iff_Indep _ _ _).1 hind
    refine indep_of_indep_of_le_left (indep_of_indep_of_le_right h ?_) ?_
    · exact Measurable.comap_le (meas_pi_of (MeasurableSpace.comap (fun ω s => b' s ω) MeasurableSpace.pi) F2 fun u => hYhm' u)
    · rw [hF1ψ, ← MeasurableSpace.comap_comp]
      exact MeasurableSpace.comap_mono hψ.comap_le
  have hindG : IndepFun G1 G2 P := by
    rw [hG1ψ]
    exact (hSind.symm.comp hψ measurable_id)
  have hlawF := (indepFun_iff_map_prod_eq_prod_map_map hF1m.aemeasurable hF2m.aemeasurable).1 hindF
  have hlawG := (indepFun_iff_map_prod_eq_prod_map_map hG1m.aemeasurable hG2m.aemeasurable).1 hindG
  have hG1F1 : P.map G1 = P.map F1 := by
    rw [hG1ψ, hF1ψ, ← Measure.map_map hψ hSpm, ← Measure.map_map hψ hpathm]
    congr 1
    exact WedgeRes.map_path_eq hSB.toIsPreBrownianReal hb hSpm hpathm
  have hG2F2 : P.map G2 = P.map F2 := by
    have hW' := hW (Q - α) (√2) c hμ hσ hc P b b' hbB hb'B hind
    exact hW'
  calc P.map (fun ω t => wA α Q b b' (hitTime (fun t => wA α Q b b' t ω) c + t) ω + c)
      = P.map (glue ∘ fun ω => (G1 ω, G2 ω)) := by
        congr 1; funext ω; exact hA'P ω
    _ = (P.map (fun ω => (G1 ω, G2 ω))).map glue :=
        (Measure.map_map measurable_glue (hG1m.prodMk hG2m)).symm
    _ = ((P.map F1).prod (P.map F2)).map glue := by rw [hlawG, hG1F1, hG2F2]
    _ = (P.map (fun ω => (F1 ω, F2 ω))).map glue := by rw [hlawF]
    _ = P.map (glue ∘ fun ω => (F1 ω, F2 ω)) :=
        Measure.map_map measurable_glue (hF1m.prodMk hF2m)
    _ = P.map (fun ω t => wA α Q b b' t ω) := by
        congr 1; funext ω; exact (hAP ω).symm

end Good

/-! ## 5. The drifted Brownian motion goes below `−c` -/

section Hit

variable {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]

theorem ae_exists_below {W : ℝ≥0 → Ω → ℝ} (hW : IsPreBrownianReal W P)
    (hWm : ∀ t, Measurable (W t)) {μ c : ℝ} (hμ : 0 < μ) (hc : 0 < c) :
    ∀ᵐ ω ∂P, ∃ n : ℕ, √2 * W n ω - μ * n < -c := by
  rw [ae_iff]
  set E := {ω | ¬ ∃ n : ℕ, √2 * W n ω - μ * n < -c} with hE
  have hbound : ∀ n : ℕ, 2 * c / μ ≤ n → 1 ≤ n →
      P E ≤ ENNReal.ofReal ((8 / μ ^ 2) / n) := by
    intro n hn hn1
    have hn0 : (0 : ℝ) < n := by exact_mod_cast hn1
    have hpos : 0 < μ * n - c := by
      have : 2 * c ≤ μ * n := by rw [div_le_iff₀ hμ] at hn; linarith
      linarith
    set a : ℝ := (μ * n - c) / √2 with ha
    have ha0 : 0 < a := by positivity
    have hsub : E ⊆ {ω | a ≤ |W n ω - P[W n]|} := by
      intro ω hω
      simp only [hE, mem_setOf_eq, not_exists, not_lt] at hω
      simp only [mem_setOf_eq, hW.integral_eval, sub_zero, NNReal.coe_natCast]
      have h1 := hω n
      have h2 : a ≤ W n ω := by
        rw [ha, div_le_iff₀ (by positivity)]
        linarith
      exact h2.trans (le_abs_self _)
    have hvar : variance (W n) P = n := by
      rw [← covariance_self (hW.aemeasurable n), hW.covariance_eval, min_self, NNReal.coe_natCast]
    refine (measure_mono hsub).trans ((meas_ge_le_variance_div_sq
      (hW.isGaussianProcess.hasGaussianLaw_eval n).memLp_two ha0).trans ?_)
    rw [hvar]
    refine ENNReal.ofReal_le_ofReal ?_
    have h2 : √2 ^ 2 = (2 : ℝ) := Real.sq_sqrt (by norm_num)
    have h3 : μ * n / 2 ≤ μ * n - c := by
      have : 2 * c ≤ μ * n := by rw [div_le_iff₀ hμ] at hn; linarith
      linarith
    have h4 : (μ * n / 2) ^ 2 ≤ (μ * n - c) ^ 2 := pow_le_pow_left₀ (by positivity) h3 2
    have hq : 0 < (μ * n - c) ^ 2 := by positivity
    rw [ha, div_pow, h2, div_div_eq_mul_div, div_le_div_iff₀ hq hn0]
    have e : 8 / μ ^ 2 * (μ * n / 2) ^ 2 = 2 * (n : ℝ) ^ 2 := by field_simp; ring
    calc (n : ℝ) * 2 * n = 8 / μ ^ 2 * (μ * n / 2) ^ 2 := by rw [e]; ring
      _ ≤ 8 / μ ^ 2 * (μ * n - c) ^ 2 := mul_le_mul_of_nonneg_left h4 (by positivity)
  have htend : Tendsto (fun n : ℕ => ENNReal.ofReal ((8 / μ ^ 2) / n)) atTop (𝓝 0) := by
    rw [← ENNReal.ofReal_zero]
    exact ENNReal.tendsto_ofReal (tendsto_const_div_atTop_nhds_zero_nat _)
  refine le_antisymm (ge_of_tendsto htend ?_) zero_le
  obtain ⟨N, hN⟩ := exists_nat_ge (2 * c / μ : ℝ)
  filter_upwards [eventually_ge_atTop (max N 1)] with n hn
  refine hbound n (hN.trans (by exact_mod_cast (le_max_left _ _).trans hn)) ?_
  exact_mod_cast (le_max_right _ _).trans hn

end Hit

/-! ## 6. Translation invariance of the wedge radial process -/

/-- **B4(c) (from L14): wedge translation invariance.** For an `α`-wedge radial process with
`α < Q` and `c > 0`, the path re-centred at `T_c = inf {t ≥ 0 | A t ≤ −c}` and shifted by `c`
has the law of `A`, as a random element of `ℝ → ℝ` with the product σ-algebra. -/
theorem wedge_translation (hW : WilliamsDriftDecomposition) {Ω : Type} [MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {α Q : ℝ} {A : ℝ → Ω → ℝ}
    (hA : IsWedgeProcess α Q A P) (hαQ : α < Q) {c : ℝ} (hc : 0 < c) :
    P.map (fun ω t => A (sInf {s | 0 ≤ s ∧ A s ω ≤ -c} + t) ω + c) =
      P.map (fun ω t => A t ω) := by
  classical
  obtain ⟨B, B', hB, hB', hBB', hAB⟩ := hA
  obtain ⟨Bt, hBtm, hBtc, hBtB⟩ := WedgeRes.exists_good_version hB
  obtain ⟨Bt', hBt'm, hBt'c, hBt'B⟩ := WedgeRes.exists_good_version hB'
  have hBtmt : ∀ t, Measurable (Bt t) := fun t => hBtm.of_uncurry_left
  have hBt'mt : ∀ t, Measurable (Bt' t) := fun t => hBt'm.of_uncurry_left
  have hBtpre : IsPreBrownianReal Bt P :=
    hB.toIsPreBrownianReal.congr fun s => hBtB.mono fun ω h => (h s).symm
  have hBt'pre : IsPreBrownianReal Bt' P :=
    hB'.toIsPreBrownianReal.congr fun s => hBt'B.mono fun ω h => (h s).symm
  have hμ : 0 < Q - α := sub_pos.2 hαQ
  -- the good set, and the modification off it
  set G : Set Ω := {ω | Bt 0 ω = 0 ∧ ∃ n : ℕ, √2 * Bt n ω - (Q - α) * n < -c} with hG
  have hGm : MeasurableSet G := by
    have h1 : MeasurableSet {ω | Bt 0 ω = 0} := measurableSet_eq_fun (hBtmt 0) measurable_const
    have h2 : MeasurableSet {ω | ∃ n : ℕ, √2 * Bt n ω - (Q - α) * n < -c} := by
      have : {ω | ∃ n : ℕ, √2 * Bt n ω - (Q - α) * n < -c} =
          ⋃ n : ℕ, {ω | √2 * Bt n ω - (Q - α) * n < -c} := by ext ω; simp
      rw [this]
      exact MeasurableSet.iUnion fun n =>
        measurableSet_lt (((hBtmt _).const_mul _).sub_const _) measurable_const
    exact h1.inter h2
  have hGae : ∀ᵐ ω ∂P, ω ∈ G := by
    filter_upwards [hBtpre.eval_zero_ae_eq_zero, ae_exists_below hBtpre hBtmt hμ hc]
      with ω h1 h2 using ⟨h1, h2⟩
  set b : ℝ≥0 → Ω → ℝ := fun s ω => if ω ∈ G then Bt s ω else -(√2 * c) * s with hbdef
  have hbm : ∀ t, Measurable (b t) := fun t => Measurable.ite hGm (hBtmt t) measurable_const
  have hbc : ∀ ω, Continuous (b · ω) := by
    intro ω
    by_cases hω : ω ∈ G
    · simp only [hbdef, if_pos hω]; exact hBtc ω
    · simp only [hbdef, if_neg hω]; exact continuous_const.mul NNReal.continuous_coe
  have hb0 : ∀ ω, b 0 ω = 0 := by
    intro ω
    by_cases hω : ω ∈ G
    · simp only [hbdef, if_pos hω]; exact hω.1
    · simp [hbdef, if_neg hω]
  have hbBt : ∀ᵐ ω ∂P, ∀ s, b s ω = B s ω := by
    filter_upwards [hGae, hBtB] with ω hω h s
    simp only [hbdef, if_pos hω, h s]
  have hbpre : IsPreBrownianReal b P :=
    hB.toIsPreBrownianReal.congr fun s => hbBt.mono fun ω h => (h s).symm
  have hind : IndepFun (pathOf b) (pathOf Bt') P := by
    refine hBB'.congr ?_ ?_
    · filter_upwards [hbBt] with ω h
      funext s; exact (h s).symm
    · filter_upwards [hBt'B] with ω h
      funext s; exact (h s).symm
  have hhit : ∀ ω, ∃ s, 0 ≤ s ∧ wA α Q b Bt' s ω ≤ -c := by
    intro ω
    by_cases hω : ω ∈ G
    · obtain ⟨n, hn⟩ := hω.2
      refine ⟨n, n.cast_nonneg, ?_⟩
      simp only [wA, wedgePath, if_pos (Nat.cast_nonneg n : (0 : ℝ) ≤ n), hbdef, if_pos hω]
      have : ((n : ℝ)).toNNReal = (n : ℝ≥0) := by simp
      rw [this]
      linarith
    · refine ⟨1, zero_le_one, ?_⟩
      simp only [wA, wedgePath, if_pos (zero_le_one : (0 : ℝ) ≤ 1), hbdef, if_neg hω,
        Real.toNNReal_one, NNReal.coe_one, mul_one]
      have h2 : √2 * √2 = (2 : ℝ) := Real.mul_self_sqrt (by norm_num)
      nlinarith
  have hmain := translation_good hW hαQ hc hbm hBt'mt hbc hBt'c hb0 hbpre hBt'pre hind hhit
  -- transfer back to `A`
  have hAeq : ∀ᵐ ω ∂P, (fun t => A t ω) = fun t => wA α Q b Bt' t ω := by
    filter_upwards [hbBt, hBt'B] with ω h1 h2
    funext t
    rw [hAB ω t, wA]
    congr 1
    · funext s; exact (h1 s).symm
    · funext s; exact (h2 s).symm
  have e1 : P.map (fun ω t => A (sInf {s | 0 ≤ s ∧ A s ω ≤ -c} + t) ω + c) =
      P.map (fun ω t => wA α Q b Bt' (hitTime (fun t => wA α Q b Bt' t ω) c + t) ω + c) := by
    refine Measure.map_congr ?_
    filter_upwards [hAeq] with ω h
    have h' : ∀ t, A t ω = wA α Q b Bt' t ω := fun t => congrFun h t
    simp only [hitTime, h']
  have e2 : P.map (fun ω t => A t ω) = P.map (fun ω t => wA α Q b Bt' t ω) :=
    Measure.map_congr (hAeq.mono fun ω h => h)
  rw [e1, e2]
  exact hmain

end WedgeTrans

end QuantumZipper
