import QuantumZipper.Proofs.Thm11.AddendumAssemblyStmt
import QuantumZipper.Proofs.Thm11.AddendumAssemblyLin
import QuantumZipper.Proofs.Thm11.CharFunRhs
import QuantumZipper.Proofs.GFF.K3.C5Cov
import QuantumZipper.Proofs.NonVacuityAddendum
import QuantumZipper.Proofs.Thm11.MainFull

/-!
# Theorem 1.1 addendum (`κ ∈ (4,8)`), AD-8: the assembly

Blueprint `blueprint/THM11_BLUEPRINT.md` §9, node AD-8; Sheffield, *Conformal weldings of random
surfaces* (arXiv:1012.4797), Theorem 1.1 and its addendum (p. 12).

`theorem1_1_addendum_of_nodes : ExtIntStmt → ExtMartStmt → ExtMeasStmt → theorem1_1_addendum`,
and `theorem1_1_of_nodes` (the same hypotheses give the full `theorem1_1`).

Route (the blueprint's AD-8, formalized as in the proved main part `Thm11MainFull`):
* replace `B` by a version `B'` with continuous measurable paths; the right-hand field
  `Y = 𝔥^ext_T(B') + X'` is a.s. the addendum's field, and has measurable pairings
  (`ExtMeasStmt`);
* `(𝔥^ext_T, ρ)` is a measurable function `Φ` of `pathOf B'` (Doob–Dynkin,
  `Measurable.exists_eq_measurable_comp`, applied with the σ-algebra generated by `pathOf B'`);
* `IsCondZeroBoundaryGFFH` with `F = cos ∘ Φ` and `F = sin ∘ Φ` gives
  `E e^{i⟨Y,ρ⟩} = E e^{iΦ − ½ zeroGFFTestCov(U)(ρ,ρ)}` (`integral_cexp_cond`);
* K3 C5 (`K3.zeroGFFTestCov_sleComplement`, proved) turns the covariance into `∬ρρV_T`, and
  `ExtMartStmt` (AD-4 + MF-5) gives `exp(i(𝔥₀,ρ) − ½∬ρρG_ℍ)`, the characteristic function of
  the left side (`CharFunFwd.charFun_lhs_fwd`);
* Cramér–Wold (`CharFunFwd.fieldLaw_eq_of_charFun`), with a.s. linearity of the pairings of the
  conditional GFF (`linearPairingH_of_condGFF`) and of `(𝔥^ext_T, ·)` (from `ExtIntStmt`).
-/

noncomputable section

open MeasureTheory ProbabilityTheory Complex Set
open scoped NNReal

namespace QuantumZipper
namespace Thm11Asm

section Meas

variable {κ T : ℝ}

theorem measurable_extPair (hMeas : ExtMeasStmt) (hκ4 : 4 < κ) (hκ8 : κ < 8) (hT : 0 < T)
    {Ω : Type} [MeasurableSpace Ω] {B : ℝ≥0 → Ω → ℝ} (hBm : ∀ t, Measurable (B t))
    (hBc : ∀ ω, Continuous fun t => B t ω) (ρ : TestFun H) :
    Measurable fun ω => ∫ z, ρ.1 z * hTfwdExt κ (drive κ B ω) T z :=
  (((ρ.2.1.continuous.measurable.comp measurable_snd).mul
    (hMeas κ T hκ4 hκ8 hT B hBm hBc)).stronglyMeasurable.integral_prod_right').measurable

theorem measurable_ofFun_ext (hMeas : ExtMeasStmt) (hκ4 : 4 < κ) (hκ8 : κ < 8) (hT : 0 < T)
    {Ω : Type} [MeasurableSpace Ω] {B : ℝ≥0 → Ω → ℝ} (hBm : ∀ t, Measurable (B t))
    (hBc : ∀ ω, Continuous fun t => B t ω) (μ : Measure ℂ) [SFinite μ] :
    Measurable fun ω => ofFun (hTfwdExt κ (drive κ B ω) T) μ := by
  unfold ofFun
  exact (hMeas κ T hκ4 hκ8 hT B hBm hBc).stronglyMeasurable.integral_prod_right'.measurable

/-- `(𝔥^ext_T, ρ)` is a measurable function of the path (Doob–Dynkin). -/
theorem exists_extPair_path (hMeas : ExtMeasStmt) (hκ4 : 4 < κ) (hκ8 : κ < 8) (hT : 0 < T)
    {Ω : Type} {B : ℝ≥0 → Ω → ℝ} (hBc : ∀ ω, Continuous fun t => B t ω) (ρ : TestFun H) :
    ∃ Φ : (ℝ≥0 → ℝ) → ℝ, Measurable Φ ∧
      ∀ ω, Φ (pathOf B ω) = ∫ z, ρ.1 z * hTfwdExt κ (drive κ B ω) T z := by
  have hpm : Measurable[MeasurableSpace.comap (pathOf B) MeasurableSpace.pi] (pathOf B) :=
    Measurable.of_comap_le le_rfl
  have h := @measurable_extPair κ T hMeas hκ4 hκ8 hT Ω
    (MeasurableSpace.comap (pathOf B) MeasurableSpace.pi) B
    (fun t => (measurable_pi_apply t).comp hpm) hBc ρ
  obtain ⟨Φ, hΦ, he⟩ := h.exists_eq_measurable_comp
  exact ⟨Φ, hΦ, fun ω => (congrFun he ω).symm⟩

/-- The random covariance on `U_T = sleComplement` is almost everywhere measurable
(via the jointly measurable version of the trace, TR6). -/
theorem aemeasurable_cov_sleComplement {Ω : Type} [MeasurableSpace Ω] {P : Measure Ω}
    {B : ℝ≥0 → Ω → ℝ} (hB : IsBrownianReal B P) (hκ4 : 4 < κ) (hκ8 : κ < 8) (hT : 0 < T)
    (ρ σ : TestFun H) :
    AEMeasurable (fun ω => zeroGFFTestCov (sleComplement κ B ω T) ρ.1 σ.1) P := by
  obtain ⟨η, -, hηm, hηc, hηeq⟩ := RS.exists_measurable_sleTrace hB (by linarith) hκ8
  set U : Ω → Set ℂ := fun ω => H \ closure (η ω '' Icc 0 T) with hUdef
  have hU : ∀ ω, IsOpen (U ω) ∧ U ω ⊆ H := fun ω =>
    ⟨(isOpen_lt continuous_const Complex.continuous_im).sdiff isClosed_closure, sdiff_subset⟩
  have hE : ∀ j, MeasurableSet {ω | tsupport (K3.testFamily j) ⊆ U ω} := fun j =>
    NonVacuityAddendum.measurableSet_subset_compl_closure_image hηm hηc hT
      (K3.testFamily_mem j).2.1
  refine (K3.measurable_zeroGFFTestCov hU hE ρ σ).aemeasurable.congr ?_
  filter_upwards [hηeq] with ω hω
  show zeroGFFTestCov (H \ closure (η ω '' Icc 0 T)) ρ.1 σ.1 =
    zeroGFFTestCov (H \ closure (sleTrace κ B ω '' Icc 0 T)) ρ.1 σ.1
  rw [(hω.mono Icc_subset_Ici_self).image_eq]

end Meas

theorem norm_cexp_I_mul_le (x : ℝ) : ‖cexp (I * (x : ℂ))‖ = 1 := norm_exp_I_mul_ofReal x

/-- **AD-8, conditional Gaussian step.** `IsCondZeroBoundaryGFFH` with `F = cos ∘ Φ` and
`F = sin ∘ Φ`. -/
theorem integral_cexp_cond {Ω E : Type*} [MeasurableSpace Ω] [MeasurableSpace E]
    {P : Measure Ω} [IsProbabilityMeasure P] {U : Ω → Set ℂ} {Yp : Ω → E}
    {X' : Ω → FieldSample} (hX' : IsCondZeroBoundaryGFFH U Yp X' P) (hU : ∀ ω, IsOpen (U ω))
    (hUH : ∀ ω, U ω ⊆ H) (hYp : AEMeasurable Yp P) (ρ : TestFun H) {Φ : E → ℝ}
    (hΦ : Measurable Φ) (hC : AEMeasurable (fun ω => zeroGFFTestCov (U ω) ρ.1 ρ.1) P) :
    ∫ ω, cexp (I * ((Φ (Yp ω) + pairRaw (X' ω) ρ.1 : ℝ) : ℂ)) ∂P =
      ∫ ω, cexp (I * (Φ (Yp ω) : ℂ) - (zeroGFFTestCov (U ω) ρ.1 ρ.1 : ℂ) / 2) ∂P := by
  have hc := hX'.condCharFun 1 (fun _ => ρ) (fun _ => 1) (fun y => Real.cos (Φ y))
    (Real.measurable_cos.comp hΦ) ⟨1, fun y => Real.abs_cos_le_one _⟩
  have hs := hX'.condCharFun 1 (fun _ => ρ) (fun _ => 1) (fun y => Real.sin (Φ y))
    (Real.measurable_sin.comp hΦ) ⟨1, fun y => Real.abs_sin_le_one _⟩
  simp only [Fin.sum_univ_one, one_mul] at hc hs
  set φ : Ω → ℝ := fun ω => Φ (Yp ω) with hφ
  set p : Ω → ℝ := fun ω => pairRaw (X' ω) ρ.1 with hp
  set C : Ω → ℝ := fun ω => zeroGFFTestCov (U ω) ρ.1 ρ.1 with hCdef
  have hφm : AEMeasurable φ P := hΦ.comp_aemeasurable hYp
  have hpm : Measurable p := measurable_pairRaw_comp hX'.measurable_coord ρ.1
  have hC0 : ∀ ω, 0 ≤ C ω := fun ω => by
    have := K3.zeroGFFTestCov_psd (hU ω) (hUH ω) (fun _ : Fin 1 => ρ) (fun _ => 1)
    simpa using this
  have hE1 : ∀ ω, ‖((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ)‖ ≤ 1 := fun ω => by
    rw [Complex.norm_real, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
    exact Real.exp_le_one_iff.2 (by nlinarith [hC0 ω])
  have hcos : ∀ ω, ‖((Real.cos (φ ω) : ℝ) : ℂ)‖ ≤ 1 := fun ω => by
    rw [Complex.norm_real, Real.norm_eq_abs]; exact Real.abs_cos_le_one _
  have hsin : ∀ ω, ‖((Real.sin (φ ω) : ℝ) : ℂ)‖ ≤ 1 := fun ω => by
    rw [Complex.norm_real, Real.norm_eq_abs]; exact Real.abs_sin_le_one _
  have mcos : AEStronglyMeasurable (fun ω => ((Real.cos (φ ω) : ℝ) : ℂ)) P :=
    (Complex.measurable_ofReal.comp_aemeasurable
      (Real.measurable_cos.comp_aemeasurable hφm)).aestronglyMeasurable
  have msin : AEStronglyMeasurable (fun ω => ((Real.sin (φ ω) : ℝ) : ℂ)) P :=
    (Complex.measurable_ofReal.comp_aemeasurable
      (Real.measurable_sin.comp_aemeasurable hφm)).aestronglyMeasurable
  have mp : AEStronglyMeasurable (fun ω => cexp (I * (p ω : ℂ))) P := by
    fun_prop
  have mE : AEStronglyMeasurable (fun ω => ((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ)) P :=
    (Complex.measurable_ofReal.comp_aemeasurable
      (Real.measurable_exp.comp_aemeasurable (hC.const_mul _))).aestronglyMeasurable
  have i1 : Integrable (fun ω => ((Real.cos (φ ω) : ℝ) : ℂ) * cexp (I * (p ω : ℂ))) P :=
    Integrable.of_bound (mcos.mul mp) 1 (ae_of_all _ fun ω => by
      rw [norm_mul, norm_cexp_I_mul_le, mul_one]; exact hcos ω)
  have i2 : Integrable (fun ω => ((Real.sin (φ ω) : ℝ) : ℂ) * cexp (I * (p ω : ℂ))) P :=
    Integrable.of_bound (msin.mul mp) 1 (ae_of_all _ fun ω => by
      rw [norm_mul, norm_cexp_I_mul_le, mul_one]; exact hsin ω)
  have j1 : Integrable (fun ω => ((Real.cos (φ ω) : ℝ) : ℂ) *
      ((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ)) P :=
    Integrable.of_bound (mcos.mul mE) 1 (ae_of_all _ fun ω => by
      rw [norm_mul]
      exact (mul_le_mul (hcos ω) (hE1 ω) (norm_nonneg _) zero_le_one).trans_eq (one_mul 1))
  have j2 : Integrable (fun ω => ((Real.sin (φ ω) : ℝ) : ℂ) *
      ((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ)) P :=
    Integrable.of_bound (msin.mul mE) 1 (ae_of_all _ fun ω => by
      rw [norm_mul]
      exact (mul_le_mul (hsin ω) (hE1 ω) (norm_nonneg _) zero_le_one).trans_eq (one_mul 1))
  have e1 : ∀ ω, cexp (I * ((φ ω + p ω : ℝ) : ℂ)) =
      ((Real.cos (φ ω) : ℝ) : ℂ) * cexp (I * (p ω : ℂ)) +
        I * (((Real.sin (φ ω) : ℝ) : ℂ) * cexp (I * (p ω : ℂ))) := fun ω => by
    rw [ofReal_add, mul_add, Complex.exp_add, mul_comm I (φ ω : ℂ), Complex.exp_mul_I,
      Complex.ofReal_cos, Complex.ofReal_sin]
    ring
  have e2 : ∀ ω, cexp (I * (φ ω : ℂ) - (C ω : ℂ) / 2) =
      ((Real.cos (φ ω) : ℝ) : ℂ) * ((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ) +
        I * (((Real.sin (φ ω) : ℝ) : ℂ) * ((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ)) := fun ω => by
    rw [show I * (φ ω : ℂ) - (C ω : ℂ) / 2 = (φ ω : ℂ) * I + ((-(1 / 2) * C ω : ℝ) : ℂ) by
      push_cast; ring, Complex.exp_add, Complex.exp_mul_I, Complex.ofReal_exp,
      Complex.ofReal_cos, Complex.ofReal_sin]
    ring
  calc ∫ ω, cexp (I * ((Φ (Yp ω) + pairRaw (X' ω) ρ.1 : ℝ) : ℂ)) ∂P
      = (∫ ω, ((Real.cos (φ ω) : ℝ) : ℂ) * cexp (I * (p ω : ℂ)) ∂P) +
          I * ∫ ω, ((Real.sin (φ ω) : ℝ) : ℂ) * cexp (I * (p ω : ℂ)) ∂P := by
        rw [← integral_const_mul, ← integral_add i1 (i2.const_mul I)]
        exact integral_congr_ae (ae_of_all _ fun ω => e1 ω)
    _ = (∫ ω, ((Real.cos (φ ω) : ℝ) : ℂ) * ((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ) ∂P) +
          I * ∫ ω, ((Real.sin (φ ω) : ℝ) : ℂ) * ((Real.exp (-(1 / 2) * C ω) : ℝ) : ℂ) ∂P := by
        rw [← hc, ← hs]
    _ = ∫ ω, cexp (I * (Φ (Yp ω) : ℂ) - (zeroGFFTestCov (U ω) ρ.1 ρ.1 : ℂ) / 2) ∂P := by
        rw [← integral_const_mul, ← integral_add j1 (j2.const_mul I)]
        exact integral_congr_ae (ae_of_all _ fun ω => (e2 ω).symm)

/-- **Theorem 1.1, addendum (`κ ∈ (4,8)`), assembled (AD-8)** from the proved nodes AD-1, AD-2
(inside K3 C5), K3 C1–C3/C5′/C5, the conditional-GFF linearity, and the three open inputs
`ExtIntStmt` (AD-4, integrability), `ExtMartStmt` (AD-4 + MF-5) and `ExtMeasStmt`
(measurability of `𝔥^ext_T`). -/
theorem theorem1_1_addendum_of_nodes (hInt : ExtIntStmt) (hMart : ExtMartStmt)
    (hMeas : ExtMeasStmt) : theorem1_1_addendum := by
  intro κ T hκ4 hκ8 hT Ω _ P _ B X X' hB hX hX'
  obtain ⟨B', hB'm, hB'c, hB'eq⟩ := CharFun.exists_good_version hB
  have hdrive : ∀ᵐ ω ∂P, drive κ B' ω = drive κ B ω :=
    hB'eq.mono fun ω h => funext fun t => by simp [drive, h]
  have hpath : ∀ᵐ ω ∂P, pathOf B' ω = pathOf B ω :=
    hB'eq.mono fun ω h => funext fun t => h t
  have hU : ∀ ω, IsOpen (sleComplement κ B ω T) := fun ω =>
    (isOpen_lt continuous_const Complex.continuous_im).sdiff isClosed_closure
  have hUH : ∀ ω, sleComplement κ B ω T ⊆ H := fun ω => sdiff_subset
  set Y : Ω → FieldSample := fun ω => ofFun (hTfwdExt κ (drive κ B' ω) T) + X' ω with hY
  have hYae : ∀ᵐ ω ∂P, Y ω = ofFun (hTfwdExt κ (drive κ B ω) T) + X' ω := by
    filter_upwards [hdrive] with ω h
    simp only [hY, h]
  rw [← CharFunRhs.fieldLaw_congr_ae hYae]
  have hInt' : ∀ ρ : TestFun H, ∀ᵐ ω ∂P,
      Integrable fun z => ρ.1 z * hTfwdExt κ (drive κ B' ω) T z := fun ρ => by
    filter_upwards [hInt κ T hκ4 hκ8 hT P B hB ρ, hdrive] with ω h hd
    rw [hd]; exact h
  have hsplit : ∀ ρ : TestFun H, ∀ᵐ ω ∂P, pairRaw (Y ω) ρ.1 =
      (∫ z, ρ.1 z * hTfwdExt κ (drive κ B' ω) T z) + pairRaw (X' ω) ρ.1 := fun ρ => by
    filter_upwards [hInt' ρ] with ω h
    rw [hY, CharFun.pairRaw_add, CharFunRhs.pairRaw_ofFun_of_integrable ρ.2.1.continuous h]
  have hYm : ∀ ρ : TestFun H, Measurable fun ω => pairRaw (Y ω) ρ.1 := fun ρ => by
    have e : (fun ω => pairRaw (Y ω) ρ.1) = fun ω =>
        (ofFun (hTfwdExt κ (drive κ B' ω) T) (volume.withDensity fun z => ENNReal.ofReal (ρ.1 z)) -
          ofFun (hTfwdExt κ (drive κ B' ω) T)
            (volume.withDensity fun z => ENNReal.ofReal (-ρ.1 z))) + pairRaw (X' ω) ρ.1 :=
      funext fun ω => by rw [hY, CharFun.pairRaw_add]; rfl
    rw [e]
    exact ((measurable_ofFun_ext hMeas hκ4 hκ8 hT hB'm hB'c _).sub
      (measurable_ofFun_ext hMeas hκ4 hκ8 hT hB'm hB'c _)).add
      (measurable_pairRaw_comp hX'.measurable_coord ρ.1)
  have hYlin : CharFunFwd.LinearPairingH Y P := by
    intro ρ₁ ρ₂ ρ₃ a h
    filter_upwards [hsplit ρ₁, hsplit ρ₂, hsplit ρ₃, hInt' ρ₁, hInt' ρ₂,
      linearPairingH_of_condGFF hU hUH hX' ρ₁ ρ₂ ρ₃ a h] with ω e1 e2 e3 i1 i2 hl
    rw [e1, e2, e3, CharFunRhs.integral_lin_int i1 i2 a h, hl]
    ring
  refine CharFunFwd.fieldLaw_eq_of_charFun (CharFunFwd.measurable_pairRaw_lhs_fwd κ hX) hYm
    (CharFunFwd.linear_lhs_fwd κ hX) hYlin fun ρ => ?_
  obtain ⟨Φ, hΦm, hΦ⟩ := exists_extPair_path hMeas hκ4 hκ8 hT hB'c ρ
  have hYp : AEMeasurable (pathOf B) P :=
    (measurable_pi_iff.2 hB'm).aemeasurable.congr hpath
  have hC5 := K3.zeroGFFTestCov_sleComplement ⟨hκ4, hκ8⟩ hT hB
  rw [CharFunFwd.charFun_lhs_fwd κ P X hX ρ, ← hMart κ T hκ4 hκ8 hT P B hB ρ]
  symm
  calc ∫ ω, cexp (I * (pairRaw (Y ω) ρ.1 : ℂ)) ∂P
      = ∫ ω, cexp (I * ((Φ (pathOf B ω) + pairRaw (X' ω) ρ.1 : ℝ) : ℂ)) ∂P := by
        refine integral_congr_ae ?_
        filter_upwards [hsplit ρ, hpath] with ω h hp
        rw [h, ← hΦ ω, hp]
    _ = ∫ ω, cexp (I * (Φ (pathOf B ω) : ℂ) -
          (zeroGFFTestCov (sleComplement κ B ω T) ρ.1 ρ.1 : ℂ) / 2) ∂P :=
        integral_cexp_cond hX' hU hUH hYp ρ hΦm (aemeasurable_cov_sleComplement hB hκ4 hκ8 hT ρ ρ)
    _ = _ := by
        refine integral_congr_ae ?_
        filter_upwards [hpath, hdrive, hC5] with ω hp hd hc
        rw [hc ρ ρ, ← hp, hΦ ω, hd]

/-- **Theorem 1.1** (main statement, proved in `Thm11MainFull`, and the addendum) from the three
open addendum inputs. -/
theorem theorem1_1_of_nodes (hInt : ExtIntStmt) (hMart : ExtMartStmt) (hMeas : ExtMeasStmt) :
    theorem1_1 :=
  ⟨Thm11MainFull.theorem1_1_main_proof, theorem1_1_addendum_of_nodes hInt hMart hMeas⟩

end Thm11Asm
end QuantumZipper
