import LQGMetric.Papers.GM.S4.L47MeasFinal

/-!
# GM (4.9): the filtration `𝓕_k = σ(𝓑^•_{t_k}, h|_{𝓑^•_{t_k}}, P|_{[0,s_k]})`

Source: GM = `literature/src/1905.00383/uniqueness-final.tex`, (4.9) (`eqn-nomax-filtration`,
l. 1650–1654): "we will work with the increasing filtration `𝓕_k := σ(𝓑^•_{t_k},
h|_{𝓑^•_{t_k}}, P|_{[0,s_k]})`".

In the model, `gmSigF … k` (`L45Meas.lean`) is GM's `𝓕_k` with the literal generated
σ-algebras (D49). GM's "increasing" holds for the path part surely
(`gm_comap_pathK_mono`: `s_j / s_k` is deterministic), but for `σ(𝓑^•_{t_k}, h|)` only up to
null sets (`𝓑^•_{t_j}` is determined by `(𝓑^•_{t_k}, h|)` through the a.s. locality of `D_h`).
We therefore use the generated filtration `gmFilt k := ⨆_{j ≤ k} 𝓕_j` (a filtration surely) and
show that conditional expectations given `gmFilt k` and given GM's `𝓕_k` agree a.s. as soon as
each `𝓕_j` (`j ≤ k`) is a.s. contained in `𝓕_k` (`gm_condExp_gmFilt_ae_eq`); the a.s.
inclusion reduces to the σ(𝓑^•, h|) part (`gm_sigF_ae_mono`).

* `gmSupFilt`: the filtration `k ↦ ⨆_{j ≤ k} 𝒢 j` of a family `𝒢 j ≤ mΩ`.
* `gm_condExp_ae_eq_of_le_aeSigma`: `G ≤ G' ≤ gmAESigma G` ⇒ `μ[f|G] =ᵐ μ[f|G']`.
* `gmFilt` (on a complete space, `gm_sigF_le`), `gm_le_gmFilt`, `gm_condExp_gmFilt_ae_eq`.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory ProbabilityTheory MeasurableSpace Set Filter
open LQGMetric.Blueprint

namespace LQGMetric.GM

section Abstract
variable {Ω : Type} {mΩ : MeasurableSpace Ω} {μ : Measure Ω}

/-- the filtration `k ↦ ⨆_{j ≤ k} 𝒢 j` generated by a family of sub-σ-algebras -/
def gmSupFilt (𝒢 : ℕ → MeasurableSpace Ω) (h𝒢 : ∀ j, 𝒢 j ≤ mΩ) : Filtration ℕ mΩ where
  seq k := ⨆ (j : ℕ) (_ : j ≤ k), 𝒢 j
  mono' _ _ hkl := iSup₂_le fun j hj => le_iSup₂_of_le (f := fun (j : ℕ) (_ : j ≤ _) => 𝒢 j)
    j (hj.trans hkl) le_rfl
  le' _ := iSup₂_le fun j _ => h𝒢 j

theorem gm_le_supFilt (𝒢 : ℕ → MeasurableSpace Ω) (h𝒢 : ∀ j, 𝒢 j ≤ mΩ) (k : ℕ) :
    𝒢 k ≤ gmSupFilt 𝒢 h𝒢 k :=
  le_iSup₂_of_le (f := fun (j : ℕ) (_ : j ≤ k) => 𝒢 j) k le_rfl le_rfl

/-- conditional expectations given `G` and given any `G'` between `G` and its a.s.-closure
agree a.s. -/
theorem gm_condExp_ae_eq_of_le_aeSigma [IsFiniteMeasure μ] {G G' : MeasurableSpace Ω}
    (hG : G ≤ mΩ) (hGG' : G ≤ G') (hG' : G' ≤ gmAESigma (mΩ := mΩ) G μ) (f : Ω → ℝ) :
    μ[f | G] =ᵐ[μ] μ[f | G'] := by
  by_cases hf : Integrable f μ
  · refine ae_eq_condExp_of_forall_setIntegral_eq (hG'.trans (gm_aeSigma_le G)) hf
      (fun s _ _ => integrable_condExp.integrableOn) (fun s hs _ => ?_)
      ((stronglyMeasurable_condExp.mono hGG').aestronglyMeasurable)
    obtain ⟨t, ht, hst⟩ := gm_measurableSet_aeSigma (hG' s hs)
    rw [setIntegral_congr_set hst, setIntegral_condExp hG hf ht, setIntegral_congr_set hst]
  · rw [condExp_of_not_integrable hf, condExp_of_not_integrable hf]

/-- the generated filtration and the family have a.s. equal conditional expectations when each
`𝒢 j`, `j ≤ k`, is a.s. contained in `𝒢 k` -/
theorem gm_condExp_supFilt_ae_eq [IsFiniteMeasure μ] (𝒢 : ℕ → MeasurableSpace Ω)
    (h𝒢 : ∀ j, 𝒢 j ≤ mΩ) {k : ℕ} (hmono : ∀ j ≤ k, 𝒢 j ≤ gmAESigma (mΩ := mΩ) (𝒢 k) μ)
    (f : Ω → ℝ) : μ[f | 𝒢 k] =ᵐ[μ] μ[f | gmSupFilt 𝒢 h𝒢 k] :=
  gm_condExp_ae_eq_of_le_aeSigma (h𝒢 k) (gm_le_supFilt 𝒢 h𝒢 k) (iSup₂_le hmono) f

end Abstract

/-! ## The path part `P|_{[0,s_k]}` is increasing surely -/

section Path
variable {Ω : Type} [MeasurableSpace Ω]

/-- the deterministic ratio `s_j / s_k = (1 + jε^β)/(1 + kε^β)` -/
def gmSRatio (ε β : ℝ) (j k : ℕ) : ℝ := (1 + j * ε ^ β) / (1 + k * ε ^ β)

theorem gm_sRatio_mem {ε β : ℝ} (hε : 0 ≤ ε ^ β) {j k : ℕ} (hjk : j ≤ k) :
    gmSRatio ε β j k ∈ Icc (0 : ℝ) 1 := by
  have hk : 0 < 1 + (k : ℝ) * ε ^ β := by positivity
  have hjk' : (j : ℝ) ≤ k := by exact_mod_cast hjk
  refine ⟨div_nonneg (by positivity) hk.le, (div_le_one hk).2 ?_⟩
  nlinarith

/-- reparametrization `f ↦ (u ↦ f(c u))` of paths on `[0,1]` -/
def gmReparam (c : ℝ) (hc : c ∈ Icc (0 : ℝ) 1) (f : unitInterval → ℂ) : unitInterval → ℂ :=
  fun u => f ⟨c * u, unitInterval.mul_mem hc u.2⟩

theorem gm_measurable_reparam (c : ℝ) (hc : c ∈ Icc (0 : ℝ) 1) :
    Measurable (gmReparam c hc) :=
  measurable_pi_iff.2 fun _ => measurable_pi_apply _

omit [MeasurableSpace Ω] in
/-- `P|_{[0,s_j]}` is the reparametrized `P|_{[0,s_k]}` -/
theorem gm_pathK_eq_reparam (D : DistC → ContMetric) (h : Ω → DistC) (𝕫 𝕨 : ℂ)
    (η : Ω → C(unitInterval, ℂ)) (ℓ 𝕣 ε β : ℝ) (hε : 0 ≤ ε ^ β) {j k : ℕ} (hjk : j ≤ k) :
    gmPathK D h 𝕫 𝕨 η (s4S D h 𝕫 ℓ 𝕣 ε β j) =
      gmReparam _ (gm_sRatio_mem hε hjk) ∘ gmPathK D h 𝕫 𝕨 η (s4S D h 𝕫 ℓ 𝕣 ε β k) := by
  funext ω u
  simp only [gmPathK, gmReparam, Function.comp_apply, s4S, gmSRatio]
  congr 1
  have hk : (1 + (k : ℝ) * ε ^ β) ≠ 0 := by positivity
  field_simp

/-- **`P|_{[0,s_k]}` is increasing in `k`** (surely) -/
theorem gm_comap_pathK_mono (D : DistC → ContMetric) (h : Ω → DistC) (𝕫 𝕨 : ℂ)
    (η : Ω → C(unitInterval, ℂ)) (ℓ 𝕣 ε β : ℝ) (hε : 0 ≤ ε ^ β) {j k : ℕ} (hjk : j ≤ k) :
    MeasurableSpace.comap (gmPathK D h 𝕫 𝕨 η (s4S D h 𝕫 ℓ 𝕣 ε β j)) inferInstance ≤
      MeasurableSpace.comap (gmPathK D h 𝕫 𝕨 η (s4S D h 𝕫 ℓ 𝕣 ε β k)) inferInstance := by
  rw [gm_pathK_eq_reparam D h 𝕫 𝕨 η ℓ 𝕣 ε β hε hjk, ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono (gm_measurable_reparam _ _).comap_le

end Path

/-! ## GM's filtration (4.9) on a complete probability space -/

section Filt
variable {γ : ℝ} {D : DistC → ContMetric} {c' : ℝ → ℝ} {Ω : Type} [MeasurableSpace Ω]
  {P : Measure Ω} [IsProbabilityMeasure P] [P.IsComplete] {h : Ω → DistC}

/-- GM's `𝓕_k` (4.9) at index `k` -/
abbrev gmSigFk (D : DistC → ContMetric) (h : Ω → DistC) (𝕫 𝕨 : ℂ) (η : Ω → C(unitInterval, ℂ))
    (ℓ 𝕣 ε β : ℝ) (k : ℕ) : MeasurableSpace Ω :=
  gmSigF D h 𝕫 𝕨 η (s4S D h 𝕫 ℓ 𝕣 ε β k) (s4T D h 𝕫 ℓ 𝕣 ε β k)

/-- **GM (4.9) as a filtration**: `gmFilt k = ⨆_{j ≤ k} 𝓕_j` on a complete probability space -/
def gmFilt (h38 : DFGPSLem3_8) (hγ : 0 < γ) (hγ2 : γ < 2) (hD : IsWeakLQGMetric γ D c')
    (hh : IsWholePlaneGFF h P) {𝕫 𝕨 : ℂ} {η : Ω → C(unitInterval, ℂ)}
    (hη : ∀ᵐ ω ∂P, IsGeod01 (D (h ω)) 𝕫 𝕨 (η ω) ∧ UniqueGeod (D (h ω)) 𝕫 𝕨)
    (ℓ 𝕣 ε β : ℝ) : Filtration ℕ ‹MeasurableSpace Ω› :=
  gmSupFilt (gmSigFk D h 𝕫 𝕨 η ℓ 𝕣 ε β) (gm_sigF_le h38 hγ hγ2 hD hh hη ℓ 𝕣 ε β)

omit [IsProbabilityMeasure P] [P.IsComplete] in
/-- the a.s. monotonicity of GM's `𝓕_k` reduces to that of `σ(𝓑^•_{t_k}, h|_{𝓑^•_{t_k}})` -/
theorem gm_sigF_ae_mono (D : DistC → ContMetric) (h : Ω → DistC) (𝕫 𝕨 : ℂ)
    (η : Ω → C(unitInterval, ℂ)) (ℓ 𝕣 ε β : ℝ) (hε : 0 ≤ ε ^ β) {j k : ℕ} (hjk : j ≤ k)
    (hk : gmSigFk D h 𝕫 𝕨 η ℓ 𝕣 ε β k ≤ ‹MeasurableSpace Ω›)
    (hA : gmSigA D h 𝕫 (s4T D h 𝕫 ℓ 𝕣 ε β j) ≤
      gmAESigma (gmSigA D h 𝕫 (s4T D h 𝕫 ℓ 𝕣 ε β k)) P) :
    gmSigFk D h 𝕫 𝕨 η ℓ 𝕣 ε β j ≤ gmAESigma (gmSigFk D h 𝕫 𝕨 η ℓ 𝕣 ε β k) P := by
  have hAk : gmSigA D h 𝕫 (s4T D h 𝕫 ℓ 𝕣 ε β k) ≤ gmSigFk D h 𝕫 𝕨 η ℓ 𝕣 ε β k := le_sup_left
  refine sup_le (fun s hs => ?_) ((gm_comap_pathK_mono D h 𝕫 𝕨 η ℓ 𝕣 ε β hε hjk).trans
    ((le_sup_right : _ ≤ gmSigFk D h 𝕫 𝕨 η ℓ 𝕣 ε β k).trans (gm_le_aeSigma hk)))
  obtain ⟨t, ht, hst⟩ := gm_measurableSet_aeSigma (hA s hs)
  refine (MeasurableSpace.measurableSet_inf).2 ⟨?_, t, hAk t ht, by rwa [inter_univ]⟩
  exact (gm_aeSigma_le _ s (hA s hs))

/-- **conditional expectations given `gmFilt k` are GM's `P[· | 𝓕_k]`** (a.s.), given the a.s.
monotonicity of `σ(𝓑^•_{t_j}, h|_{𝓑^•_{t_j}})` -/
theorem gm_condExp_gmFilt_ae_eq (h38 : DFGPSLem3_8) (hγ : 0 < γ) (hγ2 : γ < 2)
    (hD : IsWeakLQGMetric γ D c') (hh : IsWholePlaneGFF h P) {𝕫 𝕨 : ℂ}
    {η : Ω → C(unitInterval, ℂ)}
    (hη : ∀ᵐ ω ∂P, IsGeod01 (D (h ω)) 𝕫 𝕨 (η ω) ∧ UniqueGeod (D (h ω)) 𝕫 𝕨)
    (ℓ 𝕣 ε β : ℝ) (hε : 0 ≤ ε ^ β) {k : ℕ}
    (hA : ∀ j ≤ k, gmSigA D h 𝕫 (s4T D h 𝕫 ℓ 𝕣 ε β j) ≤
      gmAESigma (gmSigA D h 𝕫 (s4T D h 𝕫 ℓ 𝕣 ε β k)) P) (f : Ω → ℝ) :
    P[f | gmSigFk D h 𝕫 𝕨 η ℓ 𝕣 ε β k] =ᵐ[P]
      P[f | gmFilt h38 hγ hγ2 hD hh hη ℓ 𝕣 ε β k] :=
  gm_condExp_supFilt_ae_eq _ _ (fun j hj => gm_sigF_ae_mono D h 𝕫 𝕨 η ℓ 𝕣 ε β hε hj
    (gm_sigF_le h38 hγ hγ2 hD hh hη ℓ 𝕣 ε β k) (hA j hj)) f

end Filt

end LQGMetric.GM
