import LQGMetric.Papers.GM.S4.JordanBasic

/-!
# Hit events of the boundary of a random closed set

Toward D94 (measurable choice of the centres `z_y` of GM L4.15 Step 3, l. 2161: "in a manner
depending only on `(𝓑^•_{t_k}, h|_{𝓑^•_{t_k}})`"): for a random closed set `A`, the hit
events `{∂A ∩ U ≠ ∅}` (`U` open) belong to `σ(A)` (`setSigma A`, generated by the hit events
of `A`), hence to `localSigma h A` (`setSigma A ≤ hullSigma h A n` for every `n`). This is the
Effros measurability of `ω ↦ ∂A(ω)`, the input of a dyadic-descent measurable selection of a
point of `∂𝓑^•_{t_k}` (own elementary proof: `∂A ∩ U ≠ ∅` iff some ball `B_r(p) ⊆ U` with `p`
in a countable dense set and `r` rational meets `A` and contains a point `p'` of the dense set
with `B_{1/(n+1)}(p') ∩ A = ∅`).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Set Metric
open LQGMetric.Blueprint

namespace LQGMetric.GM

/-- **`{∂A ∩ U ≠ ∅}` is `σ(A)`-measurable** for a random closed set `A` and open `U` -/
theorem p412f_frontier_hit_meas {Ω : Type} (A : Ω → Set ℂ) (hA : ∀ ω, IsClosed (A ω))
    {U : Set ℂ} (hU : IsOpen U) :
    MeasurableSet[setSigma A] {ω | (frontier (A ω) ∩ U).Nonempty} := by
  obtain ⟨S, hSc, hSd⟩ := TopologicalSpace.exists_countable_dense ℂ
  have hhit : ∀ V : Set ℂ, IsOpen V → MeasurableSet[setSigma A] {ω | (A ω ∩ V).Nonempty} :=
    fun V hV => MeasurableSpace.measurableSet_generateFrom ⟨V, hV, rfl⟩
  have heq : {ω | (frontier (A ω) ∩ U).Nonempty} =
      ⋃ p ∈ S, ⋃ r : ℚ, ⋃ (_ : 0 < (r : ℝ) ∧ ball p r ⊆ U),
        ({ω | (A ω ∩ ball p r).Nonempty} ∩
          ⋃ p' ∈ S ∩ ball p r, ⋃ n : ℕ, {ω | (A ω ∩ ball p' (1 / (n + 1))).Nonempty}ᶜ) := by
    ext ω
    simp only [mem_setOf_eq, mem_iUnion, mem_inter_iff, mem_compl_iff, exists_prop]
    constructor
    · rintro ⟨x, hxf, hxU⟩
      obtain ⟨ρ, hρ, hρU⟩ := Metric.isOpen_iff.1 hU x hxU
      obtain ⟨r, hr0, hrρ⟩ := exists_rat_btwn (show (0 : ℝ) < ρ / 2 by positivity)
      obtain ⟨p, hpS, hpx⟩ := hSd.exists_mem_open isOpen_ball ⟨x, (mem_ball_self (show (0 : ℝ) < r
        from by exact_mod_cast hr0) : x ∈ ball x r)⟩
      have hxp : x ∈ ball p r := by rw [mem_ball, dist_comm]; exact hpx
      have hsub : ball p r ⊆ U := fun y hy => hρU (by
        rw [mem_ball] at hy hpx ⊢; linarith [dist_triangle y p x])
      refine ⟨p, hpS, r, ⟨by exact_mod_cast hr0, hsub⟩,
        ⟨x, (hA ω).frontier_subset hxf, hxp⟩, ?_⟩
      -- a point of the dense set outside `A`, near `x`
      have hxc : x ∈ closure (A ω)ᶜ := by
        have := frontier_subset_closure (s := (A ω)ᶜ) (by rwa [frontier_compl]); exact this
      obtain ⟨y, hyB, hyA⟩ := mem_closure_iff.1 hxc _ isOpen_ball hxp
      obtain ⟨s, hs, hsB⟩ := Metric.isOpen_iff.1 (isOpen_ball.inter (hA ω).isOpen_compl) y
        ⟨hyB, hyA⟩
      obtain ⟨p', hp'S, hp'y⟩ := hSd.exists_mem_open isOpen_ball
        ⟨y, (mem_ball_self (half_pos hs) : y ∈ ball y (s / 2))⟩
      obtain ⟨n, hn⟩ := exists_nat_one_div_lt (half_pos hs)
      have hp'B : ball p' (1 / (n + 1)) ⊆ ball y s := fun z hz => by
        rw [mem_ball] at hz hp'y ⊢
        have : (1 : ℝ) / (n + 1) < s / 2 := hn
        linarith [dist_triangle z p' y]
      refine ⟨p', ⟨hp'S, (hsB (mem_ball.2 (by rw [mem_ball] at hp'y; linarith))).1⟩, n, ?_⟩
      rintro ⟨z, hzA, hz⟩
      exact (hsB (hp'B hz)).2 hzA
    · rintro ⟨p, -, r, ⟨hr0, hsub⟩, ⟨a, haA, hap⟩, p', ⟨-, hp'B⟩, n, hn⟩
      have hp'A : p' ∉ A ω := fun h => hn ⟨p', h, mem_ball_self (by positivity)⟩
      obtain ⟨x, hxB, hxf⟩ := jb_inter_frontier_nonempty (hA ω) (convex_ball p r).isPreconnected
        hp'B hp'A hap haA
      exact ⟨x, hxf, hsub hxB⟩
  rw [heq]
  refine MeasurableSet.biUnion hSc fun p _ => MeasurableSet.iUnion fun r =>
    MeasurableSet.iUnion fun _ => (hhit _ isOpen_ball).inter ?_
  refine MeasurableSet.biUnion (hSc.mono inter_subset_left) fun p' _ =>
    MeasurableSet.iUnion fun n => (hhit _ isOpen_ball).compl

/-- `σ(A) ≤ σ(A, h|_A)` -/
theorem p412f_setSigma_le_localSigma {Ω : Type} (h : Ω → DistC) (A : Ω → Set ℂ) :
    setSigma A ≤ localSigma h A :=
  le_iInf fun _ => le_sup_left

end LQGMetric.GM
