import LQGMetric.Papers.GM.S4.P412iStop

/-!
# CONF l. 1302: `σ^ε_{τ,𝕣}` is determined by the data visible inside `𝓑^•_T` (deterministic part)

Source: CONF = Gwynne–Miller, *Confluence of geodesics in LQG*, arXiv:1905.00381,
`literature/src/1905.00381/confluence-final.tex`, l. 1258–1260 ("Since `E_r(z)` is determined by
`h|_{A_{2r,5r}(z)}`, it follows that `ρ^n_𝕣(z)` is a stopping time for the filtration generated by
`h|_{B_{5r}(z)}`") and l. 1300–1302 ("so that `𝓑^•_{σ}` contains `B_{6ρ(z)}(z)` for each
`z ∈ B_{ε𝕣}(𝓑^•_s)`. Since each `ρ(z)` is a stopping time …, if `τ` is a stopping time … then so is
`σ^ε_{τ,𝕣}`"). Used by GM L4.15 Step 4, l. 2189 (D98 (b2), packet P-stop).

The recursions `confRho`, `confRK`, `confSigma` depend on `ω` only through the metric `D_h` and the
membership `ω ∈ E_r(z)`. We restate them with an abstract event predicate `E r z`
(`p412iRho`, `p412iRK`, `p412iSig`; definitional copies, `p412i_confSigma_eq`) and prove the
deterministic core of CONF's argument:

* `p412i_rho_attained`: `ρ^{n+1}`, when finite, is attained (the dyadic radii are discrete);
* **`p412i_rho_congr`**: `ρ^n` only depends on the events `E_r(z)` with `r ≤ ρ^n(z)`;
* **`p412i_sig_congr`**: if two metrics have the same filled balls up to radius `T`, `𝓑^•_T ⊆ U`
  (`U` bounded) and the event predicates agree for all `(r, z)` with `cl B_{5r}(z) ⊆ U`, then
  `σ < T` for the first implies equal `σ`'s (and equal `𝓑^•_σ`, `p412i_sigBall_congr`).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Set Filter Metric
open scoped ENNReal
open LQGMetric.Blueprint

namespace LQGMetric.GM

/-- `ρ^n_R(z)` (CONF (3.13)) for an abstract event predicate `E r z` (copy of `confRho`) -/
def p412iRho (E : ℝ → ℂ → Prop) (R : ℝ) (z : ℂ) : ℕ → ℝ≥0∞
  | 0 => ENNReal.ofReal R
  | n + 1 => ⨅ (k : ℤ) (_ : 6 * p412iRho E R z n ≤ ENNReal.ofReal ((2 : ℝ) ^ k * R))
      (_ : E ((2 : ℝ) ^ k * R) z), ENNReal.ofReal ((2 : ℝ) ^ k * R)

/-- `R^ε_R(K)` (CONF (3.16)) for an abstract event predicate (copy of `confRK`) -/
def p412iRK (E : ℝ → ℂ → Prop) (N : ℕ) (R ε : ℝ) (K : Set ℂ) : ℝ≥0∞ :=
  6 * (⨆ z ∈ gridPts (ε * R / 4) ∩ thickening (ε * R) K, p412iRho E (ε * R) z N) +
    ENNReal.ofReal (ε * R)

/-- `σ^ε_{t,R}` (CONF (3.17)) for a metric `d` and an abstract event predicate (copy of
`confSigma`) -/
def p412iSig (d : ContMetric) (z₀ : ℂ) (E : ℝ → ℂ → Prop) (N : ℕ) (R ε t : ℝ) : ℝ≥0∞ :=
  ⨅ (s' : ℝ) (_ : t < s') (_ : enbhd (p412iRK E N R ε (filledBall d z₀ t)) (filledBall d z₀ t) ⊆
      filledBall d z₀ s'), ENNReal.ofReal s'

section Eq
variable {Ω : Type} [MeasurableSpace Ω]

theorem p412i_confRho_eq (ξ : ℝ) (cc : ℝ → ℝ) (D : DistC → ContMetric) (P : Measure Ω)
    (h : Ω → DistC) (p : CONFParams) (R : ℝ) (z : ℂ) (n : ℕ) (ω : Ω) :
    confRho ξ cc D P h p R z n ω = p412iRho (fun r z => ω ∈ confE ξ cc D P h p r z) R z n := by
  induction n with
  | zero => rfl
  | succ n ih => simp only [confRho, p412iRho, ih]

theorem p412i_confRK_eq (ξ : ℝ) (cc : ℝ → ℝ) (D : DistC → ContMetric) (P : Measure Ω)
    (h : Ω → DistC) (p : CONFParams) (R ε : ℝ) (K : Set ℂ) (ω : Ω) :
    confRK ξ cc D P h p R ε K ω =
      p412iRK (fun r z => ω ∈ confE ξ cc D P h p r z) (confN p ε) R ε K := by
  simp only [confRK, p412iRK, p412i_confRho_eq]

/-- `confSigma` is `p412iSig` at the metric `D_h` and the events `E_r(z)` -/
theorem p412i_confSigma_eq (ξ : ℝ) (cc : ℝ → ℝ) (D : DistC → ContMetric) (P : Measure Ω)
    (h : Ω → DistC) (p : CONFParams) (z₀ : ℂ) (R ε s : ℝ) (ω : Ω) :
    confSigma ξ cc D P h p z₀ R ε s ω =
      p412iSig (D (h ω)) z₀ (fun r z => ω ∈ confE ξ cc D P h p r z) (confN p ε) R ε s := by
  simp only [confSigma, p412iSig, p412i_confRK_eq]

end Eq

variable {E E₁ E₂ : ℝ → ℂ → Prop} {R : ℝ} {z : ℂ}

theorem p412i_rho_six_le (n : ℕ) : 6 * p412iRho E R z n ≤ p412iRho E R z (n + 1) :=
  le_iInf₂ fun _ hk => le_iInf fun _ => hk

theorem p412i_rho_le_succ (n : ℕ) : p412iRho E R z n ≤ p412iRho E R z (n + 1) :=
  le_trans (le_mul_of_one_le_left' (by norm_num)) (p412i_rho_six_le n)

theorem p412i_rho_pos (hR : 0 < R) (n : ℕ) : 0 < p412iRho E R z n := by
  induction n with
  | zero => exact ENNReal.ofReal_pos.2 hR
  | succ n ih =>
    exact lt_of_lt_of_le (ENNReal.mul_pos (by norm_num) ih.ne').bot_lt (p412i_rho_six_le n)

/-- **`ρ^{n+1}` is attained when finite** (the admissible dyadic exponents are bounded below) -/
theorem p412i_rho_attained (hR : 0 < R) (n : ℕ) (hfin : p412iRho E R z (n + 1) < ⊤) :
    ∃ k : ℤ, 6 * p412iRho E R z n ≤ ENNReal.ofReal ((2 : ℝ) ^ k * R) ∧ E ((2 : ℝ) ^ k * R) z ∧
      p412iRho E R z (n + 1) = ENNReal.ofReal ((2 : ℝ) ^ k * R) := by
  set S : Set ℤ := {k | 6 * p412iRho E R z n ≤ ENNReal.ofReal ((2 : ℝ) ^ k * R) ∧
    E ((2 : ℝ) ^ k * R) z} with hS
  have hne : S.Nonempty := by
    by_contra h0
    rw [not_nonempty_iff_eq_empty] at h0
    apply hfin.ne
    refine iInf_eq_top.2 fun k => iInf_eq_top.2 fun h6 => iInf_eq_top.2 fun hE => ?_
    exact absurd (show k ∈ S from ⟨h6, hE⟩) (h0 ▸ notMem_empty k)
  have hpos := p412i_rho_pos (E := E) (z := z) hR n
  have hnfin : p412iRho E R z n < ⊤ := lt_of_le_of_lt (p412i_rho_le_succ n) hfin
  set c : ℝ := (p412iRho E R z n).toReal with hc
  have hc0 : 0 < c := ENNReal.toReal_pos hpos.ne' hnfin.ne
  obtain ⟨m, hm⟩ := exists_pow_lt_of_lt_one (div_pos hc0 hR) (by norm_num : (1 / 2 : ℝ) < 1)
  have hbdd : BddBelow S := by
    refine ⟨-(m : ℤ), fun k hk => ?_⟩
    by_contra hlt
    replace hlt := not_le.1 hlt
    have h1 : (2 : ℝ) ^ k ≤ (2 : ℝ) ^ (-(m : ℤ)) :=
      zpow_le_zpow_right₀ (by norm_num) hlt.le
    have h2 : (2 : ℝ) ^ (-(m : ℤ)) = (1 / 2) ^ m := by
      rw [zpow_neg, zpow_natCast, one_div, inv_pow]
    have h3 : (2 : ℝ) ^ k * R < c := by
      have := (lt_div_iff₀ hR).1 (h2 ▸ hm)
      nlinarith
    have h4 : ENNReal.ofReal c ≤ ENNReal.ofReal ((2 : ℝ) ^ k * R) := by
      rw [hc, ENNReal.ofReal_toReal hnfin.ne]
      exact le_trans (le_mul_of_one_le_left' (by norm_num)) hk.1
    have := (ENNReal.ofReal_le_ofReal_iff (by positivity)).1 h4
    linarith
  obtain ⟨k₀, hk₀S, hk₀min⟩ := Int.exists_least_of_bdd
    (let ⟨b, hb⟩ := hbdd; ⟨b, fun k hk => hb hk⟩) hne
  refine ⟨k₀, hk₀S.1, hk₀S.2, le_antisymm (iInf₂_le_of_le k₀ hk₀S.1 (iInf_le _ hk₀S.2)) ?_⟩
  refine le_iInf₂ fun k h6 => le_iInf fun hE => ?_
  exact ENNReal.ofReal_le_ofReal (mul_le_mul_of_nonneg_right
    (zpow_le_zpow_right₀ (by norm_num) (hk₀min k ⟨h6, hE⟩)) hR.le)

/-- **`ρ^n(z)` only depends on the events `E_r(z)`, `r ≤ ρ^n(z)`** (CONF l. 1260) -/
theorem p412i_rho_congr (hR : 0 < R) (n : ℕ) (hfin : p412iRho E₁ R z n < ⊤)
    (hE : ∀ r : ℝ, 0 < r → ENNReal.ofReal r ≤ p412iRho E₁ R z n → (E₁ r z ↔ E₂ r z)) :
    p412iRho E₂ R z n = p412iRho E₁ R z n := by
  induction n with
  | zero => rfl
  | succ n ih =>
    have hle := p412i_rho_le_succ (E := E₁) (R := R) (z := z) n
    have ihn := ih (lt_of_le_of_lt hle hfin) fun r hr h' => hE r hr (h'.trans hle)
    obtain ⟨k₀, h6, hE₀, heq⟩ := p412i_rho_attained hR n hfin
    have hr₀ : 0 < (2 : ℝ) ^ k₀ * R := by positivity
    refine le_antisymm ?_ ?_
    · rw [heq]
      refine iInf₂_le_of_le k₀ (by rw [p412iRho] at *; rw [ihn]; exact h6) (iInf_le _ ?_)
      exact (hE _ hr₀ heq.ge).1 hE₀
    · refine le_iInf₂ fun k h6' => le_iInf fun hE' => ?_
      by_contra hlt
      replace hlt := not_le.1 hlt
      have hk : 0 < (2 : ℝ) ^ k * R := by positivity
      have hE₁k := (hE _ hk hlt.le).2 hE'
      rw [ihn] at h6'
      exact absurd (iInf₂_le_of_le k h6' (iInf_le _ hE₁k)) (not_le.2 hlt)

/-- `R^ε(K)` only depends on the visible events (consequence of `p412i_rho_congr`) -/
theorem p412i_RK_congr {N : ℕ} {ε : ℝ} (hεR : 0 < ε * R) {K : Set ℂ}
    (hfin : p412iRK E₁ N R ε K < ⊤)
    (hE : ∀ z ∈ gridPts (ε * R / 4) ∩ thickening (ε * R) K, ∀ r : ℝ, 0 < r →
      ENNReal.ofReal r ≤ p412iRho E₁ (ε * R) z N → (E₁ r z ↔ E₂ r z)) :
    p412iRK E₂ N R ε K = p412iRK E₁ N R ε K := by
  have hsup : (⨆ z ∈ gridPts (ε * R / 4) ∩ thickening (ε * R) K, p412iRho E₁ (ε * R) z N) < ⊤ := by
    have h1 := (ENNReal.add_lt_top.1 hfin).1
    by_contra htop
    rw [not_lt_top_iff] at htop
    rw [htop] at h1
    exact absurd h1 (by norm_num)
  unfold p412iRK
  congr 2
  refine iSup_congr fun z => iSup_congr fun hz => ?_
  exact p412i_rho_congr hεR N (lt_of_le_of_lt (le_iSup₂ (f := fun z (_ : z ∈ _) =>
    p412iRho E₁ (ε * R) z N) z hz) hsup) (hE z hz)

/-- the balls `cl B_{5r}(z)`, `r ≤ ρ(z)`, at grid points `z ∈ B_{εR}(K)` lie in `B_{R^ε(K)}(K)` -/
theorem p412i_ball_subset_enbhd {N : ℕ} {ε : ℝ} {K : Set ℂ}
    (hfin : p412iRK E N R ε K < ⊤) {z : ℂ}
    (hz : z ∈ gridPts (ε * R / 4) ∩ thickening (ε * R) K) {r : ℝ}
    (hrρ : ENNReal.ofReal r ≤ p412iRho E (ε * R) z N) :
    closedBall z (5 * r) ⊆ enbhd (p412iRK E N R ε K) K := by
  intro x hx
  have hρle : p412iRho E (ε * R) z N ≤
      ⨆ z ∈ gridPts (ε * R / 4) ∩ thickening (ε * R) K, p412iRho E (ε * R) z N :=
    le_iSup₂ (f := fun z (_ : z ∈ _) => p412iRho E (ε * R) z N) z hz
  have hρfin : p412iRho E (ε * R) z N ≠ ⊤ := by
    intro htop
    have h1 := (ENNReal.add_lt_top.1 hfin).1
    rw [htop, top_le_iff] at hρle
    rw [hρle] at h1
    exact absurd h1 (by norm_num)
  have hzK : Metric.infEDist z K < ENNReal.ofReal (ε * R) :=
    mem_thickening_iff_infEDist_lt.1 hz.2
  have hxz : edist x z ≤ 5 * p412iRho E (ε * R) z N := by
    rw [edist_dist]
    calc ENNReal.ofReal (dist x z) ≤ ENNReal.ofReal (5 * r) :=
          ENNReal.ofReal_le_ofReal (mem_closedBall.1 hx)
      _ = 5 * ENNReal.ofReal r := by
          rw [ENNReal.ofReal_mul (by norm_num)]; norm_num
      _ ≤ 5 * p412iRho E (ε * R) z N := by gcongr
  show Metric.infEDist x K < p412iRK E N R ε K
  calc Metric.infEDist x K ≤ Metric.infEDist z K + edist x z :=
        Metric.infEDist_le_infEDist_add_edist
    _ ≤ Metric.infEDist z K + 5 * p412iRho E (ε * R) z N := by gcongr
    _ < ENNReal.ofReal (ε * R) + 5 * p412iRho E (ε * R) z N :=
        ENNReal.add_lt_add_right (ENNReal.mul_ne_top (by norm_num) hρfin) hzK
    _ ≤ 6 * (⨆ z ∈ gridPts (ε * R / 4) ∩ thickening (ε * R) K, p412iRho E (ε * R) z N) +
          ENNReal.ofReal (ε * R) := by
        rw [add_comm]
        gcongr ?_ + _
        calc 5 * p412iRho E (ε * R) z N ≤ 6 * p412iRho E (ε * R) z N := by gcongr; norm_num
          _ ≤ _ := by gcongr

/-- **CONF l. 1302, deterministic core**: `σ < T` for `(d₁, E₁)` and agreement of the filled
balls up to `T`, of the events `E_r(z)` with `cl B_{5r}(z) ⊆ U ⊇ 𝓑^•_T` (`U` bounded) give
`σ(d₂, E₂) = σ(d₁, E₁)` -/
theorem p412i_sig_congr {d₁ d₂ : ContMetric} {z₀ : ℂ} {N : ℕ} {ε t T : ℝ} {U : Set ℂ}
    (hεR : 0 < ε * R) (htT : t ≤ T)
    (hfb : ∀ u ≤ T, filledBall d₂ z₀ u = filledBall d₁ z₀ u)
    (hK : (filledBall d₁ z₀ t).Nonempty) (hTU : filledBall d₁ z₀ T ⊆ U)
    (hUb : Bornology.IsBounded U)
    (hE : ∀ r : ℝ, 0 < r → ∀ z, closedBall z (5 * r) ⊆ U → (E₁ r z ↔ E₂ r z))
    (hσ : p412iSig d₁ z₀ E₁ N R ε t < ENNReal.ofReal T) :
    p412iSig d₂ z₀ E₂ N R ε t = p412iSig d₁ z₀ E₁ N R ε t := by
  set K := filledBall d₁ z₀ t with hKdef
  have hK₂ : filledBall d₂ z₀ t = K := hfb t htT
  obtain ⟨s'', hts, hsub, hsT⟩ : ∃ s'', t < s'' ∧
      enbhd (p412iRK E₁ N R ε K) K ⊆ filledBall d₁ z₀ s'' ∧
      ENNReal.ofReal s'' < ENNReal.ofReal T := by
    simp only [p412iSig, iInf_lt_iff] at hσ
    obtain ⟨s'', h1, h2, h3⟩ := hσ
    exact ⟨s'', h1, h2, h3⟩
  have hsT' : s'' < T := (ENNReal.ofReal_lt_ofReal_iff'.1 hsT).1
  have hU : enbhd (p412iRK E₁ N R ε K) K ⊆ U :=
    hsub.trans ((gm_filledBall_mono _ _ hsT'.le).trans hTU)
  have hfin : p412iRK E₁ N R ε K < ⊤ := by
    by_contra htop
    rw [not_lt_top_iff] at htop
    apply NormedSpace.unbounded_univ ℝ ℂ
    refine hUb.subset fun x _ => hU ?_
    show Metric.infEDist x K < p412iRK E₁ N R ε K
    rw [htop]
    exact lt_top_iff_ne_top.2 (Metric.infEDist_ne_top hK)
  have hRK : p412iRK E₂ N R ε K = p412iRK E₁ N R ε K :=
    p412i_RK_congr hεR hfin fun z hz r hr hrρ =>
      hE r hr z ((p412i_ball_subset_enbhd hfin hz hrρ).trans hU)
  have hadm : ∀ s', s' ≤ T → (enbhd (p412iRK E₂ N R ε (filledBall d₂ z₀ t))
      (filledBall d₂ z₀ t) ⊆ filledBall d₂ z₀ s' ↔
      enbhd (p412iRK E₁ N R ε K) K ⊆ filledBall d₁ z₀ s') := by
    intro s' hs'
    rw [hK₂, hRK, hfb s' hs']
  refine le_antisymm ?_ ?_
  · refine le_of_forall_gt_imp_ge_of_dense fun c hc => ?_
    have hlt : p412iSig d₁ z₀ E₁ N R ε t < min c (ENNReal.ofReal T) := lt_min hc hσ
    obtain ⟨s', h1, h2, h34⟩ : ∃ s', t < s' ∧ enbhd (p412iRK E₁ N R ε K) K ⊆
        filledBall d₁ z₀ s' ∧ ENNReal.ofReal s' < min c (ENNReal.ofReal T) := by
      simpa only [p412iSig, iInf_lt_iff, exists_prop] using hlt
    obtain ⟨h3, h4⟩ := lt_min_iff.1 h34
    have hs'T : s' ≤ T := (ENNReal.ofReal_lt_ofReal_iff'.1 h4).1.le
    exact (iInf₂_le_of_le s' h1 (iInf_le _ ((hadm s' hs'T).2 h2))).trans h3.le
  · refine le_iInf₂ fun s' h1 => le_iInf fun h2 => ?_
    by_cases hs'T : s' ≤ T
    · exact iInf₂_le_of_le s' h1 (iInf_le _ ((hadm s' hs'T).1 h2))
    · exact hσ.le.trans (ENNReal.ofReal_le_ofReal (not_le.1 hs'T).le)

end LQGMetric.GM
