import LQGMetric.Papers.GM.S4.Setup

/-!
# `τ_R` is a filled-ball stopping time (decision D49, package E1 of `decisions/DEC-E.md` §3)

GM l. 854 / CONF l. 477 take for granted that the hitting time
`τ_R = inf {s > 0 : 𝓑^•_s(z; D_h) ⊄ B_R(z)}` is a stopping time for the filtration generated by
`(𝓑^•_s, h|_{𝓑^•_s})`. With the generated filtration and optional times of D49 this is a sure
statement, proved here:

* `gm_filledBall_isClosed`: `𝓑^•_s(z; D)` is closed (its complement is the union of the unbounded
  components of the open set `ℂ ∖ cl 𝓑_s`, each of which is open since `ℂ` is locally connected);
* `gm_setSigma_hit_closed`: for a random closed set `A` and a closed `F`, the hitting event
  `{A ∩ F ≠ ∅}` lies in `σ(A)` (the standard Effros-σ-algebra fact, e.g. Molchanov, *Theory of
  Random Sets*, §1.1.1: the Effros and Fell σ-algebras agree on closed sets of a locally compact
  separable space; we follow that proof: `F = ⋃ₘ F ∩ cl B_m(0)` and, for compact `K`,
  `{A ∩ K ≠ ∅} = ⋂ₙ {A ∩ B_{1/(n+1)}(K) ≠ ∅}` by the finite-intersection property);
* `gm_tauR_lt_iff`: `τ_R < t ⟺ ∃ q ∈ ℚ, 0 < q < t, 𝓑^•_q ⊄ B_R(z)`;
* `gm_tauR_isStop`: `τ_R` is a filled-ball stopping time (surely, for every `D` and `h`), and
  `gm_S4_12_uncond`: `s_k`, `t_k` of GM (4.6) are filled-ball stopping times (GM.S4.12 without
  hypotheses).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Filter Topology Set
open LQGMetric.Blueprint

namespace LQGMetric.GM

/-- filled metric balls are closed -/
theorem gm_filledBall_isClosed (D : ContMetric) (z : ℂ) (s : ℝ) :
    IsClosed (filledBall D z s) := by
  set X := closure (ballM D z s)
  have hU : IsOpen Xᶜ := isClosed_closure.isOpen_compl
  rw [← isOpen_compl_iff, isOpen_iff_mem_nhds]
  intro x hx
  have hx' : x ∉ X ∧ ¬ Bornology.IsBounded (connectedComponentIn Xᶜ x) := by
    simp only [filledBall, mem_compl_iff, mem_union, mem_ofPred_eq, not_or, not_and] at hx
    exact ⟨hx.1, hx.2 hx.1⟩
  refine Filter.mem_of_superset ((hU.connectedComponentIn (x := x)).mem_nhds
    (mem_connectedComponentIn hx'.1)) ?_
  intro y hy
  have hyU : y ∈ Xᶜ := connectedComponentIn_subset _ _ hy
  have heq := connectedComponentIn_eq hy
  simp only [filledBall, mem_compl_iff, mem_union, mem_ofPred_eq, not_or, not_and]
  exact ⟨hyU, fun _ => heq ▸ hx'.2⟩

section Sigma
variable {Ω : Type} [MeasurableSpace Ω]

omit [MeasurableSpace Ω] in
theorem gm_setSigma_hit_open (A : Ω → Set ℂ) {U : Set ℂ} (hU : IsOpen U) :
    MeasurableSet[setSigma A] {ω | (A ω ∩ U).Nonempty} :=
  MeasurableSpace.measurableSet_generateFrom ⟨U, hU, rfl⟩

omit [MeasurableSpace Ω] in
/-- hitting a compact set is a `σ(A)`-event when `A` is a random closed set -/
theorem gm_setSigma_hit_compact (A : Ω → Set ℂ) (hA : ∀ ω, IsClosed (A ω)) {K : Set ℂ}
    (hK : IsCompact K) : MeasurableSet[setSigma A] {ω | (A ω ∩ K).Nonempty} := by
  have e : {ω | (A ω ∩ K).Nonempty} =
      ⋂ n : ℕ, {ω | (A ω ∩ Metric.thickening (1 / ((n : ℝ) + 1)) K).Nonempty} := by
    ext ω
    simp only [mem_ofPred_eq, mem_iInter]
    constructor
    · rintro ⟨x, hxA, hxK⟩ n
      exact ⟨x, hxA, Metric.self_subset_thickening (by positivity) K hxK⟩
    · intro hn
      set T : ℕ → Set ℂ := fun n => A ω ∩ Metric.cthickening (1 / ((n : ℝ) + 1)) K
      have hT := IsCompact.nonempty_iInter_of_sequence_nonempty_isCompact_isClosed T
        (fun n => inter_subset_inter_right _ (Metric.cthickening_mono (by
          apply one_div_le_one_div_of_le (by positivity); push_cast; linarith) K))
        (fun n => (hn n).mono (inter_subset_inter_right _ (Metric.thickening_subset_cthickening _ _)))
        (hK.cthickening.inter_left (hA ω))
        (fun n => (hA ω).inter Metric.isClosed_cthickening)
      obtain ⟨x, hx⟩ := hT
      simp only [T, mem_iInter, mem_inter_iff] at hx
      refine ⟨x, (hx 0).1, ?_⟩
      rw [← hK.isClosed.closure_eq,
        Metric.closure_eq_iInter_cthickening' K (range fun n : ℕ => 1 / ((n : ℝ) + 1))]
      · simp only [mem_iInter, mem_range, forall_exists_index]
        rintro δ n rfl
        exact (hx n).2
      · intro ε hε
        obtain ⟨n, hn⟩ := exists_nat_one_div_lt hε
        exact ⟨_, ⟨n, rfl⟩, by positivity, hn.le⟩
  rw [e]
  exact MeasurableSet.iInter fun n => gm_setSigma_hit_open A Metric.isOpen_thickening

omit [MeasurableSpace Ω] in
/-- **Effros step** (DEC-E §3, E1): hitting a closed set is a `σ(A)`-event when `A` is a random
closed set -/
theorem gm_setSigma_hit_closed {A : Ω → Set ℂ} {F : Set ℂ} (hA : ∀ ω, IsClosed (A ω))
    (hF : IsClosed F) : MeasurableSet[setSigma A] {ω | (A ω ∩ F).Nonempty} := by
  have e : {ω | (A ω ∩ F).Nonempty} =
      ⋃ m : ℕ, {ω | (A ω ∩ (F ∩ Metric.closedBall 0 m)).Nonempty} := by
    ext ω
    simp only [mem_ofPred_eq, mem_iUnion]
    constructor
    · rintro ⟨x, hxA, hxF⟩
      obtain ⟨m, hm⟩ := exists_nat_ge (dist x 0)
      exact ⟨m, x, hxA, hxF, hm⟩
    · rintro ⟨m, hm⟩
      exact hm.mono (inter_subset_inter_right _ inter_subset_left)
  rw [e]
  exact MeasurableSet.iUnion fun m =>
    gm_setSigma_hit_compact A hA ((isCompact_closedBall 0 _).inter_left hF)

omit [MeasurableSpace Ω] in
/-- `σ(A) ⊆ σ(A, h|_A)` -/
theorem gm_setSigma_le_localSigma (h : Ω → DistC) (A : Ω → Set ℂ) :
    setSigma A ≤ localSigma h A :=
  le_iInf fun _ => le_sup_left

/-- the set defining `τ_R` is nonempty (`D` is real-valued) -/
theorem gm_tauR_set_nonempty (D : ContMetric) (z : ℂ) (R : ℝ) :
    {s : ℝ | 0 < s ∧ ¬ filledBall D z s ⊆ Metric.ball z R}.Nonempty := by
  set w : ℂ := z + (|R| : ℝ)
  refine ⟨D.1 (z, w) + 1, ?_, fun hsub => ?_⟩
  · have h1 := D.2.triangle z w z
    rw [D.2.self_eq_zero, D.2.symm w z] at h1
    linarith
  · have hw : w ∈ filledBall D z (D.1 (z, w) + 1) :=
      Or.inl (subset_closure (show D.1 (z, w) < D.1 (z, w) + 1 by linarith))
    have := hsub hw
    rw [Metric.mem_ball, dist_eq_norm] at this
    simp [w, Complex.norm_real] at this
    exact absurd this (not_lt.mpr (le_abs_self R))

omit [MeasurableSpace Ω] in
/-- `τ_R < t` iff some rational `0 < q < t` has `𝓑^•_q ⊄ B_R(z)` -/
theorem gm_tauR_lt_iff (D : DistC → ContMetric) (h : Ω → DistC) (z : ℂ) (R : ℝ) (ω : Ω)
    (t : ℝ) : tauR D h z R ω < t ↔
      ∃ q : ℚ, 0 < (q : ℝ) ∧ (q : ℝ) < t ∧ ¬ filledBall (D (h ω)) z q ⊆ Metric.ball z R := by
  unfold tauR
  constructor
  · intro ht
    obtain ⟨s, ⟨hs0, hs⟩, hst⟩ := exists_lt_of_csInf_lt (gm_tauR_set_nonempty _ z R) ht
    obtain ⟨q, hsq, hqt⟩ := exists_rat_btwn hst
    exact ⟨q, hs0.trans hsq, hqt, fun hsub => hs ((gm_filledBall_mono _ z hsq.le).trans hsub)⟩
  · rintro ⟨q, hq0, hqt, hq⟩
    exact lt_of_le_of_lt (csInf_le ⟨0, fun s hs => hs.1.le⟩ ⟨hq0, hq⟩) hqt

omit [MeasurableSpace Ω] in
/-- **`τ_R` is a filled-ball stopping time** (GM l. 854, CONF l. 477; D49), surely, for every
`D` and `h` -/
theorem gm_tauR_isStop (D : DistC → ContMetric) (h : Ω → DistC) (z : ℂ) (R : ℝ) :
    IsFilledBallStoppingTime D h z (tauR D h z R) := by
  intro t
  have e : {ω | tauR D h z R ω < t} = ⋃ q : ℚ, ⋃ (_ : 0 < (q : ℝ) ∧ (q : ℝ) < t),
      {ω | (filledBall (D (h ω)) z q ∩ (Metric.ball z R)ᶜ).Nonempty} := by
    ext ω
    simp only [mem_ofPred_eq, mem_iUnion, gm_tauR_lt_iff, exists_prop, and_assoc,
      inter_compl_nonempty_iff]
  rw [e]
  refine MeasurableSet.iUnion fun q => MeasurableSet.iUnion fun hq => ?_
  have h1 := gm_setSigma_hit_closed (A := fun ω => filledBall (D (h ω)) z q) (F := (Metric.ball z R)ᶜ)
    (fun ω => gm_filledBall_isClosed _ z q) Metric.isOpen_ball.isClosed_compl
  have hle : setSigma (fun ω => filledBall (D (h ω)) z q) ≤ filledBallSigma D h z t :=
    (gm_setSigma_le_localSigma h _).trans
      (le_iSup₂ (f := fun (s : ℝ) (_ : s ≤ t) =>
        localSigma h (fun ω => filledBall (D (h ω)) z s)) (q : ℝ) hq.2.le)
  exact hle _ h1

omit [MeasurableSpace Ω] in
/-- **GM.S4.12, unconditional**: `s_k` and `t_k` of GM (4.6) are filled-ball stopping times
(`ε > 0`; `𝔲 = τ_{ℓ𝕣}(𝕫)` is one by `gm_tauR_isStop`) -/
theorem gm_S4_12_uncond (D : DistC → ContMetric) (h : Ω → DistC) (𝕫 : ℂ) (ℓ 𝕣 ε β : ℝ)
    (hε : 0 < ε) (k : ℕ) :
    IsFilledBallStoppingTime D h 𝕫 (s4S D h 𝕫 ℓ 𝕣 ε β k) ∧
      IsFilledBallStoppingTime D h 𝕫 (s4T D h 𝕫 ℓ 𝕣 ε β k) :=
  gm_S4_12 (gm_tauR_isStop D h 𝕫 (ℓ * 𝕣)) hε k

end Sigma

end LQGMetric.GM
