import ReflectedGMS.Forms.TraceDiscountedOccupation
import Mathlib.Probability.Independence.InfinitePi

/-!
# One-step shift of the embedded chain and its holding times

This file proves that deleting the first embedded-chain state and the first
holding time preserves the conditional holding kernel and restarts the chain
from its one-step transition law.
-/

set_option autoImplicit false

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace ReflectedGMS.FullNetworkForm

open ReflectedWalk

variable {S : Type*} [MeasurableSpace S] [Countable S]
  [MeasurableSingletonClass S]

/-- The first coordinate together with the tail beginning at coordinate one. -/
def firstAndTail (t : ℕ → ℝ) : ℝ × (ℕ → ℝ) :=
  (t 0, MarkovChain.walkShift 1 t)

theorem measurable_firstAndTail : Measurable firstAndTail :=
  (measurable_pi_apply 0).prodMk (MarkovChain.measurable_walkShift 1)

/-- Deleting coordinates before `k` from an infinite product leaves the
product of the correspondingly shifted one-coordinate laws. -/
theorem infinitePi_map_walkShift {A : Type*} [MeasurableSpace A]
    (μ : ℕ → Measure A) [∀ n, IsProbabilityMeasure (μ n)] (k : ℕ) :
    (Measure.infinitePi μ).map (MarkovChain.walkShift k) =
      Measure.infinitePi fun n => μ (k + n) := by
  change (Measure.infinitePi μ).map (fun ω i => ω (k + i)) = _
  exact Measure.map_infinitePi_infinitePi_of_inj
    (P := μ) (f := fun n : ℕ => k + n) (add_right_injective k)

set_option warn.classDefReducibility false in
/-- The sigma algebra generated by a block of sequence coordinates. -/
private def holdingBlockSigma (I : Set ℕ) : MeasurableSpace (ℕ → ℝ) :=
  ⨆ i ∈ I, MeasurableSpace.comap (fun e : ℕ → ℝ => e i) inferInstance

private theorem measurable_eval_holdingBlockSigma {I : Set ℕ} {i : ℕ} (hi : i ∈ I) :
    Measurable[holdingBlockSigma I] fun e : ℕ → ℝ => e i :=
  Measurable.mono (measurable_iff_comap_le.mpr le_rfl)
    (le_iSup_of_le i (le_iSup_of_le hi le_rfl)) le_rfl

private theorem indepFun_expSeq_of_disjoint {I J : Set ℕ} (hIJ : Disjoint I J)
    {A B : Type*} [MeasurableSpace A] [MeasurableSpace B]
    {f : (ℕ → ℝ) → A} {g : (ℕ → ℝ) → B}
    (hf : Measurable[holdingBlockSigma I] f)
    (hg : Measurable[holdingBlockSigma J] g) :
    IndepFun f g ReflectedWalk.expSeq := by
  have hcoord : iIndepFun (fun (i : ℕ) (e : ℕ → ℝ) => e i) ReflectedWalk.expSeq := by
    rw [iIndepFun_iff_map_fun_eq_infinitePi_map fun i => measurable_pi_apply i]
    simp only [ReflectedWalk.expSeq, Measure.infinitePi_map_eval]
    exact Measure.map_id
  have hle : ∀ i : ℕ, MeasurableSpace.comap (fun e : ℕ → ℝ => e i) inferInstance ≤
      (inferInstance : MeasurableSpace (ℕ → ℝ)) :=
    fun i => measurable_iff_comap_le.mp (measurable_pi_apply i)
  have h := indep_iSup_of_disjoint hle hcoord.iIndep hIJ
  change Indep (MeasurableSpace.comap _ _) (MeasurableSpace.comap _ _)
    ReflectedWalk.expSeq
  exact indep_of_indep_of_le_right
    (indep_of_indep_of_le_left h (measurable_iff_comap_le.mp hf))
    (measurable_iff_comap_le.mp hg)

private theorem measurable_walkShift_holdingBlockSigma (k : ℕ) :
    Measurable[holdingBlockSigma (Set.Ici k)] (MarkovChain.walkShift (S := ℝ) k) :=
  (@measurable_pi_iff (ℕ → ℝ) ℕ (fun _ => ℝ) (holdingBlockSigma (Set.Ici k)) _ _).mpr
    fun i => measurable_eval_holdingBlockSigma
      (Set.mem_Ici.mpr (Nat.le_add_right k i))

/-- The first unit exponential and the remaining unit-exponential sequence
are independent. -/
private theorem expSeq_map_firstAndTail :
    ReflectedWalk.expSeq.map firstAndTail =
      (expMeasure 1).prod ReflectedWalk.expSeq := by
  have hind : IndepFun (fun e : ℕ → ℝ => e 0) (MarkovChain.walkShift 1)
      ReflectedWalk.expSeq :=
    indepFun_expSeq_of_disjoint (I := {0}) (J := Set.Ici 1)
      (Set.disjoint_singleton_left.mpr (by simp))
      (measurable_eval_holdingBlockSigma (Set.mem_singleton 0))
      (measurable_walkShift_holdingBlockSigma 1)
  change ReflectedWalk.expSeq.map
      (fun e : ℕ → ℝ => (e 0, MarkovChain.walkShift 1 e)) = _
  rw [hind.map_prod_eq_prod_map_map (measurable_pi_apply 0).aemeasurable
    (MarkovChain.measurable_walkShift 1).aemeasurable]
  simp only [ReflectedWalk.expSeq]
  rw [infinitePi_map_walkShift (fun _ : ℕ => expMeasure 1) 1,
    Measure.infinitePi_map_eval]

/-- Conditionally on an embedded path, deleting the first holding time gives
the holding kernel associated with the shifted embedded path. -/
theorem holdingKernel_map_walkShift {w : S → ℝ} (hw : ∀ z, 0 < w z)
    (y : ℕ → S) :
    (holdingKernel w y).map (MarkovChain.walkShift 1) =
      holdingKernel w (MarkovChain.walkShift 1 y) := by
  letI (n : ℕ) : IsProbabilityMeasure (expMeasure (w (y n))) :=
    isProbabilityMeasure_expMeasure (hw (y n))
  rw [holdingKernel_apply hw, holdingKernel_apply hw,
    infinitePi_map_walkShift (fun n => expMeasure (w (y n))) 1]
  rfl

/-- The first holding time is independent of the shifted holding tail,
conditionally on the embedded path. -/
theorem holdingKernel_map_firstAndTail {w : S → ℝ} (hw : ∀ z, 0 < w z)
    (y : ℕ → S) :
    (holdingKernel w y).map firstAndTail =
      (expMeasure (w (y 0))).prod
        (holdingKernel w (MarkovChain.walkShift 1 y)) := by
  let scale : (ℕ → S) → (ℕ → ℝ) → (ℕ → ℝ) :=
    fun z e n => e n / w (z n)
  have hscale (z : ℕ → S) : Measurable (scale z) := by
    unfold scale
    fun_prop
  have hhold (z : ℕ → S) :
      holdingKernel w z = ReflectedWalk.expSeq.map (scale z) := by
    rw [holdingKernel_apply hw, ← ReflectedWalk.expSeq_map_div
      (fun n => w (z n)) (fun n => hw (z n))]
  rw [hhold y, Measure.map_map measurable_firstAndTail (hscale y)]
  have hcomp : firstAndTail ∘ scale y =
      Prod.map (fun r : ℝ => r / w (y 0))
        (scale (MarkovChain.walkShift 1 y)) ∘ firstAndTail := by
    funext e
    apply Prod.ext
    · rfl
    · funext n
      rfl
  rw [hcomp]
  calc
    ReflectedWalk.expSeq.map
        (Prod.map (fun r : ℝ => r / w (y 0))
          (scale (MarkovChain.walkShift 1 y)) ∘ firstAndTail) =
        (ReflectedWalk.expSeq.map firstAndTail).map
          (Prod.map (fun r : ℝ => r / w (y 0))
            (scale (MarkovChain.walkShift 1 y))) := by
          exact (Measure.map_map
            ((measurable_id.div_const (w (y 0))).prodMap
              (hscale (MarkovChain.walkShift 1 y))) measurable_firstAndTail).symm
    _ = ((expMeasure 1).prod ReflectedWalk.expSeq).map
          (Prod.map (fun r : ℝ => r / w (y 0))
            (scale (MarkovChain.walkShift 1 y))) := by rw [expSeq_map_firstAndTail]
    _ = (expMeasure (w (y 0))).prod
          (holdingKernel w (MarkovChain.walkShift 1 y)) := by
      calc
        ((expMeasure 1).prod ReflectedWalk.expSeq).map
            (Prod.map (fun r : ℝ => r / w (y 0))
              (scale (MarkovChain.walkShift 1 y))) =
            ((expMeasure 1).map (fun r : ℝ => r / w (y 0))).prod
              (ReflectedWalk.expSeq.map (scale (MarkovChain.walkShift 1 y))) := by
                simpa only [id_eq] using
                  (Measure.map_prod_map (expMeasure 1) ReflectedWalk.expSeq
                    (measurable_id.div_const (w (y 0)))
                    (hscale (MarkovChain.walkShift 1 y))).symm
        _ = _ := by
          rw [ReflectedWalk.Existence.expMeasure_one_map_div (hw (y 0)),
            ← hhold (MarkovChain.walkShift 1 y)]

/-- The joint embedded-chain/holding law shifts in one step to the chain
restarted from its one-step marginal, with its matching holding kernel. -/
theorem chainLaw_compProd_map_jointWalkShift
    (κ : Kernel S S) [IsMarkovKernel κ] (w : S → ℝ) (hw : ∀ z, 0 < w z)
    (x : S) :
    (MarkovChain.chainLaw κ x ⊗ₘ holdingKernel w).map
        (Prod.map (MarkovChain.walkShift 1) (MarkovChain.walkShift 1)) =
      ((MarkovChain.pathKernel κ ∘ₘ κ x) ⊗ₘ holdingKernel w) := by
  rw [MarkovChain.compProd_map_prod_of_kernel_map
    (MarkovChain.chainLaw κ x) (holdingKernel w) (holdingKernel w)
    (MarkovChain.walkShift 1) (MarkovChain.walkShift 1)
    (MarkovChain.measurable_walkShift 1) (MarkovChain.measurable_walkShift 1)
    (holdingKernel_map_walkShift hw)]
  rw [MarkovChain.chainLaw_map_walkShift, MarkovChain.chainLaw_marginal_one]

/-- Nonnegative-integrand form of the simultaneous one-step disintegration:
after deleting the first state and holding time, first sample the next state
from `κ x`, then a fresh joint chain/holding path from that state. -/
theorem lintegral_chainLaw_compProd_jointWalkShift
    (κ : Kernel S S) [IsMarkovKernel κ] (w : S → ℝ) (hw : ∀ z, 0 < w z)
    (x : S) {H : ((ℕ → S) × (ℕ → ℝ)) → ℝ≥0∞} (hH : Measurable H) :
    (∫⁻ p, H (MarkovChain.walkShift 1 p.1, MarkovChain.walkShift 1 p.2)
        ∂(MarkovChain.chainLaw κ x ⊗ₘ holdingKernel w)) =
      ∫⁻ y, ∫⁻ p, H p ∂(MarkovChain.chainLaw κ y ⊗ₘ holdingKernel w) ∂κ x := by
  let shiftPair : ((ℕ → S) × (ℕ → ℝ)) → ((ℕ → S) × (ℕ → ℝ)) :=
    Prod.map (MarkovChain.walkShift 1) (MarkovChain.walkShift 1)
  have hshift : Measurable shiftPair :=
    (MarkovChain.measurable_walkShift 1).prodMap (MarkovChain.measurable_walkShift 1)
  change (∫⁻ p, H (shiftPair p)
      ∂(MarkovChain.chainLaw κ x ⊗ₘ holdingKernel w)) = _
  rw [← lintegral_map hH hshift]
  change (∫⁻ p, H p ∂(MarkovChain.chainLaw κ x ⊗ₘ holdingKernel w).map shiftPair) = _
  rw [chainLaw_compProd_map_jointWalkShift κ w hw x,
    Measure.lintegral_compProd hH]
  have hm : Measurable fun p : ℕ → S =>
      ∫⁻ t, H (p, t) ∂holdingKernel w p :=
    Measurable.lintegral_kernel_prod_right' hH
  change (∫⁻ p, ∫⁻ t, H (p, t) ∂holdingKernel w p
      ∂(MarkovChain.pathKernel κ ∘ₖ κ) x) = _
  rw [Kernel.lintegral_comp _ _ _ hm]
  simp_rw [MarkovChain.pathKernel_apply, Measure.lintegral_compProd hH]

/-- The first holding time factors from every nonnegative measurable
functional of the shifted joint path.  This is the renewal-ready form of the
one-step disintegration. -/
theorem lintegral_firstHolding_mul_jointWalkShift
    (κ : Kernel S S) [IsMarkovKernel κ] (w : S → ℝ) (hw : ∀ z, 0 < w z)
    (x : S) {h : ℝ → ℝ≥0∞} (hh : Measurable h)
    {F : ((ℕ → S) × (ℕ → ℝ)) → ℝ≥0∞} (hF : Measurable F) :
    (∫⁻ p, h (p.2 0) *
        F (MarkovChain.walkShift 1 p.1, MarkovChain.walkShift 1 p.2)
        ∂(MarkovChain.chainLaw κ x ⊗ₘ holdingKernel w)) =
      (∫⁻ t, h t ∂expMeasure (w x)) *
        ∫⁻ y, ∫⁻ p, F p ∂(MarkovChain.chainLaw κ y ⊗ₘ holdingKernel w) ∂κ x := by
  have hmeas : Measurable fun p : (ℕ → S) × (ℕ → ℝ) =>
      h (p.2 0) * F (MarkovChain.walkShift 1 p.1, MarkovChain.walkShift 1 p.2) := by
    exact (hh.comp ((measurable_pi_apply 0).comp measurable_snd)).mul
      (hF.comp ((MarkovChain.measurable_walkShift 1).comp measurable_fst |>.prodMk
        ((MarkovChain.measurable_walkShift 1).comp measurable_snd)))
  rw [Measure.lintegral_compProd hmeas]
  have hinner (y : ℕ → S) :
      (∫⁻ t, h (t 0) * F (MarkovChain.walkShift 1 y, MarkovChain.walkShift 1 t)
          ∂holdingKernel w y) =
        (∫⁻ r, h r ∂expMeasure (w (y 0))) *
          ∫⁻ t, F (MarkovChain.walkShift 1 y, t)
            ∂holdingKernel w (MarkovChain.walkShift 1 y) := by
    let G : ℝ × (ℕ → ℝ) → ℝ≥0∞ :=
      fun q => h q.1 * F (MarkovChain.walkShift 1 y, q.2)
    have hG : Measurable G :=
      (hh.comp measurable_fst).mul
        (hF.comp (measurable_const.prodMk measurable_snd))
    change (∫⁻ t, G (firstAndTail t) ∂holdingKernel w y) = _
    rw [← lintegral_map hG measurable_firstAndTail,
      holdingKernel_map_firstAndTail hw y]
    exact lintegral_prod_mul
      (μ := expMeasure (w (y 0))) (ν := holdingKernel w (MarkovChain.walkShift 1 y))
      hh.aemeasurable
      (hF.comp (measurable_const.prodMk measurable_id)).aemeasurable
  rw [lintegral_congr hinner]
  have hstart := MarkovChain.chainLaw_ae_start κ x
  rw [lintegral_congr_ae (by
    filter_upwards [hstart] with y hy
    rw [hy])]
  have htailMeas : Measurable fun y : ℕ → S =>
      ∫⁻ t, F (MarkovChain.walkShift 1 y, t)
        ∂holdingKernel w (MarkovChain.walkShift 1 y) := by
    have hm : Measurable fun z : ℕ → S => ∫⁻ t, F (z, t) ∂holdingKernel w z :=
      Measurable.lintegral_kernel_prod_right' hF
    exact hm.comp (MarkovChain.measurable_walkShift 1)
  rw [lintegral_const_mul _ htailMeas]
  congr 1
  rw [← lintegral_chainLaw_compProd_jointWalkShift κ w hw x hF]
  symm
  have hshiftF : Measurable fun p : (ℕ → S) × (ℕ → ℝ) =>
      F (MarkovChain.walkShift 1 p.1, MarkovChain.walkShift 1 p.2) := by
    exact hF.comp
      (((MarkovChain.measurable_walkShift 1).comp measurable_fst).prodMk
        ((MarkovChain.measurable_walkShift 1).comp measurable_snd))
  rw [Measure.lintegral_compProd hshiftF]
  apply lintegral_congr
  intro y
  let G : (ℕ → ℝ) → ℝ≥0∞ := fun t => F (MarkovChain.walkShift 1 y, t)
  have hG : Measurable G := hF.comp (measurable_const.prodMk measurable_id)
  change (∫⁻ b, G (MarkovChain.walkShift 1 b) ∂holdingKernel w y) =
    ∫⁻ t, G t ∂holdingKernel w (MarkovChain.walkShift 1 y)
  rw [← lintegral_map hG (MarkovChain.measurable_walkShift 1),
    holdingKernel_map_walkShift hw y]

end ReflectedGMS.FullNetworkForm
