import ReflectedGMS.Forms.CountableResolventCore
import ReflectedGMS.Forms.CompactCoreAlgebra
import ReflectedGMS.Forms.CompactVertexSpace
import Mathlib.MeasureTheory.Measure.Regular
import Mathlib.MeasureTheory.Measure.Support
import Mathlib.MeasureTheory.Measure.Sum
import Mathlib.MeasureTheory.Measure.Dirac.Basic
import Mathlib.Topology.Algebra.InfiniteSum.ENNReal
import ReflectedGMS.Forms.HilbertEnergySpace
import ReflectedGMS.Forms.FullNetworkForm
import Mathlib.MeasureTheory.Function.StronglyMeasurable.Lemmas
import Mathlib.MeasureTheory.Function.LpSeminorm.Basic
import Mathlib.MeasureTheory.Integral.Lebesgue.Countable
import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-!
# The compact space generated by vertex resolvent potentials

This file specializes the existing compact evaluation closure to the countable
family of finite rational combinations of discount-one vertex potentials.  The
resulting continuous energy algebra is uniformly dense and dense in the full
Hilbert graph norm.  No process realization or path regularity is asserted here.
-/

set_option autoImplicit false

open Set MeasureTheory Topology

namespace ReflectedGMS.ResolventCompactSpace

open FullNetworkForm

variable {V : Type*} [DecidableEq V]

/-- The countable coordinate index: finite rational combinations of vertices. -/
abbrev Index (V : Type*) := CountableResolventCoreIndex V

/-- The bounded coordinate represented by a finite rational combination of
discount-one vertex occupation potentials. -/
noncomputable abbrev feature (G : ReflectedWalk.ConductanceGraph V) (m : V → ℝ) :
    Index V → V → ℝ :=
  countableResolventCoreFeature G m

/-- The explicit uniform bound used for each resolvent coordinate. -/
noncomputable abbrev bound : Index V → ℝ :=
  countableResolventCoreBound

theorem feature_abs_le (G : ReflectedWalk.ConductanceGraph V) (m : V → ℝ)
    (hm : ∀ v, 0 < m v) (q : Index V) (x : V) :
    |feature G m q x| ≤ bound q :=
  countableResolventCoreFeature_abs_le G m hm q x

/-- The actual compact evaluation closure generated by the resolvent core and
vertex indicators. -/
abbrev Space (G : ReflectedWalk.ConductanceGraph V) (m : V → ℝ)
    (hm : ∀ v, 0 < m v) :=
  CompactVertexSpace.Space (feature G m) bound (feature_abs_le G m hm)

/-- The canonical embedding of the original vertex set. -/
noncomputable abbrev vertex (G : ReflectedWalk.ConductanceGraph V) (m : V → ℝ)
    (hm : ∀ v, 0 < m v) : V → Space G m hm :=
  CompactVertexSpace.vertex (feature G m) bound (feature_abs_le G m hm)

theorem vertex_injective (G : ReflectedWalk.ConductanceGraph V) (m : V → ℝ)
    (hm : ∀ v, 0 < m v) : Function.Injective (vertex G m hm) :=
  CompactVertexSpace.vertex_injective (feature G m) bound (feature_abs_le G m hm)

/-- The continuous coordinate for one finite rational potential combination. -/
noncomputable abbrev coordinate (G : ReflectedWalk.ConductanceGraph V) (m : V → ℝ)
    (hm : ∀ v, 0 < m v) (q : Index V) : C(Space G m hm, ℝ) :=
  CompactVertexSpace.coordinate (feature G m) bound (feature_abs_le G m hm) q

@[simp] theorem coordinate_vertex (G : ReflectedWalk.ConductanceGraph V) (m : V → ℝ)
    (hm : ∀ v, 0 < m v) (q : Index V) (x : V) :
    coordinate G m hm q (vertex G m hm x) =
      q.sum fun y a => (a : ℝ) * vertexOccupationPotential G m 1 x y := by
  rw [CompactVertexSpace.coordinate_vertex]
  exact countableResolventCoreFeature_eq_sum G m q x

/-- The individual discount-one potential is one of the continuous coordinates. -/
noncomputable abbrev potentialCoordinate (G : ReflectedWalk.ConductanceGraph V)
    (m : V → ℝ) (hm : ∀ v, 0 < m v) (y : V) : C(Space G m hm, ℝ) :=
  coordinate G m hm (Finsupp.single y 1)

@[simp] theorem potentialCoordinate_vertex (G : ReflectedWalk.ConductanceGraph V)
    (m : V → ℝ) (hm : ∀ v, 0 < m v) (x y : V) :
    potentialCoordinate G m hm y (vertex G m hm x) =
      vertexOccupationPotential G m 1 x y := by
  rw [show potentialCoordinate G m hm y (vertex G m hm x) =
      (Finsupp.single y (1 : ℚ)).sum fun z a =>
        (a : ℝ) * vertexOccupationPotential G m 1 x z from
    coordinate_vertex G m hm (Finsupp.single y 1) x]
  simp

end ReflectedGMS.ResolventCompactSpace
