import ReflectedGMS.GeomTop.GMSTopologyBounds
import ReflectedGMS.GeomTop.GMSInclusion
import Mathlib.Util.AssertNoSorry

/-!
# `τ_sing` restricted to GMS's configurations is GMS's topology (Proposition 2.5, (2.6))

Manuscript `work/geomtop/manuscript-text.txt:433-456`: on the class `C_GMS` of spatially locally
finite configurations, the subspace topology of the geometric topology `τ_sing` (the metric
topology of `d_sing`, Definition 2.1) is the topology `τ_GMS` of GMS's metric `d^CC`:

* `GeomTop.isEmbedding_toSing`: the inclusion `toSing : GMSSpace → SingSpace` is a topological
  embedding;
* `GeomTop.topology_gmsSpace_eq_induced`: `τ_GMS` is the topology induced by `τ_sing`;
* `GeomTop.measurableSpace_gmsSpace_eq_comap`: consequently GMS's Borel σ-algebra is the trace of
  `B_sing` (the trace-σ-algebra assertion of Proposition 2.5).

Both topologies are the ones generated by the open balls of the respective (extended) metrics, as
in `GMS/Theorem116Statement.lean` and `GeomTop/Statement.lean`; the balls of `d_sing` are centred at
arbitrary points of `C_sing`, not only at GMS configurations.  The proof is the manuscript's:
around a GMS configuration, `d_sing(H,·)` small forces `d^CC(H,·)` small and conversely
(`GMSTopologyBounds`), and the triangle inequalities (`GMSTopologyTriangle`) turn these local
comparisons into equality of the generated topologies.  The two metrics need not agree numerically.
-/

set_option autoImplicit false

open MeasureTheory Set Filter Topology Metric
open scoped ENNReal NNReal

namespace ReflectedGMS.GeomTop

open GMS GMSTopology

/-- The inclusion `C_GMS → C_sing` is continuous: the preimage of a `d_sing`-ball (centred at an
arbitrary point of `C_sing`) is `d^CC`-open. -/
theorem continuous_toSing : Continuous toSing := by
  refine continuous_generateFrom_iff.2 ?_
  rintro _ ⟨H₀, ε, hε, rfl⟩
  refine isOpen_of_forall_dCC fun H hH => ?_
  have hH' : dSing H₀.1 H.1 < ε := hH
  obtain ⟨δ, hδ, hspec⟩ :=
    exists_dCC_lt_imp_dSing_lt (finite_restrict_ball H.2) (tsub_pos_of_lt hH')
  refine ⟨δ, hδ, fun H'' hH'' => ?_⟩
  show dSing H₀.1 H''.1 < ε
  calc dSing H₀.1 H''.1 ≤ dSing H₀.1 H.1 + dSing H.1 H''.1 := dSing_triangle _ _ _
    _ < dSing H₀.1 H.1 + (ε - dSing H₀.1 H.1) :=
        ENNReal.add_lt_add_left hH'.ne_top (hspec H''.1 hH'')
    _ = ε := add_tsub_cancel_of_le hH'.le

/-- Every `d^CC`-ball is open for the topology induced by `τ_sing`. -/
theorem induced_toSing_le :
    TopologicalSpace.induced toSing inferInstance ≤ (inferInstance : TopologicalSpace GMSSpace) := by
  refine le_generateFrom ?_
  rintro _ ⟨H₀, ε, hε, rfl⟩
  refine (@isOpen_iff_forall_mem_open GMSSpace
    (TopologicalSpace.induced toSing inferInstance) _).2 fun H hH => ?_
  have hH' : CellConfig.dCC H₀.1 H.1 < ε := hH
  obtain ⟨δ, hδ, hspec⟩ :=
    exists_dSing_lt_imp_dCC_lt (finite_restrict_ball H.2) (tsub_pos_of_lt hH')
  refine ⟨toSing ⁻¹' {H' : SingSpace | dSing (toSing H).1 H'.1 < δ}, fun H'' hH'' => ?_,
    isOpen_induced (TopologicalSpace.isOpen_generateFrom_of_mem ⟨toSing H, δ, hδ, rfl⟩), ?_⟩
  · show CellConfig.dCC H₀.1 H''.1 < ε
    calc CellConfig.dCC H₀.1 H''.1 ≤ CellConfig.dCC H₀.1 H.1 + CellConfig.dCC H.1 H''.1 :=
          dCC_triangle (finite_restrict_ball H₀.2) (finite_restrict_ball H.2) _
      _ < CellConfig.dCC H₀.1 H.1 + (ε - CellConfig.dCC H₀.1 H.1) :=
          ENNReal.add_lt_add_left hH'.ne_top (hspec H''.1 hH'')
      _ = ε := add_tsub_cancel_of_le hH'.le
  · show dSing H.1 H.1 < δ
    rw [CoordsMeasurable.dSing_self]
    exact hδ

/-- **Proposition 2.5, (2.6)**: `τ_sing|_{C_GMS} = τ_GMS`. -/
theorem topology_gmsSpace_eq_induced :
    (inferInstance : TopologicalSpace GMSSpace) = TopologicalSpace.induced toSing inferInstance :=
  le_antisymm (continuous_iff_le_induced.1 continuous_toSing) induced_toSing_le

/-- **Proposition 2.5, (2.6)**, embedding form: the inclusion `C_GMS → C_sing` is a topological
embedding. -/
theorem isEmbedding_toSing : Topology.IsEmbedding toSing :=
  ⟨⟨topology_gmsSpace_eq_induced⟩, toSing_injective⟩

/-- **Proposition 2.5**, trace σ-algebra: GMS's Borel σ-algebra is the trace of `B_sing` on
`C_GMS`. -/
theorem measurableSpace_gmsSpace_eq_comap :
    (inferInstance : MeasurableSpace GMSSpace) = MeasurableSpace.comap toSing inferInstance :=
  calc (inferInstance : MeasurableSpace GMSSpace) = @borel GMSSpace inferInstance := rfl
    _ = @borel GMSSpace (TopologicalSpace.induced toSing inferInstance) :=
        congrArg (@borel GMSSpace) topology_gmsSpace_eq_induced
    _ = MeasurableSpace.comap toSing (borel SingSpace) := borel_comap
    _ = MeasurableSpace.comap toSing inferInstance := rfl

end ReflectedGMS.GeomTop

assert_no_sorry ReflectedGMS.GeomTop.isEmbedding_toSing
assert_no_sorry ReflectedGMS.GeomTop.topology_gmsSpace_eq_induced
assert_no_sorry ReflectedGMS.GeomTop.measurableSpace_gmsSpace_eq_comap
#print axioms ReflectedGMS.GeomTop.isEmbedding_toSing
#print axioms ReflectedGMS.GeomTop.topology_gmsSpace_eq_induced
#print axioms ReflectedGMS.GeomTop.measurableSpace_gmsSpace_eq_comap
