import LQGMetric.Papers.DDDF.LenCountable
import LQGMetric.Papers.DDDF.LenObs
import LQGMetric.Gaussian.PittVector
import Mathlib.Probability.Process.FiniteDimensionalLaws
import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousMap

/-!
# Law transfer for crossing lengths of `φ_{a,b}` between white noises (for DDDF Prop 10)

DDDF Prop 10 (arXiv:1904.08021, `tightness.tex` l. 725–736) compares `L` (field `φ_{0,n}` of
`W`) with `L'` (field `φ̃_{0,n}` of the coupled white noise `W̃`, l. 541–543), which DDDF and
DF (arXiv:1809.02607, Props. 4.5–4.6) treat as a field with the law of `φ_{0,n}`. In the Lean
statement `Prop10` (D-DDDF-18) `L'` is computed from `φ_{0,n}` of `W` itself, and `W̃` lives on
an enlarged probability space; this module proves that the probabilities of crossing-length
events do not depend on the white noise or the probability space:

* `hasLaw_dual_phi`, `map_restrict_phi_eq`: the finite-dimensional laws of a version of
  `φ_{a,b}` are the same for every white noise (characteristic functionals,
  `Measure.ext_of_charFunDual`);
* `map_phi_eq`: hence the laws on `ℂ → ℝ` agree (`IsProjectiveLimit.unique`);
* `measure_crossLenIn_eq`: for continuous measurable versions and compact `K`,
  `P(crossLenIn(Y) ∈ S) = P₂(crossLenIn(Y₂) ∈ S)` for Borel `S`. The crossing length is a
  measurable function on `C(ℂ, ℝ)` (`measurable_crossLenIn`), and the Borel σ-algebra of
  `C(ℂ, ℝ)` is generated by the evaluations (mathlib `ContinuousMap.borel_eq_iSup_comap_eval`).

Standard measure theory, no published source needed (own routine step).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory ProbabilityTheory Set
open scoped ENNReal

namespace LQGMetric
namespace DDDF

open WhiteNoise

variable {Ω Ω₂ : Type*} [MeasurableSpace Ω] [MeasurableSpace Ω₂] {P : Measure Ω}
  {P₂ : Measure Ω₂}

/-- The law of a linear functional of `(Y(x_i))_{i ∈ I}` for a version `Y` of `φ_{a,b}`
depends only on `a, b, I, L`. -/
lemma hasLaw_dual_phi {W : WNSpace → Ω → ℝ} (hW : IsWhiteNoise P W) (a b : ℝ) (I : Finset ℂ)
    (L : StrongDual ℝ (I → ℝ)) {Y : ℂ → Ω → ℝ} (hY : ∀ x, Y x =ᵐ[P] phi W a b x) :
    HasLaw (fun ω => L (fun i : I => Y i ω)) (gaussianReal 0
      (‖∑ i : I, (Real.sqrt Real.pi * L (Pitt.unitVec i)) • phiKernelL2 a b i‖ ^ 2).toNNReal) P := by
  classical
  refine (hW.hasLaw (fun i : I => phiKernelL2 a b i)
    (fun i => Real.sqrt Real.pi * L (Pitt.unitVec i))).congr ?_
  have hall : ∀ᵐ ω ∂P, ∀ i : I, Y i ω = phi W a b i ω := ae_all_iff.2 fun i => hY i
  filter_upwards [hall] with ω hω
  rw [Pitt.dual_apply_eq_sum]
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [hω i, phi]; ring

/-- Equal finite-dimensional laws of versions of `φ_{a,b}` for two white noises. -/
lemma map_restrict_phi_eq {W : WNSpace → Ω → ℝ} {V : WNSpace → Ω₂ → ℝ} (hW : IsWhiteNoise P W)
    (hV : IsWhiteNoise P₂ V) (a b : ℝ) {Y : ℂ → Ω → ℝ} {Y₂ : ℂ → Ω₂ → ℝ}
    (hYm : ∀ x, Measurable (Y x)) (hY₂m : ∀ x, Measurable (Y₂ x))
    (hY : ∀ x, Y x =ᵐ[P] phi W a b x) (hY₂ : ∀ x, Y₂ x =ᵐ[P₂] phi V a b x) (I : Finset ℂ) :
    P.map (fun ω => I.restrict (Y · ω)) = P₂.map (fun ω => I.restrict (Y₂ · ω)) := by
  have := hW.isProbabilityMeasure
  have := hV.isProbabilityMeasure
  have hm : Measurable (fun ω => I.restrict (Y · ω)) := measurable_pi_iff.2 fun i => hYm i
  have hm₂ : Measurable (fun ω => I.restrict (Y₂ · ω)) := measurable_pi_iff.2 fun i => hY₂m i
  refine Measure.ext_of_charFunDual (funext fun L => ?_)
  rw [charFunDual_eq_charFun_map_one, charFunDual_eq_charFun_map_one,
    Measure.map_map L.continuous.measurable hm, Measure.map_map L.continuous.measurable hm₂]
  congr 1
  exact (hasLaw_dual_phi hW a b I L hY).map_eq.trans (hasLaw_dual_phi hV a b I L hY₂).map_eq.symm

/-- Equal laws on `ℂ → ℝ` of versions of `φ_{a,b}` for two white noises. -/
theorem map_phi_eq {W : WNSpace → Ω → ℝ} {V : WNSpace → Ω₂ → ℝ} (hW : IsWhiteNoise P W)
    (hV : IsWhiteNoise P₂ V) (a b : ℝ) {Y : ℂ → Ω → ℝ} {Y₂ : ℂ → Ω₂ → ℝ}
    (hYm : ∀ x, Measurable (Y x)) (hY₂m : ∀ x, Measurable (Y₂ x))
    (hY : ∀ x, Y x =ᵐ[P] phi W a b x) (hY₂ : ∀ x, Y₂ x =ᵐ[P₂] phi V a b x) :
    P.map (fun ω => (Y · ω)) = P₂.map (fun ω => (Y₂ · ω)) := by
  have := hW.isProbabilityMeasure
  have := hV.isProbabilityMeasure
  have h1 := isProjectiveLimit_map (P := P) (X := Y) (measurable_pi_iff.2 hYm).aemeasurable
  have h2 := isProjectiveLimit_map (P := P₂) (X := Y₂) (measurable_pi_iff.2 hY₂m).aemeasurable
  have e : (fun I : Finset ℂ => P.map (fun ω => I.restrict (Y · ω))) =
      fun I => P₂.map (fun ω => I.restrict (Y₂ · ω)) :=
    funext fun I => map_restrict_phi_eq hW hV a b hYm hY₂m hY hY₂ I
  rw [e] at h1
  exact h1.unique h2

/-- The σ-algebra of `C(ℂ, ℝ)` is the pullback of the product σ-algebra. -/
lemma measurableSpace_continuousMap_eq_comap :
    (ContinuousMap.measurableSpace : MeasurableSpace C(ℂ, ℝ)) =
      MeasurableSpace.comap (fun f : C(ℂ, ℝ) => (f : ℂ → ℝ)) MeasurableSpace.pi := by
  rw [ContinuousMap.measurableSpace_eq_iSup_comap_eval, MeasurableSpace.pi,
    MeasurableSpace.comap_iSup]
  simp_rw [MeasurableSpace.comap_comp]
  rfl

/-- **Law transfer of crossing lengths**: if two continuous measurable fields have the same law
on `ℂ → ℝ`, their crossing lengths in a compact `K` have the same law. -/
theorem measure_crossLenIn_eq {ξ : ℝ} {K A B : Set ℂ} (hK : IsCompact K) {Y : ℂ → Ω → ℝ}
    {Y₂ : ℂ → Ω₂ → ℝ} (hYc : ∀ ω, Continuous fun x => Y x ω) (hYm : ∀ x, Measurable (Y x))
    (hY₂c : ∀ ω, Continuous fun x => Y₂ x ω) (hY₂m : ∀ x, Measurable (Y₂ x))
    (hlaw : P.map (fun ω => (Y · ω)) = P₂.map (fun ω => (Y₂ · ω))) {S : Set ℝ≥0∞}
    (hS : MeasurableSet S) :
    P {ω | crossLenIn ξ (fun x => Y x ω) K A B ∈ S} =
      P₂ {ω | crossLenIn ξ (fun x => Y₂ x ω) K A B ∈ S} := by
  have hgm : Measurable fun f : C(ℂ, ℝ) => crossLenIn ξ (fun x => f x) K A B :=
    measurable_crossLenIn (Y := fun x (f : C(ℂ, ℝ)) => f x) hK (fun f => f.continuous)
      (fun x => ContinuousMap.measurable_eval x)
  have hE : MeasurableSet[MeasurableSpace.comap (fun f : C(ℂ, ℝ) => (f : ℂ → ℝ))
      MeasurableSpace.pi] {f : C(ℂ, ℝ) | crossLenIn ξ (fun x => f x) K A B ∈ S} := by
    rw [← measurableSpace_continuousMap_eq_comap]; exact hgm hS
  obtain ⟨T, hT, hTE⟩ := hE
  have key : ∀ g : ℂ → ℝ, Continuous g → (crossLenIn ξ g K A B ∈ S ↔ g ∈ T) := by
    intro g hg
    have := congrArg (fun E => (⟨g, hg⟩ : C(ℂ, ℝ)) ∈ E) hTE
    simp only [mem_preimage, ContinuousMap.coe_mk, mem_ofPred_eq, eq_iff_iff] at this
    exact this.symm
  have h1 : {ω | crossLenIn ξ (fun x => Y x ω) K A B ∈ S} = (fun ω => (Y · ω)) ⁻¹' T := by
    ext ω; exact key _ (hYc ω)
  have h2 : {ω | crossLenIn ξ (fun x => Y₂ x ω) K A B ∈ S} = (fun ω => (Y₂ · ω)) ⁻¹' T := by
    ext ω; exact key _ (hY₂c ω)
  rw [h1, h2, ← Measure.map_apply (measurable_pi_iff.2 hYm) hT,
    ← Measure.map_apply (measurable_pi_iff.2 hY₂m) hT, hlaw]

/-- Crossing-length probabilities of `phiVer` do not depend on the white noise. -/
theorem measure_crossLenIn_phiVer_eq {ξ : ℝ} {K A B : Set ℂ} (hK : IsCompact K)
    {W : WNSpace → Ω → ℝ} {V : WNSpace → Ω₂ → ℝ} (hW : IsWhiteNoise P W)
    (hV : IsWhiteNoise P₂ V) {a b : ℝ} (ha : 0 < a) (hab : a ≤ b) {S : Set ℝ≥0∞}
    (hS : MeasurableSet S) :
    P {ω | crossLenIn ξ (fun x => phiVer W P a b x ω) K A B ∈ S} =
      P₂ {ω | crossLenIn ξ (fun x => phiVer V P₂ a b x ω) K A B ∈ S} := by
  have h1 := isPhiVersion_phiVer hW ha hab
  have h2 := isPhiVersion_phiVer hV ha hab
  exact measure_crossLenIn_eq hK h1.cont h1.meas h2.cont h2.meas
    (map_phi_eq hW hV a b h1.meas h2.meas h1.ae_eq h2.ae_eq) hS

end DDDF
end LQGMetric
