import QuantumZipper.Common.Basic
import Mathlib.Analysis.SpecialFunctions.Complex.CircleMap
import Mathlib.MeasureTheory.Integral.CircleIntegral
import Mathlib.MeasureTheory.Measure.Lebesgue.Complex
import Mathlib.MeasureTheory.Measure.AEMeasurable
import Mathlib.MeasureTheory.Measure.WithDensity
import Mathlib.MeasureTheory.Function.Floor
import Mathlib.MeasureTheory.Constructions.Polish.StronglyMeasurable
import Mathlib.MeasureTheory.Integral.Prod
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic

/-!
# Field samples

Sheffield, *Conformal weldings of random surfaces: SLE and the quantum gravity zipper*,
arXiv:1012.4797.  This file implements `FOUNDATIONS.md` §2: a `FieldSample` is a candidate
value of a random distribution `h`, recorded as its pairing against every finite measure on
`ℂ`. Every evaluation of a field (circle average, semicircle average, pairing with a measure
or a test function, coordinate change under a conformal map) is built from the *canonical
regularization*: dyadically-rounded circle averages at radius `2^{-k}`, then a limit as
`k → ∞`. This makes every evaluation measurable *by construction* (Principle 1 of
`FOUNDATIONS.md` §0), which is what the `measurable_*` lemmas below record.
-/

noncomputable section

open MeasureTheory Filter
open scoped Real Topology

namespace QuantumZipper

/-- A field sample: a real number for every finite measure on `ℂ` ("pairing with `μ`").
Only finite, compactly supported, finite-energy measures carry the paper's meaning (namely
`⟨h, μ⟩`); the value at other measures is junk. The measurable-space structure on
`FieldSample` is `Pi.measurableSpace`, i.e. the cylinder σ-algebra generated by the evaluation
maps `x ↦ x μ`. Laws of random fields (`fieldLaw`, `Field/Law.lean`) live on this σ-algebra. -/
abbrev FieldSample := Measure ℂ → ℝ

/-- Fold a point of `ℂ` into the closed upper half-plane `Hbar` by reflecting points with
negative imaginary part across the real axis. Used to make a "circle average" meaningful even
when the circle pokes below `ℝ`: the folded circle (`foldedCircle`) always sits in `Hbar`. -/
def foldH (w : ℂ) : ℂ := if 0 ≤ w.im then w else (starRingEnd ℂ) w

/-- `foldH` is measurable: it is the identity on the closed set `Hbar` and complex conjugation
(continuous) off it. -/
theorem measurable_foldH : Measurable foldH :=
  Measurable.ite isClosed_Hbar.measurableSet measurable_id Complex.continuous_conj.measurable

/-- The uniform probability measure on the circle `∂B(z,ε)` of radius `ε` centred at `z`: the
pushforward of Lebesgue measure on `[0, 2π)` under `circleMap z ε`, normalized to total
mass `1` by `(2π)⁻¹`. (For `ε ≤ 0` this reduces to the Dirac mass at `z`.) -/
def circleUnif (z : ℂ) (ε : ℝ) : Measure ℂ :=
  (ENNReal.ofReal (2 * π))⁻¹ • (volume.restrict (Set.Ico 0 (2 * π))).map (circleMap z ε)

instance isProbabilityMeasure_circleUnif (z : ℂ) (ε : ℝ) :
    IsProbabilityMeasure (circleUnif z ε) := by
  have h2π : (0 : ℝ) < 2 * π := by positivity
  constructor
  show (ENNReal.ofReal (2 * π))⁻¹ •
      (volume.restrict (Set.Ico 0 (2 * π))).map (circleMap z ε) Set.univ = 1
  rw [smul_eq_mul,
    Measure.map_apply (measurable_circleMap z ε) MeasurableSet.univ, Set.preimage_univ,
    Measure.restrict_apply MeasurableSet.univ, Set.univ_inter, Real.volume_Ico, sub_zero]
  exact ENNReal.inv_mul_cancel (ENNReal.ofReal_pos.mpr h2π).ne' ENNReal.ofReal_ne_top

/-- The folded circle measure: the uniform circle measure `circleUnif z ε` pushed into the
closed upper half-plane by `foldH`. For `ε < Im z` this is just the circle measure (it never
leaves `H`); for `z ∈ ℝ` it is the uniform measure on the semicircle `{z + ε e^{iθ} : θ ∈ [0,π]}`
(each half of the circle folds onto the other). This is the measure the paper integrates
against to form circle/semicircle averages of a field. -/
def foldedCircle (z : ℂ) (ε : ℝ) : Measure ℂ := (circleUnif z ε).map foldH

instance isProbabilityMeasure_foldedCircle (z : ℂ) (ε : ℝ) :
    IsProbabilityMeasure (foldedCircle z ε) := by
  unfold foldedCircle; infer_instance

/-- `dyadicRound n` is measurable: it is `Int.floor` after scaling by `2^n`, then rescaled
back down. -/
private theorem measurable_dyadicRound (n : ℕ) : Measurable (dyadicRound n) := by
  unfold dyadicRound
  exact ((measurable_from_top : Measurable (Int.cast : ℤ → ℝ)).div_const ((2 : ℝ) ^ n)).comp
    (Measurable.floor (measurable_id.const_mul ((2 : ℝ) ^ n)))

/-- `dyadicRoundC n` is measurable: it rounds the real and imaginary parts independently. -/
private theorem measurable_dyadicRoundC (n : ℕ) : Measurable (dyadicRoundC n) := by
  have hrw : dyadicRoundC n
      = fun z : ℂ => (dyadicRound n z.re : ℂ) + (dyadicRound n z.im : ℂ) * Complex.I := by
    funext z
    apply Complex.ext <;> simp [dyadicRoundC]
  rw [hrw]
  exact (Complex.continuous_ofReal.measurable.comp
        ((measurable_dyadicRound n).comp Complex.measurable_re)).add
    ((Complex.continuous_ofReal.measurable.comp
        ((measurable_dyadicRound n).comp Complex.measurable_im)).mul_const Complex.I)

/-- `dyadicRoundC n` has countable range: it only ever takes values on the dyadic grid of mesh
`2^{-n}` in `ℂ`. This is what lets `avgReg` (which samples `x` only at `foldedCircle` of dyadic
approximations of the centre) be jointly measurable in `(x, z)`, even though a field sample `x`
need not depend continuously (or even measurably) on the centre of an arbitrary circle. -/
private theorem countable_range_dyadicRoundC (n : ℕ) :
    (Set.range (dyadicRoundC n)).Countable := by
  have hsub : Set.range (dyadicRoundC n) ⊆
      Set.range (fun p : ℤ × ℤ => (⟨(p.1 : ℝ) / (2 : ℝ) ^ n, (p.2 : ℝ) / (2 : ℝ) ^ n⟩ : ℂ)) := by
    rintro _ ⟨z, rfl⟩
    exact ⟨(⌊(2 : ℝ) ^ n * z.re⌋, ⌊(2 : ℝ) ^ n * z.im⌋), rfl⟩
  exact (Set.countable_range _).mono hsub

/-- Joint measurability, in `(x, z)`, of the raw (un-limited) term in `avgReg` at a fixed
dyadic scale `n`. The key point: `dyadicRoundC n` has countable range, so `z` only ever selects
among countably many measures `foldedCircle d (radius k)`, at each of which `x ↦ x (…)` is a
coordinate projection and hence measurable; countably many measurable "slices" glue to a
jointly measurable function. -/
private theorem measurable_eval_dyadic (n k : ℕ) :
    Measurable (fun p : FieldSample × ℂ => p.1 (foldedCircle (dyadicRoundC n p.2) (radius k))) := by
  have : Countable (Set.range (dyadicRoundC n)) := (countable_range_dyadicRoundC n).to_subtype
  intro T hT
  have key : (fun p : FieldSample × ℂ => p.1 (foldedCircle (dyadicRoundC n p.2) (radius k))) ⁻¹' T
      = ⋃ d : Set.range (dyadicRoundC n),
          {x : FieldSample | x (foldedCircle (d : ℂ) (radius k)) ∈ T} ×ˢ
            (dyadicRoundC n ⁻¹' ({(d : ℂ)} : Set ℂ)) := by
    ext ⟨x, z⟩
    simp only [Set.mem_preimage, Set.mem_iUnion, Set.mem_prod, Set.mem_ofPred_eq,
      Set.mem_singleton_iff]
    constructor
    · intro hmem
      exact ⟨⟨dyadicRoundC n z, Set.mem_range_self z⟩, hmem, rfl⟩
    · rintro ⟨d, hmem, hdz⟩
      rwa [hdz]
  rw [key]
  refine MeasurableSet.iUnion fun d => MeasurableSet.prod ?_ ?_
  · exact measurable_pi_apply (foldedCircle (d : ℂ) (radius k)) hT
  · exact (measurable_dyadicRoundC n) (measurableSet_singleton _)

/-- Regularized folded-circle average at radius `2^{-k}`: the limit, along the dyadic
approximations `dyadicRoundC n z → z`, of the raw values `x (foldedCircle (dyadicRoundC n z)
(radius k))` (junk `0` if the limit does not exist). This is the paper's `h_{2^{-k}}(z)`, made
into a canonical, measurable function of `(x, z)` as required by `FOUNDATIONS.md` §0.1. -/
def avgReg (x : FieldSample) (k : ℕ) (z : ℂ) : ℝ :=
  limUnder atTop fun n => x (foldedCircle (dyadicRoundC n z) (radius k))

/-- `avgReg` is jointly measurable in `(x, z)` at each fixed scale `k`: a `limUnder` of a
sequence of jointly measurable functions. -/
theorem measurable_avgReg (k : ℕ) : Measurable (fun p : FieldSample × ℂ => avgReg p.1 k p.2) := by
  unfold avgReg
  exact (StronglyMeasurable.limUnder
    (fun n => (measurable_eval_dyadic n k).stronglyMeasurable)).measurable

/-- Regularized semicircle average of `x` centred at `0`, at radius `r > 0` (this is the
paper's radial part `h_r(0)`): the limit, along dyadic approximations `dyadicRound n r +
radius n → r`, of the corresponding folded-circle averages. -/
def radAvgReg (x : FieldSample) (r : ℝ) : ℝ :=
  limUnder atTop fun n => x (foldedCircle 0 (dyadicRound n r + radius n))

/-- Regularized evaluation of the field `x` at an arbitrary finite measure `ν`: the limit, as
`k → ∞`, of `∫ avgReg x k dν` (junk `0` if the limit does not exist). This is the paper's
`⟨x, ν⟩`, defined so as to be measurable in `x` for every fixed `ν` (`FOUNDATIONS.md` §0.1). -/
def evalReg (x : FieldSample) (ν : Measure ℂ) : ℝ :=
  limUnder atTop fun k => ∫ w, avgReg x k w ∂ν

/-- `evalReg x ν` is measurable in `x`, for every fixed s-finite `ν`: a `limUnder` of a sequence
of `x ↦ ∫ avgReg x k · ∂ν`, each of which is measurable by joint measurability of `avgReg` and
Fubini-type measurability of the partial integral (`StronglyMeasurable.integral_prod_right'`). -/
theorem measurable_evalReg (ν : Measure ℂ) [SFinite ν] :
    Measurable (fun x : FieldSample => evalReg x ν) := by
  unfold evalReg
  have hf : ∀ k : ℕ, StronglyMeasurable (fun x : FieldSample => ∫ w, avgReg x k w ∂ν) := fun k =>
    StronglyMeasurable.integral_prod_right' (measurable_avgReg k).stronglyMeasurable
  exact (StronglyMeasurable.limUnder hf).measurable

/-- Pairing of the field `x` with a real test function `ρ` (as a signed density with respect to
Lebesgue measure on `ℂ`): `⟨x, ρ⟩ = ⟨x, ρ⁺ dz⟩ - ⟨x, ρ⁻ dz⟩`, evaluated through `evalReg`. -/
def pairTest (x : FieldSample) (ρ : ℂ → ℝ) : ℝ :=
  evalReg x (volume.withDensity fun z => ENNReal.ofReal (ρ z)) -
  evalReg x (volume.withDensity fun z => ENNReal.ofReal (-ρ z))

/-- `pairTest x ρ` is measurable in `x`, for every (not necessarily measurable) test function
`ρ`: Lebesgue measure on `ℂ` is s-finite, `withDensity` preserves s-finiteness unconditionally,
so `measurable_evalReg` applies to both signed parts. -/
theorem measurable_pairTest (ρ : ℂ → ℝ) : Measurable (fun x : FieldSample => pairTest x ρ) := by
  unfold pairTest
  exact (measurable_evalReg _).sub (measurable_evalReg _)

/-- A deterministic function `g` viewed as a field sample: pairing with `μ` is literally
`∫ g dμ`. This is how the paper's explicit harmonic functions (`𝔥₀`, `𝔥_T`, …) become
`FieldSample`s to be added to a genuinely random field. -/
def ofFun (g : ℂ → ℝ) : FieldSample := fun μ => ∫ z, g z ∂μ

/-- Coordinate change (paper's (1.3)): `h ↦ h∘ψ + Q log|ψ'|` for `ψ` a conformal map into the
domain where `x` lives. Evaluated at `μ`, this is `evalReg x (μ.map ψ) + Q ∫ log‖ψ'‖ dμ`. -/
def coordChange (x : FieldSample) (ψ : ℂ → ℂ) (Q : ℝ) : FieldSample :=
  fun μ => evalReg x (μ.map ψ) + Q * ∫ z, Real.log ‖deriv ψ z‖ ∂μ

/-- For fixed `ψ`, `Q` and an s-finite `μ`, `x ↦ coordChange x ψ Q μ` is measurable: the second
summand does not depend on `x`, and `μ.map ψ` is again s-finite (unconditionally in `ψ`), so
`measurable_evalReg` applies to the first summand. -/
theorem measurable_coordChange_apply (ψ : ℂ → ℂ) (Q : ℝ) (μ : Measure ℂ) [SFinite μ] :
    Measurable (fun x : FieldSample => coordChange x ψ Q μ) := by
  unfold coordChange
  exact (measurable_evalReg (μ.map ψ)).add measurable_const

/-- The field `x` translated by `a`: pairing with `μ` becomes pairing of `x` with `μ`
translated by `a`. -/
def translate (x : FieldSample) (a : ℂ) : FieldSample := fun μ => evalReg x (μ.map (· + a))

/-- The field `x` rescaled by `a` (with LQG constant `Q`): the special case of `coordChange` by
the conformal map `z ↦ a z`. This implements the rescaling freedom `h ↦ h(a ·) + Q log a` of
`FOUNDATIONS.md` §1.6 / `THEOREM_STATEMENTS_ENGLISH.md`. -/
def rescale (x : FieldSample) (Q a : ℝ) : FieldSample := coordChange x (fun z => (a : ℂ) * z) Q

/-- The field `x` shifted by the additive constant `c`: pairing with `μ` picks up `c · μ(univ)`.
-/
def addConst (x : FieldSample) (c : ℝ) : FieldSample := fun μ => x μ + c * (μ Set.univ).toReal

end QuantumZipper
