import ReflectedGMS.Process.QuenchedLimit
import BouRabeeGwynne.BrownianLawUniqueness
import Mathlib.MeasureTheory.Measure.Prokhorov
import Mathlib.MeasureTheory.Constructions.BorelSpace.ContinuousMap
import Mathlib.MeasureTheory.Constructions.Projective

/-!
# Tightness plus finite-dimensional convergence gives the quenched path limit

This file supplies the *structural* half of the quenched invariance principle
`hlimit` of `ReflectedGMS/InvarianceAssembly.lean`, namely the classical
functional-limit skeleton

> a uniformly tight family of laws on a continuous-path space whose
> finite-dimensional distributions converge to those of a fixed limit law
> converges weakly to that limit law.

Nothing probabilistic about the reflected walk is proved here.  The two
genuinely analytic inputs are left as named hypotheses:

* `htight` — uniform tightness of the diffusively rescaled path laws on
  `C(ℝ≥0, Euc 2)` (an Arzelà–Ascoli / modulus-of-continuity estimate), and
* `hfdd` — weak convergence of every finite-dimensional distribution to the
  corresponding one of the anisotropic Brownian target.

**This file therefore does not certify the quenched invariance principle.**  It
certifies the reduction of the convergence assertion of
`ReflectedGMS.StatementIngredients.QuenchedWeakLimitAtFixedStart` to those two
inputs, and it identifies the limit law against the *constructed* target
`AnisotropicBrownianTarget` rather than against an abstract Brownian law.

## Route and reused results

* mathlib's Prokhorov theorem `MeasureTheory.isCompact_closure_of_isTightMeasureSet`
  turns tightness into compactness of the closure of the family;
* mathlib's `IsCompact.tendsto_nhds_of_unique_mapClusterPt` turns "compact plus
  a unique cluster point" into convergence;
* `MeasureTheory.ProbabilityMeasure.continuous_map` pushes a cluster point
  forward through the (continuous) finite-dimensional evaluation maps, so the
  cluster point has the target's finite-dimensional distributions;
* `ContinuousMap.measurableSpace_eq_iSup_comap_eval` together with
  `MeasureTheory.IsProjectiveLimit.unique` shows that the finite-dimensional
  distributions determine a law on `C(X, E)`;
* `BouRabeeGwynne.standardBrownianLaw_unique` identifies the target path law
  as the linear image of *the* standard Brownian law.

## Main results

* `measure_eq_of_forall_map_finsetRestrict_eq` — finite-dimensional
  distributions determine a finite measure on `C(X, E)`.
* `tendsto_of_isTightMeasureSet_of_tendsto_map_finsetRestrict` — the skeleton
  theorem, for an arbitrary filter of indices.
* `quenchedWeakLimitAtFixedStart_of_isTightMeasureSet_of_tendsto_map_finsetRestrict`
  and its two-clock form — the same statement in exactly the shape consumed by
  `RepresentativePathConclusions`.
* `map_linearImageBrownianPath_eq_pathLaw` — the target path law is the image of
  *any* standard Brownian law under the target's factor matrix.
-/

set_option autoImplicit false

open MeasureTheory Filter Set
open scoped ENNReal NNReal Topology

namespace ReflectedGMS.MartingaleLimit

section PathLaws

variable {X E : Type*} [TopologicalSpace X] [MetricSpace E]
  [MeasurableSpace E] [BorelSpace E]

/-- Forget continuity: the raw coordinate family of a continuous path. -/
def pathCoordinates (f : C(X, E)) : X → E := fun x => f x

theorem measurable_pathCoordinates :
    Measurable (pathCoordinates : C(X, E) → X → E) :=
  Measurable.of_eval fun x => ContinuousMap.measurable_eval x

omit [MeasurableSpace E] [BorelSpace E] in
/-- Evaluation at a finite set of times is continuous on the path space. -/
theorem continuous_finsetRestrict_pathCoordinates (I : Finset X) :
    Continuous (fun f : C(X, E) => I.restrict (pathCoordinates f)) :=
  continuous_pi fun i => continuous_eval_const (i : X)

variable [SecondCountableTopology X] [SecondCountableTopology E]
  [LocallyCompactSpace X]

/-- The Borel structure of the compact-open topology is the one generated by the
evaluations, in the bundled `comap` form. -/
theorem measurableSpace_continuousMap_eq_comap_pathCoordinates :
    (ContinuousMap.measurableSpace : MeasurableSpace C(X, E)) =
      MeasurableSpace.comap (pathCoordinates : C(X, E) → X → E) inferInstance := by
  refine le_antisymm ?_ measurable_pathCoordinates.comap_le
  rw [ContinuousMap.measurableSpace_eq_iSup_comap_eval]
  refine iSup_le fun x => ?_
  have heval : Measurable[MeasurableSpace.comap
      (pathCoordinates : C(X, E) → X → E) inferInstance] (fun f : C(X, E) => f x) :=
    (measurable_pi_apply x).comp (comap_measurable _)
  exact heval.comap_le

/-- Two laws on the continuous-path space with the same raw coordinate image
coincide. -/
theorem measure_eq_of_map_pathCoordinates_eq {μ ν : Measure C(X, E)}
    (h : μ.map pathCoordinates = ν.map pathCoordinates) : μ = ν := by
  ext s hs
  have hs' : MeasurableSet[MeasurableSpace.comap
      (pathCoordinates : C(X, E) → X → E) inferInstance] s :=
    measurableSpace_continuousMap_eq_comap_pathCoordinates (X := X) (E := E) ▸ hs
  obtain ⟨t, ht, rfl⟩ := hs'
  rw [← Measure.map_apply measurable_pathCoordinates ht,
    ← Measure.map_apply measurable_pathCoordinates ht, h]

/-- **The finite-dimensional distributions determine a finite law on the
continuous-path space.** -/
theorem measure_eq_of_forall_map_finsetRestrict_eq {μ ν : Measure C(X, E)}
    [IsFiniteMeasure μ] [IsFiniteMeasure ν]
    (h : ∀ I : Finset X,
      μ.map (fun f : C(X, E) => I.restrict (pathCoordinates f)) =
        ν.map (fun f : C(X, E) => I.restrict (pathCoordinates f))) :
    μ = ν := by
  refine measure_eq_of_map_pathCoordinates_eq ?_
  set P : ∀ I : Finset X, Measure (∀ i : I, E) :=
    fun I => μ.map (fun f : C(X, E) => I.restrict (pathCoordinates f)) with hP
  have hμlim : IsProjectiveLimit (μ.map pathCoordinates) P := by
    intro I
    rw [Measure.map_map I.measurable_restrict measurable_pathCoordinates]
    rfl
  have hνlim : IsProjectiveLimit (ν.map pathCoordinates) P := by
    intro I
    rw [Measure.map_map I.measurable_restrict measurable_pathCoordinates]
    exact (h I).symm
  have hfin : ∀ I : Finset X, IsFiniteMeasure (P I) := by
    intro I
    rw [hP]
    infer_instance
  exact hμlim.unique hνlim

/-- **Tightness plus convergence of the finite-dimensional distributions gives
weak convergence of the path laws.**  The index filter is arbitrary, so this
applies verbatim to the positive-side scale limit `𝓝[>] 0`. -/
theorem tendsto_of_isTightMeasureSet_of_tendsto_map_finsetRestrict
    {ι : Type*} {l : Filter ι} [l.NeBot]
    (F : ι → ProbabilityMeasure C(X, E)) (μ : ProbabilityMeasure C(X, E))
    (S : Set (ProbabilityMeasure C(X, E)))
    (hmem : ∀ᶠ i in l, F i ∈ S)
    (htight : IsTightMeasureSet
      {((ρ : ProbabilityMeasure C(X, E)) : Measure C(X, E)) | ρ ∈ S})
    (hfdd : ∀ I : Finset X,
      Tendsto (fun i => (F i).map (fun f : C(X, E) => I.restrict (pathCoordinates f))) l
        (𝓝 (μ.map (fun f : C(X, E) => I.restrict (pathCoordinates f))))) :
    Tendsto F l (𝓝 μ) := by
  have hcomp : IsCompact (closure S) := isCompact_closure_of_isTightMeasureSet htight
  refine hcomp.tendsto_nhds_of_unique_mapClusterPt
    (hmem.mono fun i hi => subset_closure hi) ?_
  intro ρ _hρ hρcl
  refine ProbabilityMeasure.toMeasure_injective ?_
  refine measure_eq_of_forall_map_finsetRestrict_eq ?_
  intro I
  have hmapcl : MapClusterPt
      (ρ.map (fun f : C(X, E) => I.restrict (pathCoordinates f))) l
      (fun i => (F i).map (fun f : C(X, E) => I.restrict (pathCoordinates f))) :=
    MapClusterPt.continuousAt_comp
      (ProbabilityMeasure.continuous_map
        (continuous_finsetRestrict_pathCoordinates I)).continuousAt hρcl
  have heq : ρ.map (fun f : C(X, E) => I.restrict (pathCoordinates f)) =
      μ.map (fun f : C(X, E) => I.restrict (pathCoordinates f)) :=
    eq_of_nhds_neBot (hmapcl.clusterPt.mono (hfdd I))
  exact congrArg (fun σ : ProbabilityMeasure (∀ i : I, E) => (σ : Measure (∀ i : I, E))) heq

end PathLaws

/-! ## Specialisation to the anisotropic Brownian target -/

section BrownianTarget

open StatementIngredients

/-- **The target path law is the linear image of any standard Brownian law.**
Identification against the constructed inhabitant of `AnisotropicBrownianTarget`
therefore only needs the standard-Brownian predicate, by
`BouRabeeGwynne.standardBrownianLaw_unique`. -/
theorem map_linearImageBrownianPath_eq_pathLaw (target : AnisotropicBrownianTarget)
    {σ : Measure (BouRabeeGwynne.BrownianPath 2)}
    (hσ : BouRabeeGwynne.IsStandardBrownianLaw σ) :
    σ.map (linearImageBrownianPath target.factor) =
      (target.pathLaw : Measure (BouRabeeGwynne.BrownianPath 2)) := by
  rw [BouRabeeGwynne.standardBrownianLaw_unique hσ target.isStandard]
  rfl

variable {Environment Vertex : Type*}

/-- **The quenched weak limit at a fixed start, reduced to tightness and
finite-dimensional convergence.**  This is the shape consumed by
`ReflectedGMS.InvarianceMainStatement.RepresentativePathConclusions`.  It is a
conditional result: neither `htight` nor `hfdd` is proved here. -/
theorem quenchedWeakLimitAtFixedStart_of_isTightMeasureSet_of_tendsto_map_finsetRestrict
    (law : Environment → Vertex → ProbabilityMeasure (BouRabeeGwynne.BrownianPath 2))
    (target : AnisotropicBrownianTarget) (environment : Environment) (start : Vertex)
    (S : Set (ProbabilityMeasure (BouRabeeGwynne.BrownianPath 2)))
    (hmem : ∀ᶠ ε in nhdsWithin (0 : ℝ≥0) (Ioi 0),
      diffusivelyRescaledPathLaw (law environment start) ε ∈ S)
    (htight : IsTightMeasureSet
      {((ρ : ProbabilityMeasure (BouRabeeGwynne.BrownianPath 2)) :
          Measure (BouRabeeGwynne.BrownianPath 2)) | ρ ∈ S})
    (hfdd : ∀ I : Finset ℝ≥0,
      Tendsto (fun ε => (diffusivelyRescaledPathLaw (law environment start) ε).map
          (fun f : BouRabeeGwynne.BrownianPath 2 => I.restrict (pathCoordinates f)))
        (nhdsWithin (0 : ℝ≥0) (Ioi 0))
        (𝓝 (target.pathLaw.map
          (fun f : BouRabeeGwynne.BrownianPath 2 => I.restrict (pathCoordinates f))))) :
    QuenchedWeakLimitAtFixedStart law target environment start :=
  tendsto_of_isTightMeasureSet_of_tendsto_map_finsetRestrict
    (fun ε => diffusivelyRescaledPathLaw (law environment start) ε)
    target.pathLaw S hmem htight hfdd

end BrownianTarget

end ReflectedGMS.MartingaleLimit
