import LQGMetric.Papers.CONF.S3D114S5

/-!
# CONF Lemma 3.6, Step 3: `{ρ̃^m = 2^ℓ𝔢}` is generated by the events `E^{Ũ}_r(𝔷)`, `r ≤ 2^ℓ𝔢`

Gwynne–Miller, *Confluence of geodesics in LQG*, arXiv:1905.00381 (CONF),
`literature/src/1905.00381/confluence-final.tex`, (3.19) (C:1350), Step 3 (C:1433–1447); decision
D114 §4 C2 (ii): "`{ρ̃^{m} = r}` for `r < 𝔯` is determined by `𝓑^•_τ` and the events
`E^{Ũ^{r'}}_{r'}(𝔷)`, `r' ≤ r`".

`conf36_measurableSet_rho`: for any σ-algebra `M` and an `M`-event `E₀ ⊆ {e = 𝔢, z = 𝔷}` such that
`E₀ ∩ E^{Ũ}_{2^j𝔢}(𝔷)` is an `M`-event for every `j < k`, all events
`E₀ ∩ {ρ̃^m = 2^ℓ𝔢}`, `ℓ < k`, are `M`-events (induction on `m` via `conf36Rho_succ_eq_iff`).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Set Metric Filter Topology
open scoped ENNReal

namespace LQGMetric.CONF

open Blueprint

/-- the event `E^{Ũ^r}_r(𝔷)` at `r = 2^j𝔢` with `Ũ^r` built from `Bf` -/
def conf36EUj {Ω : Type} [MeasurableSpace Ω] (ξ : ℝ) (cc : ℝ → ℝ) (D : DistC → ContMetric) (P : Measure Ω) (h : Ω → DistC)
    (p : CONFParams) (Bf : Ω → Set ℂ) (𝔢 : ℝ) (𝔷 : ℂ) (j : ℤ) : Set Ω :=
  {ω | ω ∈ confEU ξ cc D P h p ((2 : ℝ) ^ j * 𝔢) 𝔷
    (conf36T p.δ ((2 : ℝ) ^ j * 𝔢) 𝔷 (Bf ω))}

theorem conf36_rho_zero_set {Ω : Type} [MeasurableSpace Ω]
    {ξ : ℝ} {cc : ℝ → ℝ} {D : DistC → ContMetric} {P : Measure Ω} {h : Ω → DistC}
    {p : CONFParams} {e : Ω → ℝ} {zf : Ω → ℂ} {Bf : Ω → Set ℂ} {𝔢 : ℝ} {𝔷 : ℂ} {E₀ : Set Ω}
    (hE₀s : ∀ ω ∈ E₀, e ω = 𝔢 ∧ zf ω = 𝔷) (ℓ : ℤ) :
    E₀ ∩ {ω | conf36Rho ξ cc D P h p e zf Bf 0 ω = ENNReal.ofReal ((2 : ℝ) ^ ℓ * 𝔢)} =
      E₀ ∩ {_ω | ENNReal.ofReal 𝔢 = ENNReal.ofReal ((2 : ℝ) ^ ℓ * 𝔢)} := by
  ext ω
  constructor
  · rintro ⟨h1, h2⟩
    refine ⟨h1, ?_⟩
    have h2' : ENNReal.ofReal (e ω) = ENNReal.ofReal ((2 : ℝ) ^ ℓ * 𝔢) := h2
    rw [(hE₀s ω h1).1] at h2'
    exact h2'
  · rintro ⟨h1, h2⟩
    refine ⟨h1, ?_⟩
    show ENNReal.ofReal (e ω) = _
    rw [(hE₀s ω h1).1]
    exact h2

set_option maxHeartbeats 1000000 in
theorem conf36_rho_succ_set {Ω : Type} [MeasurableSpace Ω]
    {ξ : ℝ} {cc : ℝ → ℝ} {D : DistC → ContMetric} {P : Measure Ω} {h : Ω → DistC}
    {p : CONFParams} {e : Ω → ℝ} {zf : Ω → ℂ} {Bf : Ω → Set ℂ} {𝔢 : ℝ} (h𝔢 : 0 < 𝔢) {𝔷 : ℂ}
    {E₀ : Set Ω} (hE₀s : ∀ ω ∈ E₀, e ω = 𝔢 ∧ zf ω = 𝔷) (m : ℕ) (ℓ : ℤ) :
    E₀ ∩ {ω | conf36Rho ξ cc D P h p e zf Bf (m + 1) ω = ENNReal.ofReal ((2 : ℝ) ^ ℓ * 𝔢)} =
      ⋃ ℓ' : ℤ, {_ω | 6 * (2 : ℝ) ^ ℓ' ≤ (2 : ℝ) ^ ℓ} ∩
      ((E₀ ∩ {ω | conf36Rho ξ cc D P h p e zf Bf m ω = ENNReal.ofReal ((2 : ℝ) ^ ℓ' * 𝔢)}) ∩
        (E₀ ∩ conf36EUj ξ cc D P h p Bf 𝔢 𝔷 ℓ) ∩
        ⋂ j : {j : ℤ // j < ℓ}, ({_ω | 6 * (2 : ℝ) ^ ℓ' ≤ (2 : ℝ) ^ j.1}ᶜ ∪
          (E₀ ∩ conf36EUj ξ cc D P h p Bf 𝔢 𝔷 j.1)ᶜ)) := by
  ext ω
  simp only [mem_inter_iff, mem_ofPred_eq, mem_iUnion, mem_iInter, mem_union,
    mem_compl_iff, conf36EUj]
  constructor
  · rintro ⟨h0, hρ⟩
    obtain ⟨he1, hz1⟩ := hE₀s ω h0
    have key := conf36Rho_succ_eq_iff (ξ := ξ) (cc := cc) (D := D) (P := P) (h := h)
      (p := p) (zf := zf) (Bf := Bf) (he1 ▸ h𝔢) m ℓ
    rw [he1, hz1] at key
    obtain ⟨ℓ', h1, h2, h3, h4⟩ := key.1 hρ
    refine ⟨ℓ', h2, ⟨⟨h0, h1⟩, h0, h3⟩, fun j => ?_⟩
    by_cases hj : 6 * (2 : ℝ) ^ ℓ' ≤ (2 : ℝ) ^ j.1
    · exact Or.inr fun hh => h4 j.1 hj j.2 hh.2
    · exact Or.inl hj
  · rintro ⟨ℓ', h2, ⟨⟨h0, h1⟩, -, h3⟩, h4⟩
    obtain ⟨he1, hz1⟩ := hE₀s ω h0
    have key := conf36Rho_succ_eq_iff (ξ := ξ) (cc := cc) (D := D) (P := P) (h := h)
      (p := p) (zf := zf) (Bf := Bf) (he1 ▸ h𝔢) m ℓ
    rw [he1, hz1] at key
    refine ⟨h0, key.2 ⟨ℓ', h1, h2, h3, fun j hj hjℓ hEj => ?_⟩⟩
    rcases h4 ⟨j, hjℓ⟩ with h5 | h5
    · exact h5 hj
    · exact h5 ⟨h0, hEj⟩

theorem conf36_measurableSet_rho {Ω : Type} (M : MeasurableSpace Ω) [MeasurableSpace Ω]
    {ξ : ℝ} {cc : ℝ → ℝ} {D : DistC → ContMetric} {P : Measure Ω} {h : Ω → DistC}
    {p : CONFParams} {e : Ω → ℝ} {zf : Ω → ℂ} {Bf : Ω → Set ℂ} {𝔢 : ℝ} (h𝔢 : 0 < 𝔢) {𝔷 : ℂ}
    {k : ℤ} {E₀ : Set Ω} (hE₀s : ∀ ω ∈ E₀, e ω = 𝔢 ∧ zf ω = 𝔷) (hE₀ : MeasurableSet[M] E₀)
    (hEU : ∀ j < k, MeasurableSet[M] (E₀ ∩ conf36EUj ξ cc D P h p Bf 𝔢 𝔷 j)) :
    ∀ m : ℕ, ∀ ℓ < k, MeasurableSet[M]
      (E₀ ∩ {ω | conf36Rho ξ cc D P h p e zf Bf m ω = ENNReal.ofReal ((2 : ℝ) ^ ℓ * 𝔢)}) := by
  intro m
  induction m with
  | zero =>
    intro ℓ _
    rw [conf36_rho_zero_set hE₀s ℓ]
    exact hE₀.inter (MeasurableSet.const (m := M) _)
  | succ m ih =>
    intro ℓ hℓ
    rw [conf36_rho_succ_set h𝔢 hE₀s m ℓ]
    refine MeasurableSet.iUnion (m := M) fun ℓ' => ?_
    by_cases h6 : 6 * (2 : ℝ) ^ ℓ' ≤ (2 : ℝ) ^ ℓ
    · have hℓ'ℓ : ℓ' < ℓ := by
        have : (2 : ℝ) ^ ℓ' < (2 : ℝ) ^ ℓ := by
          have := zpow_pos (by norm_num : (0 : ℝ) < 2) ℓ'; linarith
        exact (zpow_lt_zpow_iff_right₀ (by norm_num : (1 : ℝ) < 2)).1 this
      exact (MeasurableSet.const (m := M) _).inter (((ih ℓ' (hℓ'ℓ.trans hℓ)).inter
        (hEU ℓ hℓ)).inter (MeasurableSet.iInter (m := M) fun j =>
          ((MeasurableSet.const (m := M) _).compl).union (hEU j.1 (j.2.trans hℓ)).compl))
    · have e0 : {_ω : Ω | 6 * (2 : ℝ) ^ ℓ' ≤ (2 : ℝ) ^ ℓ} = ∅ := by
        ext ω; simp only [mem_ofPred_eq, mem_empty_iff_false, iff_false]; exact h6
      rw [e0, empty_inter]
      exact @MeasurableSet.empty _ M

end LQGMetric.CONF
