import LQGMetric.Blueprint.StoppingAE
import LQGMetric.Blueprint.M2Defs

/-!
# A.s. filled-ball stopping times of the mod-constant filtration (D130 §4)

CONF = Gwynne–Miller arXiv:1905.00381, `confluence-final.tex`. The iteration in the proof of CONF
Theorem 3.9 (C:1292–1302, 1506–1566) uses stopping times of the filtration generated by
`(𝓑^•_s, h|_{𝓑^•_s})`, `s ≤ t`, with `h` viewed modulo additive constants (C:1154; D108, D110).
`IsFilledBallStoppingTimeAE0` is that notion, holding a.s. (as `IsFilledBallStoppingTimeAE`,
D120); it is the invariant of the induction of decision D130 §4 (packets J6a–J6e).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory

namespace LQGMetric.CONF

open LQGMetric.Blueprint

variable {Ω : Type} [MeasurableSpace Ω]

/-- `τ` is a.s. a stopping time of the filtration `t ↦ ⨆_{s ≤ t} localSigma0 h 𝓑^•_s` (D130 §4).
Caveat (P2-T39K2, P2-AUDITL, D130B): the balls `𝓑^•_s` are the raw filled balls of `D_h`, whose
radii see the additive constant of `h`, so this is not the filtration of `h` modulo constants;
every deterministic time is such a stopping time (`t39k2_ae0_const`). It is used only as the
a.s. stopping-time property inside the D130B iteration (L0, L1, L3), never as locality. -/
def IsFilledBallStoppingTimeAE0 (P : Measure Ω) (D : DistC → ContMetric) (h : Ω → DistC)
    (z₀ : ℂ) (τ : Ω → ℝ) : Prop :=
  ∀ t : ℝ, AEEventIn P
    (⨆ (s : ℝ) (_ : s ≤ t), localSigma0 h (fun ω => filledBall (D (h ω)) z₀ s)) {ω | τ ω < t}

end LQGMetric.CONF
