import LQGMetric.Papers.CONF.S3T39K0
import LQGMetric.Papers.CONF.S3T39J5a
import LQGMetric.Papers.CONF.L2_1B
import LQGMetric.Papers.GM.S4.JordanPunct
import LQGMetric.Papers.GM.S4.L45Det3
import LQGMetric.Meas.LocalEventRandom
import LQGMetric.Papers.CONF.S3D110A

/-!
# CONF Theorem 3.9, packet J6a: the base of the mod-constant stopping-time iteration (D130 §4)

CONF = Gwynne–Miller arXiv:1905.00381, `confluence-final.tex`. In the proof of CONF Theorem 3.9
(C:1506–1566) the times `s_k` are stopping times of the filtration generated by
`(𝓑^•_s, h|_{𝓑^•_s})`, `h` viewed modulo additive constants (C:1154, 1559–1561). Decision D130 §4
(decisions/DEC-130.md) replaces CONF's tacit assumption on `τ` by `IsLocalSetDet0 P h 𝓑^•_τ`; this
file proves the base `L0` of the iteration and `L3`:

* `t39k_ae_subset_localSigma0`: for a local set `B` modulo constants (`IsLocalSetDet0`) and an
  a.s. bounded random closed set `A`, `{B ⊆ A}` is a.s. a `σ(A, h|_A mod const)`-event
  (`{B ⊆ A} = ⋂_m ⋃_S {A^{(m)} = S} ∩ {B ⊆ int S}`, glued over the hull partition as in
  `LocalEvent.aeEventIn_hullSigma_of_pieces`, whose proof is copied for `hullSigma0`);
* `t39k_filledBall_not_subset`: `𝓑^•_s ⊄ 𝓑^•_q` for `0 ≤ q < s` (length metrics: a point of
  `∂𝓑^•_{(q+s)/2}` is at distance `(q+s)/2`, `GM.jp_frontier_subset_sphere`,
  `GM.gm_not_mem_filledBall_of_frontier`);
* **`t39k_ae_le_localSigma0`** (the piece form for J6c): `{s ≤ q}` is a.s. a
  `localSigma0 h 𝓑^•_q`-event, for `s` with `𝓑^•_s` local mod constants and `s ≥ 0` a.s.;
* **`t39k_ae0_of_isLocalSetDet0`** (L0) and **`t39k_ae_of_ae0`** (L3).

Own routine arguments (CONF uses the stopping-time property without discussing it; the
equivalence `{τ ≤ q} = {𝓑^•_τ ⊆ 𝓑^•_q}` is the one stated in D130 §4 L0).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Set Filter Metric Topology
open LQGMetric.Blueprint

namespace LQGMetric.CONF
open GM LocalEvent

section Gen
variable {Ω : Type} {m0 : MeasurableSpace Ω} {P : Measure[m0] Ω}

theorem t39k1_aeEventIn_mono {m m' : MeasurableSpace Ω} (hmm : m ≤ m') {E : Set Ω}
    (hE : @AEEventIn Ω m0 P m E) : @AEEventIn Ω m0 P m' E := by
  obtain ⟨F, hF, hEF⟩ := hE
  exact ⟨F, hmm _ hF, hEF⟩

theorem t39k1_aeEventIn_iUnion {m : MeasurableSpace Ω} {ι : Type} [Countable ι]
    {E : ι → Set Ω} (hE : ∀ i, @AEEventIn Ω m0 P m (E i)) : @AEEventIn Ω m0 P m (⋃ i, E i) := by
  choose F hF hEF using hE
  exact ⟨⋃ i, F i, MeasurableSet.iUnion (m := m) hF, EventuallyEqSet.countable_iUnion hEF⟩

theorem t39k1_aeEventIn_iInter {m : MeasurableSpace Ω} {ι : Type} [Countable ι]
    {E : ι → Set Ω} (hE : ∀ i, @AEEventIn Ω m0 P m (E i)) : @AEEventIn Ω m0 P m (⋂ i, E i) := by
  choose F hF hEF using hE
  exact ⟨⋂ i, F i, MeasurableSet.iInter (m := m) hF, EventuallyEqSet.countable_iInter hEF⟩

/-- **Gluing over the hull partition, mod constants**: copy of
`LocalEvent.aeEventIn_hullSigma_of_pieces` with `fieldSigma0On` and `hullSigma0`. -/
theorem t39k1_aeEventIn_hullSigma0_of_pieces (h : Ω → DistC) (A : Ω → Set ℂ)
    (hb : ∀ᵐ ω ∂P, Bornology.IsBounded (A ω)) (n : ℕ) {E : Set Ω}
    (hE : ∀ s : Finset (ℤ × ℤ), ∃ F, MeasurableSet[fieldSigma0On h (interior (hullFin n s))] F ∧
      ∀ᵐ ω ∂P, dyadicHull n (A ω) = hullFin n s → (ω ∈ E ↔ ω ∈ F)) :
    AEEventIn P (hullSigma0 h A n) E := by
  choose F hFm hEF using hE
  refine ⟨⋃ s, {ω | dyadicHull n (A ω) = hullFin n s} ∩ F s, ?_, ?_⟩
  · exact MeasurableSet.iUnion fun s => (le_sup_right : _ ≤ hullSigma0 h A n) _
      (MeasurableSpace.measurableSet_generateFrom ⟨hullFin n s, F s, hFm s, rfl⟩)
  · filter_upwards [hb, ae_all_iff.2 hEF] with ω hbω hω
    obtain ⟨s, hs⟩ := exists_hullFin_of_bounded hbω n
    apply propext
    simp only [mem_iUnion, mem_inter_iff, mem_ofPred_eq]
    constructor
    · exact fun hE => ⟨s, hs, (hω s hs).1 hE⟩
    · rintro ⟨s', hs', hF'⟩
      exact (hω s' hs').2 hF'

end Gen

/-- a point in the dyadic hulls of `A` of all levels `≥ n` lies in `cl A` -/
theorem t39k1_mem_closure_of_hull {A : Set ℂ} {x : ℂ} (n : ℕ)
    (hx : ∀ m, x ∈ dyadicHull (n + m) A) : x ∈ closure A := by
  rw [Metric.mem_closure_iff]
  intro ε hε
  obtain ⟨m, hm⟩ := exists_pow_lt_of_lt_one (show 0 < ε / 2 by positivity)
    (show (2 : ℝ)⁻¹ < 1 by norm_num)
  have hx' := hx m
  simp only [dyadicHull, mem_iUnion] at hx'
  obtain ⟨k, ⟨y, hyQ, hyA⟩, hxQ⟩ := hx'
  refine ⟨y, hyA, (conf21_sq_dist hxQ hyQ).trans_lt ?_⟩
  have h2 : (2 : ℝ) ^ m ≤ 2 ^ (n + m) := pow_le_pow_right₀ (by norm_num) (by omega)
  have h1 : (2 : ℝ) / 2 ^ (n + m) ≤ 2 * (2⁻¹) ^ m := by
    rw [inv_pow, ← div_eq_mul_inv]
    exact div_le_div_of_nonneg_left (by norm_num) (by positivity) h2
  linarith

section Subset
variable {Ω : Type} [MeasurableSpace Ω] {P : Measure Ω}

/-- **`{B ⊆ A}` is a.s. an event of `σ(A, h|_A)` mod constants** for a local set `B` modulo
constants and an a.s. bounded random closed set `A` (D130 §4 L0:
`{B ⊆ A} = ⋂_m ⋃_S {A^{(m)} = S} ∩ {B ⊆ int S}`). -/
theorem t39k_ae_subset_localSigma0 (h : Ω → DistC) {A B : Ω → Set ℂ}
    (hA : ∀ ω, IsClosed (A ω)) (hb : ∀ᵐ ω ∂P, Bornology.IsBounded (A ω))
    (hB : IsLocalSetDet0 P h B) :
    AEEventIn P (localSigma0 h A) {ω | B ω ⊆ A ω} := by
  -- the level-`m` approximations
  have hG : ∀ m, AEEventIn P (hullSigma0 h A m) {ω | B ω ⊆ interior (dyadicHull m (A ω))} := by
    intro m
    refine t39k1_aeEventIn_hullSigma0_of_pieces h A hb m fun s => ?_
    obtain ⟨F, hF, hEF⟩ := hB (interior (hullFin m s)) isOpen_interior
    refine ⟨F, hF, ?_⟩
    filter_upwards [hEF] with ω hω hs
    have hω' : (ω ∈ {ω | B ω ⊆ interior (hullFin m s)}) = (ω ∈ F) := hω
    rw [← hω']
    simp only [mem_ofPred_eq, hs]
  refine t39j_aeEventIn_localSigma0 h hA fun n => ?_
  have heq : {ω | B ω ⊆ A ω} =
      ⋂ m : ℕ, {ω | B ω ⊆ interior (dyadicHull (n + m) (A ω))} := by
    ext ω
    simp only [mem_ofPred_eq, mem_iInter]
    constructor
    · exact fun hBA m => hBA.trans (subset_interior_dyadicHull _ _)
    · intro H x hx
      rw [← (hA ω).closure_eq]
      exact t39k1_mem_closure_of_hull n fun m => interior_subset (H m hx)
  rw [heq]
  exact t39k1_aeEventIn_iInter fun m =>
    t39k1_aeEventIn_mono (t39j_hullSigma0_anti h hA (Nat.le_add_right n m)) (hG (n + m))

end Subset

/-- filled balls of a length metric increase strictly: `𝓑^•_s ⊄ 𝓑^•_q` for `0 ≤ q < s` -/
theorem t39k_filledBall_not_subset {d : ContMetric} (hd : d ∈ lenSet) (z₀ : ℂ) {q s : ℝ}
    (hq : 0 ≤ q) (hqs : q < s) : ¬ filledBall d z₀ s ⊆ filledBall d z₀ q := by
  intro hsub
  set r := (q + s) / 2 with hr
  have hqr : q < r := by rw [hr]; linarith
  have hrs : r ≤ s := by rw [hr]; linarith
  have hr0 : 0 < r := hq.trans_lt hqr
  have hbd := gm_filledBall_isBounded_of_lenSet hd z₀ r
  have hne : (frontier (filledBall d z₀ r)).Nonempty := by
    rw [nonempty_frontier_iff]
    refine ⟨⟨z₀, jo_mem_filledBall_self hr0⟩, fun hu => ?_⟩
    rw [hu] at hbd
    exact NormedSpace.unbounded_univ ℝ ℂ hbd
  obtain ⟨y, hy⟩ := hne
  have hyd : d.1 (z₀, y) = r :=
    jp_frontier_subset_sphere (hbd.subset (subset_closure.trans subset_union_left)) hy
  exact gm_not_mem_filledBall_of_frontier hyd hy hqr
    (hsub (gm_filledBall_mono d z₀ hrs ((gm_filledBall_isClosed d z₀ r).frontier_subset hy)))

section Stop
variable {Ω : Type} [MeasurableSpace Ω] {P : Measure Ω}

/-- `{s ≤ q} = {𝓑^•_s ⊆ 𝓑^•_q}` a.s. (`q ≥ 0`), and `= ∅` a.s. (`q < 0`) -/
theorem t39k_ae_le_eq (D : DistC → ContMetric) (h : Ω → DistC) (z₀ : ℂ)
    (hlen : ∀ᵐ ω ∂P, D (h ω) ∈ lenSet) (s : Ω → ℝ) (h0 : ∀ᵐ ω ∂P, 0 ≤ s ω) {q : ℝ}
    (hq : 0 ≤ q) :
    {ω | s ω ≤ q} =ᵐ[P]
      {ω | filledBall (D (h ω)) z₀ (s ω) ⊆ filledBall (D (h ω)) z₀ q} := by
  filter_upwards [hlen, h0] with ω hd _
  apply propext
  constructor
  · exact fun hsq => gm_filledBall_mono _ z₀ hsq
  · intro hsub
    by_contra hlt
    exact t39k_filledBall_not_subset hd z₀ hq (not_le.1 hlt) hsub

/-- **the piece form (for J6c)**: for `s ≥ 0` a.s. with `𝓑^•_s` local modulo constants,
`{s ≤ q}` is a.s. an event of `σ(𝓑^•_q, h|_{𝓑^•_q})` modulo constants. -/
theorem t39k_ae_le_localSigma0 (D : DistC → ContMetric) (h : Ω → DistC) (z₀ : ℂ)
    (hlen : ∀ᵐ ω ∂P, D (h ω) ∈ lenSet) (s : Ω → ℝ)
    (hloc : IsLocalSetDet0 P h (fun ω => filledBall (D (h ω)) z₀ (s ω)))
    (h0 : ∀ᵐ ω ∂P, 0 ≤ s ω) (q : ℝ) :
    AEEventIn P (localSigma0 h (fun ω => filledBall (D (h ω)) z₀ q)) {ω | s ω ≤ q} := by
  rcases lt_or_ge q 0 with hq | hq
  · refine ⟨∅, @MeasurableSet.empty Ω (localSigma0 h (fun ω => filledBall (D (h ω)) z₀ q)), ?_⟩
    filter_upwards [h0] with ω hω
    apply propext
    simp only [mem_empty_iff_false, iff_false, not_le]
    linarith
  · obtain ⟨F, hF, hEF⟩ := t39k_ae_subset_localSigma0 h
      (A := fun ω => filledBall (D (h ω)) z₀ q) (fun ω => gm_filledBall_isClosed _ z₀ q)
      (hlen.mono fun ω hω => gm_filledBall_isBounded_of_lenSet hω z₀ q) hloc
    exact ⟨F, hF, (t39k_ae_le_eq D h z₀ hlen s h0 hq).trans hEF⟩

/-- **L0 (D130 §4)**: a time `τ ≥ 0` (a.s.) whose filled ball is a local set of `h` modulo
additive constants is an a.s. stopping time of the mod-constant filled-ball filtration. -/
theorem t39k_ae0_of_isLocalSetDet0 (D : DistC → ContMetric) (h : Ω → DistC) (z₀ : ℂ)
    (hlen : ∀ᵐ ω ∂P, D (h ω) ∈ lenSet) (τ : Ω → ℝ)
    (hloc : IsLocalSetDet0 P h (fun ω => filledBall (D (h ω)) z₀ (τ ω)))
    (h0 : ∀ᵐ ω ∂P, 0 ≤ τ ω) : IsFilledBallStoppingTimeAE0 P D h z₀ τ := by
  intro t
  have heq : {ω | τ ω < t} = ⋃ q : {q : ℚ // (q : ℝ) < t}, {ω | τ ω ≤ (q : ℝ)} := by
    ext ω
    simp only [mem_ofPred_eq, mem_iUnion, Subtype.exists, exists_prop]
    constructor
    · intro ht
      obtain ⟨q, h1, h2⟩ := exists_rat_btwn ht
      exact ⟨q, h2, h1.le⟩
    · rintro ⟨q, hq, hτq⟩
      exact hτq.trans_lt hq
  rw [heq]
  refine t39k1_aeEventIn_iUnion fun q => t39k1_aeEventIn_mono ?_
    (t39k_ae_le_localSigma0 D h z₀ hlen τ hloc h0 q)
  exact le_iSup₂_of_le (f := fun (u : ℝ) (_ : u ≤ t) =>
    localSigma0 h (fun ω => filledBall (D (h ω)) z₀ u)) (q : ℝ) q.2.le le_rfl

/-- **L3 (D130 §4)**: an a.s. stopping time of the mod-constant filtration is an a.s. stopping
time of the raw filled-ball filtration (field 1 of `T39J6Rest`). -/
theorem t39k_ae_of_ae0 {D : DistC → ContMetric} {h : Ω → DistC} {z₀ : ℂ} {τ : Ω → ℝ}
    (hτ : IsFilledBallStoppingTimeAE0 P D h z₀ τ) : IsFilledBallStoppingTimeAE P D h z₀ τ :=
  fun t => t39k1_aeEventIn_mono
    (iSup₂_mono fun _ _ => localSigma0_le_localSigma h _) (hτ t)

end Stop

/-! ## Field 3 (`hmono`) of `T39J6Rest`: `σ(𝓑^•_s, h|) ⊆ σ(𝓑^•_{s'}, h|)` a.s. mod constants

Mod-constant copy of `GM.gm_localSigma_le_aeSigma` / `GM.gm_hullSigma_le_pieceSig` /
`GM.gmPieceSig` (Papers/GM/S4/Iterate2FiltA.lean, GM (4.9), l. 1650–1654); the hit events of the
smaller set are piecewise local because it is a local set modulo constants. -/

section Mono
variable {Ω : Type} [MeasurableSpace Ω]

/-- events which on `{B^{(n)} = S}` a.s. agree with a `σ(h|_{int S} mod const)`-event (copy of
`GM.gmPieceSig` with `fieldSigma0On`) -/
def t39kPieceSig0 (h : Ω → DistC) (B : Ω → Set ℂ) (n : ℕ) (S : Set ℂ) (P : Measure Ω) :
    MeasurableSpace Ω where
  MeasurableSet' E := ∃ F, MeasurableSet[fieldSigma0On h (interior S)] F ∧
    ∀ᵐ ω ∂P, dyadicHull n (B ω) = S → (ω ∈ E ↔ ω ∈ F)
  measurableSet_empty := ⟨∅, @MeasurableSet.empty Ω (fieldSigma0On _ _),
    Eventually.of_forall fun _ _ => Iff.rfl⟩
  measurableSet_compl := fun E ⟨F, hF, hEF⟩ => ⟨Fᶜ, hF.compl, by
    filter_upwards [hEF] with ω hω hS
    exact not_congr (hω hS)⟩
  measurableSet_iUnion := fun E hE => by
    choose F hF hEF using hE
    refine ⟨⋃ i, F i, MeasurableSet.iUnion hF, ?_⟩
    filter_upwards [ae_all_iff.2 hEF] with ω hω hS
    simp only [mem_iUnion]
    exact exists_congr fun i => hω i hS

omit [MeasurableSpace Ω] in
/-- copy of `GM.gm_dyadicHull_mono` -/
theorem t39k1_dyadicHull_mono (n : ℕ) {A B : Set ℂ} (hAB : A ⊆ B) :
    dyadicHull n A ⊆ dyadicHull n B := by
  intro x hx
  simp only [dyadicHull, mem_iUnion] at hx ⊢
  obtain ⟨k, hk, hxk⟩ := hx
  exact ⟨k, hk.mono (inter_subset_inter_right _ hAB), hxk⟩

/-- one hull level of `σ(A, h|_A mod const)` is piecewise local for `B ⊇ A` (copy of
`GM.gm_hullSigma_le_pieceSig`, inclusion only a.s.) -/
theorem t39k_hullSigma0_le_pieceSig0 (h : Ω → DistC) {P : Measure Ω} {A B : Ω → Set ℂ}
    (hA : ∀ ω, IsClosed (A ω)) (hAB : ∀ᵐ ω ∂P, A ω ⊆ B ω) (n : ℕ) (S' : Set ℂ)
    (hhit : ∀ U : Set ℂ, IsOpen U →
      MeasurableSet[t39kPieceSig0 h B n S' P] {ω | (A ω ∩ U).Nonempty}) :
    hullSigma0 h A n ≤ t39kPieceSig0 h B n S' P := by
  have hset : setSigma A ≤ t39kPieceSig0 h B n S' P :=
    MeasurableSpace.generateFrom_le (by rintro _ ⟨U, hU, rfl⟩; exact hhit U hU)
  refine sup_le hset (MeasurableSpace.generateFrom_le ?_)
  rintro _ ⟨S, F, hF, rfl⟩
  obtain ⟨F₁, hF₁, hE₁⟩ := hset _ (measurableSet_hull_eq hA n S)
  by_cases hSS : S ⊆ S'
  · refine ⟨F₁ ∩ F, hF₁.inter (conf36_fieldSigma0On_mono h (interior_mono hSS) _ hF), ?_⟩
    filter_upwards [hE₁] with ω hω hS
    simp only [mem_inter_iff, mem_ofPred_eq] at hω ⊢
    rw [hω hS]
  · refine ⟨∅, @MeasurableSet.empty Ω (fieldSigma0On _ _), ?_⟩
    filter_upwards [hAB] with ω hω hS
    simp only [mem_inter_iff, mem_ofPred_eq, mem_empty_iff_false, iff_false, not_and]
    intro h1 _
    exact hSS (h1 ▸ hS ▸ t39k1_dyadicHull_mono n hω)

/-- the hit events of a local set `A ⊆ B` modulo constants are piecewise local for `B`:
on `{B^{(n)} = S}`, `{A ∩ U = ∅} = ⋂_j {A ⊆ F_jᶜ ∩ int S}` for closed `F_j ↑ U` -/
theorem t39k_hit_pieceSig0 (h : Ω → DistC) {P : Measure Ω} {A B : Ω → Set ℂ}
    (hloc : IsLocalSetDet0 P h A) (hAB : ∀ᵐ ω ∂P, A ω ⊆ B ω) (n : ℕ) (S : Set ℂ)
    {U : Set ℂ} (hU : IsOpen U) :
    MeasurableSet[t39kPieceSig0 h B n S P] {ω | (A ω ∩ U).Nonempty} := by
  obtain ⟨K, hKc, -, hKU, -⟩ := hU.exists_iUnion_isClosed
  have hG := fun j => hloc ((K j)ᶜ ∩ interior S) ((hKc j).isOpen_compl.inter isOpen_interior)
  choose G hGm hGe using hG
  refine ⟨(⋂ j, G j)ᶜ, MeasurableSet.compl (MeasurableSet.iInter fun j =>
    conf36_fieldSigma0On_mono h inter_subset_right _ (hGm j)), ?_⟩
  filter_upwards [hAB, ae_all_iff.2 hGe] with ω hω hGω hS
  have hAS : A ω ⊆ interior S := hS ▸ hω.trans (subset_interior_dyadicHull n (B ω))
  have key : (A ω ∩ U).Nonempty ↔ ¬ ∀ j, A ω ⊆ (K j)ᶜ ∩ interior S := by
    rw [← hKU]
    constructor
    · rintro ⟨x, hxA, hxU⟩ H
      obtain ⟨j, hj⟩ := mem_iUnion.1 hxU
      exact (H j hxA).1 hj
    · intro H
      by_contra hne
      refine H fun j x hx => ⟨fun hxK => hne ⟨x, hx, mem_iUnion.2 ⟨j, hxK⟩⟩, hAS hx⟩
  have hGj : ∀ j, (A ω ⊆ (K j)ᶜ ∩ interior S) ↔ ω ∈ G j := fun j =>
    Iff.of_eq (hGω j)
  show (A ω ∩ U).Nonempty ↔ ω ∈ (⋂ j, G j)ᶜ
  rw [key, mem_compl_iff, mem_iInter]
  exact not_congr (forall_congr' hGj)

/-- **`σ(A, h|_A) ⊆ σ(B, h|_B)` a.s., modulo constants**, for a local set `A` (mod constants)
contained a.s. in an a.s. bounded random closed set `B` (mod-constant form of
`GM.gm_localSigma_le_aeSigma`). -/
theorem t39k_aeEventIn_localSigma0_of_subset (h : Ω → DistC) {P : Measure Ω} {A B : Ω → Set ℂ}
    (hA : ∀ ω, IsClosed (A ω)) (hB : ∀ ω, IsClosed (B ω))
    (hb : ∀ᵐ ω ∂P, Bornology.IsBounded (B ω)) (hAB : ∀ᵐ ω ∂P, A ω ⊆ B ω)
    (hloc : IsLocalSetDet0 P h A) {E : Set Ω} (hE : MeasurableSet[localSigma0 h A] E) :
    AEEventIn P (localSigma0 h B) E :=
  t39j_aeEventIn_localSigma0 h hB fun n =>
    t39k1_aeEventIn_hullSigma0_of_pieces h B hb n fun _ =>
      t39k_hullSigma0_le_pieceSig0 h hA hAB n _
        (fun _ hU => t39k_hit_pieceSig0 h hloc hAB n _ hU) E
        ((MeasurableSpace.measurableSet_iInf.1 hE) n)

omit [MeasurableSpace Ω] in
/-- `𝓑^•_{ofReal s} = 𝓑^•_s` (also proved as `t39k_filledBallE_ofReal` in S3T39K4) -/
theorem t39k1_filledBallE_ofReal (d : ContMetric) (z₀ : ℂ) (s : ℝ) :
    filledBallE d z₀ (ENNReal.ofReal s) = filledBall d z₀ s := by
  simp only [filledBallE, ENNReal.ofReal_ne_top, ↓reduceIte, ENNReal.toReal_ofReal']
  rcases le_or_gt s 0 with hs | hs
  · rw [max_eq_right hs, gm_filledBall_nonpos d z₀ le_rfl, gm_filledBall_nonpos d z₀ hs]
  · rw [max_eq_left hs.le]

/-- **field 3 (`hmono`) of `T39J6Rest`, generic form**: for `s ≤ s'` a.s. with `𝓑^•_s` local
modulo constants, the `filledBallSigmaAt0 (s)`-events are a.s. `filledBallSigmaAt0 (s')`-events
(GM analogue P412nMain l. 181–184 / `GM.gm_sigA_ae_mono`). -/
theorem t39k_hmono_of_le {P : Measure Ω} (D : DistC → ContMetric) (h : Ω → DistC) (z₀ : ℂ)
    (hlen : ∀ᵐ ω ∂P, D (h ω) ∈ lenSet) (s s' : Ω → ℝ)
    (hloc : IsLocalSetDet0 P h (fun ω => filledBall (D (h ω)) z₀ (s ω)))
    (hss : ∀ᵐ ω ∂P, s ω ≤ s' ω) (A : Set Ω)
    (hA : MeasurableSet[filledBallSigmaAt0 D h z₀ (fun ω => ENNReal.ofReal (s ω))] A) :
    AEEventIn P (filledBallSigmaAt0 D h z₀ (fun ω => ENNReal.ofReal (s' ω))) A := by
  have e : ∀ x : Ω → ℝ, filledBallSigmaAt0 D h z₀ (fun ω => ENNReal.ofReal (x ω)) =
      localSigma0 h (fun ω => filledBall (D (h ω)) z₀ (x ω)) := fun x => by
    unfold filledBallSigmaAt0
    simp_rw [t39k1_filledBallE_ofReal]
  rw [e] at hA ⊢
  exact t39k_aeEventIn_localSigma0_of_subset h (fun ω => gm_filledBall_isClosed _ z₀ _)
    (fun ω => gm_filledBall_isClosed _ z₀ _)
    (hlen.mono fun ω hω => gm_filledBall_isBounded_of_lenSet hω z₀ _)
    (hss.mono fun ω hω => gm_filledBall_mono _ z₀ hω) hloc hA

/-- **field 3 (`hmono`) of `T39J6Rest`** for any sequence of times with local filled balls
(mod constants) and `s k ≤ s (k+1)` a.s.; for `s = t39j7S …` the latter is
`t39j7_le_confSigma` on `{σ < ∞}` (a.s., `t39j6_confSigma_ae_ne_top`). -/
theorem t39k_hmono_seq {P : Measure Ω} (D : DistC → ContMetric) (h : Ω → DistC) (z₀ : ℂ)
    (hlen : ∀ᵐ ω ∂P, D (h ω) ∈ lenSet) (s : ℕ → Ω → ℝ)
    (hloc : ∀ k, IsLocalSetDet0 P h (fun ω => filledBall (D (h ω)) z₀ (s k ω)))
    (hss : ∀ k, ∀ᵐ ω ∂P, s k ω ≤ s (k + 1) ω) :
    ∀ k, ∀ A : Set Ω, MeasurableSet[filledBallSigmaAt0 D h z₀
      (fun ω => ENNReal.ofReal (s k ω))] A →
    AEEventIn P (filledBallSigmaAt0 D h z₀ (fun ω => ENNReal.ofReal (s (k + 1) ω))) A :=
  fun k => t39k_hmono_of_le D h z₀ hlen (s k) (s (k + 1)) (hloc k) (hss k)

end Mono

end LQGMetric.CONF
