import LQGMetric.Blueprint.CONFDefs
import LQGMetric.Papers.CONF.Lift
import LQGMetric.Blueprint.StoppingAE

/-!
# Blueprint: the CONF results used by GM §§2 and 4

Source: Gwynne–Miller, *Confluence of geodesics in Liouville quantum gravity for γ ∈ (0,2)*,
arXiv:1905.00381 (CONF), `literature/src/1905.00381/confluence-final.tex`; GM's restatements:
`literature/src/1905.00383/uniqueness-final.tex` l. 854–856 (GM L2.1), 1096–1168 (GM L2.13, S2.6,
L2.14, T2.15, S2.7, T2.16). Inventory: `blueprint/Confluence.md`, `blueprint/GM_A.md` §2c.

Every Prop is stated as GM uses it: for `γ ∈ (0,2)`, a weak γ-LQG metric `D` with scaling constants
`c` (`IsWeakLQGMetric γ D c`, CONF l. 466: "Let D be a weak γ-LQG metric … and let h be a
whole-plane GFF"), `h` a whole-plane GFF, at a general deterministic centre `𝕫` (CONF: centre `0`;
GM: centre `𝕫` via Axiom IV′ and translation invariance of `h` modulo constants — proposed
deviation BP-M2-CONF-1). The parameters `c, δ, A, η` of CONF §3.2 (fixed after Lemma 3.5,
l. 1286) are shared by Lemmas 3.5, 3.6, 3.8 and Theorem 3.9 (`CONFSection3`).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory ProbabilityTheory Filter Topology Set
open scoped ENNReal

namespace LQGMetric.Blueprint

/-- **CONF Lemma 2.1** (`lem-ball-local`, l. 476–479; GM Lemma 2.1, l. 854–856): "Let `z ∈ ℂ` be
deterministic. If `τ` is a stopping time for the filtration generated by
`(cl 𝓑_s(z;D_h), h|_{cl 𝓑_s(z;D_h)})`, then `cl 𝓑_τ(z;D_h)` is a local set for `h`. The same is
true with `𝓑^•_s(z;D_h)` in place of `cl 𝓑_s(z;D_h)`." Local sets in determined form (D32). -/
def CONFLem2_1 : Prop :=
  ∀ γ : ℝ, 0 < γ → γ < 2 → ∀ (D : DistC → ContMetric) (c : ℝ → ℝ), IsWeakLQGMetric γ D c →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ (z₀ : ℂ) (τ : Ω → ℝ),
      (IsClosedBallStoppingTime D h z₀ τ →
        IsLocalSetDet P h (fun ω => closure (ballM (D (h ω)) z₀ (τ ω)))) ∧
      (IsFilledBallStoppingTime D h z₀ τ →
        IsLocalSetDet P h (fun ω => filledBall (D (h ω)) z₀ (τ ω)))

/-- **CONF Lemma 2.2** (`lem-geo-unique`, l. 505–507, from the proof of MQ Thm 1.2): "Almost
surely, for each `q ∈ ℚ²` there is only one `D_h`-geodesic from 0 to `q`." (centre `𝕫`) -/
def CONFLem2_2 : Prop :=
  ∀ γ : ℝ, 0 < γ → γ < 2 → ∀ (D : DistC → ContMetric) (c : ℝ → ℝ), IsWeakLQGMetric γ D c →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ z₀ : ℂ, ∀ᵐ ω ∂P, ∀ q : ℚ × ℚ, UniqueGeod (D (h ω)) z₀ (ratPt q)

/-- **CONF Lemma 2.4** (`lem-leftmost-geodesic`, l. 533–537): "Almost surely, for each `s > 0` and
each `y ∈ ∂𝓑^•_s`, there exists a unique leftmost (resp. rightmost) geodesic `P_y^-` (resp.
`P_y^+`) from 0 to `y` such that each `D_h`-geodesic from 0 to `y` lies (weakly) to the right
(resp. left) of `P_y^-` (resp. `P_y^+`) … Moreover, there are sequences of points
`q_n^-, q_n^+ ∈ ℚ² ∖ 𝓑^•_s` such that the `D_h`-geodesics from 0 to `q_n^±` satisfy
`P_{q_n^±} → P_y^±` uniformly." With leftmost/rightmost read by `IsSideGeod` (existence, uniqueness
on `[0,s]`, rational approximation on `[0,s]`); the clause "each geodesic lies weakly to the right"
has no formal counterpart (CONF defines no "left of"). -/
def CONFLem2_4 : Prop :=
  ∀ γ : ℝ, 0 < γ → γ < 2 → ∀ (D : DistC → ContMetric) (c : ℝ → ℝ), IsWeakLQGMetric γ D c →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ z₀ : ℂ, ∀ᵐ ω ∂P, ∀ s : ℝ, 0 < s →
      ∀ y ∈ frontier (filledBall (D (h ω)) z₀ s), ∀ left : Bool,
        (∃ Q, IsSideGeod left (D (h ω)) z₀ s y Q) ∧
        (∀ Q Q', IsSideGeod left (D (h ω)) z₀ s y Q → IsSideGeod left (D (h ω)) z₀ s y Q' →
          EqOn Q Q' (Icc 0 s)) ∧
        ∀ Q, IsSideGeod left (D (h ω)) z₀ s y Q →
          ∃ (q : ℕ → ℚ × ℚ) (Qn : ℕ → ℝ → ℂ),
            (∀ n, ratPt (q n) ∉ filledBall (D (h ω)) z₀ s) ∧
            (∀ n, IsGeodesicL (D (h ω)) (Qn n) ((D (h ω)).1 (z₀, ratPt (q n))) z₀ (ratPt (q n))) ∧
            Tendsto (fun n => supDistOn (Qn n) Q s) atTop (𝓝 0)

/-- **CONF Lemma 2.7** (`lem-geo-arc`, l. 617–622): "Almost surely, the following is true for each
`0 < s < s′ < ∞`. Let `𝓘` be a finite collection of disjoint arcs of `∂𝓑^•_s`. For each `I ∈ 𝓘`,
let `I′` be the set of `y ∈ ∂𝓑^•_{s′}` such that the leftmost `D_h`-geodesic from 0 to `y` passes
through `I`. Then each `I′` is either empty or is a connected arc of `∂𝓑^•_{s′}` and the arcs `I′`
for different choices of `I ∈ 𝓘` are disjoint." (centre `𝕫`; arcs as in `IsBdyArc`) -/
def CONFLem2_7 : Prop :=
  ∀ γ : ℝ, 0 < γ → γ < 2 → ∀ (D : DistC → ContMetric) (c : ℝ → ℝ), IsWeakLQGMetric γ D c →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ z₀ : ℂ, ∀ᵐ ω ∂P, ∀ s s' : ℝ, 0 < s → s < s' →
      ∀ 𝓘 : Set (Set ℂ), 𝓘.Finite → (∀ I ∈ 𝓘, IsBdyArc (D (h ω)) z₀ s I) → 𝓘.PairwiseDisjoint id →
        (∀ I ∈ 𝓘, {y | y ∈ frontier (filledBall (D (h ω)) z₀ s') ∧ ∃ Q,
            IsLeftmostGeod (D (h ω)) z₀ s' y Q ∧ ∃ u ∈ Icc 0 s', Q u ∈ I} = ∅ ∨
          IsBdyArc (D (h ω)) z₀ s' {y | y ∈ frontier (filledBall (D (h ω)) z₀ s') ∧ ∃ Q,
            IsLeftmostGeod (D (h ω)) z₀ s' y Q ∧ ∃ u ∈ Icc 0 s', Q u ∈ I}) ∧
        𝓘.PairwiseDisjoint (fun I => {y | y ∈ frontier (filledBall (D (h ω)) z₀ s') ∧ ∃ Q,
            IsLeftmostGeod (D (h ω)) z₀ s' y Q ∧ ∃ u ∈ Icc 0 s', Q u ∈ I})

/-- **CONF Theorem 1.4** (`thm-finite-geo0`, l. 380–382; GM Thm 2.15, l. 1142–1144): "Fix
`z ∈ ℂ`. Almost surely, for each `0 < t < s < ∞` there is a finite set of `D_h`-geodesics from
[`z`] to `∂𝓑^•_t(z;D_h)` such that every leftmost `D_h`-geodesic from [`z`] to `∂𝓑^•_s(z;D_h)`
coincides with one of these `D_h`-geodesics on the time interval `[0,t]`. In particular, there are
a.s. only finitely many points of `∂𝓑^•_t(z;D_h)` which are hit by leftmost `D_h`-geodesics from
[`z`] to `∂𝓑^•_s(z;D_h)`." (CONF l. 381 writes "from 0"; GM's centre-`𝕫` form.) -/
def CONFThm1_4 : Prop :=
  ∀ γ : ℝ, 0 < γ → γ < 2 → ∀ (D : DistC → ContMetric) (c : ℝ → ℝ), IsWeakLQGMetric γ D c →
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ z₀ : ℂ, ∀ᵐ ω ∂P, ∀ t s : ℝ, 0 < t → t < s →
      (∃ F : Set (ℝ → ℂ), F.Finite ∧
        (∀ Q ∈ F, ∃ x ∈ frontier (filledBall (D (h ω)) z₀ t), IsGeodesicL (D (h ω)) Q t z₀ x) ∧
        ∀ y Q, IsLeftmostGeod (D (h ω)) z₀ s y Q → ∃ Q' ∈ F, EqOn Q Q' (Icc 0 t)) ∧
      (hitSet (D (h ω)) z₀ t s).Finite

/-! ## CONF §3: the parameter-dependent statements -/

/-- CONF l. 1262–1286 parameter ranges: `c, δ ∈ (0,1)`, `A > 0`, `η > 0` -/
def CONFParams.Valid (p : CONFParams) : Prop :=
  0 < p.c ∧ p.c < 1 ∧ 0 < p.δ ∧ p.δ < 1 ∧ 0 < p.A ∧ 0 < p.η

/-- the conclusion of **CONF Lemma 3.5** (`lem-clsce-all`, l. 1276–1282; GM Lemma 2.13,
l. 1099–1108, which adds the centre `𝕫`) for the parameters `p`: "For each compact set `K ⊂ ℂ`, it
holds with probability `1 − O_ε(ε²)` (at a rate depending on `K`) that
`ρ^{⌊η log ε⁻¹⌋}_{ε𝕣}(z) ≤ ε^{1/2}𝕣` for all `z ∈ (ε𝕣/4)ℤ² ∩ B_{ε𝕣}(𝕣K [+ 𝕫])`", uniformly in
`𝕣` (and `𝕫`). -/
def CONFLem3_5At (γ : ℝ) (D : DistC → ContMetric) (c : ℝ → ℝ) (p : CONFParams) : Prop :=
  ∀ K : Set ℂ, IsCompact K → ∃ C₀ ε₀ : ℝ, 0 < C₀ ∧ 0 < ε₀ ∧
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ (z₀ : ℂ) (R : ℝ), 0 < R → ∀ ε ∈ Ioo 0 ε₀,
      P {ω | ∃ z ∈ gridPts (ε * R / 4) ∩ Metric.thickening (ε * R) ((fun x => R * x + z₀) '' K),
        ENNReal.ofReal (ε ^ (1 / 2 : ℝ) * R) <
          confRho (xiGamma γ) c D P h p (ε * R) z (confN p ε) ω} ≤ ENNReal.ofReal (C₀ * ε ^ 2)

/-- **CONF Lemma 3.6, a.s. form modulo additive constants** (D108 (a), moved from
`Papers/CONF/S3D108A.lean` by D110 P1; C:1308–1320 with the field "viewed modulo additive
constant", C:347, 1154, 1187). As `CONFLem3_6AtAE` (D106) with: the σ-algebras `σ(𝓑^•_τ, h|_{𝓑^•_τ})`,
`σ(𝓑^•_{σ^ε_{τ,𝕣}}, h|_{𝓑^•_{σ^ε_{τ,𝕣}}})` read modulo additive constants (`localSigma0`,
`filledBallSigmaAt0`), and the hypothesis that `𝓑^•_τ` is a local set modulo constants
(`IsLocalSetDet0`; CONF Lemma 2.1 as used at C:1431). D114: the sub-σ-algebra hypothesis
`localSigma0 h 𝓑^•_τ ≤ mΩ` (tacit in CONF/GM, GM l. 854), a countably valued `ε` (CONF's Step 3
conditions on `{ε = 𝔢, …}`, C:1438), and "`G ∈ σ(𝓑^•_{σ^ε}, …)`" (C:1313) read as `AEEventIn`
(a.s. equal to an event of that σ-algebra; D30, forced by the a.s. Axiom II). D120: the
stopping-time hypothesis is almost sure (`IsFilledBallStoppingTimeAE`, `Blueprint/StoppingAE.lean`;
CONF l. 1302, GM l. 2189). -/
def CONFLem3_6AtAE0 (γ : ℝ) (D : DistC → ContMetric) (c : ℝ → ℝ) (p : CONFParams) : Prop :=
  ∃ α C₀ : ℝ, 0 < α ∧ 1 < C₀ ∧
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ (z₀ : ℂ) (R : ℝ), 0 < R → ∀ τ : Ω → ℝ,
      IsFilledBallStoppingTimeAE P D h z₀ τ →
      IsLocalSetDet0 P h (fun ω => filledBall (D (h ω)) z₀ (τ ω)) →
      localSigma0 h (fun ω => filledBall (D (h ω)) z₀ (τ ω)) ≤ ‹MeasurableSpace Ω› →
      ∀ (x : Ω → ℂ) (ε : Ω → ℝ),
      @Measurable Ω ℂ (localSigma0 h (fun ω => filledBall (D (h ω)) z₀ (τ ω))) _ x →
      @Measurable Ω ℝ (localSigma0 h (fun ω => filledBall (D (h ω)) z₀ (τ ω))) _ ε →
      (∀ᵐ ω ∂P, x ω ∈ frontier (filledBall (D (h ω)) z₀ (τ ω))) → (∀ ω, ε ω ∈ Ioo 0 1) →
      (Set.range ε).Countable →
      ∃ G : Set Ω,
        AEEventIn P (filledBallSigmaAt0 D h z₀
          (fun ω => confSigma (xiGamma γ) c D P h p z₀ R (ε ω) (τ ω) ω)) G ∧
        (∀ ω ∈ G, x ω ∈ frontier (filledBall (D (h ω)) z₀ (τ ω)) →
          confRK (xiGamma γ) c D P h p R (ε ω) (filledBall (D (h ω)) z₀ (τ ω)) ω ≤
            Metric.ediam (filledBall (D (h ω)) z₀ (τ ω)) →
          ∀ (y : ℂ) (Q : ℝ → ℂ) (L : ℝ),
            y ∉ enbhd (confRK (xiGamma γ) c D P h p R (ε ω) (filledBall (D (h ω)) z₀ (τ ω)) ω)
              (filledBall (D (h ω)) z₀ (τ ω)) →
            IsGeodesicL (D (h ω)) Q L z₀ y → ∀ u ∈ Icc 0 L,
              Q u ∉ Metric.ball (x ω) (ε ω * R) \ filledBall (D (h ω)) z₀ (τ ω)) ∧
        ∀ᵐ ω ∂P, 1 - C₀ * ε ω ^ α ≤
          (P[G.indicator (fun _ => (1 : ℝ)) |
            localSigma0 h (fun ω => filledBall (D (h ω)) z₀ (τ ω))]) ω

/-- the conclusion of **CONF Lemma 3.8** (`lem-finite-geo-reg`, l. 1493–1495; GM S2.7,
l. 1153–1160, uniform in `𝕫`) for the parameters `p` and the Hölder exponent `χ`: "For each
`p ∈ (0,1)`, there exists `a = a(p) > 0` such that `P[𝓔_𝕣(a)] ≥ p` for every `𝕣 > 0`."
("`P[E] ≥ q`" in the D30 form `P Eᶜ ≤ 1 − q`, D58.) -/
def CONFLem3_8At (γ : ℝ) (D : DistC → ContMetric) (c : ℝ → ℝ) (p : CONFParams) (χ : ℝ) : Prop :=
  ∀ q ∈ Ioo (0 : ℝ) 1, ∃ a ∈ Ioo (0 : ℝ) 1,
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ (z₀ : ℂ) (R : ℝ), 0 < R →
      P (confReg (xiGamma γ) c D P h p χ z₀ R a)ᶜ ≤ ENNReal.ofReal (1 - q)

/-- CONF's `X_{t,s}` (l. 1049): the points of `∂𝓑^•_t(z; D)` hit by leftmost `D`-geodesics from
`z` to `∂𝓑^•_s(z; D)`, with "leftmost" read literally as in CONF Lemma 2.4 (l. 533–537): every
geodesic to the endpoint lies weakly to its right (decision D44 = D-D1, `CONF.DD.IsLeftmostGeod`;
D76). It is `GM.hitSetDD` (`Papers/GM/S4/P412Step12.lean`) verbatim. -/
def hitSetLM (D : ContMetric) (z : ℂ) (t s : ℝ) : Set ℂ :=
  {x | x ∈ frontier (filledBall D z t) ∧
    ∃ y P, CONF.DD.IsLeftmostGeod D z s y P ∧ ∃ u ∈ Icc 0 s, P u = x}

/-- the conclusion of **CONF Theorem 3.9** (`thm-finite-geo-quant`, l. 1506–1509; GM Thm 2.16,
l. 1165–1168) for `p`, `χ`: "For each `a ∈ (0,1)`, there is a constant `b₀ > 0` depending only on
`a` and constants `b₁, β > 0` depending only on the choice of metric `D` such that … for each
`𝕣 > 0`, each `N ∈ ℕ`, and each stopping time `τ` for `{(𝓑^•_s, h|_{𝓑^•_s})}` with
`τ ∈ [τ_𝕣, τ_{2𝕣}]` a.s., the probability that `𝓔_𝕣(a)` occurs and there are more than `N` points
of `∂𝓑^•_τ` which are hit by leftmost `D_h`-geodesics from 0 to
`∂𝓑^•_{τ + N^{−β}𝔠_𝕣e^{ξh_𝕣(0)}}` is at most `b₀e^{−b₁N^β}`." (centre `𝕫`; `ℕ = {1,2,…}`).
Leftmost geodesics as in CONF Lemma 2.4 (D44; the count is `hitSetLM`, D76).
The stopping time `τ` is also assumed to have `𝓑^•_τ` local modulo additive constants
(`IsLocalSetDet0`; D130; CONF C:1431 via L2.1 with `h` modulo constants, C:1154), as in
`CONFLem3_6AtAE0` (D108). -/
def CONFThm3_9At (γ : ℝ) (D : DistC → ContMetric) (c : ℝ → ℝ) (p : CONFParams) (χ : ℝ) : Prop :=
  ∃ b₁ β : ℝ, 0 < b₁ ∧ 0 < β ∧ ∀ a ∈ Ioo (0 : ℝ) 1, ∃ b₀ : ℝ, 0 < b₀ ∧
  ∀ {Ω : Type} [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P] (h : Ω → DistC),
    IsWholePlaneGFF h P → ∀ (z₀ : ℂ) (R : ℝ), 0 < R → ∀ N : ℕ, 1 ≤ N → ∀ τ : Ω → ℝ,
      IsFilledBallStoppingTime D h z₀ τ →
      IsLocalSetDet0 P h (fun ω => filledBall (D (h ω)) z₀ (τ ω)) →
      (∀ᵐ ω ∂P, τ ω ∈ Icc (tauR D h z₀ R ω) (tauR D h z₀ (2 * R) ω)) →
      P {ω | ω ∈ confReg (xiGamma γ) c D P h p χ z₀ R a ∧
          ((N : ℕ∞) : ℕ∞) < (hitSetLM (D (h ω)) z₀ (τ ω)
            (τ ω + (N : ℝ) ^ (-β) * scaleFac (xiGamma γ) c (h ω) R z₀)).encard} ≤
        ENNReal.ofReal (b₀ * Real.exp (-b₁ * (N : ℝ) ^ β))

/-- **CONF §3 package** (Lemmas 3.5, 3.6, 3.8, Theorem 3.9 with one choice of the parameters
`c, δ, A, η`, "depending only on the choice of metric `D`", CONF l. 1277, 1286, 1476; any fixed
Hölder exponent `χ ∈ (0, ξ(Q−2))`, l. 1480–1481). This is the form GM §4 uses (GM l. 1096–1168).
Lemma 3.6 is in its true form `CONFLem3_6AtAE0` (modulo additive constants; D108, D110). -/
def CONFSection3 : Prop :=
  ∀ γ : ℝ, 0 < γ → γ < 2 → ∀ (D : DistC → ContMetric) (c : ℝ → ℝ), IsWeakLQGMetric γ D c →
    ∃ p : CONFParams, p.Valid ∧ CONFLem3_5At γ D c p ∧ CONFLem3_6AtAE0 γ D c p ∧
      ∀ χ ∈ Ioo (0 : ℝ) (xiGamma γ * (Q γ - 2)), CONFLem3_8At γ D c p χ ∧ CONFThm3_9At γ D c p χ

end LQGMetric.Blueprint
