import QuantumZipper.Proofs.GFF.K3.HalfDiscTV
import QuantumZipper.Proofs.LQG.WedgeToolkit
import QuantumZipper.Proofs.Probability.GermZeroOne
import Mathlib.MeasureTheory.Measure.HasOuterApproxClosed
import Mathlib.MeasureTheory.Constructions.Polish.StronglyMeasurable
import Mathlib.Analysis.SpecialFunctions.SmoothTransition
import Mathlib.Analysis.SpecialFunctions.Complex.LogDeriv
import Mathlib.Analysis.Calculus.ParametricIntegral
import Mathlib.Analysis.Complex.CauchyIntegral
import Mathlib.MeasureTheory.Measure.Lebesgue.VolumeOfBalls

/-!
# Lateral germ triviality of the free field (blueprint E-L11)

For a free-boundary GFF modulo constants `X` on `ℍ` (`IsFreeGFFModConstH X P`), the germ at `0`
of its lateral part is trivial:
`isTrivialSigma_lateralGerm : IsTrivialSigma (⨅ n, lateralGerm X P (2⁻¹ ^ n)) P`.

**Deviation from TASKS.md R5 (statement).** `lateralGerm X P r` is generated by
`lateralPart (X ·) μ` only at those admissible `μ` carried by `closedBall 0 r ∩ Hbar` at which the
canonical regularization is almost surely exact, `∀ᵐ ω ∂P, evalReg (X ω) μ = X ω μ` (hence the
extra argument `P`). This class contains every folded circle (`WedgeTK.ae_evalReg_fc`) and every
bounded density (`ae_evalReg_eq_withDensity`), i.e. everything the regularized evaluations of the
wedge field read. For a general admissible `μ` no such identity is known: `evalReg` is a limit of
circle-average integrals along the fixed radii `2^{-k}`, whose almost sure convergence needs a
rate that bounded log-potential alone does not give; where it fails, `lateralPart (X ω) μ` is the
junk value of `limUnder` minus a radial integral, and it depends on the (arbitrary, possibly
random) additive constant of `X`, which the free field modulo constants does not control.

**Proof (own argument, modelled on Duplantier–Miller–Sheffield, arXiv:1409.7055, Lemma 7.2,
p. 127).** DMS show that the conditional law of every test pairing given the germ is the
unconditional one, using the Markov property in the exterior of a small half-disc. The exterior
Markov property is not available here, so we use the interior one (blueprint L2, `K3`) at a fixed
outer radius `r` and a Hilbert-space decomposition instead:

1. (`indep_germ_outside`) Let `W = X ν - X ν'` with `ν, ν'` carried outside `B(0,r)`. Its covariance
   with a germ coordinate `X μ - X(radSmear μ)` is `∫ u d(μ - radSmear μ)`, where `u` is the
   `neumannH`-potential of `ν - ν'`, smooth on `B(0,r)` (`contDiffOn_potN`: it is the real part of
   a holomorphic parameter integral). With `φ_ρ = χ(·/ρ)(u - u 0)` and the measures
   `m± = (2π)⁻¹(∓Δφ_ρ)^± dy` on `H`, the local variable `Z(m⁺) - Z(m⁻)` of the half-disc Markov
   decomposition has the same covariances with the germ at scale `ρ/2` (Green representation,
   L3 `halfDiscGreen_represent`) and variance `E_H(φ_ρ) = O(ρ²)` (L3 energy identity). Hence
   `V_ρ = W - Z(m⁺) + Z(m⁻)` is jointly Gaussian with and uncorrelated with the germ, so
   independent of it, and `V_ρ → W` a.s. along `ρ_j = (r/4)2^{-j}`. Independence passes to a.s.
   limits (`indep_comap_of_tendsto_ae`), so the germ is independent of the field outside `B(0,r)`.
2. (`exists_outside_version`) Every germ coordinate is an a.s. limit of pairings of measures
   avoiding small discs (`μ|_{B(0,δ)ᶜ}`, with an `L²` error `O(μ(B(0,δ)))`).
3. The germ is independent of `⨆_r outsideSigma X 0 r` and contained in it up to null sets, so it is
   independent of itself.

Sources: Duplantier–Miller–Sheffield, *Liouville quantum gravity as a mating of trees*,
arXiv:1409.7055, Lemma 7.2 (structure of the argument); Sheffield, *Gaussian free fields for
mathematicians* (math/0312099), §2.6 (domain Markov property, in-project as blueprint L2);
Bogachev, *Gaussian Measures*, Thm 2.4.5 is **not** needed (no Cameron–Martin step).

-/

noncomputable section

open MeasureTheory ProbabilityTheory Filter Set Metric Laplacian Topology
open scoped Real ComplexConjugate ENNReal NNReal

namespace QuantumZipper
namespace LateralGerm

open K3 CircleFubini

/-! ## 0. Probability toolkit -/

section Prob

variable {Ω : Type*} {m m' m₁ m₂ m₃ a a' b b' : MeasurableSpace Ω} [mΩ : MeasurableSpace Ω]
  {P : Measure Ω}

/-! ## Inclusion of σ-algebras up to null sets -/

/-- `m₁` is contained in `m₂` up to `P`-null sets. -/
def AESub (m₁ m₂ : MeasurableSpace Ω) (P : @Measure Ω mΩ) : Prop :=
  ∀ s, MeasurableSet[m₁] s → ∃ t, MeasurableSet[m₂] t ∧ s =ᵐ[P] t

/-- The σ-algebra of sets a.e. equal to a set of `m`. -/
@[instance_reducible]
def aeClosure (m : MeasurableSpace Ω) (P : @Measure Ω mΩ) : MeasurableSpace Ω where
  MeasurableSet' s := ∃ t, MeasurableSet[m] t ∧ s =ᵐ[P] t
  measurableSet_empty := ⟨∅, @MeasurableSet.empty _ m, EventuallyEqSet.rfl⟩
  measurableSet_compl s := by
    rintro ⟨t, ht, hst⟩
    exact ⟨tᶜ, ht.compl, hst.compl⟩
  measurableSet_iUnion f hf := by
    choose t ht hft using hf
    exact ⟨⋃ i, t i, MeasurableSet.iUnion ht, EventuallyEqSet.countable_iUnion hft⟩

lemma aeSub_of_le (h : m₁ ≤ m₂) : AESub m₁ m₂ P :=
  fun s hs => ⟨s, h s hs, EventuallyEqSet.rfl⟩

lemma AESub.trans (h₁ : AESub m₁ m₂ P) (h₂ : AESub m₂ m₃ P) :
    AESub m₁ m₃ P := fun s hs => by
  obtain ⟨t, ht, hst⟩ := h₁ s hs
  obtain ⟨u, hu, htu⟩ := h₂ t ht
  exact ⟨u, hu, hst.trans htu⟩

lemma aeSub_iSup {ι : Sort*} {M : ι → MeasurableSpace Ω}
    (h : ∀ i, AESub (M i) m' P) : AESub (⨆ i, M i) m' P :=
  (iSup_le (fun i => (h i : M i ≤ aeClosure m' P)) : (⨆ i, M i) ≤ aeClosure m' P)

lemma aeSub_comap {β : Type*} [MeasurableSpace β] {f g : Ω → β}
    (hg : Measurable[m'] g) (hfg : f =ᵐ[P] g) :
    AESub (MeasurableSpace.comap f inferInstance) m' P := by
  rintro s ⟨B, hB, rfl⟩
  refine ⟨g ⁻¹' B, hg hB, ?_⟩
  change ∀ᵐ ω ∂P, (ω ∈ f ⁻¹' B) = (ω ∈ g ⁻¹' B)
  filter_upwards [hfg] with ω hω
  simp only [Set.mem_preimage, hω]

lemma indep_of_aeSub (h : Indep a' b' P) (ha : AESub a a' P)
    (hb : AESub b b' P) : Indep a b P := by
  rw [Indep_iff] at h ⊢
  intro s t hs ht
  obtain ⟨s', hs', hss⟩ := ha s hs
  obtain ⟨t', ht', htt⟩ := hb t ht
  rw [measure_congr hss, measure_congr htt, measure_congr (hss.inter htt)]
  exact h s' t' hs' ht'

/-- A σ-algebra independent of a σ-algebra containing it up to null sets is trivial. -/
lemma isTrivialSigma_of_indep_aeSub [IsProbabilityMeasure P]
    (hind : Indep m m' P) (hsub : AESub m m' P) : GermZeroOne.IsTrivialSigma m P :=
  GermZeroOne.isTrivialSigma_of_indep_self (indep_of_aeSub hind (aeSub_of_le le_rfl) hsub)

/-! ## Independence passes to almost sure limits -/

lemma integral_indicator_mul_of_indep [IsProbabilityMeasure P]
    (hm : m ≤ mΩ) {E : Type*} [TopologicalSpace E] [MeasurableSpace E] [OpensMeasurableSpace E]
    {Y : Ω → E} (hY : Measurable Y) (hind : Indep m (MeasurableSpace.comap Y inferInstance) P)
    {s : Set Ω} (hs : MeasurableSet[m] s) {f : E → ℝ} (hf : Continuous f) :
    ∫ ω in s, f (Y ω) ∂P = (P s).toReal * ∫ ω, f (Y ω) ∂P := by
  have h1 : StronglyMeasurable[m] (s.indicator fun _ : Ω => (1 : ℝ)) :=
    (stronglyMeasurable_const.indicator hs)
  have h2 : StronglyMeasurable[MeasurableSpace.comap Y inferInstance] fun ω => f (Y ω) :=
    (hf.measurable.comp (comap_measurable Y)).stronglyMeasurable
  have key := GermZeroOne.integral_mul_of_indep hind h1 h2 hm hY.comap_le
  have e1 : (fun ω => s.indicator (fun _ : Ω => (1 : ℝ)) ω * f (Y ω)) =
      s.indicator fun ω => f (Y ω) := by
    funext ω; by_cases h : ω ∈ s <;> simp [h]
  rw [e1, integral_indicator (hm s hs), integral_indicator_const _ (hm s hs), smul_eq_mul,
    mul_one] at key
  rw [key, measureReal_def]

/-- If `m` is independent of each `Y j` and `Y j → Ylim` almost surely, then `m` is independent
of `Ylim`. -/
lemma indep_comap_of_tendsto_ae [IsProbabilityMeasure P] (hm : m ≤ mΩ)
    {E : Type*} [PseudoMetricSpace E] [MeasurableSpace E] [BorelSpace E]
    {Y : ℕ → Ω → E} {Ylim : Ω → E} (hY : ∀ j, Measurable (Y j)) (hYlim : Measurable Ylim)
    (hind : ∀ j, Indep m (MeasurableSpace.comap (Y j) inferInstance) P)
    (hlim : ∀ᵐ ω ∂P, Tendsto (fun j => Y j ω) atTop (𝓝 (Ylim ω))) :
    Indep m (MeasurableSpace.comap Ylim inferInstance) P := by
  rw [Indep_iff]
  rintro s _ hs ⟨A, hA, rfl⟩
  have key : (P.restrict s).map Ylim = (P s).toNNReal • P.map Ylim := by
    apply ext_of_forall_integral_eq_of_IsFiniteMeasure
    intro f
    rw [integral_map hYlim.aemeasurable f.continuous.aestronglyMeasurable,
      integral_smul_nnreal_measure,
      integral_map hYlim.aemeasurable f.continuous.aestronglyMeasurable]
    have hconv : ∀ (μ : Measure Ω) [IsFiniteMeasure μ], μ ≪ P →
        Tendsto (fun j => ∫ ω, f (Y j ω) ∂μ) atTop (𝓝 (∫ ω, f (Ylim ω) ∂μ)) := by
      intro μ _ hμ
      refine tendsto_integral_of_dominated_convergence (fun _ => ‖f‖)
        (fun j => (f.continuous.measurable.comp (hY j)).aestronglyMeasurable)
        (integrable_const _) (fun j => ae_of_all _ fun ω => f.norm_coe_le_norm _) ?_
      filter_upwards [hμ.ae_le hlim] with ω hω
      exact (f.continuous.tendsto _).comp hω
    have h1 := hconv (P.restrict s) (Measure.absolutelyContinuous_of_le Measure.restrict_le_self)
    have h2 := (hconv P (Measure.AbsolutelyContinuous.refl _)).const_mul (P s).toReal
    have hj : ∀ j, ∫ ω in s, f (Y j ω) ∂P = (P s).toReal * ∫ ω, f (Y j ω) ∂P := fun j =>
      integral_indicator_mul_of_indep hm (hY j) (hind j) hs f.continuous
    simp_rw [hj] at h1
    rw [tendsto_nhds_unique h1 h2, NNReal.smul_def, smul_eq_mul,
      ENNReal.coe_toNNReal_eq_toReal]
  have hA' := congrArg (fun μ : Measure E => μ A) key
  simp only [Measure.map_apply hYlim hA, Measure.restrict_apply (hYlim hA),
    Measure.smul_apply, ENNReal.smul_def, smul_eq_mul, ENNReal.coe_toNNReal (measure_ne_top P s)]
    at hA'
  rw [Set.inter_comm, hA']

/-! ## Summable second moments give almost sure convergence -/

lemma ae_tendsto_zero_of_summable_sq {f : ℕ → Ω → ℝ} (hf : ∀ j, AEMeasurable (f j) P)
    (hint : ∀ j, Integrable (fun ω => f j ω ^ 2) P)
    (hs : Summable fun j => ∫ ω, f j ω ^ 2 ∂P) :
    ∀ᵐ ω ∂P, Tendsto (fun j => f j ω) atTop (𝓝 0) := by
  have hm : ∀ j, AEMeasurable (fun ω => ENNReal.ofReal (f j ω ^ 2)) P :=
    fun j => ((hf j).pow_const 2).ennreal_ofReal
  have h : ∫⁻ ω, ∑' j, ENNReal.ofReal (f j ω ^ 2) ∂P ≠ ⊤ := by
    rw [lintegral_tsum hm]
    have e : ∀ j, ∫⁻ ω, ENNReal.ofReal (f j ω ^ 2) ∂P = ENNReal.ofReal (∫ ω, f j ω ^ 2 ∂P) :=
      fun j => (ofReal_integral_eq_lintegral_ofReal (hint j)
        (ae_of_all _ fun ω => sq_nonneg _)).symm
    simp_rw [e]
    rw [← ENNReal.ofReal_tsum_of_nonneg (fun j => integral_nonneg fun ω => sq_nonneg _) hs]
    exact ENNReal.ofReal_ne_top
  filter_upwards [ae_lt_top' (AEMeasurable.ennreal_tsum hm) h] with ω hω
  have hsum : Summable fun j => f j ω ^ 2 :=
    (ENNReal.summable_toReal hω.ne).congr fun j => ENNReal.toReal_ofReal (sq_nonneg _)
  have h2 := hsum.tendsto_atTop_zero.sqrt
  simp only [Real.sqrt_sq_eq_abs, Real.sqrt_zero] at h2
  exact tendsto_zero_iff_norm_tendsto_zero.2 (by simpa [Real.norm_eq_abs] using h2)

/-- An almost sure limit of `m`-measurable functions has an `m`-measurable version. -/
lemma comap_le_comap_of_comp {α β γ : Type*} [MeasurableSpace β] [MeasurableSpace γ]
    {F : α → β} {R : β → γ} (hR : Measurable R) :
    MeasurableSpace.comap (R ∘ F) inferInstance ≤ MeasurableSpace.comap F inferInstance := by
  rw [← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono hR.comap_le

lemma exists_measurable_ae_eq_of_tendsto {Y : ℕ → Ω → ℝ} {Z : Ω → ℝ}
    (hY : ∀ j, Measurable[m] (Y j))
    (hlim : ∀ᵐ ω ∂P, Tendsto (fun j => Y j ω) atTop (𝓝 (Z ω))) :
    ∃ g : Ω → ℝ, Measurable[m] g ∧ Z =ᵐ[P] g := by
  refine ⟨fun ω => limUnder atTop fun j => Y j ω, ?_, ?_⟩
  · letI := m
    exact (StronglyMeasurable.limUnder fun j => (hY j).stronglyMeasurable).measurable
  · filter_upwards [hlim] with ω hω
    exact hω.limUnder_eq.symm

end Prob

/-! ## 1. The log potential of a measure outside a disc is smooth inside the disc -/

/-- `log(1 - x/y) + log(1 - x/ȳ)`: for `‖x‖ < ‖y‖`, its real part is
`log ‖x - y‖ + log ‖x - ȳ‖ - 2 log ‖y‖`. -/
def logTerm (x y : ℂ) : ℂ := Complex.log (1 - x * y⁻¹) + Complex.log (1 - x * (conj y)⁻¹)

/-- The `x`-derivative of `logTerm`. -/
def logTerm' (x y : ℂ) : ℂ :=
  -(1 * y⁻¹) / (1 - x * y⁻¹) + -(1 * (conj y)⁻¹) / (1 - x * (conj y)⁻¹)

theorem norm_mul_inv_lt_one {x y : ℂ} {r : ℝ} (hx : ‖x‖ < r) (hy : r ≤ ‖y‖) :
    ‖x * y⁻¹‖ < 1 := by
  have hy0 : 0 < ‖y‖ := ((norm_nonneg x).trans_lt hx).trans_le hy
  rw [norm_mul, norm_inv, ← div_eq_mul_inv, div_lt_one hy0]
  exact hx.trans_le hy

theorem one_sub_mem_slitPlane {w : ℂ} (h : ‖w‖ < 1) : 1 - w ∈ Complex.slitPlane := by
  have := Complex.mem_slitPlane_of_norm_lt_one (z := -w) (by rwa [norm_neg])
  rwa [← sub_eq_add_neg] at this

theorem neumannH_eq_logTerm {x y : ℂ} {r : ℝ} (hx : ‖x‖ < r) (hy : r ≤ ‖y‖) :
    neumannH x y = -(2 * Real.log ‖y‖) - (logTerm x y).re := by
  have hy0 : y ≠ 0 := norm_pos_iff.1 (((norm_nonneg x).trans_lt hx).trans_le hy)
  have hyc : conj y ≠ 0 := (map_ne_zero _).2 hy0
  have hyr : r ≤ ‖conj y‖ := by rwa [Complex.norm_conj]
  have n1 := Complex.slitPlane_ne_zero (one_sub_mem_slitPlane (norm_mul_inv_lt_one hx hy))
  have n2 := Complex.slitPlane_ne_zero (one_sub_mem_slitPlane (norm_mul_inv_lt_one hx hyr))
  have e1 : x - y = -y * (1 - x * y⁻¹) := by
    have := mul_inv_cancel₀ hy0
    linear_combination (-x) * this
  have e2 : x - conj y = -conj y * (1 - x * (conj y)⁻¹) := by
    have := mul_inv_cancel₀ hyc
    linear_combination (-x) * this
  unfold neumannH logTerm
  rw [Complex.add_re, Complex.log_re, Complex.log_re, e1, e2, norm_mul, norm_mul, norm_neg,
    norm_neg, Complex.norm_conj, Real.log_mul (norm_ne_zero_iff.2 hy0) (norm_ne_zero_iff.2 n1),
    Real.log_mul (norm_ne_zero_iff.2 hy0) (norm_ne_zero_iff.2 n2)]
  ring

theorem hasDerivAt_logTerm {x y : ℂ} {r : ℝ} (hx : ‖x‖ < r) (hy : r ≤ ‖y‖) :
    HasDerivAt (fun x => logTerm x y) (logTerm' x y) x := by
  have h1 := (((hasDerivAt_id' x).mul_const y⁻¹).const_sub 1).clog
    (one_sub_mem_slitPlane (norm_mul_inv_lt_one hx hy))
  have h2 := (((hasDerivAt_id' x).mul_const (conj y)⁻¹).const_sub 1).clog
    (one_sub_mem_slitPlane (norm_mul_inv_lt_one hx (by rwa [Complex.norm_conj])))
  exact h1.add h2

theorem norm_logTerm'_part_le {x y : ℂ} {δ : ℝ} (hδ : 0 < δ) (hy0 : y ≠ 0)
    (hxy : δ ≤ ‖y - x‖) : ‖-(1 * y⁻¹) / (1 - x * y⁻¹)‖ ≤ 1 / δ := by
  have e : 1 - x * y⁻¹ = (y - x) * y⁻¹ := by rw [sub_mul, mul_inv_cancel₀ hy0]
  rw [norm_div, norm_neg, one_mul, e, norm_mul, mul_comm, ← div_div,
    div_self (norm_ne_zero_iff.2 (inv_ne_zero hy0))]
  exact one_div_le_one_div_of_le hδ hxy

theorem measurable_logTerm (x : ℂ) : Measurable (logTerm x) :=
  ((measurable_const.sub (measurable_const.mul measurable_inv)).clog).add
    ((measurable_const.sub (measurable_const.mul
      (Complex.continuous_conj.measurable.inv))).clog)

theorem measurable_logTerm' (x : ℂ) : Measurable (logTerm' x) :=
  ((measurable_const.mul measurable_inv).neg.div
      (measurable_const.sub (measurable_const.mul measurable_inv))).add
    ((measurable_const.mul Complex.continuous_conj.measurable.inv).neg.div
      (measurable_const.sub (measurable_const.mul Complex.continuous_conj.measurable.inv)))

section Potential

variable {ν : Measure ℂ} [IsFiniteMeasure ν] {K : Set ℂ} {r : ℝ}

theorem integrable_of_continuousOn_K {E : Type*} [NormedAddCommGroup E] {g : ℂ → E}
    (hK : IsCompact K) (hνK : ν Kᶜ = 0) (hg : ContinuousOn g K) : Integrable g ν := by
  have hae : ∀ᵐ y ∂ν, y ∈ K := ae_iff.2 hνK
  have : IntegrableOn g K ν := hg.integrableOn_compact hK
  rwa [IntegrableOn, Measure.restrict_eq_self_of_ae_mem hae] at this

theorem continuousOn_logTerm (hKr : ∀ y ∈ K, r ≤ ‖y‖) {x : ℂ} (hx : ‖x‖ < r) :
    ContinuousOn (logTerm x) K := by
  intro y hy
  have hy0 : y ≠ 0 := norm_pos_iff.1 (((norm_nonneg x).trans_lt hx).trans_le (hKr y hy))
  have hyc : conj y ≠ 0 := (map_ne_zero _).2 hy0
  refine ContinuousAt.continuousWithinAt ?_
  exact ((continuousAt_const.sub (continuousAt_const.mul (continuousAt_inv₀ hy0))).clog
    (one_sub_mem_slitPlane (norm_mul_inv_lt_one hx (hKr y hy)))).add
    ((continuousAt_const.sub (continuousAt_const.mul
      (Complex.continuous_conj.continuousAt.inv₀ hyc))).clog
    (one_sub_mem_slitPlane (norm_mul_inv_lt_one hx (by rw [Complex.norm_conj]; exact hKr y hy))))

theorem hasDerivAt_integral_logTerm (hK : IsCompact K) (hνK : ν Kᶜ = 0)
    (hKr : ∀ y ∈ K, r ≤ ‖y‖) {x₀ : ℂ} (hx₀ : ‖x₀‖ < r) :
    HasDerivAt (fun x => ∫ y, logTerm x y ∂ν) (∫ y, logTerm' x₀ y ∂ν) x₀ := by
  set δ := (r - ‖x₀‖) / 2 with hδ
  have hδ0 : 0 < δ := by rw [hδ]; linarith
  have hae : ∀ᵐ y ∂ν, y ∈ K := ae_iff.2 hνK
  have hball : ∀ x ∈ ball x₀ δ, ‖x‖ < r - δ := by
    intro x hx
    have h1 := norm_sub_norm_le x x₀
    have h2 := mem_ball_iff_norm.1 hx
    rw [hδ] at h2 ⊢
    linarith
  refine (hasDerivAt_integral_of_dominated_loc_of_deriv_le (F := fun x y => logTerm x y)
    (F' := fun x y => logTerm' x y) (bound := fun _ => 2 / δ)
    (ball_mem_nhds x₀ hδ0) (Eventually.of_forall fun x => (measurable_logTerm x).aestronglyMeasurable)
    (integrable_of_continuousOn_K hK hνK (continuousOn_logTerm hKr hx₀))
    (measurable_logTerm' x₀).aestronglyMeasurable ?_ (integrable_const _) ?_).2
  · filter_upwards [hae] with y hy x hx
    have hxr := hball x hx
    have hyr := hKr y hy
    have hy0 : y ≠ 0 := norm_pos_iff.1 (by linarith [norm_nonneg x])
    have hyc : conj y ≠ 0 := (map_ne_zero _).2 hy0
    have d1 : δ ≤ ‖y - x‖ := by have := norm_sub_norm_le y x; linarith
    have d2 : δ ≤ ‖conj y - x‖ := by
      have := norm_sub_norm_le (conj y) x
      rw [Complex.norm_conj] at this; linarith
    show ‖logTerm' x y‖ ≤ 2 / δ
    unfold logTerm'
    calc _ ≤ 1 / δ + 1 / δ := (norm_add_le _ _).trans
          (add_le_add (norm_logTerm'_part_le hδ0 hy0 d1) (norm_logTerm'_part_le hδ0 hyc d2))
      _ = 2 / δ := by ring
  · filter_upwards [hae] with y hy x hx
    exact hasDerivAt_logTerm (r := r) (by linarith [hball x hx]) (hKr y hy)

/-- The `neumannH` potential of a measure. -/
def potN (ν : Measure ℂ) (x : ℂ) : ℝ := ∫ y, neumannH x y ∂ν

theorem potN_eq (hK : IsCompact K) (hνK : ν Kᶜ = 0) (hKr : ∀ y ∈ K, r ≤ ‖y‖) {x : ℂ}
    (hx : ‖x‖ < r) :
    potN ν x = -(2 * ∫ y, Real.log ‖y‖ ∂ν) - (∫ y, logTerm x y ∂ν).re := by
  have hae : ∀ᵐ y ∂ν, y ∈ K := ae_iff.2 hνK
  have hr : 0 < r := (norm_nonneg x).trans_lt hx
  have hlog : Integrable (fun y => Real.log ‖y‖) ν :=
    integrable_of_continuousOn_K hK hνK fun y hy =>
      (continuous_norm.continuousAt.log (norm_ne_zero_iff.2
        (norm_pos_iff.1 (hr.trans_le (hKr y hy))))).continuousWithinAt
  have hlt : Integrable (logTerm x) ν :=
    integrable_of_continuousOn_K hK hνK (continuousOn_logTerm hKr hx)
  unfold potN
  rw [integral_congr_ae (hae.mono fun y hy => neumannH_eq_logTerm hx (hKr y hy)),
    integral_sub (f := fun y => -(2 * Real.log ‖y‖)) (g := fun y => (logTerm x y).re)
      (hlog.const_mul 2).neg hlt.re, integral_neg, integral_const_mul]
  congr 1
  exact integral_re hlt

theorem contDiffOn_potN (hK : IsCompact K) (hνK : ν Kᶜ = 0) (hKr : ∀ y ∈ K, r ≤ ‖y‖)
    {n : WithTop ℕ∞} : ContDiffOn ℝ n (potN ν) (ball 0 r) := by
  have hd : DifferentiableOn ℂ (fun x => ∫ y, logTerm x y ∂ν) (ball 0 r) := fun x hx =>
    (hasDerivAt_integral_logTerm hK hνK hKr
      (mem_ball_zero_iff.1 hx)).differentiableAt.differentiableWithinAt
  have hc : ContDiffOn ℝ n (fun x => Complex.reCLM (∫ y, logTerm x y ∂ν)) (ball 0 r) :=
    Complex.reCLM.contDiff.comp_contDiffOn ((hd.contDiffOn isOpen_ball).restrict_scalars ℝ)
  refine ((contDiffOn_const (c := -(2 * ∫ y, Real.log ‖y‖ ∂ν))).sub hc).congr fun x hx => ?_
  rw [potN_eq hK hνK hKr (mem_ball_zero_iff.1 hx), Complex.reCLM_apply]

theorem neumannH_conj_left (x y : ℂ) : neumannH (conj x) y = neumannH x y := by
  have h1 : ‖conj x - y‖ = ‖x - conj y‖ := by
    rw [← Complex.norm_conj, map_sub, Complex.conj_conj]
  have h2 : ‖conj x - conj y‖ = ‖x - y‖ := by
    rw [← map_sub, Complex.norm_conj]
  unfold neumannH
  rw [h1, h2]; ring

theorem potN_conj (ν : Measure ℂ) (x : ℂ) : potN ν (conj x) = potN ν x := by
  unfold potN; simp_rw [neumannH_conj_left]

end Potential

/-! ## 2. A smooth radial cutoff -/

/-- A smooth radial cutoff: `1` on `closedBall 0 (1/2)`, `0` off `ball 0 1`. -/
def cutb (v : ℂ) : ℝ := Real.smoothTransition (2 - 2 * ‖v‖ ^ 2)

theorem contDiff_cutb {n : ℕ∞} : ContDiff ℝ n cutb :=
  Real.smoothTransition.contDiff.comp
    (contDiff_const.sub (contDiff_const.mul (contDiff_norm_sq ℝ)))

theorem cutb_eq_one {v : ℂ} (hv : ‖v‖ ≤ 1 / 2) : cutb v = 1 :=
  Real.smoothTransition.one_of_one_le (by nlinarith [norm_nonneg v])

theorem cutb_eq_zero {v : ℂ} (hv : 1 ≤ ‖v‖) : cutb v = 0 :=
  Real.smoothTransition.zero_of_nonpos (by nlinarith [norm_nonneg v])

theorem cutb_nonneg (v : ℂ) : 0 ≤ cutb v := Real.smoothTransition.nonneg _

theorem cutb_le_one (v : ℂ) : cutb v ≤ 1 := Real.smoothTransition.le_one _

theorem hasCompactSupport_cutb : HasCompactSupport cutb :=
  HasCompactSupport.intro (isCompact_closedBall 0 1) fun v hv =>
    cutb_eq_zero (by rw [mem_closedBall_zero_iff, not_le] at hv; exact hv.le)

theorem exists_bound_fderiv_cutb : ∃ B, ∀ v, ‖fderiv ℝ cutb v‖ ≤ B :=
  (hasCompactSupport_cutb.fderiv (𝕜 := ℝ)).exists_bound_of_continuous
    ((contDiff_cutb (n := 1)).continuous_fderiv (by simp))

theorem hasFDerivAt_cutb_scale (ρ : ℝ) (x : ℂ) :
    HasFDerivAt (fun x : ℂ => cutb (ρ⁻¹ • x))
      ((fderiv ℝ cutb (ρ⁻¹ • x)).comp (ρ⁻¹ • ContinuousLinearMap.id ℝ ℂ)) x :=
  ((contDiff_cutb (n := 1)).differentiable (by simp) _).hasFDerivAt.comp x
    ((ContinuousLinearMap.id ℝ ℂ).hasFDerivAt.const_smul ρ⁻¹)

/-! ## 3. The cut-off potential `φ = χ_ρ (u - u 0)` -/

section Phi

variable {u : ℂ → ℝ} {r ρ : ℝ}

/-- `φ x = χ(x/ρ) (u x - u 0)`. -/
def phiCut (u : ℂ → ℝ) (ρ : ℝ) (x : ℂ) : ℝ := cutb (ρ⁻¹ • x) * (u x - u 0)

theorem norm_inv_smul {ρ : ℝ} (hρ : 0 < ρ) (x : ℂ) : ‖ρ⁻¹ • x‖ = ‖x‖ / ρ := by
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (inv_pos.2 hρ), inv_mul_eq_div]

theorem phiCut_eq_zero (hρ : 0 < ρ) {x : ℂ} (hx : ρ ≤ ‖x‖) : phiCut u ρ x = 0 := by
  unfold phiCut
  rw [cutb_eq_zero, zero_mul]
  rw [norm_inv_smul hρ, le_div_iff₀ hρ]; linarith

theorem tsupport_phiCut (hρ : 0 < ρ) : tsupport (phiCut u ρ) ⊆ closedBall 0 ρ := by
  refine closure_minimal (fun x hx => ?_) isClosed_closedBall
  rw [mem_closedBall_zero_iff]
  by_contra h
  exact hx (phiCut_eq_zero hρ (not_le.1 h).le)

theorem phiCut_eq_of_le (hρ : 0 < ρ) {x : ℂ} (hx : ‖x‖ ≤ ρ / 2) :
    phiCut u ρ x = u x - u 0 := by
  unfold phiCut
  rw [cutb_eq_one, one_mul]
  rw [norm_inv_smul hρ, div_le_iff₀ hρ]; linarith

theorem phiCut_conj (hu : ∀ x, u (conj x) = u x) (x : ℂ) :
    phiCut u ρ (conj x) = phiCut u ρ x := by
  unfold phiCut
  have : cutb (ρ⁻¹ • conj x) = cutb (ρ⁻¹ • x) := by
    unfold cutb; rw [norm_smul, norm_smul, Complex.norm_conj]
  rw [this, hu]

theorem contDiff_cutb2 : ContDiff ℝ 2 cutb := contDiff_cutb

theorem contDiff_phiCut (hρ : 0 < ρ) (hρr : ρ < r) (hu : ContDiffOn ℝ 2 u (ball 0 r)) :
    ContDiff ℝ 2 (phiCut u ρ) := by
  rw [contDiff_iff_contDiffAt]
  intro x
  by_cases hx : ‖x‖ < r
  · have hux : ContDiffAt ℝ 2 u x :=
      hu.contDiffAt (isOpen_ball.mem_nhds (mem_ball_zero_iff.2 hx))
    exact (contDiff_cutb2.comp (contDiff_const_smul _)).contDiffAt.mul
      (hux.sub contDiffAt_const)
  · have hopen : IsOpen {y : ℂ | ρ < ‖y‖} := isOpen_lt continuous_const continuous_norm
    have : phiCut u ρ =ᶠ[𝓝 x] fun _ => 0 := by
      filter_upwards [hopen.mem_nhds (show ρ < ‖x‖ by linarith [not_lt.1 hx])] with y hy
      exact phiCut_eq_zero hρ (le_of_lt hy)
    exact contDiffAt_const.congr_of_eventuallyEq this

theorem hasCompactSupport_phiCut (hρ : 0 < ρ) : HasCompactSupport (phiCut u ρ) :=
  (isCompact_closedBall 0 ρ).of_isClosed_subset (isClosed_tsupport _) (tsupport_phiCut hρ)

theorem norm_comp_scale_le {B ρ : ℝ} (hB : ∀ v, ‖fderiv ℝ cutb v‖ ≤ B) (hρ : 0 < ρ) (x : ℂ) :
    ‖(fderiv ℝ cutb (ρ⁻¹ • x)).comp (ρ⁻¹ • ContinuousLinearMap.id ℝ ℂ)‖ ≤ B * ρ⁻¹ := by
  refine (ContinuousLinearMap.opNorm_comp_le _ _).trans ?_
  have hB0 : 0 ≤ B := (norm_nonneg _).trans (hB 0)
  refine mul_le_mul (hB _) ?_ (norm_nonneg _) hB0
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (inv_pos.2 hρ)]
  exact mul_le_of_le_one_right (inv_pos.2 hρ).le ContinuousLinearMap.norm_id_le

theorem volume_real_closedBall (x : ℂ) {ρ : ℝ} (hρ : 0 ≤ ρ) :
    volume.real (closedBall x ρ) = π * ρ ^ 2 := by
  rw [measureReal_def, Complex.volume_closedBall, ENNReal.toReal_mul, ENNReal.toReal_pow,
    ENNReal.toReal_ofReal hρ, ENNReal.coe_toReal, NNReal.coe_real_pi]
  ring

/-- **Energy of the cut-off potential**: `E_H(φ_ρ) ≤ K ρ²`. -/
theorem energy_phiCut_le (hr : 0 < r) (hu : ContDiffOn ℝ 2 u (ball 0 r)) :
    ∃ Kc : ℝ, ∀ ρ, 0 < ρ → ρ ≤ r / 2 → dirichletEnergyOn H (phiCut u ρ) ≤ Kc * ρ ^ 2 := by
  obtain ⟨B, hB⟩ := exists_bound_fderiv_cutb
  have hB0 : 0 ≤ B := (norm_nonneg _).trans (hB 0)
  have hsub : closedBall (0 : ℂ) (r / 2) ⊆ ball 0 r := closedBall_subset_ball (by linarith)
  have hdiff : ∀ x ∈ closedBall (0 : ℂ) (r / 2), DifferentiableAt ℝ u x := fun x hx =>
    (hu.contDiffAt (isOpen_ball.mem_nhds (hsub hx))).differentiableAt (by simp)
  obtain ⟨M, hM⟩ := (isCompact_closedBall (0 : ℂ) (r / 2)).exists_bound_of_continuousOn
    ((hu.continuousOn_fderiv_of_isOpen isOpen_ball one_le_two).mono hsub)
  have h0 : (0 : ℂ) ∈ closedBall (0 : ℂ) (r / 2) := mem_closedBall_self (by linarith)
  have hM0 : 0 ≤ M := (norm_nonneg _).trans (hM 0 h0)
  refine ⟨(M * (1 + B)) ^ 2 / 2, fun ρ hρ hρr => ?_⟩
  set c := (M * (1 + B)) ^ 2 with hc
  have hc0 : 0 ≤ c := sq_nonneg _
  have hφ := contDiff_phiCut (u := u) hρ (by linarith) hu
  have hpt : ∀ x, ‖fderiv ℝ (phiCut u ρ) x‖ ^ 2 ≤
      (closedBall (0 : ℂ) ρ).indicator (fun _ => c) x := by
    intro x
    by_cases hx : x ∈ closedBall (0 : ℂ) ρ
    · rw [indicator_of_mem hx]
      have hx2 : x ∈ closedBall (0 : ℂ) (r / 2) := closedBall_subset_closedBall hρr hx
      have hux := hdiff x hx2
      have hd := (hasFDerivAt_cutb_scale ρ x).mul (hux.hasFDerivAt.sub_const (u 0))
      have heq : phiCut u ρ = fun y => cutb (ρ⁻¹ • y) * (u y - u 0) := rfl
      rw [heq, (show HasFDerivAt (fun y => cutb (ρ⁻¹ • y) * (u y - u 0)) _ x from hd).fderiv]
      have h1 : ‖u x - u 0‖ ≤ M * ρ := by
        have := (convex_closedBall (0 : ℂ) (r / 2)).norm_image_sub_le_of_norm_fderiv_le
          hdiff hM h0 hx2
        rw [sub_zero] at this
        exact this.trans (mul_le_mul_of_nonneg_left (mem_closedBall_zero_iff.1 hx) hM0)
      have h2 := norm_comp_scale_le hB hρ x
      have h3 : ‖cutb (ρ⁻¹ • x)‖ ≤ 1 := by
        rw [Real.norm_eq_abs, abs_of_nonneg (cutb_nonneg _)]; exact cutb_le_one _
      have hbound : ‖cutb (ρ⁻¹ • x) • fderiv ℝ u x + (u x - u 0) •
          (fderiv ℝ cutb (ρ⁻¹ • x)).comp (ρ⁻¹ • ContinuousLinearMap.id ℝ ℂ)‖ ≤ M * (1 + B) := by
        refine (norm_add_le _ _).trans ?_
        rw [norm_smul, norm_smul]
        have e1 : ‖cutb (ρ⁻¹ • x)‖ * ‖fderiv ℝ u x‖ ≤ 1 * M :=
          mul_le_mul h3 (hM x hx2) (norm_nonneg _) zero_le_one
        have e2 : ‖u x - u 0‖ * ‖(fderiv ℝ cutb (ρ⁻¹ • x)).comp
            (ρ⁻¹ • ContinuousLinearMap.id ℝ ℂ)‖ ≤ (M * ρ) * (B * ρ⁻¹) :=
          mul_le_mul h1 h2 (norm_nonneg _) (by positivity)
        have e3 : (M * ρ) * (B * ρ⁻¹) = M * B := by
          rw [mul_mul_mul_comm, mul_inv_cancel₀ hρ.ne', mul_one]
        rw [e3] at e2
        nlinarith
      exact pow_le_pow_left₀ (norm_nonneg _) hbound 2
    · rw [indicator_of_notMem hx]
      have hxt : x ∉ tsupport (phiCut u ρ) := fun h => hx (tsupport_phiCut hρ h)
      have h0 : fderiv ℝ (phiCut u ρ) x = 0 := by
        by_contra h
        exact hxt (support_fderiv_subset (𝕜 := ℝ) h)
      rw [h0, norm_zero]; norm_num
  have hcs : HasCompactSupport fun x => ‖fderiv ℝ (phiCut u ρ) x‖ ^ 2 :=
    ((hasCompactSupport_phiCut hρ).fderiv (𝕜 := ℝ)).comp_left
      (g := fun A : ℂ →L[ℝ] ℝ => ‖A‖ ^ 2) (by simp)
  have hint : Integrable fun x => ‖fderiv ℝ (phiCut u ρ) x‖ ^ 2 :=
    ((hφ.continuous_fderiv (by simp)).norm.pow 2).integrable_of_hasCompactSupport hcs
  have hI : ∫ x in H, ‖fderiv ℝ (phiCut u ρ) x‖ ^ 2 ≤ c * (π * ρ ^ 2) := by
    calc ∫ x in H, ‖fderiv ℝ (phiCut u ρ) x‖ ^ 2
        ≤ ∫ x, ‖fderiv ℝ (phiCut u ρ) x‖ ^ 2 :=
          setIntegral_le_integral hint (ae_of_all _ fun x => sq_nonneg _)
      _ ≤ ∫ x, (closedBall (0 : ℂ) ρ).indicator (fun _ => c) x :=
          integral_mono hint ((integrable_indicator_iff measurableSet_closedBall).2
            (continuousOn_const.integrableOn_compact (isCompact_closedBall _ _))) hpt
      _ = c * (π * ρ ^ 2) := by
          rw [integral_indicator_const _ measurableSet_closedBall, smul_eq_mul,
            volume_real_closedBall 0 hρ.le]; ring
  unfold dirichletEnergyOn
  have hπ : 0 < π := Real.pi_pos
  calc (2 * π)⁻¹ * ∫ x in H, ‖fderiv ℝ (phiCut u ρ) x‖ ^ 2
      ≤ (2 * π)⁻¹ * (c * (π * ρ ^ 2)) :=
        mul_le_mul_of_nonneg_left hI (by positivity)
    _ = c / 2 * ρ ^ 2 * (π * π⁻¹) := by ring
    _ = c / 2 * ρ ^ 2 := by rw [mul_inv_cancel₀ hπ.ne', mul_one]

end Phi

/-! ## 4. The Laplacian measures `m± = (2π)⁻¹ (∓Δφ)^± dy` on `H` -/

/-- `(volume on H) with density ofReal (s (2π)⁻¹ (-Δφ))`: `s = 1` gives `m⁺`, `s = -1` gives `m⁻`. -/
def mPM (s : ℝ) (φ : ℂ → ℝ) : Measure ℂ :=
  (volume.restrict H).withDensity fun y => ENNReal.ofReal (s * (2 * π)⁻¹ * (-Δ φ y))

section Meas

variable {φ : ℂ → ℝ} {ρ : ℝ}

theorem mPM_eq (s : ℝ) (φ : ℂ → ℝ) : mPM s φ =
    volume.withDensity (H.indicator fun y => ENNReal.ofReal (s * (2 * π)⁻¹ * (-Δ φ y))) :=
  (withDensity_indicator measurableSet_H_k3 _).symm

theorem laplacian_eq_zero_of_not_mem_closedBall (hsupp : tsupport φ ⊆ closedBall 0 ρ) {y : ℂ}
    (hy : y ∉ closedBall (0 : ℂ) ρ) : Δ φ y = 0 :=
  laplacian_eq_zero_of_notMem_tsupport fun h => hy (hsupp h)

theorem isAdmissibleH_mPM (hφ : ContDiff ℝ 2 φ) (hsupp : tsupport φ ⊆ closedBall 0 ρ) (s : ℝ) :
    IsAdmissibleH (mPM s φ) := by
  have hc : HasCompactSupport φ :=
    (isCompact_closedBall 0 ρ).of_isClosed_subset (isClosed_tsupport φ) hsupp
  have hΔc := continuous_laplacian_K3 hφ
  obtain ⟨C, hC⟩ := (hasCompactSupport_laplacian_K3 hc).exists_bound_of_continuous hΔc
  rw [mPM_eq]
  refine isAdmissibleH_withDensity (M := ENNReal.ofReal (|s| * (2 * π)⁻¹ * C)) ?_
    ENNReal.ofReal_lt_top ?_ ((isCompact_closedBall (0 : ℂ) ρ).inter_right isClosed_Hbar)
    inter_subset_right ?_
  · exact (measurable_const.mul hΔc.measurable.neg).ennreal_ofReal.indicator measurableSet_H_k3
  · intro y
    by_cases hy : y ∈ H
    · rw [indicator_of_mem hy]
      apply ENNReal.ofReal_le_ofReal
      have hπ : 0 < (2 * π)⁻¹ := by positivity
      calc s * (2 * π)⁻¹ * (-Δ φ y) ≤ |s * (2 * π)⁻¹ * (-Δ φ y)| := le_abs_self _
        _ = |s| * (2 * π)⁻¹ * ‖Δ φ y‖ := by
            rw [abs_mul, abs_mul, abs_neg, abs_of_pos hπ, Real.norm_eq_abs]
        _ ≤ |s| * (2 * π)⁻¹ * C := by gcongr; exact hC y
    · rw [indicator_of_notMem hy]; exact zero_le
  · intro y hy
    by_cases hyH : y ∈ H
    · rw [indicator_of_mem hyH]
      have hyb : y ∉ closedBall (0 : ℂ) ρ := fun h =>
        hy ⟨h, show (0 : ℝ) ≤ y.im from le_of_lt hyH⟩
      rw [laplacian_eq_zero_of_not_mem_closedBall hsupp hyb]; simp
    · rw [indicator_of_notMem hyH]

theorem mPM_compl (hsupp : tsupport φ ⊆ closedBall 0 ρ) (s : ℝ) :
    mPM s φ (closedBall (0 : ℂ) ρ)ᶜ = 0 := by
  have hs : MeasurableSet (closedBall (0 : ℂ) ρ)ᶜ := measurableSet_closedBall.compl
  have h0 : ∀ y ∈ (closedBall (0 : ℂ) ρ)ᶜ, ENNReal.ofReal (s * (2 * π)⁻¹ * (-Δ φ y)) = 0 :=
    fun y hy => by rw [laplacian_eq_zero_of_not_mem_closedBall hsupp hy]; simp
  rw [mPM, withDensity_apply _ hs, lintegral_congr_ae ((ae_restrict_iff' hs).2 (ae_of_all _ h0)),
    lintegral_zero]

end Meas

/-! ## 5. Green representation against `m⁺ - m⁻` -/

section Green

variable {r : ℝ}

/-- `x ↦ ∫ G(x,y) dm(y)` is `ℓ`-integrable for local admissible `ℓ` and admissible `m`
(the argument of `K3.kernelCov_halfDiscGreen`). -/
theorem integrable_integral_halfDiscGreen {r' : ℝ} (hr : 0 < r) (hr'r : r' < r)
    {ℓ m : Measure ℂ} (hℓ : IsAdmissibleH ℓ) (hℓr : ℓ (closedBall ((0 : ℝ) : ℂ) r')ᶜ = 0)
    (hm : IsAdmissibleH m) :
    Integrable (fun x => ∫ y, halfDiscGreen 0 r x y ∂m) ℓ := by
  have := hℓ.1
  have := hm.1
  obtain ⟨R₁, hR₁⟩ := exists_ballH_of_admissible hℓ
  obtain ⟨R₂, hR₂⟩ := exists_ballH_of_admissible hm
  set R := max (max R₁ R₂) (|(0 : ℝ)| + r) with hRdef
  have hR : |(0 : ℝ)| + r ≤ R := le_max_right _ _
  have hℓS : ℓ (ballH R)ᶜ = 0 :=
    compl_ballH_null_mono ((le_max_left _ _).trans (le_max_left _ _)) hR₁
  have hmS : m (ballH R)ᶜ = 0 :=
    compl_ballH_null_mono ((le_max_right _ _).trans (le_max_left _ _)) hR₂
  obtain ⟨C, hC, hmP⟩ := hm.2.2
  have := isFiniteMeasure_bal hr hr'r hℓr
  have hintμ := CircleFubini.integrable_neumannH hℓS hmS hC.ne hmP
  have hintb := CircleFubini.integrable_neumannH (bal_ballH_compl (μ := ℓ) hr hR) hmS hC.ne hmP
  obtain ⟨ib, -⟩ := integral_bal (t := 0) (r := r) (μ := ℓ)
    (F := fun x => ∫ y, neumannH x y ∂m) hintb.integral_prod_left
  refine (hintμ.integral_prod_left.sub ib).congr ?_
  filter_upwards [mem_ae_iff.2 hℓr, hintμ.prod_right_ae] with x hx hxi
  have hxb := mem_ball_of_le_k3 hr'r (mem_closedBall_iff_norm.1 hx)
  have := isProbabilityMeasure_halfDiscPoisson hr hxb
  have hint' := CircleFubini.integrable_neumannH (halfDiscPoisson_ballH_compl hr x hR) hmS
    hC.ne hmP
  show (∫ y, neumannH x y ∂m) - ∫ u, (∫ y, neumannH u y ∂m) ∂halfDiscPoisson 0 r x =
    ∫ y, halfDiscGreen 0 r x y ∂m
  unfold halfDiscGreen
  rw [integral_sub hxi hint'.integral_prod_right,
    integral_integral_swap (f := fun u y => neumannH u y) hint']

variable {ρ : ℝ} {φ : ℂ → ℝ}

theorem integral_green_mPM_sub (hr : 0 < r) (hρr : ρ < r) (hφ : ContDiff ℝ 2 φ)
    (hsupp : tsupport φ ⊆ closedBall 0 ρ) (heven : ∀ x, φ (conj x) = φ x) {x : ℂ}
    (hx : x ∈ ball ((0 : ℝ) : ℂ) r) :
    ∫ y, halfDiscGreen 0 r x y ∂(mPM 1 φ) - ∫ y, halfDiscGreen 0 r x y ∂(mPM (-1) φ) =
      φ x := by
  have hsupp' : tsupport φ ⊆ ball ((0 : ℝ) : ℂ) r := by
    rw [Complex.ofReal_zero]; exact hsupp.trans (closedBall_subset_ball hρr)
  have hc := hasCompactSupport_of_tsupport_ball hsupp'
  have hD := continuous_laplacian_K3 hφ
  have hDs := hasCompactSupport_laplacian_K3 hc
  have hmeas : ∀ s : ℝ, Measurable fun y => ENNReal.ofReal (s * (2 * π)⁻¹ * (-Δ φ y)) :=
    fun s => (measurable_const.mul hD.measurable.neg).ennreal_ofReal
  have e : ∀ s : ℝ, ∫ y, halfDiscGreen 0 r x y ∂(mPM s φ) =
      ∫ y in H, halfDiscGreen 0 r x y * max (s * (2 * π)⁻¹ * (-Δ φ y)) 0 := by
    intro s
    rw [mPM, integral_withDensity_eq_integral_toReal_smul (hmeas s)
      (ae_of_all _ fun _ => ENNReal.ofReal_lt_top)]
    refine integral_congr_ae (ae_of_all _ fun y => ?_)
    simp only [ENNReal.toReal_ofReal', smul_eq_mul, mul_comm]
  have hint : ∀ s : ℝ, IntegrableOn
      (fun y => halfDiscGreen 0 r x y * max (s * (2 * π)⁻¹ * (-Δ φ y)) 0) H := by
    intro s
    have hψc : Continuous fun y => max (s * (2 * π)⁻¹ * (-Δ φ y)) 0 :=
      (continuous_const.mul hD.neg).max continuous_const
    have hψs : HasCompactSupport fun y => max (s * (2 * π)⁻¹ * (-Δ φ y)) 0 :=
      hDs.comp_left (g := fun t => max (s * (2 * π)⁻¹ * -t) 0) (by simp)
    exact (integrable_halfDiscGreen_mul hr hx hψc hψs).1.integrableOn
  rw [e, e, ← integral_sub (hint 1) (hint (-1))]
  have hpt : ∀ y, halfDiscGreen 0 r x y * max (1 * (2 * π)⁻¹ * (-Δ φ y)) 0 -
      halfDiscGreen 0 r x y * max (-1 * (2 * π)⁻¹ * (-Δ φ y)) 0 =
      (2 * π)⁻¹ * (halfDiscGreen 0 r x y * (-Δ φ y)) := by
    intro y
    rw [← mul_sub, neg_one_mul, one_mul, neg_mul, max_zero_sub_max_neg_zero_eq_self]; ring
  simp_rw [hpt]
  rw [integral_const_mul]
  exact halfDiscGreen_represent hr hφ hsupp' heven hx

/-- **Green representation**: `K_G(ℓ, m⁺) - K_G(ℓ, m⁻) = ∫ φ dℓ` for local `ℓ`. -/
theorem kernelCov_green_mPM_sub {r' : ℝ} (hr : 0 < r) (hr'r : r' < r) (hρ : 0 < ρ)
    (hρr : ρ < r) (hφ : ContDiff ℝ 2 φ) (hsupp : tsupport φ ⊆ closedBall 0 ρ)
    (heven : ∀ x, φ (conj x) = φ x) {ℓ : Measure ℂ} (hℓ : IsAdmissibleH ℓ)
    (hℓr : ℓ (closedBall ((0 : ℝ) : ℂ) r')ᶜ = 0) :
    kernelCov (halfDiscGreen 0 r) ℓ (mPM 1 φ) - kernelCov (halfDiscGreen 0 r) ℓ (mPM (-1) φ) =
      ∫ x, φ x ∂ℓ := by
  have i1 := integrable_integral_halfDiscGreen hr hr'r hℓ hℓr (isAdmissibleH_mPM hφ hsupp 1)
  have i2 := integrable_integral_halfDiscGreen hr hr'r hℓ hℓr (isAdmissibleH_mPM hφ hsupp (-1))
  unfold kernelCov
  rw [← integral_sub i1 i2]
  refine integral_congr_ae ?_
  filter_upwards [mem_ae_iff.2 hℓr] with x hx
  exact integral_green_mPM_sub hr hρr hφ hsupp heven
    (mem_ball_of_le_k3 hr'r (mem_closedBall_iff_norm.1 hx))

/-- **Energy identity**: the Green quadratic form of `m⁺ - m⁻` is `E_H(φ)`. -/
theorem kernelCov_green_mPM_energy (hr : 0 < r) (hρ : 0 < ρ) (hρr : ρ < r)
    (hφ : ContDiff ℝ 2 φ) (hsupp : tsupport φ ⊆ closedBall 0 ρ)
    (heven : ∀ x, φ (conj x) = φ x) :
    (kernelCov (halfDiscGreen 0 r) (mPM 1 φ) (mPM 1 φ) -
        kernelCov (halfDiscGreen 0 r) (mPM 1 φ) (mPM (-1) φ)) -
      (kernelCov (halfDiscGreen 0 r) (mPM (-1) φ) (mPM 1 φ) -
        kernelCov (halfDiscGreen 0 r) (mPM (-1) φ) (mPM (-1) φ)) =
      dirichletEnergyOn H φ := by
  have hc0 : ∀ s : ℝ, mPM s φ (closedBall ((0 : ℝ) : ℂ) ρ)ᶜ = 0 := fun s => by
    rw [Complex.ofReal_zero]; exact mPM_compl hsupp s
  rw [kernelCov_green_mPM_sub hr hρr hρ hρr hφ hsupp heven (isAdmissibleH_mPM hφ hsupp 1) (hc0 1),
    kernelCov_green_mPM_sub hr hρr hρ hρr hφ hsupp heven (isAdmissibleH_mPM hφ hsupp (-1))
      (hc0 (-1))]
  have hc : HasCompactSupport φ :=
    (isCompact_closedBall 0 ρ).of_isClosed_subset (isClosed_tsupport φ) hsupp
  have hD := continuous_laplacian_K3 hφ
  have hmeas : ∀ s : ℝ, Measurable fun y => ENNReal.ofReal (s * (2 * π)⁻¹ * (-Δ φ y)) :=
    fun s => (measurable_const.mul hD.measurable.neg).ennreal_ofReal
  have e : ∀ s : ℝ, ∫ x, φ x ∂(mPM s φ) =
      ∫ y in H, max (s * (2 * π)⁻¹ * (-Δ φ y)) 0 * φ y := by
    intro s
    rw [mPM, integral_withDensity_eq_integral_toReal_smul (hmeas s)
      (ae_of_all _ fun _ => ENNReal.ofReal_lt_top)]
    refine integral_congr_ae (ae_of_all _ fun y => ?_)
    simp only [ENNReal.toReal_ofReal', smul_eq_mul]
  have hint : ∀ s : ℝ, IntegrableOn (fun y => max (s * (2 * π)⁻¹ * (-Δ φ y)) 0 * φ y) H := by
    intro s
    have hcont : Continuous fun y => max (s * (2 * π)⁻¹ * (-Δ φ y)) 0 * φ y :=
      ((continuous_const.mul hD.neg).max continuous_const).mul hφ.continuous
    exact (hcont.integrable_of_hasCompactSupport hc.mul_left).integrableOn
  rw [e, e, ← integral_sub (hint 1) (hint (-1))]
  have hpt : ∀ y, max (1 * (2 * π)⁻¹ * (-Δ φ y)) 0 * φ y -
      max (-1 * (2 * π)⁻¹ * (-Δ φ y)) 0 * φ y = (2 * π)⁻¹ * (φ y * (-Δ φ y)) := by
    intro y
    rw [← sub_mul, neg_one_mul, one_mul, neg_mul, max_zero_sub_max_neg_zero_eq_self]; ring
  simp_rw [hpt]
  rw [integral_const_mul, setIntegral_H_mul_neg_laplacian hφ hc heven]
  rfl

end Green

/-! ## 6. Measure-theoretic helpers -/

section Helpers

theorem isAdmissibleH_restrict {μ : Measure ℂ} (hμ : IsAdmissibleH μ) (s : Set ℂ) :
    IsAdmissibleH (μ.restrict s) := by
  obtain ⟨hfin, ⟨K, hK, hKH, hμK⟩, C, hC, hbd⟩ := hμ
  exact ⟨inferInstance, ⟨K, hK, hKH,
    nonpos_iff_eq_zero.1 ((Measure.restrict_apply_le s Kᶜ).trans hμK.le)⟩,
    C, hC, fun y => (lintegral_mono' Measure.restrict_le_self le_rfl).trans (hbd y)⟩

theorem radSmear_add (a b : Measure ℂ) : WedgeTK.radSmear (a + b) =
    WedgeTK.radSmear a + WedgeTK.radSmear b := by
  ext A hA
  rw [WedgeTK.radSmear_apply _ hA, Measure.add_apply, WedgeTK.radSmear_apply _ hA,
    WedgeTK.radSmear_apply _ hA, lintegral_add_measure]

theorem radSmear_mono {a b : Measure ℂ} (h : a ≤ b) :
    WedgeTK.radSmear a ≤ WedgeTK.radSmear b :=
  Measure.le_iff.2 fun A hA => by
    rw [WedgeTK.radSmear_apply _ hA, WedgeTK.radSmear_apply _ hA]
    exact lintegral_mono' h le_rfl

/-- The folded semicircle of radius `s ≥ δ` about `0` misses the open disc of radius `δ`. -/
theorem foldedCircle_ball_eq_zero {s δ : ℝ} (hδ : 0 < δ) (hs : δ ≤ s) :
    foldedCircle 0 s (ball 0 δ) = 0 := by
  have hae := WedgeTK.fc_ae_norm (hδ.trans_le hs)
  refine measure_mono_null (fun x hx => ?_) (ae_iff.1 hae)
  rw [mem_ball_zero_iff] at hx
  show ¬ ‖x‖ = s
  intro hx'
  linarith

theorem radSmear_ball_eq_zero {μ : Measure ℂ} {δ : ℝ} (hδ : 0 < δ)
    (hμ : ∀ᵐ z ∂μ, δ ≤ ‖z‖) : WedgeTK.radSmear μ (ball 0 δ) = 0 := by
  rw [WedgeTK.radSmear_apply _ measurableSet_ball,
    lintegral_congr_ae (hμ.mono fun z hz => foldedCircle_ball_eq_zero hδ hz), lintegral_zero]

theorem closedBall_compl_null {μ : Measure ℂ} {ε : ℝ}
    (h : μ (closedBall 0 ε ∩ Hbar)ᶜ = 0) : μ (closedBall 0 ε)ᶜ = 0 :=
  measure_mono_null (compl_subset_compl.2 inter_subset_left) h

theorem ballH_subset_ball {ε r : ℝ} (h : ε < r) : ballH ε ⊆ ball (0 : ℂ) r := fun x hx =>
  mem_ball_zero_iff.2 (lt_of_le_of_lt (mem_closedBall_zero_iff.1 hx.1) h)

end Helpers

/-! ## 7. The lateral germ and its Gaussian version -/

section Field

variable {Ω : Type*} [mΩ : MeasurableSpace Ω] {P : Measure Ω} {X : Ω → FieldSample}

open WedgeTK

/-- **The lateral germ at scale `r`**: the σ-algebra generated by the lateral parts
`lateralPart (X ·) μ` at the admissible measures `μ` carried by `closedBall 0 r ∩ Hbar` at which
the canonical regularization is almost surely exact (`evalReg (X ω) μ = X ω μ` a.s.). This
holds for all folded circles (`WedgeTK.ae_evalReg_fc`) and for bounded densities
(`ae_evalReg_eq_withDensity`); see the module docstring for why the restriction is needed. -/
def lateralGerm (X : Ω → FieldSample) (P : Measure Ω) (r : ℝ) : MeasurableSpace Ω :=
  ⨆ (μ : Measure ℂ) (_ : IsAdmissibleH μ ∧ μ (closedBall 0 r ∩ Hbar)ᶜ = 0 ∧
      ∀ᵐ ω ∂P, evalReg (X ω) μ = X ω μ),
    MeasurableSpace.comap (fun ω => lateralPart (X ω) μ) inferInstance

/-- The germ `⨅ n, lateralGerm X P 2⁻ⁿ`. -/
def germ (X : Ω → FieldSample) (P : Measure Ω) : MeasurableSpace Ω :=
  ⨅ n : ℕ, lateralGerm X P ((2 : ℝ)⁻¹ ^ n)

/-- Generators of the lateral germ at scale `ε`. -/
abbrev GIdx (X : Ω → FieldSample) (P : Measure Ω) (ε : ℝ) : Type :=
  {μ : Measure ℂ // IsAdmissibleH μ ∧ μ (closedBall 0 ε ∩ Hbar)ᶜ = 0 ∧
    ∀ᵐ ω ∂P, evalReg (X ω) μ = X ω μ}

/-- The Gaussian pair `(μ, radSmear μ)` of a germ generator. -/
def latPairG {ε : ℝ} (μ : GIdx X P ε) : BPair :=
  ⟨(μ.1, radSmear μ.1), μ.2.1, isAdmissibleH_radSmear μ.2.1, (radSmear_univ _).symm⟩

/-- The lateral pair difference `X μ - X (radSmear μ)`. -/
def Lf (X : Ω → FieldSample) (μ : Measure ℂ) (ω : Ω) : ℝ := X ω μ - X ω (radSmear μ)

/-- The rescaled cutoff radii `ρ_j = (r/4) 2^{-j}`. -/
def rhoJ (r : ℝ) (j : ℕ) : ℝ := r / 4 * (1 / 2) ^ j

theorem rhoJ_pos {r : ℝ} (hr : 0 < r) (j : ℕ) : 0 < rhoJ r j := by unfold rhoJ; positivity

theorem rhoJ_le {r : ℝ} (hr : 0 < r) (j : ℕ) : rhoJ r j ≤ r / 4 := by
  unfold rhoJ
  have : (1 / 2 : ℝ) ^ j ≤ 1 := pow_le_one₀ (by norm_num) (by norm_num)
  nlinarith

theorem exists_K_of_out {r : ℝ} {ν : Measure ℂ} (hν : IsAdmissibleH ν)
    (hνB : ν (ball ((0 : ℝ) : ℂ) r) = 0) :
    ∃ K, IsCompact K ∧ ν Kᶜ = 0 ∧ ∀ y ∈ K, r ≤ ‖y‖ := by
  obtain ⟨-, ⟨K0, hK0, -, hνK0⟩, -⟩ := hν
  rw [Complex.ofReal_zero] at hνB
  refine ⟨K0 \ ball 0 r, hK0.diff isOpen_ball, ?_, fun y hy => ?_⟩
  · rw [compl_sdiff]; exact measure_union_null hνB hνK0
  · have := hy.2; rw [mem_ball_zero_iff, not_lt] at this; exact this

/-- The potential difference of an outside pair. -/
def uP {r : ℝ} (p : OutIdx 0 r) : ℂ → ℝ := fun x => potN p.1.1 x - potN p.1.2 x

theorem contDiffOn_potN_out {r : ℝ} {ν : Measure ℂ} (hν : IsAdmissibleH ν)
    (hνB : ν (ball ((0 : ℝ) : ℂ) r) = 0) : ContDiffOn ℝ 2 (potN ν) (ball 0 r) := by
  obtain ⟨K, hK, hνK, hKr⟩ := exists_K_of_out hν hνB
  have := hν.1
  exact contDiffOn_potN hK hνK hKr

theorem contDiffOn_uP {r : ℝ} (p : OutIdx 0 r) : ContDiffOn ℝ 2 (uP p) (ball 0 r) :=
  (contDiffOn_potN_out p.2.1 p.2.2.2.2.1).sub (contDiffOn_potN_out p.2.2.1 p.2.2.2.2.2)

theorem uP_conj {r : ℝ} (p : OutIdx 0 r) (x : ℂ) : uP p (conj x) = uP p x := by
  simp only [uP, potN_conj]

/-- The cut-off potential of an outside pair at scale `ρ_j`. -/
def phiP {r : ℝ} (p : OutIdx 0 r) (j : ℕ) : ℂ → ℝ := phiCut (uP p) (rhoJ r j)

theorem phiP_props {r : ℝ} (hr : 0 < r) (p : OutIdx 0 r) (j : ℕ) :
    ContDiff ℝ 2 (phiP p j) ∧ tsupport (phiP p j) ⊆ closedBall 0 (rhoJ r j) ∧
      (∀ x, phiP p j (conj x) = phiP p j x) :=
  ⟨contDiff_phiCut (rhoJ_pos hr j) (by linarith [rhoJ_le hr j]) (contDiffOn_uP p),
    tsupport_phiCut (rhoJ_pos hr j), phiCut_conj (uP_conj p)⟩

theorem isLocalH_mPM {r : ℝ} (hr : 0 < r) (p : OutIdx 0 r) (j : ℕ) (s : ℝ) :
    K3.IsLocalH 0 r (mPM s (phiP p j)) := by
  obtain ⟨hφ, hsupp, -⟩ := phiP_props hr p j
  refine ⟨isAdmissibleH_mPM hφ hsupp s, rhoJ r j, by linarith [rhoJ_le hr j], ?_⟩
  rw [Complex.ofReal_zero]; exact mPM_compl hsupp s

/-- The Gaussian pair `(ν + bal m⁺ + m⁻, ν' + m⁺ + bal m⁻)`: its pairing is
`W - Z(m⁺) + Z(m⁻)`, the part of `W = X ν - X ν'` uncorrelated with the germ. -/
def qP {r : ℝ} (hr : 0 < r) (p : OutIdx 0 r) (j : ℕ) : BPair :=
  ⟨(p.1.1 + bal 0 r (mPM 1 (phiP p j)) + mPM (-1) (phiP p j),
      p.1.2 + mPM 1 (phiP p j) + bal 0 r (mPM (-1) (phiP p j))),
    isAdmissibleH_add (isAdmissibleH_add p.2.1 ((isLocalH_mPM hr p j 1).bal_spec hr).1)
      (isLocalH_mPM hr p j (-1)).1,
    isAdmissibleH_add (isAdmissibleH_add p.2.2.1 (isLocalH_mPM hr p j 1).1)
      ((isLocalH_mPM hr p j (-1)).bal_spec hr).1,
    by
      simp only [Measure.add_apply]
      rw [← ((isLocalH_mPM hr p j 1).bal_spec hr).2,
        ← ((isLocalH_mPM hr p j (-1)).bal_spec hr).2, p.2.2.2.1]⟩

/-- The outside pairing `W = X ν - X ν'`. -/
def Wf (X : Ω → FieldSample) {r : ℝ} (p : OutIdx 0 r) (ω : Ω) : ℝ := X ω p.1.1 - X ω p.1.2

/-- The decoupled pairing `V_j`. -/
def Vf (X : Ω → FieldSample) {r : ℝ} (hr : 0 < r) (j : ℕ) (p : OutIdx 0 r) (ω : Ω) : ℝ :=
  X ω (qP hr p j).1.1 - X ω (qP hr p j).1.2

/-- The local Gaussian variables `Z(m^±)`. -/
def Zm (X : Ω → FieldSample) {r : ℝ} (p : OutIdx 0 r) (j : ℕ) (s : ℝ) (ω : Ω) : ℝ :=
  K3.markovZ X 0 r ω (mPM s (phiP p j))

section Decomp

variable [IsProbabilityMeasure P] (hX : IsFreeGFFModConstH X P) {r : ℝ} (hr : 0 < r)
include hX

theorem memLp_pair {a b : Measure ℂ} (ha : IsAdmissibleH a) (hb : IsAdmissibleH b)
    (hab : a Set.univ = b Set.univ) : MemLp (fun ω => X ω a - X ω b) 2 P :=
  CircleFubini.gff_memLp hX (p := (a, b)) ha hb hab

theorem lateralGerm_le (r : ℝ) : lateralGerm X P r ≤ mΩ :=
  iSup₂_le fun μ h => by
    haveI := h.1.1
    exact measurable_iff_comap_le.1
      ((measurable_lateralPart_apply μ).comp (measurable_X_pi hX))

theorem aeSub_lateralGerm {G : Ω → ℂ × ℝ → ℝ} (hG : IsRegVersion X P G) (ε : ℝ) :
    AESub (lateralGerm X P ε)
      (MeasurableSpace.comap (fun ω (μ : GIdx X P ε) => gaussFam X latPairG μ ω) inferInstance)
      P :=
  aeSub_iSup fun μ => aeSub_iSup fun h =>
    aeSub_comap ((measurable_pi_apply (⟨μ, h⟩ : GIdx X P ε)).comp
      (comap_measurable (fun ω (μ : GIdx X P ε) => gaussFam X latPairG μ ω)))
      (ae_lateral_X hX hG h.1 h.2.2)

include hr

theorem memLp_markovZ {a : Measure ℂ} (ha : K3.IsLocalH 0 r a) :
    MemLp (fun ω => K3.markovZ X 0 r ω a) 2 P :=
  memLp_pair hX ha.1 (ha.bal_spec hr).1 (ha.bal_spec hr).2

theorem memLp_Vf (j : ℕ) (p : OutIdx 0 r) : MemLp (Vf X hr j p) 2 P :=
  memLp_pair hX (qP hr p j).2.1 (qP hr p j).2.2.1 (qP hr p j).2.2.2

theorem Vf_ae (p : OutIdx 0 r) (j : ℕ) :
    ∀ᵐ ω ∂P, Vf X hr j p ω = Wf X p ω - Zm X p j 1 ω + Zm X p j (-1) ω := by
  have h1 := isLocalH_mPM hr p j 1
  have h2 := isLocalH_mPM hr p j (-1)
  have hb1 := (h1.bal_spec hr).1
  have hb2 := (h2.bal_spec hr).1
  filter_upwards [ae_add_X hX (isAdmissibleH_add p.2.1 hb1) h2.1, ae_add_X hX p.2.1 hb1,
    ae_add_X hX (isAdmissibleH_add p.2.2.1 h1.1) hb2, ae_add_X hX p.2.2.1 h1.1]
    with ω e1 e2 e3 e4
  simp only [Vf, Wf, Zm, qP, K3.markovZ]
  rw [e1, e2, e3, e4]; ring

/-- `E (W - V_j)² = E_H(φ_j)`. -/
theorem integral_sq_Wf_sub_Vf (p : OutIdx 0 r) (j : ℕ) :
    ∫ ω, (Wf X p ω - Vf X hr j p ω) ^ 2 ∂P = dirichletEnergyOn H (phiP p j) := by
  obtain ⟨hφ, hsupp, heven⟩ := phiP_props hr p j
  have h1 := isLocalH_mPM hr p j 1
  have h2 := isLocalH_mPM hr p j (-1)
  have hZ1 : MemLp (Zm X p j 1) 2 P := memLp_markovZ hX hr h1
  have hZ2 : MemLp (Zm X p j (-1)) 2 P := memLp_markovZ hX hr h2
  have hZ12 := hZ1.sub hZ2
  have hae : (fun ω => (Wf X p ω - Vf X hr j p ω) ^ 2) =ᵐ[P]
      fun ω => ((Zm X p j 1 - Zm X p j (-1)) * (Zm X p j 1 - Zm X p j (-1))) ω := by
    filter_upwards [Vf_ae hX hr p j] with ω h
    simp only [Pi.mul_apply, Pi.sub_apply]
    rw [h]; ring
  have hm : ∫ ω, (Zm X p j 1 - Zm X p j (-1)) ω ∂P = 0 := by
    simp only [Pi.sub_apply]
    rw [integral_sub (hZ1.integrable one_le_two) (hZ2.integrable one_le_two)]
    simp only [Zm]
    rw [K3.integral_markovZ hX hr h1, K3.integral_markovZ hX hr h2, sub_zero]
  have c11 : cov[Zm X p j 1, Zm X p j 1; P] =
      kernelCov (halfDiscGreen 0 r) (mPM 1 (phiP p j)) (mPM 1 (phiP p j)) :=
    K3.covariance_markovZ hX hr h1 h1
  have c12 : cov[Zm X p j 1, Zm X p j (-1); P] =
      kernelCov (halfDiscGreen 0 r) (mPM 1 (phiP p j)) (mPM (-1) (phiP p j)) :=
    K3.covariance_markovZ hX hr h1 h2
  have c21 : cov[Zm X p j (-1), Zm X p j 1; P] =
      kernelCov (halfDiscGreen 0 r) (mPM (-1) (phiP p j)) (mPM 1 (phiP p j)) :=
    K3.covariance_markovZ hX hr h2 h1
  have c22 : cov[Zm X p j (-1), Zm X p j (-1); P] =
      kernelCov (halfDiscGreen 0 r) (mPM (-1) (phiP p j)) (mPM (-1) (phiP p j)) :=
    K3.covariance_markovZ hX hr h2 h2
  have hcov := covariance_eq_sub hZ12 hZ12
  rw [hm, mul_zero, sub_zero, covariance_sub_sub hZ1 hZ2 hZ1 hZ2, c11, c12, c21, c22] at hcov
  have hE := kernelCov_green_mPM_energy hr (rhoJ_pos hr j) (by linarith [rhoJ_le hr j]) hφ
    hsupp heven
  rw [integral_congr_ae hae]
  linarith

theorem cov_Lf_Wf (p : OutIdx 0 r) {ε : ℝ} (hε : ε < r) {μ : Measure ℂ}
    (hμ : IsAdmissibleH μ) (hμs : μ (closedBall 0 ε ∩ Hbar)ᶜ = 0) :
    cov[Lf X μ, Wf X p; P] = ∫ x, uP p x ∂μ - ∫ x, uP p x ∂(radSmear μ) := by
  have hc := hX.covariance_eq (μ, radSmear μ) p.1 hμ (isAdmissibleH_radSmear hμ)
    (radSmear_univ μ).symm p.2.1 p.2.2.1 p.2.2.2.1
  refine hc.trans ?_
  have := hμ.1
  have hS : μ (ballH ε)ᶜ = 0 := hμs
  have hS' : radSmear μ (ballH ε)ᶜ = 0 := radSmear_support hS
  have hint : ∀ ν : Measure ℂ, IsAdmissibleH ν → ν (ball ((0 : ℝ) : ℂ) r) = 0 →
      Integrable (potN ν) μ ∧ Integrable (potN ν) (radSmear μ) := fun ν hν hνB =>
    ⟨integrable_of_continuousOn_K (isCompact_ballH ε) hS
      ((contDiffOn_potN_out hν hνB).continuousOn.mono (ballH_subset_ball hε)),
     integrable_of_continuousOn_K (isCompact_ballH ε) hS'
      ((contDiffOn_potN_out hν hνB).continuousOn.mono (ballH_subset_ball hε))⟩
  obtain ⟨i1, i2⟩ := hint _ p.2.1 p.2.2.2.2.1
  obtain ⟨i3, i4⟩ := hint _ p.2.2.1 p.2.2.2.2.2
  show (∫ x, potN p.1.1 x ∂μ) - (∫ x, potN p.1.2 x ∂μ) - (∫ x, potN p.1.1 x ∂(radSmear μ)) +
    (∫ x, potN p.1.2 x ∂(radSmear μ)) = _
  simp only [uP]
  rw [integral_sub i1 i3, integral_sub i2 i4]
  ring

theorem cov_Lf_Z {ε : ℝ} (hε : ε < r) {μ : Measure ℂ} (hμ : IsAdmissibleH μ)
    (hμs : μ (closedBall 0 ε ∩ Hbar)ᶜ = 0) {a : Measure ℂ} (ha : K3.IsLocalH 0 r a) :
    cov[Lf X μ, fun ω => K3.markovZ X 0 r ω a; P] =
      kernelCov (halfDiscGreen 0 r) μ a - kernelCov (halfDiscGreen 0 r) (radSmear μ) a := by
  have hμl : K3.IsLocalH 0 r μ :=
    ⟨hμ, ε, hε, by rw [Complex.ofReal_zero]; exact closedBall_compl_null hμs⟩
  have hrl : K3.IsLocalH 0 r (radSmear μ) :=
    ⟨isAdmissibleH_radSmear hμ, ε, hε, by
      rw [Complex.ofReal_zero]; exact closedBall_compl_null (radSmear_support (R := ε) hμs)⟩
  have hbμ := hμl.bal_spec hr
  have hbr := hrl.bal_spec hr
  set O : Ω → ℝ := fun ω => X ω (bal 0 r μ) - X ω (bal 0 r (radSmear μ)) with hOdef
  have hmass : bal 0 r μ Set.univ = bal 0 r (radSmear μ) Set.univ := by
    rw [← hbμ.2, ← hbr.2, radSmear_univ]
  have hZμ := memLp_markovZ hX hr hμl
  have hZr := memLp_markovZ hX hr hrl
  have hZa := memLp_markovZ hX hr ha
  have hO : MemLp O 2 P := memLp_pair hX hbμ.1 hbr.1 hmass
  have hsplit : Lf X μ = ((fun ω => K3.markovZ X 0 r ω μ) -
      (fun ω => K3.markovZ X 0 r ω (radSmear μ))) + O := by
    funext ω; simp only [Lf, K3.markovZ, Pi.add_apply, Pi.sub_apply, hOdef]; ring
  rw [hsplit, covariance_add_left (hZμ.sub hZr) hO hZa, covariance_sub_left hZμ hZr hZa,
    K3.covariance_markovZ hX hr hμl ha, K3.covariance_markovZ hX hr hrl ha]
  have hind := K3.indep_markovZ_outside hX hr (t := 0)
  have hZam : Measurable[⨆ ν : {ν // K3.IsLocalH 0 r ν},
      MeasurableSpace.comap (fun ω => K3.markovZ X 0 r ω ν.1) inferInstance]
      (fun ω => K3.markovZ X 0 r ω a) :=
    measurable_iff_comap_le.2 (le_iSup (fun ν : {ν // K3.IsLocalH 0 r ν} =>
      MeasurableSpace.comap (fun ω => K3.markovZ X 0 r ω ν.1) inferInstance) ⟨a, ha⟩)
  have hOm : Measurable[K3.outsideSigma X 0 r] O :=
    K3.measurable_outsideSigma hbμ.1 hbr.1 hmass (K3.bal_ball hr) (K3.bal_ball hr)
  have hIF : IndepFun O (fun ω => K3.markovZ X 0 r ω a) P := by
    rw [IndepFun_iff_Indep]
    exact indep_of_indep_of_le_right (indep_of_indep_of_le_left hind.symm hOm.comap_le)
      hZam.comap_le
  rw [hIF.covariance_eq_zero hO hZa]; ring

theorem cov_Lf_Vf (p : OutIdx 0 r) (j : ℕ) {ε : ℝ} (hεj : ε ≤ rhoJ r j / 2) {μ : Measure ℂ}
    (hμ : IsAdmissibleH μ) (hμs : μ (closedBall 0 ε ∩ Hbar)ᶜ = 0) :
    cov[Lf X μ, Vf X hr j p; P] = 0 := by
  obtain ⟨hφ, hsupp, heven⟩ := phiP_props hr p j
  have hρ := rhoJ_pos hr j
  have hρr : rhoJ r j < r := by linarith [rhoJ_le hr j]
  have hε : ε < r := by linarith
  have h1 := isLocalH_mPM hr p j 1
  have h2 := isLocalH_mPM hr p j (-1)
  have hL : MemLp (Lf X μ) 2 P :=
    memLp_pair hX hμ (isAdmissibleH_radSmear hμ) (radSmear_univ μ).symm
  have hW : MemLp (Wf X p) 2 P := memLp_pair hX p.2.1 p.2.2.1 p.2.2.2.1
  have hZ1 : MemLp (Zm X p j 1) 2 P := memLp_markovZ hX hr h1
  have hZ2 : MemLp (Zm X p j (-1)) 2 P := memLp_markovZ hX hr h2
  have hV : Vf X hr j p =ᵐ[P] (Wf X p - Zm X p j 1) + Zm X p j (-1) := by
    filter_upwards [Vf_ae hX hr p j] with ω h
    simp only [Pi.add_apply, Pi.sub_apply]; exact h
  rw [WedgeTK.covariance_congr_ae (EventuallyEq.rfl) hV, covariance_add_right hL (hW.sub hZ1) hZ2,
    covariance_sub_right hL hW hZ1, cov_Lf_Wf hX hr p hε hμ hμs,
    show Zm X p j 1 = fun ω => K3.markovZ X 0 r ω (mPM 1 (phiP p j)) from rfl,
    show Zm X p j (-1) = fun ω => K3.markovZ X 0 r ω (mPM (-1) (phiP p j)) from rfl,
    cov_Lf_Z hX hr hε hμ hμs h1, cov_Lf_Z hX hr hε hμ hμs h2]
  have hS : μ (ballH ε)ᶜ = 0 := hμs
  have hS' : radSmear μ (ballH ε)ᶜ = 0 := radSmear_support hS
  have hμc : μ (closedBall ((0 : ℝ) : ℂ) ε)ᶜ = 0 := by
    rw [Complex.ofReal_zero]; exact closedBall_compl_null hμs
  have hrc : radSmear μ (closedBall ((0 : ℝ) : ℂ) ε)ᶜ = 0 := by
    rw [Complex.ofReal_zero]; exact closedBall_compl_null (radSmear_support (R := ε) hμs)
  have g1 := kernelCov_green_mPM_sub hr hε hρ hρr hφ hsupp heven hμ hμc
  have g2 := kernelCov_green_mPM_sub hr hε hρ hρr hφ hsupp heven (isAdmissibleH_radSmear hμ) hrc
  -- `u - φ = u 0` on the support
  have hcst : ∀ ν : Measure ℂ, IsFiniteMeasure ν → ν (ballH ε)ᶜ = 0 →
      ∫ x, uP p x ∂ν - ∫ x, phiP p j x ∂ν = ν.real Set.univ * uP p 0 := by
    intro ν _ hν
    have iu : Integrable (uP p) ν := integrable_of_continuousOn_K (isCompact_ballH ε) hν
      ((contDiffOn_uP p).continuousOn.mono (ballH_subset_ball hε))
    have iφ : Integrable (phiP p j) ν :=
      integrable_of_continuousOn_K (isCompact_ballH ε) hν hφ.continuous.continuousOn
    rw [← integral_sub iu iφ, ← smul_eq_mul, ← integral_const]
    refine integral_congr_ae ?_
    filter_upwards [mem_ae_iff.2 hν] with x hx
    have hxε : ‖x‖ ≤ rhoJ r j / 2 := (mem_closedBall_zero_iff.1 hx.1).trans hεj
    simp only [phiP]
    rw [phiCut_eq_of_le hρ hxε]; ring
  have := hμ.1
  have e1 := hcst μ inferInstance hS
  have e2 := hcst (radSmear μ) inferInstance hS'
  have hmass : (radSmear μ).real Set.univ = μ.real Set.univ := by
    rw [measureReal_def, measureReal_def, radSmear_univ]
  rw [hmass] at e2
  linarith

theorem indepFun_L_V (j : ℕ) {ε : ℝ} (hεj : ε ≤ rhoJ r j / 2) :
    IndepFun (fun ω (μ : GIdx X P ε) => gaussFam X latPairG μ ω)
      (fun ω (p : OutIdx 0 r) => Vf X hr j p ω) P := by
  let g : GIdx X P ε ⊕ OutIdx 0 r → BPair :=
    Sum.elim (latPairG (X := X) (P := P) (ε := ε)) fun p => qP hr p j
  have hG : IsGaussianProcess (Sum.elim (gaussFam X (latPairG (X := X) (P := P) (ε := ε)))
      fun p => Vf X hr j p) P := by
    have e : (Sum.elim (gaussFam X (latPairG (X := X) (P := P) (ε := ε)))
        fun p => Vf X hr j p) = gaussFam X g := by
      funext x; cases x <;> rfl
    rw [e]; exact isGaussianProcess_gaussFam hX g
  exact hG.indepFun_of_covariance_eq_zero (fun μ => (measurable_gaussFam hX _ μ).aemeasurable)
    (fun p => ((hX.measurable_coord _).sub (hX.measurable_coord _)).aemeasurable)
    (fun μ p => cov_Lf_Vf hX hr p j hεj μ.2.1 μ.2.2.1)

theorem indep_lateralGerm_V (j : ℕ) {ε : ℝ} (hεj : ε ≤ rhoJ r j / 2) :
    Indep (lateralGerm X P ε)
      (MeasurableSpace.comap (fun ω (p : OutIdx 0 r) => Vf X hr j p ω) inferInstance) P := by
  obtain ⟨G, hG⟩ := exists_isRegVersion hX
  have h := indepFun_L_V hX hr j hεj
  rw [IndepFun_iff_Indep] at h
  exact indep_of_aeSub h (aeSub_lateralGerm hX hG ε) (aeSub_of_le le_rfl)

theorem ae_tendsto_Vf (p : OutIdx 0 r) :
    ∀ᵐ ω ∂P, Tendsto (fun j => Vf X hr j p ω) atTop (𝓝 (Wf X p ω)) := by
  obtain ⟨Kc, hKc⟩ := energy_phiCut_le hr (contDiffOn_uP p)
  have hW : MemLp (Wf X p) 2 P := memLp_pair hX p.2.1 p.2.2.1 p.2.2.2.1
  have hgeo : Summable fun j : ℕ => Kc * (r / 4) ^ 2 * (1 / 4 : ℝ) ^ j :=
    (summable_geometric_of_lt_one (by norm_num) (by norm_num)).mul_left _
  have hs : Summable fun j => ∫ ω, (Wf X p ω - Vf X hr j p ω) ^ 2 ∂P := by
    refine Summable.of_nonneg_of_le (fun j => integral_nonneg fun ω => sq_nonneg _)
      (fun j => ?_) hgeo
    rw [integral_sq_Wf_sub_Vf hX hr p j]
    refine (hKc _ (rhoJ_pos hr j) (by linarith [rhoJ_le hr j])).trans (le_of_eq ?_)
    have : (1 / 4 : ℝ) ^ j = ((1 / 2 : ℝ) ^ j) ^ 2 := by
      rw [← pow_mul, mul_comm, pow_mul]; norm_num
    rw [this]; unfold rhoJ; ring
  have h := ae_tendsto_zero_of_summable_sq (f := fun j ω => Wf X p ω - Vf X hr j p ω)
    (fun j => (hW.sub (memLp_Vf hX hr j p)).aestronglyMeasurable.aemeasurable)
    (fun j => (hW.sub (memLp_Vf hX hr j p)).integrable_sq) hs
  filter_upwards [h] with ω hω
  have := hω.const_sub (Wf X p ω)
  simpa using this

theorem outsideSigma_le : K3.outsideSigma X 0 r ≤ mΩ :=
  iSup_le fun _ => ((hX.measurable_coord _).sub (hX.measurable_coord _)).comap_le

omit hr in
theorem outsideSigma_anti {r r' : ℝ} (h : r' ≤ r) :
    K3.outsideSigma X 0 r ≤ K3.outsideSigma X 0 r' :=
  iSup_le fun p => le_iSup_of_le (⟨p.1, p.2.1, p.2.2.1, p.2.2.2.1,
    measure_mono_null (ball_subset_ball h) p.2.2.2.2.1,
    measure_mono_null (ball_subset_ball h) p.2.2.2.2.2⟩ : K3.OutIdx 0 r') le_rfl

/-- **The germ is independent of the field outside `B(0,r)`.** -/
theorem indep_germ_outside :
    Indep (⨅ n : ℕ, lateralGerm X P ((2 : ℝ)⁻¹ ^ n)) (K3.outsideSigma X 0 r) P := by
  classical
  show Indep (germ X P) _ P
  have hG𝒢 : germ X P ≤ mΩ := (iInf_le _ 0).trans (lateralGerm_le hX _)
  have hVm : ∀ j (p : OutIdx 0 r), Measurable (Vf X hr j p) := fun j p =>
    (hX.measurable_coord _).sub (hX.measurable_coord _)
  have hWm : ∀ p : OutIdx 0 r, Measurable (Wf X p) := fun p =>
    (hX.measurable_coord _).sub (hX.measurable_coord _)
  have hVind : ∀ j, Indep (germ X P)
      (MeasurableSpace.comap (fun ω (p : OutIdx 0 r) => Vf X hr j p ω) inferInstance) P := by
    intro j
    obtain ⟨n, hn⟩ := exists_pow_lt_of_lt_one (half_pos (rhoJ_pos hr j))
      (show (2 : ℝ)⁻¹ < 1 by norm_num)
    exact indep_of_indep_of_le_left (indep_lateralGerm_V hX hr j hn.le) (iInf_le _ n)
  have hJ : ∀ J : Finset (OutIdx 0 r),
      Indep (MeasurableSpace.comap (fun ω (p : J) => Wf X p.1 ω) inferInstance) (germ X P) P := by
    intro J
    refine (indep_comap_of_tendsto_ae hG𝒢 (Y := fun j ω (p : J) => Vf X hr j p.1 ω)
      (fun j => measurable_pi_iff.2 fun p => hVm j p.1)
      (measurable_pi_iff.2 fun p => hWm p.1)
      (fun j => indep_of_indep_of_le_right (hVind j) ?_) ?_).symm
    · exact comap_le_comap_of_comp (F := fun ω (q : OutIdx 0 r) => Vf X hr j q ω)
        (R := fun v (p : J) => v p.1) (measurable_pi_iff.2 fun p => measurable_pi_apply _)
    · have := ae_all_iff.2 fun p : J => ae_tendsto_Vf hX hr p.1
      filter_upwards [this] with ω hω
      exact tendsto_pi_nhds.2 hω
  have hdir : Directed (· ≤ ·) fun J : Finset (OutIdx 0 r) =>
      MeasurableSpace.comap (fun ω (p : J) => Wf X p.1 ω) inferInstance := by
    intro J J'
    refine ⟨J ∪ J', ?_, ?_⟩
    · exact comap_le_comap_of_comp (F := fun ω (q : ↥(J ∪ J')) => Wf X q.1 ω)
        (R := fun v (p : J) => v ⟨p.1, Finset.mem_union_left _ p.2⟩)
        (measurable_pi_iff.2 fun p => measurable_pi_apply _)
    · exact comap_le_comap_of_comp (F := fun ω (q : ↥(J ∪ J')) => Wf X q.1 ω)
        (R := fun v (p : J') => v ⟨p.1, Finset.mem_union_right _ p.2⟩)
        (measurable_pi_iff.2 fun p => measurable_pi_apply _)
  have h := indep_iSup_of_directed_le hJ
    (fun J => (measurable_pi_iff.2 fun p : J => hWm p.1).comap_le) hG𝒢 hdir
  refine (indep_of_indep_of_le_left h ?_).symm
  refine iSup_le fun p => le_trans ?_ (le_iSup _ {p})
  exact measurable_iff_comap_le.1 ((measurable_pi_apply
    (⟨p, Finset.mem_singleton_self p⟩ : ↥({p} : Finset (OutIdx 0 r)))).comp
    (comap_measurable (fun ω (q : ↥({p} : Finset (OutIdx 0 r))) => Wf X q.1 ω)))

end Decomp

/-! ### The germ is generated by the outside fields, up to null sets -/

section Outside

variable [IsProbabilityMeasure P] (hX : IsFreeGFFModConstH X P)
include hX

theorem ae_Lf_sub_split {μ : Measure ℂ} (hμ : IsAdmissibleH μ) {s : Set ℂ}
    (hs : MeasurableSet s) :
    ∀ᵐ ω ∂P, Lf X μ ω - Lf X (μ.restrict sᶜ) ω = Lf X (μ.restrict s) ω := by
  have ha := isAdmissibleH_restrict hμ s
  have hb := isAdmissibleH_restrict hμ sᶜ
  have e1 : μ = μ.restrict s + μ.restrict sᶜ := (Measure.restrict_add_restrict_compl hs).symm
  have e2 : radSmear μ = radSmear (μ.restrict s) + radSmear (μ.restrict sᶜ) := by
    rw [← radSmear_add, Measure.restrict_add_restrict_compl hs]
  filter_upwards [ae_add_X hX ha hb, ae_add_X hX (isAdmissibleH_radSmear ha)
    (isAdmissibleH_radSmear hb)] with ω h1 h2
  have h1' : X ω μ = X ω (μ.restrict s) + X ω (μ.restrict sᶜ) := by rw [← h1, ← e1]
  have h2' : X ω (radSmear μ) = X ω (radSmear (μ.restrict s)) +
      X ω (radSmear (μ.restrict sᶜ)) := by rw [← h2, ← e2]
  simp only [Lf]
  rw [h1', h2']; ring

theorem abs_kernelCov_restrict_le {μ : Measure ℂ} (hμ : IsAdmissibleH μ) :
    ∃ Kt : ℝ, 0 ≤ Kt ∧ ∀ s : Set ℂ, MeasurableSet s →
      ∫ ω, (Lf X (μ.restrict s) ω) ^ 2 ∂P ≤ 4 * (μ s).toReal * Kt := by
  have := hμ.1
  obtain ⟨R, hR⟩ := exists_ballH_of_admissible hμ
  obtain ⟨C₁, hC₁, hb₁⟩ := hμ.2.2
  obtain ⟨C₂, hC₂, hb₂⟩ := (isAdmissibleH_radSmear hμ).2.2
  set C := C₁ + C₂
  have hCt : C ≠ ⊤ := ENNReal.add_ne_top.2 ⟨hC₁.ne, hC₂.ne⟩
  set Ke : ℝ≥0∞ := ENNReal.ofReal (2 * Real.log (max (2 * R) 1)) * μ Set.univ + 2 * C
  have hKe : Ke ≠ ⊤ := ENNReal.add_ne_top.2 ⟨ENNReal.mul_ne_top ENNReal.ofReal_ne_top
    (measure_ne_top _ _), ENNReal.mul_ne_top (by simp) hCt⟩
  refine ⟨Ke.toReal, ENNReal.toReal_nonneg, fun s hs => ?_⟩
  set a := μ.restrict s
  have ha := isAdmissibleH_restrict hμ s
  have hra := isAdmissibleH_radSmear ha
  have haS : a (ballH R)ᶜ = 0 :=
    nonpos_iff_eq_zero.1 ((Measure.restrict_apply_le _ _).trans hR.le)
  have hraS : radSmear a (ballH R)ᶜ = 0 := radSmear_support haS
  have hapot : ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂a ≤ C := fun y =>
    ((lintegral_mono' Measure.restrict_le_self le_rfl).trans (hb₁ y)).trans le_self_add
  have hrpot : ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂(radSmear a) ≤ C := fun y =>
    ((lintegral_mono' (radSmear_mono Measure.restrict_le_self) le_rfl).trans (hb₂ y)).trans
      le_add_self
  have hau : a Set.univ = μ s := by rw [Measure.restrict_apply_univ]
  have hrau : radSmear a Set.univ = μ s := by rw [radSmear_univ, hau]
  have hle : ∀ b : Measure ℂ, b Set.univ ≤ μ Set.univ →
      ENNReal.ofReal (2 * Real.log (max (2 * R) 1)) * b Set.univ + 2 * C ≤ Ke := fun b hb =>
    add_le_add (mul_le_mul' le_rfl hb) le_rfl
  have hsu : μ s ≤ μ Set.univ := measure_mono (subset_univ _)
  have bnd : ∀ (c b : Measure ℂ) [IsFiniteMeasure c] [IsFiniteMeasure b],
      c (ballH R)ᶜ = 0 → b (ballH R)ᶜ = 0 → c Set.univ = μ s → b Set.univ ≤ μ Set.univ →
      (∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂b ≤ C) →
      |kernelCov neumannH c b| ≤ (μ s).toReal * Ke.toReal := by
    intro c b _ _ hc hb hcu hbu hbp
    refine (abs_kernelCov_le hc hb hCt hbp).trans ?_
    rw [← ENNReal.toReal_mul]
    refine ENNReal.toReal_mono (ENNReal.mul_ne_top (measure_ne_top _ _) hKe) ?_
    unfold nBound
    rw [hcu]
    exact mul_le_mul' le_rfl (hle b hbu)
  have := ha.1
  have := hra.1
  have k1 := bnd a a haS haS hau (hau.trans_le hsu) hapot
  have k2 := bnd a (radSmear a) haS hraS hau (hrau.trans_le hsu) hrpot
  have k3 := bnd (radSmear a) a hraS haS hrau (hau.trans_le hsu) hapot
  have k4 := bnd (radSmear a) (radSmear a) hraS hraS hrau (hrau.trans_le hsu) hrpot
  have hI := CircleFubini.gff_integral_mul hX (p := (a, radSmear a)) (q := (a, radSmear a))
    ha hra (radSmear_univ a).symm ha hra (radSmear_univ a).symm
  have e : ∫ ω, (Lf X a ω) ^ 2 ∂P = kernelCov2 neumannH (a, radSmear a) (a, radSmear a) := by
    rw [← hI]; simp only [Lf, sq]
  rw [e]
  unfold kernelCov2
  simp only
  have := abs_le.1 k1
  have := abs_le.1 k2
  have := abs_le.1 k3
  have := abs_le.1 k4
  linarith

/-- The outside σ-algebra at all dyadic scales. -/
def outsideAll (X : Ω → FieldSample) : MeasurableSpace Ω :=
  ⨆ k : ℕ, K3.outsideSigma X 0 ((2 : ℝ)⁻¹ ^ k)

theorem tendsto_measure_closedBall_zero {μ : Measure ℂ} (hμ : IsAdmissibleH μ) :
    Tendsto (fun k : ℕ => μ (closedBall 0 ((2 : ℝ)⁻¹ ^ k))) atTop (𝓝 0) := by
  have := hμ.1
  have hanti : Antitone fun k : ℕ => closedBall (0 : ℂ) ((2 : ℝ)⁻¹ ^ k) := fun a b h =>
    closedBall_subset_closedBall (pow_le_pow_of_le_one (by norm_num) (by norm_num) h)
  have ht := tendsto_measure_iInter_atTop (μ := μ)
    (fun k => measurableSet_closedBall.nullMeasurableSet) hanti ⟨0, measure_ne_top μ _⟩
  have hI : ⋂ k : ℕ, closedBall (0 : ℂ) ((2 : ℝ)⁻¹ ^ k) = {0} := by
    ext z
    simp only [mem_iInter, mem_closedBall_zero_iff, mem_singleton_iff]
    constructor
    · intro h
      by_contra hz
      obtain ⟨k, hk⟩ := exists_pow_lt_of_lt_one (norm_pos_iff.2 hz)
        (show (2 : ℝ)⁻¹ < 1 by norm_num)
      linarith [h k]
    · rintro rfl k; simp
  rw [hI, noAtoms_of_isAdmissibleH hμ 0] at ht
  exact ht

/-- Every lateral pair `X μ - X(radSmear μ)` has a version measurable for the outside fields. -/
theorem exists_outside_version {μ : Measure ℂ} (hμ : IsAdmissibleH μ) :
    ∃ g : Ω → ℝ, Measurable[outsideAll X] g ∧ Lf X μ =ᵐ[P] g := by
  have := hμ.1
  obtain ⟨Kt, hKt0, hKt⟩ := abs_kernelCov_restrict_le hX hμ
  have hsmall : ∀ j : ℕ, ∃ k : ℕ, μ (closedBall 0 ((2 : ℝ)⁻¹ ^ k)) ≤ ENNReal.ofReal ((1 / 2) ^ j) :=
    fun j => by
      obtain ⟨N, hN⟩ := (ENNReal.tendsto_atTop_zero.1 (tendsto_measure_closedBall_zero hX hμ))
        (ENNReal.ofReal ((1 / 2) ^ j)) (ENNReal.ofReal_pos.2 (by positivity))
      exact ⟨N, hN N le_rfl⟩
  choose k hk using hsmall
  set δ : ℕ → ℝ := fun j => (2 : ℝ)⁻¹ ^ k j
  have hδ : ∀ j, 0 < δ j := fun j => by positivity
  set Y : ℕ → Ω → ℝ := fun j => Lf X (μ.restrict (closedBall 0 (δ j))ᶜ)
  have hYm : ∀ j, Measurable[outsideAll X] (Y j) := by
    intro j
    set ν := μ.restrict (closedBall (0 : ℂ) (δ j))ᶜ
    have hν := isAdmissibleH_restrict hμ (closedBall (0 : ℂ) (δ j))ᶜ
    have hνB : ν (ball ((0 : ℝ) : ℂ) (δ j)) = 0 := by
      rw [Complex.ofReal_zero, Measure.restrict_apply measurableSet_ball]
      rw [show ball (0 : ℂ) (δ j) ∩ (closedBall 0 (δ j))ᶜ = ∅ from
        Set.eq_empty_of_forall_notMem fun x hx => hx.2 (ball_subset_closedBall hx.1)]
      exact measure_empty
    have hrB : radSmear ν (ball ((0 : ℝ) : ℂ) (δ j)) = 0 := by
      rw [Complex.ofReal_zero]
      refine radSmear_ball_eq_zero (hδ j) ?_
      filter_upwards [ae_restrict_mem measurableSet_closedBall.compl] with z hz
      rw [mem_compl_iff, mem_closedBall_zero_iff, not_le] at hz
      exact hz.le
    exact (K3.measurable_outsideSigma hν (isAdmissibleH_radSmear hν) (radSmear_univ ν).symm hνB
      hrB).mono (le_iSup (fun k : ℕ => K3.outsideSigma X 0 ((2 : ℝ)⁻¹ ^ k)) (k j)) le_rfl
  have hLm : MemLp (Lf X μ) 2 P :=
    memLp_pair hX hμ (isAdmissibleH_radSmear hμ) (radSmear_univ μ).symm
  have hYL : ∀ j, MemLp (Y j) 2 P := fun j => by
    have hν := isAdmissibleH_restrict hμ (closedBall (0 : ℂ) (δ j))ᶜ
    exact memLp_pair hX hν (isAdmissibleH_radSmear hν) (radSmear_univ _).symm
  have hdiff : ∀ j, (fun ω => Lf X μ ω - Y j ω) =ᵐ[P]
      Lf X (μ.restrict (closedBall (0 : ℂ) (δ j))) :=
    fun j => ae_Lf_sub_split hX hμ measurableSet_closedBall
  have hInL : ∀ j, MemLp (Lf X (μ.restrict (closedBall (0 : ℂ) (δ j)))) 2 P := fun j => by
    have hν := isAdmissibleH_restrict hμ (closedBall (0 : ℂ) (δ j))
    exact memLp_pair hX hν (isAdmissibleH_radSmear hν) (radSmear_univ _).symm
  have hs : Summable fun j => ∫ ω, (Lf X μ ω - Y j ω) ^ 2 ∂P := by
    have hgeo : Summable fun j : ℕ => 4 * Kt * (1 / 2 : ℝ) ^ j :=
      (summable_geometric_of_lt_one (by norm_num) (by norm_num)).mul_left _
    refine Summable.of_nonneg_of_le (fun j => integral_nonneg fun ω => sq_nonneg _)
      (fun j => ?_) hgeo
    have e : ∫ ω, (Lf X μ ω - Y j ω) ^ 2 ∂P =
        ∫ ω, (Lf X (μ.restrict (closedBall (0 : ℂ) (δ j))) ω) ^ 2 ∂P :=
      integral_congr_ae ((hdiff j).mono fun ω h => by simp only [h])
    rw [e]
    refine (hKt _ measurableSet_closedBall).trans ?_
    have hμj : (μ (closedBall (0 : ℂ) (δ j))).toReal ≤ (1 / 2) ^ j :=
      ENNReal.toReal_le_of_le_ofReal (by positivity) (hk j)
    nlinarith
  have hconv := ae_tendsto_zero_of_summable_sq (f := fun j ω => Lf X μ ω - Y j ω)
    (fun j => (hLm.sub (hYL j)).aestronglyMeasurable.aemeasurable)
    (fun j => (hLm.sub (hYL j)).integrable_sq) hs
  refine exists_measurable_ae_eq_of_tendsto hYm ?_
  filter_upwards [hconv] with ω hω
  have := hω.const_sub (Lf X μ ω)
  simpa using this

theorem aeSub_lateralGerm_outside (r : ℝ) : AESub (lateralGerm X P r) (outsideAll X) P := by
  obtain ⟨G, hG⟩ := exists_isRegVersion hX
  exact aeSub_iSup fun μ => aeSub_iSup fun h => by
    obtain ⟨g, hg, hLg⟩ := exists_outside_version hX h.1
    exact aeSub_comap hg ((show (fun ω => lateralPart (X ω) μ) =ᵐ[P] Lf X μ from
      ae_lateral_X hX hG h.1 h.2.2).trans hLg)

/-- **E-L11 (lateral germ triviality).** For a free-boundary GFF modulo constants `X`, the germ
at `0` of its lateral part is `P`-trivial. -/
theorem isTrivialSigma_lateralGerm :
    GermZeroOne.IsTrivialSigma (⨅ n : ℕ, lateralGerm X P ((2 : ℝ)⁻¹ ^ n)) P := by
  show GermZeroOne.IsTrivialSigma (germ X P) P
  have h𝒢 : germ X P ≤ mΩ := (iInf_le _ 0).trans (lateralGerm_le hX _)
  have hmono : Monotone fun k : ℕ => K3.outsideSigma X 0 ((2 : ℝ)⁻¹ ^ k) := fun a b h =>
    outsideSigma_anti hX (pow_le_pow_of_le_one (by norm_num) (by norm_num) h)
  have hind : Indep (germ X P) (outsideAll X) P :=
    (indep_iSup_of_directed_le (fun k => (indep_germ_outside hX (by positivity : (0 : ℝ) <
      (2 : ℝ)⁻¹ ^ k)).symm) (fun k => outsideSigma_le hX (by positivity)) h𝒢
      hmono.directed_le).symm
  have hsub : AESub (germ X P) (outsideAll X) P :=
    (aeSub_of_le (iInf_le _ 0)).trans (aeSub_lateralGerm_outside hX _)
  exact isTrivialSigma_of_indep_aeSub hind hsub

end Outside

end Field

end LateralGerm
end QuantumZipper
