import QuantumZipper.Proofs.GFF.K3.HalfDiscPoisson
import QuantumZipper.Proofs.GFF.CircleFubini
import QuantumZipper.Proofs.GFF.CircleContinuity
import LQGDimension.LFPP.CouplingAux2
import Mathlib.Probability.Distributions.Gaussian.IsGaussianProcess.Independence

/-!
# Domain Markov property of the free field on a half-disc (blueprint GFF-K3, node L2)

For `t ∈ ℝ`, `r > 0`, let `P_z = halfDiscPoisson t r z` (node L1) and
`bal μ = μ.bind P` (the balayage of `μ` onto the folded semicircle). For a free-boundary GFF
modulo constants `X`:

* `Z μ := X μ - X (bal μ)` is, for local `μ` (admissible, carried by `closedBall t r'`,
  `r' < r`), a centered Gaussian process with covariance `kernelCov (halfDiscGreen t r)`,
  independent of the outside σ-algebra `outsideSigma X t r` (generated by balanced differences
  of measures giving no mass to `ball t r`);
* `h z := X (P_z) - X (P_{z₀})` has a version continuous in `z` and measurable for
  `outsideSigma`, and `X μ = Z μ + ∫ h dμ + μ(ℂ) X(P_{z₀})` a.s. (stochastic Fubini).

The key kernel identity is `kernelCov neumannH (bal μ) ρ = kernelCov neumannH μ ρ` whenever
`ρ (ball t r) = 0` (from L1 and its arc case, proved here by a limit from outside).
-/

noncomputable section

open MeasureTheory ProbabilityTheory Metric Filter Topology
open scoped Real ComplexConjugate ENNReal NNReal

namespace QuantumZipper

namespace K3

open CircleFubini (ballH potConst nBound)

/-! ## 1. The arc case of the Neumann-kernel reproduction -/

theorem measurable_neumannH_left_k3 (y : ℂ) : Measurable fun x => neumannH x y :=
  measurable_neumannH.comp (measurable_id.prodMk measurable_const)

theorem integral_neumannH_halfDiscPoisson_eq_circle (t r : ℝ) {z : ℂ} (hz : z ∈ ball (t : ℂ) r)
    (y : ℂ) :
    ∫ x, neumannH x y ∂(halfDiscPoisson t r z) =
      ∫ w, (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 * neumannH w y ∂(circleUnif (t : ℂ) r) := by
  have hpos : 0 ≤ r ^ 2 - ‖z - t‖ ^ 2 := by
    have := mem_ball_iff_norm.1 hz; nlinarith [norm_nonneg (z - t)]
  rw [integral_halfDiscPoisson_eq_circle t r z (measurable_neumannH_left_k3 y).aestronglyMeasurable]
  refine integral_congr_ae (ae_of_all _ fun w => ?_)
  simp only [smul_eq_mul]
  rw [ENNReal.toReal_ofReal (div_nonneg hpos (sq_nonneg _))]
  congr 1
  unfold foldH
  split_ifs
  · rfl
  · exact neumannH_conj_left_k3 w y

theorem sq_norm_eq_k3 (z : ℂ) : ‖z‖ ^ 2 = z.re ^ 2 + z.im ^ 2 := by
  rw [Complex.sq_norm, Complex.normSq_apply]; ring

/-- Pushing a point of the circle radially outwards increases its distance to every point of
the circle. -/
theorem norm_sub_le_norm_sub_radial {t r s : ℝ} (hs : 0 ≤ s) {x y : ℂ} (hx : ‖x - t‖ = r)
    (hy : ‖y - t‖ = r) : ‖x - y‖ ≤ ‖x - (y + (s : ℂ) * (y - t))‖ := by
  refine le_of_pow_le_pow_left₀ two_ne_zero (norm_nonneg _) ?_
  have hx2 := sq_norm_eq_k3 (x - t)
  have hy2 := sq_norm_eq_k3 (y - t)
  rw [hx] at hx2; rw [hy] at hy2
  rw [sq_norm_eq_k3, sq_norm_eq_k3]
  simp only [Complex.sub_re, Complex.sub_im, Complex.add_re, Complex.add_im, Complex.mul_re,
    Complex.mul_im, Complex.ofReal_re, Complex.ofReal_im] at hx2 hy2 ⊢
  have e : s * ((x.re - t) ^ 2 + (x.im - 0) ^ 2) = s * ((y.re - t) ^ 2 + (y.im - 0) ^ 2) := by
    rw [← hx2, ← hy2]
  nlinarith [e, mul_nonneg hs (add_nonneg (sq_nonneg (x.re - y.re)) (sq_nonneg (x.im - y.im))),
    mul_nonneg (mul_nonneg hs hs) (add_nonneg (sq_nonneg (y.re - t)) (sq_nonneg (y.im - 0)))]

theorem abs_log_le_of_le_k3 {a b c : ℝ} (hb : 0 < b) (hba : b ≤ a) (hac : a ≤ c) :
    |Real.log a| ≤ |Real.log b| + |Real.log c| := by
  have ha : 0 < a := lt_of_lt_of_le hb hba
  rcases le_total 0 (Real.log a) with h | h
  · rw [abs_of_nonneg h]
    have := Real.log_le_log ha hac
    linarith [le_abs_self (Real.log c), abs_nonneg (Real.log b)]
  · rw [abs_of_nonpos h]
    have := Real.log_le_log hb hba
    linarith [neg_abs_le (Real.log b), abs_nonneg (Real.log c)]

theorem ae_ne_circMeas_k3 (c : ℂ) {r : ℝ} (hr : r ≠ 0) (p : ℂ) :
    ∀ᵐ w ∂LQGDimension.Coupling.circMeas c r, w ≠ p := by
  rw [ae_iff]; simpa using LQGDimension.Coupling.circMeas_singleton hr p

/-- **Arc case of L1**: the reproduction of `neumannH (·, y)` also holds for `y` on the circle,
by a limit `y_n → y` from outside, dominated on the circle. -/
theorem integral_neumannH_halfDiscPoisson_sphere {t r : ℝ} (hr : 0 < r) {z : ℂ}
    (hz : z ∈ ball (t : ℂ) r) {y : ℂ} (hy : y ∈ sphere (t : ℂ) r) :
    ∫ x, neumannH x y ∂(halfDiscPoisson t r z) = neumannH z y := by
  set s : ℕ → ℝ := fun n => 1 / ((n : ℝ) + 1) with hs
  have hs0 : ∀ n, 0 < s n := fun n => by positivity
  have hs1 : ∀ n, s n ≤ 1 := fun n => by
    simp only [hs]; rw [div_le_one (by positivity)]; linarith [(n.cast_nonneg : (0 : ℝ) ≤ n)]
  set yn : ℕ → ℂ := fun n => y + (s n : ℂ) * (y - t) with hyn
  have hyt : ‖y - t‖ = r := mem_sphere_iff_norm.1 hy
  have hycon : ‖conj y - t‖ = r := by rw [norm_conj_sub_ofReal_k3, hyt]
  have hynt : ∀ n, ‖yn n - t‖ = (1 + s n) * r := fun n => by
    have : yn n - t = ((1 + s n : ℝ) : ℂ) * (y - t) := by simp only [hyn]; push_cast; ring
    rw [this, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_pos (by linarith [hs0 n]),
      hyt]
  have hconj_yn : ∀ n, conj (yn n) = conj y + (s n : ℂ) * (conj y - t) := fun n => by
    simp only [hyn, map_add, map_mul, map_sub, Complex.conj_ofReal]
  have hyn_out : ∀ n, yn n ∉ closedBall (t : ℂ) r := fun n h => by
    rw [mem_closedBall_iff_norm, hynt] at h; nlinarith [hs0 n]
  have hL1 : ∀ n, ∫ x, neumannH x (yn n) ∂(halfDiscPoisson t r z) = neumannH z (yn n) :=
    fun n => integral_neumannH_halfDiscPoisson hr hz (hyn_out n)
  have hs_lim : Tendsto s atTop (𝓝 0) := tendsto_one_div_add_atTop_nhds_zero_nat
  have hyn_lim : Tendsto yn atTop (𝓝 y) := by
    have : Tendsto (fun n => y + (s n : ℂ) * (y - t)) atTop
        (𝓝 (y + ((0 : ℝ) : ℂ) * (y - t))) :=
      tendsto_const_nhds.add
        (((Complex.continuous_ofReal.tendsto 0).comp hs_lim).mul tendsto_const_nhds)
    simpa using this
  have hcontN : ∀ x, x ≠ y → x ≠ conj y → ContinuousAt (fun w => neumannH x w) y := by
    intro x h1 h2
    unfold neumannH
    have c1 : ContinuousAt (fun w : ℂ => ‖x - w‖) y :=
      (continuous_const.sub continuous_id).norm.continuousAt
    have c2 : ContinuousAt (fun w : ℂ => ‖x - conj w‖) y :=
      (continuous_const.sub Complex.continuous_conj).norm.continuousAt
    exact (c1.log (norm_ne_zero_iff.2 (sub_ne_zero.2 h1))).neg.sub
      (c2.log (norm_ne_zero_iff.2 (sub_ne_zero.2 h2)))
  have hzt : ‖z - t‖ < r := mem_ball_iff_norm.1 hz
  have hzy : z ≠ y := by
    rintro rfl; exact absurd hyt (ne_of_lt hzt)
  have hzy' : z ≠ conj y := by
    intro h; rw [h, hycon] at hzt; exact lt_irrefl _ hzt
  have hR : Tendsto (fun n => neumannH z (yn n)) atTop (𝓝 (neumannH z y)) :=
    (hcontN z hzy hzy').tendsto.comp hyn_lim
  -- the dominated convergence on the circle
  set ρ : ℂ → ℝ := fun w => (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 with hρ
  set ρmax : ℝ := r ^ 2 / (r - ‖z - t‖) ^ 2 with hρmax
  have hd : 0 < r - ‖z - t‖ := by linarith
  have hρm : Measurable ρ :=
    measurable_const.div ((measurable_id.sub measurable_const).norm.pow_const 2)
  have hρb : ∀ w : ℂ, ‖w - (t : ℂ)‖ = r → 0 ≤ ρ w ∧ ρ w ≤ ρmax := by
    intro w hw
    have hwz : r - ‖z - t‖ ≤ ‖w - z‖ := by
      have := norm_sub_norm_le (w - t) (z - t)
      rw [sub_sub_sub_cancel_right] at this; linarith
    have hnum0 : 0 ≤ r ^ 2 - ‖z - t‖ ^ 2 := by nlinarith [norm_nonneg (z - t)]
    refine ⟨div_nonneg hnum0 (sq_nonneg _), ?_⟩
    calc ρ w ≤ r ^ 2 / ‖w - z‖ ^ 2 :=
          div_le_div_of_nonneg_right (by nlinarith [norm_nonneg (z - t)]) (sq_nonneg _)
      _ ≤ ρmax := div_le_div_of_nonneg_left (sq_nonneg r) (pow_pos hd 2)
          (pow_le_pow_left₀ hd.le hwz 2)
  have hLHS : Tendsto (fun n => ∫ x, neumannH x (yn n) ∂(halfDiscPoisson t r z)) atTop
      (𝓝 (∫ x, neumannH x y ∂(halfDiscPoisson t r z))) := by
    simp_rw [integral_neumannH_halfDiscPoisson_eq_circle t r hz, circleUnif_eq_circMeas_k3]
    have hlog1 : Integrable (fun w => |Real.log ‖w - y‖|)
        (LQGDimension.Coupling.circMeas (t : ℂ) r) := by
      have := (LQGDimension.Coupling.integrable_log_norm_sub_circ y (t : ℂ) r).abs
      simpa only [norm_sub_rev y] using this
    have hlog2 : Integrable (fun w => |Real.log ‖w - conj y‖|)
        (LQGDimension.Coupling.circMeas (t : ℂ) r) := by
      have := (LQGDimension.Coupling.integrable_log_norm_sub_circ (conj y) (t : ℂ) r).abs
      simpa only [norm_sub_rev (conj y)] using this
    have hsph : ∀ᵐ (w : ℂ) ∂LQGDimension.Coupling.circMeas (t : ℂ) r, ‖w - (t : ℂ)‖ = r := by
      filter_upwards [LQGDimension.Coupling.ae_circMeas (t : ℂ) r] with w hw
      rw [hw, abs_of_pos hr]
    refine tendsto_integral_of_dominated_convergence
      (fun w => ρmax * (|Real.log ‖w - y‖| + |Real.log ‖w - conj y‖| + 2 * |Real.log (3 * r)|))
      (fun n => (hρm.mul (measurable_neumannH_left_k3 _)).aestronglyMeasurable)
      (((hlog1.add hlog2).add (integrable_const _)).const_mul ρmax) (fun n => ?_) ?_
    · filter_upwards [hsph, ae_ne_circMeas_k3 (t : ℂ) hr.ne' y,
        ae_ne_circMeas_k3 (t : ℂ) hr.ne' (conj y)] with w hw hwy hwy'
      obtain ⟨hρ0, hρ1⟩ := hρb w hw
      have b1 : |Real.log ‖w - yn n‖| ≤ |Real.log ‖w - y‖| + |Real.log (3 * r)| := by
        refine abs_log_le_of_le_k3 (norm_pos_iff.2 (sub_ne_zero.2 hwy))
          (norm_sub_le_norm_sub_radial (hs0 n).le hw hyt) ?_
        calc ‖w - yn n‖ = ‖(w - t) - (yn n - t)‖ := by ring_nf
          _ ≤ ‖w - t‖ + ‖yn n - t‖ := norm_sub_le _ _
          _ ≤ 3 * r := by rw [hw, hynt]; nlinarith [hs1 n]
      have b2 : |Real.log ‖w - conj (yn n)‖| ≤ |Real.log ‖w - conj y‖| + |Real.log (3 * r)| := by
        rw [hconj_yn]
        refine abs_log_le_of_le_k3 (norm_pos_iff.2 (sub_ne_zero.2 hwy'))
          (norm_sub_le_norm_sub_radial (hs0 n).le hw hycon) ?_
        calc ‖w - (conj y + (s n : ℂ) * (conj y - t))‖
            = ‖(w - t) - (conj y + (s n : ℂ) * (conj y - t) - t)‖ := by ring_nf
          _ ≤ ‖w - t‖ + ‖conj y + (s n : ℂ) * (conj y - t) - t‖ := norm_sub_le _ _
          _ = ‖w - t‖ + ‖conj (yn n) - t‖ := by rw [hconj_yn]
          _ ≤ 3 * r := by
            rw [hw, norm_conj_sub_ofReal_k3, hynt]; nlinarith [hs1 n]
      have hN : |neumannH w (yn n)| ≤
          |Real.log ‖w - y‖| + |Real.log ‖w - conj y‖| + 2 * |Real.log (3 * r)| := by
        unfold neumannH
        calc |-Real.log ‖w - yn n‖ - Real.log ‖w - conj (yn n)‖|
            ≤ |Real.log ‖w - yn n‖| + |Real.log ‖w - conj (yn n)‖| := by
              rw [show -Real.log ‖w - yn n‖ - Real.log ‖w - conj (yn n)‖ =
                -(Real.log ‖w - yn n‖ + Real.log ‖w - conj (yn n)‖) by ring, abs_neg]
              exact abs_add_le _ _
          _ ≤ _ := by linarith
      rw [Real.norm_eq_abs, abs_mul, abs_of_nonneg hρ0]
      exact mul_le_mul hρ1 hN (abs_nonneg _) (hρ0.trans hρ1)
    · filter_upwards [ae_ne_circMeas_k3 (t : ℂ) hr.ne' y,
        ae_ne_circMeas_k3 (t : ℂ) hr.ne' (conj y)] with w hwy hwy'
      exact tendsto_const_nhds.mul ((hcontN w hwy hwy').tendsto.comp hyn_lim)
  have := hLHS
  simp_rw [hL1] at this
  exact tendsto_nhds_unique this hR

/-- Reproduction of `neumannH (·, y)` for every `y` outside the open disc. -/
theorem integral_neumannH_halfDiscPoisson_of_not_mem_ball {t r : ℝ} (hr : 0 < r) {z : ℂ}
    (hz : z ∈ ball (t : ℂ) r) {y : ℂ} (hy : y ∉ ball (t : ℂ) r) :
    ∫ x, neumannH x y ∂(halfDiscPoisson t r z) = neumannH z y := by
  by_cases h : y ∈ closedBall (t : ℂ) r
  · refine integral_neumannH_halfDiscPoisson_sphere hr hz ?_
    rw [mem_sphere_iff_norm]
    rw [mem_closedBall_iff_norm] at h
    rw [mem_ball_iff_norm, not_lt] at hy
    exact le_antisymm h hy
  · exact integral_neumannH_halfDiscPoisson hr hz h

/-! ## 2. Comparison with the folded circle; admissibility -/

theorem halfDiscPoisson_density_le {t r r' : ℝ} (hr'r : r' < r) {z w : ℂ} (hz : ‖z - t‖ ≤ r')
    (hw : ‖w - t‖ = r) : (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 ≤ r ^ 2 / (r - r') ^ 2 := by
  have hwz : r - r' ≤ ‖w - z‖ := by
    have := norm_sub_norm_le (w - t) (z - t)
    rw [sub_sub_sub_cancel_right] at this; linarith
  have hd : 0 < r - r' := by linarith
  calc (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 ≤ r ^ 2 / ‖w - z‖ ^ 2 :=
        div_le_div_of_nonneg_right (by nlinarith [norm_nonneg (z - t)]) (sq_nonneg _)
    _ ≤ r ^ 2 / (r - r') ^ 2 :=
        div_le_div_of_nonneg_left (sq_nonneg r) (pow_pos hd 2) (pow_le_pow_left₀ hd.le hwz 2)

/-- The density bound `r² / (r - r')²`. -/
def pBound (r r' : ℝ) : ℝ≥0∞ := ENNReal.ofReal (r ^ 2 / (r - r') ^ 2)

/-- The potential bound for half-disc Poisson measures of points of `closedBall t r'`. -/
def potC (r r' : ℝ) : ℝ≥0∞ := pBound r r' * (2 * ENNReal.ofReal (potConst r))

theorem potC_ne_top (r r' : ℝ) : potC r r' ≠ ⊤ :=
  ENNReal.mul_ne_top ENNReal.ofReal_ne_top (ENNReal.mul_ne_top (by simp) ENNReal.ofReal_ne_top)

theorem halfDiscPoisson_le {t r r' : ℝ} (hr : 0 < r) (hr'r : r' < r) {z : ℂ}
    (hz : ‖z - t‖ ≤ r') : halfDiscPoisson t r z ≤ pBound r r' • foldedCircle (t : ℂ) r := by
  unfold halfDiscPoisson foldedCircle pBound
  calc _ ≤ ((circleUnif (t : ℂ) r).withDensity
        fun _ => ENNReal.ofReal (r ^ 2 / (r - r') ^ 2)).map foldH := by
        refine Measure.map_mono (withDensity_mono ?_) measurable_foldH
        filter_upwards [ae_mem_sphere_circleUnif_k3 (t : ℂ) hr] with w hw
        exact ENNReal.ofReal_le_ofReal
          (halfDiscPoisson_density_le hr'r hz (mem_sphere_iff_norm.1 hw))
    _ = _ := by
        rw [withDensity_const, Measure.map_smul]
        all_goals exact measurable_foldH.aemeasurable

theorem halfDiscPoisson_pot_le {t r r' : ℝ} (hr : 0 < r) (hr'r : r' < r) {z : ℂ}
    (hz : ‖z - t‖ ≤ r') (y : ℂ) :
    ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂(halfDiscPoisson t r z) ≤ potC r r' := by
  calc _ ≤ ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂(pBound r r' • foldedCircle (t : ℂ) r) :=
        lintegral_mono' (halfDiscPoisson_le hr hr'r hz) le_rfl
    _ ≤ _ := by
        rw [lintegral_smul_measure, smul_eq_mul]
        exact mul_le_mul' le_rfl (CircleFubini.foldedCircle_pot_le hr _ y)

theorem ballH_mono_k3 {R R' : ℝ} (h : R ≤ R') : ballH R ⊆ ballH R' :=
  fun _ hx => ⟨closedBall_subset_closedBall h hx.1, hx.2⟩

theorem compl_ballH_null_mono {μ : Measure ℂ} {R R' : ℝ} (h : R ≤ R') (hμ : μ (ballH R)ᶜ = 0) :
    μ (ballH R')ᶜ = 0 :=
  measure_mono_null (Set.compl_subset_compl.2 (ballH_mono_k3 h)) hμ

theorem norm_le_of_mem_sphere_k3 {t r : ℝ} {x : ℂ} (hx : x ∈ sphere (t : ℂ) r) :
    ‖x‖ ≤ |t| + r := by
  calc ‖x‖ = ‖(x - t) + (t : ℂ)‖ := by ring_nf
    _ ≤ ‖x - t‖ + ‖(t : ℂ)‖ := norm_add_le _ _
    _ = |t| + r := by rw [mem_sphere_iff_norm.1 hx, Complex.norm_real, Real.norm_eq_abs]; ring

theorem halfDiscPoisson_ballH_compl {t r : ℝ} (hr : 0 < r) (z : ℂ) {R : ℝ} (hR : |t| + r ≤ R) :
    halfDiscPoisson t r z (ballH R)ᶜ = 0 :=
  measure_mono_null (Set.compl_subset_compl.2 fun x hx =>
    ⟨mem_closedBall_zero_iff.2 ((norm_le_of_mem_sphere_k3 hx.1).trans hR), hx.2⟩)
    (halfDiscPoisson_compl_eq_zero hr z)

theorem halfDiscPoisson_ball {t r : ℝ} (hr : 0 < r) (z : ℂ) :
    halfDiscPoisson t r z (ball (t : ℂ) r) = 0 :=
  measure_mono_null (show ball (t : ℂ) r ⊆ (sphere (t : ℂ) r ∩ Hbar)ᶜ from fun x hx hx' => by
    have h1 := mem_sphere_iff_norm.1 hx'.1
    have h2 := mem_ball_iff_norm.1 hx
    linarith) (halfDiscPoisson_compl_eq_zero hr z)

theorem mem_ball_of_le_k3 {t r r' : ℝ} (hr'r : r' < r) {z : ℂ} (hz : ‖z - t‖ ≤ r') :
    z ∈ ball (t : ℂ) r :=
  mem_ball_iff_norm.2 (lt_of_le_of_lt hz hr'r)

theorem isAdmissibleH_halfDiscPoisson {t r r' : ℝ} (hr : 0 < r) (hr'r : r' < r) {z : ℂ}
    (hz : ‖z - t‖ ≤ r') : IsAdmissibleH (halfDiscPoisson t r z) := by
  have := isProbabilityMeasure_halfDiscPoisson hr (mem_ball_of_le_k3 hr'r hz)
  exact CircleFubini.admissible_of_bounds (halfDiscPoisson_ballH_compl hr z le_rfl)
    (potC_ne_top r r') (halfDiscPoisson_pot_le hr hr'r hz)

/-! ## 3. Balayage -/

/-- The balayage of `μ` onto the folded semicircle `∂B(t,r) ∩ Hbar`. -/
def bal (t r : ℝ) (μ : Measure ℂ) : Measure ℂ := μ.bind (halfDiscPoisson t r)

section Bal

variable {t r r' : ℝ} {μ : Measure ℂ}

theorem bal_apply {A : Set ℂ} (hA : MeasurableSet A) :
    bal t r μ A = ∫⁻ z, halfDiscPoisson t r z A ∂μ :=
  Measure.bind_apply hA (measurable_halfDiscPoisson t r).aemeasurable

theorem bal_univ (hr : 0 < r) (hr'r : r' < r) (hμ : μ (closedBall (t : ℂ) r')ᶜ = 0) :
    bal t r μ Set.univ = μ Set.univ := by
  rw [bal_apply MeasurableSet.univ]
  have : ∀ᵐ z ∂μ, halfDiscPoisson t r z Set.univ = 1 := by
    filter_upwards [mem_ae_iff.2 hμ] with z hz
    have := isProbabilityMeasure_halfDiscPoisson hr
      (mem_ball_of_le_k3 hr'r (mem_closedBall_iff_norm.1 hz))
    exact measure_univ
  rw [lintegral_congr_ae this, lintegral_one]

theorem isFiniteMeasure_bal [IsFiniteMeasure μ] (hr : 0 < r) (hr'r : r' < r)
    (hμ : μ (closedBall (t : ℂ) r')ᶜ = 0) : IsFiniteMeasure (bal t r μ) :=
  ⟨by rw [bal_univ hr hr'r hμ]; exact measure_lt_top _ _⟩

theorem bal_null_of_forall {A : Set ℂ} (hA : MeasurableSet A)
    (h : ∀ z, halfDiscPoisson t r z A = 0) : bal t r μ A = 0 := by
  rw [bal_apply hA]; simp [h]

theorem bal_ballH_compl (hr : 0 < r) {R : ℝ} (hR : |t| + r ≤ R) : bal t r μ (ballH R)ᶜ = 0 :=
  bal_null_of_forall (CircleFubini.measurableSet_ballH R).compl
    fun z => halfDiscPoisson_ballH_compl hr z hR

theorem bal_ball (hr : 0 < r) : bal t r μ (ball (t : ℂ) r) = 0 :=
  bal_null_of_forall measurableSet_ball fun z => halfDiscPoisson_ball hr z

theorem bal_pot_le (hr : 0 < r) (hr'r : r' < r) (hμ : μ (closedBall (t : ℂ) r')ᶜ = 0) (y : ℂ) :
    ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂(bal t r μ) ≤ μ Set.univ * potC r r' := by
  rw [bal, Measure.lintegral_bind (measurable_halfDiscPoisson t r).aemeasurable
    (CircleFubini.measurable_logPot y).aemeasurable]
  calc ∫⁻ z, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂halfDiscPoisson t r z ∂μ
      ≤ ∫⁻ _, potC r r' ∂μ := lintegral_mono_ae (by
        filter_upwards [mem_ae_iff.2 hμ] with z hz
        exact halfDiscPoisson_pot_le hr hr'r (mem_closedBall_iff_norm.1 hz) y)
    _ = μ Set.univ * potC r r' := by rw [lintegral_const, mul_comm]

theorem isAdmissibleH_bal [IsFiniteMeasure μ] (hr : 0 < r) (hr'r : r' < r)
    (hμ : μ (closedBall (t : ℂ) r')ᶜ = 0) : IsAdmissibleH (bal t r μ) := by
  have := isFiniteMeasure_bal hr hr'r hμ
  exact CircleFubini.admissible_of_bounds (bal_ballH_compl hr le_rfl)
    (ENNReal.mul_ne_top (measure_ne_top _ _) (potC_ne_top r r')) (bal_pot_le hr hr'r hμ)

theorem integral_bal [IsFiniteMeasure μ] {F : ℂ → ℝ} (hF : Integrable F (bal t r μ)) :
    Integrable (fun w => ∫ x, F x ∂halfDiscPoisson t r w) μ ∧
      ∫ x, F x ∂bal t r μ = ∫ w, ∫ x, F x ∂halfDiscPoisson t r w ∂μ := by
  have hk : halfDiscPoisson t r = ⇑(halfDiscPoissonKernel t r) :=
    funext fun z => (halfDiscPoissonKernel_apply t r z).symm
  unfold bal at hF ⊢
  rw [hk] at hF ⊢
  change Integrable F (halfDiscPoissonKernel t r ∘ₘ μ) at hF
  change Integrable (fun w => ∫ x, F x ∂halfDiscPoissonKernel t r w) μ ∧
    ∫ x, F x ∂(halfDiscPoissonKernel t r ∘ₘ μ) = ∫ w, ∫ x, F x ∂halfDiscPoissonKernel t r w ∂μ
  rw [Measure.comp_eq_comp_const_apply] at hF ⊢
  refine ⟨?_, ?_⟩
  · simpa using hF.integral_comp
  · rw [ProbabilityTheory.Kernel.integral_comp hF]; simp

/-- **Key kernel identity**: balayage does not change the `neumannH`-pairing with a measure
giving no mass to the open disc. -/
theorem kernelCov_bal_left [IsFiniteMeasure μ] (hr : 0 < r) (hr'r : r' < r)
    (hμ : μ (closedBall (t : ℂ) r')ᶜ = 0) {ρ : Measure ℂ} [IsFiniteMeasure ρ] {R : ℝ}
    (hR : |t| + r ≤ R) (hρS : ρ (ballH R)ᶜ = 0) {C : ℝ≥0∞} (hCt : C ≠ ⊤)
    (hρP : ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂ρ ≤ C)
    (hρB : ρ (ball (t : ℂ) r) = 0) :
    kernelCov neumannH (bal t r μ) ρ = kernelCov neumannH μ ρ := by
  have := isFiniteMeasure_bal hr hr'r hμ
  have hint := CircleFubini.integrable_neumannH (bal_ballH_compl (μ := μ) hr hR) hρS hCt hρP
  obtain ⟨-, e⟩ := integral_bal (t := t) (r := r) (μ := μ) (F := fun x => ∫ y, neumannH x y ∂ρ)
    hint.integral_prod_left
  unfold kernelCov
  rw [e]
  refine integral_congr_ae ?_
  filter_upwards [mem_ae_iff.2 hμ] with w hw
  have hwb := mem_ball_of_le_k3 hr'r (mem_closedBall_iff_norm.1 hw)
  have := isProbabilityMeasure_halfDiscPoisson hr hwb
  have hint' := CircleFubini.integrable_neumannH (halfDiscPoisson_ballH_compl hr w hR) hρS hCt hρP
  rw [integral_integral_swap hint']
  refine integral_congr_ae ?_
  have hρae : ∀ᵐ y ∂ρ, y ∉ ball (t : ℂ) r := by
    exact ae_iff.2 (by simpa only [not_not, Set.ofPred_mem_eq] using hρB)
  filter_upwards [hρae] with y hy
  exact integral_neumannH_halfDiscPoisson_of_not_mem_ball hr hwb hy

/-- The half-disc Green kernel pairing, expanded. -/
theorem kernelCov_halfDiscGreen [IsFiniteMeasure μ] (hr : 0 < r) (hr'r : r' < r)
    (hμ : μ (closedBall (t : ℂ) r')ᶜ = 0) {ν : Measure ℂ} [IsFiniteMeasure ν] {R : ℝ}
    (hR : |t| + r ≤ R) (hμS : μ (ballH R)ᶜ = 0) (hνS : ν (ballH R)ᶜ = 0) {C : ℝ≥0∞}
    (hCt : C ≠ ⊤) (hνP : ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂ν ≤ C) :
    kernelCov (halfDiscGreen t r) μ ν =
      kernelCov neumannH μ ν - kernelCov neumannH (bal t r μ) ν := by
  have := isFiniteMeasure_bal hr hr'r hμ
  have hintμ := CircleFubini.integrable_neumannH hμS hνS hCt hνP
  have hintb := CircleFubini.integrable_neumannH (bal_ballH_compl (μ := μ) hr hR) hνS hCt hνP
  obtain ⟨ib, eb⟩ := integral_bal (t := t) (r := r) (μ := μ)
    (F := fun x => ∫ y, neumannH x y ∂ν) hintb.integral_prod_left
  unfold kernelCov
  rw [eb, ← integral_sub hintμ.integral_prod_left ib]
  refine integral_congr_ae ?_
  filter_upwards [mem_ae_iff.2 hμ, hintμ.prod_right_ae] with x hx hxi
  have hxb := mem_ball_of_le_k3 hr'r (mem_closedBall_iff_norm.1 hx)
  have := isProbabilityMeasure_halfDiscPoisson hr hxb
  have hint' := CircleFubini.integrable_neumannH (halfDiscPoisson_ballH_compl hr x hR) hνS hCt hνP
  unfold halfDiscGreen
  rw [integral_sub hxi hint'.integral_prod_right,
    integral_integral_swap (f := fun u y => neumannH u y) hint']

end Bal

/-! ## 4. A Lipschitz retraction onto the closed half-disc -/

theorem radial_coef_lip {ρ a b : ℝ} (hρ : 0 < ρ) (ha : 0 ≤ a) (hb : 0 ≤ b) :
    |min 1 (ρ / a) - min 1 (ρ / b)| * b ≤ |a - b| := by
  rcases eq_or_lt_of_le hb with rfl | hb'
  · simp
  have cb : min 1 (ρ / b) = if b ≤ ρ then 1 else ρ / b := by
    split_ifs with h
    · exact min_eq_left ((one_le_div hb').2 h)
    · exact min_eq_right ((div_le_one hb').2 (not_le.1 h).le)
  rcases eq_or_lt_of_le ha with rfl | ha'
  · rw [div_zero, min_eq_right zero_le_one, cb]
    split_ifs with h
    · simp [abs_of_pos hb']
    · rw [zero_sub, abs_neg, abs_of_pos (div_pos hρ hb'), div_mul_cancel₀ _ hb'.ne', zero_sub,
        abs_neg, abs_of_pos hb']
      exact (not_le.1 h).le
  have ca : min 1 (ρ / a) = if a ≤ ρ then 1 else ρ / a := by
    split_ifs with h
    · exact min_eq_left ((one_le_div ha').2 h)
    · exact min_eq_right ((div_le_one ha').2 (not_le.1 h).le)
  rw [ca, cb]
  split_ifs with h1 h2 h2
  · simp
  · rw [one_sub_div hb'.ne', abs_div, abs_of_pos hb', abs_of_nonneg (by linarith [not_le.1 h2]),
      div_mul_cancel₀ _ hb'.ne', abs_of_nonpos (by linarith [not_le.1 h2])]
    linarith
  · have h1' := not_le.1 h1
    rw [div_sub_one ha'.ne', abs_div, abs_of_pos ha', abs_sub_comm,
      abs_of_nonneg (by linarith : 0 ≤ a - ρ), abs_of_nonneg (by linarith : 0 ≤ a - b),
      div_mul_eq_mul_div, div_le_iff₀ ha']
    nlinarith [mul_le_mul_of_nonneg_left h2 hb, sq_nonneg (a - b)]
  · have h1' := not_le.1 h1
    rw [div_sub_div _ _ ha'.ne' hb'.ne', abs_div, abs_of_pos (mul_pos ha' hb'),
      div_mul_eq_mul_div, div_le_iff₀ (mul_pos ha' hb'),
      show ρ * b - a * ρ = ρ * (b - a) by ring, abs_mul, abs_of_pos hρ, abs_sub_comm b a]
    have := abs_nonneg (a - b)
    nlinarith [mul_nonneg (mul_nonneg (sub_nonneg.2 h1'.le) this) hb]

/-- The retraction of `ℂ` onto `closedBall t r' ∩ Hbar`: fold into `Hbar`, then project
radially onto the disc. -/
def retr (t r' : ℝ) (z : ℂ) : ℂ :=
  (t : ℂ) + ((min 1 (r' / ‖foldH z - t‖) : ℝ) : ℂ) * (foldH z - t)

theorem norm_foldH_sub_foldH_le (z w : ℂ) : ‖foldH z - foldH w‖ ≤ ‖z - w‖ := by
  refine le_of_pow_le_pow_left₀ two_ne_zero (norm_nonneg _) ?_
  rw [sq_norm_eq_k3, sq_norm_eq_k3, CircleFubini.foldH_eq_mk, CircleFubini.foldH_eq_mk]
  simp only [Complex.sub_re, Complex.sub_im, Complex.add_re, Complex.add_im, Complex.mul_re,
    Complex.mul_im, Complex.ofReal_re, Complex.ofReal_im, Complex.I_re, Complex.I_im, mul_zero,
    zero_mul, sub_zero, add_zero, mul_one, zero_add]
  have h2 := pow_le_pow_left₀ (abs_nonneg _) (abs_abs_sub_abs_le_abs_sub z.im w.im) 2
  rw [sq_abs, sq_abs] at h2
  linarith

theorem norm_retr_sub_le {t r' : ℝ} (hr' : 0 < r') (z : ℂ) : ‖retr t r' z - t‖ ≤ r' := by
  have e : retr t r' z - t = ((min 1 (r' / ‖foldH z - t‖) : ℝ) : ℂ) * (foldH z - t) := by
    unfold retr; ring
  rw [e, norm_mul, Complex.norm_real, Real.norm_eq_abs]
  have hc0 : 0 ≤ min 1 (r' / ‖foldH z - t‖) :=
    le_min zero_le_one (div_nonneg hr'.le (norm_nonneg _))
  rw [abs_of_nonneg hc0]
  rcases eq_or_lt_of_le (norm_nonneg (foldH z - t)) with h | h
  · rw [← h, mul_zero]; exact hr'.le
  · calc min 1 (r' / ‖foldH z - t‖) * ‖foldH z - t‖ ≤ r' / ‖foldH z - t‖ * ‖foldH z - t‖ :=
          mul_le_mul_of_nonneg_right (min_le_right _ _) h.le
      _ = r' := div_mul_cancel₀ _ h.ne'

theorem retr_mem_Hbar {t r' : ℝ} (hr' : 0 < r') (z : ℂ) : retr t r' z ∈ Hbar := by
  have hc0 : 0 ≤ min 1 (r' / ‖foldH z - t‖) :=
    le_min zero_le_one (div_nonneg hr'.le (norm_nonneg _))
  have hf : 0 ≤ (foldH z).im := CircleFubini.foldH_mem_Hbar' z
  show 0 ≤ (retr t r' z).im
  unfold retr
  simp only [Complex.add_im, Complex.ofReal_im, Complex.mul_im, Complex.ofReal_re,
    Complex.sub_im, zero_add, zero_mul, add_zero, sub_zero]
  exact mul_nonneg hc0 hf

theorem retr_eq_self {t r' : ℝ} {z : ℂ} (hz : z ∈ Hbar) (hzr : ‖z - t‖ ≤ r') :
    retr t r' z = z := by
  unfold retr
  rw [CircleFubini.foldH_of_mem' hz]
  rcases eq_or_lt_of_le (norm_nonneg (z - t)) with h | h
  · have : z - t = 0 := norm_eq_zero.1 h.symm
    rw [this, mul_zero, add_zero]; exact (sub_eq_zero.1 this).symm
  · rw [min_eq_left ((one_le_div h).2 hzr), Complex.ofReal_one, one_mul]; ring

theorem norm_retr_sub_retr_le {t r' : ℝ} (hr' : 0 < r') (z w : ℂ) :
    ‖retr t r' z - retr t r' w‖ ≤ 2 * ‖z - w‖ := by
  have huv : ‖(foldH z - t) - (foldH w - t)‖ ≤ ‖z - w‖ := by
    rw [sub_sub_sub_cancel_right]; exact norm_foldH_sub_foldH_le z w
  have e : retr t r' z - retr t r' w =
      ((min 1 (r' / ‖foldH z - t‖) : ℝ) : ℂ) * ((foldH z - t) - (foldH w - t)) +
      ((min 1 (r' / ‖foldH z - t‖) - min 1 (r' / ‖foldH w - t‖) : ℝ) : ℂ) * (foldH w - t) := by
    unfold retr; push_cast; ring
  rw [e]
  generalize foldH z - (t : ℂ) = u at huv ⊢
  generalize foldH w - (t : ℂ) = v at huv ⊢
  have hcu0 : 0 ≤ min 1 (r' / ‖u‖) := le_min zero_le_one (div_nonneg hr'.le (norm_nonneg _))
  calc _ ≤ ‖((min 1 (r' / ‖u‖) : ℝ) : ℂ) * (u - v)‖ +
        ‖((min 1 (r' / ‖u‖) - min 1 (r' / ‖v‖) : ℝ) : ℂ) * v‖ := norm_add_le _ _
    _ = min 1 (r' / ‖u‖) * ‖u - v‖ + |min 1 (r' / ‖u‖) - min 1 (r' / ‖v‖)| * ‖v‖ := by
        rw [norm_mul, norm_mul, Complex.norm_real, Complex.norm_real, Real.norm_eq_abs,
          Real.norm_eq_abs, abs_of_nonneg hcu0]
    _ ≤ ‖u - v‖ + |‖u‖ - ‖v‖| :=
        add_le_add (mul_le_of_le_one_left (norm_nonneg _) (min_le_left _ _))
          (radial_coef_lip hr' (norm_nonneg _) (norm_nonneg _))
    _ ≤ ‖u - v‖ + ‖u - v‖ := add_le_add le_rfl (abs_norm_sub_norm_le u v)
    _ ≤ 2 * ‖z - w‖ := by linarith

/-! ## 5. Lipschitz dependence of the half-disc Poisson measure on the point -/

/-- The Lipschitz constant of the Poisson density in the point, on `closedBall t r'`. -/
def lipρ (r r' : ℝ) : ℝ := (2 * r' * (r + r') ^ 2 + 2 * r ^ 2 * (r + r')) / (r - r') ^ 4

theorem lipρ_nonneg {r r' : ℝ} (hr' : 0 ≤ r') (hr'r : r' < r) : 0 ≤ lipρ r r' := by
  have hr : 0 < r := lt_of_le_of_lt hr' hr'r
  unfold lipρ
  refine div_nonneg (add_nonneg ?_ ?_) (by positivity)
  · exact mul_nonneg (mul_nonneg zero_le_two hr') (sq_nonneg _)
  · exact mul_nonneg (mul_nonneg zero_le_two (sq_nonneg _)) (by linarith)

theorem real_density_lip {r r' α β p q δ : ℝ} (hr' : 0 ≤ r') (hr'r : r' < r) (hα0 : 0 ≤ α)
    (hβ0 : 0 ≤ β) (hα : α ≤ r') (hβ : β ≤ r') (hp1 : r - r' ≤ p) (hq1 : r - r' ≤ q)
    (hq2 : q ≤ r + r') (hp2 : p ≤ r + r') (hαβ : |α - β| ≤ δ) (hpq : |q - p| ≤ δ) :
    |(r ^ 2 - α ^ 2) / p ^ 2 - (r ^ 2 - β ^ 2) / q ^ 2| ≤ lipρ r r' * δ := by
  have hd : 0 < r - r' := by linarith
  have hp : 0 < p := lt_of_lt_of_le hd hp1
  have hq : 0 < q := lt_of_lt_of_le hd hq1
  have hδ0 : 0 ≤ δ := le_trans (abs_nonneg _) hαβ
  have hpq0 : 0 < p ^ 2 * q ^ 2 := mul_pos (pow_pos hp 2) (pow_pos hq 2)
  rw [div_sub_div _ _ (pow_pos hp 2).ne' (pow_pos hq 2).ne', abs_div,
    abs_of_pos hpq0, div_le_iff₀ hpq0]
  have t1 : |β - α| * (β + α) * q ^ 2 ≤ δ * (2 * r') * (r + r') ^ 2 := by
    have h1 : |β - α| * (β + α) ≤ δ * (2 * r') :=
      mul_le_mul (by rwa [abs_sub_comm]) (by linarith) (by linarith) hδ0
    exact mul_le_mul h1 (pow_le_pow_left₀ hq.le hq2 2) (sq_nonneg _)
      (mul_nonneg hδ0 (by linarith))
  have t2 : (r ^ 2 - β ^ 2) * (|q - p| * (q + p)) ≤ r ^ 2 * (δ * (2 * (r + r'))) :=
    mul_le_mul (by nlinarith) (mul_le_mul hpq (by linarith) (by linarith) hδ0)
      (mul_nonneg (abs_nonneg _) (by linarith)) (sq_nonneg r)
  have key : |(r ^ 2 - α ^ 2) * q ^ 2 - p ^ 2 * (r ^ 2 - β ^ 2)| ≤
      δ * (2 * r' * (r + r') ^ 2 + 2 * r ^ 2 * (r + r')) := by
    calc |(r ^ 2 - α ^ 2) * q ^ 2 - p ^ 2 * (r ^ 2 - β ^ 2)|
        = |(β - α) * (β + α) * q ^ 2 + (r ^ 2 - β ^ 2) * ((q - p) * (q + p))| := by
          congr 1; ring
      _ ≤ |(β - α) * (β + α) * q ^ 2| + |(r ^ 2 - β ^ 2) * ((q - p) * (q + p))| :=
          abs_add_le _ _
      _ = |β - α| * (β + α) * q ^ 2 + (r ^ 2 - β ^ 2) * (|q - p| * (q + p)) := by
          rw [abs_mul, abs_mul, abs_mul, abs_mul, abs_of_nonneg (by linarith : 0 ≤ β + α),
            abs_of_nonneg (sq_nonneg q), abs_of_nonneg (by nlinarith : 0 ≤ r ^ 2 - β ^ 2),
            abs_of_nonneg (by linarith : 0 ≤ q + p)]
      _ ≤ _ := by linarith
  have hL : lipρ r r' * (r - r') ^ 4 = 2 * r' * (r + r') ^ 2 + 2 * r ^ 2 * (r + r') :=
    div_mul_cancel₀ _ (pow_pos hd 4).ne'
  have h4 : (r - r') ^ 4 ≤ p ^ 2 * q ^ 2 := by
    calc (r - r') ^ 4 = (r - r') ^ 2 * (r - r') ^ 2 := by ring
      _ ≤ p ^ 2 * q ^ 2 := mul_le_mul (pow_le_pow_left₀ hd.le hp1 2)
          (pow_le_pow_left₀ hd.le hq1 2) (by positivity) (by positivity)
  calc _ ≤ δ * (2 * r' * (r + r') ^ 2 + 2 * r ^ 2 * (r + r')) := key
    _ = lipρ r r' * δ * (r - r') ^ 4 := by rw [← hL]; ring
    _ ≤ lipρ r r' * δ * (p ^ 2 * q ^ 2) :=
        mul_le_mul_of_nonneg_left h4 (mul_nonneg (lipρ_nonneg hr' hr'r) hδ0)

theorem abs_density_sub_le {t r r' : ℝ} (hr' : 0 ≤ r') (hr'r : r' < r) {a b w : ℂ}
    (ha : ‖a - t‖ ≤ r') (hb : ‖b - t‖ ≤ r') (hw : ‖w - t‖ = r) :
    |(r ^ 2 - ‖a - t‖ ^ 2) / ‖w - a‖ ^ 2 - (r ^ 2 - ‖b - t‖ ^ 2) / ‖w - b‖ ^ 2| ≤
      lipρ r r' * ‖a - b‖ := by
  have lo : ∀ c : ℂ, ‖c - t‖ ≤ r' → r - r' ≤ ‖w - c‖ := fun c hc => by
    have := norm_sub_norm_le (w - t) (c - t)
    rw [sub_sub_sub_cancel_right] at this; linarith
  have hi : ∀ c : ℂ, ‖c - t‖ ≤ r' → ‖w - c‖ ≤ r + r' := fun c hc => by
    have := norm_sub_le (w - t) (c - t)
    rw [sub_sub_sub_cancel_right] at this; linarith
  refine real_density_lip hr' hr'r (norm_nonneg _) (norm_nonneg _) ha hb (lo a ha) (lo b hb)
    (hi b hb) (hi a ha) ?_ ?_
  · have := abs_norm_sub_norm_le (a - t) (b - t)
    rwa [sub_sub_sub_cancel_right] at this
  · have := abs_norm_sub_norm_le (w - b) (w - a)
    rwa [sub_sub_sub_cancel_left] at this

/-- Circle form of the half-disc Poisson integral. -/
theorem integral_halfDiscPoisson_eq_circle' {t r : ℝ} {z : ℂ} (hz : z ∈ ball (t : ℂ) r)
    {f : ℂ → ℝ} (hf : AEStronglyMeasurable f (halfDiscPoisson t r z)) :
    ∫ x, f x ∂(halfDiscPoisson t r z) =
      ∫ w, (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 * f (foldH w) ∂(circleUnif (t : ℂ) r) := by
  have hpos : 0 ≤ r ^ 2 - ‖z - t‖ ^ 2 := by
    have := mem_ball_iff_norm.1 hz; nlinarith [norm_nonneg (z - t)]
  rw [integral_halfDiscPoisson_eq_circle t r z hf]
  refine integral_congr_ae (ae_of_all _ fun w => ?_)
  simp only [smul_eq_mul]
  rw [ENNReal.toReal_ofReal (div_nonneg hpos (sq_nonneg _))]

theorem integral_abs_inner_le {μ μ' : Measure ℂ} [IsFiniteMeasure μ] [IsFiniteMeasure μ']
    {R : ℝ} (hμ : μ (ballH R)ᶜ = 0) (hμ' : μ' (ballH R)ᶜ = 0) {C : ℝ≥0∞} (hCt : C ≠ ⊤)
    (hC : ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂μ' ≤ C) :
    ∫ x, |∫ y, neumannH x y ∂μ'| ∂μ ≤ (nBound μ μ' R C).toReal := by
  have hint := CircleFubini.integrable_neumannH hμ hμ' hCt hC
  calc ∫ x, |∫ y, neumannH x y ∂μ'| ∂μ ≤ ∫ x, ∫ y, ‖neumannH x y‖ ∂μ' ∂μ := by
        refine integral_mono hint.integral_prod_left.abs hint.norm.integral_prod_left
          fun x => ?_
        simpa only [Real.norm_eq_abs] using norm_integral_le_integral_norm (μ := μ')
          (fun y => neumannH x y)
    _ = ∫ p, ‖neumannH p.1 p.2‖ ∂(μ.prod μ') := (integral_prod _ hint.norm).symm
    _ ≤ (nBound μ μ' R C).toReal := by
        rw [integral_norm_eq_lintegral_enorm hint.1]
        simp_rw [← ofReal_norm]
        exact ENNReal.toReal_mono (CircleFubini.nBound_ne_top R hCt)
          (CircleFubini.lintegral_norm_neumannH_le hμ hμ' hC)

/-- The uniform bound on `∫ |∫ neumannH|` for the folded circle against half-disc Poisson
measures. -/
def Bv (t r r' : ℝ) : ℝ :=
  (ENNReal.ofReal (2 * Real.log (max (2 * (|t| + r)) 1)) + 2 * potC r r').toReal

theorem abs_kernelCov_halfDiscPoisson_sub_le {t r r' : ℝ} (hr : 0 < r) (hr' : 0 ≤ r')
    (hr'r : r' < r) {a b c : ℂ} (ha : ‖a - t‖ ≤ r') (hb : ‖b - t‖ ≤ r') (hc : ‖c - t‖ ≤ r') :
    |kernelCov neumannH (halfDiscPoisson t r a) (halfDiscPoisson t r c) -
      kernelCov neumannH (halfDiscPoisson t r b) (halfDiscPoisson t r c)| ≤
      lipρ r r' * ‖a - b‖ * Bv t r r' := by
  have := isProbabilityMeasure_halfDiscPoisson hr (mem_ball_of_le_k3 hr'r hc)
  have hgm : Measurable fun x => ∫ y, neumannH x y ∂(halfDiscPoisson t r c) :=
    (measurable_neumannH.stronglyMeasurable.integral_prod_right'
      (ν := halfDiscPoisson t r c)).measurable
  set g : ℂ → ℝ := fun x => ∫ y, neumannH x y ∂(halfDiscPoisson t r c) with hg_def
  have hfS : foldedCircle (t : ℂ) r (ballH (|t| + r))ᶜ = 0 :=
    CircleFubini.foldedCircle_support hr.le (by rw [Complex.norm_real, Real.norm_eq_abs])
  have hcS : halfDiscPoisson t r c (ballH (|t| + r))ᶜ = 0 :=
    halfDiscPoisson_ballH_compl hr c le_rfl
  have hgI : Integrable g (foldedCircle (t : ℂ) r) :=
    (CircleFubini.integrable_neumannH hfS hcS (potC_ne_top r r')
      (halfDiscPoisson_pot_le hr hr'r hc)).integral_prod_left
  have hgI' : Integrable (fun w => g (foldH w)) (circleUnif (t : ℂ) r) :=
    (integrable_map_measure hgm.aestronglyMeasurable measurable_foldH.aemeasurable).1 hgI
  have hρm : ∀ z : ℂ, Measurable fun w : ℂ => (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 := fun z =>
    measurable_const.div ((measurable_id.sub measurable_const).norm.pow_const 2)
  have hsph := ae_mem_sphere_circleUnif_k3 (t : ℂ) hr
  have hint : ∀ z : ℂ, ‖z - t‖ ≤ r' →
      Integrable (fun w => (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 * g (foldH w))
        (circleUnif (t : ℂ) r) := fun z hz =>
    hgI'.bdd_mul (c := r ^ 2 / (r - r') ^ 2) (hρm z).aestronglyMeasurable (by
      filter_upwards [hsph] with w hw
      have hw' := mem_sphere_iff_norm.1 hw
      have hnn : 0 ≤ (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 :=
        div_nonneg (by nlinarith [norm_nonneg (z - t)]) (sq_nonneg _)
      rw [Real.norm_eq_abs, abs_of_nonneg hnn]
      exact halfDiscPoisson_density_le hr'r hz hw')
  have hK : ∀ z : ℂ, ‖z - t‖ ≤ r' →
      kernelCov neumannH (halfDiscPoisson t r z) (halfDiscPoisson t r c) =
      ∫ w, (r ^ 2 - ‖z - t‖ ^ 2) / ‖w - z‖ ^ 2 * g (foldH w) ∂(circleUnif (t : ℂ) r) :=
    fun z hz => integral_halfDiscPoisson_eq_circle' (mem_ball_of_le_k3 hr'r hz)
      hgm.aestronglyMeasurable
  rw [hK a ha, hK b hb, ← integral_sub (hint a ha) (hint b hb)]
  have hbound : ∀ᵐ w ∂circleUnif (t : ℂ) r,
      ‖(r ^ 2 - ‖a - t‖ ^ 2) / ‖w - a‖ ^ 2 * g (foldH w) -
        (r ^ 2 - ‖b - t‖ ^ 2) / ‖w - b‖ ^ 2 * g (foldH w)‖ ≤
        lipρ r r' * ‖a - b‖ * |g (foldH w)| := by
    filter_upwards [hsph] with w hw
    rw [← sub_mul, Real.norm_eq_abs, abs_mul]
    exact mul_le_mul_of_nonneg_right
      (abs_density_sub_le hr' hr'r ha hb (mem_sphere_iff_norm.1 hw)) (abs_nonneg _)
  have h1 := norm_integral_le_of_norm_le (hgI'.abs.const_mul (lipρ r r' * ‖a - b‖)) hbound
  rw [Real.norm_eq_abs] at h1
  refine h1.trans ?_
  rw [integral_const_mul]
  refine mul_le_mul_of_nonneg_left ?_
    (mul_nonneg (lipρ_nonneg hr' hr'r) (norm_nonneg _))
  have e2 : ∫ w, |g (foldH w)| ∂circleUnif (t : ℂ) r = ∫ x, |g x| ∂foldedCircle (t : ℂ) r := by
    unfold foldedCircle
    exact (integral_map measurable_foldH.aemeasurable
      (show AEStronglyMeasurable (fun x => |g x|) _ from
        (continuous_abs.measurable.comp hgm).aestronglyMeasurable)).symm
  rw [e2]
  refine (integral_abs_inner_le hfS hcS (potC_ne_top r r')
    (halfDiscPoisson_pot_le hr hr'r hc)).trans (le_of_eq ?_)
  simp only [nBound, measure_univ, one_mul, mul_one, Bv]

theorem kernelCov2_halfDiscPoisson_le {t r r' : ℝ} (hr : 0 < r) (hr' : 0 ≤ r')
    (hr'r : r' < r) {a b : ℂ} (ha : ‖a - t‖ ≤ r') (hb : ‖b - t‖ ≤ r') :
    kernelCov2 neumannH (halfDiscPoisson t r a, halfDiscPoisson t r b)
      (halfDiscPoisson t r a, halfDiscPoisson t r b) ≤
      2 * (lipρ r r' * Bv t r r') * ‖a - b‖ := by
  have h1 := abs_le.1 (abs_kernelCov_halfDiscPoisson_sub_le hr hr' hr'r ha hb ha)
  have h2 := abs_le.1 (abs_kernelCov_halfDiscPoisson_sub_le hr hr' hr'r ha hb hb)
  simp only [kernelCov2]
  nlinarith [h1.2, h2.1]

/-! ## 6. Kolmogorov continuity, with measurability for a sub-σ-algebra -/

section Kolmogorov

variable {Ω : Type*}

/-- The good event of the dyadic chaining. -/
def kGood (Z : ℂ → Ω → ℝ) (ω : Ω) : Prop :=
  ∀ R : ℕ, ∃ N, ∀ j ≥ N, CircleCont.GoodLevel (fun z => Z z ω) R j

open Classical in
/-- The explicit Kolmogorov modification (as in `CircleCont.exists_continuous_modification`). -/
def kolY (Z : ℂ → Ω → ℝ) (z : ℂ) (ω : Ω) : ℝ :=
  if kGood Z ω then limUnder atTop (fun n => Z (dyadicRoundC n z) ω) else 0

theorem measurableSet_kGood [MeasurableSpace Ω] {Z : ℂ → Ω → ℝ} (hZ : ∀ z, Measurable (Z z)) :
    MeasurableSet {ω | kGood Z ω} := by
  unfold kGood CircleCont.GoodLevel
  refine measurableSet_setOfPred.2 ?_
  refine Measurable.forall fun R => Measurable.exists fun N => Measurable.forall fun j =>
    Measurable.imp measurable_const <| Measurable.forall fun a => Measurable.forall fun b =>
      Measurable.imp measurable_const <| Measurable.and ?_ ?_
  · exact measurableSet_setOfPred.1 (measurableSet_le (continuous_abs.measurable.comp ((hZ _).sub (hZ _)))
    measurable_const)
  · exact measurableSet_setOfPred.1 (measurableSet_le (continuous_abs.measurable.comp ((hZ _).sub (hZ _)))
    measurable_const)

theorem measurable_kolY [MeasurableSpace Ω] {Z : ℂ → Ω → ℝ} (hZ : ∀ z, Measurable (Z z))
    {z : ℂ} (hz : z ∈ Hbar) : Measurable (kolY Z z) := by
  obtain ⟨R, hR⟩ := CircleCont.exists_boxR hz
  refine measurable_of_tendsto_metrizable
    (f := fun n ω => {ω | kGood Z ω}.indicator (Z (dyadicRoundC n z)) ω)
    (fun n => (hZ _).indicator (measurableSet_kGood hZ)) ?_
  rw [tendsto_pi_nhds]; intro ω
  by_cases hG : kGood Z ω
  · simp only [Set.indicator_of_mem (show ω ∈ {ω | kGood Z ω} from hG)]
    rw [kolY, if_pos hG]
    obtain ⟨N, hN⟩ := hG R
    exact CircleCont.tendsto_of_good (f := fun z => Z z ω) hR hN
  · simp only [Set.indicator_of_notMem (show ω ∉ {ω | kGood Z ω} from hG)]
    rw [kolY, if_neg hG]
    exact tendsto_const_nhds

theorem kolY_spec [MeasurableSpace Ω] {P : Measure Ω} {Z : ℂ → Ω → ℝ}
    (hZ : ∀ z, AEMeasurable (Z z) P) {K : ℝ} (hK : 0 ≤ K) (hmom : CircleCont.MomentBound Z P K) :
    (∀ ω, ContinuousOn (fun z => kolY Z z ω) Hbar) ∧ (∀ z ∈ Hbar, kolY Z z =ᵐ[P] Z z) := by
  refine ⟨fun ω => ?_, fun z hz => ?_⟩
  · by_cases h : kGood Z ω
    · simp only [kolY, if_pos h]; exact CircleCont.continuousOn_of_good h
    · simp only [kolY, if_neg h]; exact continuousOn_const
  · filter_upwards [CircleCont.ae_good hZ hK hmom, CircleCont.ae_tendsto_at hZ hK hmom hz]
      with ω hG ht
    rw [kolY, if_pos (show kGood Z ω from hG)]
    exact ht.limUnder_eq

end Kolmogorov

/-! ## 7. Stochastic Fubini for a measurable family of measures -/

theorem integral_bind_kernel_k3 {c : ℂ → Measure ℂ} (hc : Measurable c) (ν : Measure ℂ)
    {F : ℂ → ℝ} (hF : Integrable F (ν.bind c)) :
    Integrable (fun w => ∫ x, F x ∂c w) ν ∧ ∫ x, F x ∂(ν.bind c) = ∫ w, ∫ x, F x ∂c w ∂ν := by
  change Integrable F ((⟨c, hc⟩ : Kernel ℂ ℂ) ∘ₘ ν) at hF
  change Integrable (fun w => ∫ x, F x ∂(⟨c, hc⟩ : Kernel ℂ ℂ) w) ν ∧
    ∫ x, F x ∂((⟨c, hc⟩ : Kernel ℂ ℂ) ∘ₘ ν) = ∫ w, ∫ x, F x ∂(⟨c, hc⟩ : Kernel ℂ ℂ) w ∂ν
  rw [Measure.comp_eq_comp_const_apply] at hF ⊢
  refine ⟨?_, ?_⟩
  · simpa using hF.integral_comp
  · rw [ProbabilityTheory.Kernel.integral_comp hF]; simp

section Fubini

variable {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
  {X : Ω → FieldSample}

/-- **Stochastic Fubini** for a measurable family `c` of probability measures with uniform
admissibility bounds on a compact `K ⊆ Hbar`: for a version `Y` (continuous on `Hbar`) of
`z ↦ X (c z) - X (c z₀)`, `∫ Y z dν = X (ν.bind c) - X (ν(ℂ) • c z₀)` a.s. (Adapted from
`integral_circleAvg_ae_eq_bind`.) -/
theorem stochFubini_kernel (hX : IsFreeGFFModConstH X P) {c : ℂ → Measure ℂ}
    (hc : Measurable c) {K : Set ℂ} (hK : IsCompact K) (hKH : K ⊆ Hbar) {z₀ : ℂ} (hz₀ : z₀ ∈ K)
    {R : ℝ} {C : ℝ≥0∞} (hCt : C ≠ ⊤) (hcU : ∀ z ∈ K, c z Set.univ = 1)
    (hcS : ∀ z ∈ K, c z (ballH R)ᶜ = 0)
    (hcP : ∀ z ∈ K, ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂c z ≤ C)
    {Y W : ℂ → Ω → ℝ} (hYc : ∀ ω, ContinuousOn (fun z => Y z ω) Hbar)
    (hWm : ∀ z, Measurable (W z)) (hY : ∀ z ∈ Hbar, (fun ω => Y z ω) =ᵐ[P] W z)
    (hWK : ∀ z ∈ K, W z = fun ω => X ω (c z) - X ω (c z₀))
    (ν : Measure ℂ) [IsFiniteMeasure ν] (hνK : ν Kᶜ = 0) :
    (fun ω => ∫ z, Y z ω ∂ν) =ᵐ[P] fun ω => X ω (ν.bind c) - X ω (ν Set.univ • c z₀) := by
  have hfin : ∀ z ∈ K, IsFiniteMeasure (c z) := fun z hz =>
    ⟨by rw [hcU z hz]; exact ENNReal.one_lt_top⟩
  have hae : ∀ᵐ z ∂ν, z ∈ K := mem_ae_iff.mpr hνK
  set νk := ν.bind c with hνk_def
  set μ₀ := ν Set.univ • c z₀ with hμ₀_def
  have := hfin z₀ hz₀
  have hbind_apply : ∀ A, MeasurableSet A → νk A = ∫⁻ w, c w A ∂ν := fun A hA =>
    Measure.bind_apply hA hc.aemeasurable
  have hkU : νk Set.univ = ν Set.univ := by
    rw [hbind_apply _ MeasurableSet.univ,
      lintegral_congr_ae (hae.mono fun z hz => hcU z hz), lintegral_one]
  have : IsFiniteMeasure νk := ⟨by rw [hkU]; exact measure_lt_top _ _⟩
  have : IsFiniteMeasure μ₀ := CircleFubini.isFiniteMeasure_smul' _ (measure_ne_top _ _) _
  have hmCt : ν Set.univ * C ≠ ⊤ := ENNReal.mul_ne_top (measure_ne_top _ _) hCt
  have hkS : νk (ballH R)ᶜ = 0 := by
    rw [hbind_apply _ (CircleFubini.measurableSet_ballH R).compl,
      lintegral_congr_ae (hae.mono fun z hz => hcS z hz), lintegral_zero]
  have hkP : ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂νk ≤ ν Set.univ * C := by
    intro y
    rw [hνk_def, Measure.lintegral_bind hc.aemeasurable
      (CircleFubini.measurable_logPot y).aemeasurable]
    calc ∫⁻ w, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂c w ∂ν ≤ ∫⁻ _, C ∂ν :=
          lintegral_mono_ae (hae.mono fun z hz => hcP z hz y)
      _ = ν Set.univ * C := by rw [lintegral_const, mul_comm]
  have hkA : IsAdmissibleH νk := CircleFubini.admissible_of_bounds hkS hmCt hkP
  have hcA : ∀ z ∈ K, IsAdmissibleH (c z) := fun z hz => by
    have := hfin z hz
    exact CircleFubini.admissible_of_bounds (hcS z hz) hCt (hcP z hz)
  have h0S : μ₀ (ballH R)ᶜ = 0 := by
    rw [hμ₀_def, Measure.smul_apply, hcS z₀ hz₀, smul_zero]
  have h0P : ∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂μ₀ ≤ ν Set.univ * C :=
    CircleFubini.smul_pot (hcP z₀ hz₀)
  have h0A : IsAdmissibleH μ₀ := CircleFubini.admissible_of_bounds h0S hmCt h0P
  have h0U : μ₀ Set.univ = ν Set.univ := by
    rw [hμ₀_def, Measure.smul_apply, hcU z₀ hz₀, smul_eq_mul, mul_one]
  set D : Ω → ℝ := fun ω => X ω νk - X ω μ₀ with hD_def
  have hDm : Measurable D := (hX.measurable_coord _).sub (hX.measurable_coord _)
  have h11 : ∀ z ∈ K, (c z) Set.univ = (c z₀) Set.univ := fun z hz => by
    rw [hcU z hz, hcU z₀ hz₀]
  have hqU : νk Set.univ = μ₀ Set.univ := by rw [hkU, h0U]
  have hWL2 : ∀ z ∈ K, MemLp (W z) 2 P := fun z hz => by
    rw [hWK z hz]
    exact CircleFubini.gff_memLp (p := (c z, c z₀)) hX (hcA z hz) (hcA z₀ hz₀) (h11 z hz)
  have hDL2 : MemLp D 2 P := CircleFubini.gff_memLp (p := (νk, μ₀)) hX hkA h0A hqU
  have hEWW : ∀ z ∈ K, ∀ z' ∈ K, ∫ ω, W z ω * W z' ω ∂P
      = kernelCov2 neumannH (c z, c z₀) (c z', c z₀) := fun z hz z' hz' => by
    rw [hWK z hz, hWK z' hz']
    exact CircleFubini.gff_integral_mul (p := (c z, c z₀)) (q := (c z', c z₀)) hX (hcA z hz)
      (hcA z₀ hz₀) (h11 z hz) (hcA z' hz') (hcA z₀ hz₀) (h11 z' hz')
  have hEWD : ∀ z ∈ K, ∫ ω, W z ω * D ω ∂P = kernelCov2 neumannH (c z, c z₀) (νk, μ₀) :=
    fun z hz => by
      rw [hWK z hz]
      exact CircleFubini.gff_integral_mul (p := (c z, c z₀)) (q := (νk, μ₀)) hX (hcA z hz)
        (hcA z₀ hz₀) (h11 z hz) hkA h0A hqU
  have hEDW : ∀ z ∈ K, ∫ ω, D ω * W z ω ∂P = kernelCov2 neumannH (νk, μ₀) (c z, c z₀) :=
    fun z hz => by
      rw [hWK z hz]
      exact CircleFubini.gff_integral_mul (p := (νk, μ₀)) (q := (c z, c z₀)) hX hkA h0A hqU
        (hcA z hz) (hcA z₀ hz₀) (h11 z hz)
  have hEDD : ∫ ω, D ω * D ω ∂P = kernelCov2 neumannH (νk, μ₀) (νk, μ₀) :=
    CircleFubini.gff_integral_mul (p := (νk, μ₀)) (q := (νk, μ₀)) hX hkA h0A hqU hkA h0A hqU
  obtain ⟨Z, hZm, hZc, hZY, hZW⟩ := CircleFubini.exists_measurable_version hYc hWm hY
  have hZL2 : ∀ z ∈ K, MemLp (Z z) 2 P := fun z hz =>
    (hWL2 z hz).ae_eq (hZW z (hKH hz)).symm
  set b := (nBound (c z₀) (c z₀) R C).toReal with hb_def
  have hkc : ∀ z ∈ K, ∀ z' ∈ K, |kernelCov neumannH (c z) (c z')| ≤ b := by
    intro z hz z' hz'
    have := hfin z hz
    have := hfin z' hz'
    have h := CircleFubini.abs_kernelCov_le (hcS z hz) (hcS z' hz') hCt (hcP z' hz')
    have he : nBound (c z) (c z') R C = nBound (c z₀) (c z₀) R C := by
      simp only [nBound, hcU z hz, hcU z' hz', hcU z₀ hz₀]
    rwa [he] at h
  have hB : ∀ z ∈ K, ∫ ω, Z z ω ^ 2 ∂P ≤ 4 * b := by
    intro z hz
    have e1 : ∫ ω, Z z ω ^ 2 ∂P = ∫ ω, W z ω * W z ω ∂P := by
      refine integral_congr_ae ?_
      filter_upwards [hZW z (hKH hz)] with ω hω
      rw [hω, sq]
    rw [e1, hEWW z hz z hz]
    simp only [kernelCov2]
    have a1 := abs_le.1 (hkc z hz z hz)
    have a2 := abs_le.1 (hkc z hz z₀ hz₀)
    have a3 := abs_le.1 (hkc z₀ hz₀ z hz)
    have a4 := abs_le.1 (hkc z₀ hz₀ z₀ hz₀)
    linarith [a1.1, a1.2, a2.1, a2.2, a3.1, a3.2, a4.1, a4.2]
  have hmom : ∀ z ∈ K, Integrable (fun ω => Z z ω ^ 2) P := fun z hz =>
    (hZL2 z hz).integrable_sq
  have hsmul : ∀ μ' : Measure ℂ, kernelCov neumannH μ₀ μ'
      = (ν Set.univ).toReal * kernelCov neumannH (c z₀) μ' := by
    intro μ'; simp only [kernelCov, hμ₀_def, integral_smul_measure, smul_eq_mul]
  have hbindK : ∀ (μ' : Measure ℂ) [IsFiniteMeasure μ'], μ' (ballH R)ᶜ = 0 →
      ∀ {C' : ℝ≥0∞}, C' ≠ ⊤ →
      (∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂μ' ≤ C') →
      Integrable (fun w => kernelCov neumannH (c w) μ') ν ∧
        ∫ w, kernelCov neumannH (c w) μ' ∂ν = kernelCov neumannH νk μ' := by
    intro μ' _ hμ' C' hC' hCμ'
    have hint := CircleFubini.integrable_neumannH hkS hμ' hC' hCμ'
    obtain ⟨h1, h2⟩ := integral_bind_kernel_k3 hc ν hint.integral_prod_left
    exact ⟨h1, h2.symm⟩
  have hlin2 : ∀ (a b' : Measure ℂ) [IsFiniteMeasure a] [IsFiniteMeasure b'],
      a (ballH R)ᶜ = 0 → b' (ballH R)ᶜ = 0 → ∀ {C C' : ℝ≥0∞}, C ≠ ⊤ → C' ≠ ⊤ →
      (∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂a ≤ C) →
      (∀ y, ∫⁻ x, ENNReal.ofReal (-Real.log ‖x - y‖) ∂b' ≤ C') →
      ∫ w, kernelCov2 neumannH (c w, c z₀) (a, b') ∂ν
        = kernelCov2 neumannH (νk, μ₀) (a, b') := by
    intro a b' _ _ ha hb' C C' hC hC' hCa hCb
    obtain ⟨ia, ea⟩ := hbindK a ha hC hCa
    obtain ⟨ib, eb⟩ := hbindK b' hb' hC' hCb
    simp only [kernelCov2]
    rw [integral_add (f := fun w => kernelCov neumannH (c w) a
          - kernelCov neumannH (c w) b' - kernelCov neumannH (c z₀) a)
        (g := fun _ => kernelCov neumannH (c z₀) b')
        ((ia.sub ib).sub (integrable_const _)) (integrable_const _),
      integral_sub (f := fun w => kernelCov neumannH (c w) a
          - kernelCov neumannH (c w) b')
        (g := fun _ => kernelCov neumannH (c z₀) a) (ia.sub ib) (integrable_const _),
      integral_sub ia ib, ea, eb,
      integral_const, integral_const, smul_eq_mul, smul_eq_mul, measureReal_def, hsmul, hsmul]
  obtain ⟨hLm, hLL2⟩ := CircleFubini.memLp_integral (B := 4 * b) hZm hνK hK hZc hmom hB
  set L : Ω → ℝ := fun ω => ∫ z, Z z ω ∂ν with hL_def
  have hZmz : ∀ z, Measurable (Z z) := fun z => hZm.of_uncurry_left
  have hZD : ∀ z ∈ K, ∫ ω, Z z ω * D ω ∂P
      = kernelCov2 neumannH (c z, c z₀) (νk, μ₀) := by
    intro z hz
    rw [← hEWD z hz]
    refine integral_congr_ae ?_
    filter_upwards [hZW z (hKH hz)] with ω hω
    rw [hω]
  have E1 : ∫ ω, L ω * D ω ∂P = kernelCov2 neumannH (νk, μ₀) (νk, μ₀) := by
    rw [CircleFubini.fubini_mul hZm hνK hmom hB hDm hDL2]
    calc ∫ z, ∫ ω, Z z ω * D ω ∂P ∂ν
        = ∫ z, kernelCov2 neumannH (c z, c z₀) (νk, μ₀) ∂ν :=
          integral_congr_ae (hae.mono fun z hz => hZD z hz)
      _ = _ := hlin2 νk μ₀ hkS h0S hmCt hmCt hkP h0P
  have E2 : ∫ ω, L ω * L ω ∂P = ∫ ω, L ω * D ω ∂P := by
    rw [CircleFubini.fubini_mul hZm hνK hmom hB hLm hLL2,
      CircleFubini.fubini_mul hZm hνK hmom hB hDm hDL2]
    refine integral_congr_ae (hae.mono fun z hz => ?_)
    show ∫ ω, Z z ω * L ω ∂P = ∫ ω, Z z ω * D ω ∂P
    have i1 : ∫ ω, Z z ω * L ω ∂P = ∫ ω, L ω * Z z ω ∂P := by simp_rw [mul_comm]
    have := hfin z hz
    rw [i1, CircleFubini.fubini_mul hZm hνK hmom hB (hZmz z) (hZL2 z hz)]
    calc ∫ z', ∫ ω, Z z' ω * Z z ω ∂P ∂ν
        = ∫ z', kernelCov2 neumannH (c z', c z₀) (c z, c z₀) ∂ν := by
          refine integral_congr_ae (hae.mono fun z' hz' => ?_)
          show ∫ ω, Z z' ω * Z z ω ∂P = _
          beta_reduce
          rw [← hEWW z' hz' z hz]
          refine integral_congr_ae ?_
          filter_upwards [hZW z (hKH hz), hZW z' (hKH hz')] with ω hω hω'
          rw [hω, hω']
      _ = kernelCov2 neumannH (νk, μ₀) (c z, c z₀) :=
          hlin2 _ _ (hcS z hz) (hcS z₀ hz₀) hCt hCt (hcP z hz) (hcP z₀ hz₀)
      _ = ∫ ω, Z z ω * D ω ∂P := by
          rw [← hEDW z hz]
          refine integral_congr_ae ?_
          filter_upwards [hZW z (hKH hz)] with ω hω
          rw [hω, mul_comm]
  have hsq : ∫ ω, (L ω - D ω) ^ 2 ∂P = 0 := by
    have : ∀ ω, (L ω - D ω) ^ 2 = (L ω * L ω - 2 * (L ω * D ω)) + D ω * D ω := fun ω => by
      ring
    simp_rw [this]
    have iLL := CircleFubini.integrable_mul_of_memLp_two hLL2 hLL2
    have iLD := CircleFubini.integrable_mul_of_memLp_two hLL2 hDL2
    have iDD := CircleFubini.integrable_mul_of_memLp_two hDL2 hDL2
    rw [integral_add (f := fun ω => L ω * L ω - 2 * (L ω * D ω)) (g := fun ω => D ω * D ω)
        (iLL.sub (iLD.const_mul 2)) iDD,
      integral_sub (f := fun ω => L ω * L ω) (g := fun ω => 2 * (L ω * D ω)) iLL
        (iLD.const_mul 2),
      integral_const_mul, E2, E1, hEDD]
    ring
  have hint : Integrable (fun ω => (L ω - D ω) ^ 2) P := (hLL2.sub hDL2).integrable_sq
  have h0 := (integral_eq_zero_iff_of_nonneg (fun ω => sq_nonneg (L ω - D ω)) hint).1 hsq
  filter_upwards [h0, hZY] with ω hω hωY
  have hLD : L ω = D ω := by
    have h2 : (L ω - D ω) ^ 2 = 0 := hω
    have := (pow_eq_zero_iff (n := 2) (by norm_num)).1 h2
    linarith
  show ∫ z, Y z ω ∂ν = D ω
  rw [← hLD]
  exact integral_congr_ae (hae.mono fun z hz => (hωY z (hKH hz)).symm)

end Fubini

/-! ## 8. The domain Markov property -/

/-- Balanced pairs of admissible measures giving no mass to `ball t r`. -/
abbrev OutIdx (t r : ℝ) :=
  {p : Measure ℂ × Measure ℂ // IsAdmissibleH p.1 ∧ IsAdmissibleH p.2 ∧
    p.1 Set.univ = p.2 Set.univ ∧ p.1 (ball (t : ℂ) r) = 0 ∧ p.2 (ball (t : ℂ) r) = 0}

/-- Balanced pairs of admissible measures (the index set of `IsFreeGFFModConstH.gaussian`). -/
abbrev BalIdx :=
  {p : Measure ℂ × Measure ℂ // IsAdmissibleH p.1 ∧ IsAdmissibleH p.2 ∧
    p.1 Set.univ = p.2 Set.univ}

section Markov

variable {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} {X : Ω → FieldSample}

/-- The σ-algebra generated by the free field outside the half-disc: balanced differences of
admissible measures giving no mass to `ball t r` (blueprint L2). -/
def outsideSigma (X : Ω → FieldSample) (t r : ℝ) : MeasurableSpace Ω :=
  ⨆ (p : OutIdx t r), MeasurableSpace.comap (fun ω => X ω p.1.1 - X ω p.1.2) inferInstance

/-- Local measures: admissible and carried by a closed disc `closedBall t r'`, `r' < r`. -/
def IsLocalH (t r : ℝ) (μ : Measure ℂ) : Prop :=
  IsAdmissibleH μ ∧ ∃ r' < r, μ (closedBall (t : ℂ) r')ᶜ = 0

/-- The local part `Z μ = X μ - X (bal μ)`. -/
def markovZ (X : Ω → FieldSample) (t r : ℝ) : Ω → FieldSample :=
  fun ω μ => X ω μ - X ω (bal t r μ)

/-- The increments `w ↦ X(P_{retr w}) - X(P_t)` of the harmonic part, on all of `ℂ`. -/
def harmIncr (X : Ω → FieldSample) (t r r' : ℝ) : ℂ → Ω → ℝ :=
  fun w ω => X ω (halfDiscPoisson t r (retr t r' w)) - X ω (halfDiscPoisson t r (t : ℂ))

/-- The harmonic part: a continuous version of `z ↦ X(P_z) - X(P_t)` near the half-disc. -/
def harmH (X : Ω → FieldSample) (t r r' : ℝ) : Ω → ℂ → ℝ :=
  fun ω z => kolY (harmIncr X t r r') (foldH z) ω

theorem measurable_outsideSigma {t r : ℝ} {μ ν : Measure ℂ} (hμ : IsAdmissibleH μ)
    (hν : IsAdmissibleH ν) (hm : μ Set.univ = ν Set.univ) (hμB : μ (ball (t : ℂ) r) = 0)
    (hνB : ν (ball (t : ℂ) r) = 0) :
    Measurable[outsideSigma X t r] fun ω => X ω μ - X ω ν :=
  measurable_iff_comap_le.2 (le_iSup (fun p : OutIdx t r =>
    MeasurableSpace.comap (fun ω => X ω p.1.1 - X ω p.1.2) inferInstance)
    ⟨(μ, ν), hμ, hν, hm, hμB, hνB⟩)

theorem norm_self_sub_ofReal (t : ℝ) : ‖(t : ℂ) - t‖ = 0 := by simp

theorem measurable_harmIncr_outside {t r r' : ℝ} (hr : 0 < r) (hr' : 0 < r') (hr'r : r' < r)
    (w : ℂ) : Measurable[outsideSigma X t r] (harmIncr X t r r' w) := by
  have h1 := norm_retr_sub_le (t := t) hr' w
  have h0 : ‖(t : ℂ) - t‖ ≤ r' := by rw [norm_self_sub_ofReal]; exact hr'.le
  have := isProbabilityMeasure_halfDiscPoisson hr (mem_ball_of_le_k3 hr'r h1)
  have := isProbabilityMeasure_halfDiscPoisson hr (mem_ball_of_le_k3 hr'r h0)
  exact measurable_outsideSigma (isAdmissibleH_halfDiscPoisson hr hr'r h1)
    (isAdmissibleH_halfDiscPoisson hr hr'r h0) (by rw [measure_univ, measure_univ])
    (halfDiscPoisson_ball hr _) (halfDiscPoisson_ball hr _)

theorem map_diff_eq_gaussianReal_k3 (hX : IsFreeGFFModConstH X P) {μ ν : Measure ℂ}
    (hμ : IsAdmissibleH μ) (hν : IsAdmissibleH ν) (hm : μ Set.univ = ν Set.univ) :
    P.map (fun ω => X ω μ - X ω ν) =
      gaussianReal 0 (kernelCov2 neumannH (μ, ν) (μ, ν)).toNNReal := by
  have hG : HasGaussianLaw (fun ω => X ω μ - X ω ν) P :=
    hX.gaussian.hasGaussianLaw_eval ⟨(μ, ν), hμ, hν, hm⟩
  have hmeas : AEMeasurable (fun ω => X ω μ - X ω ν) P :=
    ((hX.measurable_coord _).sub (hX.measurable_coord _)).aemeasurable
  have hc : P[fun ω => X ω μ - X ω ν] = 0 := hX.centered _ _ hμ hν hm
  have hcov : cov[fun ω => X ω μ - X ω ν, fun ω => X ω μ - X ω ν; P] =
      kernelCov2 neumannH (μ, ν) (μ, ν) :=
    hX.covariance_eq (μ, ν) (μ, ν) hμ hν hm hμ hν hm
  rw [hG.map_eq_gaussianReal, hc, ← covariance_self hmeas, hcov]

/-- The eighth-moment Kolmogorov bound for `harmIncr`. -/
theorem momentBound_harmIncr (hX : IsFreeGFFModConstH X P) {t r r' : ℝ} (hr : 0 < r)
    (hr' : 0 < r') (hr'r : r' < r) :
    CircleCont.MomentBound (harmIncr X t r r') P
      ((4 * (lipρ r r' * Bv t r r')) ^ 4 * gaussianAbsMoment 8) := by
  intro z _ w _
  have hz := norm_retr_sub_le (t := t) hr' z
  have hw := norm_retr_sub_le (t := t) hr' w
  have := isProbabilityMeasure_halfDiscPoisson hr (mem_ball_of_le_k3 hr'r hz)
  have := isProbabilityMeasure_halfDiscPoisson hr (mem_ball_of_le_k3 hr'r hw)
  have e : ∀ ω, harmIncr X t r r' z ω - harmIncr X t r r' w ω =
      X ω (halfDiscPoisson t r (retr t r' z)) - X ω (halfDiscPoisson t r (retr t r' w)) :=
    fun ω => by simp only [harmIncr]; ring
  simp only [e]
  rw [CircleCont.lintegral_pow8_of_map_eq (U := fun ω => X ω (halfDiscPoisson t r (retr t r' z)) -
      X ω (halfDiscPoisson t r (retr t r' w))) ((hX.measurable_coord _).sub (hX.measurable_coord _))
    (map_diff_eq_gaussianReal_k3 hX (isAdmissibleH_halfDiscPoisson hr hr'r hz)
      (isAdmissibleH_halfDiscPoisson hr hr'r hw) (by rw [measure_univ, measure_univ]))]
  apply ENNReal.ofReal_le_ofReal
  have hL : 0 ≤ lipρ r r' * Bv t r r' :=
    mul_nonneg (lipρ_nonneg hr'.le hr'r) ENNReal.toReal_nonneg
  have hkb := kernelCov2_halfDiscPoisson_le hr hr'.le hr'r hz hw
  have hlip := norm_retr_sub_retr_le (t := t) hr' z w
  have hkb' : kernelCov2 neumannH (halfDiscPoisson t r (retr t r' z),
      halfDiscPoisson t r (retr t r' w)) (halfDiscPoisson t r (retr t r' z),
      halfDiscPoisson t r (retr t r' w)) ≤ 4 * (lipρ r r' * Bv t r r') * ‖z - w‖ := by
    nlinarith [mul_le_mul_of_nonneg_left hlip hL]
  have hnn : 0 ≤ 4 * (lipρ r r' * Bv t r r') * ‖z - w‖ :=
    mul_nonneg (mul_nonneg (by norm_num) hL) (norm_nonneg _)
  have hv : ((kernelCov2 neumannH (halfDiscPoisson t r (retr t r' z),
      halfDiscPoisson t r (retr t r' w)) (halfDiscPoisson t r (retr t r' z),
      halfDiscPoisson t r (retr t r' w))).toNNReal : ℝ) ≤
        4 * (lipρ r r' * Bv t r r') * ‖z - w‖ := by
    rw [Real.coe_toNNReal']; exact max_le hkb' hnn
  have h4 := pow_le_pow_left₀ (NNReal.coe_nonneg _) hv 4
  calc _ ≤ (4 * (lipρ r r' * Bv t r r') * ‖z - w‖) ^ 4 * gaussianAbsMoment 8 :=
        mul_le_mul_of_nonneg_right h4 (gaussianAbsMoment_nonneg 8)
    _ = (4 * (lipρ r r' * Bv t r r')) ^ 4 * gaussianAbsMoment 8 * ‖z - w‖ ^ 4 := by ring

theorem kolY_harmIncr_spec (hX : IsFreeGFFModConstH X P) {t r r' : ℝ} (hr : 0 < r)
    (hr' : 0 < r') (hr'r : r' < r) :
    (∀ ω, ContinuousOn (fun z => kolY (harmIncr X t r r') z ω) Hbar) ∧
      (∀ z ∈ Hbar, kolY (harmIncr X t r r') z =ᵐ[P] harmIncr X t r r' z) :=
  kolY_spec (fun z => ((hX.measurable_coord _).sub (hX.measurable_coord _)).aemeasurable)
    (mul_nonneg (pow_nonneg (mul_nonneg (by norm_num)
      (mul_nonneg (lipρ_nonneg hr'.le hr'r) ENNReal.toReal_nonneg)) 4)
      (gaussianAbsMoment_nonneg 8))
    (momentBound_harmIncr hX hr hr' hr'r)

theorem continuous_harmH (hX : IsFreeGFFModConstH X P) {t r r' : ℝ} (hr : 0 < r)
    (hr' : 0 < r') (hr'r : r' < r) (ω : Ω) : Continuous (harmH X t r r' ω) :=
  ((kolY_harmIncr_spec (P := P) hX hr hr' hr'r).1 ω).comp_continuous
    CircleFubini.continuous_foldH' CircleFubini.foldH_mem_Hbar'

theorem measurable_harmH_outside {t r r' : ℝ} (hr : 0 < r) (hr' : 0 < r') (hr'r : r' < r)
    (z : ℂ) : Measurable[outsideSigma X t r] fun ω => harmH X t r r' ω z :=
  @measurable_kolY Ω (outsideSigma X t r) (harmIncr X t r r')
    (fun w => measurable_harmIncr_outside hr hr' hr'r w) (foldH z)
    (CircleFubini.foldH_mem_Hbar' z)

theorem exists_ballH_of_admissible {μ : Measure ℂ} (hμ : IsAdmissibleH μ) :
    ∃ R, μ (ballH R)ᶜ = 0 := by
  obtain ⟨-, ⟨K, hK, hKH, hK0⟩, -⟩ := hμ
  obtain ⟨R, hR⟩ := hK.isBounded.subset_closedBall (0 : ℂ)
  exact ⟨R, measure_mono_null (Set.compl_subset_compl.2 fun x hx => ⟨hR hx, hKH hx⟩) hK0⟩

theorem ae_mem_Hbar_of_admissible {μ : Measure ℂ} (hμ : IsAdmissibleH μ) :
    ∀ᵐ x ∂μ, x ∈ Hbar := by
  obtain ⟨-, ⟨K, -, hKH, hK0⟩, -⟩ := hμ
  filter_upwards [mem_ae_iff.2 hK0] with x hx using hKH hx

/-- **Decomposition** `X μ = Z μ + ∫ h dμ + μ(ℂ) · X(P_t)` a.s. for admissible `μ` carried by
`closedBall t r'`. -/
theorem markov_decomposition [IsProbabilityMeasure P] (hX : IsFreeGFFModConstH X P)
    {t r r' : ℝ} (hr : 0 < r) (hr' : 0 < r') (hr'r : r' < r) {μ : Measure ℂ}
    (hμ : IsAdmissibleH μ) (hμr : μ (closedBall (t : ℂ) r')ᶜ = 0) :
    ∀ᵐ ω ∂P, X ω μ = markovZ X t r ω μ + ∫ z, harmH X t r r' ω z ∂μ +
      (μ Set.univ).toReal * X ω (halfDiscPoisson t r (t : ℂ)) := by
  have hfin : IsFiniteMeasure μ := hμ.1
  set K := closedBall (t : ℂ) r' ∩ Hbar with hK_def
  have hKc : IsCompact K := (isCompact_closedBall _ _).inter_right isClosed_Hbar
  have ht0 : ‖(t : ℂ) - t‖ ≤ r' := by rw [norm_self_sub_ofReal]; exact hr'.le
  have htK : (t : ℂ) ∈ K := ⟨mem_closedBall_iff_norm.2 ht0, by show (0 : ℝ) ≤ (t : ℂ).im; simp⟩
  have hμK : μ Kᶜ = 0 := by
    rw [hK_def, Set.compl_inter]
    exact measure_union_null hμr (ae_iff.1 (ae_mem_Hbar_of_admissible hμ))
  have hKb : ∀ z ∈ K, ‖z - t‖ ≤ r' := fun z hz => mem_closedBall_iff_norm.1 hz.1
  obtain ⟨hYc, hY⟩ := kolY_harmIncr_spec (P := P) hX hr hr' hr'r
  have hF := stochFubini_kernel hX (measurable_halfDiscPoisson t r) hKc
    Set.inter_subset_right htK (R := |t| + r) (potC_ne_top r r')
    (fun z hz => by
      have := isProbabilityMeasure_halfDiscPoisson hr (mem_ball_of_le_k3 hr'r (hKb z hz))
      exact measure_univ)
    (fun z _ => halfDiscPoisson_ballH_compl hr z le_rfl)
    (fun z hz y => halfDiscPoisson_pot_le hr hr'r (hKb z hz) y)
    hYc (W := harmIncr X t r r')
    (fun z => show Measurable (harmIncr X t r r' z) from
      (hX.measurable_coord _).sub (hX.measurable_coord _)) hY
    (fun z hz => by
      funext ω
      simp only [harmIncr, retr_eq_self hz.2 (hKb z hz)])
    μ hμK
  -- linearity for the constant term
  have hP0 := isAdmissibleH_halfDiscPoisson hr hr'r ht0
  have hlin := hX.linear _ _ hP0 hP0 (μ Set.univ).toNNReal 0
  have hmeq : ((μ Set.univ).toNNReal • halfDiscPoisson t r (t : ℂ) +
      (0 : ℝ≥0) • halfDiscPoisson t r (t : ℂ) : Measure ℂ) =
      μ Set.univ • halfDiscPoisson t r (t : ℂ) := by
    rw [zero_smul, add_zero]
    ext s hs
    rw [Measure.coe_nnreal_smul_apply, Measure.smul_apply, smul_eq_mul,
      ENNReal.coe_toNNReal (measure_ne_top _ _)]
  rw [hmeq] at hlin
  have hH : ∀ ω, ∫ z, harmH X t r r' ω z ∂μ = ∫ z, kolY (harmIncr X t r r') z ω ∂μ := fun ω =>
    integral_congr_ae ((ae_mem_Hbar_of_admissible hμ).mono fun z hz => by
      simp only [harmH, CircleFubini.foldH_of_mem' hz])
  filter_upwards [hF, hlin] with ω hω hl
  rw [hH ω, hω, hl]
  simp only [markovZ, bal, NNReal.coe_zero, zero_mul, add_zero]
  rw [show ((μ Set.univ).toNNReal : ℝ) = (μ Set.univ).toReal from rfl]
  ring

theorem IsLocalH.bal_spec {t r : ℝ} (hr : 0 < r) {μ : Measure ℂ} (h : IsLocalH t r μ) :
    IsAdmissibleH (bal t r μ) ∧ μ Set.univ = bal t r μ Set.univ := by
  obtain ⟨hμ, r', hr'r, hμr⟩ := h
  have := hμ.1
  exact ⟨isAdmissibleH_bal hr hr'r hμr, (bal_univ hr hr'r hμr).symm⟩

/-- The index map of the local process into balanced admissible pairs. -/
def localIdx {t r : ℝ} (hr : 0 < r) (μ : {μ // IsLocalH t r μ}) : BalIdx :=
  ⟨(μ.1, bal t r μ.1), μ.2.1, (μ.2.bal_spec hr).1, (μ.2.bal_spec hr).2⟩

theorem integral_markovZ (hX : IsFreeGFFModConstH X P) {t r : ℝ} (hr : 0 < r) {μ : Measure ℂ}
    (hμ : IsLocalH t r μ) : ∫ ω, markovZ X t r ω μ ∂P = 0 :=
  hX.centered _ _ hμ.1 (hμ.bal_spec hr).1 (hμ.bal_spec hr).2

/-- Support and potential data of a local measure (and of its balayage) in a common `ballH R`. -/
theorem local_data {t r : ℝ} (hr : 0 < r) {μ : Measure ℂ} (hμ : IsLocalH t r μ) :
    ∃ r' < r, μ (closedBall (t : ℂ) r')ᶜ = 0 ∧ ∃ R, |t| + r ≤ R ∧ μ (ballH R)ᶜ = 0 := by
  obtain ⟨hA, r', hr'r, hμr⟩ := hμ
  obtain ⟨R, hR⟩ := exists_ballH_of_admissible hA
  exact ⟨r', hr'r, hμr, max R (|t| + r), le_max_right _ _,
    compl_ballH_null_mono (le_max_left _ _) hR⟩

theorem covariance_markovZ (hX : IsFreeGFFModConstH X P) {t r : ℝ} (hr : 0 < r)
    {μ ν : Measure ℂ} (hμ : IsLocalH t r μ) (hν : IsLocalH t r ν) :
    cov[fun ω => markovZ X t r ω μ, fun ω => markovZ X t r ω ν; P] =
      kernelCov (halfDiscGreen t r) μ ν := by
  have hc := hX.covariance_eq (μ, bal t r μ) (ν, bal t r ν) hμ.1 (hμ.bal_spec hr).1
    (hμ.bal_spec hr).2 hν.1 (hν.bal_spec hr).1 (hν.bal_spec hr).2
  simp only [markovZ]
  rw [hc]
  obtain ⟨r₁, hr₁, hμr, R₁, hR₁, hμR⟩ := local_data hr hμ
  obtain ⟨r₂, hr₂, hνr, R₂, hR₂, hνR⟩ := local_data hr hν
  set R := max R₁ R₂
  have hμR' := compl_ballH_null_mono (le_max_left R₁ R₂) hμR
  have hνR' := compl_ballH_null_mono (le_max_right R₁ R₂) hνR
  have hRt : |t| + r ≤ R := hR₁.trans (le_max_left _ _)
  have := hμ.1.1
  have := hν.1.1
  have := isFiniteMeasure_bal hr hr₂ hνr
  obtain ⟨Cν, hCν, hνP⟩ := hν.1.2.2
  have e1 := kernelCov_bal_left (μ := μ) hr hr₁ hμr hRt (bal_ballH_compl (μ := ν) hr hRt)
    (ENNReal.mul_ne_top (measure_ne_top ν _) (potC_ne_top r r₂)) (bal_pot_le hr hr₂ hνr)
    (bal_ball hr)
  have e2 := kernelCov_halfDiscGreen hr hr₁ hμr hRt hμR' hνR' hCν.ne hνP
  simp only [kernelCov2]
  rw [e1, e2]
  ring

/-- **Independence** of the local process from the outside σ-algebra. -/
theorem indep_markovZ_outside [IsProbabilityMeasure P] (hX : IsFreeGFFModConstH X P) {t r : ℝ}
    (hr : 0 < r) :
    Indep (⨆ μ : {μ // IsLocalH t r μ},
        MeasurableSpace.comap (fun ω => markovZ X t r ω μ.1) inferInstance)
      (outsideSigma X t r) P := by
  set Zf : {μ // IsLocalH t r μ} → Ω → ℝ := fun μ ω => markovZ X t r ω μ.1 with hZf
  set Of : OutIdx t r → Ω → ℝ := fun p ω => X ω p.1.1 - X ω p.1.2 with hOf
  let g : {μ // IsLocalH t r μ} ⊕ OutIdx t r → BalIdx :=
    Sum.elim (localIdx hr) fun p => ⟨p.1, p.2.1, p.2.2.1, p.2.2.2.1⟩
  have hG : IsGaussianProcess (Sum.elim Zf Of) P := by
    have := hX.gaussian.comp_right g
    have hfe : Sum.elim Zf Of = (fun (p : BalIdx) ω => X ω p.1.1 - X ω p.1.2) ∘ g := by
      funext x
      cases x <;> rfl
    rw [hfe]
    exact this
  have hcov : ∀ μ p, cov[Zf μ, Of p; P] = 0 := by
    intro μ p
    obtain ⟨⟨ν, ν'⟩, hν, hν', hm, hνB, hν'B⟩ := p
    have hc := hX.covariance_eq (μ.1, bal t r μ.1) (ν, ν') μ.2.1 (μ.2.bal_spec hr).1
      (μ.2.bal_spec hr).2 hν hν' hm
    simp only [hZf, hOf, markovZ]
    rw [hc]
    obtain ⟨r₁, hr₁, hμr, R₁, hR₁, -⟩ := local_data hr μ.2
    obtain ⟨R₂, hR₂⟩ := exists_ballH_of_admissible hν
    obtain ⟨R₃, hR₃⟩ := exists_ballH_of_admissible hν'
    set R := max R₁ (max R₂ R₃)
    have hRt : |t| + r ≤ R := hR₁.trans (le_max_left _ _)
    have := μ.2.1.1
    have := hν.1
    have := hν'.1
    obtain ⟨C₂, hC₂, hP₂⟩ := hν.2.2
    obtain ⟨C₃, hC₃, hP₃⟩ := hν'.2.2
    have e1 := kernelCov_bal_left (μ := μ.1) hr hr₁ hμr hRt
      (compl_ballH_null_mono ((le_max_left _ _).trans (le_max_right _ _)) hR₂) hC₂.ne hP₂ hνB
    have e2 := kernelCov_bal_left (μ := μ.1) hr hr₁ hμr hRt
      (compl_ballH_null_mono ((le_max_right _ _).trans (le_max_right _ _)) hR₃) hC₃.ne hP₃ hν'B
    simp only [kernelCov2]
    rw [e1, e2]
    ring
  have hind := hG.indepFun_of_covariance_eq_zero
    (fun μ => ((hX.measurable_coord _).sub (hX.measurable_coord _)).aemeasurable)
    (fun p => ((hX.measurable_coord _).sub (hX.measurable_coord _)).aemeasurable) hcov
  have hI : Indep (MeasurableSpace.comap (fun ω μ => Zf μ ω) inferInstance)
      (MeasurableSpace.comap (fun ω p => Of p ω) inferInstance) P := hind
  refine indep_of_indep_of_le hI (iSup_le fun μ => ?_) (iSup_le fun p => ?_)
  · exact measurable_iff_comap_le.1
      ((measurable_pi_apply μ).comp (comap_measurable (fun ω μ => Zf μ ω)))
  · exact measurable_iff_comap_le.1
      ((measurable_pi_apply p).comp (comap_measurable (fun ω p => Of p ω)))

end Markov

end K3

end QuantumZipper
