import QuantumZipper.Proofs.GFF.K3.MixedProj
import QuantumZipper.Statements.Prop16
import Mathlib.Probability.Independence.Basic

/-!
# Statements of the remaining K3-mixed nodes M5(c)–(d), M6, M7

Blueprint: `blueprint/GFF_K3_BLUEPRINT.md`, §3.M. These are the fixed Lean statements of the
nodes that are **not yet proved**. They are `Prop`-valued definitions (never assumed anywhere);
the proved nodes are in `MixedProj.lean` (M5 first part) and `MixedM5*.lean`.

Conventions (deviation L-K3): the blueprint's per-point radius `r₀ x` is replaced by one uniform
radius `R > 0` with `LocalBall D S z (2 * R)` for every `z ∈ K`, as in M4; the remainder kernel
uses the folded circles of radius `R` (by `remVec_foldedCircle_eq` any radius `< 2R` gives the
same kernel).
-/

noncomputable section

open MeasureTheory Set Metric ProbabilityTheory
open scoped Real ComplexConjugate ENNReal NNReal RealInnerProductSpace

namespace QuantumZipper.K3

/-- The standing local hypotheses of M5–M7: `(D, S)` a bounded open subset of `H` with free
part on `ℝ`, `K` compact with uniform local discs of radius `2R`. -/
structure MixedLocalHyp (D S K : Set ℂ) (R : ℝ) : Prop where
  isOpen : IsOpen D
  subset_H : D ⊆ H
  bounded : Bornology.IsBounded D
  free_real : S ⊆ {z : ℂ | z.im = 0}
  compact : IsCompact K
  pos : 0 < R
  local_ : ∀ z ∈ K, LocalBall D S z (2 * R)

/-- The domain geometry of Proposition 1.6 (the hypotheses on `(D, c, d)` in `theorem1_6`). -/
def Prop16Geometry (D : Set ℂ) (c d : ℝ) : Prop :=
  IsOpen D ∧ IsConnected D ∧ Bornology.IsBounded D ∧ D ⊆ H ∧ c < d ∧
    frontier D ∩ {z : ℂ | z.im = 0} = realSet (Set.Icc c d) ∧
    ∀ t ∈ Set.Ioo c d, ∃ r > 0, Metric.ball (t : ℂ) r ∩ H ⊆ D

/-- **M6.** Near the free arc, the mixed covariance is `neumannH` plus a continuous kernel. -/
def MixedLocalKernelStmt (D : Set ℂ) (c d : ℝ) (K : Set ℂ) (R : ℝ) : Prop :=
  Prop16Geometry D c d → MixedLocalHyp D (realSet (Set.Icc c d)) K R →
    ∃ k : ℂ → ℂ → ℝ, ContinuousOn (Function.uncurry k) (K ×ˢ K) ∧
      ∀ μ ν : Measure ℂ, IsAdmissibleH μ → μ Kᶜ = 0 → IsAdmissibleH ν → ν Kᶜ = 0 →
        dualCov D (mixedSpace D (realSet (Set.Icc c d))) μ ν =
          kernelCov (fun x y => neumannH x y + k x y) μ ν

/-- The σ-algebra generated by the balanced increments of a free field modulo constants. -/
def freeIncrSigma {Ω : Type*} (X : Ω → FieldSample) : MeasurableSpace Ω :=
  MeasurableSpace.comap
    (fun ω (p : {p : Measure ℂ × Measure ℂ //
        IsAdmissibleH p.1 ∧ IsAdmissibleH p.2 ∧ p.1 Set.univ = p.2 Set.univ}) =>
      X ω p.1.1 - X ω p.1.2) MeasurableSpace.pi

end QuantumZipper.K3
