import LQGMetric.Papers.DZZ.S3ConcG
import LQGMetric.Papers.DDDF.P10Space

/-!
# D124 packet I1: the mixing white noise `wnMix` (P2-DZZI0)

Decision D124 (`decisions/DEC-124.md` §1, §5 I1). DZZ (arXiv:1807.00422, `LBM_LGDarXiv.tex`)
l. 1555–1566: `𝐗_δ` is generated by the white noise at times `s ≥ δ^{2C_mc}`, `𝐘_δ` (its
orthogonal complement) by the white noise at times `s < δ^{2C_mc}`, and the field with coarse part
`𝐱_δ` and fine part `𝒴_δ` is the object of the conditional argument. We realise the pair
`(coarse of ω₁, fine of ω₂)` as the white noise `wnMix W κ δ` on `(Ω × Ω, P ⊗ P)`.

* **`isWhiteNoise_wnMix`**: `wnMix W κ δ` is a white noise (the computation of
  `WNPush.isWhiteNoise_coupledNoise`, with the two independent white noises `W ∘ fst`, `W ∘ snd`
  of `DDDF.isWhiteNoise_fst/snd`, `indepFun_fst_snd_noise`).
* `wnMix_eq_fst`: for `g` supported in `coarseTime κ δ`, `W̃ g (ω₁, ω₂) = W g ω₁` whenever
  `W 0 ω₂ = 0` (an a.s. event).
* **`coarseField_wnMix`**: the coarse field of `W̃` at `(ω₁, ω₂)` is that of `W` at `ω₁`
  (DZZ l. 1567: `𝒳_δ` is a function of the coarse part only).
* **`cutL2_wndKernelL2_coarse`**, **`tildeHInf_wnMix_sub`**: the exact identity
  `h̃_ε(v)(ω₁,ω₂) − h̃_ε(v)(ω₁',ω₂) = h̃_{max(ε,δ^κ)}(v)(ω₁) − h̃_{max(ε,δ^κ)}(v)(ω₁')`
  (the fine parts cancel), used for Lemma 3.8 on the mixed samples (DZZ l. 1584–1587).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory ProbabilityTheory Real Set Filter
open scoped ENNReal

namespace LQGMetric
namespace DZZ

open WhiteNoise WNPush DDDF

variable {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} {W : WNSpace → Ω → ℝ}

/-- **The mixing noise is a white noise** (D124-1; same computation as
`isWhiteNoise_coupledNoise`). -/
theorem isWhiteNoise_wnMix (hW : IsWhiteNoise P W) (κ δ : ℝ) :
    IsWhiteNoise (P.prod P) (wnMix W κ δ) := by
  have h1 := isWhiteNoise_fst hW
  have h2 := isWhiteNoise_snd hW
  refine ⟨fun f => (h1.measurable _).add (h2.measurable _), ?_⟩
  intro ι _ f c
  set hC := measurableSet_coarseTime κ δ
  set X : Ω × Ω → ℝ := fun ω => ∑ i, c i * W (cutL2 hC (f i)) ω.1
  set Y : Ω × Ω → ℝ := fun ω => ∑ i, c i * W (cutL2 hC.compl (f i)) ω.2
  have hX := h1.hasLaw (fun i => cutL2 hC (f i)) c
  have hY := h2.hasLaw (fun i => cutL2 hC.compl (f i)) c
  have hXY : IndepFun X Y (P.prod P) :=
    (indepFun_fst_snd_noise hW).comp
      (φ := fun x : WNSpace → ℝ => ∑ i, c i * x (cutL2 hC (f i)))
      (ψ := fun x : WNSpace → ℝ => ∑ i, c i * x (cutL2 hC.compl (f i)))
      (Finset.measurable_sum _ fun i _ => (measurable_pi_apply _).const_mul _)
      (Finset.measurable_sum _ fun i _ => (measurable_pi_apply _).const_mul _)
  have e : (fun ω => ∑ i, c i * wnMix W κ δ (f i) ω) = X + Y := by
    funext ω
    simp [X, Y, wnMix, mul_add, Finset.sum_add_distrib]
  have e1 : ∀ (A : Set (ℝ × ℂ)) (hA : MeasurableSet A),
      ∑ i, c i • cutL2 hA (f i) = cutL2 hA (∑ i, c i • f i) := by
    intro A hA
    rw [← cutLM_apply, map_sum]
    simp only [map_smul, cutLM_apply]
  have hnorm : ‖∑ i, c i • cutL2 hC (f i)‖ ^ 2 + ‖∑ i, c i • cutL2 hC.compl (f i)‖ ^ 2 =
      ‖∑ i, c i • f i‖ ^ 2 := by
    rw [e1 _ hC, e1 _ hC.compl, norm_sq_cutL2, norm_sq_cutL2, norm_sq_split hC]
  rw [e]
  refine ⟨hX.aemeasurable.add hY.aemeasurable, ?_⟩
  rw [gaussianReal_add_gaussianReal_of_indepFun hXY hX hY, add_zero,
    ← Real.toNNReal_add (sq_nonneg _) (sq_nonneg _), hnorm]

/-- `g 1_A = g` in `L²` for `g` supported in `A`. -/
lemma cutL2_of_supportedIn {A : Set (ℝ × ℂ)} (hA : MeasurableSet A) {g : WNSpace}
    (hg : SupportedIn A g) : cutL2 hA g = g := by
  apply Lp.ext
  filter_upwards [coeFn_cutL2 hA g, (ae_restrict_iff' hA.compl).1 hg] with p h1 h3
  rw [h1]
  by_cases hp : p ∈ A
  · simp [hp]
  · simp [hp, h3 (mem_compl hp)]

/-- `g 1_{Aᶜ} = 0` in `L²` for `g` supported in `A`. -/
lemma cutL2_compl_of_supportedIn {A : Set (ℝ × ℂ)} (hA : MeasurableSet A) {g : WNSpace}
    (hg : SupportedIn A g) : cutL2 hA.compl g = 0 := by
  apply Lp.ext
  filter_upwards [coeFn_cutL2 hA.compl g, Lp.coeFn_zero ℝ 2 volume,
    (ae_restrict_iff' hA.compl).1 hg] with p h1 h2 h3
  rw [h1, h2]
  by_cases hp : p ∈ Aᶜ
  · simp [hp, h3 hp]
  · simp [hp]

/-- `W 0 = 0` almost surely. -/
lemma ae_wn_zero (hW : IsWhiteNoise P W) : ∀ᵐ ω ∂P, W 0 ω = 0 := by
  filter_upwards [hW.smul_ae 0 0] with ω hω
  simpa using hω

/-- For `g` supported in the coarse times, `W̃ g (ω₁, ω₂) = W g ω₁` once `W 0 ω₂ = 0`. -/
lemma wnMix_eq_fst_of {κ δ : ℝ} {g : WNSpace} (hg : SupportedIn (coarseTime κ δ) g)
    {ω₂ : Ω} (h0 : W 0 ω₂ = 0) (ω₁ : Ω) : wnMix W κ δ g (ω₁, ω₂) = W g ω₁ := by
  simp only [wnMix]
  rw [cutL2_of_supportedIn (measurableSet_coarseTime κ δ) hg,
    cutL2_compl_of_supportedIn (measurableSet_coarseTime κ δ) hg, h0, add_zero]

open Classical in
/-- An `L²` element given by a kernel vanishing outside `A` is supported in `A`. -/
lemma supportedIn_dite {A : Set (ℝ × ℂ)} (hA : MeasurableSet A) {k : ℝ × ℂ → ℝ}
    (hk : ∀ p, p ∉ A → k p = 0) :
    SupportedIn A (if h : MemLp k 2 volume then h.toLp k else 0) := by
  refine (ae_restrict_iff' hA.compl).2 ?_
  split_ifs with h
  · filter_upwards [h.coeFn_toLp] with p hp hpA
    rw [hp, hk p hpA]
  · filter_upwards [Lp.coeFn_zero ℝ 2 volume] with p hp _
    rw [hp]; rfl

lemma supportedIn_coarseKernel {κ δ : ℝ} (hδ : 0 ≤ δ) (t : CoarseIdx κ δ) :
    SupportedIn (coarseTime κ δ) (coarseKernel κ δ t) := by
  have hd : 0 ≤ δ ^ κ := Real.rpow_nonneg hδ κ
  have key : ∀ {ε : ℝ}, δ ^ κ ≤ ε → ∀ p : ℝ × ℂ, p ∉ coarseTime κ δ → p.1 ∉ Ioi (ε ^ 2) := by
    intro ε hε p hp h
    apply hp
    refine ⟨?_, mem_univ _⟩
    exact (pow_le_pow_left₀ hd hε 2).trans (le_of_lt h)
  rcases t with b | q
  · change SupportedIn _ (etaKernelL2 _ _)
    unfold etaKernelL2
    exact supportedIn_dite (measurableSet_coarseTime κ δ) fun p hp =>
      indicator_of_notMem (key b.2 p hp) _
  · change SupportedIn _ (wndKernelL2 _ _ _)
    unfold wndKernelL2
    exact supportedIn_dite (measurableSet_coarseTime κ δ) fun p hp =>
      indicator_of_notMem (key (le_of_isCoarseScale q.2.2.2) p hp) _

/-- **The coarse field of the mixed sample is that of the first coordinate** (D124-1). -/
theorem coarseField_wnMix (hW : IsWhiteNoise P W) {κ δ : ℝ} (hδ : 0 < δ) :
    ∀ᵐ ω₂ ∂P, ∀ ω₁ s, coarseField (wnMix W κ δ) κ δ s (ω₁, ω₂) = coarseField W κ δ s ω₁ := by
  filter_upwards [ae_wn_zero hW] with ω₂ h0 ω₁ s
  rw [coarseField_eq_sqrtPi, coarseField_eq_sqrtPi]
  simp only
  rw [wnMix_eq_fst_of (supportedIn_coarseKernel hδ.le s) h0]

/-- The time slice `{s = c}` is Lebesgue-null in `ℝ × ℂ`. -/
lemma ae_fst_ne (c : ℝ) : ∀ᵐ p : ℝ × ℂ ∂volume, p.1 ≠ c := by
  have h : (volume : Measure (ℝ × ℂ)) ({c} ×ˢ univ) = 0 := by
    rw [Measure.volume_eq_prod, Measure.prod_prod, Real.volume_singleton, zero_mul]
  filter_upwards [measure_eq_zero_iff_ae_notMem.1 h] with p hp hpc
  exact hp ⟨hpc, mem_univ _⟩

/-- **The cut of the `h̃_ε` kernel to the coarse times is the `h̃_{max(ε, δ^κ)}` kernel.** -/
theorem cutL2_wndKernelL2_coarse {κ δ : ℝ} (hδ : 0 < δ) {ε : ℝ} (hε : 0 < ε) (v : ℂ) :
    cutL2 (measurableSet_coarseTime κ δ) (wndKernelL2 openSquare (Ioi (ε ^ 2)) v) =
      wndKernelL2 openSquare (Ioi (max ε (δ ^ κ) ^ 2)) v := by
  have hd : 0 ≤ δ ^ κ := Real.rpow_nonneg hδ.le κ
  have hm : 0 < max ε (δ ^ κ) := lt_max_of_lt_left hε
  have hmem : ∀ e : ℝ, 0 < e → MemLp (wndKernel openSquare (Ioi (e ^ 2)) v) 2 volume :=
    fun e he => memLp_wndKernel LQGMetric.isOpen_openSquare (by norm_num : (0 : ℝ) ≤ 2)
      openSquare_subset_ball measurableSet_Ioi (half_pos (pow_pos he 2))
      (Ioi_subset_Ioi (half_lt_self (pow_pos he 2)).le) v
  have h1 := hmem ε hε
  have h2 := hmem _ hm
  apply Lp.ext
  rw [wndKernelL2, wndKernelL2, dite_eq_left_of_eq_true (eq_true h2),
    dite_eq_left_of_eq_true (eq_true h1)]
  filter_upwards [coeFn_cutL2 (measurableSet_coarseTime κ δ) (h1.toLp _), h1.coeFn_toLp, h2.coeFn_toLp,
      ae_fst_ne ((δ ^ κ) ^ 2)] with p hc hk1 hk2 hne
  rw [hc, hk2]
  have hsq : ∀ {a b : ℝ}, 0 ≤ a → a ≤ b → a ^ 2 ≤ b ^ 2 := fun ha hab =>
    pow_le_pow_left₀ ha hab 2
  by_cases hp : p ∈ coarseTime κ δ
  · have hp1 : (δ ^ κ) ^ 2 ≤ p.1 := hp.1
    have hp2 : (δ ^ κ) ^ 2 < p.1 := lt_of_le_of_ne hp1 (Ne.symm hne)
    rw [indicator_of_mem hp, hk1]
    unfold wndKernel
    rcases le_total ε (δ ^ κ) with h | h
    · rw [max_eq_right h, indicator_of_mem (mem_Ioi.2 hp2),
        indicator_of_mem (mem_Ioi.2 ((hsq hε.le h).trans_lt hp2))]
    · rw [max_eq_left h]
  · have hp1 : p.1 < (δ ^ κ) ^ 2 := by
      by_contra hc'
      exact hp ⟨not_lt.1 hc', mem_univ _⟩
    rw [indicator_of_notMem hp]
    unfold wndKernel
    rw [indicator_of_notMem]
    exact fun h => absurd (hp1.trans_le (hsq hd (le_max_right _ _))) (not_lt.2 (le_of_lt h))

/-- **The `h̃`-difference of two mixed samples with a common fine part** is the difference of the
coarse `h̃`-fields at the scale `max(ε, δ^κ)` (D124-1; exact, for every sample). -/
theorem tildeHInf_wnMix_sub (W : WNSpace → Ω → ℝ) {κ δ : ℝ} (hδ : 0 < δ) {ε : ℝ}
    (hε : 0 < ε) (v : ℂ) (ω₁ ω₁' ω₂ : Ω) :
    tildeHInf (wnMix W κ δ) ε v (ω₁, ω₂) - tildeHInf (wnMix W κ δ) ε v (ω₁', ω₂) =
      tildeHInf W (max ε (δ ^ κ)) v ω₁ - tildeHInf W (max ε (δ ^ κ)) v ω₁' := by
  simp only [tildeHInf, wnField, wnMix]
  rw [cutL2_wndKernelL2_coarse hδ hε]
  ring

end DZZ
end LQGMetric
