import LQGMetric.Papers.DZZ.S3P317E
import LQGMetric.Papers.DZZ.S3L10Exp
import LQGMetric.Papers.DZZ.S3L12S5
import LQGMetric.Papers.DDDF.L6Decomp

/-!
# D124: the coarse field `𝒳_δ`, the mixing white noise and DZZ's event `𝓔*` (shared statements)

Decision `decisions/DEC-124.md` (P2-DEC124). Source: DZZ (arXiv:1807.00422,
`LBM_LGDarXiv.tex`), proof of Prop 3.17, l. 1555–1594 and 1631–1645.

* `CoarseIdx κ δ`, `coarseField`: DZZ's `𝒳_δ` (l. 1557–1558), the Gaussian vector
  `{(η_ε(v), h̃_ε(v)) : v ∈ 𝕍, ε ≥ δ^{C_mc}}`, with the index set reduced to what the proof reads:
  the `η`-component at the dyadic boxes of side `≥ δ^κ` (the masses `M_{γ,s_B}(B)` of `D'`,
  (eq-def-approximate-LQG)) and the `h̃`-component at the rational points of `𝕍` and the scales
  `2^{-n} ≥ δ^κ` and `δ^κ` (Lemma 3.8 on `D_{γ,δ}`, the chaos of `h̃`; countable, so that the
  white-noise field — defined only a.s. — can be read at the indices).
  This replaces P2-DZZCONC's `η`-only index set of `S3ConcF` (DEC-124 §2: DZZ's Lipschitz
  argument compares the `h̃`-chaos `D_{γ,δ}` on two coarse configurations, so `h̃_ε(v)` must be a
  coordinate of `𝒳_δ`).
* `coarseTime κ δ = {s ≥ δ^{2κ}}` (`𝐗_δ`, l. 1558–1559: `𝐘_δ` is generated by `W` for
  `s < δ^{2C_mc}`); `wnMix W κ δ`: the white noise on `Ω × Ω` whose coarse part is read from the
  first coordinate and whose fine part from the second (DZZ's "`(𝐱_δ, 𝒴_δ)`", l. 1560–1566: the
  pair `(coarse, fine)` has the product law, so DZZ's conditional probabilities given `𝐗_δ` are
  Fubini integrals over the second factor; DEC-124 §1).
* `eStarEvent S γ W' μ' δ r τ A B`: DZZ's `𝓔̃*` (l. 1572–1575, 1633–1636) for the distance
  `D = D^{μ'}` and the approximate distance `D'_S` through the cell family `S` (`S = univ` for
  `D'`): `D'_δ` finite and `≥ 1`, `D_{δ'}` finite and
  `|log D_{δ'} − log D'_δ| ≤ τ` for all `δ' ∈ [δe^{−r}, δe^{r}]`. Part 1 of P3.17:
  `r = (ι/α) log δ⁻¹`, `τ = (ι/4) log δ⁻¹`; part 2: `r = α⁻¹ (log δ⁻¹)^{0.9}`,
  `τ = (log δ⁻¹)^{0.91}`. (DZZ's `δ''` is only used at `δ'' = δ`.)
* `WNCanon`, `wnCanon`, `wnPath`, `wnLaw`: the canonical white noise and the law of `W` (law transfer,
  packet I2L: `wnLaw_eq`, `isWhiteNoise_wnCanon`), which makes the `𝓔*` constants uniform in `δ`.
* `DZZEStar1`, `DZZEStar2`: the OPEN probability nodes for `𝓔*` at `μIn` (packet I2 of
  DEC-124; DZZ l. 1577–1579, 1637–1639: Prop 3.2 at `δe^{±r}` and Lemma 3.5 twice, Lemma 3.1).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory ProbabilityTheory Real Set Filter Metric
open scoped ENNReal

namespace LQGMetric
namespace DZZ

open WhiteNoise DyBox DDDF

variable {Ω : Type*}

/-! ### The coarse field -/

/-- `v` has rational coordinates. -/
def IsRatPt (v : ℂ) : Prop := ∃ a b : ℚ, v = ⟨a, b⟩

/-- The coarse scales: `δ^κ` itself and the dyadic scales `2^{-n} ≥ δ^κ`. -/
def IsCoarseScale (κ δ ε : ℝ) : Prop := ε = δ ^ κ ∨ ∃ n : ℕ, ε = (2 : ℝ)⁻¹ ^ n ∧ δ ^ κ ≤ ε

/-- The index set of the `h̃`-component: `(v, ε)` with `v ∈ 𝕍` rational and `ε` a coarse scale. -/
def CoarsePt (κ δ : ℝ) : Type :=
  {p : ℂ × ℝ // p.1 ∈ dzzV ∧ IsRatPt p.1 ∧ IsCoarseScale κ δ p.2}

/-- The index set of DZZ's `𝒳_δ`: the dyadic boxes of side `≥ δ^κ` (the `η`-component, read by
`D'`) and the coarse points (the `h̃`-component, read by Lemma 3.8). -/
def CoarseIdx (κ δ : ℝ) : Type := {b : DyBox // δ ^ κ ≤ b.side} ⊕ CoarsePt κ δ

/-- DZZ's coarse field `𝒳_δ`: `η_{s_B}(c_B)` at the boxes, `h̃_ε(v)` at the coarse points. -/
def coarseField (W : WNSpace → Ω → ℝ) (κ δ : ℝ) (p : CoarseIdx κ δ) (ω : Ω) : ℝ :=
  match p with
  | Sum.inl b => etaInf W b.1.side b.1.center ω
  | Sum.inr q => tildeHInf W q.1.2 q.1.1 ω

lemma coarseField_inl (W : WNSpace → Ω → ℝ) (κ δ : ℝ) (b : {b : DyBox // δ ^ κ ≤ b.side})
    (ω : Ω) : coarseField W κ δ (Sum.inl b) ω = etaInf W b.1.side b.1.center ω := rfl

/-! ### The mixing white noise -/

/-- The coarse time region `{(s, w) : s ≥ δ^{2κ}}` (DZZ l. 1558–1559). -/
def coarseTime (κ δ : ℝ) : Set (ℝ × ℂ) := timeHigh (δ ^ κ)

lemma measurableSet_coarseTime (κ δ : ℝ) : MeasurableSet (coarseTime κ δ) :=
  measurableSet_timeHigh _

/-- **The mixing white noise** on `Ω × Ω`: `W̃(g)(ω₁, ω₂) = W(g 1_{s ≥ δ^{2κ}})(ω₁) +
W(g 1_{s < δ^{2κ}})(ω₂)` — the coarse part `𝐱_δ` of the first sample and the fine part `𝐲_δ` of
the second (DZZ l. 1560–1566). -/
def wnMix (W : WNSpace → Ω → ℝ) (κ δ : ℝ) (g : WNSpace) (p : Ω × Ω) : ℝ :=
  W (WNPush.cutL2 (measurableSet_coarseTime κ δ) g) p.1 +
    W (WNPush.cutL2 (measurableSet_coarseTime κ δ).compl g) p.2

/-! ### The canonical white noise (law transfer) -/

/-- The canonical path space of a white noise. -/
abbrev WNCanon : Type := WNSpace → ℝ

/-- The coordinate process on `WNCanon`. -/
def wnCanon (f : WNSpace) (x : WNCanon) : ℝ := x f

/-- The path map `ω ↦ (f ↦ W f ω)`. -/
def wnPath (W : WNSpace → Ω → ℝ) (ω : Ω) : WNCanon := fun f => W f ω

/-- The law of a white noise on `WNCanon` (unique: packet I2L of DEC-124, `wnLaw_eq`; it is the
law of the Gaussian process with covariance `⟪f, g⟫`, as `IsZBGFFProcess.map_eq`). Every DZZ
statement for an arbitrary white noise applies to `(wnLaw W P, wnCanon)` once, with fixed
constants; the event probabilities of the mixing noises `wnMix W κ δ` (all `δ`) are then read off
by `wnLaw_eq`, which is how the constants of `DZZEStar1/2` are made uniform in `δ`. -/
def wnLaw [MeasurableSpace Ω] (W : WNSpace → Ω → ℝ) (P : Measure Ω) : Measure WNCanon :=
  P.map (wnPath W)

/-! ### DZZ's event `𝓔*` -/

/-- **DZZ's `𝓔̃*`** (l. 1572–1575; part 2: l. 1633–1636) for `D = D^{μ'}` and `D' = D'_S`:
`D'_δ(A, B)` finite and `≥ 1`, and for all `δ' ∈ [δ e^{−r}, δ e^{r}]`, `D_{δ'}(A, B)` finite with
`|log D_{δ'}(A, B) − log D'_δ(A, B)| ≤ τ`. -/
def eStarEvent {Ω' : Type*} (S : Set DyBox) (γ : ℝ) (W' : WNSpace → Ω' → ℝ)
    (μ' : Ω' → Measure ℂ) (δ r τ : ℝ) (A B : Set ℂ) : Set Ω' :=
  {ω | approxLGDSetOn S γ W' δ A B ω ≠ ⊤ ∧ 1 ≤ approxLGDSetOn S γ W' δ A B ω ∧
    ∀ δ' ∈ Icc (δ * Real.exp (-r)) (δ * Real.exp r),
      lgdMinSet (μ' ω) δ' A B ≠ ⊤ ∧
        |logMinLGD (μ' ω) δ' A B - logApproxLGDOn S γ W' δ A B ω| ≤ τ}

/-- **OPEN (packet I2, part 1)**: DZZ l. 1577–1579 at `μIn`. There are `α = α(γ) > 0` and
`c > 0` such that for every `ξ`-admissible sequence and every `ι ∈ (0,1)`,
`P(𝓔*_{δ,ι,α}ᶜ) ≤ δ^c` for all small `δ` (`r = (ι/α) log δ⁻¹`, `τ = (ι/4) log δ⁻¹`). -/
def DZZEStar1 [MeasurableSpace Ω] (P : Measure Ω) (γ : ℝ) (W : WNSpace → Ω → ℝ) (ξ : ℝ) : Prop :=
  ∃ α : ℝ, 0 < α ∧ ∃ c : ℝ, 0 < c ∧ ∀ A B : ℝ → Set ℂ, IsXiAdmissible ξ A B →
    ∀ ι ∈ Ioo (0 : ℝ) 1, ∃ δ₀ : ℝ, 0 < δ₀ ∧ ∀ δ ∈ Ioo (0 : ℝ) δ₀,
      P (eStarEvent univ γ W (dzzMuIn γ W) δ (ι / α * Real.log δ⁻¹) (ι / 4 * Real.log δ⁻¹)
        (A δ) (B δ))ᶜ ≤ ENNReal.ofReal (δ ^ c)

end DZZ
end LQGMetric
