import LQGMetric.Papers.DZZ.S3L12Defs

/-!
# DZZ Lemma 3.13: `σ(𝒱_δ)` is a sub-σ-algebra (P2-DZZ312)

`cellSigma_le`: the σ-algebra generated by the partition `𝒱_δ` is contained in the ambient one (so the
conditional expectation in `DZZLemma313` is the genuine one). Own elementary proof.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Set

namespace LQGMetric
namespace DZZ

open WhiteNoise DyBox

variable {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} {W : WNSpace → Ω → ℝ}

lemma measurable_approxLQG (hW : IsWhiteNoise P W) (γ : ℝ) (b : DyBox) :
    Measurable fun ω => approxLQG γ W ω b := by
  unfold approxLQG etaInf etaField
  exact measurable_const.mul (((hW.measurable _).const_mul _ |>.const_mul _).sub_const _).exp

lemma measurableSet_isCell (hW : IsWhiteNoise P W) (γ δ : ℝ) (b : DyBox) :
    MeasurableSet {ω | IsCell (approxLQG γ W ω) δ b} := by
  show MeasurableSet ({ω | approxLQG γ W ω b < δ ^ 2} ∩
    {ω | ∀ i < b.n, δ ^ 2 ≤ approxLQG γ W ω (b.anc i)})
  refine (measurableSet_lt (measurable_approxLQG hW γ b) measurable_const).inter ?_
  have e : {ω | ∀ i < b.n, δ ^ 2 ≤ approxLQG γ W ω (b.anc i)} =
      ⋂ i, ⋂ (_ : i < b.n), {ω | δ ^ 2 ≤ approxLQG γ W ω (b.anc i)} := by
    ext ω; simp
  rw [e]
  exact MeasurableSet.iInter fun i => MeasurableSet.iInter fun _ =>
    measurableSet_le measurable_const (measurable_approxLQG hW γ _)

/-- `σ(𝒱_δ) ≤` the ambient σ-algebra. -/
theorem cellSigma_le (hW : IsWhiteNoise P W) (γ δ : ℝ) :
    cellSigma γ W δ ≤ ‹MeasurableSpace Ω› := by
  refine Measurable.comap_le ?_
  rw [measurable_pi_iff]
  intro b
  refine measurable_to_prop ?_
  have : (fun ω => IsCell (approxLQG γ W ω) δ b) ⁻¹' {True} = {ω | IsCell (approxLQG γ W ω) δ b} := by
    ext ω; simp
  rw [this]
  exact measurableSet_isCell hW γ δ b

end DZZ
end LQGMetric
