import LQGMetric.Papers.DZZ.S6L61D
import LQGMetric.Papers.DZZ.S5L53B8

/-!
# D117: shared statements for the open DZZ §5–6 nodes (decision DEC-117)

Ding–Zeitouni–Zhang, arXiv:1807.00422, `literature/src/1807.00422/LBM_LGDarXiv.tex`:
lem-scaling-coupling l. 611–624 (`C = C(ξ, κ₁, κ₂)`, uniform in the translation), (eq-translation-
invariant) l. 2271, (eq-geodesic-range) l. 2340–2345, (eq-z-open) l. 2452, (eq-point-to-segment)
l. 2559 and its proof l. 2551–2568 (symmetry l. 2555, big balls l. 2562, crossings l. 2566),
(eq-point-to-boundary-kappa) l. 2593–2596, Fig. glue l. 2605.

This file only *states* the shared infrastructure decided in `decisions/DEC-117.md`:

* `DZZSimCoupleU`: the similarity coupling of walled LGDs (lem-scaling-coupling composed with
  DZZ L3.8, `dzz_lemma38_walled`), with the constant uniform in the translation `b`;
* `DZZDihedralLaw`: exact invariance in law under the symmetries of `𝕍` (used for DZZ's "by
  symmetry", l. 2555, through the reflection `x ↦ 1 − x`);
* `DZZBigBalls`: every ball of radius `≥ r` inside `𝕍` has mass `> 2δ²`, w.p. → 1 (l. 2562);
* `legWall`, `DZZLem54SegQ`: the corrected (eq-point-to-segment) (DEC-117 §2(a)): the leg from
  `u` to `L` lives in `legWall u λ L ⊆ 𝕍̃_{u,v}` (D123: the axis-parallel square `legSq`), and the segment length is `δ^κ` with
  `κ χ ≥ 2ι` (DZZ's `δ^{2ι}` needs `χ ≥ 1/2`);
* `DZZL61GlueK`: `DZZL61Glue` with the segment length `δ^κ` (same correction);
* `DZZCrossLemma`: the deterministic core of the gluing (perpendicular crossings of a rectangle
  intersect).
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false

noncomputable section

open MeasureTheory Set Filter Topology
open scoped ENNReal

namespace LQGMetric
namespace DZZ

open WhiteNoise QuantumZipper

variable {Ω : Type*} [MeasurableSpace Ω]

/-- **Similarity coupling of walled LGDs, uniform in the translation** (DZZ lem-scaling-coupling,
l. 611–624, with (eq-coupling-hat-h-eta-1/2) and Lemma 3.8 in the walled form
`dzz_lemma38_walled`): for `θ = simMap a b`, `‖a‖ ≤ 1`, `K ⊆ 𝕍^ξ` and `θ K ⊆ 𝕍^ξ`, there is a
coupling `(W₁, W₂)` of white noises such that, outside an event of probability `≤ C e^{−λ²/C}`,
for all `x, y ∈ K` and `δ > 0`,
`D^{θK}_{‖a‖ δ e^{λ}}(θx, θy)[W₂] ≤ D^{K}_δ(x, y)[W₁] ≤ D^{θK}_{‖a‖ δ e^{−λ}}(θx, θy)[W₂]`.
`C` depends on `(ξ, a)` only (DZZ: `C = C(ξ, κ₁, κ₂)`), not on `b`: this uniformity is what the
moving centres of `DZZL61PtBdry` need. -/
def DZZSimCoupleU (γ ξ : ℝ) (K : Set ℂ) (a : ℂ) : Prop :=
  ∃ C : ℝ, 0 < C ∧ ∀ b : ℂ, simMap a b '' K ⊆ dzzVXi ξ →
    ∃ (Ω' : Type) (_ : MeasurableSpace Ω') (P' : Measure Ω') (W₁ W₂ : WNSpace → Ω' → ℝ),
      IsWhiteNoise P' W₁ ∧ IsWhiteNoise P' W₂ ∧ ∀ lam : ℝ, 0 ≤ lam →
        P'.real {ω | ¬ ∀ x ∈ K, ∀ y ∈ K, ∀ δ : ℝ, 0 < δ →
          lgdDZZ (dzzWall (simMap a b '' K) (dzzMuIn γ W₂ ω)) (‖a‖ * δ * Real.exp lam)
              (simMap a b x) (simMap a b y) ≤
            lgdDZZ (dzzWall K (dzzMuIn γ W₁ ω)) δ x y ∧
          lgdDZZ (dzzWall K (dzzMuIn γ W₁ ω)) δ x y ≤
            lgdDZZ (dzzWall (simMap a b '' K) (dzzMuIn γ W₂ ω)) (‖a‖ * δ * Real.exp (-lam))
              (simMap a b x) (simMap a b y)} ≤ C * Real.exp (-lam ^ 2 / C)

/-- The eight symmetries of `𝕍 = [0,1]²` are generated by the reflection `x + iy ↦ (1 − x) + iy`
and the rotation by `π/2` about `1/2 + i/2`. -/
def dzzRefl (z : ℂ) : ℂ := ⟨1 - z.re, z.im⟩

def dzzRot (z : ℂ) : ℂ := Complex.I * (z - ⟨1 / 2, 1 / 2⟩) + ⟨1 / 2, 1 / 2⟩

/-- `g` is a symmetry of `𝕍`: a finite composition of `dzzRefl` and `dzzRot`. -/
inductive IsDzzSym : (ℂ → ℂ) → Prop
  | id : IsDzzSym id
  | refl {g} : IsDzzSym g → IsDzzSym (dzzRefl ∘ g)
  | rot {g} : IsDzzSym g → IsDzzSym (dzzRot ∘ g)

/-- **Exact invariance in law under the symmetries of `𝕍`** (DZZ (eq-translation-invariant),
l. 2271, and "by symmetry", l. 2555): for every symmetry `g` of `𝕍` the law of the rational ball
masses of `g_* M_{γ,η}` is the law of those of `M_{γ,η}` (the kernel `p_𝕍` is `g`-invariant, so
the η-field of the noise `W ∘ g` is the η-field of `W` composed with `g`, pathwise). The
consequence used: `P(E(D^{gK}(gx, gy))) = P(E(D^{K}(x, y)))` for events of countably many walled
LGD values, via `lgdDZZ_map_similarity` for isometries. -/
def DZZDihedralLaw (P : Measure Ω) (γ : ℝ) (W : WNSpace → Ω → ℝ) : Prop :=
  ∀ g : ℂ → ℂ, IsDzzSym g → ∀ S : Set (ℚ × ℚ → ℚ → ℝ≥0∞), MeasurableSet S →
    P {ω | ballMassQ ((dzzMuIn γ W ω).map g) ∈ S} = P {ω | ballMassQ (dzzMuIn γ W ω) ∈ S}

/-- **Big balls** (DZZ l. 2342 and 2562: "with high probability, balls intersecting both
`∂𝕍_{u,λ}` and `∂𝕍_{u,2λ}` have LQG measure larger than `2δ²`"), in the form used: every ball
of radius `≥ r` contained in `𝕍` has mass `> 2δ²`, with probability `→ 1` as `δ → 0`. -/
def DZZBigBalls (P : Measure Ω) (μ : Ω → Measure ℂ) (r : ℝ) : Prop :=
  Tendsto (fun δ : ℝ => P {ω | ¬ ∀ (x : ℂ) (ρ : ℝ), r ≤ ρ → Metric.ball x ρ ⊆ dzzV →
    ENNReal.ofReal (2 * δ ^ 2) < μ ω (Metric.ball x ρ)}) (𝓝[>] 0) (𝓝 0)

/-- The DEC-117 region of the leg from `u` to a segment `L ⊆ ∂𝕍_{u,λ}`: `𝕍_{u,λ} ∪ N_{λ/2}(L)`
(the stadium form; superseded by `legWall` in D123, kept for the truncation proof of S5L54F3). -/
def legWallC (u : ℂ) (l : ℝ) (L : Set ℂ) : Set ℂ :=
  sqBox u l ∪ Metric.cthickening (l / 2) L

/-- The four sides of `∂𝕍_{c,a}` (bottom, left, top, right; the order of `bdrySeg`). -/
def sqSide (c : ℂ) (a : ℝ) : Fin 4 → Set ℂ :=
  ![Icc (c.re - a / 2) (c.re + a / 2) ×ℂ {c.im - a / 2},
    {c.re - a / 2} ×ℂ Icc (c.im - a / 2) (c.im + a / 2),
    Icc (c.re - a / 2) (c.re + a / 2) ×ℂ {c.im + a / 2},
    {c.re + a / 2} ×ℂ Icc (c.im - a / 2) (c.im + a / 2)]

/-- The outward unit direction of the `j`-th side. -/
def legDir : Fin 4 → ℂ := ![-Complex.I, -1, Complex.I, 1]

/-- **The leg wall of D123** for a segment on the `j`-th side of `∂𝕍_{u,l}`: the axis-parallel
square `𝕍_{u + (l/2) e_j, 2l} = 𝕍_{u,2l} ∩ 𝕍̃_{u, u + l e_j}`, i.e. the tilde box of the pair
`(u, v)`, `v = u + l e_j`, the point of the contradiction of DZZ l. 2553–2568 facing that side. A
chain of balls in it is both a `D̄^{u,2l}`-chain and a `D̃(u,v)`-chain (DEC-117 §2(a)(ii)). -/
def legSq (u : ℂ) (l : ℝ) (j : Fin 4) : Set ℂ :=
  sqBox (u + (l / 2 : ℝ) * legDir j) (2 * l)

open Classical in
/-- **The leg wall** (D123, replacing DEC-117's stadium `legWallC`): `legSq u l j` for `L` on the
`j`-th side of `∂𝕍_{u,l}` (the first such `j`), and DZZ's own wall `𝕍_{u,2l}` otherwise. Every
value is an axis-parallel closed square of side `2l` containing `𝕍_{u,l}`, and `legWallC ⊆ legWall`
(S5D123), so the DEC-117 truncation transfers by monotonicity. -/
def legWall (u : ℂ) (l : ℝ) (L : Set ℂ) : Set ℂ :=
  if h : ∃ j, L ⊆ sqSide u l j then legSq u l (Classical.choose h) else sqBox u (2 * l)

/-- **(eq-point-to-segment), corrected** (DZZ l. 2559; DEC-117 §2(a)): for `u ∈ 𝕍̄`, `λ = 1/20`,
there are `ι₀ > 0` and `K > 0` (`K χ ≥ 2`) such that for `ι < ι₀` and small `δ`, for every
segment `L ⊆ ∂𝕍_{u,λ}` of length in `[δ^{Kι}/2, δ^{Kι}]`,
`E log min_{x ∈ L} D^{legWall}_δ(u, x) ≥ (χ − 2ι) log δ⁻¹`.
On `DZZBigBalls` at `r = λ/4`, `min_{∂𝕍_{u,λ}} D̄^{u,2λ}(u,·) ≥ min_L min_{x∈L} D^{legWall}(u,x)`
((eq-geodesic-range) argument), which is what the union bound `dzzLem54_lower` needs. -/
def DZZLem54SegQ (P : Measure Ω) (μ : Ω → Measure ℂ) (χ : ℝ) : Prop :=
  ∀ u ∈ dzzVbar, ∃ ι₀ K : ℝ, 0 < ι₀ ∧ 0 < K ∧ 2 ≤ K * χ ∧ ∀ ι ∈ Ioo (0 : ℝ) ι₀,
    ∀ᶠ δ in 𝓝[>] (0 : ℝ), ∀ L : Set ℂ, IsBdrySeg u (1 / 20) (δ ^ (K * ι)) L →
      (χ - 2 * ι) * Real.log δ⁻¹ ≤
        ∫ ω, logMinLGD (dzzWall (legWall u (1 / 20) L) (μ ω)) δ {u} L ∂P

/-- **`DZZL61Glue` with the segment length `δ^κ`** (DZZ l. 2605; DEC-117 §2(c)): the four short
crossings around `L_δ` cost `O(D̃_δ)` at scale `|L_δ| = δ^κ`, i.e. `δ^{−χ(1−κ)+o(1)}`, which is
`≤ δ^{−(χ−ι)}` when `κ χ ≥ 2ι`. The original `DZZL61Glue` is the case `κ = 2ι`, valid only for
`χ ≥ 1/2`. -/
def DZZL61GlueK (P : Measure Ω) (μ : Ω → Measure ℂ) (α χ : ℝ) (u : ℂ) (ι κ : ℝ) : Prop :=
  ∀ (L : ℝ → Set ℂ) (v : ℝ → ℂ),
    (∀ᶠ δ in 𝓝[>] (0 : ℝ), IsBdrySeg u (α / 20) (δ ^ κ) (L δ) ∧ v δ ∈ L δ) →
    Tendsto (fun δ => P {ω | ¬ ((lgdMinSet (μ ω) δ {v δ} (frontier (sqBox u (1 / 20))) : ℝ≥0∞) ≤
      (lgdMinSet (μ ω) δ (L δ) (frontier (sqBox u (1 / 20))) : ℝ≥0∞) +
        ENNReal.ofReal (δ ^ (-(χ - ι))))}) (𝓝[>] 0) (𝓝 0)

end DZZ
end LQGMetric
