import QuantumZipper.Proofs.RS.Generation
import QuantumZipper.Proofs.Loewner.CaraRZ

/-!
# EXT-RS node GEN, corollaries GEN-a, GEN-b, GEN-c

Blueprint `blueprint/EXT_RS_BLUEPRINT.md` §3, node **GEN** (task RS-GEN). Standing hypotheses
(those of `gen_no_path`): `W` continuous, `W 0 = 0`, `t ≥ 0`, radial limits
`f̂_s(iy) → trace W s` uniform in `s ∈ [0,t]`, `trace W` continuous on `[0,t]`;
`A = trace W '' [0,t]`, `K_t = fwdHull W t`, `H_t = H \ K_t`.

* `exists_ball_subset_fwdHull_of_not_mem`: every point of `K_t \ A` is interior to `K_t`.
* **GEN-b** `frontier_compl_fwdHull_inter_H_subset`: `frontier H_t ∩ H ⊆ A`.
* **GEN-c** `fwdHull_subset_trace_image_of_interior_eq_empty`: `interior K_t = ∅ → K_t ⊆ A`.
* **GEN-a** `compl_fwdHull_eq_connectedComponentIn` (for any base point of `H_t`) and
  `exists_compl_fwdHull_eq_connectedComponentIn_mul_I` (base point `M i`, `M` large):
  `H_t` is the connected component of `H \ A` containing the points `M i` near `∞`, i.e. the
  hulls are generated by the trace (Kemppainen, Def. 5.3, p. 76).

Sources: Rohde–Schramm (2005), Thm 4.1 and its proof (pp. 19–20: "`H_t` is connected and
disjoint from ...; `∂H_t ∩ H` is contained in ...; therefore `H_t` is a connected component");
Kemppainen (2017) Thm 6.4 and Cor 6.2 (pp. 109–110); Lawler (2005) Prop 4.28 (pp. 87–88). The
key input `gen_no_path` is the own adaptation recorded in `Generation.lean`. The topological
deductions below are elementary.
-/

noncomputable section

open Set Filter Topology Metric Complex

namespace QuantumZipper
namespace RS

variable {W : ℝ → ℝ} {t : ℝ}

/-- Every point of `K_t` off the trace is an interior point of `K_t` (from `gen_no_path`, with
a segment inside a ball of `H \ A`). -/
theorem exists_ball_subset_fwdHull_of_not_mem (hW : Continuous W) (hW0 : W 0 = 0) (ht : 0 ≤ t)
    (hunif : TendstoUniformlyOn (fun (y : ℝ) (s : ℝ) => fwdMapInv W s (y * I)) (trace W)
      (𝓝[>] 0) (Icc 0 t))
    (hcont : ContinuousOn (trace W) (Icc 0 t)) {z : ℂ} (hz : z ∈ fwdHull W t)
    (hzA : z ∉ trace W '' Icc 0 t) : ∃ ρ > 0, ball z ρ ⊆ fwdHull W t := by
  have hAc : IsCompact (trace W '' Icc 0 t) := isCompact_Icc.image_of_continuousOn hcont
  have hopen : IsOpen (H \ trace W '' Icc 0 t) := isOpen_H.sdiff hAc.isClosed
  obtain ⟨ρ, hρ, hball⟩ := Metric.isOpen_iff.1 hopen z ⟨fwdHull_mono.2 t hz, hzA⟩
  refine ⟨ρ, hρ, fun q hq => ?_⟩
  by_contra hqK
  have hj : JoinedIn (ball z ρ) z q :=
    ((convex_ball z ρ).isPathConnected ⟨z, mem_ball_self hρ⟩).joinedIn z (mem_ball_self hρ) q hq
  exact gen_no_path hW hW0 ht hunif hcont hz ⟨(hball hq).1, hqK⟩ hj.somePath
    fun u => hball (hj.somePath_mem u)

/-- **GEN-b.** `frontier H_t ∩ H ⊆ trace W '' [0,t]`. -/
theorem frontier_compl_fwdHull_inter_H_subset (hW : Continuous W) (hW0 : W 0 = 0) (ht : 0 ≤ t)
    (hunif : TendstoUniformlyOn (fun (y : ℝ) (s : ℝ) => fwdMapInv W s (y * I)) (trace W)
      (𝓝[>] 0) (Icc 0 t))
    (hcont : ContinuousOn (trace W) (Icc 0 t)) :
    frontier (H \ fwdHull W t) ∩ H ⊆ trace W '' Icc 0 t := by
  rintro z ⟨hzf, hzH⟩
  by_contra hzA
  have hopen := FwdHolo.isOpen_compl_fwdHull hW ht
  have hzK : z ∈ fwdHull W t := by
    by_contra hzK
    have : z ∈ (H \ fwdHull W t) ∩ frontier (H \ fwdHull W t) := ⟨⟨hzH, hzK⟩, hzf⟩
    rwa [hopen.inter_frontier_eq] at this
  obtain ⟨ρ, hρ, hball⟩ := exists_ball_subset_fwdHull_of_not_mem hW hW0 ht hunif hcont hzK hzA
  obtain ⟨b, hb, hzb⟩ := Metric.mem_closure_iff.1 (frontier_subset_closure hzf) ρ hρ
  exact hb.2 (hball (by rw [mem_ball, dist_comm]; exact hzb))

/-- **GEN-c.** If `K_t` has empty interior, then `K_t ⊆ trace W '' [0,t]`. -/
theorem fwdHull_subset_trace_image_of_interior_eq_empty (hW : Continuous W) (hW0 : W 0 = 0)
    (ht : 0 ≤ t)
    (hunif : TendstoUniformlyOn (fun (y : ℝ) (s : ℝ) => fwdMapInv W s (y * I)) (trace W)
      (𝓝[>] 0) (Icc 0 t))
    (hcont : ContinuousOn (trace W) (Icc 0 t)) (hint : interior (fwdHull W t) = ∅) :
    fwdHull W t ⊆ trace W '' Icc 0 t := by
  intro z hz
  by_contra hzA
  obtain ⟨ρ, hρ, hball⟩ := exists_ball_subset_fwdHull_of_not_mem hW hW0 ht hunif hcont hz hzA
  have : z ∈ interior (fwdHull W t) :=
    mem_interior_iff_mem_nhds.2 (Filter.mem_of_superset (ball_mem_nhds z hρ) hball)
  rw [hint] at this
  exact this

/-- `H_t` avoids the trace: `H \ K_t ⊆ H \ trace W '' [0,t]` (TR5). -/
theorem compl_fwdHull_subset_compl_trace (hW : Continuous W) (hW0 : W 0 = 0)
    (hunif : TendstoUniformlyOn (fun (y : ℝ) (s : ℝ) => fwdMapInv W s (y * I)) (trace W)
      (𝓝[>] 0) (Icc 0 t)) :
    H \ fwdHull W t ⊆ H \ trace W '' Icc 0 t := by
  rintro z ⟨hzH, hzK⟩
  refine ⟨hzH, ?_⟩
  rintro ⟨s, hs, rfl⟩
  rcases trace_mem_fwdHull_or_real hW hW0 hs.1 (hunif.tendsto_at hs) with h | h
  · exact hzK (fwdHull_mono.1 hs.2 h)
  · exact (ne_of_gt (show (0 : ℝ) < (trace W s).im from hzH)) h

/-- `H_t` is preconnected: it is the image of `H` under the continuous map `f̂_t`. -/
theorem isPreconnected_compl_fwdHull (hW : Continuous W) (hW0 : W 0 = 0) (ht : 0 ≤ t) :
    IsPreconnected (H \ fwdHull W t) := by
  rw [← image_fwdMapInv_H hW hW0 ht]
  have hH : IsPreconnected H :=
    (convex_halfSpace_gt (f := Complex.im) Complex.imLm.isLinear (0 : ℝ)).isPreconnected
  exact hH.image _ fun z hz => (continuousAt_fwdMapInv hW hW0 ht hz).continuousWithinAt

/-- **GEN-a, general base point.** For every `x ∈ H_t`, `H_t` is the connected component of
`H \ trace W '' [0,t]` containing `x`. -/
theorem compl_fwdHull_eq_connectedComponentIn (hW : Continuous W) (hW0 : W 0 = 0) (ht : 0 ≤ t)
    (hunif : TendstoUniformlyOn (fun (y : ℝ) (s : ℝ) => fwdMapInv W s (y * I)) (trace W)
      (𝓝[>] 0) (Icc 0 t))
    (hcont : ContinuousOn (trace W) (Icc 0 t)) {x : ℂ} (hx : x ∈ H \ fwdHull W t) :
    H \ fwdHull W t = connectedComponentIn (H \ trace W '' Icc 0 t) x := by
  have hsub := compl_fwdHull_subset_compl_trace hW hW0 hunif
  refine subset_antisymm
    ((isPreconnected_compl_fwdHull hW hW0 ht).subset_connectedComponentIn hx hsub) ?_
  intro y hy
  have hAc : IsCompact (trace W '' Icc 0 t) := isCompact_Icc.image_of_continuousOn hcont
  have hopen : IsOpen (H \ trace W '' Icc 0 t) := isOpen_H.sdiff hAc.isClosed
  have hCo : IsOpen (connectedComponentIn (H \ trace W '' Icc 0 t) x) :=
    hopen.connectedComponentIn
  have hCc : IsConnected (connectedComponentIn (H \ trace W '' Icc 0 t) x) :=
    isConnected_connectedComponentIn_iff.2 (hsub hx)
  have hCp := (hCo.isConnected_iff_isPathConnected).1 hCc
  have hyH : y ∈ H := (connectedComponentIn_subset _ _ hy).1
  refine ⟨hyH, fun hyK => ?_⟩
  have hj := hCp.joinedIn y hy x (mem_connectedComponentIn (hsub hx))
  exact gen_no_path hW hW0 ht hunif hcont hyK hx hj.somePath
    fun u => connectedComponentIn_subset _ _ (hj.somePath_mem u)

/-- **GEN-a.** For all large `M`, the point `M i` lies in `H_t`, and `H_t` is the connected
component of `H \ trace W '' [0,t]` containing `M i` (the unbounded component: the hulls are
generated by the trace). -/
theorem exists_compl_fwdHull_eq_connectedComponentIn_mul_I (hW : Continuous W) (hW0 : W 0 = 0)
    (ht : 0 ≤ t)
    (hunif : TendstoUniformlyOn (fun (y : ℝ) (s : ℝ) => fwdMapInv W s (y * I)) (trace W)
      (𝓝[>] 0) (Icc 0 t))
    (hcont : ContinuousOn (trace W) (Icc 0 t)) :
    ∃ M₀ : ℝ, ∀ M : ℝ, M₀ ≤ M → (M : ℂ) * I ∈ H \ fwdHull W t ∧
      H \ fwdHull W t = connectedComponentIn (H \ trace W '' Icc 0 t) ((M : ℂ) * I) := by
  obtain ⟨B, hB⟩ :=
    isCompact_Icc.exists_bound_of_continuousOn (hW.continuousOn (s := Icc 0 (t + 1)))
  have hB' : ∀ r ∈ Icc (0 : ℝ) (t + 1), |W r| ≤ B := fun r hr => by
    simpa [Real.norm_eq_abs] using hB r hr
  have hK := CaraR.fwdHull_subset_closedBall hW (by linarith : (0 : ℝ) < t + 1) hB'
  refine ⟨|B + 3 * Real.sqrt (t + 1)| + 1, fun M hM => ?_⟩
  have hM0 : 0 < M := lt_of_lt_of_le (by positivity) hM
  have hmem : (M : ℂ) * I ∈ H \ fwdHull W t := by
    refine ⟨show 0 < ((M : ℂ) * I).im by simpa using hM0, fun hMK => ?_⟩
    have h1 := mem_closedBall_zero_iff.1 (hK (fwdHull_mono.1 (by linarith) hMK))
    rw [norm_mul, norm_I, mul_one, norm_real, Real.norm_eq_abs, abs_of_pos hM0] at h1
    linarith [le_abs_self (B + 3 * Real.sqrt (t + 1))]
  exact ⟨hmem, compl_fwdHull_eq_connectedComponentIn hW hW0 ht hunif hcont hmem⟩

/-- **Bridge from the TR3/TR4 bound.** A radial bound `‖f̂_s(iy) − trace W s‖ ≤ C y^δ`
(`δ > 0`) on `[0,t] × (0,1]` (the shape of `trace_of_radialBound` and `ae_sleTrace_good`)
gives the uniform radial convergence hypothesis of `gen_no_path`. -/
theorem tendstoUniformlyOn_fwdMapInv_mul_I_of_bound {C δ : ℝ} (hδ : 0 < δ)
    (h : ∀ s ∈ Icc 0 t, ∀ y ∈ Ioc (0 : ℝ) 1, ‖fwdMapInv W s (y * I) - trace W s‖ ≤ C * y ^ δ) :
    TendstoUniformlyOn (fun (y : ℝ) (s : ℝ) => fwdMapInv W s (y * I)) (trace W)
      (𝓝[>] 0) (Icc 0 t) := by
  rw [Metric.tendstoUniformlyOn_iff]
  intro ε hε
  obtain ⟨y₁, hy₁, hlt⟩ := exists_mul_rpow_lt (K := |C|) hδ hε
  filter_upwards [Ioc_mem_nhdsGT_zero hy₁.1] with y hy s hs
  rw [dist_comm, dist_eq_norm]
  have hyδ : y ^ δ ≤ y₁ ^ δ := Real.rpow_le_rpow hy.1.le hy.2 hδ.le
  calc ‖fwdMapInv W s (y * I) - trace W s‖ ≤ C * y ^ δ := h s hs y ⟨hy.1, hy.2.trans hy₁.2⟩
    _ ≤ |C| * y ^ δ := mul_le_mul_of_nonneg_right (le_abs_self C) (Real.rpow_nonneg hy.1.le δ)
    _ ≤ |C| * y₁ ^ δ := mul_le_mul_of_nonneg_left hyδ (abs_nonneg C)
    _ < ε := hlt

end RS
end QuantumZipper
